hashintel/hash

resources/docs/simulation/tutorials/phase-1-building-a-simple-hotelling-model-in-2d/initialization.md
I hope I found the right page. The old one was moved. 
Also I wasn't sure if the emphasis was needed so I removed the bold-markers.
Let me know if I should change something.
=> fix dead link and markup issues

resources/docs/simulation/creating-simulations/datasets/README.md
I believe there is a typo on line 50 and have updated it.
I am new to contributing to open-source projects, so I hope this change is not too small, but I can see someone running into issues if they were to copy and paste directly from your documentation.
=> Updated a ")" typo to a "]"

packages/engine/README.md
[Asana task](https://app.asana.com/0/0/1201494000207954)
=> Split dependency section into required and optional

packages/engine/README.md
[Asana task](https://app.asana.com/0/1199550852792314/1201486809262027/f)
=> Add quick-start section

packages/engine/src/output/buffer/part.rs, packages/engine/src/output/local/sim.rs
As title says, outputs were missing closing "]"
=> Fixing a bug where JSON state output wasn't finalized / terminated

packages/engine/bin/cli/src/manifest.rs
Sugarscape's simple experiment wasn't working. 
(`run --bin cli  -- -p "sugarscape" simple --experiment-name "agent_density_linspace"`)
This was caused by two things
* There was a division by 0 if the number of samples was 1
* We incorrectly parsed the ChangedProperties of the experiments
This PR fixes both of those idenfitied problem. It's not a claim that all simple experiments will now work, in fact this experiment of Sugarscape runs for many steps and then reaches a point where it will hang infinitely.
This has an asana task to track: https://app.asana.com/0/1199550852792314/1201499989227954/f
=> Fixing a bug in how changedProperties are parsed, and / by 0 in linspacevariant

packages/engine/src/output/local/sim.rs
Removes an unneeded clone
- ✅ Clippy
=> Remove unneeded clone in output

packages/engine/src/datastore/arrow/batch_conversion.rs, packages/engine/src/datastore/schema/field_spec/accessor.rs, packages/engine/src/datastore/schema/field_spec/creator.rs, packages/engine/src/datastore/schema/field_spec/mod.rs
Improves documentation
- [Asana task description](https://app.asana.com/0/1199550852792314/1201503366718084/f)
=> Improve Docstrings for `FieldKey` and `RootFieldSpecCreator`

.github/workflows/rust-lints.yml
- Fix rustfmt not annotating when multiple crate are not properly formatted
- Fix clippy not annotating at all
- [Asana task description](https://app.asana.com/0/1199550852792314/1201481504728214/f)
- CI searches for all crates
- Rustfmt is executed per crate
- Use a fork of action-rs/clippy-check which supports multiple workspaces
- ✅ GitHub Actions
=> Fix Rust annotations

.github/workflows/rust-lints.yml, packages/engine/rust-toolchain.toml, packages/engine/src/worker/runner/python/setup.py
=> Updating nightly version

packages/engine/bin/cli/src/experiment.rs, packages/engine/src/experiment/controller/controller.rs, packages/engine/src/proto.rs, packages/engine/src/worker/mod.rs, packages/engine/src/worker/runner/comms/outbound.rs, packages/engine/src/worker/runner/javascript/mod.rs, packages/engine/src/workerpool/comms/mod.rs, packages/engine/src/workerpool/comms/top.rs, packages/engine/src/workerpool/mod.rs
In order to see `console.log` from behaviors, they are now send to the CLI to be printed.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201524950327098/f)
1. Run an experiment with `console.log` functions
2. Watch the output
=> Enable logging from JS behaviors

packages/engine/README.md
Behaviors are accompanied by a .json file that defines the types of the fields used within the behavior. This needs to be described in the README.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201494000207946/f)
=> Add description for behavior-keys file to README

.github/workflows/rust-lints.yml
Reverts and fixes #104 
- [Asana task description](https://app.asana.com/0/1199550852792314/1201531032484627/f)
=> Only run lints when in `packages/engine`

packages/engine/src/worker/runner/javascript/state.js
Messages were being incorrectly serialized in the JS runner, this fixes it.
- [Asana task description](https://app.asana.com/0/0/1201532662164419/f)
- We previously were trying to be efficient by only deserializing messages when we needed them. To do this we kept track of if the message had been converted to a native (i.e. JS object) message already. The functionality was broken however and we were trying to deserialize already deserialized data. This PR removes the native flags, and instead we deserialize all messages at the start, and serialize them all at the end. 
- It also adds a TODO to revisit this.
- ✅ Manual Tests (Errors no longer appear and Sugarscape and Warehouse Logistics sims work)
=> Fixing message serialization in JS runner

resources/docs/simulation/creating-simulations/libraries/hash/agent.md, resources/docs/simulation/creating-simulations/libraries/hash/init.md, resources/docs/simulation/creating-simulations/libraries/hash/neighbors.md, resources/docs/simulation/creating-simulations/libraries/hash/random.md, resources/docs/simulation/creating-simulations/libraries/hash/spatial.md
Merging in the python examples for hash_stdlib docs
=> Python examples for hstd

packages/engine/src/config/topology.rs, packages/engine/src/hash_types/state.rs, packages/engine/src/simulation/package/context/packages/neighbors/adjacency.rs, packages/engine/src/simulation/package/context/packages/neighbors/mod.rs, packages/engine/src/simulation/package/state/packages/topology/adjacency.rs, packages/engine/src/simulation/package/state/packages/topology/mod.rs
Rewrites the topology configuration:
- Adds warnings when fallback values are used
- Adds warnings if unknown keys are provided
- support +/-inf for bounds
- [Asana task description](https://app.asana.com/0/1199550852792314/1201532423341532/f)
- ✅ Unit Tests
=> Rewrite topology configuration

packages/engine/CONTRIBUTING.md
Give a better description on how to use `clippy` and `rustfmt`
- [Asana task description](https://app.asana.com/0/1199550852792314/1201507052344929/f)
=> Add Rust linting instruction to CONTRIBUTING.md

.github/workflows/rust-lints.yml
Rust Ci was not running
- [Asana task description](https://app.asana.com/0/1199550852792314/1201545236176385/f)
- ✅ GitHub Actions
=> Fix Rust CI not running

.github/workflows/rust.yml, packages/engine/src/datastore/arrow/field_conversion.rs, packages/engine/src/datastore/batch/migration/mod.rs, packages/engine/src/datastore/mod.rs, packages/engine/src/simulation/enum_dispatch.rs, packages/engine/src/simulation/task/msg.rs, packages/engine/src/worker/runner/javascript/mini_v8/tests/function.rs, packages/engine/src/worker/runner/javascript/mini_v8/tests/mini_v8.rs
Ignore currently failing tests and enable GitHub Actions for testing.
- [Comment out failing unit tests](https://app.asana.com/0/1199550852792314/1201545236176397/f)
- [Add GH Actions for Unit testing](https://app.asana.com/0/1199550852792314/1201546500237297/f)
- ✅ Unit Tests
=> Add Rust tests to GitHub Actions

.github/labeler.yml, .github/workflows/labeler.yml
Automatically applies labels for hEngine, HASH, stdlib and learn.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201533886101111/f)
=> Add labeler Action

.github/labeler.yml, .github/workflows/rust.yml
- Fix Copy/Paste error in #127
- Fix Copy/Paste error in #128 (Clippy is not needed in a test run)
=> Fix copy/paste errors

packages/engine/Cargo.lock, packages/engine/Cargo.toml, packages/engine/bin/cli/Cargo.toml, packages/engine/bin/cli/src/experiment.rs, packages/engine/bin/cli/src/main.rs, packages/engine/src/args.rs
Upgrade `clap` to version 3, which comes with a bunch of new built-in features.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201487105179315/f)
- [Clap repository](https://github.com/clap-rs/clap)
=> Upgrade Clap to v3

packages/engine/src/simulation/package/context/packages/agent_messages/package.py
Python init PR #5
- [Asana task description](https://app.asana.com/0/0/1201539039235286/f)
* Fixes syntax
1. Run any experiment.
2. Python should get through messages package init and reach NewSimulationRun message handling
=> Fix messages package Python component init

packages/engine/Cargo.lock, packages/engine/bin/server/Cargo.toml, packages/engine/bin/server/src/main.rs
Apply the new error handling library to the CLI
- [Asana task description](https://app.asana.com/0/1199550852792314/1201629001641125/f)
It replaces `anyhow` in our CLI service
=> Apply error library to server binary

packages/engine/Cargo.lock, packages/engine/bin/cli/Cargo.toml, packages/engine/bin/cli/src/experiment.rs, packages/engine/bin/cli/src/exsrv.rs, packages/engine/bin/cli/src/main.rs, packages/engine/bin/cli/src/manifest.rs, packages/engine/bin/cli/src/process/local.rs, packages/engine/bin/cli/src/process/process.rs
Apply the new error handling library to the CLI
- [Asana task description](https://app.asana.com/0/1199550852792314/1201629001641121/f)
It replaces `anyhow` in our CLI service
=> Apply error library to CLI

packages/engine/src/datastore/arrow/batch_conversion.rs, packages/engine/src/datastore/mod.rs, packages/engine/src/datastore/schema/field_spec/mod.rs, packages/engine/src/datastore/table/context/mod.rs, packages/engine/src/datastore/table/pool/agent.rs, packages/engine/src/datastore/table/pool/message.rs, packages/engine/src/datastore/table/pool/mod.rs, packages/engine/src/datastore/table/state/mod.rs, packages/engine/src/datastore/table/task_shared_store.rs, packages/engine/src/hash_types/state.rs, packages/engine/src/proto.rs, packages/engine/src/simulation/command.rs, packages/engine/src/simulation/comms/mod.rs, packages/engine/src/simulation/controller/run.rs, packages/engine/src/simulation/engine.rs, packages/engine/src/simulation/package/context/mod.rs, packages/engine/src/simulation/package/init/mod.rs, packages/engine/src/simulation/package/run.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/mod.rs, packages/engine/src/worker/mod.rs, packages/engine/src/worker/runner/comms/inbound.rs, packages/engine/src/worker/runner/javascript/mod.rs, packages/engine/src/worker/runner/mod.rs, packages/engine/src/workerpool/mod.rs
Adds a large suite of `TODO: DOC` comments to track areas of improvement over the next weeks
=> Documentation TODOs

packages/engine/src/output/local/sim.rs
=> Fixes typo

.github/pull_request_template_.md
Introduces a PR template in order to standardise descriptions and:
- making it easier to write them
- making it easier to read them
- make it more likely that useful topics are covered
None.
See how this goes and refine it as needed.
- [Slack thread](https://hashintel.slack.com/archives/CM3JJMYRL/p1641813925004500) (_internal_)
This PR is the demo.
=> [TOOL] Add PR template

LICENSE.md, packages/engine/LICENSE.md, resources/LICENSE.md
Further improvements to the root `LICENSE.md` file to improve clarity and address outstanding questions re: the use of mixed licenses in the monorepo.
=> Further LICENSE updates

.github/pull_request_template.md, .markdownlint.json, README.md, packages/engine/README.md
Follows #159 
[GitHub docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
=> Rename `pull_request_template.yml`, tweak Markdownlint config

packages/engine/lib/orchestrator/src/manifest.rs
Dependencies tried to read initial states, this PR fixes this.
- The integration tests suite tests the CLI for projects without dependencies
- Manually runs where done for projects with dependencies
- Run `cargo test` for automated test suite
- Run other projects with `cargo run -p cli` (See command line instructions for details)
=> Fix dependencies tries to load initial states

packages/blocks/header/src/App.tsx, packages/blocks/header/variants.json, packages/hash/api/src/collab/Instance.ts, packages/hash/frontend/src/blocks/page/BlockView.tsx, packages/hash/frontend/src/blocks/page/ComponentView.tsx, packages/hash/frontend/src/blocks/page/createSuggester/createSuggester.tsx, packages/hash/shared/src/ProsemirrorSchemaManager.ts, packages/hash/shared/src/entity.ts, packages/hash/shared/src/entityStore.ts, packages/hash/shared/src/entityStorePlugin.ts, packages/hash/shared/src/queries/entity.queries.ts, packages/hash/shared/src/queries/page.queries.ts, packages/hash/shared/src/save.ts, packages/hash/shared/src/util.ts
This pull request allows you to set variant properties on text and non-text blocks using the block selector, feeding from `variants.json`. If setting on text, it will create a "variant" entity which will be linked to the underlying text entity in order to store these properties (and will create the necessary entity type for this). 
**Description incoming**
This is a new feature, but I don't think we have UI docs, and this is integrating `variants.json` which is a feature which exists in the docs. 
- [**\[ASANA\]** Fix switching variant](https://app.asana.com/0/1200211978612931/1200972693311572/f) (_internal_)
None
Try switching between different blocks of different types with different variants. You'll need to point the editor at a local copy of the header block for this. …
=> [FE] [BE] [COLLAB] Block variants

packages/engine/src/datastore/arrow/ipc.rs, packages/engine/src/datastore/batch/message.rs, packages/engine/src/datastore/error.rs, packages/engine/src/datastore/mod.rs, packages/engine/src/datastore/shared_store.rs, packages/engine/src/datastore/store.rs, packages/engine/src/datastore/table/context/mod.rs, packages/engine/src/datastore/table/mod.rs, packages/engine/src/datastore/table/pool/agent.rs, packages/engine/src/datastore/table/pool/message.rs, packages/engine/src/datastore/table/pool/mod.rs, packages/engine/src/datastore/table/pool/proxy.rs, packages/engine/src/datastore/table/proxy.rs, packages/engine/src/datastore/table/state/create_remove/planner.rs, packages/engine/src/datastore/table/state/mod.rs, packages/engine/src/datastore/table/state/view.rs, packages/engine/src/simulation/engine.rs, packages/engine/src/simulation/package/context/packages/agent_messages/mod.rs, packages/engine/src/simulation/package/context/packages/api_requests/mod.rs, packages/engine/src/simulation/package/context/packages/neighbors/mod.rs, packages/engine/src/simulation/package/mod.rs, packages/engine/src/simulation/package/output/packages/analysis/mod.rs, packages/engine/src/simulation/package/output/packages/json_state/mod.rs, packages/engine/src/simulation/package/run.rs, packages/engine/src/simulation/package/state/mod.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/chain.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/mod.rs, packages/engine/src/simulation/package/state/packages/topology/mod.rs, packages/engine/src/worker/runner/python/sender.rs
Generally improves documentation around the Datastore, with some added drivebys
See the TODOs in the changes
See the TODOs in the changes
Self-explanatory
- [Asana task](https://app.asana.com/0/1201481007343159/1201712695072972/f) (_internal_)
No doc-tests as of yet
=> [ENGINE] Doc Improvements

packages/engine/src/utils.rs
#241 added the possibility to specify a log folder, but the texray-generation wasn't affected. This PR fixes this.
=> [ENGINE] Use log-folder passed to the orchestrator for texray generation

packages/engine/tests/units/experiment.rs
Fixes integration test suite broken by #256
Make sure the test suite is executed every time the engine is changed.
=> [ENGINE] Fix integration test suite

.github/workflows/rust.yml, packages/engine/tests/experiment/mod.rs
Uploads data generated in #261 to datadog
- [Asana task](https://app.asana.com/0/1201707629991362/1201762844341059/f) (_internal_)
- [Datadog API](https://docs.datadoghq.com/api/latest/logs/)
=> Upload timings to datadog

.github/pull_request_template.md
Every section has a badge, let's add one for the docs-section 🙂 
Someone may not like scrolls 🙁 
[Rendered](https://github.com/hashintel/hash/blob/8af83256bd1f092f8196db0192994e8193b94cad/.github/pull_request_template.md)
=> Add 📜  to docs-section in PR template

packages/engine/tests/experiment/mod.rs
When tests are running and passing, we don't want logging output.
- Uses [`TestWriter`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/struct.TestWriter.html) for tests to only output on errors
- Properly print the test results on failure
- [Asana task](https://app.asana.com/0/1201793759102797/1201826830638652/f) (_internal_)
=> Hide logging output from tests if not failing

packages/hash/shared/src/blockPaths.json
This PR completes work on the callout block. It follows #308 and https://github.com/blockprotocol/blockprotocol/pull/222 – see those PRs for details.
=> Add callout to `blockPaths.json`

packages/hash/README.md
Adds a few pointers to the HASH `README.md` to better cover (a) the current state and long-term plans, and (b) help block authors use it as a test playground.
[Preview](https://github.com/hashintel/hash/blob/81395f4b8930e6a279e26ccbb4116d7859ca5a1b/packages/hash/README.md)
[[internal task link]](https://app.asana.com/0/1200211978612931/1201472293975867/f)
=> Update HASH README.md

CONTRIBUTING.md
Add some general principles / guidance to the root `CONTRIBUTING.md`.
[[internal task](https://app.asana.com/0/1201637128042639/1201656027079616/f)]
=> Add common contribution processes

packages/engine/src/worker/runner/javascript/mod.rs
When generating a fixed-size list in JS, the child data does not necessarily contain all values if not needed. This PR takes this into account when converting to an arrow-rs `Array`
Changes the way, the validity map is read. Considering the fixed-size list `[null, [1, 2, 3], null]`, JS generates a null-map for the child array only for the first two entries, thus a length of `6`. To translate this into Rust, we:
- Create a buffer with the `target_len` (`9` in this case)
- Reads `6` bits into the array (`111000`)
- Grows the validity map to `9` (resulting in `000111000`, resizing always is appending `0`s)
- Adjust the `null_count` from `3` to `3 + 9 - 6 = 6`
No
- [Asana task](https://app.asana.com/0/1201893074552404/1201893568192898/f) (_internal_)
- Closes #357 
- #356
=> Fix Arrow conversion from JS with fixed-size lists

packages/hash/api/src/db/adapter.ts, packages/hash/api/src/db/postgres/client.ts, packages/hash/api/src/db/postgres/entitytypes.ts, packages/hash/api/src/db/postgres/index.ts, packages/hash/api/src/graphql/resolvers/entityType/entityTypeInheritance.ts, packages/hash/api/src/graphql/resolvers/entityType/updateEntityType.ts, packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/lib/schemas/jsonSchema.ts, packages/hash/api/src/model/entityType.model.ts, packages/hash/integration/src/mockData/entityTypes.ts
This PR moves around some implementation-details for creating EntityTypes.
Before this PR, the `EntityType` JSON Schema was validated in the database client, creating a `jsonSchemaCompiler` dependency.
In this PR, the JSON Schema validation happens from the `EntityType` model class, so that the database client doesn't need to use the `jsonSchemaCompiler`.
These changes also prompted a couple changes to the inheritance field resolver (stylistic choice).
We will now have a more centralized location to do JSON schema validation as well.
- To implement better inheritance chain resolving see [asana task](https://app.asana.com/0/1201095311341924/1201715431493439/f) (_internal_)
- We could consolidate more of the Update/create logic in the postgres client for EntityType, I decided not to do this …
=> Refactor JSON schema validation

packages/hash/frontend/src/testUtils/testUtils.tsx, packages/hash/playwright/tests/entity-creation.spec.ts, packages/hash/playwright/tests/guest-user.spec.ts
One of the previous commits to the `header-sidebar-update` branch had broken the CI. More specifically, `jest` and `playwright` tests. This PR is responsible for fixing those tests so all future PRs can benefit from working off of a stable branch.
Changes will be described in the comments below.
- Existing playwright and jest tests cover the changes made in this PR.
Run `yarn test` or `yarn test:playwright` on the `frontend` package locally. Otherwise, rely on the CI output presented by GitHub Actions.
---
- https://app.asana.com/0/0/1201925844970643
=> Fix failing tests on Header-Sidebar feature branch

packages/engine/Cargo.lock, packages/engine/Cargo.toml
We try to keep Arrow up-to-date because it's critical to our ecosystem
=> Bump Arrow and Flatbuffers

packages/hash/README.md
Was a little confusing that commands were ran from the repo root and not packages/hash
=> Clarifying README

packages/engine/README.md
Currently, it's required to have a set up Python environment. This needs to be stated in the README.
[Only enable the Python runner if Python behaviors are present](https://app.asana.com/0/1199548034582004/1202021770319180/f)
=> Mention, that a Python setup is currently always required

packages/hash/api/src/graphql/resolvers/entity/linkGroups.ts, packages/hash/integration/src/tests/model/entity.model.test.ts
This quick PR adds a unit test for the `Entity.isEquivalentTo` method to verify it behaves as expected, and replaces an existing temporary equivalent function with the class method. I've tested locally that this doesn't throw any unexpected errors as well, which fixes [the bug captured in this task](https://app.asana.com/0/1200211978612931/1201657798338499/f).
No
- [Fix `this` in Entity equivalentTo is undefined](https://app.asana.com/0/1200211978612931/1201657798338499/f) _(internal)_
To test that the bug captured in this task can no longer be replicated:
2. Login to the local developer environment
3. <details>
<summary>Create an basic aggregation for an entity in the workspace</summary>
```GraphQL
mutation CreateLinkedAggregations {
createLinkedAggregation( …
```
=> `Entity.isEquivalentTo` method test and adopt usage

README.md, SECURITY.md, packages/engine/README.md, packages/hash/README.md
This PR makes a number of updates to our in-repository security policy.
=> Update our in-repo security policy

README.md, SECURITY.md, sites/README.md, sites/hashai/README.md, sites/hashdev/README.md
- Improves the clarity of various repo READMEs based on feedback from team members and community.
- Adds a `sites/hashai` directory in anticipation of code and content being gradually ported in here from its current home in our private `internal` monorepo.
=> Update various repo READMEs

packages/engine/lib/memory/src/shared_memory/segment.rs
A previous PR accidentally broke compilation on macOS (which is hard to detect if you're not on macOS). This PR contains the fix.
=> macOS hotfix

sites/hashdev/src/pages/index.page.tsx
Improve the spacing between headings.
- [Asana task](https://app.asana.com/0/1201095311341924/1202321800174327/f) _(internal)_
=> Improve spacing between headings on hash.dev site

packages/blocks/drawing-canvas/package.json
Updates the drawing canvas block so that it can be added under the `tldraw` namespace. 
- Merge https://github.com/blockprotocol/blockprotocol/pull/316
=> Update Drawing canvas block author

packages/engine/lib/error/src/macros.rs
Ensures, that a `Report` isn't changed when passed to a macro call (`report!`, `bail!`, `ensure!`).
- [Asana task](https://app.asana.com/0/0/1201596707170558/f) _(internal)_
- ~#592~
- Add a `ReportTag` for inferring a `Report` inside of a macro
- Make macro functions inline
- Improve documentation on macros
(Also applies to `bail!` and `ensure!`)
Given:
```rust
let report_a = report!(std::io::Error { .. });
assert!(report_a.contains::<std::io::Error>()); // Succeeds
let report_b = report!(report_a);
```
**Before:**
```rust
assert!(report_b.contains::<std::io::Error>()); // Fails
```
**After:**
```rust
assert!(report_b.contains::<std::io::Error>()); // Succeeds
```
=> Ensure `Report` is kept when passed to macro

packages/engine/lib/error/src/future.rs
The `Future` adaptors have all the same logic, this can be converted in a macro for simplification
- [Asana task](https://app.asana.com/0/1199550852792314/1201586921294315) _(internal)_
Use a macro instead of writing the adaptors by hand
Internal change only, docs are unchanged (they are generated from the method name)
When new adaptors are added, this macro can be used, e.g. when implementing `Report::provide`.
=> Simplify future adaptors by using macros

packages/libs/error-stack/README.md
Fix capitalization in error-crate README.md
=> Fix capitalization in error-crate readme

packages/blocks/code/package.json, packages/blocks/table/src/components/filter-detail.tsx, sites/hashdev/package.json, sites/hashdev/src/components/MdxPre.tsx, sites/hashdev/src/components/Snippet.tsx, sites/hashdev/src/pages/_app.page.tsx, sites/hashdev/src/util/mdxComponents.tsx, sites/hashdev/styles/globals.css, sites/hashdev/styles/prism.css, yarn.lock
Add code syntax highlighting to the hash.dev blog posts.
Fix the display of list items.
---
- https://app.asana.com/0/0/1202405291900006
=> hash.dev blog: add syntax highlighting, fix list items

resources/docs/simulation/tutorials/phase-1-building-a-simple-hotelling-model-in-2d/set-up-environment.md
Old link was wrong, hopefully this link is right?
Changed /docs/simulation/configuration/topology into /docs/simulation/creating-simulations/configuration/topology
Fixing a link on the https://hash.ai/docs/simulation/tutorials/phase-1-building-a-simple-hotelling-model-in-2d/set-up-environment
https://hash.ai/docs/simulation/tutorials/phase-1-building-a-simple-hotelling-model-in-2d/set-up-environment
- ...
- The docs for x need updating to explain that y
-
1.  Try X
1.  Confirm that Y
Try the link?
=> Updated Topology Link

packages/blocks/table/example-graph.json, packages/blocks/table/package.json, packages/blocks/table/src/components/editable-cell.tsx, packages/blocks/table/src/components/entity-type-dropdown.tsx, packages/blocks/table/src/components/filter-detail.tsx, packages/blocks/table/src/components/header.tsx, packages/blocks/table/src/components/sort-detail.tsx, packages/blocks/table/src/dev.js, packages/blocks/table/src/dev.tsx, packages/blocks/table/src/lib/columns.ts, packages/blocks/table/src/lib/filter-entities.ts, packages/blocks/table/src/lib/sort-entities.ts, packages/blocks/table/src/table.tsx, yarn.lock
Update the Table block for the protocol v0.2 (public docs coming soon).
- This block cannot be published on the Block Hub until blockprotocol.org is updated for BP 0.2
- Update blockprotocol.org to handle BP 0.2
1.  Check that the block works when running yarn dev
---
- https://app.asana.com/0/0/1202418951550821
=> Update table block to v0.2

packages/blocks/person/package.json, packages/blocks/person/src/app.tsx, packages/blocks/person/src/dev.tsx
This PR updates person block similar to https://github.com/hashintel/hash/pull/643 and https://github.com/hashintel/hash/pull/646
- This block cannot be published on the Block Hub until blockprotocol.org is updated for BP 0.2
- Update blockprotocol.org to handle BP 0.2
1.  Check that the block works when running yarn dev
---
- https://app.asana.com/0/0/1202418951550831
=> Upgrade Person block to v0.2

sites/hashdev/src/pages/blog/index.page.tsx
This PR uses the `Divider` MUI component in the hash.dev blog, and changes the divider color
=> hash.dev blog fix divider color

sites/hashdev/src/_pages/blog/5_build-blocks-in-any-language.mdx, sites/hashdev/src/components/CalculationBlock.tsx
I noticed some visual issues on mobile when viewing the post. 
- Embedded block was adding a horizontal scroll bar to the entire page
- Subsequently some inline code blocks added horizontal scroll
- Embedded block was not centered
The new lines added do not split the paragraphs.
=> F# blog post small visual fixups

packages/engine/lib/memory/src/shared_memory/segment.rs
A mistake was made in #444, this fixes it.
=> Fixing memory allocation on macOS

packages/engine/Cargo.lock
Updates the lock file to use the latest git revision of `shared_memory`
- [Asana task](https://app.asana.com/0/1199548034582004/1201566010883987/f) _(internal)_
- https://github.com/hashdeps/shared_memory-rs/pull/38
=> Update `shared_memory` to latest git commit

packages/hash/frontend/src/blocks/page/createSuggester/Suggester.tsx, packages/hash/frontend/src/blocks/page/createSuggester/createSuggester.tsx, packages/hash/frontend/src/blocks/page/createSuggester/useFilteredBlocks.tsx
This PR adds some improvements to the block suggester majorly around when to show the block suggester dropdown and properly ranking the search results.
- [Bug: @ menu hidden if text below?](https://app.asana.com/0/1202482456346915/1202510248434786) _(internal)_
- [Bug: attempt to only show / menu when user intends](https://app.asana.com/0/1202482456346915/1202518487775878) _(internal)_
- [Rank blocks in / menu by search query relevance](https://app.asana.com/0/1202482456346915/1202500568584715) _(internal)_
- The [method](https://github.com/hashintel/hash/blob/main/packages/hash/frontend/src/blocks/page/createSuggester/createSuggester.tsx#L33) used to find strings that bring up the block suggester didn't initially account for hard breaks. This …
=> Block Suggester improvements

.github/scripts/rust/Makefile.toml, .github/workflows/rust.yml, packages/engine/Makefile.toml, packages/graph/hash_graph/Makefile.toml, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/datastore/mod.rs, packages/libs/error-stack/Makefile.toml
=> Improve Rust CI performance (`dev/graph`)

packages/graph/hash_graph/lib/graph/src/datastore/mod.rs, packages/graph/hash_graph/lib/graph/src/datastore/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/types/schema/array.rs, packages/graph/hash_graph/lib/graph/src/types/schema/data_type.rs, packages/graph/hash_graph/lib/graph/src/types/schema/entity_type.rs, packages/graph/hash_graph/lib/graph/src/types/schema/link.rs, packages/graph/hash_graph/lib/graph/src/types/schema/mod.rs, packages/graph/hash_graph/lib/graph/src/types/schema/object.rs, packages/graph/hash_graph/lib/graph/src/types/schema/property_type.rs, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
Implements CRU operations for entity types
- [Asana task](https://app.asana.com/0/1200211978612931/1202510174412972) _(internal)_
- Implements CRU operations for entity types
Tests were added to test this functionality
=> Implement CRU operations for entity types

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/datastore/error.rs, packages/graph/hash_graph/lib/graph/src/datastore/mod.rs, packages/graph/hash_graph/lib/graph/src/datastore/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/types/mod.rs, packages/graph/hash_graph/lib/graph/src/types/schema/data_type.rs, packages/graph/hash_graph/lib/graph/src/types/schema/entity_type.rs, packages/graph/hash_graph/lib/graph/src/types/schema/link.rs, packages/graph/hash_graph/lib/graph/src/types/schema/mod.rs, packages/graph/hash_graph/lib/graph/src/types/schema/object.rs, packages/graph/hash_graph/lib/graph/src/types/schema/property_type.rs, packages/graph/hash_graph/lib/graph/src/types/uri.rs, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
In order to keep track of versioning, URIs has to be aware of versions.
- [Asana task](https://app.asana.com/0/1201095311341924/1202591159011628) _(internal)_
- Make `Uri` aware of `base_id` and `version`
- Update test-data to include versions
- Change database to allow checking for existing versions
- Return an error if inserting with an existing version
The tests has been adjusted
=> Implement versioning for URIs

packages/hash/frontend/src/blocks/page/BlockContextMenu/BlockContextMenu.tsx, packages/hash/frontend/src/blocks/page/BlockContextMenu/BlockLoaderInput.tsx, packages/hash/playwright/tests/page-creation.spec.ts
Fixes create-page playwright test which started failing after #752.
- [Fix create page Playwright test](https://app.asana.com/0/1202482456346918/1202596925797566) _(internal)_
- Updates block loader input to close block menu after block has been loaded
- Updates page creation playwright tests
1.  Playwright tests should be passing
=> Fix create page playwright test

packages/graph/hash_graph/lib/graph/src/datastore/postgres/mod.rs
To ensure that the database is in a well defined states, transactions needs to be used.
- [Asana task](https://app.asana.com/0/0/1202598517577613) _(internal)_
- Abstract internal methods of database over an `Executor`
- Use transactions when inserting or updating
No, this is internal only
As this is internal only, the current test suite will test this as well
=> Use transactions for insertion and updating

packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/tests/rest-test.http
Similar to other types, we also want to create, query, and update entities from the REST API
- [Asana task](https://app.asana.com/0/1202542409311090/1202622269244649/f) _(internal)_
- #840 
- ~#841~
- #843 
- Implements the endpoints for entitites
- Adds tests for testing the endpoints
The OpenAPI specs will pick these endpoints up
=> Implement REST endpoints for entity API

packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
This PR adds another table in the postgres store to allow for entities to be referenced without a version ID. This is in preparation for adding links in the datastore, where we want to reference non-versioned entities as part of a new table.
- [Asana task](https://app.asana.com/0/0/1202661885539216/f) _(internal)_
- Pinning CI cargo quickinstalls
- Adds lookup table for `entity_ids`
- Adds `insert_entity_id` method on the postgres store internally
- Uses lookup `entity_ids` tablefor operations related to creating and updating entities
- Cleans up entities after integration tests (this will be removed very soon, though)
- The docs for x need updating to explain that y
- Implement links in the graph
- Integration tests
No changes to functionality yet
=> Split out entities composite primary key in anticipation for links

packages/hash/api/src/model/index.ts, packages/hash/api/src/model/ontology/data-type.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/link-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts, packages/hash/integration/src/tests/model/ontology/data-type.model.test.ts, packages/hash/integration/src/tests/model/ontology/entity-type.model.test.ts, packages/hash/integration/src/tests/model/ontology/link-type.model.test.ts, packages/hash/integration/src/tests/model/ontology/property-type.model.test.ts
This PR introduces the `Entity Type` model class, with basic CRU operations and `getOutgoingLinkTypes`/`getPropertyTypes` helper methods.
- [Asana task](https://app.asana.com/0/1202621375435411/1202705536455597/f) _(internal)_
- Implements the `EntityTypeModel` class in `src/model/ontology/entity-type.model.ts`
- Graph API errors are difficult to track down using the API client
- [Migrate CRU functionality for entities in the HASH workspace BE to the Graph API](https://app.asana.com/0/1200211978612931/1202731581883433/f) _(internal)_
- `packages/hash/integration/src/tests/model/ontology/entity-type.model.test.ts`
1.  Recreate and migrate DB and run backend
- From the `packages/graph/hash_graph/bin/hash_graph` path run:
- `cargo make …
=> Add `EntityTypeModel` class with Graph API CRU operations

packages/graph/hash_graph/Makefile.toml, packages/graph/hash_graph/lib/graph/src/api/rest/json_schemas/entity_type.json, packages/graph/hash_graph/lib/graph/src/ontology/types/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/types/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/types/serde_shared/array.rs, packages/graph/hash_graph/tests/test_data/entity_type/book.json
The EntityType struct accidentally didn't let you set a property as being an array. This fixes that
- The full test suite, the `Book` test entity has been updated to have an array
1. Follow the README as normal
=> Fix Entity Type

packages/hash/README.md, packages/hash/api/src/auth/seed-dev-users.ts, packages/hash/api/src/index.ts
This PR adds a seed step for creating Kratos identities and Graph user entities for two development users, `alice@example.com` and `bob@example.com`.
- [Asana task](https://app.asana.com/0/1202621375435417/1202714661072444/f) _(internal)_
- Add a seed step before starting the backend ensuring the two users exist
- Changed readme to reflect how users are seeded now
- manual test
1.  Run external services `yarn external-services up`
1.  Run the frontend/backend `yarn dev` from the root
1.  Observe backend logs. Should contain two lines looking like `Development user available, email = "alice@example.com" password = "password"`
1.  Login with the given user at http://localhost:3000/login
=> Seed development users in kratos and the Graph API

packages/libs/error-stack/CHANGELOG.md
I forgot to adjust the changelog in my PRs, which remedies this.
Input on the wording is much appreciated, and things I might've forgotten.
=> Update `error-stack` changelog 

packages/blocks/callout/package.json, packages/blocks/callout/src/app.tsx, packages/blocks/paragraph/package.json, packages/blocks/paragraph/src/app.tsx, packages/blocks/paragraph/src/dev.tsx
This converts our remaining blocks to the hook service in preparation for removing editable ref. 
- [Asana task](https://app.asana.com/0/1202621375435417/1202834301075791/f) _(internal)_
- Upgrades paragraph block to latest version of block protocol / mock block dock
- Replaces editableRef with hook service in both
N/A
N/A
- Upgrade block hub to use hook service + update blocks in hub + make them visible in hub
- Remove editableRef from HASH [Asana task](https://app.asana.com/0/1201095311341924/1202834301075793/f) (_internal_)
- Upgrade mock block dock to support hook service 
N/A
1. Checkout branch
2. Build and serve blocks locally
3. Point HASH at local blocks
4. Check works as expected
=> Convert paragraph and callout blocks to hook service

.github/workflows/rust.yml, packages/libs/error-stack/macros/Cargo.toml
This is another attempt to fix the `publish` job on push to main
- #989 
- #982 
It's not possible to test this in CI in a pull request and requires a merge
=> Attempt to fix the `publish` job on push to main

.github/workflows/rust.yml, packages/libs/error-stack/macros/Cargo.toml
This is another attempt to fix the `publish` job on push to main
- #982 
- #989 
- #991
It's not possible to test this in CI in a pull request and requires a merge
=> Attempt to fix `publish` job on push to `main`, II

.github/workflows/rust.yml, packages/libs/error-stack/macros/Cargo.toml
Publish `error-stack-macros` as reserved crate
- #982
- #989 
- #991
- #992
=> Publish `error-stack-macros`

packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/pool.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/resolve.rs
Especially with #1012  and #1024, some bounds on generics got quite complicated, this makes those more readble
=> Make bounds on generics more readable

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/link.rs, packages/graph/hash_graph/lib/graph/src/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/link/read.rs, packages/hash/api/src/model/knowledge/link.model.ts
`OutgoingLinks` is not used anymore, so we can safely remove it
=> Remove `OutgoingLinks`

packages/graph/hash_graph/tests/rest-test.http, packages/hash/api/src/graphql/resolvers/ontology/model-mapping.ts, packages/hash/api/src/graphql/resolvers/ontology/property-type.ts, packages/hash/api/src/graphql/resolvers/util.ts, packages/hash/api/src/graphql/typeDefs/ontology/property-type.typedef.ts, packages/hash/api/src/model/ontology/data-type.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts, packages/hash/api/src/model/util.ts, packages/hash/external-services/docker-compose.yml
Adds a method to optionally allow recursive lookups for property types. This is passed down to GraphQL, so it's possible to read referenced property types and referenced data types by a given data type.
- [Asana task](https://app.asana.com/0/1200211978612931/1202900021005255/f) _(internal)_
- #1059 
- Support recursive lookup of properties in queries (Graph API)
- Expose recursive lookup in GraphQL
The GraphQL documentation was adjusted
- Implement the same for entity types and entities
Input: 
```gql
query recursive_property_types {
getAllLatestPropertyTypes {
propertyType
referencedDataTypes {
dataType
}
referencedPropertyTypes {
propertyType
}
}
}
```
<details>
<summary>Output</summary>
```json
{
"data": {
"getAllLatestPropertyTypes": [
{
"propertyType": {
"$id": …
```
=> Implement recursive queries for property types

packages/hash/api/src/graphql/resolvers/ontology/entity-type.ts, packages/hash/api/src/graphql/resolvers/ontology/model-mapping.ts, packages/hash/api/src/graphql/resolvers/ontology/property-type.ts, packages/hash/api/src/graphql/resolvers/util.ts, packages/hash/api/src/graphql/typeDefs/ontology/entity-type.typedef.ts, packages/hash/api/src/graphql/typeDefs/ontology/property-type.typedef.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/link-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts
Similar to #1051, this implements recursive lookups for entity types
- [Asana task](https://app.asana.com/0/1202882583267702/1202962778211049/f) _(internal)_
- Expose recursive lookup in GraphQL
The GraphQL documentation was adjusted
- Implement the same for enties and entities: [Asana task](https://app.asana.com/0/1200211978612931/1202682556665585/f) (_internal_)
```gql
query recursive_entity_types {
getEntityType(entityTypeVersionedUri: "http://localhost:3000/@example/types/entity-type/organization/v/1") {
entityTypeVersionedUri
referencedDataTypes {
dataTypeVersionedUri
}
referencedPropertyTypes {
propertyTypeVersionedUri
}
referencedLinkTypes {
linkTypeVersionedUri
}
referencedEntityTypes {
entityTypeVersionedUri
}
}
}
```
```json
{
"data": {
"getEntityType": { …
```
=> Expose recursive queries for entity types

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/mod.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/rest-test.http
Initial PR to support recursive queries for entities. This PR only covers the Graph API and only supports ontology types to be returned as well.
- [Asana task](https://app.asana.com/0/1200211978612931/1202682556665585/f) _(internal)_
- Change the query-endpoint to take a query with references and return a rooted subgraph
- Use functionality introduced in #1059 to return ontology types
The OpenAPI client was updated
- Allow returning of references to entities and links as well
- Expose functionality in GraphQL (blocked on #1062)
A small endpoint test was added
```http
POST http://127.0.0.1:4000/entities/query
{
"query": {
"eq": [
{
"path": [
"version"
]
},
{
"literal": "latest"
}
]
},
"dataTypeQueryDepth": 255,
"propertyTypeQueryDepth": 255, …
```
=> Support returning referenced ontology types for entities

packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs
With the last commit in #1072 it's possible to remove things from the dependency list again. This PR uses the dependency map also for resolving the root, which then gets removed at the end of the operation. This greatly reduces code duplications and makes it easier to maintain
- #1059
- #1072
=> Remove duplicated code from recursing logic

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link.rs, packages/graph/hash_graph/lib/graph/src/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/rest-test.http, packages/hash/api/src/model/knowledge/link.model.ts, packages/hash/api/src/model/knowledge/orgMembership.model.ts, packages/hash/api/src/model/knowledge/user.model.ts
Adds support to return `Link`s referred to from entities, either by starting from an entity query or from a link query
- [Asana task](https://app.asana.com/0/1202882583267702/1202986163519979/f) _(internal)_
- Unify `EntityQuery` and `LinkQuery` into `KnowledgeQuery`
- Support links to be returned from entities
- Support linked entities returned from Link queries
The OpenAPI client was updated
The return structure is not necessary optimal, we might want to [move to a vertex/edge set](https://app.asana.com/0/0/1202996107497595/f) (_internal_)
Test the query with different setups and parameters
```http
POST http://127.0.0.1:4000/entities/query
{
"query": {
"eq": [
{
"path": [
"version"
]
},
{
"literal": "latest"
}
]
},
"dataTypeQueryDepth": 0, …
```
=> Support links to be returned from queries

packages/hash/realtime/src/index.ts
Adds a todo in realtime that we should investigate for production ready citus.
=> Add 'for update' citus TODO

packages/libs/error-stack/README.md, packages/libs/error-stack/macros/rust-toolchain.toml, packages/libs/error-stack/rust-toolchain.toml, packages/libs/error-stack/src/fmt/hook.rs, packages/libs/error-stack/src/hook.rs, packages/libs/error-stack/src/lib.rs, packages/libs/error-stack/tests/common.rs
In a recent nightly, the provider interface on `Demand` changed slightly.
=> Bump error-stack toolchain to 2022-09-27

packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/logging/args.rs, packages/graph/hash_graph/lib/graph/src/logging/init.rs, packages/graph/hash_graph/lib/graph/src/store/query.rs, packages/graph/hash_graph/rust-toolchain.toml
One of the recent nightly toolchains fixed the clippy lint `use_self`. This bumps the toolchain and applies the lint
=> Bump toolchain to 2022-09-27

packages/libs/error-stack/CHANGELOG.md
In #1127 a link was deleted accidentally, this adds it back.
=> Fix Changelog link

packages/libs/error-stack/CHANGELOG.md, packages/libs/error-stack/Cargo.toml, packages/libs/error-stack/Makefile.toml, packages/libs/error-stack/build.rs, packages/libs/error-stack/src/fmt/hook.rs
We introduced breaking changes so we can safely remove the deprecated features directly
- [Notion comment](https://www.notion.so/Announcing-error-stack-v0-2-DRAFT-997028b272644a22b4035340f47c61bf?d=adb847977e79485bb6f1e83c6bca5ea4#19b399a9b3804e62a787dac57fee44ab) _(internal)_
=> Remove unused features

packages/hash/api/src/graph/workspace-types.ts, packages/hash/api/src/graphql/resolvers/knowledge/model-mapping.ts, packages/hash/api/src/graphql/typeDefs/knowledge/page.typedef.ts, packages/hash/api/src/model/knowledge/page.model.ts, packages/hash/frontend/src/blocks/page/PageTitle/PageTitle.tsx, packages/hash/frontend/src/components/PageIcon.tsx, packages/hash/frontend/src/components/PageIconButton.tsx, packages/hash/frontend/src/components/hooks/useUpdatePageIcon.ts, packages/hash/frontend/src/components/hooks/useUpdatePageTitle.ts, packages/hash/frontend/src/pages/[account-slug]/[page-slug].page.tsx, packages/hash/frontend/src/shared/layout/layout-with-sidebar/account-page-list/page-tree-item.tsx
This PR fixes setting page titles and icons. Previously this was broken as we were using the `updateEntity` mutation rather than the special cased page modification mutation.
This also fixes page archival banner that wasn't being loaded correctly.
- Adds hooks for updating page titles and icons
- Fixes usage of `updateEntity` for the page title
- Fixes page archival banner
- Adds missing `icon` property type for the page entity type
-
1.  Checkout the branch, start external services and `yarn dev`
1. Open the workspace and sign in
1. Create a page and edit its title/icon
=> Fix broken page title/icon and archival banner

packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/graphql/resolvers/knowledge/entity/entity.ts, packages/hash/api/src/graphql/typeDefs/knowledge/entity.typedef.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/knowledge-shim.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolGetEntity.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolUpdateEntity.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetDataType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetEntityType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetLinkType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetPropertyType.ts, packages/hash/frontend/src/graphql/queries/knowledge/entity.queries.ts, packages/hash/frontend/src/pages/type-editor/blockprotocol-ontology-functions-hook.ts
This PR adds an `updateEntity` hook to use for the new graph type system. 
@yusufkinatas example usage:  https://github.com/hashintel/hash/commit/d41b4e141531e6accbfd3e443d565ced3622e51c
- [Asana task](https://app.asana.com/0/1202953520344821/1203086812814270/f) _(internal)_
- Perhaps merging?
- This adds a new GQL mutation, `updateEntity`
- Adds a new BP shim message `UpdateEntityRequest`
- Adds a new BP hook ``useBlockProtocolUpdateEntity`
- Exposes the new `updateEntity` functionality in `useBlockProtocolFunctionsWithOntology`
- Existing integration tests on the backend
Here is an example usage
https://github.com/hashintel/hash/commit/d41b4e141531e6accbfd3e443d565ced3622e51c
=> Add `updateEntity` BP hook

packages/hash/frontend/src/blocks/page/createSuggester/createSuggester.tsx
This PR fixes the vertical positioning of the block and mention suggester on multi-line text blocks.
- [Asana task](https://app.asana.com/0/1200211978612931/1203064559981310/f) _(internal)_
Before:
After:
=> fix suggester vertical positioning

packages/libs/deer/README.md
One line copy change PR that makes clear in the `deer` README that the crate is experimental.
=> Make explicit that `deer` is experimental

packages/graph/hash_graph/lib/graph/src/store/postgres/query/condition.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/window.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs, packages/graph/hash_graph/lib/graph/src/store/query/filter.rs, packages/graph/hash_graph/lib/graph/src/store/query/mod.rs
For `WITH` clauses, we need the `MAX()` function and window statements.
- [Asana task](https://app.asana.com/0/1203007126736607/1203150072758518/f) _(internal)_
- #1210 
- Rename `ConditionValue` to `Expression` (it's used in more places than in `Condition`)
- Move `Expression` from the `condition` module to the `expression` module
- Drive-by: Rename `database` module to `table`
- Add `Expression::Function` variant and `Function` enum
- Add `Expression::Window` variant and `WindowStatement` struct
New tests were added to test the new expressions
=> Add function expression and window expression

packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs
Very similar to #1258 but for entities
- [Asana task](https://app.asana.com/0/1203007126736610/1203205825668100/f) _(internal)_
- #1258 
- #1255
- #1267
- #1268
- #1269
- #1273 
- #1228 
Applies the same changes as #1258 but for entities instead
=> Use optimized queries in entity endpoints

packages/graph/hash_graph/lib/graph/src/api/rest/link.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/link/read.rs
Very similar to #1275 but for links
- [Asana task](https://app.asana.com/0/1203007126736610/1203225514907869/f) _(internal)_
- #1258 
- #1255
- #1267
- #1268
- #1269
- #1271
- #1272 
- #1273 
- #1228 
- #1274
- #1275
Applies the same changes as #1275 but for links instead
=> Use optimized queries in link endpoints

blocks/calculation/package.json, blocks/callout/package.json, blocks/code/package.json, blocks/countdown/package.json, blocks/drawing/package.json, blocks/github-pr-overview/package.json, blocks/header/package.json, blocks/image/package.json, blocks/paragraph/package.json, blocks/person/package.json, blocks/shuffle/package.json, blocks/table/package.json, blocks/timer/package.json, blocks/video/package.json, packages/hash/frontend/package.json, yarn.lock
It updates dependencies in blocks to bring in bug fixes in `@blockprotocol/hook` and `mock-block-dock`
Update blocks in `blockprotocol`
=> Update dependencies in blocks

packages/libs/error-stack/src/frame/frame_impl.rs, packages/libs/error-stack/src/frame/mod.rs
Currently, the `Frame` implementation requires a fair bit of `unsafe` code when calling functions related to downcasting (`is<T>`, `downcast_ref<T>`, `downcast_mut<T>`). By using the implementation of `Any`, this can be avoided.
Initially, I thought this is only possible with `feature(trait_upcasting)` but we don't have to cast the `dyn FrameImpl` but the inner type of `dyn FrameImpl`.
- Return `dyn Any` instead of `TypeId`
- Rely on `Any::downcast` instead
This is an internal change only.
I like to make `error-stack` unsafe-free at some point
With these changes we only have four locations with `unsafe` code:
- Implementation for the `Future` extension (alternative would be to pull the `pin_project` crate, which does the same thing)
- Implementation for mutable Iterator. Maybe we can get …
=> Avoid frame casting by using `Any` instead of `unsafe`

.github/workflows/ci.yml, .github/workflows/rust.yml
Supplements https://github.com/hashintel/hash/pull/1291. Gives us up-to-date baseline coverage (against which PR coverage is calculated).
Yaml changes are inspired by [BP → ci.yml](https://github.com/blockprotocol/blockprotocol/blob/be40a3a1c208397edfb5e11b83037bfc45a49e45/.github/workflows/ci.yml).
Improve existing test coverage and report coverage from more tests.
=> Run unit and backend tests on main branch to report coverage

codecov.yml
This PR eases codecov.io feedback till the setup process is complete.
- [Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1667239411103039) _(internal)_
- [Docs](https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations-via-yaml)
=> Disable codecov annotations and make all checks informational for now

.eslintrc.cjs, .prettierrc.js, packages/graph/clients/typescript/.eslintrc.cjs, packages/graph/migrations/.eslintrc.cjs, packages/hash/api/.eslintrc.cjs, packages/hash/backend-utils/.eslintrc.cjs, packages/hash/design-system/.eslintrc.cjs, packages/hash/frontend/.eslintrc.cjs, packages/hash/integration/.eslintrc.cjs, packages/hash/playwright/.eslintrc.cjs, packages/hash/realtime/.eslintrc.cjs, packages/hash/search-loader/.eslintrc.cjs, packages/hash/shared/.eslintrc.cjs, packages/hash/task-executor/.eslintrc.cjs, sites/hashai/.eslintrc.cjs, sites/hashdev/.eslintrc.cjs
Part 2/2 of `git blame` preservation. Context: https://github.com/hashintel/hash/pull/1306#discussion_r1010421641
Makes https://github.com/hashintel/hash/pull/1285 easier to review later on.
- [Asana task](https://app.asana.com/0/1203007126736613/1203268787004300/f) _(internal)_
=> Format `.eslintrc.cjs` files

packages/graph/hash_graph/bin/hash_graph/src/main.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs, packages/graph/hash_graph/tests/rest-test.http
We can create entity types and entities but currently not return them. This PR solves this.
- [Asana task](https://app.asana.com/0/1201095311341924/1203250001255262/f) _(internal)_
- Add variants to `EntityTypePath` and `EntityPath`
- Adjust `EntityType` queries
- Adjust `Entity` queries
We currently cannot investigate the `links` query on `entity-types` and `entity`, this will be done in a follow-up
=> Fix queries for entity types and entities -- Part I

packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs
When adding link support for entities, I missed adding deserialization for `LeftEntity` and `RightEntity`.
- [Asana task](https://app.asana.com/0/1201095311341924/1203250001255262/f) _(internal)_
- Add `LeftEntity` and `RightEntity` variants to `EntityQueryPathToken`
- Fix wrong deserialization message
A test for `leftEntity.id` was added
=> Add deserialization for `LeftEntity` and `RightEntity`

.github/renovate.json
Continues #1373, adds https://docs.renovatebot.com/configuration-options/#postupdateoptions, fixes CI in https://github.com/hashintel/hash/pull/1377
x-ref: https://github.com/blockprotocol/blockprotocol/blob/d96b316ce8385b3eae0e5ff810557d0f8e1772da/.github/renovate.json#L3
=> Deduplicate dependencies after updating them

packages/graph/hash_graph/bench/benches/read_scaling/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/seed.rs, packages/graph/hash_graph/bench/benches/util.rs, packages/graph/hash_graph/lib/graph/src/api/rest/middleware.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/depths.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/edges/kind.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/edges/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/vertices/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/vertices/vertex.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/query/filter.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/test_data/src/entity_type/book.json, packages/graph/hash_graph/tests/test_data/src/entity_type/building.json
in `dev/links` we didn't require a passing CI. This makes sure, that all jobs are green again
- [Asana task](https://app.asana.com/0/1202805690238892/1203348428860466/f) _(internal)_
- Fix clippy lints
- Implement Default for Edges: 2c4c8d0
- Remove unnecessary function calls: 95c5528
- Ignore option_if_let_else lint: 9080e7e
- Box vertices: f9cd57a
- Satisfy Send bound: 48eadbb
- Remove unfulfilled lint attribute: d40f942
- Ignore too_many_lines lint: 8ac9462
- Fix benchmark code: a16d234
- Fix doc links: ff4a82c
The CI will pick all of this up
=> Fix benchmarks and various other lints

packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs
#1367 forgot to adjust changes made in #1387, this is a hotfix
=> Fix doc-tests not passing

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs
Adding archival to the TS API. This was a small oversigt, and a one-line change to get generated.
=> Add archival to api

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/shared/subgraph/edges/edge.rs
We were accidentally using the `EdgeKind` type for `Endpoint` and vice versa
=> Fix OpenAPI spec for edges

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/property_type.rs
The tokens were out of sync. This generates them based on the implementation
- [Slack discussion](https://hashintel.slack.com/archives/C03F7V6DU9M/p1668617489446579) _(internal)_
=> Correctly generate query tokens for OpenAPI interface

packages/hash/subgraph/src/types/element.ts
Some nested types would be helpful to export as standalone ones so they can be used in `create` methods and similar.
- [Asana task](https://app.asana.com/0/1202805690238892/1203409252899196/f) _(internal)_
=> Update subgraph exports

packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/api/src/model/knowledge/linkEntity.model.ts, packages/hash/api/src/model/knowledge/page.model.ts
Updating link orders and other metadata was broken in the API package, this fixes that and some other TS errors.
=> Fix Link updating in model classes

packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/knowledge-shim.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolAggregateEntities.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolCreateEntity.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolGetEntity.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolUpdateEntity.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/ontology-types-shim.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolAggregateDataTypes.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolAggregateEntityTypes.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolAggregatePropertyTypes.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolCreateEntityType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolCreatePropertyType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetDataType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetEntityType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetPropertyType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolUpdateEntityType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolUpdatePropertyType.ts, packages/hash/frontend/src/pages/type-editor/blockprotocol-ontology-functions-hook.ts, packages/hash/frontend/src/pages/type-editor/index.page.tsx
The BP hooks needed updating for the changes made in this branch. This does that
- [Asana task](https://app.asana.com/0/1203301853897838/1203421643873814/f) _(internal)_
See commit list
We will be experimenting with new hook signatures locally, we can then propose changes to the BP spec.
Many things are still broken, testing this is hard, I am mostly relying on TSC
- Delete the old hooks
- Fix more of the frontend
- None really at the moment
1.  Follow the README to run `yarn dev`
2. Go to `localhost:3000/type-editor` all buttons should work
=> Fix BP hooks

packages/hash/frontend/src/pages/[account-slug]/types/entity-type/[entity-type-id].page.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/property-type-form.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/use-entity-type.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/use-property-types.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/use-route-namespace.tsx, packages/hash/frontend/src/pages/[account-slug]/types/new/entity-type.page.tsx
This fixes the type editor
- [Asana task](https://app.asana.com/0/0/1203421643873816/f) _(internal)_
See commits
No
Fix the entity editor
Unsure if there are any
1.  Follow the README to run the app
1.  Go to `http://localhost:3000/@alice/types/new/entity-type`
1.  Test out the editor
https://user-images.githubusercontent.com/25749103/203407054-fa9a1248-a9d8-400f-82f3-07ab90ee7477.mov
=> Fix Type Editor

packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetEntityType.ts, packages/hash/frontend/src/components/hooks/useGetAccountIdForShortname.ts, packages/hash/frontend/src/components/hooks/useOrgs.ts, packages/hash/frontend/src/components/hooks/useUsers.ts, packages/hash/frontend/src/graphql/queries/ontology/entity-type.queries.ts, packages/hash/frontend/src/lib/entities.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/entity-editor-context.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/links-section.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/links-section/link-table/constants.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/links-section/link-table/types.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/links-section/link-table/use-row-data.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/use-on-cell-edited.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/use-row-data.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/use-row-data/generate-property-rows-from-entity.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/use-row-data/generate-property-rows-from-entity/generate-property-row-recursively.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/use-row-data/generate-property-rows-from-entity/get-expected-types-of-property-type.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/types-section.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-page-wrapper.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/[entity-type-id].page.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/property-type-form.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/tabs/entities-tab.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/use-entities-table.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/use-entity-type-entities.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/use-route-namespace.tsx, packages/hash/frontend/src/pages/[account-slug]/types/new/entity-type.page.tsx, packages/hash/frontend/src/pages/entity-editor.page.tsx, packages/hash/subgraph/src/types/identifier.ts
This fixes the entity editor
- [Asana task](https://app.asana.com/0/1203301853897838/1203421643873817/f) _(internal)_
See commits
No
Unsure if there are any
1.  Follow the README to run the app
1.  Go to `http://localhost:3000/entity-editor`
1.  Pick out some entities (get their entityUuid by taking the component after the `%` in the baseId)
1.  Try and find their associated user (or guess it's Alice)
1.  Go to `http://localhost:3000/@<SHORTNAME>/entities/<ENTITY_UUID>`
1.  Test out the editor
=> Fix Entity Editor

packages/hash/frontend/src/blocks/page/MentionView/MentionDisplay.tsx, packages/hash/frontend/src/blocks/page/createSuggester/MentionSuggester.tsx, packages/hash/frontend/src/components/hooks/useReorderPage.ts, packages/hash/shared/src/graphql/types.ts
The mentions selector was broken by changes on `dev/links`. This fixes them, and completes a number of TODOs encountered during.
- [Asana task](https://app.asana.com/0/1203301853897838/1203433977257882/f) _(internal)_
See commits
No
None to my knowledge.
1.  Try the mentions menu
=> Fix mentions

packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/graphql/resolvers/knowledge/org/create-org.ts, packages/hash/api/src/model/ontology/data-type.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts, packages/hash/frontend/src/blocks/page/BlockContextMenu/LoadEntityMenuContent.tsx, packages/hash/frontend/src/blocks/page/Comments/CreateBlockCommentButton.tsx, packages/hash/frontend/src/components/hooks/useReorderPage.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/entity-editor-context.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section/property-table/use-row-data/generate-property-rows-from-entity/generate-property-row-recursively.ts, packages/hash/integration/src/tests/integration.test.ts, packages/hash/integration/src/tests/model/aggregation.model.test.ts, packages/hash/search-loader/package.json, packages/hash/search-loader/src/index.ts, packages/hash/subgraph/package.json, yarn.lock
We weren't fixing lints as we went due to the sheer quantity of errors in the middle of the process. This PR now fixes lints, and we expect the lint job in CI to pass.
- [Asana task](https://app.asana.com/0/1203301853897838/1203361740074436/f) _(internal)_
See commits
No
- Fix any remaining failures in CI
- Cleanup
- Merge
- See CI
See CI
This PR
=> Fix Lints in dev/links

packages/hash/api/src/model/knowledge/comment.model.ts, packages/hash/frontend/src/blocks/page/Comments/CommentThread.tsx
=> Fix comments

packages/hash/api/codegen.yml, packages/hash/api/src/graphql/resolvers/knowledge/page/update-page-actions.ts, packages/hash/api/src/graphql/typeDefs/knowledge/block.typedef.ts, packages/hash/api/src/graphql/typeDefs/knowledge/comment.typedef.ts, packages/hash/api/src/graphql/typeDefs/knowledge/entity.typedef.ts, packages/hash/api/src/graphql/typeDefs/knowledge/page.typedef.ts, packages/hash/frontend/codegen.yml, packages/hash/frontend/src/blocks/page/BlockContextMenu/BlockContextMenu.tsx, packages/hash/frontend/src/blocks/page/BlockContextMenu/LoadEntityMenuContent.tsx, packages/hash/frontend/src/blocks/page/BlockHandle.tsx, packages/hash/frontend/src/graphql/queries/knowledge/entity.queries.ts, packages/hash/integration/codegen.yml, packages/hash/shared/codegen.yml, packages/hash/shared/src/entityStore.ts, packages/hash/shared/src/entityStorePlugin.ts, packages/hash/subgraph/src/types/element.ts
We were missing even more GraphQL scalar types. I have updated the imports to be more reflective, and fixed the subsequent type errors across the workspace.
I have also removed outdated TODOs and such in drive-bys.
- [Asana task](https://app.asana.com/0/1203301853897838/1203439666002395/f) _(internal)_
- See commits
No
- There are poor typings inside the `entityStore` which need to be improved, it caused issues in development of this PR.
- We are storing child entities nested inside a properties blob of an entity? I expect this to cause problems in the near future now that we actually are trying to abide by the type system.
- The comment and other special GraphQL types still have nested recursive entities within them, but the typings are broken.
- Standard tests, `yarn test`
1.  `yarn …
=> Fixups to GraphQL

packages/hash/api/codegen.yml, packages/hash/api/src/graphql/resolvers/knowledge/entity/entity.ts, packages/hash/api/src/graphql/typeDefs/knowledge/entity.typedef.ts, packages/hash/frontend/codegen.yml, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/knowledge-shim.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolCreateEntity.ts, packages/hash/frontend/src/graphql/queries/knowledge/entity.queries.ts, packages/hash/integration/codegen.yml, packages/hash/shared/codegen.yml
This PR refactors the `createEntity` GQL mutation to accept an optional `linkMetadata` parameter which lets callers create link entities.
- [Asana task](https://app.asana.com/0/1203301853897838/1203438053318775/f) _(internal)_
See commits.
The GQL docs have been updated.
None.
1. Follow the instructions to run the HASH App using `yarn dev`
2. Log in to the frontend
3. Go to the GQL playground (at localhost:5001/graphql)
4. Create a link entity using `createEntity`. For example to create an org membership:
```GraphQL
mutation createOrgMembershipQuery($properties: JSONObject!, $linkMetadata: LinkMetadata!) {
createEntity(
entityTypeId: "http://localhost:3000/@example-org/types/entity-type/org-membership/v/1"
properties: $properties
linkMetadata: $linkMetadata
)
}
```
```JSON
{
"properties": …
```
=> Refactor `createEntity` GQL mutation to enable link entity creation

packages/hash/subgraph/src/stdlib/edge/link.ts
There was a TODO in the code to get around a temporary solution that was added to ensure correctness. This is now unblocked and we can have a consistent (and faster) implementation to look for incoming links using their edge kinds by directly looking in the edge set, rather than looking through the complete edge set.
- [Asana task](https://app.asana.com/0/1201095311341924/1203448398358926/f) _(internal)_
See diff, is small
No
None
- No automated tests to my knowledge, but the function is used inside `lib/org.ts`, and as demonstrated below, the code using that hook continues to work.
1.  Try X
1.  Confirm that Y
=> Simplify Subgraph lib function

packages/hash/api/src/graphql/createApolloServer.ts, packages/hash/api/src/graphql/typeDefs/knowledge/user.typedef.ts
This PR fixes an incorrect default value in the GQL schema. In addition, it makes the GQL playground available in a production environment.
=> Fix incorrect default value in the GQL schema, make GQL playground accessible in prod

packages/hash/frontend/src/pages/api/ory/[...paths].api.ts
Simple fix to allow for cookie domain rewrite in a production environment using subdomains
=> Fixes for hosted instance

packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs
We weren't appropriately checking the `Dependency` status which meant that we sometimes were not traversing dependencies as intended.
Test the app as normal please, make sure to run locally as deployments do not redeploy the backend
=> Fix dependency resolution

packages/hash/frontend/src/pages/[account-slug]/types/entity-type/array-data-type-child.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/array-data-type-menu.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/data-type-badge.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/data-type-selector.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/property-type-utils.ts
This PR improves the UX when creating array data types.
- [Asana task](https://app.asana.com/0/1203312852763953/1203481015428204/f) _(internal)_
- Prevent popper from open to the side;
- Trigger a window resize event whenever a new data type is added/removed so that the popper component recalculates its position;
- Add expand/collapse animations to data types when adding/removing them from the schema;
- Add expand/collapse width animation to the prefix ("CONTAINING", "OR", etc...) container.
https://www.loom.com/share/efa8cb19fc414afb9a0e36efed612c66
=> Creating Array Data Types UX improvements 

apps/hashdotdev/src/components/HiringBanner.tsx
Updates hiring banner to reflect current focuses.
---
- https://app.asana.com/0/0/1203468941620572
=> Update hiring banner

packages/hash/frontend/src/pages/[account-slug]/types/entity-type/array-data-type-menu.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/delete-data-type-modal.tsx
This PR implements a deletion confirmation modal for arrays when creating a custom property type.
- [Asana task](https://app.asana.com/0/1203312852763953/1203480092863705/f) _(internal)_
=> Array property type deletion confirmation modal

packages/graph/hash_graph/lib/graph/src/shared/identifier/knowledge.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
As agreed in https://github.com/hashintel/hash/pull/1604#discussion_r1042221384 this renames the system time to transaction time
- https://github.com/hashintel/hash/pull/1604#discussion_r1042221384
- [Asana task](https://app.asana.com/0/1203363157432081/1203505325130330/f) _(internal)_
- #1606
=> Temporal versioning: Rename `system_time` to `transaction_time`

packages/hash/frontend/src/shared/layout/layout-with-header/actions-dropdown.tsx, packages/hash/playwright/tests/page-creation.spec.ts
This PR fixes ❌ in CI for Playwright tests ([example](https://github.com/hashintel/hash/actions/runs/3658090452/jobs/6182439798)).
- [Asana task](https://app.asana.com/0/1203301853897838/1203429129383876/f) _(internal)_
- Make Playwright tests a required check
CI
=> Fix Playwright tests

packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/shared/identifier/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/conditional.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/select_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/query/filter.rs
With temporal versionings, the unit tests were not passing. This ensures PR adjusts the tests and fixes some minor issues introduced in previous PRs
- [Asana task](https://app.asana.com/0/1203363157432081/1203505325130326/f) _(internal)_
- #1626 
- Implement `From` conversion on timespans for ranges
- Fix duplicated output for `"decision_time"` conditions
- Fix unit tests
=> Temporal versioning: Fix unit tests

packages/graph/hash_graph/tests/integration/postgres/links.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
Similar to #1629, this fixes the Graph integration test suite
- [Asana task](https://app.asana.com/0/0/1203505325130327/f) _(internal)_
- #1629
=> Temporal versioning: Fix integration tests

packages/hash/external-services/kratos/kratos.dev.yml, packages/hash/external-services/kratos/kratos.prod.yml
- #1635 
1.  Checkout the branch and start locally
1.  create user
1.  query `sessions` in kratos db
=> Three year sessions for kratos

packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs
Hotfix to fix an error responsible to return a wrong subgraph
- [Slack discussion](https://hashintel.slack.com/archives/C03F7V6DU9M/p1670949225223959) _(internal)_
=> Fix decision time not selected on all entity tables

packages/hash/api/src/graphql/resolvers/knowledge/page/page.ts, packages/hash/api/src/graphql/resolvers/ontology/entity-type.ts, packages/hash/api/src/graphql/resolvers/ontology/property-type.ts, packages/hash/api/src/model/util.ts, packages/hash/api/src/task-execution/index.ts, packages/hash/frontend/src/blocks/page/MentionView/MentionDisplay.tsx, packages/hash/frontend/src/blocks/page/createEditorView.ts, packages/hash/frontend/src/blocks/page/createSuggester/MentionSuggester.tsx, packages/hash/frontend/src/pages/entity-editor.page.tsx, packages/hash/frontend/src/shared/layout/layout-with-header/actions-dropdown.tsx, packages/hash/frontend/src/shared/layout/layout-with-sidebar/account-page-list/account-page-list.tsx, packages/hash/frontend/src/shared/routing/route-page-info.tsx, packages/hash/integration/src/tests/graph/ontology/primitive/data-type.test.ts, packages/hash/integration/src/tests/graph/ontology/primitive/entity-type.test.ts, packages/hash/integration/src/tests/graph/ontology/primitive/property-type.test.ts, packages/hash/integration/src/tests/model/knowledge/block.model.test.ts, packages/hash/integration/src/tests/model/knowledge/entity.model.test.ts, packages/hash/integration/src/tests/model/knowledge/link-entity.model.test.ts, packages/hash/shared/src/types.ts
This PR removes the `brand` function after it turning out to be too permissive. We would need further constraints for the casting to be correct
=> Remove brand function

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs
Strongly typed paths are great, but this leads to issues as soon as variables are passed as parameters
- [Slack discussion](https://hashintel.slack.com/archives/C03F7V6DU9M/p1671459440212509) _(internal)_
=> Lift type constrains on query path tokens

packages/graph/hash_graph/bench/benches/representative_read/knowledge/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/query/filter.rs
With #1684 and #1685 a bunch of functions are now unused and those should be removed
- [Asana task](https://app.asana.com/0/1203363157432084/1203449432963800/f) _(internal)_
- #1684
- #1685
=> Remove unused functions previously used in GET endpoints

packages/README.md
Updates an image link to correct a typo within the original.
=> Update `/libs` banner image to correct for a typo

blocks/README.md, packages/hash/README.md
Fixes an incorrect assertion in the HASH app README around where blocks might be found, and makes other minor improvements to our docs around blocks.
=> Update docs around blocks

packages/hash/design-system/package.json, packages/hash/design-system/src/text-field.tsx
Matches the text field success state to the design
- [Asana task](https://app.asana.com/0/1203363157432094/1203410466759003/f) _(internal)_
- [Figma](https://www.figma.com/file/gydVGka9FjNEg9E2STwhi2/HASH-App?node-id=4100%3A209235&t=GKersGbUTxovUN1d-4) _(internal)_
=> Correct success state for text field

.github/workflows/rust.yml, apps/README.md, libs/README.md, packages/README.md, packages/graph/migrations/README.md, packages/hash/api/src/graphql/resolvers/task-executor/generation.ts, packages/hash/frontend/src/pages/signup.page/signup-intro.tsx
Updates our READMEs to reflect the current state of the repository, and fixes a number of styleguide violations.
=> Improve repo docs

packages/graph/hash_graph/lib/interval-ops/src/interval.rs
The `Interval::merge` operation currently returns an iterator, which always has a single value. Instead, we can return the value directly.
- Change the return value of `Interval::merge` from `impl ExactSizeIterator<Item = Self>` to `Self`
- The Rust compiler
- The unit tests of `Interval` were adjusted to use only a single value instead of an iterator
=> Change return value of `Interval::merge` to always return a value

packages/graph/hash_graph/lib/interval-ops/src/bounds.rs, packages/graph/hash_graph/lib/interval-ops/src/interval.rs
A minor change to slightly improve the in-code comments on how bounds are compared
=> Improve comments in bound comparison logic

packages/hash/api/src/index.ts, packages/hash/api/src/storage/index.ts
Fix a typo i somehow messed up in 2 different ways :laughing:
=> setupFileProxyHandler typo

.trunk/trunk.yaml
We encountered an error without any information when trying to merge a PR with trunk.io. This PR attempts to fix that issue by adding more information to the configuration file and removing empty sections.
=> Attempt to fix trunk.io merge queue

apps/hash-frontend/src/components/grid/utils/draw-chip-with-icon.ts, apps/hash-frontend/src/components/grid/utils/draw-chip.ts, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/cells/link-cell.tsx, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/cells/linked-with-cell.tsx, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/cells/linked-with-cell/linked-entity-list-editor.tsx, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/types.ts, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/use-create-get-cell-content.ts, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/use-rows.ts, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/chip-cell.tsx
This PR supports "Anything" as expected entity type on links table at entity editor visually and functionally. 
- [Asana task](https://app.asana.com/0/1203543021352041/1203784294156174/f) _(internal)_
- Add `borderColor` support to `drawChip` util of `Grid` component
- Add `isList` value to `LinkRow` to help rendering list specific visuals (e.g. List icon) 
- Improve `maxItems` logic on links table by implementing `maxItems === undefined` means "endless"
1.  Create an entity type with a link has "Anything" as it's expected type
1.  Create an entity from that entity type
2. Confirm that link with expected type "Anything" works normally.
=> Fix crash when creating an entity for an entity type with an "anything" link

.github/workflows/hash-backend-cd.yml, apps/hash-external-services/docker-compose.prod.yml, infra/terraform/README.md
As flagged in https://github.com/hashintel/hash/pull/1931#issuecomment-1402284288 I missed a few locations to update in https://github.com/hashintel/hash/pull/1931
=> Fix path to hash-graph `Dockerfile`

.github/workflows/hash-backend-cd.yml, README.md, apps/hash-frontend/src/pages/index.page.tsx, apps/hash-graph/README.md, apps/hash/README.md, apps/hashdotdev/src/_pages/blog/0003_one-principle.mdx, apps/hashdotdev/src/_pages/blog/0010_error-stack-update-0-2.mdx, apps/hashdotdev/src/pages/index.page.tsx
Updates `packages/hash` to `apps/hash` in various places throughout the repo.
=> Update refs to `/packages/hash` with `/apps/hash` 

.github/scripts/rust/Makefile.toml, .github/scripts/rust/setup.py, apps/engine/Makefile.toml, apps/hash-graph/Makefile.toml, libs/deer/Makefile.toml, packages/libs/error-stack/Makefile.toml
We run the CI in two stages:
1. In the pull request
2. Before merging
Only if (1) passes, the second stage can be entered. This PR speeds up (1) significantly by only running a subset of possible tests, while (2) will still test everything as before. This will make iterations much faster.
This mainly is an experiment and may require further discussion and observations.
=> Significantly speed up Rust CI in PRs

infra/docker/api/prod/Dockerfile, infra/docker/frontend/prod/Dockerfile
In #1937 a few changes were missed. This PR attempts to fix those.
=> Fix Backend CD Dockerfiles

.github/workflows/canary-release.yml
Adds missing steps to the canary release flow, discovered after testing it out in https://github.com/blockprotocol/blockprotocol
=> Add missing steps to canary release flow

infra/terraform/modules/postgres/postgres.tf
This PR bumps the used postgres version in our infrastructure. This change has already been applied.
=> Bump Postgres version

.github/scripts/rust/setup.py
We are going to publish the `antsi` crate introduced in #2018.
- [Asana task](https://app.asana.com/0/1202805690238892/1203893818926461/f) _(internal)_
=> Publish the `antsi` crate

.github/workflows/rust.yml
This reverts commit eddd15946265e9010e0c41334b07e734002cfc8b.
=> Revert "Temporarily disable `SemVer check` job"

apps/hash-frontend/src/pages/[shortname]/types/entity-type/[entity-type-id].page.tsx, apps/hash-frontend/src/pages/[shortname]/types/entity-type/[entity-type-id].page/use-entity-type-value.tsx
This fixes a bug where the entity type editor state would 'resync' with the persisted entity type when you created a new link type (as this is an entity type), which would reset the form. This was most obvious where it wouldn't add the newly created link type to your entity type, but it was actually a full form reset. 
- [Asana task](https://app.asana.com/0/1203623179643281/1203936594749424/f) _(internal)_
None
`useEntityTypeValue` now only calls `onCompleted` when the versioned URI of the entity type has changed, even if the identity of the entity type stored in context has changed. I've separated the state management of property types/entity types in this hook to make that simpler. 
No
None
None
None
1. Create a link entity type
2. Ensure it is added to the entity type in a draft state …
=> Prevent entity type editor reseting when creating link types

infra/terraform/README.md, infra/terraform/modules/hash_application/graph.tf
This PR updates the ECS health check for the graph as a follow up to #2038 
As a drive-by I've adjusted the readme for the infrastructure to account for the new migration strategy.
Let's wait to merge this until the backend is fully deployed again
=> Update ECS health checks

infra/docker/api/prod/Dockerfile
We forgot to adjust the API dockerfile after #2059, this fixes it for the CD job.
=> Fix API dockerfile missing a dependency

libs/deer/Cargo.toml, libs/deer/README.md, libs/deer/desert/README.md, libs/deer/json/Cargo.toml, libs/deer/json/README.md, libs/deer/macros/Cargo.toml, libs/deer/macros/README.md
Update the `README.md` and `Cargo.toml` to prepare for the initial reservation of crate names.
=> `deer`: update metadata

blocks/countdown/package.json, blocks/timer/package.json
This PR prepares for using https://github.com/hashintel/hash/pull/2043
- [Asana task](https://app.asana.com/0/1203358502199087/1203388867587773/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C02LG39FJAU/p1676559166581709) _(internal)_
=> Change ownership of two blocks

.github/workflows/hash-backend-cd.yml, infra/terraform/hash/main.tf, infra/terraform/hash/prod-usea1.tfvars, infra/terraform/modules/hash_application/graph.tf, infra/terraform/modules/hash_application/main.tf, infra/terraform/modules/hash_application/type_fetcher.tf, infra/terraform/modules/hash_application/variables.tf
This PR adds the type fetcher service to our production terraform config.
I cheated a little by already deploying this in production.
- [Asana task](https://app.asana.com/0/1203623179643281/1203893826309840/f) _(internal)_
- Adds type fetcher in terraform module for the app
- Builds the container in CD
Look at hosted instance!
=> Add type fetcher to production infra

apps/hash-graph/bin/cli/src/subcommand/server.rs
With the type fetcher in place we can now completely remove the stopgap solution.
- [Asana task](https://app.asana.com/0/1203543026679380/1203843814258959/f) _(internal)_
- Removes the stopgap setup when running with the `"type-fetcher"`-feature
Remove the feature flag, so we completely can remove the solution
=> Remove stopgap-setup when running with the type fetcher

apps/hash-graph/Makefile.toml
I accidentally removed this section in https://github.com/hashintel/hash/pull/2073. This reverts this change
- https://github.com/hashintel/hash/pull/2073
- [Asana task](https://app.asana.com/0/1203193968491715/1203958456055101/f) _(internal)_
=> Don't run doc-tests in production builds

apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
The name `DependencyContext` and related structs is outdated and misleading. We decided to rename it to `TraversalContext` to better reflect the logic it's encapsulating.
- #1854 
- Rename `DependencyContext` to `TraversalContext`
- Rename `DependencyMap` to `TraversalMap`
- Rename `DependencyStatus` to `TraversalStatus`
- Update documentation to use the new naming scheme
- Drive-by: Copy over and adjust comments, which were missed in #1848
This is an internal change only. Internal documentation has been adjusted
=> Rename `Dependency` to `Traversal`

apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
We currently have a bug in the traversal logic, which happens due to optimization. This PR removes the optimization and uses a plain recursion
- [Asana task](https://app.asana.com/0/1203623179643287/1203783495017463/f) _(internal)_
- [Asana task](https://app.asana.com/0/0/1204117845662860/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C03F7V6DU9M/p1678107081222519) _(internal)_
- [Move current implementation to unfold loop instead of recursive calls](https://app.asana.com/0/1203623179643290/1204117845662864/f)
Basically every test, which is using the traversal logic
=> Remove optimization path in traversal logic

blocks/ai-image/src/app/generate-image.tsx, blocks/ai-image/src/app/generate-image/image-preview.tsx
This PR makes fixes to the AI Image block in WP.
=> `AI Image` Wordpress fixes

.cargo/config.toml, .github/scripts/rust/setup.py
With the sparse registries now being stabilized, we should enable this feature to speed up CI times
- [Rust 1.68 announcement post](https://blog.rust-lang.org/2023/03/09/Rust-1.68.0.html#cargos-sparse-protocol)
=> Use sparse cargo profile

.github/renovate.json
We want a unified commit message for all dependencies, thus, this is an attempt to modify the commit messages for Rust crates
=> Tweak commit message for Rust crates

.github/renovate.json
Renovate supports the GitHub Merge Queue, so we can enable automerge again
- #1923 
---
- https://app.asana.com/0/0/1204143704715742
- https://app.asana.com/0/0/1204138539312008
=> Use automerge for renovate PRs

.github/workflows/ci.yml, package.json
Implements the same change as https://github.com/blockprotocol/blockprotocol/pull/1175 in this repo – see the rationale there.
=> Remove Changeset linting step from CI workflow

libs/README.md
Fixes a broken link in the repo docs.
=> Fix broken `sarif` lib link

.github/scripts/rust/setup.py
=> Remove outdated comment in `setup.py`

packages/graph/hash_graph/type-defs/status-payloads.ts
#1810 accidentally introduced a stray file during rebases. This removes it
=> Remove stray file

libs/@hashintel/design-system/README.md
Very simply adds a link to the Storybook associated with the `design-system`, in its README.
=> Add Storybook link to `design-system` package README

blocks/image/src/components/media.tsx, blocks/video/src/components/media.tsx
This PR adds JSON LD descriptions for the image/video block.
- [Asana task](https://app.asana.com/0/1203801045329780/1204217934265155/f) _(internal)_
N/A
- Add a JSON LD script tag for image block setting url/contentUrl to the src of the image, and description to the caption
- Add a JSON LD script tag for video block setting url/contentUrl to the src of the video, and description to the caption
N/A
**Please see limitations outlined in Asana**
**Please see limitations outlined in Asana**
None
Check the HTML output of the blocks. 
We'll check how the output is recognised by bots later.
=> Add JSON LD descriptions for image/video blocks

blocks/table/package.json, blocks/table/src/components/grid/get-scrollbar-width.ts, blocks/table/src/components/grid/grid.tsx, yarn.lock
This PR fixes horizontal scrollbar behavior on table block.
- [Asana task](https://app.asana.com/0/1204000740778938/1204224367231751/f) _(internal)_
Visual confirmation (as shown as the demo below)
https://user-images.githubusercontent.com/39553853/227569977-81d3ca94-9789-4dad-a796-40e60414d641.mov
=> Fix `Table` block horizontal scrollbar issue

.github/renovate.json
Some crates are almost always updated at the same time or should be updated together
=> Add several Rust crate groups to renovate.json

.github/pull_request_template.md, .gitignore, .prettierignore, blocks/README.md, blocks/ai-chat/package.json, blocks/ai-chat/src/types/generated/ai-chat-block.ts, blocks/ai-chat/src/types/generated/ai-chat-request-message.ts, blocks/ai-chat/src/types/generated/ai-chat-response-message.ts, blocks/ai-chat/src/types/generated/shared.ts, blocks/minesweeper/package.json, blocks/minesweeper/src/types/generated/block-entity.ts
A couple of small DX improvements suggested in recent weeks:
1. Since the introduction of the new codegen https://github.com/blockprotocol/blockprotocol/pull/1158 we have been ignoring auto-generated block type files, because the linting pipeline was broken for them:  `yarn deduplicate` would run _after_ prettier, which triggered `codegen` – it's a `postinstall` and `yarn deduplicate` does an install – producing the unformatted file again. This PR fixes that by renaming the dedup script so that it comes before prettier, un-ignores the block files and adds the previously ignored types (for `minesweeper` and `ai-chat`).
2. Includes a section in the PR template on published packages. Ideally we would have an automated check for 'have you modified a published package'  but we'll need to write …
=> Un-ignore block generated types files, publish question in PR template

blocks/faq/package.json
=> Fix FAQ block display name

.github/ISSUE_TEMPLATE/bug-report-hash-core.yml
Realized to be missing while responding to user messages in Discord.
=> Add GitHub Issue reporting form for HASH Core

apps/hash-graph/Cargo.lock, apps/hash-graph/Cargo.toml
`libc` filed a new release, which fixes the issue with `socket2`.
This PR:
=> Update `libc` to `0.2.141`

apps/hashdotdev/src/_pages/blog/0001_block-design.mdx, apps/hashdotdev/src/_pages/blog/0005_build-blocks-in-any-language.mdx
Fixing broken img sources on blog posts.
1.  Confirm that these two blog posts are working: https://hash.dev/blog/block-design - https://hash.dev/blog/build-blocks-in-any-language
=> Fix broken image sources on blog posts

apps/hash-graph/lib/graph/src/snapshot/entity/batch.rs
This was forgotten in #2398 
This PR:
=> Fix `entity_link_edges_tmp` not being dropped on commit

apps/hash-frontend/package.json, apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-page-list/page-tree-item.tsx, blocks/address/package.json, blocks/table/package.json, libs/@hashintel/type-editor/package.json, tests/hash-playwright/tests/page-navigation.spec.ts, yarn.lock
This PR fixes not working show/hide subpages button on sidebar.
- [Asana task](https://app.asana.com/0/1203179076056209/1203857507057423/f) _(internal)_
- Updates `rooks` version to fix this issue 
- Adds test for testing this functionality
`useLocalstorageState` function from `rooks` was not actually supporting calling the setState function like `setState(current => new)`. While debugging, I realized that setState runs twice. And because the specific setState here is the “Toggle dropdown” one, it was toggling it twice. Which means nothing changes.
`rooks` fixed the issue here: https://github.com/imbhargav5/rooks/releases/tag/rooks%407.6.1, so just updating the rooks version fixed the issue
This PR:
- `page-navigation.spec.ts`
1.  Try …
=> Fix broken subpage show/hide button on sidebar.

apps/hash-frontend/src/blocks/page/component-view.tsx, apps/hash-frontend/src/components/remote-block/remote-block.tsx
This restores text editing capability on pages after blocks were updated to BP 0.3
- [Asana task](https://app.asana.com/0/1204260760205594/1203978096566301/f) _(internal)_
- N/A
Update the hook module implementation to check for the correct "path" argument for hook messages to indicate text capability. 
This PR:
No
N/A
N/A
N/A
1.  Create a page
2. Attempt to edit some text
=> Restore text editing in page

apps/hash/README.md
We have a requirement on `docker compose version`, which is not documented, this adds this to the README.
This PR:
=> Mention minimum docker compose version

.github/workflows/ci.yml, apps/hash-agents/app/__init__.py, apps/hash-agents/app/logger.py, apps/hash-agents/package.json, apps/hash-agents/poetry.lock, apps/hash-agents/pyproject.toml, apps/hash-agents/turbo.json, package.json, turbo.json
This adds the `black` formatter for `hash-agents`' Python code
- [Asana task](https://app.asana.com/0/1204260760205594/1204431665478215/f) _(internal)_
- #2458 
- #2460
- Add `black` as dev-dependency
- Add `fix:black` and `lint:black` as script
- Run `lint:black` from CI
- Add `fix:black` to lint-staged
This PR:
=> Add `black` as Python formatter

apps/hash-graph/lib/graph/src/api/rest/test_server.rs
#2454 introduced the functionality to delete data in a test environment. This exposes the functionality to the `test-server`
- [Asana task](https://app.asana.com/0/1204260760205594/1204407146528687/f) _(internal)_
- #2454
This PR:
=> Expose deletion to `test-server` API

apps/hash-agents/docker/Dockerfile, apps/hash-agents/package.json, apps/hash-agents/poetry.lock, apps/hash-agents/pyproject.toml
Instead of using a single `dev` group it's easier to reason about the purpose when using the group feature with different names
- [Asana task](https://app.asana.com/0/1204260760205594/1204431665478215/f) _(internal)_
This PR:
=> Use `group` section for tools and production

apps/hash-agents/app/__init__.py, apps/hash-agents/app/agents/__init__.py, apps/hash-agents/app/agents/__main__.py, apps/hash-agents/app/agents/template/__main__.py, apps/hash-agents/poetry.lock, apps/hash-agents/pyproject.toml
This adds runtime validations to functions to assert the correct input/output
- [Asana task](https://app.asana.com/0/1204260760205594/1204431665478222/f) _(internal)_
This PR:
=> Use `beartype` decorators for functions

blocks/shuffle/package.json
Makes the `shuffle` block the `Shuffle` block, fixing a minor inconsistency.
Changes the description and name of the `Shuffle` block.
This PR:
=> Capitalize 'shuffle' in `Shuffle` block name

apps/hash-agents/app/agents/__main__.py, apps/hash-agents/app/agents/semantic-search/__main__.py, apps/hash-agents/app/agents/semantic-search/io_types.ts, apps/hash-agents/poetry.lock, apps/hash-agents/pyproject.toml
This prototype adds a QA prompt on top of our vector DB index (qdrant). The agent is able to answer questions and operate on data from our graph. It is able to answer general questions about the information without needing to do any filter/preselections.
When starting the app through external services and `yarn dev`, the realtime app and vector-loader app should automatically start as well, which are the base for running this agent.
With a running HASH app, you can create some entities, either by typing on a page or by create an entity type and subsequently creating entities. The changes are automatically indexed, and you'll be able to execute arbitrary queries by running the following command from the `/apps/hash-agents` location:
```console
$ poetry run python -m app.agents …
```
=> Natural language semantic entity search

apps/hash-frontend/src/pages/api/block-generator/initialize-container.api.ts, apps/hash-frontend/src/pages/api/block-generator/install-dependencies.api.ts, apps/hash-frontend/src/pages/block-generator.page.tsx, apps/hash-frontend/src/pages/block-generator/demo-live-editor.tsx
This PR simplifies dependency installation in the Generate block prototype.
=> Generate block prototype: Speed up dependency installation

apps/hash-frontend/src/shared/command-bar.tsx, tests/hash-playwright/package.json, tests/hash-playwright/tests/shared/runtime.ts
Fixes a few things to do with Playwright tests:
1. Fixes the `test` command in the playwright package to actually run all tests rather than apply a filter. This command was unused until #2463 which is why the (long-standing) filter has been uncovered
2. Adds a custom message to the 'unexpected console message' check to make it clear this is what is happening (it's otherwise completely unclear that the failure is because of console messages)
3. Fixes one such unexpected console message that crept in since the tests weren't being run
- [Asana task](https://app.asana.com/0/1204260760205594/1204355839255075/f) _(internal)_
This PR:
1.  Check that Playwright tests run and pass
**Output without custom message**
**Output with custom message**
=> Fix Playwright test script, improve output, fix failing test

apps/hash-frontend/next.config.js, apps/hash-frontend/package.json, apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx, apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/entity-type-description.tsx
This PR adds a description field to the entity type editor page, similarly to how it was implemented in blockprotocol.
- [Asana task](https://app.asana.com/0/1204274556967336/1204485873929278/f) _(internal)
- Used `EditableField` from `@hashintel/block-design-system` for the description field.
This PR:
1.  Create an entity type;
2.  Edit and publish description;
3.  Make sure it persists through reload;
=> Add editable description to the entity type editor page

tests/hash-backend-integration/src/tests/setup.ts, tests/hash-backend-integration/src/tests/subgraph/fail/wrong-version.jsonl, tests/hash-backend-integration/src/tests/subgraph/simple.test.ts, tests/hash-backend-integration/src/tests/test-server.ts
To test various snapshots and to avoid conflicts between them and other test data the BE integration test require the ability to reset the Graph. This PR adds functions to remove existing entities, types, and accounts and provide a convenient function to reset the Graph to the provided Snapshot.
- [Asana task](https://app.asana.com/0/1204274556967336/1204549651666223/f) _(internal)_
- Move test-server function to `test-server.ts`
- Provide functions to delete entities, types, and accounts
- Provide convenient function to wipe the Graph and restore a provided snapshot
This PR does not modify any publishable blocks or libraries, or modifications do not need publishing.
The changes in this PR is internal and does not require a docs change, however, documentation for the functions has been …
=> Allow resetting database from BE integration tests

apps/hash-frontend/src/components/hooks/use-logout-flow.ts
This PR fixes a runtime error that was thrown when logging out of the application. The cause was that the `client.resetStore()` not only clears the apollo client cache, but also refetches all active queries. This means that any queries which require an authenticated user (such as the `getAccountPagesTree` query) would throw authentication erros.
What I've done to address this is to use `client.clearStore()` instead (which only clears the apollo client cache), and added a manual call to `refetchUser` to update the state in the `AuthInfo` context provider.
- [Asana task](https://app.asana.com/0/1204260760205594/1204355839255065/f) _(internal)_
This PR:
Manual testing
1. Checkout the branch
2. Start the developer environment
3. Log in with a user, and log out
4. …
=> Fix logout runtime error

.github/actions/build-docker-images/action.yml, .github/workflows/ci.yml
We encountered an issue where BE integration tests and PW tests were skipped as a dependency job did not succeed. This implied a fulfilled requirements-check and the PR would have been able to be merged.
- [Asana task](https://app.asana.com/0/1204274556967336/1204578032052234/f) _(internal)_
- Make sure both jobs are running always
This PR:
=> Always run BE integration tests and PW tests

apps/hash-api/src/graph/knowledge/primitive/entity.ts, apps/hash-api/src/graph/ontology/primitive/data-type.ts, apps/hash-api/src/graph/ontology/primitive/entity-type.ts, apps/hash-api/src/graph/ontology/primitive/property-type.ts, tests/hash-backend-integration/src/tests/test-server.ts
In comparison to the `hash-api`, the BE tests require the ability to read data from the Graph using all structural query features. This adds the functions to support reading the Graph.
- [Asana task](https://app.asana.com/0/1204274556967336/1204549651666230/f) _(internal)_
- #2538 
Adds
- `getDataTypes`
- `getPropertyTypes`
- `getEntityTypes`
- `getEntities`
This PR does not modify any publishable blocks or libraries, or modifications do not need publishing 
The changes in this PR are internal and do not require a docs change
The changes in this PR does not affect the execution graph
=> Support raw reading from the Graph in BE tests

apps/hash-external-services/package.json, apps/hash-external-services/turbo.json, apps/hash-graph/package.json, apps/hash-graph/turbo.json, package.json
While testing https://github.com/hashintel/hash/pull/2554 it was very annoying to run the production images as we have no script for it. This adds scripts similar to what we have in the dev-setup but without the test-server running and with an optimized build.
This PR:
=> Provide yarn script to run production environment

tests/hash-backend-integration/README.md
Creating snapshots is very easy but it's not documented yet.
- [Asana task](https://app.asana.com/0/1204274556967336/1204584047986189/f) _(internal)_
- Add documentation on how to create a snapshot from the Graph
This PR:
- Follow the instructions and verify it's working as expected
=> Add documentation on how to create snapshots from the Graph

apps/hash-api/src/graph/knowledge/primitive/entity/query.ts, apps/hash-api/src/graphql/resolvers/knowledge/entity/entity.ts, apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/use-entity-type-entities-context-value.tsx
This PR adds a `queryEntities` filter to HASH that allows checking against a non-versioned `EntityTypeId` a `EntityTypeBaseUrl`. I am aware we have multiple names for this, but since the query syntax is explicitly for querying entities, I wanted to be explicit about the fact that `EntityTypeBaseUrl` queries for the entity type of the entity.
We should likely not keep adding these cases to the query translator, as it can turn into quite a messy function, this one is quite useful for parts of the frontend.
- Adds `EntityTypeBaseUrl` clause to the `queryEntities` translation function
- Update the frontend entity type 'entities' tab to make use of the new filter (fixing the todo)
- Add warning when querying with empty `queryEntities` `operation`
This PR:
The changes in …
=> Add entity type base URL filter

apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-page-list/account-page-list.tsx
This PR makes it so the subpage list of a parent page is expanded when adding a subpage inside it.
- [Asana task](https://app.asana.com/0/1203179076056209/1203468941620568/f) _(internal)_
This PR:
https://github.com/hashintel/hash/assets/37453800/9c7a176c-1416-43c4-90a3-e2dea4cec96c
=> Auto-expand parent pages in # sidebar when creating sub-pages

README.md, apps/README.md, apps/hash-agents/README.md, apps/hash-ai-worker-py/README.md, apps/hash-ai-worker-ts/README.md, apps/hash-api/README.md, apps/hash-external-services/README.md, apps/hash-frontend/README.md, apps/hash-graph/README.md, apps/intellij-plugin/README.md
Minor improvements to various READMEs, including tidying up of formatting and fixing of a missing link.
=> Improve various READMEs

tests/hash-backend-integration/src/tests/subgraph/friendship.test.ts
This further improves the subgraph integration tests to gain more confidence
- [Asana task](https://app.asana.com/0/1202805690238892/1204165139634977/f) _(internal)_
- Extend existing tests with more assertions
- Add a bunch of test cases with a low resolve depth and make sure the correct records are returned
- Add a test with chained resolve depths (person -> link -> type) as the first more complex example. This is expected to be enhanced in the follow-up PR.
This PR:
- Look at the expected test outputs and make sure these make sense
=> Add a wider range of subgraph integration tests

.github/actions/docker-build-push/action.yml, .github/actions/docker-ecr-login/action.yml, .github/workflows/hash-backend-cd.yml
This PR switches from our secrets-based hardcoded AWS credentials to using our vault instance to get temporary credentials for pushing images.
- [Asana task](https://app.asana.com/0/0/1204675418698206/f) _(internal)_
- Changes actions and workflows related to pushing to ECR
- Driveby todo fixes
This PR:
- Migrate to STS based credentials in terraform
- Automate Terraform plan/apply
- CI/CD
Hard to test manually, This run contains the result from this change https://github.com/hashintel/hash/actions/runs/5089339009 (no effective change)
=> Use Vault for HASH AWS credentials

.github/workflows/tf-apply-hash.yml, .github/workflows/tf-plan-hash.yml, infra/terraform/hash/main.tf, infra/terraform/hash/variables.tf
This PR automates deployment of the HASH infrastructure. 
Pieces of this PR is quite repetitive and can be consolidated (also similar to our internal API deployment infra.)
- [Asana task](https://app.asana.com/0/1203193968491715/1204675418698198/f) _(internal)_
- Moves to STS based Vault user generation in Terraform
- Adds two workflows for apply/plan of the terraform script
This PR:
- Consolidate our scripts together (both GHA and Terraform)
- Perhaps make apply part of the CD workflow we have
- CI/CD
It's hard to test this locally, although you should be able to see https://github.com/hashintel/hash/actions/runs/5092036652?pr=2609 succeed
=> Automate HASH infrastructure deployment

.github/workflows/tf-apply-hash.yml
This is a hotfix for the failed `apply` terraform workflow
=> Fix parens in matrix check

apps/hash-external-services/README.md, apps/hash-external-services/postgres/Dockerfile, infra/terraform/hash/postgres/postgres.tf
This PR bumps PostgreSQL version to 15 for both our docker compose and our hosted infrastructure.
As a drive-by I've added a small service snippet to allow for backups of the docker-compose `postgres` service (which is optional).
- [Asana task](https://app.asana.com/0/1204610208832639/1204727810359042/f) _(internal)_
- [Asana task](https://app.asana.com/0/1204610208832639/1204727810359038/f) _(internal)_
- Changes our Postgres dockerfile to use PG15
- Changes infra to use PG15
This PR:
- Docs about Postgres Backups
- Users of the production compose may have to migrate their DB to the new version somewhat manually (dump DBs and restore them again). This isn't a big issue, but somewhat of a hassle. Should be fairly self-contained, though.
- CI …
=> Bump PostgreSQL to 15

.github/labeler.yml
=> Add `infra/` folder to `infra` label

.github/actions/terraform-exec/action.yml, .github/actions/terraform-plan/action.yml, .github/workflows/tf-apply-hash.yml, .github/workflows/tf-plan-hash.yml
This PR refactors the GH actions to reuse the steps required to prepare/execute Terraform commands. 
The apply/plan workflows now use a composite action which encapsulates all the steps needed to execute/summarize terraform commands.
- [Asana task](https://app.asana.com/0/1204610208832639/1204691860848733/f) _(internal)_
- Refactors github actions for TF
This PR:
- Use this flow in other projects we have that need CI/CD terraform jobs
- CI
You can execute the workflows manually with dispatches, i've executed both here:
https://github.com/hashintel/hash/actions/runs/5176563531?pr=2639 (plan)
https://github.com/hashintel/hash/actions/runs/5176564761?pr=2639  (apply)
=> Refactor GitHub Actions for infra deployment

tests/hash-backend-integration/src/tests/subgraph/friendship.test.ts
This adds test cases to retrieve ontology types if the resolve depths are not zeroed. Zeroed resolve depths are covered in other tests.
- [Asana task](https://app.asana.com/0/1204610208832639/1204749865544745/f) _(internal)_
- https://github.com/hashintel/hash/pull/2637 (tests are expected to fail until the fix is merged)
This PR:
=> Add tests to validate ontology types to exist in subgraph

apps/README.md, apps/hash-external-services/README.md, apps/hash/README.md, blocks/README.md
Updates the `apps`, `apps/hash`, `apps/hash-external-services` and `blocks` READMEs.
=> Update in-repo READMEs

apps/engine/lib/execution/src/package/simulation.rs, apps/engine/lib/execution/src/package/simulation/state/behavior_execution/config.rs, apps/engine/lib/execution/src/task.rs
Just fixes a couple typos and adds a comment
No
- I think? I mean it is a docs change
=> hEngine: Minor comment improvements

infra/terraform/hash/main.tf, infra/terraform/modules/vpc_spoke_peer/README.md
A small follow up to https://github.com/hashintel/hash/pull/2664 to add some documentation for usage of the new module
=> Add example usage for the VPC spoke module

.github/actions/terraform-exec/action.yml, apps/hash-graph/lib/graph/src/store/record.rs, infra/terraform/modules/base_network/main.tf, infra/terraform/modules/base_network/variables.tf, infra/terraform/modules/bastion/main.tf
This PR disables VPC Flow logs as we don't use them for anything for now. 
I've also drive-by pinned the AMI image for the bastion host.
Supersedes https://github.com/hashintel/hash/pull/2675
=> Disable VPC Flow Logs

infra/terraform/README.md
=> Fix typos in `infra/terraform/README.md`

apps/hash-ai-worker-py/poetry.lock, apps/hash-ai-worker-py/pyproject.toml
We have a bunch of dependencies specified for the Python temporal worker but only very few we actually use. There are some packages we're probably going to use in the future but it's easier to add them on demand.
- Remove unused dependencies
- Add missing `dotenv` dependency
This PR:
=> Remove unused Python-worker dependencies

infra/terraform/modules/tunnel/ssh_tunnel.sh
=> Add hint to ssh tunnel that `jq` is required

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/cells/linked-with-cell/linked-entity-list-editor.tsx, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/shared/use-draft-entity-subgraph.ts
This PR fixes the create entity page by updating the delimiter used in draft entity IDs to be `~`.
- [Asana task](https://app.asana.com/0/1204727813960182/1204934288903197) _(internal)_
See commits
This PR:
Checkout the branch, and try creating an entity
=> Fix create entity page

.github/workflows/ci.yml, apps/hash-ai-worker-py/app/activities.py, apps/hash-ai-worker-py/package.json, apps/hash-ai-worker-py/poetry.lock, apps/hash-ai-worker-py/pyproject.toml, apps/hash-ai-worker-py/turbo.json, package.json
While developing within the Temporal Python worker it incredible helped to have `mypy` enabled.
- Relevant documentation for the lints: https://mypy.readthedocs.io/en/stable/config_file.html
- Install `mypy` as dev dependency
- Check `mypy` in CI
=> Add `mypy` configuration for more safe Python dev

apps/hash-api/src/graphql/resolvers/knowledge/entity/entity.ts, apps/hash-frontend/src/blocks/user-blocks.tsx, apps/hash-frontend/src/pages/[shortname]/[page-slug].page.tsx, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/cells/linked-with-cell/entity-selector.tsx, apps/hash-frontend/src/pages/shared/top-context-bar.tsx, libs/@hashintel/query-editor/src/entity-query-editor/utils.ts
Fixes a few bugs in HASH:
1. Querying for all entities was returning nothing because it used the wrong operator – e.g. create an entity type which has a link with no constraints on its destination... previously attempting to create an entity of this type would have no entities in the option for that link
2. The canvas/document toggle was showing in pages where it shouldn't
3. Old blocks (protocol version < 0.3) were being included in the block selector, but they don't work
- [Asana task for canvas toggle](https://app.asana.com/0/1204727813960182/1204934281645543/f) _(internal)_
This PR:
=> Fix querying all entities, hide canvas toggle on non-pages, don't show old blocks

.github/CODEOWNERS
We decided to remove the code ownership for the database migration files for now.
This PR:
=> Remove code ownership for migration files

apps/hash-frontend/src/blocks/page/create-editor-view.ts
Closes https://github.com/hashintel/hash/pull/2606 in favour of cherry-picking the commit there Nate introduced to reduce save frequency.
This PR:
1.  Check that saving in a page still works
=> [H-41] Save less frequently

apps/hash-ai-worker-py/app/typesystem/_schema.py, apps/hash-ai-worker-py/app/typesystem/data_type.py, apps/hash-ai-worker-py/app/typesystem/entity_type.py, apps/hash-ai-worker-py/app/typesystem/property_type.py, apps/hash-ai-worker-py/app/workflows.py, apps/hash-ai-worker-py/poetry.lock, apps/hash-ai-worker-py/pyproject.toml
This implements entity validation by generating dynamic models from the provided schemas.
- https://github.com/hashintel/hash/pull/2695
- https://github.com/hashintel/hash/pull/2696 (CI will fail until merged)
- https://github.com/hashintel/hash/pull/2699
- https://github.com/hashintel/hash/pull/2701
- https://github.com/hashintel/hash/pull/2702 (CI is likely to fail until merged)
- Add an **A**bstract **B**ase **C**lass `Schema` which requires a `create_model` method
- Implement `create_model` on all relevant schemas
- Add a `print_schema` debugging function to test functionality. This function is going to be removed when using the functionality in other places.
This PR:
- There are a few Pydantic v2 Issues and they are linked in the code …
=> H-31: Implement Entity validation for Temporal worker

apps/hash-api/package.json, apps/hash-frontend/next.config.js, apps/hash-frontend/package.json, apps/hash-frontend/src/blocks/on-block-loaded.tsx, apps/hash-frontend/src/blocks/page/block-context-menu/block-context-menu.tsx, apps/hash-frontend/src/blocks/page/block-highlight.tsx, apps/hash-frontend/src/blocks/page/block-view.tsx, apps/hash-frontend/src/pages/[shortname]/[page-slug].page.tsx, apps/hash-frontend/src/shared/get-block-dom-id.ts, apps/hash-frontend/src/shared/layout/layout-with-header/search-bar.tsx, apps/hash-frontend/src/shared/routing/route-page-info.tsx, yarn.lock
In starting to look at frontend performance, I noticed that every page shared a common JS bundle of almost 1MB. 
This is because the root `_app` page imported from some places it shouldn't, including the main Page page.
This PR moves the small functions it needed from those places into a shared location, halving the shared JS from `990kB` to `487kB`. There is more that could be done here, but these are the quick wins.
It also disables some Sentry stuff to cut how much it contributes to the bundle
Also upgrades Ory clients as a drive-by (I was doing this to debug Ory issues, although it doesn't seem to have fixed them)
This PR:
1.  Check things still work. Hopefully this will have an impact on perceived page load times once deployed – it's …
=> Reduce frontend shared JS size. Upgrade Ory clients

.github/workflows/hash-backend-cd.yml
The workflow currently does not run if changed, this PR will change that behavior
=> Trigger workflow if workflow definition changed

.github/actions/warm-up-vercel/action.yml, .github/workflows/warm-up-vercel.yml
Periodically makes a request to key pages in the production frontend to keep Vercel lambdas warm.
This PR:
Here's an example run: https://github.com/hashintel/hash/actions/runs/5553171922/jobs/10141401257?pr=2762
=> H-99: Warm up key frontend pages

apps/hash-api/src/graph/knowledge/primitive/entity.ts, apps/hash-api/src/graph/knowledge/system-types/block.ts, apps/hash-api/src/graph/knowledge/system-types/comment.ts, apps/hash-api/src/graphql/resolvers/knowledge/comment/author.ts, apps/hash-api/src/graphql/resolvers/knowledge/comment/comment.ts, apps/hash-api/src/graphql/resolvers/knowledge/comment/has-text.ts, apps/hash-api/src/graphql/resolvers/knowledge/comment/parent.ts, apps/hash-api/src/graphql/resolvers/knowledge/comment/replies.ts, apps/hash-api/src/graphql/resolvers/knowledge/comment/text-updated-at.ts, apps/hash-api/src/graphql/resolvers/knowledge/comment/update-text.ts, tests/hash-backend-integration/src/tests/graph/knowledge/system-types/comment.test.ts
This PR reduces the time it takes to resolve requests to create, edit and resolve comments, by:
1. Removing unnecessary requests: where we are given an `entityId` by the caller, we were fetching the entity, and then passing the entity into another function, where the other function only used the `entityId` in the first place. This updates such functions to only require the `entityId`.
2. Parallelising requests where they can be – creating a comment previously involved running 5 requests serially. These can be done in 2 batches.
This PR:
- There's a backend integration test for creating a comment.
1.  Visit a page
2. Check that comment operations still work: creating, replying, editing, deleting, resolving a thread
=> H-89: Speed up comment request resolution

.github/labeler.yml
As a follow-up of #2774 / [IN-24](https://linear.app/hash/issue/IN-24) the labels should be properly ordered and a few missing labels should be added.
This PR:
=> H-168: Enhance labels in GitHub

.github/labeler.yml
=> H-168: Fix typo in labels

apps/hash-api/package.json, apps/hash-api/src/graphql/context.ts, apps/hash-api/src/graphql/create-apollo-server.ts, apps/hash-api/src/graphql/resolvers/knowledge/entity/entity.ts, apps/hash-api/src/index.ts, apps/hash-api/src/temporal/index.ts, yarn.lock
To invoke a temporal workflow we require the API to connect to the temporal server. This PR introduces the `TemporalClient` and uses that to call the `inferEntities` workflow (which is not implemented yet).
This PR:
=> H-181: Implement logic to run a workflow from HASH

apps/hash-external-services/turbo.json, apps/hash-integration-worker/.eslintrc.cjs, apps/hash-integration-worker/LICENSE.md, apps/hash-integration-worker/README.md, apps/hash-integration-worker/docker/Dockerfile, apps/hash-integration-worker/package.json, apps/hash-integration-worker/scripts/bundle-workflow-code.ts, apps/hash-integration-worker/src/activities.ts, apps/hash-integration-worker/src/main.ts, apps/hash-integration-worker/src/workflows.ts, apps/hash-integration-worker/tsconfig.json, apps/hash-integration-worker/turbo.json
We need a package to allow communicating between external services like Linear or GitHub to read/write data from/to. As the services should be queued via Temporal and we expect a fair amount of integrations, this is supposed to be a standalone package.
- Create a new package `hash-integration-worker`
- Add a placeholder activity and workflow to be populated in a follow-up PR
This PR:
```
> temporal workflow execute --task-queue integration --namespace HASH --type helloWorldWorkflow
Running execution:
WorkflowId  30bfc5fa-b80a-490b-85ec-c7cadf282d64  
RunId       4b36d284-2e21-4805-9d25-499529892576  
Type        helloWorldWorkflow                    
Namespace   HASH                                  
TaskQueue   integration …
```
=> H-187: Create basic package for integrations

apps/hash-integration-worker/package.json, apps/hash-integration-worker/src/activities.ts, apps/hash-integration-worker/src/main.ts, apps/hash-integration-worker/src/workflows.ts, yarn.lock
To read data from linear we're going to use their node SDK.
This PR:
=> H-189: Implement activities and workflows to read Linear entities

.github/actions/build-docker-images/action.yml, .github/actions/load-docker-images/action.yml, .github/workflows/ci.yml, apps/hash-external-services/docker-compose.yml, apps/hash-external-services/turbo.json, apps/hash-integration-worker/docker/Dockerfile, apps/hash-integration-worker/package.json, infra/terraform/hash/hash_application/main.tf, infra/terraform/hash/hash_application/temporal_worker_integration.tf, infra/terraform/hash/hash_application/variables.tf, infra/terraform/hash/main.tf
To allow the usage of the new integration it needs to be connection in the actual HASH environment
This PR:
=> H-190: Add docker image for integration worker

apps/hash-api/src/graph/linear-types.ts, apps/hash-integration-worker/package.json, apps/hash-integration-worker/src/activities.ts, apps/hash-integration-worker/src/mappings.ts, apps/hash-integration-worker/src/workflows.ts
To insert entities we need to create entities from the linear types. For the existing type definitions this provides mapping functions to convert the typescript types to entities.
This PR:
=> H-201: Implement mapping functions for Linear

apps/hash-integration-worker/src/activities.ts, apps/hash-integration-worker/src/mappings.ts, apps/hash-integration-worker/src/workflows.ts
This implements the initial import from linear to HASH
This PR:
=> H-191: Add linearImport workflow to integration worker

apps/hash-api/src/graph/knowledge/system-types/linear-integration-entity.ts, apps/hash-api/src/graphql/resolvers/index.ts, apps/hash-api/src/graphql/resolvers/integrations/linear/sync-workspaces-with-teams.ts, apps/hash-frontend/src/graphql/queries/integrations/linear.queries.ts, apps/hash-frontend/src/pages/account/integrations/linear/new.page.tsx, apps/hash-frontend/src/pages/account/integrations/linear/select-linear-teams.tsx, libs/@local/hash-graphql-shared/src/graphql/type-defs/integration/linear.typedef.ts
This PR adds a `syncLinearIntegrationWithWorkspace` mutation which links a linear integration to HASH users and orgs that it will sync data to. It also updates the FE to call this mutation when the user has selected the relevant linear teams to sync with a workspace.
This PR:
The table isn't populated with the previous state.
None
1. Go to `/account/integrations` and click "Connect to Linear"
2. Complete the OAuth flow, and select some teams to add to workspaces in the table dropdown
3. Click "Save and continue"
4. Once redirected, the `syncLinearDataWith` links should have been created. You can check the datastore to verify this
=> H-209: Link Linear integration with HASH workspaces

apps/hash-api/src/graph/knowledge/system-types/linear-integration-entity.ts, apps/hash-api/src/graph/knowledge/system-types/linear-user-secret.ts, apps/hash-api/src/graphql/resolvers/integrations/linear/sync-workspaces-with-teams.ts, apps/hash-api/src/integrations/linear.ts, apps/hash-integration-worker/src/activities.ts, apps/hash-integration-worker/src/workflows.ts
When synchronizing a linear account with the workspace we want to trigger the temporal workflow.
This PR:
=> H-193: Trigger workflow when synchronizing Linear with workspace

infra/terraform/hash/main.tf
Add environment variables for prod environment for linear integration
This PR:
=> H-218: Provide Linear variables to prod environment

apps/hash-external-services/docker-compose.yml, apps/hash-external-services/vault/config/storage.hcl
Add a Docker volume for Vault, don’t have it in-memory only (secrets are lost if Docker container rebuilt)
This PR:
=> H-220: Use `file` storage for local vault

apps/hash-integration-worker/src/activities.ts, apps/hash-integration-worker/src/workflows.ts
We don't want to insert the same linear entities if they already exist in the workspace.
This PR:
=> H-214: Avoid re-inserting Linear entities if they already exist in a workspace

.github/workflows/hash-backend-cd.yml
=> H-223: Build and push docker image for integration worker

apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs
Adjusts the structural query compiler to pin the `ontology_temporal_metadata` table to the provided temporal bounds
- #2843 
- Makes it easier to create/read the parameter index for time bounds
- Adjust the compile step to create a condition on transaction time for ontology types
This PR:
=> H-293: Support temporal queries for ontology

apps/hash-api/src/graphql/resolvers/index.ts, apps/hash-api/src/graphql/resolvers/ontology/entity-type.ts, apps/hash-api/src/graphql/resolvers/ontology/property-type.ts, libs/@local/hash-graphql-shared/src/graphql/scalar-mapping.ts, libs/@local/hash-graphql-shared/src/graphql/type-defs/ontology/data-type.typedef.ts, libs/@local/hash-graphql-shared/src/graphql/type-defs/ontology/entity-type.typedef.ts, libs/@local/hash-graphql-shared/src/graphql/type-defs/ontology/property-type.typedef.ts
Exposes the functionality from the backend to the frontend.
- #2850
This PR:
=> H-247: Expose property type and entity type (un-)archival to GraphQL

apps/hash-frontend/package.json, apps/hash-frontend/src/middleware/return-types-as-json.ts, libs/@local/hash-isomorphic-utils/src/system-types/comment.ts, libs/@local/hash-isomorphic-utils/src/system-types/file.ts, libs/@local/hash-isomorphic-utils/src/system-types/hashinstance.ts, libs/@local/hash-isomorphic-utils/src/system-types/linear/issue.ts, libs/@local/hash-isomorphic-utils/src/system-types/linear/organization.ts, libs/@local/hash-isomorphic-utils/src/system-types/linear/shared.ts, libs/@local/hash-isomorphic-utils/src/system-types/page.ts, libs/@local/hash-isomorphic-utils/src/system-types/shared.ts, yarn.lock
#2852 introduced a TypeScript-type generator for system types, but the output was not deterministic.
This is because the JSON representation of ontology types was not stable, because the order of keys in the `properties` and `links` objects can change.
This PR fixes that by making the JSON sorted.
This PR:
1.  Run `yarn dev`
2.  Run `yarn generate-system-types` a couple of times and confirm that no diff is created
=> H-314: Make types' JSON representation stable

infra/terraform/README.md
The list of docker images is outdated. The document should be kept up-to-date as this reflects the required steps to deploy a docker image to production.
This PR:
=> H-222: Extend infra README on existing Docker images

apps/hash-api/src/graph/knowledge/primitive/entity.ts, apps/hash-api/src/graph/knowledge/system-types/page.ts, apps/hash-api/src/graphql/resolvers/knowledge/page/page.ts, apps/hash-frontend/src/blocks/page/page-section-container.tsx, apps/hash-frontend/src/components/hooks/use-account-pages.ts, apps/hash-frontend/src/components/hooks/use-archive-page.ts, apps/hash-frontend/src/graphql/queries/account.queries.ts, apps/hash-frontend/src/pages/[shortname]/[page-slug].page.tsx, apps/hash-frontend/src/pages/shared/top-context-bar.tsx, apps/hash-frontend/src/shared/icons/box-archive-icon.tsx, apps/hash-frontend/src/shared/icons/calendar-icon.tsx, apps/hash-frontend/src/shared/icons/user-icon.tsx, apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-page-list/account-page-list.tsx, apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-page-list/page-menu.tsx, apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-page-list/page-tree-item.tsx, libs/@local/hash-graphql-shared/src/graphql/type-defs/knowledge/page.typedef.ts
This PR updates the "archive page" banner to display the person who archived the page, alongside the timestamp.
- fixes restoring pages, which was previously broken because it wasn't possible to set properties to `false` via the `updateEntityProperties` method in the TS API
This PR:
None
1. Login and archive a page in the sidebar
2. View the updated content of the archived page banner
3. Use the "restore" button to unarchive the page
4. Ensure the "Page Restored!" message is displayed
https://github.com/hashintel/hash/assets/42802102/ce81dea2-31f4-4dca-a282-a32c7aadee84
=> H-69: Update the "archived page" banner

.github/workflows/dispatch-fix.yml
When running the `Fix` workflow the mail address is shown as invalid. This PR changes the name and mail to represent @hashdotai.
This PR:
=> H-380: Set user and mail for CI action

apps/hashdotdev/src/pages/roadmap/technology-tree-data.tsx
Small updates to the tech tree content on the [hash.dev/roadmap](https://hash.dev/roadmap) page.
_None_
_Nothing_
Updates node statuses on the tech tree, corrects and incorrect parent, and adds entity labels.
_None_
_None_
_None_
Check out the preview deployment/make sure linting tests pass.
=> H-239: Update `hash.dev/roadmap` tech tree

.github/renovate.json
With dependencyDashboardApproval set to true globally we can also enable automerge enable globally. The enabled flag is set to true by default and does not need to be set. Also, the anyhow filter does not work properly.
This PR:
=> GEN-70: Simplify renovate configuration

apps/hash-frontend/src/pages/index.page.tsx
Updates the homepage/welcome copy in the HASH app.
=> H-535: Update app welcome screen copy

.github/actions/build-docker-images/action.yml, .github/workflows/rust.yml
The pre-loaded docker images are not used and require a lot of space. This buys us time.
This PR:
=> H-518: Attempt to reduce required memory in CI

.github/actions/build-docker-images/action.yml, .github/actions/load-docker-images/action.yml, .github/workflows/ci.yml, .github/workflows/remove-obsolete-caches.yml, .github/workflows/rust.yml
Utilizes the GHCR to upload images and caches so we don't use up the GHA cache and it's more reliable. Image tags are removed after the branch has hit main.
This PR:
=> GEN-75: Use GHCR to store Docker image caches

.github/actions/build-docker-images/action.yml, .github/actions/load-docker-images/action.yml, .github/workflows/remove-obsolete-caches.yml
#2992 introduced docker image tags. This PR adjusts these tags to make them more readable. Also, this properly deletes old image tags from the registry so it stays clean.
=> GEN-75: Use recognizable names for Docker tags

.github/actions/load-docker-images/action.yml, .github/workflows/remove-obsolete-caches.yml
The tag for the build cache is not removed. This will make sure that those tags also gets removed after the PR is merged.
=> GEN-75: Remove build-cache tags

.github/actions/build-docker-images/action.yml, .github/actions/docker-build-push/action.yml, .github/actions/docker-ecr-login/action.yml, .github/actions/load-docker-images/action.yml, .github/actions/setup-rust-ci/action.yml, .github/actions/terraform-exec/action.yml, .github/actions/warm-up-repo/action.yml, .github/renovate.json, .github/workflows/canary-release.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/dependency-review.yml, .github/workflows/dispatch-fix.yml, .github/workflows/hash-backend-cd.yml, .github/workflows/labeler.yml, .github/workflows/publish-blocks-to-preview.yml, .github/workflows/publish-blocks-to-production.yml, .github/workflows/release.yml, .github/workflows/remove-obsolete-caches.yml, .github/workflows/rust.yml, .github/workflows/semgrep.yml, .github/workflows/sync-algolia-index.yml, .github/workflows/tf-apply-hash.yml, .github/workflows/tf-plan-hash.yml, .github/workflows/warm-up-vercel.yml
This improves the naming of some dependency bumps and as a drive-by use the exact version for GHA deps
=> H-605: Configure renovate to better name Action upgrades

libs/@local/eslint-config/package.json, libs/@local/hash-graph-client/typescript/package.json, yarn.lock
=> Revert "Update ESLint npm packages (major)"

apps/hash-graph/lib/authorization/src/backend.rs, apps/hash-graph/lib/authorization/src/backend/spicedb.rs
Schema import/export is not a strictly required feature as this could be done on seeding exactly once, however, this allows better testing strategies.
This PR:
=> H-650, H-651: Implement schema import/export

apps/hash-graph/Cargo.lock, apps/hash-graph/Cargo.toml, apps/hash-graph/bench/Cargo.toml, apps/hash-graph/bin/cli/Cargo.toml, apps/hash-graph/lib/authorization/Cargo.toml, apps/hash-graph/lib/authorization/src/backend/spicedb/api.rs, apps/hash-graph/lib/authorization/src/zanzibar.rs, apps/hash-graph/lib/authorization/tests/api.rs, apps/hash-graph/lib/authorization/tests/schema.rs, apps/hash-graph/lib/authorization/tests/schemas/simple.zed, apps/hash-graph/lib/authorization/tests/simple.rs, apps/hash-graph/lib/graph/Cargo.toml, apps/hash-graph/lib/type-fetcher/Cargo.toml, apps/hash-graph/tests/integration/Cargo.toml
Authorization is a backbone of the Graph and needs to be very well tested. A proper testing strategie is required, which includes an automatic cleanup after running.
- #3043
- Adds base logic for a test suite
- Tests the current API with a very simple schema
This PR:
=> H-680: Write initial test suite for authorization

.github/renovate.json
Applies @TimDiekmann's suggestions from [chat](https://hashintel.slack.com/archives/C02TWBTT3ED/p1693568163092989?thread_ts=1693567980.352119&cid=C02TWBTT3ED) (_internal link_)
=> H-694: Enable additional auto-updates in Renovate

.github/pull_request_template.md, .github/workflows/semgrep.yml
The SemGrep job tries to upload a file even if it does not exist.
- Check for the file before uploading
- Pin version to 1.38.0
- Drive-by: Remove unneeded whitespaces in PR template
This PR:
=> GEN-92: Fix failing Semgrep test in `hash` repo

apps/hash-graph/lib/authorization/src/backend.rs, apps/hash-graph/lib/authorization/src/backend/spicedb/api.rs, apps/hash-graph/lib/authorization/src/zanzibar.rs, apps/hash-graph/lib/authorization/tests/api.rs, apps/hash-graph/lib/authorization/tests/schema.rs, apps/hash-graph/lib/authorization/tests/simple.rs
Adds various test cases for the currently implemented API
This PR:
=> H-696: Add tests to test all API endpoints

.github/renovate.json
I discovered a few more dev-dependencies which can easily be upgraded.
This PR:
=> H-702: Add more auto-schedule packages to renovate

.github/ISSUE_TEMPLATE/bug-report-block.yml, .github/ISSUE_TEMPLATE/bug-report-deer.yml, .github/ISSUE_TEMPLATE/bug-report-error-stack.yml, .github/ISSUE_TEMPLATE/bug-report-hash-app.yml, .github/ISSUE_TEMPLATE/bug-report-website.yml, .github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request-error-stack.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/labeler.yml
Changes the format of our labels in preparation for future cross-repo/app synchronization.
Reapply labels on https://github.com/hashintel/hash/pull/3074 and delete duplicate tags auto-created on that PR while this one was in-flight.
=> GEN-95: Update labels for sync

.github/CODEOWNERS
=> GEN-98: Remove `libs` CODEOWNERS

libs/@local/hash-graph-sdk/python/graph_sdk/client/blocking.py
=> H-746: Fix CI failing `git diff` checks

apps/hash-graph/lib/authorization/src/api.rs, apps/hash-graph/lib/authorization/src/backend.rs, apps/hash-graph/lib/authorization/src/lib.rs, apps/hash-graph/lib/authorization/src/zanzibar.rs, apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
The Graph is expected to check for a permission before doing any modification. This adds checks for entities.
This PR:
=> H-720: Check for permissions when modifying an entity

apps/hashdotdev/src/pages/roadmap/technology-tree-filters.tsx
This PR adds a "Toggle All" checkbox to the tech tree filters to make it easier to filter by 'just one' thing on roadmap page.
- H-626
This PR:
None.
View the `/roadmap` page on the deployment, and verify the "Toggle All" filters function as expected.
https://github.com/hashintel/hash/assets/42802102/5cdec9a1-fbb2-4b1d-9140-a411e7d801da
=> H-626: Add "Toggle All" checkboxes to roadmap tech tree filters

libs/deer/desert/src/assert.rs, libs/deer/json/src/deserializer.rs, libs/deer/json/src/object.rs, libs/deer/src/error/serialize.rs, libs/deer/src/error/tuple.rs, libs/deer/src/helpers.rs, libs/deer/src/impls/core/array.rs, libs/deer/src/impls/core/ops.rs, libs/deer/src/impls/core/tuples.rs, libs/deer/src/schema.rs, libs/deer/src/value/object.rs, libs/deer/tests/test_bound.rs, libs/deer/tests/test_enum_core_result.rs, libs/deer/tests/test_enum_visitor.rs, libs/deer/tests/test_impls_core_cell.rs, libs/deer/tests/test_impls_core_cmp.rs, libs/deer/tests/test_impls_core_mem.rs, libs/deer/tests/test_impls_core_num.rs, libs/deer/tests/test_impls_core_num_primitives.rs, libs/deer/tests/test_impls_core_ops.rs, libs/deer/tests/test_impls_core_option.rs, libs/deer/tests/test_impls_core_string.rs, libs/deer/tests/test_impls_core_sync.rs, libs/deer/tests/test_impls_core_time.rs, libs/deer/tests/test_impls_core_tuples.rs, libs/deer/tests/test_struct_visitor.rs, libs/deer/tests/test_value.rs
Fixes several linting issues in `deer`.
This PR:
=> H-807: Fix linting issues in `deer`

.github/renovate.json
Enables automatic schedule for Rust dependencies
=> H-833: Automatically update Rust dependencies

apps/hash-graph/Cargo.lock, apps/hash-graph/lib/authorization/Cargo.toml, apps/hash-graph/lib/authorization/src/backend/spicedb/api.rs, apps/hash-graph/lib/authorization/src/backend/spicedb/model.rs, apps/hash-graph/lib/authorization/src/lib.rs
Some methods in SpiceDB have a streaming interface (such as reading relations). To use those, a streaming interface has to be added.
This PR:
=> H-851: Add support to stream SpiceDB return values

.github/workflows/package.yml
The test was forgotten to be updated. In addition, the logic was simplified.
=> GEN-112: Fix CI not building docker images

apps/hash-graph/lib/authorization/src/backend.rs, apps/hash-graph/lib/authorization/src/backend/spicedb/api.rs, apps/hash-graph/lib/authorization/src/backend/spicedb/model.rs, apps/hash-graph/lib/authorization/src/lib.rs, apps/hash-graph/lib/authorization/src/schema/account.rs, apps/hash-graph/lib/authorization/src/schema/account_group.rs, apps/hash-graph/lib/authorization/src/schema/entity.rs, apps/hash-graph/lib/authorization/src/schema/web.rs, apps/hash-graph/lib/authorization/src/zanzibar/api.rs, apps/hash-graph/lib/authorization/src/zanzibar/types.rs, apps/hash-graph/lib/authorization/tests/api.rs, apps/hash-graph/lib/authorization/tests/schema.rs
To store information in the snapshots about permissions the relationships has to be read from the store.
- #3210 
- #3211 
- #3223
- ~#3224~
This PR:
=> H-843: Support reading all relationships

.github/actions/build-docker-images/action.yml, apps/hash-api/src/graph/knowledge/system-types/hash-instance.ts, apps/hash-api/src/graph/knowledge/system-types/user.ts, apps/hash-external-services/docker-compose.dev.yml, apps/hash-external-services/docker-compose.test.yml, apps/hash-graph/bin/cli/src/subcommand/server.rs, apps/hash-graph/bin/cli/src/subcommand/snapshot.rs, apps/hash-graph/bin/cli/src/subcommand/test_server.rs, apps/hash-graph/docker/Dockerfile, apps/hash-graph/lib/authorization/src/backend/spicedb.rs, apps/hash-graph/lib/authorization/tests/api.rs, apps/hash-graph/package.json, tests/hash-backend-integration/src/tests/graph/knowledge/system-types/hash-instance.test.ts
With all tests passing it's possible to finally enable the Authorization API in the dev builds. This also includes H-817 as due to several rebases that PR was lost.
- #3210 
- #3211 
- #3223
- #3224
- #3243 
- #3254 
- #3255 
This PR:
=> H-839, H-817: Enable permission system in `dev`

apps/hashdotai-new/vercel.json
As the UI setting does not work we try to silence the PR comment via `vercel.json`
=> H-885: Add `vercel.json` to silent Vercel comments on PRs

libs/@local/hash-graph-client/python/graph_client/models.py
For some reason, the codegen does generate a different diff than committed. This provides the correct code so the diff is empty.
=> H-882: Fix generated code in `@local/hash-graph-client-python` package

libs/@local/hash-isomorphic-utils/src/ontology-types.ts
[nit] Makes punctuation consistent across ontology type descriptions.
=> H-901: Improve ontology type description consistency

apps/hash-ai-worker-py/app/infer/entities/workflow.py, libs/@local/hash-graph-sdk/python/examples/query_company_entity_type.py, libs/@local/hash-graph-types/graph_types/_schema.py, libs/@local/hash-graph-types/graph_types/data_type.py, libs/@local/hash-graph-types/graph_types/entity_type.py, libs/@local/hash-graph-types/graph_types/property_type.py, libs/@local/hash-graphql-shared/src/graphql/type-defs/knowledge/entity.typedef.ts
The AI may come up with some properties, which can then just be ignored.
This PR:
=> H-918: Allow `additionalProperties` when `validation` is set to `PARTIAL`

apps/hash-ai-worker-py/docker/Dockerfile
The container does not find the `worker` module.
This PR:
=> H-940: Fix python path environment

.github/workflows/hash-backend-cd.yml, .github/workflows/release.yml, .github/workflows/tf-apply-hash.yml
#3341 worked to stop the action attempting to use Vault, but I got the webhook URL variable name wrong. This PR fixes that.
=> Correct action variable name

libs/@local/hash-graph-client/python/graph_client/models.py, libs/@local/hash-graph-client/python/poetry.lock, libs/@local/hash-graph-client/python/pyproject.toml, libs/@local/hash-graph-client/python/scripts/codegen.sh, libs/@local/hash-graph-client/python/turbo.json
This fixes some problems encountered during the generation of the `models.py` by @TimDiekmann, most notably it adds support for `x-patternProperties` and plumbing needed to make it work.
* https://github.com/koxudaxi/datamodel-code-generator/issues/1584
This PR:
```python
class PropertyObjectReference(BaseModel):
model_config = ConfigDict(extra="forbid", populate_by_name=True)
field_ref: BaseURL = Field(..., alias="$ref")
class PropertyTypeObjectItem(BaseModel):
model_config = ConfigDict(extra="forbid", populate_by_name=True)
type: Literal["array"]
items: PropertyObjectReference
min_items: int | None = Field(None, alias="minItems", ge=0)
max_items: int | None = Field(None, alias="maxItems", ge=0)
class PropertyTypeObject(
RootModel[dict[str, …
```
=> H-993: python `hash-graph-client`: properly type `patternProperties` in generated models

.github/workflows/package.yml
The workflow is allowed to fail but the job should fail
=> H-1001: Fix `System Tests` job not failing on Playwright error

apps/hash-frontend/src/pages/[shortname].page/profile-page-info.tsx, libs/@hashintel/design-system/src/avatar.tsx
This PR adds the "Webs" section to user profiles. _Listing members on shared webs will come later._
- H-868
This PR:
None
Go to the user profile page, and confirm the "Webs" section exists as expected
With tooltip:
With row wrapping:
=> H-868: Implement User "Webs" section on profile pages

apps/plugin-browser/README.md
Adds placeholder content to the plugin readme, ahead of the public beta release.
=> H-1046: Add download and use sections to plugin readme

.github/workflows/hash-backend-cd.yml
The name of the service was wrong
=> H-1057: Fix Docker image deployment CD

.github/workflows/test.yml
PW tests were fixed, let's require them again.
This PR:
=> H-1090: Require Playwright to pass for CI

apps/hashdotai/README.md
Updates the README to reflect new agreed plans.
=> H-1101: Update `hashdotai` app future plans

libs/@local/hash-graph-client/python/graph_client/models.py, libs/@local/hash-graph-client/python/scripts/codegen.sh
For unknown reason black cannot decide how a file should formatted. Dozens of PR already failed because of this issue.
- H-1132
This PR:
=> H-1132: Remove formatting from Python codegen

apps/hash-graph/lib/graph/src/api/rest/account.rs, apps/hash-graph/lib/graph/src/api/rest/web.rs, apps/hash-graph/openapi/openapi.json
The OpenAPI specs exports the wrong types.
=> H-1135: Fix schema for permission checks

apps/hash-frontend/src/components/hooks/use-orgs-with-links.ts, apps/hash-frontend/src/components/hooks/use-orgs.ts, apps/hash-frontend/src/components/hooks/use-users-with-links.ts, apps/hash-frontend/src/components/hooks/use-users.ts, apps/hash-frontend/src/lib/user-and-org.ts, apps/hash-frontend/src/pages/[shortname].page.tsx, apps/hash-frontend/src/pages/[shortname]/[page-slug].page.tsx, apps/hash-frontend/src/pages/shared/auth-info-context.tsx, apps/hash-frontend/src/pages/shared/top-context-bar/share-dropdown-menu/share-entity-section.tsx, apps/hash-frontend/src/shared/use-user-or-org.ts, libs/@local/hash-isomorphic-utils/src/save.ts
This PR fixes being able to invite users/orgs to view a page or entity.
- H-1145
- Sets `kind` of the viewer relationship correctly
- Removes all casts from `Entity` to `Entity<XProperties>`, replacing them with type assertions
This PR:
None
Go to the deployment, try to invite a user or an org to an entity/page. Their name should now display correctly
https://github.com/hashintel/hash/assets/42802102/6b141c2e-087e-4481-8b18-7cea3b9e35e1
=> H-1145: Fix inviting users/orgs to view a page/entity

apps/hash-graph/Cargo.lock, apps/hash-graph/Cargo.toml, apps/hash-graph/bench/read_scaling/knowledge/complete/entity.rs, apps/hash-graph/bench/read_scaling/knowledge/linkless/entity.rs, apps/hash-graph/bench/representative_read/seed.rs, apps/hash-graph/bench/util.rs, apps/hash-graph/lib/graph/src/api/rest/utoipa_typedef.rs, apps/hash-graph/lib/graph/src/snapshot/ontology/table.rs, apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/lib/type-fetcher/src/fetcher.rs, libs/@local/hash-graph-types/rust/Cargo.toml, libs/@local/hash-graph-types/rust/src/ontology/data_type.rs, libs/@local/hash-graph-types/rust/src/ontology/entity_type.rs, libs/@local/hash-graph-types/rust/src/ontology/property_type.rs, tests/hash-graph-integration/Cargo.toml, tests/hash-graph-integration/postgres/data_type.rs, tests/hash-graph-integration/postgres/entity_type.rs, tests/hash-graph-integration/postgres/lib.rs, tests/hash-graph-integration/postgres/property_type.rs
The type-system package was updated and we need the newest version of the crate in HASH
This PR:
=> H-1165: Update `type-system` crate

.github/renovate.json, .github/workflows/lint.yml, .github/workflows/test.yml, apps/hash-frontend/package.json, apps/hash-graph/.justfile, libs/@local/hash-graph-sdk/python/.gitattributes, libs/@local/hash-graph-sdk/python/graph_sdk/client/blocking.py, libs/@local/hash-graph-sdk/python/graph_sdk/filter/path.py, libs/@local/hash-graph-sdk/python/package.json, libs/@local/hash-graph-sdk/python/pyproject.toml, yarn.lock
We encountered various issues with Python recently even though we barely use Python at all. Currently, we only use the hash-ai-worker-py package, which we will rewrite in Typescript as soon as entity validation is available in the Graph.
To avoid further CI failures we allow the Python packages to fail in CI.
Note, that this includes https://github.com/hashintel/hash/pull/3490
- H-1173
- Allow errors in the Python CI
- Disable auto-updates for Python linters
This PR:
-
1. Checkout the branch / view the deployment
1. Try X
1. Confirm that Y
=> H-1173: Allow Python CI to fail

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section.tsx, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/use-rows.ts
#2918 added handling of inherited _properties_ in the entity editor but failed to handle inherited links. This PR corrects that oversight.
Hide whitespace, most of the diff is indention.
This PR:
- None, but we need to add them.
1. Add Type A with a link
2. Extend Type B
3. Create entity of Type B and check that there are links addable
=> H-1197: Handle inherited links in the entity editor

turbo.json
This hopefully fixes that all jobs will run as soon as workflows changed. This cannot be tested in this PR as `turbo.json` had to be changed.
This PR:
=> GEN-111: Fix global dependencies for `turbo.json`

apps/hash-api/src/graphql/resolvers/knowledge/entity/entity.ts
To avoid re-triggering the same workflow if it already fails this sets a maximum number of attempts.
This PR:
=> H-1201: Set a maximum number of attempts to infer entities

apps/hash-graph/lib/graph/src/api/rest.rs, apps/hash-graph/lib/graph/src/api/rest/data_type.rs, apps/hash-graph/lib/graph/src/api/rest/entity_type.rs, apps/hash-graph/lib/graph/src/api/rest/property_type.rs, apps/hash-graph/lib/graph/src/api/rest/status.rs, apps/hash-graph/openapi/openapi.json, libs/@local/hash-graph-client/python/graph_client/models.py
to bypass fetching the schema from the URL, just use the provided schema
This PR:
=> H-1164: Allow specifying schema with external types

apps/hash-api/README.md, apps/hash-api/src/graph/util.ts
1. Allow forcing self-hosted behavior via environment variable for local testing / development 
2. Don't create the organization entities that own system types if self-hosted (since they are loaded as external types then)
This PR:
=> H-1232: Allow forcing self-hosted behavior, don't create system orgs if self-hosted

apps/hash-graph/lib/graph/src/store/fetcher.rs
If external types are self referencing the type fetcher will try to fetch these as well.
This PR:
=> H-1242: Allow inserting external self-referencing ontology types

apps/hash-frontend/src/components/block-loader/block-loader.tsx, blocks/code/package.json, blocks/code/src/app.tsx, blocks/code/src/types/generated/block-entity.ts, blocks/heading/variants.json, libs/@local/hash-isomorphic-utils/src/blocks.ts, libs/@local/hash-isomorphic-utils/src/prosemirror-manager.ts
Recreation of #3564 which I accidentally merged into a feature branch rather than `main`. 🙃 
See that PR for description.
=> H-60, H-1262: Retain text when swapping between blocks. Fix block permissions [RECREATES #3564] 

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section.tsx, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/cells/linked-with-cell.ts, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/types.ts, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/use-rows.ts
This PR makes the link chips in the entity links table clickable, so that the user can navigate to the linked entitie's entity editor page.
- H-1231
- makes use of the `InteractableManager` to make each rendered chip clickable in the `linked-with-cell` data grid cell type
This PR:
None
1. Go to the entity editor for an entity with an outgoing link (easiest to find one on the `/entities` page
2. Click on a linked entity, to navigate to its entity editor page
https://github.com/hashintel/hash/assets/42802102/523a2f35-d6e2-4abf-a903-eb3e72cb7893
=> H-1231: Make linked entities clickable to take you to their page

apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
- ...
- ...
This PR:
- this is tracked in: [Insert Link Here](link)
- _Provide more detail here_
-
1. Checkout the branch / view the deployment
1. Try X
1. Confirm that Y
=> H-1320: Fix entity type icon not being inserted into database

apps/hash-api/src/block-protocol-external-service-method-proxy.ts, apps/hash-api/src/index.ts, apps/hash-frontend/next.config.js, apps/hash-frontend/package.json, apps/hash-frontend/src/components/remote-block/construct-service-module-callbacks.ts, apps/hash-frontend/src/components/remote-block/remote-block.tsx, apps/hash-frontend/src/pages/[shortname].page/profile-page-info.tsx
This PR adds the service module to the HASH app, making it possible for blocks to call external service methods.
Drive-by:
- hide "Webs" section on profile page when there are no webs to display (H-1116)
- H-1151
- adds a `/external-service-method` endpoint to the Node API, which proxies the `/external-service-method` endpoint on the block protocol site, attaching the HASH BP API key to the any requests made
This PR:
- The Address and the AI Chat block have unrelated bugs, which need to be fixed to restore their functionality (See https://linear.app/hash/issue/H-1264/check-fix-existing-block-functionality)
None
Try using the AI Text or AI Chat block in a local running version of HASH.
=> H-1151: Add `Service Module` support to HASH

.github/actions/build-docker-images/action.yml, apps/hash-graph/bin/cli/Cargo.toml, apps/hash-graph/bin/cli/src/subcommand/server.rs, apps/hash-graph/bin/cli/src/subcommand/snapshot.rs, apps/hash-graph/bin/cli/src/subcommand/test_server.rs, apps/hash-graph/docker/Dockerfile
The feature flag is not needed anymore
This PR:
=> H-1470: Remove feature flag to disable permissions

apps/hash-frontend/src/components/block-loader/block-loader.tsx, apps/hash-frontend/src/pages/shared/block-collection/block-context-menu/block-select-data-modal.tsx, blocks/chart/src/app.tsx, blocks/chart/src/bar-chart.tsx, blocks/chart/src/edit-chart-definition/bar-graph-definition-form/count-linked-entities-form.tsx, blocks/chart/src/edit-chart-definition/bar-graph-definition-form/group-by-property-form.tsx, libs/@hashintel/design-system/src/modal.tsx, libs/@hashintel/query-editor/src/entity-query-editor.tsx, libs/@hashintel/query-editor/src/entity-query-editor/query-form.tsx, libs/@hashintel/query-editor/src/entity-query-editor/query-form/filter-row.tsx, libs/@hashintel/query-editor/src/entity-query-editor/query-form/filter-row/entity-type-selector.tsx, libs/@hashintel/query-editor/src/entity-query-editor/query-form/filter-row/property-type-selector.tsx, libs/@hashintel/query-editor/src/entity-query-editor/query-form/filter-row/selector-group-wrapper.tsx
This PR makes several improvements and related bug fixes to the chart block.
- H-1549
- Close the "Select block data" modal when the query has been created or updated
- Ad ontology chips to the query selector dropdowns to help distinguish between types with the same title
- Fix a crash in the chart block when no results are returned by the query
- Regenerate the chart definition when the query entity edition has changed (i.e. when the user updates the query in the "Select block data" modal
- Fix an issue where intermittently the "Select block data" modal wasn't populated with the query, because the `blockSubgraph` was `undefined` in the block context provider.
- Alphabetically sort the bar chart data on the X axis, so that when there are re-renders but the underlying data hasn't changed …
=> H-1549: Chart block improvements and bug fixes

apps/hash-ai-worker-ts/src/activities/infer-entities.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/get-entity-by-filter.ts
Fixes retrieving draft entities in the AI inference worker to check if they can be updated.
Also stops prettifying logs in production (stop them taking up many lines)
This PR:
=> H-1555: Fix finding draft entities to update

.github/workflows/lint.yml, apps/hash-graph/.justfile, apps/hash-graph/README.md, apps/hash-graph/bins/cli/src/subcommand/mod.rs, apps/hash-graph/docker/Dockerfile, apps/hash-graph/libs/graph/src/api/rest/mod.rs, apps/hash-graph/libs/graph/src/store/fetcher.rs, apps/hash-graph/libs/graph/src/store/knowledge.rs, apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs, apps/hash-graph/libs/graph/src/store/postgres/mod.rs, apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/libs/graph/src/store/postgres/ontology/mod.rs, apps/hash-graph/libs/graph/src/store/postgres/ontology/property_type.rs, apps/hash-graph/package.json, apps/hash-graph/tests/circular-links.http, apps/hash-graph/tests/friendship.http, apps/hash-graph/tests/reset-database.http, package.json, tests/hash-graph-integration/package.json
For development it's pretty annoying to reset the whole Docker volume each time in testing. This provides a shortcut and improves DX
=> H-1214: Be able to wipe the database locally easily

apps/hash-frontend/src/pages/drafts.page/draft-entities.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entity/draft-entity-action-buttons.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entity/draft-entity-provenance.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entity/draft-entity-type.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entity/draft-entity-viewers.tsx, apps/hash-frontend/src/pages/shared/link-label-with-source-and-destination.tsx, apps/hash-frontend/src/shared/icons/feather-regular-icon.tsx, apps/hash-frontend/src/shared/layout/layout-with-sidebar/acount-entities-list.tsx, apps/hash-frontend/src/shared/ui/link.tsx, libs/@hashintel/design-system/src/alert-modal.tsx
This PR updates the copy and displays the source and target entities in the "accept draft link" warning modal.
Drive-by fixes:
- display "Only visible to me" instead of the incorrect "Visible to 0 users" for when a draft entity is created by a machine user
- fixes an issue where draft entities weren't displayed on the `/drafts` page when a draft entity had more than one revision
- hide link entities in "Entities" sidebar section (H-1602)
- makes the `/drafts` page slightly more responsive by preventing the collapsing of text, and hiding the "By" and "At" copy at smaller screen sizes
- H-1541
See description/commits.
This PR:
Manual testing
Create a draft link entity with either a draft source or target entity, and view the warning modal when …
=> H-1541, H-1602: display source and destination in the "accept draft link" warning modal

apps/hash-api/src/graph/knowledge/primitive/entity.ts, apps/hash-frontend/src/pages/drafts.page/draft-entities.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entity.tsx, apps/hash-frontend/src/pages/shared/block-collection/shared/mention-suggester.tsx, libs/@local/hash-isomorphic-utils/src/generate-entity-label.ts
This PR filters archived outgoing links from displaying in the mention suggester.
Other drive-by changes:
- only mount properties table when it is being displayed on `/drafts` page
- render draft entities in increments of 20
- generates entity labels if there is a "First Name" or "Last Name" (or "Family Name") property, or both
- H-1664
This PR:
Manual
Previously:
Now:
=> H-1664: Don't display archived links in mention suggester + other fixes

apps/hash-frontend/src/shared/notifications-context.tsx
This PR aims to fix a intermittent runtime error in the notifications context. 
- Previously we were fetching the two queries needed to construct the notifications at the same time, which meant it was possible for the revisions subgraph to not contain a notification entity that was returned by the other query. Now the revisions query will only be called after the other query for getting the notifications has responded, and will only fetch for entities which are in that query's response.
This PR:
I've tried producing notifications via the browser plugin repeatedly, and am no longer able to reproduce this error.
=> H-1667: Fix notifications runtime error

libs/@local/hash-authorization/src/api.rs, libs/@local/hash-authorization/src/lib.rs, libs/@local/hash-authorization/src/zanzibar/api.rs
Checking the permissions for types don't use the batch endpoint.
=> H-1733: Use `BatchCheckPermission` for types

Cargo.lock, libs/@local/hash-validation/Cargo.toml, libs/@local/hash-validation/src/data_type.rs
Adds support for
- `enum`
- `minLength`
- `maxLength`
- `pattern`
=> H-1766: Support more validation constrains defined in JSON Schema

apps/hash-api/src/graph/knowledge/primitive/entity/before-update-entity-hooks.ts, apps/hash-api/src/graphql/resolvers/index.ts, apps/hash-api/src/graphql/resolvers/knowledge/entity/entity.ts, apps/hash-api/src/graphql/resolvers/knowledge/user/has-access-to-hash.ts, apps/hash-api/src/graphql/resolvers/shared/user-has-access-to-hash.ts, apps/hash-api/src/shared/user-has-access-to-hash.ts, apps/hash-frontend/src/graphql/queries/user.queries.ts, apps/hash-frontend/src/pages/_app.page.tsx, apps/hash-frontend/src/pages/index.page.tsx, apps/hash-frontend/src/pages/shared/auth-info-context.tsx, infra/terraform/hash/main.tf, libs/@local/hash-isomorphic-utils/src/graphql/type-defs/knowledge/user.typedef.ts
This PR adds support for an `USER_EMAIL_ALLOW_LIST` environment variable, to limit the number of users who have access to HASH via their email address. 
- H-1768
- prevents users from completing signup (i.e. setting a preferred name/shortname) if they don't have access to the HASH instance
- displays a message for authenticated users who don't have access to HASH on the home page
This PR:
1. Add an `USER_EMAIL_ALLOW_LIST` environment variable, containing an allowed email (e.g. `charlie@example.com`
2. Ensure you're able to sign up with this email address and use HASH
3. Ensure you're not able to sign up or log in with an email that is not in the list
When authenticated as a user who doesn't have access to the HASH instance:
=> H-1768: Add optional "allowlist only" access mode to HASH

.github/workflows/test.yml, apps/hash-frontend/src/pages/signup.page.tsx, apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-entities-list.tsx, apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-page-list/account-page-list.tsx, apps/hash-graph/libs/query-builder-derive/Cargo.toml, package.json, tests/hash-playwright/playwright.config.ts, tests/hash-playwright/tests/entity-creation.spec.ts, tests/hash-playwright/tests/entity-type-creation.spec.ts, tests/hash-playwright/tests/guest-user.spec.ts, tests/hash-playwright/tests/page-creation.spec.ts, tests/hash-playwright/tests/page-navigation.spec.ts, tests/hash-playwright/tests/shared/reset-db.ts, tests/hash-playwright/tests/shared/runtime.ts, tests/hash-playwright/tests/signup.spec.ts, turbo.json
This PR fixes Playwright tests timing out in CI – this was because:
- `test:system` depended on `build` in the Turbo configuration
- meaning that all build commands were run before the Playwright tests
- which caused the frontend (which had already been built and run in a previous step) to be rebuilt
- in a way which meant it loaded but some of the JavaScript file URLs were wrong
- recreating this locally requires bypassing the Turbo cache
The PR fixes the above by removing `build` as a dependency of running `test:system`. The API and frontend must already be built and running for tests to work, nothing needs building again when the actual test command is run. 
It also:
- removes `build` as a dependency of the `dev` command from the root `turbo.json` (individual apps can add dependencies …
=> H-1800: Fix Playwright setup, existing tests

apps/hash-frontend/src/components/hooks/block-protocol-functions/knowledge/use-block-protocol-create-entity.ts, apps/hash-frontend/src/shared/use-entity-type-entities.tsx
This PR ensures the sidebar "Entities" section is updated when the user creates the first instance of a type that is from a different web, without needing to refresh the page.
- H-1799
- adds a refetch query to `createEntity` in the `useBlockProtocolCreateEntity`
This PR:
Manual testing
1. Create a new type in an org that the user is a member of or has access to
2. Switch to the user's web in the sidebar. The type should not be displayed in the "Entities" section, as the user has not instances of that type.
3. Create an instance of the type
4. Ensure the sidebar to include the type, once the entity has been created
https://github.com/hashintel/hash/assets/42802102/c73aa1a1-f49a-4f3f-9f53-33a7cfe08160
=> H-1799: Show newly created ‘types’ of entities in the ‘Entities’ section of the sidebar, without having to hard refresh the page

apps/hash-frontend/package.json, apps/hash-frontend/src/components/remote-block/construct-service-module-callbacks.ts, blocks/address/package.json, blocks/ai-chat/package.json, blocks/ai-image/package.json, blocks/ai-text/package.json, blocks/ai-text/src/app/generate-text.tsx, yarn.lock
This PR removes usages of `completeText` from the AI Text block, and as a driveby remove the deprecated `completeText` method from the HASH frontend service callbacks and upgrade the `@blockprotocol/service` package.
- H-1865
This PR:
Load the AI Text block, and ensure it still works.
=> H-1865: Remove `completeText` from the AI Text block

.github/workflows/lint.yml, .github/workflows/test.yml
We hit rate limits using the GH action, so instead we'll use apt instead.
=> H-1878: Install Protobuf compiler in CI manually

apps/hash-graph/bench/representative_read/knowledge/entity.rs, apps/hash-graph/libs/api/src/rest/entity.rs, apps/hash-graph/libs/graph/src/store/fetcher.rs, apps/hash-graph/libs/graph/src/store/knowledge.rs, apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs, apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/read.rs, apps/hash-graph/libs/graph/src/store/postgres/ontology/read.rs, apps/hash-graph/libs/graph/src/store/postgres/query/compile.rs, apps/hash-graph/libs/graph/src/store/postgres/query/expression/where_clause.rs, tests/hash-graph-integration/postgres/lib.rs
Pagination had two issues:
1. Too few results would be returned if the actor was not allowed to see a few entries
2. The cursor was not transpired correctly to Postgres
This PR:
=> H-1873: Fix pagination

libs/@hashintel/design-system/src/ontology-chip.tsx, libs/@hashintel/design-system/src/selector-autocomplete/selector-autocomplete-option.tsx, libs/@hashintel/type-editor/src/entity-type-editor/shared/insert-property-field/type-selector.tsx, tests/hash-playwright/tests/entity-creation.spec.ts, tests/hash-playwright/tests/entity-type-creation.spec.ts
This PR adds to the `entity-type-creation.spec.ts` playwright test, adding a property and a link to the entity via the type selectors, and creating the type.
- H-1819
- update the "no option" copy in the type selector to read "No results" instead
This PR:
Verify the playwright tests are passing.
=> H-1819: Add test for adding outgoing link/property to an entity type

apps/hash-frontend/src/pages/drafts.page/draft-entities.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entities/draft-entities-filters.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entities/draft-entities-filters/filter-section.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entities/draft-entities-filters/types.ts
This PR adds a numeric value next to each filter option on the `/drafts` page, which indicates the number of entities which would come into view with the filter option enabled/disabled.
- H-1751
- adds a `FilterSection` component which makes some of the layout for each filter section more re-usable, and defines the filter sections as an array of objects
This PR:
1. Go to the `/drafts` page with drafts of different kinds
2. Ensure the numbers next to the filter options are accurate
https://github.com/hashintel/hash/assets/42802102/ae66e764-0611-44fe-a230-7e8b5f2fc860
=> H-1751: Display count next to filter options on `/drafts` page

apps/hash-frontend/src/pages/drafts.page/draft-entities/draft-entities-filters/filter-section.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entities/draft-entities-filters/types.ts, apps/hash-frontend/src/pages/drafts.page/draft-entity.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entity/draft-entity-chip.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entity/draft-entity-provenance.tsx, apps/hash-frontend/src/pages/drafts.page/draft-entity/draft-entity-web.tsx
This PR adds a "select all" switch to the draft filter options, and replaces "Visible to X people" with name of containing web.
- H-1543
- H-1550
This PR:
1. Go to the `/drafts` page
2. Try out the "Select All" switch for a filter section
3. Observe that the draft entity displays the web in which it was created in
https://github.com/hashintel/hash/assets/42802102/931705a0-ee1f-40d2-b741-850ae22310e6
=> H-1543, H-1550: add "select all" switch to draft filter options + show draft entity web

apps/hash-api/src/storage/index.ts, apps/hash-frontend/src/pages/[shortname].page/profile-bio.tsx, tests/hash-playwright/tests/profile-page.spec.ts, tests/hash-playwright/turbo.json
One of the linting "fixes" introduced in #2940 caused a crash when adding a bio to a user or org's profile page. I don't know why because the query is not supposed to be run unless `profile.hasBio` is defined, but it crashes because `profile.hasBio` is undefined once a bio is added.
I've taken the opportunity to add a test for the profile page which checks that it can be rendered and the bio edited.
I noticed that Playwright tests are cached regardless of whether files in the apps they are testing change, so I've disabled caching for the `test:system` command. Since if it passes it only takes a couple of minutes, this seems easier than trying to define all the files that might change it as `inputs`.
This PR also adds some more debug logs to file download in an attempt to debug H-1943. I …
=> H-2007: Fix crash in profile page when adding bio

apps/hash-api/src/cache/adapter.ts, apps/hash-api/src/cache/redis.ts, apps/hash-api/src/index.ts, apps/hash-api/src/integrations/sync-back-watcher.ts, apps/hash-api/src/storage/aws-s3-storage-provider.ts, apps/hash-api/src/storage/index.ts, apps/hash-realtime/src/config.ts, apps/hash-realtime/src/scripts/clear-redis.ts, apps/hash-search-loader/src/index.ts, infra/terraform/hash/main.tf, infra/terraform/modules/realtime/realtime.tf, infra/terraform/modules/search-loader/search-loader.tf, libs/@local/hash-backend-utils/package.json, libs/@local/hash-backend-utils/src/queue/redis.ts, libs/@local/hash-backend-utils/src/redis.ts, yarn.lock
This PR possibly / hopefully fixes access between the Node API and the Redis cluster in production, which is causing uploaded files to be inaccessible in production (because Redis is involved). I'm not convinced Redis needs to be involved in file download, but it's currently also a dependency of integration outward sync, which we will want soon.
I believe the issue is that the AWS ElastiCache cluster is configured to only accept encrypted traffic, but the Redis client in the repo wasn't configured to send it if needed. We'll only know after this is deployed though.
I updated the version of the client we were using, which also necessitated a few changes to the logic around it.
This PR:
See if this works.
- None.
1. Merge it
=> H-1943: Fix(?) Redis connection in production

apps/hash-frontend/src/shared/use-actors.ts
This PR fixes an infinite render issue in the `EntitiesTable` component, where a `useEffect` dependency on `rows`, which has a dependency on `actors` returned by `useActors`, would trigger an infinite re-render cycle because re-rendering `useActors` with the same parameters would result in an array to be returned with a different reference. Adding a `useMemo` fixes this.
- ...
- adds a `useMemo` to `useActors`
This PR:
Manual testing
Check the responsiveness of the `EntitesTable`, or add a log to the render function to ensure it's not infinite.
=> Fix infinite render issue in the `EntitiesTable` component

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util.ts
As part of the migration scripts we update existing entities to new versions of the type they belong to, where the type is updated as part of the migration.
The function doing this wasn't using the correct authority to find and update entities, meaning it could (a) not find all entities needing updating, and (b) could find some it could not update.
This PR fixes that by using the web-scoped bot to find and update entities in each web (it has permission to view and edit all entities in the web it is assigned to).
This PR:
1. Difficult as it requires partially migrating the system, creating an entity of a type, and then running a migration which upgrades the type and entity. This could be done by deleting the image migration, for example, and then uploading an avatar …
=> H-2173: Use web bot's authority to find and update entities in migration

apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
To archive draft entities when they become live it's required that the old entity is archived. This implements the graph functionality to archive an entity based in its temporal axes.
- #4022
- Add logic to archive an entity by setting the end timestamp
This PR:
=> H-2146: Implement entity archival in the Graph

.github/workflows/hash-backend-cd.yml, .github/workflows/test.yml
In #4063 I neglected to add the CI workflow steps necessary to build the Hydra Docker image and push it to its ECR repository.
This PR fixes that.
This PR:
=> H-2222: Add build and push of Hydra Docker image to CI workflow

apps/hash-external-services/docker-compose.prod.yml, infra/terraform/hash/prod-usea1.tfvars
In the Terraform config I missed a Kratos environment variable and had the wrong values for two Hydra variables – this PR fixes that.
This PR:
=> H-2229: Fix production environment variables for Hydra and Kratos

apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs, apps/hash-graph/tests/friendship.http
The parameter numbering was wrong.
=> H-2234: Fix parameter numbers for embedding update

infra/terraform/hash/main.tf
The integration worker does OOM pretty quickly. This increases the memory limit from 0.5 GB to 1 GB.
=> H-2273: Increase memory for integration worker

apps/hashdotdev/src/_pages/blog/0016_file-structuring.mdx
=> H-2367: Mention Rust exceptions in `Fractal Trees` HDEV post

infra/terraform/hash/hash_application/temporal_worker_integration.tf
In #4174 I overlooked adding the secrets to the integration worker's task definition.
=> H-2406: Add missing secrets definition to Temporal integration worker task definition

apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs, apps/hash-graph/tests/friendship.http, libs/@local/hash-validation/src/entity_type.rs, tests/hash-graph-integration/postgres/lib.rs, tests/hash-graph-integration/postgres/multi_type.rs
To improve our confidence around multi-type entities this PR adds a few test cases.
=> H-2370: Write tests for multi-type entities

infra/terraform/hash/hash_application/main.tf
Another fix following #4174 and #4178
=> H-2413: Add policy to allow access to integration worker SSM values

.github/workflows/test.yml
Reverts hashintel/hash#4134
#4166 should address test flakiness
=> Revert "H-2347: Temporarily disable Playwright test requirement"

apps/hashdotdev/package.json, apps/hashdotdev/src/components/navbar/mobile-nav-items.tsx, yarn.lock
This PR fixes the navbar from becoming unresponsive on iOS devices, by memoizing calculations made for each navbar item.
As a drive-by it also addresses a duplicate react key error, which occurred because the "Modeling a Portfolio" blog post has two sibling headings with the same name.
- H-2423
This PR:
Open the deployment on an iOS device (I wasn't able to reproduce the issue in a browser/simulator on desktop), and ensure the mobile nav can be navigated without performance degradation.
https://github.com/hashintel/hash/assets/42802102/d622eba6-ba3d-4d6b-9834-1f91fe4e5254
=> H-2423: fix hash.dev mobile navbar responsiveness issue

Cargo.lock, apps/hash-graph/bench/read_scaling/knowledge/complete/entity.rs, apps/hash-graph/bench/read_scaling/knowledge/linkless/entity.rs, libs/@blockprotocol/type-system/rust/src/ontology/entity_type/mod.rs, tests/hash-graph-integration/postgres/drafts.rs, tests/hash-graph-integration/postgres/entity.rs, tests/hash-graph-integration/postgres/entity_type.rs, tests/hash-graph-integration/postgres/lib.rs, tests/hash-graph-integration/postgres/links.rs, tests/hash-graph-integration/postgres/multi_type.rs, tests/hash-graph-integration/postgres/partial_updates.rs, tests/hash-graph-integration/postgres/sorting.rs, tests/hash-graph-test-data/rust/src/entity_type/person.json
Partial update operations are important to be correct and reliable. This adds test cases for the different property change operations and type id change behavior.
- #4183 
This PR:
=> H-2422: Create more tests for partial updates

.vscode/extensions.json, apps/hash/README.md
Updates outdated references to Jest.
=> H-2435: Update in-repo documentation to mention Vitest

apps/hashdotai/guide/01_introduction/00_index.mdx, apps/hashdotai/guide/01_introduction/02_core-concepts.mdx, apps/hashdotai/guide/01_introduction/03_get-started.mdx, apps/hashdotai/guide/02_webs/00_index.mdx, apps/hashdotai/guide/03_entities/01_attributes.mdx, apps/hashdotai/guide/03_entities/02_creating.mdx, apps/hashdotai/guide/09_plugins/00_index.mdx, apps/hashdotai/guide/10_flows/00_index.mdx, apps/hashdotai/guide/12_ai/00_index.mdx, apps/hashdotai/guide/13_inbox/01_actions.mdx
Adds a selection of example page "covers" for different `/guide` pages. The set will be made more stylistically consistent later, and completed.
=> H-1253: Add initial cover images for guide

Cargo.lock, apps/hash-api/src/graph/knowledge/primitive/entity.ts, apps/hash-api/src/graph/ontology/primitive/entity-type.ts, apps/hash-api/src/graph/shared/rewrite-semantic-filter.ts, apps/hash-api/src/graphql/resolvers/ontology/entity-type.ts, apps/hash-frontend/src/graphql/queries/ontology/entity-type.queries.ts, apps/hash-frontend/src/shared/layout/layout-with-header/search-bar.tsx, libs/@local/hash-isomorphic-utils/src/graphql/scalar-mapping.ts, libs/@local/hash-isomorphic-utils/src/graphql/type-defs/ontology/entity-type.typedef.ts
Also looks for types when the user types in the search bar.
This PR:
- I noticed a mismatch between library types and HASH values, mentioned in a comment – H-2489.
1. Try searching for a type
https://github.com/hashintel/hash/assets/37743469/318ac574-2778-45a8-b777-1832c728c0a2
=> H-2418: Add ability to search for types in HASH search bar

infra/terraform/hash/hash_application/kratos.tf
The terraform configuration currently uses `latest`. We should pick that version manually.
=> H-2534: Manually specify kratos version in Terraform

.github/workflows/test.yml
PW currently fails to install.
- https://github.com/microsoft/playwright/issues/30503
- Disable the requirement to pass system tests
=> H-2550: Temporarily disable PW tests

.github/workflows/test.yml
Reverts #4349 now fixed: https://github.com/microsoft/linux-package-repositories/issues/130#issuecomment-2074910628
=> H-2551: Enable Playwright tests again

Cargo.lock, apps/hash-graph/libs/graph/src/store/postgres/crud.rs, apps/hash-graph/libs/graph/src/store/validation.rs, apps/hash-graph/tests/friendship.http, libs/@local/hash-validation/src/entity_type.rs, libs/@local/hash-validation/src/lib.rs
If a link's left/right entity points to an entity which also has a draft entity it will raise an error, this fixes the issue.
This PR:
=> H-2553: Fix entity validation for drafts

apps/hash-ai-worker-ts/src/activities/flow-activities/infer-entities-from-content-action.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/persist-entities-action.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/persist-entity-action.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/coordinator-tools.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/infer-entities-from-web-page-worker-agent.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/open-ai-coordinating-agent.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/types.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/util.ts, apps/hash-ai-worker-ts/src/activities/infer-entities-from-web-page-activity.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/infer-entity-summaries-from-web-page.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/infer-entity-summaries.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/infer-entity-summaries/generate-summary-tools.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/inference-types.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/persist-entities.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/persist-entities/create-entities.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/persist-entities/generate-persist-entities-tools.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/persist-entities/update-entities.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/propose-entities.ts, apps/hash-ai-worker-ts/src/activities/infer-entities/shared/generate-propose-entities-tools.ts, apps/hash-ai-worker-ts/src/activities/shared/find-existing-entity.ts, apps/hash-ai-worker-ts/src/activities/shared/get-entity-by-filter.ts, apps/hash-ai-worker-ts/src/activities/shared/get-llm-response.ts, apps/hash-ai-worker-ts/src/activities/shared/get-llm-response/types.ts, apps/hash-ai-worker-ts/src/activities/shared/map-action-input-entities-to-entities.ts, apps/hash-ai-worker-ts/src/activities/shared/simplify-entity.ts, apps/hash-frontend/src/pages/ai.page/research-task-flow.tsx, libs/@local/hash-isomorphic-utils/src/ai-inference-types.ts, libs/@local/hash-isomorphic-utils/src/flows/action-definitions.ts, libs/@local/hash-isomorphic-utils/src/flows/types.ts
This PR adds the ability for the coordinating agent in the research entities action to create proposed links, whether they are between existing entities, proposed entities or a proposed entity and an existing entity.
It adds support for passing existing entities to the `inferEntitiesFromContent` flow action, so that links created from the content can link between proposed and existing entities.
- H-2496
- adds retry capabilities to the `createInitialPlan` LLM call in the worker agent
- adds required `explanation` arguments to the tools in the coordinator agent, to be more consistent with the implementation in the worker agent
- adds a check step when the coordinator agent calls the `complete` tool. I added this because it would sometimes not create links for types that were provided, so I …
=> H-2496: Add link creation capabilities to the research entities action, including between proposed and existing entities

infra/terraform/hash/hash_application/main.tf
The migration script may takes a while to complete
This PR:
This is a temporary solution. The migration should run in a container which expects to exit, then the health-checked service should be started
=> H-2588: Increase ELB timeout and interval

libs/error-stack/Cargo.toml, libs/sarif/Cargo.toml
This reverts commit 76c3c2659c53ca1eadc9cbbfec8fcb84a06bbba5.
- #4419
=> GEN-156: Revert renovate PRs using wrong update behavior (again)

apps/hashdotai/guide/01_introduction/03_get-started.mdx
This PR fixes MDX content on the `hash.ai/guide/introduction/get-started` page.
- H-2660
- Untruncates the list items in the content, which was presumably previously truncated by prettier
This PR:
=> H-2660: Fix MDX content on the `hash.ai/guide/introduction/get-started` callout

Cargo.lock, apps/hash-graph/bench/Cargo.toml, apps/hash-graph/bench/read_scaling/knowledge/complete/entity.rs, apps/hash-graph/bench/read_scaling/knowledge/linkless/entity.rs, apps/hash-graph/bench/representative_read/lib.rs, apps/hash-graph/bench/util.rs
Tracing data is being used to create Flamegraphs.
- #4464 
- Generate tracing data when running benchmarks
This PR:
=> H-2701: Automate creating tracing-data for benchmarks

libs/@local/repo-chores/rust/bin/cli/subcommand/benches/analyze.rs, libs/@local/repo-chores/rust/bin/cli/subcommand/benches/mod.rs, libs/@local/repo-chores/rust/bin/cli/subcommand/benches/upload.rs, libs/@local/repo-chores/rust/src/benches/analyze/criterion.rs
As the flame graphs are uploaded to S3 we can link them in the PR comments
- #4469 
- #4470 
- #4471 
- #4472 
This PR:
=> H-2706: Link the flamegraphs in the benchmark results comment

libs/@local/repo-chores/rust/src/benches/analyze/tracing.rs
Bench startup takes some time and due to this, the flame graphs currently contain a large section without any further information.
- #4470 
- #4471 
- #4472 
- #4474 
This PR:
=> H-2703: Trim `Thread(1)-main ` from flamegraphs

apps/hash-ai-worker-ts/src/main.ts, apps/hash-integration-worker/src/main.ts
In a further attempt to figure out why the AI worker is not connecting to the Temporal server, this PR removes its use of the Flow activities (which aren't used in production yet anyway) to eliminate more sources of potential bugs.
This PR will need to be reverted in order for Flows to work locally.
I also noticed that the integration worker has the wrong service name in its logger.
=> H-2835: Comment out Flow activities from AI worker

apps/hash-ai-worker-ts/src/main.ts
Restores the Flow activities which were removed from the AI worker in #4550.
With these commented out, the AI worker did get further in starting up that it had previously and managed to start running, but I had made other changes which may have had an impact. If the AI worker starts experiencing the same error it was before, we know there is some issue in importing the Flow activity modules which is a factor in the issues in AWS.
I have removed the `ping` of the Temporal server as we know it is reachable (the AI worker can start running, which it does not if it cannot connect to the server).
Now that the AI worker is running, the API migration container is being killed before it can complete its migrations with `Error from Graph API: upstream request timeout`. It's unclear if this is …
=> H-2839: Restore flow code to AI worker

apps/hash-ai-worker-ts/src/activities/flow-activities.ts, apps/hash-ai-worker-ts/src/main.ts, apps/hash-ai-worker-ts/src/workflows/run-flow-workflow.ts
Restoring the Flow code to the AI worker in #4555 did cause the timeout error to reappear when the worker starts up.
This PR removes _some_ of the Flow code to start narrowing it down.
=> H-2843: Remove some Flow code

apps/hash-ai-worker-ts/src/activities/flow-activities.ts, apps/hash-ai-worker-ts/src/workflows/run-flow-workflow.ts, libs/@local/hash-backend-utils/src/hash-instance.ts
The AI worker started again after removing the code in #4559. This PR restores all of it apart from the part that uses the Vault Client, in case that is somehow related.
It also adds another debug log around the function where the API migration container fails to get a request from the graph (separate issue).
=> H-2389: Restore some Flow code to AI worker

apps/hash-ai-worker-ts/src/activities/flow-activities.ts, apps/hash-ai-worker-ts/src/workflows/run-flow-workflow.ts, libs/@local/hash-backend-utils/src/create-graph-client.ts
More things to debug two deployment issues:
1. Comment out some more code from the AI worker to see if it starts working again
2. Increase the max sockets and timeout in the Graph API client to see if it fixes the migrations timing out when there's a lot of concurrent requests
=> H-2843: Remove some more Flow code from AI worker. Increase Graph API client timeout

apps/hash-frontend/src/pages/goals/new.page.tsx, libs/@local/hash-graph-sdk/typescript/package.json, libs/@local/hash-graph-sdk/typescript/src/entity.ts
=> H-2844: Fix import in Graph SDK, fix new goal check

apps/hash-ai-worker-ts/src/activities/flow-activities.ts, apps/hash-ai-worker-ts/src/main.ts
Restores some further code to the AI worker to see what causes it to break in production.
=> H-2839: Restore some Flow code

apps/hash-ai-worker-ts/src/activities/flow-activities.ts
=> H-2843: Remove flow code

apps/hash-ai-worker-ts/src/activities/flow-activities.ts
=> Remove a Flow activity

apps/hash-ai-worker-ts/src/activities/flow-activities.ts
=> Remove another activity

apps/hash-ai-worker-ts/README.md, apps/hash-api/README.md, infra/terraform/hash/main.tf
Adds an environment variable for the internal API host in production.
Fixes getting the waitlist position for users.
This PR:
=> H-2848: Add internal API host to Terraform

apps/hash-ai-worker-ts/src/activities/shared/get-flow-context.ts
I have a theory that the issues with the AI worker starting in production might be due to the side effects in this module. I'm removing them to prove or disprove it.
This PR:
=> H-2831: Remove client + cache creation side effects in `get-flows-context`

apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
When spans were added to improve tracing, accidentally spans were added in loops which implies some span recursion. This removes spans in loops.
=> H-2875: Fix spans being recursive

apps/hash-ai-worker-ts/src/activities/flow-activities/generate-web-queries-action.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/get-web-page-summary-action.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/infer-entities-from-content-action.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/check-sub-tasks-agent.ai.test.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/check-sub-tasks-agent.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/coordinator-tools.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/infer-facts-from-web-page-worker-agent/update-state-from-inferred-facts.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/shared/infer-facts-from-text/get-entity-summaries-from-text.ts, apps/hash-ai-worker-ts/src/activities/flow-activities/shared/infer-facts-from-text/infer-entity-facts-from-text.ts, apps/hash-ai-worker-ts/src/activities/get-web-page-activity.ts, apps/hash-ai-worker-ts/src/activities/shared/get-llm-response.ts, apps/hash-ai-worker-ts/src/activities/shared/inference-model-alias-to-llm-model.ts, apps/hash-ai-worker-ts/src/activities/shared/openai-client.ts, apps/plugin-browser/src/pages/popup/popup-contents/action-center/one-off/infer-entities-action.tsx, apps/plugin-browser/src/scripts/background.ts, apps/plugin-browser/src/scripts/background/infer-entities.ts, apps/plugin-browser/src/scripts/background/infer-entities/get-website-content.ts, apps/plugin-browser/src/scripts/content.ts, apps/plugin-browser/src/shared/messages.ts, libs/@local/hash-graph-sdk/typescript/src/entity.ts, libs/@local/hash-isomorphic-utils/src/ai-inference-types.ts, libs/@local/hash-isomorphic-utils/src/flows/action-definitions.ts, libs/@local/hash-isomorphic-utils/src/flows/types.ts
This PR aims to improve the sub-task creation process, by introducing a check step before sub-tasks are run to help ensure they are relevant to the research task, and will contribute to the final output.
It also switches the web page summarizing agent to `haiku`, and makes use of `innerText` instead of `innerHtml` when summarizing content.
- H-2911
- modifies the `WebPage` type to include `innerText`, so that both the `innerHtml` and `innerText` are available when a `WebPage` has been requested.
- switches the fact gathering agents to `haiku`
This PR:
Run a research task which will likely include a sub-task (something researching multiple entities).
=> H-2911: Improve sub-task creation process, use `innerText` summarizing webpages with Haiku

.justfile, apps/hash-graph/libs/graph/src/store/query/filter.rs, apps/hash-graph/libs/graph/src/store/query/path.rs, libs/@blockprotocol/type-system/rust/src/ontology/entity_type/mod.rs, libs/@local/harpc/wire-protocol/src/request/id.rs, libs/@local/hash-authorization/tests/simple.rs, libs/@local/status/rust/src/lib.rs, tests/hash-graph-benches/util.rs
The CI did not treat an error in the linting script as real error so it didn't print any diagnostics
=> H-2928: Fix clippy errors not shown in CI

apps/hashdotai/guide/11_pages/00_index.mdx, apps/hashdotai/guide/12_apps/00_index.mdx
If a Learn index page has 'Visibility: Hidden', that section will not be shown in the sidebar at https://hash.ai
This PR:
H-2979: Hide the pages from the sidebar that have this flag present.
=> H-2978: Add Visibility flag to some Learn pages

apps/hash-graph/openapi/openapi.json, libs/@local/hash-graph-types/rust/src/knowledge/entity/provenance.rs
If the actor type is a machine 🙃
=> H-3042: Add machine actor type

infra/terraform/hash/bastion.md
The readme covers the most important things, but for usability the easiest way is to use the `terraform` output.
=> H-3067: Update README to make connection to RDS easier

.github/renovate.json
Improves grouping of Renovate dependencies.
Closes #4701 and #4704.
=> GEN-187: Improve Renovate dependency grouping

apps/README.md
fixed typo.
- ...
ran -> run
- ...
This PR:
- this is tracked in: [Insert Link Here](link)
- _Provide more detail here_
-
1. Checkout the branch / view the deployment
1. Try X
1. Confirm that Y
=> H-3112: Fix typo in `apps/README.md`

.env, .env.development, .env.production, .env.test
Adds an explanation of how `.env` files are utilized by HASH.
=> H-3104: Document `.env` file stacking

.github/workflows/bench.yml, .github/workflows/deploy.yml, .github/workflows/hash-backend-cd.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/tf-apply-hash.yml
Updates our Slack notifications in CI to reflect current areas of ownership.
=> H-3124: Update CI Slack notifications

apps/hashdotdesign/.nvmrc, apps/hashdotdev/.nvmrc
These mirror the versions of Node for each application specified in Vercel.
=> H-3179: Add specific `.nvmrc` subdir files

.env, .env.development, apps/hashdotai/guide/01_introduction/02_core-concepts.mdx, apps/hashdotai/guide/04_types/03_property-types.mdx, apps/hashdotai/guide/04_types/04_data-types.mdx
Adds the content that corresponds with this _internal PR_: https://github.com/hashintel/internal-gitstart/pull/111
**Merge this PR first.**
Also:
- expands and improves a few other guide pages
- adds default opt-outs of telemetry enabled by various third-party tools, so that HASH is run more privately by default (internal sister PR: https://github.com/hashintel/internal/pull/159)
=> H-3204: Update `Core Concepts` page content

libs/@local/harpc/net/Cargo.toml, libs/@local/harpc/net/src/session/client/connection/collection.rs, libs/@local/harpc/net/src/session/client/connection/mod.rs, libs/@local/harpc/net/src/session/client/transaction/mod.rs, libs/@local/harpc/net/src/session/client/transaction/stream.rs, libs/@local/harpc/net/src/session/gc.rs, libs/@local/harpc/net/src/session/server/connection/collection.rs, libs/@local/harpc/net/src/session/server/connection/mod.rs, libs/@local/harpc/net/src/session/server/session_id.rs, libs/@local/harpc/net/src/session/server/task.rs, libs/@local/harpc/net/src/session/server/test.rs, libs/@local/harpc/net/src/session/server/transaction/mod.rs, libs/@local/harpc/net/src/session/test.rs, libs/@local/harpc/net/src/session/writer/mod.rs, libs/@local/harpc/net/src/transport/behaviour.rs, libs/@local/harpc/net/src/transport/connection.rs, libs/@local/harpc/net/src/transport/mod.rs, libs/@local/harpc/tower/Cargo.toml, libs/@local/harpc/tower/src/body/full.rs, libs/@local/harpc/tower/src/body/mod.rs, libs/@local/harpc/tower/src/extensions.rs, libs/@local/harpc/tower/src/net/unpack.rs
Enables and fixes workspace lints for `harpc-net` and `harpc-tower`.
This PR:
=>  H-3208: Enable workspace lints for `harpc-net` and `harpc-tower`

.github/workflows/lint.yml
If no sarif file is uploaded, GH cannot know that it's resolved 🙃
=> H-3231: Make sure clippy warnings get resolved in PR comments

libs/@local/hash-validation/src/property_type.rs
If no data type ID is provided it's not clear if the property should be interpreted as a value.
For example if a property is `[]` it's not clear if this is an empty property array or a value (e.g. `empty-list`). This adjusts the validation logic to convert the property to a value and checks it as well. This can only happen if `dataTypeId` is not specified.
=> H-3243: Fix validation for ambiguous data types

.github/renovate.json
Groups `signia` npm package updates.
=> H-3288: Add `signia` Renovate group

.github/renovate.json
The dependencies needs to be updated at the same time.
=> H-3309: Create dependency-group for libp2p

.github/CODEOWNERS
- #5033 forgot to update code owner file.
=> H-3319: Update code ownership file

.github/renovate.json
=> H-3323: Add `rollup` Renovate group

.github/workflows/lint.yml, blocks/chart/src/types/generated/block-entity.ts, blocks/faq/src/types/generated/block-entity.ts, blocks/table/src/types/generated/block-entity.ts
We updated the descriptions of some entity types. The codegen now generates these as comments.
=> H-3525: Update description of generated block code

apps/hash-graph/libs/graph/postgres_migrations/V34__closed_data_types.sql, apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/channel.rs, apps/hash-graph/libs/graph/src/store/postgres/mod.rs, apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/libs/graph/src/store/postgres/query/rows.rs
The closed data types are created but currently, they are not stored.
- Add a `closed_schema` column to data types
- Populate it when creating/updating/reindexing
This PR:
=> H-3534: Store closed data type schemas in database

Cargo.lock, Cargo.toml, libs/@local/graph/README.md, libs/@local/graph/migrations/Cargo.toml, libs/@local/graph/migrations/LICENSE.md, libs/@local/graph/migrations/package.json, libs/@local/graph/migrations/src/lib.rs
Setting up a new crate always comes with boilerplate which should be reviewed standalone.
Create the `hash-graph-migration` crate
This PR:
=> H-3581: Create crate for graph-migrations

.github/renovate.json
Groups related npm package updates in Renovate.
=> H-3623: Group `effect` packages in Renovate

libs/@local/harpc/client/typescript/src/net/internal/dns.ts
We're still experiencing DNS errors on AWS, and the switch to `dns.resolve` ([H-3792](https://linear.app/hash/issue/H-3792/harpc-switch-to-dnsresolve)) results in EADDRNOTFOUND (although it is the more correct thing to do).
(This seems to be an AWS DNS issue, not with the implementation itself)
This PR:
=> H-3806: increase DNS logging in HaRPC

apps/hash-ai-worker-ts/docker/Dockerfile, apps/hash-ai-worker-ts/src/activities/flow-activities/shared/infer-summaries-then-claims-from-text/get-entity-summaries-from-text.optimize.ai.test.ts, apps/hash-frontend/package.json, apps/hash-graph/docker/Dockerfile, apps/hash-integration-worker/docker/Dockerfile, apps/hashdotdesign/vercel-build.sh, apps/hashdotdev/package.json, apps/hashdotdev/tsconfig.json, infra/docker/api/prod/Dockerfile, infra/docker/frontend/prod/Dockerfile, infra/docker/realtime/prod/Dockerfile, infra/docker/search-loader/prod/Dockerfile, libs/@blockprotocol/graph/package.json, libs/@blockprotocol/graph/tsconfig.json, libs/@blockprotocol/type-system/typescript/tsconfig.json, libs/@local/harpc/client/typescript/tsconfig.json, libs/@local/hash-isomorphic-utils/tsconfig.json, libs/@local/tsconfig/legacy-base-tsconfig-to-refactor.json, package.json
Upgrades to use Node 22.
This PR:
=> H-3819: Upgrade to Node 22

CITATION.cff
Adds a `CITATION.cff` file to the root of the repository, so that GitHub will show citation information in its UI when viewing this repository.
@TimDiekmann @CiaranMn If you have [ORCiD](https://orcid.org/)s, please can you let me know?
=> H-3844: Add `CITATION` file

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/001-create-hash-system-types.migration.ts, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/file-preview-section.tsx, apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/outgoing-links-section/cells/linked-with-cell/linked-entity-selector.tsx, apps/hash-frontend/src/pages/goals/new.page/file-settings.tsx, apps/hash-frontend/src/pages/settings/shared/file-upload-dropzone.tsx, apps/hash-frontend/src/pages/settings/shared/image-field.tsx, apps/hash-frontend/src/pages/shared/entity-type-page/file-uploads-tab.tsx, apps/hash-frontend/src/shared/file-upload-context.tsx
In a couple of places, users might want to select multiple files to upload:
1. When providing files as context to a Flow
2. On the general file upload page
This PR enables that.
As a driveby I noticed that the user was missing a 'has cover image' link and fixed this in the migration scripts. It needs fixing in prod as part of a wider migration.
This PR:
- The 'new goal' page has less file upload functionality than the general one – it doesn't show progress or errors, nor allow retrying errors. H-3917.
- None yet.
1. Can be tested in preview deployment
https://github.com/user-attachments/assets/75e9036e-e339-4968-be8c-8812ffe7d90b
=> H-3914: Enable selecting multiple files to upload at once

.github/workflows/hash-backend-cd.yml, apps/hash-external-services/package.json, infra/terraform/hash/hash_application/api.tf, infra/terraform/hash/hash_application/main.tf, infra/terraform/hash/hash_application/spicedb.tf, infra/terraform/hash/temporal/main.tf
Mainly as it makes uploading easier and it's ~ 20% cheaper:
per vCPU per hour:
x86: $0.04048,
ARM: $0.03238
per GB per hour:
x86: $0.004445
ARM: $0.00356
Follow-up of #6224
=> H-3958: Use ARM architecture for other ECS services

.github/workflows/bench.yml
The matrix names were changed but two lines were forgotten to be adjusted.
=> H-4007: Fix benchmark CI

apps/hash-ai-worker-ts/package.json, yarn.lock
Reverts hashintel/hash#6360
This requires code changing
=> Revert "Update npm package `llamaindex` to v0.8.32"

libs/@local/harpc/client/rust/package.json, libs/@local/harpc/codec/package.json, libs/@local/harpc/server/package.json, libs/@local/harpc/system/package.json, libs/@local/harpc/tower/package.json, libs/@local/harpc/tower/src/extensions.rs
Some scripts were missing from `package.json`, this fixes that.
=> H-4047: Fix HaRPC tests not running in CI

.github/renovate.json
See https://github.com/hashintel/.github/pull/11
=> H-4073: Enable Renovate `lockFailMaintenance`

libs/@local/graph/migrations/graph-migrations/v009__entities/up.sql, libs/@local/graph/postgres-store/postgres_migrations/V40__fix_label_property_sorting.sql
Sorting by label currently does not work.
Fix `label_property` field which should be `labelProperty` instead.
=> H-4092: Fix sorting by labels not working

.cargo/config.toml, .clippy.toml, .config/nextest.toml, .rustfmt.toml, .taplo.toml, apps/lm-prompt-optimization/pyproject.toml, libs/@local/effect-dns/hickory/.cargo/config.toml, libs/antsi/rust-toolchain.toml, libs/deer/rust-toolchain.toml, libs/error-stack/rust-toolchain.toml, libs/sarif/rust-toolchain.toml, pyproject.toml, rust-toolchain.toml
Currently, we only format a very small subset of TOML files using taplo. This extends the formatting to all toml files.
=> H-4137: Apply TOML formatting to all `*.toml` files

apps/hashdotai/blog/002_information-failure.mdx, apps/hashdotai/blog/022_popular-datasets-in-hash.mdx, apps/hashdotai/blog/029_outer-space-datasets-in-hash.mdx, apps/hashdotai/blog/031_announcing-the-block-protocol.mdx, apps/hashdotai/blog/032_coronavirus-data-on-hash.mdx, apps/hashdotai/blog/033_open-sourcing-hash.mdx, apps/hashdotai/blog/035_monkeypox-infection-data-on-hash.mdx, apps/hashdotai/blog/037_what-is-the-block-protocol.mdx, apps/hashdotai/blog/038_what-is-the-entity-layer.mdx, apps/hashdotai/blog/039_self-building-database.mdx, apps/hashdotai/blog/040_aria-safeguarded-ai-supply-chains.mdx
Adds a logo banner to our new ARIA _Mathematics for Safeguarded AI_ TA3 announcement post, and improves blog post formatting consistency.
=> H-4306: Improve blog post formatting consistency

apps/hashdotai/blog/040_aria-safeguarded-ai-supply-chains.mdx
Updates the SAILS announcement post structure.
=> H-4307: Improve SAILS announcement post structure

apps/hashdotai/blog/040_aria-safeguarded-ai-supply-chains.mdx
=> H-4311: Use `Callout` in ARIA blog post

apps/hashdotai/README.md, apps/hashdotai/blog/040_aria-safeguarded-ai-supply-chains.mdx
Prepares the repo, and updates the announcement post again.
=> H-4312: Update content structure

libs/@local/hashql/ast/src/lowering/mod.rs, libs/@local/hashql/ast/src/lowering/node_renumberer.rs, libs/@local/hashql/ast/src/lowering/special_form_expander/mod.rs, libs/@local/hashql/ast/tests/ui/lowering/node-renumberer/.spec.toml, libs/@local/hashql/ast/tests/ui/lowering/node-renumberer/basic.jsonc, libs/@local/hashql/ast/tests/ui/lowering/node-renumberer/basic.stdout, libs/@local/hashql/ast/tests/ui/lowering/node-renumberer/diverging.jsonc, libs/@local/hashql/ast/tests/ui/lowering/node-renumberer/diverging.stdout, libs/@local/hashql/ast/tests/ui/lowering/node-renumberer/nested.jsonc, libs/@local/hashql/ast/tests/ui/lowering/node-renumberer/nested.stdout, libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/let-argument-not-ident.stderr, libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/let-collect-all-errors.stderr, libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/newtype-collect-all-errors.stderr, libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/type-collect-all-errors.stderr, libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/type-expr-invalid.stderr, libs/@local/hashql/compiletest/src/suite/ast_lowering_node_renumberer.rs, libs/@local/hashql/compiletest/src/suite/ast_lowering_special_form_expander.rs, libs/@local/hashql/compiletest/src/suite/common.rs, libs/@local/hashql/compiletest/src/suite/mod.rs, libs/@local/hashql/core/src/id.rs, libs/@local/hashql/diagnostics/src/diagnostic.rs
As simple as it gets, traverse the tree and increment the counter on every NodeId we encounter.
After all steps have been done, but type checking hasn't taken place yet, re-number all the NodeId to actual ids that can then be used to refer to in the tree.
This PR:
=> H-4369: HashQL: NodeId re-numbering

Cargo.lock, Cargo.toml, libs/@local/codegen/Cargo.toml, libs/@local/codegen/LICENSE.md, libs/@local/codegen/docs/dependency-diagram.mmd, libs/@local/codegen/package.json, libs/@local/codegen/src/lib.rs, yarn.lock
This adds the crate setup for the upcoming codegen implementation
=> H-4437: Add codegen crate scaffolding

.config/mise/config.toml, Cargo.lock, Cargo.toml, libs/@local/hashql/compiletest/Cargo.toml, libs/@local/repo-chores/rust/Cargo.toml
bi-weekly tool and transitive Cargo dependency bump
=> H-4408, H-4418: Bump indirect Cargo and tool dependencies

libs/@local/codegen/src/lib.rs, libs/@local/codegen/src/typescript.rs, libs/@local/codegen/tests/codegen/main.rs, libs/@local/codegen/tests/codegen/snapshots/codegen__EntityUuid::Typescript.snap, libs/@local/codegen/tests/codegen/snapshots/codegen__MapKeyEnum::Typescript.snap
It's quite easy to miss some types to be registered. This allows registering all transitive types.
=> H-4507: Support codegen type registration for transitive types

apps/hash-frontend/src/pages/shared/entity-type-page/shared/entity-type-header.tsx, apps/hash-frontend/src/pages/shared/entity-type-selector.tsx, apps/hash-frontend/src/pages/shared/entity-type.tsx, apps/hash-frontend/src/pages/shared/entity.tsx, apps/hash-frontend/src/pages/shared/entity/entity-editor/links-section/outgoing-links-section/use-create-get-cell-content.ts, apps/hash-frontend/src/pages/shared/entity/shared/create-draft-entity-subgraph.ts, apps/hash-frontend/src/pages/shared/entity/shared/use-handle-type-changes.ts, apps/hash-frontend/src/pages/shared/use-validate-entity.ts, apps/hash-frontend/src/shared/layout/layout-with-header/account-dropdown.tsx, libs/@hashintel/type-editor/src/entity-type-editor/inheritance-row.tsx
Some minor bug fixes around the type and entity editors:
1. H-1161: Don't show the 'Extend' button on archived types
2. H-1674: When selecting a parent for a type, don't show the type itself as an option in the dropdown
3. H-4570: Fix entity validation being out of sync with currently selected types for entity
4. Fix missing icon on 'Anything' chip when a link can have any destination
5. Hide page types from the entity type selector when the user does not have the pages feature flag enabled
6. Fix a `404` that would flash up when creating a new entity due to some data not being loaded in yet
Also 
7. H-1776: Add `Organizations` as an item in the navbar dropdown menu (links to `/settings/organizations`)
This PR:
1. Mostly testable on preview …
=> H-1161, H-1674, H-1776, H-4570: Small bug fixes to editors

.config/mise/config.toml, .github/CONTRIBUTING.md, blocks/minesweeper/README.md, infra/terraform/playbooks/db_recovery.md, libs/@blockprotocol/graph/README.md, libs/@hashintel/type-editor/README.md
Recurring task to upgrade tools which are not automatically updated through renovate.
=> H-4520: Bump tool dependencies

apps/hash-api/src/ai/infer-entities-websocket.ts, apps/hash-api/src/graph/knowledge/system-types/user.ts, apps/hash-api/src/graphql/resolvers/flows/start-flow.ts, apps/hash-api/src/graphql/resolvers/knowledge/file/create-file-from-url.ts, apps/hash-api/src/graphql/resolvers/knowledge/file/request-file-upload.ts, apps/hash-frontend/src/pages/shared/entity-type-selector.tsx, apps/plugin-browser/package.json, apps/plugin-browser/src/pages/popup/popup-contents.tsx, apps/plugin-browser/src/pages/popup/popup-contents/action-center.tsx, apps/plugin-browser/src/pages/popup/popup-contents/action-center/automated.tsx, apps/plugin-browser/src/pages/popup/popup-contents/action-center/history.tsx, apps/plugin-browser/src/pages/popup/popup-contents/action-center/one-off.tsx, apps/plugin-browser/src/pages/popup/popup-contents/action-center/shared/tab-props.ts, apps/plugin-browser/src/pages/popup/popup-contents/not-enabled.tsx, tests/hash-playwright/package.json, yarn.lock
Some HASH features, such as pages/notes and AI flows, are behind feature flags.
This previously just hid them in the UI. This PR improves that by:
1. Rejecting API requests for features where the feature flag isn't enabled
2. Show a message in the browser plugin if none of the feature flags gating its functionality are enabled for a user (see screenshot)
This PR:
- Publish the updated browser plugin to the Chrome store
- Basic browser plugin tests.
=> H-4488: Better feature flag handling

apps/hash-graph/src/subcommand/migrate.rs, apps/hash-graph/src/subcommand/server.rs
Runs the policy seeding as part of the Graph migrations instead of before the node migrations.
=> H-4627: Enhance migration process by adding system policy seeding

libs/@local/graph/authorization/src/policies/principal/mod.rs, libs/@local/graph/authorization/src/policies/store/error.rs, libs/@local/graph/authorization/src/policies/store/mod.rs, libs/@local/graph/authorization/types/index.snap.d.ts, libs/@local/graph/postgres-store/src/store/postgres/mod.rs, libs/@local/graph/postgres-store/src/store/postgres/seed_policies.rs
We only need to update policies if they have changed. this properly updates the policies instead of replacing them.
=> H-4651: Properly update policies instead of replacing them

libs/@local/hashql/core/src/type/environment/lattice.rs, libs/@local/hashql/core/src/type/error.rs, libs/@local/hashql/core/src/type/inference/solver/test.rs
This is very similar to the diagnostic generated (and code used) by projection.
This PR:
=> H-4646: HashQL: Implement and issue diagnostics for subscript on recursive types

libs/@local/hashql/hir/src/fold/mod.rs, libs/@local/hashql/hir/src/intern.rs, libs/@local/hashql/hir/src/node/graph/mod.rs, libs/@local/hashql/hir/src/node/graph/read.rs, libs/@local/hashql/hir/src/pretty.rs, libs/@local/hashql/hir/src/visit.rs
Unlike other code, which retains their functional nature until the MIR, due to early evaluation of the graph expressions in the HIR (for now) we convert the graph expression into a set of linear actions.
This PR:
=> H-4550: HashQL: Specify HIR Graph Expressions

infra/terraform/modules/bastion/main.tf, infra/terraform/modules/tunnel/main.tf, infra/terraform/modules/tunnel/ssh_tunnel.sh, infra/terraform/modules/tunnel/variables.tf
This PR fixes critical reliability issues in the SSH tunnel script that were causing Terraform plan failures with PostgreSQL connection errors. The script has been completely rewritten to ensure reliable tunnel establishment and verification, eliminating the "dial tcp 127.0.0.1:45678: connect: connection refused" errors that were blocking infrastructure deployments.
- **Fixed SSH command structure**: Replaced problematic `-tf` flags with proper `-f -N` flags for background daemon mode
- **Added tunnel verification**: Implemented connection testing using `nc -z` to verify tunnel works before returning success
- **Improved error handling**: Added retry logic, proper exit codes, and meaningful error messages
- **Enhanced platform compatibility**: Removed dependency on GNU `timeout` command …
=> H-4811: Make the Terraform SSH-tunneling script more robust

libs/@local/hash-isomorphic-utils/src/subgraph-mapping.ts
Small tweak to the property filtering logic.
This PR:
=> H-4896: Improve property filtering

apps/hash-graph/package.json, libs/@local/graph/api/package.json, tests/graph/benches/package.json
Some packages are missing `clippy` instructions.
=> H-4992: Add clippy to `package.json` where missing

apps/hash-graph/README.md
The Readme is quite outdated. This PR tries to improve the situaiton. While the README still is far from being perfect, it at least should not contain wrong information anymore.
=> H-4209: Update README for `app/hash-graph`

apps/hash-frontend/src/pages/maintenance.page.tsx
I've put the frontend into maintenance mode as we do db migrations, but noticed incorrect copy on it. This PR fixes that.
=> H-5026: Copy fix on maintenance page

apps/hash-external-services/README.md, apps/hash-external-services/docker-compose.dev.yml, apps/hash-external-services/grafana/provisioning/datasources/loki.yml, apps/hash-external-services/grafana/provisioning/datasources/prometheus.yml, apps/hash-external-services/grafana/provisioning/datasources/tempo.yml, apps/hash-external-services/loki/loki.yaml, apps/hash-external-services/opentelemetry-collector/otel-collector-config.yaml, apps/hash-external-services/prometheus/prometheus.yml, apps/hash-external-services/tempo/tempo.yaml, apps/hash-graph/README.md
This PR replaces the existing Jaeger-based tracing setup with a comprehensive OpenTelemetry observability stack consisting of Grafana Loki (logs), Tempo (traces), Prometheus (metrics), and Grafana (visualization). The new setup provides better service graph generation, improved trace correlation, and a unified observability experience.
- Linear issue: H-5012 (improve telemetry setup)
- OpenTelemetry Collector Documentation: https://opentelemetry.io/docs/collector/
- Grafana Observability Stack: https://grafana.com/oss/
- **Removed** Jaeger all-in-one container and related configuration
- **Added** Grafana Loki (3.5.2) for log aggregation with OTLP support
- **Added** Grafana Tempo (2.8.1) for distributed tracing with service graph generation
- **Added** Prometheus (v3.5.0) for metrics …
=> H-4208, H-5006: Replace Jaeger-tracing with Grafana in local dev

libs/@local/hashql/README.md, libs/@local/hashql/core/docs/identifier-grammar.svg, libs/@local/hashql/syntax-jexpr/docs/embedded-dsl.svg
This updates the root README with condensed information from the Großer Beleg. This has primarily been generated through GPT-5 Pro, with minor manual touch-up to experiment with the viability of such a setup.
> Tagging Dei as it is README
This PR:
=> BE-36: HashQL: Update `README` contents of HashQL

Cargo.lock, Cargo.toml, libs/@local/graph/api/Cargo.toml, libs/@local/graph/api/openapi/openapi.json, libs/@local/graph/api/src/rest/entity.rs, libs/@local/graph/api/src/rest/entity_query_request.rs, libs/@local/graph/api/src/rest/mod.rs, libs/@local/hashql/diagnostics/src/diagnostic.rs, libs/@local/hashql/diagnostics/src/label.rs, libs/@local/hashql/diagnostics/src/severity.rs, libs/@local/hashql/diagnostics/src/status.rs, libs/@local/hashql/eval/src/error.rs, libs/@local/hashql/eval/src/graph/error.rs, libs/@local/hashql/eval/src/graph/mod.rs, libs/@local/hashql/eval/src/lib.rs
Implements diagnostic reporting in the REST API. Errors are either returned as JSON (the default) or, if the `Interactive` header is set, as HTML. This allows for easy introspection by the user
This PR:
```json
[
{
"category": "hashql::ast::lowering::import-resolver::unresolved-import",
"severity": {
"id": "error",
"code": 400,
"name": "Error",
"description": "An error that prevents compilation from finishing.",
"color": "#AA0000"
},
"message": null,
"labels": [
{
"span": {
"range": {
"start": 347,
"end": 350
},
"pointer": "/1/2/4/2/1/0"
},
"message": "'Uid' not found in module '::core::uuid'",
"order": 0,
"priority": null,
"color": "#AA0000"
},
{
"span": {
"range": {
"start": 341,
"end": 345
},
"pointer": "/1/2/4/2/1/0"
},
"message": "This module",
"order": 1, …
```
=> BE-39: HashQL: Handle errors in the Graph API properly
