apps/hash-graph/docker/Dockerfile
infra/docker/api/prod/Dockerfile

We encounter frequent timeouts when building the docker images for production, this provides a fix. Please see the linked linear issues for more details.
This PR:
[The CI](https://github.com/hashintel/hash/actions/runs/5529518791/jobs/10087696585) does not have timeouts anymore

H-127: Add network timeout to Dockerfiles

---

.github/actions/docker-build-push/action.yml
infra/terraform/hash/hash_application/main.tf

The CI workers are [extremly slow](https://github.com/hashintel/hash/actions/runs/5529518791/jobs/10087696585) when compiling x86->arm so we chose to revert #2749.

Revert "IN-12: Change containers to linux/arm64"

---

.github/workflows/hash-backend-cd.yml
infra/terraform/hash/temporal/main.tf

To avoid manually pushing the worker images and temporal script images after each commit this builds the images as part of CD. This incorporates #2754 to avoid unnecessary merge conflicts. 
- #2752 
This PR:

H-48: Build and push all docker images from GitHub Actions

---

infra/terraform/hash/hash_application/main.tf

I cannot precisely tell why this is required and will investigate this at some later point but it appears to require a more general CIDR is required for `egress` to connect the temporal workers to the temporal service.

Fix CIDR block in egress for temporal workers

---

.github/pull_request_template.md

We moved the PR template checkboxes from 'check as appropriate and delete the rest' to 'uncomment as appropriate' as it was less likely that PR descriptions ended up with unnecessary checkboxes appearing as tasks to complete in the PR.
Uncommenting the checkboxes is fiddly and annoying, and so this PR goes back to 'check and delete as appropriate'.
At some point GitHub [Tasklists](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists) feature might stop checkboxes appearing as tasks unless they're explicitly marked as tasks, although in the private beta it currently only applies to Issues, not PRs.
This PR:

Update PR template checkboxes to 'tick & delete' rather than 'uncomment'

---

apps/hash-frontend/src/shared/command-bar.tsx
apps/hash-frontend/src/shared/command-bar/cheat-sheet.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/sidebar.tsx

There's a command bar which appears if you hit cmd/ctrl + K. There's also a hotkey cheat sheet which appears if you press ?. This happens even if you press ? inside contenteditables, which is not the desired behaviour.
This PR fixes that bug, but also hides the cheat sheet entirely, as it doesn't serve much purpose at the moment, since the hot keys are already shown on the command bar. Its use would be to be able to display _all_ hot keys, even ones which are not applicable in the current context, but since we don't have many at the moment and the cheat sheet requires styling, it's not worth it.
This PR:

H-149: Hide hotkey cheat sheet

---

apps/hash-graph/lib/graph/src/snapshot/ontology/entity_type/channel.rs
apps/hash-graph/lib/graph/src/snapshot/ontology/table.rs
apps/hash-graph/postgres_migrations/V9__label_property.sql

Adds the `label_property` column to the entity type database table
- #2775 
- #2778 
- Adds the `label_property` column to the entity type database table
- Adjust the snapshot API to allow the backend integration tests to continue passing. This is currently the only location where it's possible to write the label property. A follow-up PR will expose this to the REST API as well.
This PR:

H-156: Adjust database to support label properties for entity types

---

apps/hash-graph/bench/util.rs
apps/hash-graph/bin/cli/src/subcommand/server.rs
apps/hash-graph/lib/graph/src/api/rest/entity_type.rs
apps/hash-graph/lib/graph/src/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/ontology.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs
apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/query/table.rs
apps/hash-graph/tests/integration/postgres/lib.rs

The database was adjusted in H-156, this PR adjusts the Graph API to allow reading/writing the new property.
- #2775 
- #2775 
- #2782 
- Make the Query Compiler aware of the new metadata field
- Adjust the creation and updating methods for entity types to include the newly added metadata field
This PR:

H-157: Expose label property from the Database to the Graph API

---

apps/hash-graph/lib/graph/src/ontology/entity_type.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/friendship.http

Exposes the `labelProperty` metadata as query parameter
- #2775 
- #2778 
- #2782 
- #2783 
- #2784 
- Allow `labelProperty` in structure queries
- Add a doc-test
- Add REST endpoint test
This PR:

H-159: Add support to query entity types by label in Structural Queries

---

apps/hash-api/src/graph/ontology/primitive/entity-type.ts
libs/@local/hash-graphql-shared/src/graphql/scalar-mapping.ts
libs/@local/hash-graphql-shared/src/graphql/type-defs/ontology/entity-type.typedef.ts

The HASH Backend is aware of the label property. In order to make it available to the frontend, it has to be exposed to GraphQL.
- #2775 
- #2778 
- #2782 
- #2783 
- #2784 
- #2785 
This PR:

H-141: Expose `labelProperty` to GraphQL

---

infra/terraform/hash/main.tf

In order to connect to temporal the environment variables for the temporal cluster has to be set in the API package.
This PR:

H-183: Make sure HASH prod can connect to hosted Temporal Server

---

apps/hash-api/package.json
apps/hash-api/src/integrations/linear.ts
apps/hash-integration-worker/src/workflows.ts

To allow picking a list of teams to integrate into HASH this provides a functionality to list all available linear teams
This PR:

H-196: Provide functionality to list existing Linear teams

---

apps/hash-integration-worker/package.json
apps/hash-integration-worker/src/activities.ts
apps/hash-integration-worker/src/graph.ts
apps/hash-integration-worker/src/main.ts
infra/terraform/hash/main.tf

To allow creating/reading entities in/from the Graph, the API needs to be available in the integration worker.
This PR:

H-200: Make Graph API available in integration worker

---

apps/hash-api/src/graph/knowledge/system-types/linear-user-secret.ts
apps/hash-api/src/graph/system-types.ts
apps/hash-api/src/graphql/resolvers/index.ts
apps/hash-api/src/graphql/resolvers/integrations/linear/linear-teams.ts
apps/hash-api/src/integrations/linear.ts
apps/hash-api/src/integrations/linear/oauth.ts
libs/@local/hash-graphql-shared/src/graphql/type-defs/integration/linear.typedef.ts
libs/@local/hash-graphql-shared/src/graphql/type-defs/schema.ts
libs/@local/hash-isomorphic-utils/src/ontology-types.ts

This PR adds a `linearTeams` GQL resolver that obtains the linear teams in a linear org using the user's linear user secret stored in vault.
This PR:
Add it to the FE

H-202: Add `linearTeams` GraphQL resolver

---

apps/hash-api/src/graph/knowledge/system-types/linear-user-secret.ts
apps/hash-api/src/graph/system-types.ts
apps/hash-api/src/graph/util.ts
apps/hash-api/src/integrations/linear/oauth.ts
apps/hash-frontend/src/pages/integrations/linear.page.tsx
libs/@local/hash-isomorphic-utils/src/ontology-types.ts

This PR adds a `Linear Integration` entity type, and reverts the `linearUserSecret` type to the `userSecret` type by moving the `linearOrgId` property type.
This PR:
None

H-205: Add Linear integration entity type and other type changes

---

apps/hash-api/src/integrations/linear/webhook.ts
apps/hash-integration-worker/src/activities.ts
apps/hash-integration-worker/src/mappings.ts
apps/hash-integration-worker/src/workflows.ts

This adds functionality to update issues and connects both, creation and updating, to webhooks
This PR:
- The data passed in webhooks differs from the data passed from the linear node sdk, for example the web hook data does not contain the issue identifier (e.g. `H-207`). 
- the web hook data is in plain JSON, so only primitive datatypes are used, such as ISO strings for dates instead of the `Date` type. 
I will address these issues in a follow-up PR.

H-207: Allow creating and updating from Linear webhooks

---

apps/hash-api/src/graph/knowledge/primitive/entity/query.ts

H-211: Fix `ownedById` in queries returns `properties`

---

apps/hash-api/src/graph/knowledge/primitive/entity/query.ts

The Graph API's structural querying supports filtering entities by their incoming and outgoing links. We previously didn't allow this when calling `queryEntities` via the Node API, on the basis that it isn't mentioned in the Block Protocol, but this is still useful for us when calling `queryEntities` from the HASH frontend (not blocks).
This PR:

H-215: Enable querying by incoming/outgoing links via `queryEntities`

---

apps/hash-integration-worker/src/activities.ts

When updating e.g. a linear Issue and the issue was imported in different workspaces in HASH all of those entities should be updated. Currently, it fails if more than one entity with the same linear ID is updating.
This PR:

H-213: Fix updating linear entities if they exist in different workspaces

---

apps/hash-integration-worker/src/mappings.ts

The Node SDK of linear returns a Date object while the webhooks passes an ISO string. Depending where the data comes from the correct conversion needs to be done.
This PR:

H-216: Make sure the same format is used for dates in linear integration

---

apps/hash-external-services/docker-compose.yml

The `HASH_GRAPH_API_*` environment variables need to be set in order to allow connecting from external services
This PR:

H-219: Provide hash-graph environment variables for integration worker

---

apps/hash-api/src/integrations/linear/oauth.ts

The redirect url in prod still points to `localhost:5001`
This PR:

H-226: Use `apiOrigin` instead of `localhost:5001` for OAuth callback

---

infra/terraform/hash/main.tf

The variable is not set in production.
This PR:

H-224: Fix `HASH_INTEGRATION_QUEUE_NAME` not available in prod

---

apps/hash-external-services/docker-compose.yml
apps/hash-external-services/vault/config/storage.hcl

Reverts hashintel/hash#2825
It looks like some additional steps will be needed for persisted dev local Vault to avoid a 'Vault already initialized' error on start up – reverting this for now so that usage of Vault in dev is unblocked until the additional config is added.
This means that Vault secrets will be lost when rebooting the container, and integrations will have to be recreated to work.

Revert "H-220: Use `file` storage for local vault"

---

apps/hash-api/src/graphql/resolvers/integrations/linear/sync-workspaces-with-teams.ts
apps/hash-api/src/integrations/linear.ts
apps/hash-api/src/integrations/linear/sync-back.ts
apps/hash-api/src/integrations/linear/webhook.ts
apps/hash-frontend/src/pages/account/integrations/select-linear-teams-table.tsx
apps/hash-integration-worker/src/activities.ts
apps/hash-integration-worker/src/main.ts
apps/hash-integration-worker/src/mappings.ts
apps/hash-integration-worker/src/workflows.ts
libs/@local/advanced-types/src/includes.ts
libs/@local/hash-backend-utils/package.json
libs/@local/hash-backend-utils/src/temporal-workflow-types.ts

We want to share the types of Temporal workflows with the API, so that the arguments (and where relevant) return types have type safety.
One of way of doing this is to import the workflow functions themselves when starting a workflow, but this is undesirable because:
1. It requires evaluating all the code in the workflows and their supporting activities, just to get their types – potentially leading to errors
2. The design of the repo is that shared code should go in `libs/` rather than apps importing from one another
This PR introduces shared types in `@local/hash-backend-utils`
- Adds shared types
- Renames some workflow functions to make clear whether they're updating a HASH resource or a Linear resource
- Ensures that the webhook uses a correct workflow name, and simplifies the …

H-230: Share Temporal types with API

---

apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/entities-tab.tsx
apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/entity-type-tabs.tsx
apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/entity-type-tabs/tab-link.tsx
apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/shared/entity-type-entities-context.ts
apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/use-entity-type-entities-context-value.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar.tsx

The entity type editor has an 'entities' tab which shows a table of entities assigned to that type.
This table's height was unconstrained, meaning that all elements were rendered at once, causing a crash in Firefox and poor performance in other browsers.
This PR introduces a cap on the table height which allows Glide's `DataEditor` component to lazily render rows when they are in view, as it is supposed to.
I've also taken this opportunity to introduce a basic loading indicator in place of the entities count, while the data is loading. It was previously misleadingly showing `0` entities when the loading was taking place. See demo below.
This PR:
Later on, add better empty state on the entities tab while data is loading, e.g. a loading …

H-249, H-256, H-272: Fix entity type entities tab table lazy loading, add basic loading indicator

---

.github/workflows/dispatch-fix.yml
apps/hash/README.md
package.json

We have a 'Fix' workflow that can be used to manually trigger linting auto-fixes on branches in GitHub, to save people having to checkout the branch and do so locally. This is useful to fix formatting when amendments are made to docs directly in GitHub, for example.
[By design](https://github.com/orgs/community/discussions/25702#discussioncomment-3248819), any actions using the default `GITHUB_TOKEN` that workflow runners are supplied will not trigger further workflow runs, defeating the point of fixing linting.
This PR updates the fix action to use another GitHub access token, which triggers CI again.
It also fixes the action to run `yarn poetry:install` and additionally adds a menu of this requirement for fixing/linting commands to the README.
- [Slack …

H-296: Make 'Fix' workflow trigger CI again

---

apps/hash-graph/bench/util.rs
apps/hash-graph/bin/cli/src/subcommand/server.rs
apps/hash-graph/lib/graph/src/api/rest/data_type.rs
apps/hash-graph/lib/graph/src/api/rest/entity_type.rs
apps/hash-graph/lib/graph/src/api/rest/property_type.rs
apps/hash-graph/lib/graph/src/ontology.rs
apps/hash-graph/lib/graph/src/snapshot/ontology/metadata/channel.rs
apps/hash-graph/lib/graph/src/snapshot/ontology/table.rs
apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/ontology.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/integration/postgres/lib.rs
libs/@local/hash-subgraph/src/types/element/ontology.ts
libs/@local/hash-subgraph/tests/compatibility.test/map-vertices.ts

Currently, the transaction time is not returned when creating an ontology type so a type has to be queried before the transaction time is available. As this information is present when creating a type it should be returned.
- #2840 
- https://github.com/hashintel/hash/pull/2849
- Introduce a partially resolved metadata struct, which does not contain information which is only available after creating the ontology type (currently only the transaction time, maybe more in the future)
- Make the transaction time required for metadata
This PR:

H-287: Return transaction time when creating ontology type

---

apps/hash-graph/lib/graph/src/store/postgres/query/condition.rs
apps/hash-graph/lib/graph/src/store/postgres/query/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/query/expression/where_clause.rs
apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs
apps/hash-graph/lib/graph/src/store/postgres/query/table.rs

When doing nested queries in a structural query it does not necessarily take the time bounds into account - depending on the requested data. By making the ontology_temporal_metadata the entry table for ontology types this is solved.
Note: For entities, we use the same behavior.
- #2844 
- Make `ontology_temporal_metadata` the main table for ontology types - the same behavior as for entities
- Adjust the test outputs -  this mainly adds the `WHERE` clauses to the tables
This PR:

H-294: Align ontology queries to temporal data

---

apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/ontology.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs

Implements the Graph functionality to archive or unarchive ontology types.
- #2845 
This PR:

H-238: Implement type (un-)archival in the Graph

---

apps/hashdotdev/src/pages/roadmap.page.tsx

The live site is not quite ready for people to try out. This PR hides the CTA to do so on the hash.dev roadmap page until it is.
This PR:

H-312: Temporarily hide 'use HASH' CTA on roadmap page

---

apps/hash-graph/lib/graph/src/ontology/data_type.rs
apps/hash-graph/lib/graph/src/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/ontology/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs
apps/hash-graph/lib/graph/src/store/postgres/query/condition.rs
apps/hash-graph/lib/graph/src/store/postgres/query/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/query/expression/conditional.rs
apps/hash-graph/lib/graph/src/store/postgres/query/expression/join_clause.rs
apps/hash-graph/lib/graph/src/store/postgres/query/expression/order_clause.rs
apps/hash-graph/lib/graph/src/store/postgres/query/expression/select_clause.rs
apps/hash-graph/lib/graph/src/store/postgres/query/expression/where_clause.rs
apps/hash-graph/lib/graph/src/store/postgres/query/expression/with_clause.rs
apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs
apps/hash-graph/lib/graph/src/store/postgres/query/table.rs
apps/hash-graph/lib/graph/src/store/query.rs

The view currently contains all metadata of an ontology type. This is bad as different archivals and unarchivals could have been done by different persons. This needs fixing for [H-303](https://linear.app/hash/issue/H-303) and this is a good opportunity to properly use the `ontology_owned_metadata` and `ontology_external_metadata` tables instead of the view as the exact same code needs adjustment in any case.
This PR:
- Various tests in the Graph API

H-305: Split the `ontology_ids_with_metadata` view

---

apps/hash-api/src/graph/ontology/primitive/data-type.ts
apps/hash-api/src/graph/ontology/primitive/entity-type.ts
apps/hash-api/src/graph/ontology/primitive/property-type.ts
apps/hash-graph/lib/graph/src/api/rest.rs
apps/hash-graph/lib/graph/src/api/rest/data_type.rs
apps/hash-graph/lib/graph/src/api/rest/entity_type.rs
apps/hash-graph/lib/graph/src/api/rest/property_type.rs
apps/hash-graph/lib/graph/src/shared/provenance.rs
apps/hash-graph/openapi/openapi.json

We want to track the actor when archiving or restoring ontology types.
This PR:

H-307: Make `actor_id` required in archival and unarchival operations

---

apps/hash-graph/bench/util.rs
apps/hash-graph/bin/cli/src/subcommand/server.rs
apps/hash-graph/lib/graph/src/api/rest/data_type.rs
apps/hash-graph/lib/graph/src/api/rest/entity_type.rs
apps/hash-graph/lib/graph/src/api/rest/property_type.rs
apps/hash-graph/lib/graph/src/ontology/data_type.rs
apps/hash-graph/lib/graph/src/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/ontology/property_type.rs
apps/hash-graph/lib/graph/src/shared/provenance.rs
apps/hash-graph/lib/graph/src/snapshot/entity/channel.rs
apps/hash-graph/lib/graph/src/snapshot/ontology/metadata/channel.rs
apps/hash-graph/lib/graph/src/snapshot/ontology/table.rs
apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/ontology.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity/read.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs
apps/hash-graph/lib/graph/src/store/postgres/query/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/query/table.rs
apps/hash-graph/lib/graph/src/store/query.rs
apps/hash-graph/postgres_migrations/V11__archival_provenance.sql
apps/hash-graph/tests/integration/postgres/lib.rs

Implements the first approach of [H-298](https://linear.app/hash/issue/H-298) as the short-term solution to be able to record provenance data.
- #2853 
- #2854 
This PR:

H-303: Add `RecordArchivedById` for archived ontology types

---

apps/hash-graph/lib/graph/src/ontology/data_type.rs
apps/hash-graph/lib/graph/src/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/ontology/property_type.rs
apps/hash-graph/lib/graph/src/shared/provenance.rs
apps/hash-graph/openapi/openapi.json
libs/@local/hash-subgraph/src/types/shared.ts
libs/@local/hash-subgraph/src/types/shared/branded.ts
libs/@local/hash-subgraph/tests/compatibility.test/map-vertices.ts

`RecordArchivedById ` is available in the Graph and can easily be exposed to the backend. Making it queryable from structural queries is also easy to just enable it.
- #2856 
This PR:

H-306: Make `RecordArchivedById` available in TS and make it queryable

---

.dockerignore
.gitignore
.markdownlintignore
.prettierignore
infra/terraform/hash/.terraform.lock.hcl

The terraform lock file `.terraform.lock.hcl` should be committed to ensure everyone runs the commands with the exact same version.
Recommended by Hashicorp: https://developer.hashicorp.com/terraform/language/files/dependency-lock#lock-file-location
This PR:

GEN-30: Remove `.terraform.lock.hcl` from `.*ignore` files

---

apps/hash-frontend/src/blocks/page/component-view.tsx
apps/hash-frontend/src/blocks/page/create-editor-view.ts
apps/hash-frontend/src/blocks/page/page-title/page-title.tsx

This PR focuses the title input of a page when it is empty, instead of always focusing the first empty paragraph.
This PR:
None
Create a new page and ensure the title is focused instead of the body. Then check a page with a filled title, and ensure the body is focused instead.
https://github.com/hashintel/hash/assets/42802102/cc2ebe72-db5d-418a-a81d-27ccd7c86587

H-71: When creating new page, start text cursor in title, not body

---

apps/hash-frontend/src/pages/[shortname]/[page-slug].page/canvas-page.tsx

This PR adjusts the height of the TLDraw canvas component so that the relevant headers remain in view on the page.
This PR:
None
Checkout the branch, login, and view a page in canvas mode to ensure that the headers remain visible

H-76: Display header on canvas pages

---

apps/README.md

While reviewing #2873 I realized some other parts of our `apps` directory README were out of date. This removes a broken link to the old `hash-agents` sub-directory, and restructures the file slightly.

H-350: Update and restructure `apps` README

---

apps/hash-graph/lib/graph/src/ontology.rs
apps/hash-graph/lib/graph/src/store/postgres/traversal_context.rs
apps/hash-graph/lib/graph/src/subgraph.rs

With archived types it's possible to have multiple types returned but the subgraph layout does not support this. The subgraph is supposed to only return the most recent record.
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1691592695326169) _(internal)_
This PR:

H-364: Work around that subgraph can only contain a single ontology type per versioned URL

---

libs/error-stack/CHANGELOG.md
libs/error-stack/README.md
libs/error-stack/examples/demo.rs
libs/error-stack/examples/parse_config.rs
libs/error-stack/src/compat.rs
libs/error-stack/src/context.rs
libs/error-stack/src/future.rs
libs/error-stack/src/lib.rs
libs/error-stack/src/report.rs
libs/error-stack/src/result.rs
libs/error-stack/tests/snapshots/doc/lib__suggestion.snap
libs/error-stack/tests/snapshots/doc/report_debug__doc.snap
libs/error-stack/tests/test_compatibility.rs
libs/error-stack/tests/test_conversion.rs
libs/error-stack/tests/ui/into_report.rs
libs/error-stack/tests/ui/into_report.stderr

After a lot of back and forth and various discussions (internally and on GitHub and other public platforms), we decided to merge the functionality of `IntoReport` into `ResultExt`.
- Closes https://github.com/hashintel/hash/issues/1968
- Extend `ResultExt` by a `type Context: Context` associated type (technically a breaking change likely has no impact) - requires a minor version bump
- Implement `ResultExt` for `core::result::Result<T, C> where C: Context`
This PR:
- We still have `IntoReportCompat` but due to the Orphan rule it's not possible to implement `ResultExt` on `eyre` or `anyhow` errors.

GEN-37: Combine `IntoReport` and `ResultExt`

---

libs/error-stack/src/compat.rs
libs/error-stack/src/context.rs
libs/error-stack/src/fmt.rs
libs/error-stack/src/fmt/charset.rs
libs/error-stack/src/fmt/color.rs
libs/error-stack/src/fmt/config.rs
libs/error-stack/src/fmt/hook.rs
libs/error-stack/src/fmt/location.rs
libs/error-stack/src/frame/frame_impl.rs
libs/error-stack/src/hook.rs
libs/error-stack/src/iter.rs
libs/error-stack/src/lib.rs
libs/error-stack/src/macros.rs
libs/error-stack/src/report.rs
libs/error-stack/src/result.rs
libs/error-stack/tests/snapshots/doc/report_debug__doc.snap

There are a bunch of locations in `error-stack` which could be improved slightly. The amount of changes adds up and it's worth doing this in a separate PR.
- Clean up imports
- Remove unneeded `repr(C)` (we don't rely on it anymore and if we would we should use `repr(transparent)`
- Remove feature flags in doc test except for `nightly` checks (we only run doc tests for stable+nightly with `--all-features`; no `miri` and no feature permutations
- Some other minor changes
This PR:

GEN-38: Minor improvements of code quality

---

apps/hash-graph/lib/graph/src/ontology.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs
apps/hash-graph/lib/graph/src/store/postgres/traversal_context.rs
apps/hash-graph/lib/graph/src/subgraph.rs

#2879 did not cover all possible paths. Instead of manually comparing the time it will now rely on the ordering returned from the database. The latest record will always be returned first.
- Reverts #2879
Correctly pick the ontology type when traversing
This PR:

H-372: Work around that subgraph can only contain a single ontology type per versioned URL, 2nd Attempt

---

apps/hash-graph/lib/graph/src/shared/identifier/time/timestamp.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs

It's required to change the creation and updating methods for entities again and instead of duplicating them it can also be moved out directly so it's easier to change them later.
- Move the. methods to Rust
- Drive-by improvements for `ToSql` and `FromSql` implementation for `Timestamp`
This PR:
Drop the old functions but I will do this when I have to add a new migration file anyway.

H-365: Move `create_entity` and `update_entity` out of the migration files

---

apps/hash-frontend/src/pages/settings/organizations/[shortname]/general.page.tsx

Fixes a bug where the form state for organization general settings was not reset when switching between organizations.
This PR:
1.  Have multiple orgs, visit the settings page for one, then another, check the form shows the correct values for each

H-375: Set form state properly when switching between organizations

---

libs/error-stack/Cargo.toml

The latest toolchain updated the `Error::provide` API. `anyhow` already updated to the latest nightly, which implies that we cannot use their latest version. This PR limits the `anyhow` version to the compatible range.
- https://github.com/dtolnay/anyhow/pull/319
- https://github.com/rust-lang/rust/pull/113464
This PR:
- [GEN-53: Update to latest `Error::provide` version](https://linear.app/hash/issue/GEN-53) _(internal)_

GEN-52: Limit version of `anyhow` to `1.0.72`

---

.github/renovate.json

Fixes https://github.com/hashintel/hash/issues/2902 originally broken by https://github.com/hashintel/hash/pull/2892
Essentially just moves stuff around (a bunch of stuff into `packageRules` which should have been there to begin with).

H-394, GEN-46: Fix Renovate

---

turbo.json

The top-level jobs `dev:*` are not marked as persistent and also don't depend on `^build` and `codegen`.
This PR:

H-422: Fix `dev:*` jobs not marked as persistent

---

.github/workflows/ci.yml

The external services require the integration worker. Until now it never happened (to my knowledge) that the BE tests or PW tests started before the integration worker completed but it just happened for the first time and to avoid issues in the future, it should be made sure that the tests are waiting for the worker to be built.
This PR:

H-423: Make BE tests and PW tests depend on the integration worker

---

apps/hash-graph/lib/graph/src/knowledge/entity/query.rs
apps/hash-graph/lib/graph/src/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/query.rs

Currently, by default, the maximum inheritance depth is used for query parameters. To allow specifying it a parameter may be passed to the query token, e.g. instead of `["type", "versionedUrl"]` it can be specified as `["type(inheritanceDepth = 5)", "versionedUrl]`.
This PR:

H-426: Extend structural queries to allow specifying inheritance depth

---

apps/hash-frontend/src/pages/shared/auth-info-context.tsx
apps/hash-frontend/src/pages/types/[[...type-kind]].page.tsx

This PR fixes the "View all types" page in production, which currently does not display correctly in production because the `authenticatedUser` is set to `undefined` on the `/types` page even when the user is logged in.
This was occurring because `getInitialProps` in `_app.page.tsx` is not compatible with `getStaticProps` in `/types`. This PR addresses this by replacing `getStaticProps` with `getServerSideProps` in the `/types` page.
This PR:
None
Click on the deployment, login, and go to the "View all types" page. Ensure the sidebar doesn't disappear, and the table is displaying as expected.

H-451: Fix "View all types" page in production

---

.github/renovate.json

Renovate does not trigger updates automatically
- Globally sets the schedule but only selectively disable the required dashboard approval
This PR:

GEN-62: Fix renovate not scheduling updates

---

apps/hashdotdev/src/util/mdx-components.tsx

The anchor tag handling in hash.dev was rewriting https://blockprotocol.org links as internal, when they aren't. This PR fixes that.
This PR:
1.  Go to a page containing links to the BP site, e.g. `/blog/block-protocol-0-3-wordpress`
2. Check that a link to a BP URL works correctly

H-476: Fix internal link detection in hash.dev

---

apps/hash-graph/.justfile
apps/hash/README.md
libs/@local/hash-graph-sdk/python/graph_sdk/filter/path.py
libs/@local/hash-graph-sdk/python/package.json
libs/@local/hash-graph-sdk/python/scripts/codegen_blocking.sh
libs/@local/hash-graph-sdk/python/scripts/codegen_filter.sh
libs/@local/hash-graph-sdk/python/turbo.json

This updates the `OpenAPI` generation to include filters upon generation, something I forgot in the previous PR (#2868)
This PR:

H-454: Update Python OpenAPI generation to include filters

---

libs/deer/desert/src/lib.rs

The `no_std` causes problem. I'm not going to track down why this is the case because this PR needs to be merged ASAP to unblock other PRs.

GEN-71: Fix CI for `deer`

---

libs/deer/desert/Cargo.toml
libs/deer/desert/src/assert.rs
libs/deer/desert/src/lib.rs

This fixes the CI failure exhibited because `similar-assert` `1.5` has been released; the change made it so that the macro now invokes another macro (instead of a function), leading to `similar-assert` calling the `format!` macro in client code instead of library code.
This PR:

GEN-71: Fix `deer` CI failure

---

apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx
apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/use-entity-type-value.tsx
libs/@hashintel/type-editor/src/entity-type-editor/inheritance-row/inherited-type-card.tsx

This PR fixes two bugs related to the entity type form: a crash could occur when switching between viewing two different types in the form, either navigating via the sidebar (moving between pages for two different types), or navigating between types in the preview slide.
The crash was caused by a mismatch between the data loaded into the form, which contains references to property types, and the property type options available to the form: it was possible for the options to be missing the property types the form data referenced. The same is true for link types.
There were two variants of this:
**1.** In the preview slide, navigating from a type with any properties to another type which was missing at least one of those properties caused a crash because the property type options were …

H-528: Fix bugs when navigating between types

---

.github/workflows/rust.yml
libs/error-stack/CHANGELOG.md
libs/error-stack/Cargo.toml

With the latest nightly change it's required to set a `git` dependency for error-stack if a nightly compiler is used.
- Bump version of `error-stack` to `0.4.0`
- Adjust changelog to point to the upcoming release tag
- `error-stack@0.3.1` does not compile on the current nightly channel (the main reason for this release), so the SemVer check cannot pass. I temporarily disabled it. I will enable it again after this PR is merged.
This PR:

GEN-77: Bump `error-stack` to 0.4

---

apps/hash-graph/lib/graph/src/snapshot/entity/batch.rs

We insert the data of snapshot in batches. Entity IDs and edition may occur multiple times as for each version the full entity is emitted. If the entities are inserted in the same batch they are deduplicated but not if they are inserted in different batches. This results in a primary key error.
This PR:
Ideally, the checks would only ignore the action if the full row is a duplicate, not only of the primary key constraint fails. This is not easily possible and can be ignored for now

H-557: Fix snapshot restore for big snapshots

---

apps/hash-frontend/src/shared/command-bar.tsx
apps/hash-frontend/src/shared/command-bar/cheat-sheet.tsx
apps/hash-frontend/src/shared/layout/layout-with-header/search-bar/search-input.tsx

Fixes a bug whereby hotkeys could apparently randomly be detected as pressed when they weren't.
The easiest recreation is to press CTRL + F to bring up the browser's find window, and click back in the page, then press K – the command bar will appear.
The underlying issue is described in https://github.com/imbhargav5/rooks/issues/1730
This PR fixes it by adding a listener for when the window loses focus, and clearing the 'pressed keys' map. We already had our own adaption of `useKeys` which could be further adapted to do this.
There are a couple of other places where we use `rooks`'s `useKeys`, but these are in components that currently aren't used (hotkey cheatsheet, and search bar). I've commented the hotkey functionality out in those so that it's obvious there is a bug to be fixed when …

H-277: Fix hotkeys detected as being pressed when they aren't

---

.github/renovate.json

Renovate is able to put the SHA on the tag by using
```json
{
"extends": ["helpers:pinGitHubActionDigests"]
}
```
- https://docs.renovatebot.com/modules/manager/github-actions/#additional-information
This PR:

H-604: Use SHA for GH Actions when using renovate

---

.github/workflows/semgrep.yml

Semgrep fails on main as it is detecting errors. This implies that it cannot upload the SARIF file as it fails before. This allows errors as the errors are already on main. The CI is not running on a PR.

H-606: Fix Semgrep Action on main branch

---

apps/hashdotdev/src/pages/roadmap/technology-tree.tsx

Fixes an issue whereby zooming on the roadmap wouldn't zoom at the cursor position.
There's now a different issue, which is that after resizing the window, the very first pan or zoom will jump to a different position.
- Use fresh values for wrapper height/width in the 'on zoom' callback.
- Change how initial height and height offset on zooming works.
This PR:
- See description.
1.  Zoom and pan the roadmap in the following conditions:
- on page load
- after resizing
- after switching between fullscreen and back again
- refreshing at different sizes

H-623: Zoom to correct position in roadmap

---

apps/hash-graph/lib/authorization/src/backend.rs
apps/hash-graph/lib/authorization/src/backend/spicedb.rs
apps/hash-graph/lib/authorization/src/lib.rs
apps/hash-graph/lib/authorization/src/zanzibar.rs

New relations should be able to be added from the Graph.
- Adds new function `update_relationship` and expose it as `create_relation`
- Make ordering of parameters consistent: 1. resource, 2. affiliation, 3. subject. This makes it consistent with a `Tuple` and across different functions 
- Make it possible to pass unsized types to the functions
- #3014 
This PR:

H-469: Support creating new relationships

---

.github/actions/build-docker-images/action.yml
.github/actions/load-docker-images/action.yml
.github/workflows/remove-obsolete-caches.yml

We encountered a lot of issues when attempting to download a previously uploaded docker image. To mitigate this issue, the registry will now only be used for caching and for passing around the images, artifacts are used.
This PR:

H-646: Use artifacts to pass around docker images

---

.github/workflows/semgrep.yml

The Semgrep (main) check now passes, but the merge_group one does not because the branch does not exist anymore. We should probably just disable that one.

H-612: Disable Semgrep in merge groups

---

.github/workflows/ci.yml
.github/workflows/rust.yml
apps/hash-external-services/docker-compose.prod.yml
apps/hash-external-services/docker-compose.prototype.yml
apps/hash-external-services/docker-compose.test.yml
apps/hash-external-services/docker-compose.type-fetcher.yml
apps/hash-external-services/docker-compose.yml
apps/hash-external-services/postgres/postgresql.conf
apps/hash-graph/.justfile

The `spicedb-migrate` jobs fails because it may run before postgres is up.
This PR:

H-645: Attempt to figure out the reason why `spicedb-migrate` fails

---

apps/hash-graph/lib/authorization/src/backend.rs
apps/hash-graph/lib/authorization/src/backend/spicedb.rs

Similar to the creation of relationships, the deletion is fundamental for a permission system.
This PR:

H-649: Support deletion of relationships

---

.github/workflows/rust.yml
apps/hash-graph/docker/Dockerfile

Previously, we required to install protoc in CI and in the Dockerfile but this is not needed anymore as the upstream issue is fixed.
- https://github.com/open-telemetry/opentelemetry-rust/issues/934
- https://github.com/hashintel/hash/pull/2987
This PR:

H-662: Remove installation of `protoc`

---

apps/hashdotdev/src/pages/roadmap.page.tsx

On the hash.dev [roadmap page](https://hash.dev/roadmap), there's a 'General' category of feature area – this is meant to be a method of categorising and filtering roadmap items, but not listed as a 'Use case'. This PR fixes that by hiding it from the 'Use case' list.
This PR:
1.  View the deployment

H-666: Hide 'General' from use case list

---

apps/hash-graph/lib/authorization/src/backend.rs
apps/hash-graph/lib/authorization/src/backend/spicedb/api.rs
apps/hash-graph/lib/authorization/src/backend/spicedb/model.rs
apps/hash-graph/lib/authorization/src/zanzibar.rs
apps/hash-graph/lib/authorization/tests/api.rs
apps/hash-graph/lib/authorization/tests/schema.rs
apps/hash-graph/lib/authorization/tests/simple.rs

SpiceDB allows to modify (touch, create, delete) relations. For simplicity we only expose a non-batched version yet. This PR improves some DX issues we had previously (discussed offline) and allows multiple tuples to be inserted/deleted at the same time.
- Support preconditions in modification endpoints
- Simplify interface to improve DX and probably compile time
- Allow multiple tuples to be passed in modification endpoints
This PR:
The authorization integration tests uses the new batch creation/deletion methods

H-642: Allow mass creation/deletion of relationships

---

apps/hashdotdev/src/_pages/blog/0008_sensitivity-assessor.mdx

Fixes a broken link/typo that slipped in.

GEN-93(b): Fix typo in migration

---

.github/workflows/ci.yml
apps/hash-ai-worker-py/docker/Dockerfile
apps/hash-external-services/docker-compose.test.yml
apps/hash-frontend/package.json
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
tests/hash-playwright/package.json

The current `CI` workflow always runs regardless of the changes. improves the behavior to only run it if needed. This can be optimized further such as only lint and run the unit tests if needed but the BE and PW tests requires a big setup this this is the first step to improve the behavior
- Adds a dependency for the PW tests on the frontend and make the API a dependency of the frontend which implies a chain of dependencies
- Check for changes in CI
- Run the bespoken jobs only if required
This PR:

GEN-57: Run BE-Test and PW-Test only if needed in CI

---

libs/error-stack/src/result.rs

The deprecation warning mentioned `ReportExt` instead of `ResultExt` which might be confusing.
- Closes https://github.com/hashintel/hash/issues/3087
This PR:

GEN-102: Fix deprecation warning typo for `IntoReport`

---

libs/error-stack/CHANGELOG.md
libs/error-stack/Cargo.toml

To avoid further confusion with the deprecation warning this is worth bumping the version.
- #3088 
This PR:

GEN-103: Bump `error-stack` to v0.4.1

---

apps/hash-external-services/docker-compose.prod.yml

This simply adds `HASH_INTEGRATION_QUEUE_NAME` to the `hash-api` service in the `docker-compose.prod.yml`, as otherwise start-up in production environments would fail.
This PR:

H-704: Add `HASH_INTEGRATION_QUEUE_NAME` to production `hash-api` service

---

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor-page.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/query-editor-page.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/select-entity-type-page.tsx
apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx
apps/hash-frontend/src/pages/new/types/entity-type.page.tsx

1. Stop hardcoding 'hash.ai' as the domain for display in certain paths, and use the `frontendDomain` instead, which is derived as follows:
```ts
export const frontendUrl =
process.env.NEXT_PUBLIC_FRONTEND_URL ??
(process.env.NEXT_PUBLIC_VERCEL_URL
? `https://${process.env.NEXT_PUBLIC_VERCEL_URL}`
: process.env.FRONTEND_URL ?? "http://localhost:3000");
export const frontendDomain = new URL(frontendUrl).hostname;
```
2. Prevent creation of new versions of an entity type unless the form is dirty, as a safety fallback – mysterious unprompted form submission has been witnessed in the past. We should figure out what could have caused this (H-706), but in the meantime this might prevent whatever the underlying bug is from causing versions to be created when they shouldn't
This PR:
The changes …

H-708, H-709: Avoid hardcoding instances of the FE domain, redundant type version increments

---

apps/hashdotdev/next.config.js

Updates `next.config.js` to set `poweredByHeader` to `false` and ensures `hash.dev/labs` redirects correctly without relying on Cloudflare Rules.
- [poweredByHeader](https://nextjs.org/docs/app/api-reference/next-config-js/poweredByHeader) in the `Next.js` docs

GEN-101: Add HDEV redirect and opt out of `poweredByHeader`

---

apps/hash-graph/lib/graph/src/api/rest.rs
apps/hash-graph/lib/graph/src/lib.rs
apps/hash-graph/lib/graph/src/store/account.rs
apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/knowledge.rs
apps/hash-graph/lib/graph/src/store/migration.rs
apps/hash-graph/lib/graph/src/store/ontology.rs
apps/hash-graph/lib/graph/src/store/pool.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/lib/graph/src/store/postgres/migration.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/pool.rs

On `nightly` it's possible to replace the amazing `#[async_trait]` by the native implementation.
This PR:
Replacing `Read` - the last remaining `trait` using `#[async_trait]` - is left as an exercise for the reader/reviewer.

H-721: Replace almost all `#[async_trait]` usages with native `async trait`

---

apps/hash-graph/lib/graph/src/api/rest.rs
apps/hash-graph/lib/graph/src/lib.rs
apps/hash-graph/lib/graph/src/store/account.rs
apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/knowledge.rs
apps/hash-graph/lib/graph/src/store/migration.rs
apps/hash-graph/lib/graph/src/store/ontology.rs
apps/hash-graph/lib/graph/src/store/pool.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/lib/graph/src/store/postgres/migration.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/pool.rs

This reverts commit 52dfa7ed50426e6c7799fbf771cc6fecb43cb018.
It's amazing that `async trait` is there, now, but we encounter a huge impact on compile times. A build on my machine built in 15 seconds previously, with H-721 merged, takes 1m 6s.

Revert "H-721: Replace almost all `#[async_trait]` usages with native `async trait` (#3099)"

---

apps/hash-frontend/src/components/hooks/use-logout-flow.ts
apps/hash-frontend/src/pages/login.page.tsx

This PR updates the logout behaviour to redirect the user to the login page, when not viewing a publicly viewable page.
- fixes the `return_to` query parameter on the `/login` page
This PR:
None
1. Login, and navigate away from the homepage to another page
2. Logout
4. If the page is a publicly accessible page (i.e. any page), ensure the user remains on the page in readonly mode. If the page is any other page, then ensure that you are redirected to the `/login` page. When logging back in you should be redirected to the previously viewed page.
https://github.com/hashintel/hash/assets/42802102/86b92915-9e07-4f5a-a4b3-c6eec23dabfa

H-139: Redirect user to login page when logging out

---

apps/hash-graph/lib/authorization/src/api.rs
apps/hash-graph/lib/authorization/src/lib.rs
apps/hash-graph/lib/graph/src/api/rest.rs
apps/hash-graph/lib/graph/src/api/rest/account.rs
apps/hash-graph/lib/graph/src/api/rest/api_resource.rs
apps/hash-graph/lib/graph/src/api/rest/data_type.rs
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/lib/graph/src/api/rest/entity_type.rs
apps/hash-graph/lib/graph/src/api/rest/property_type.rs
apps/hash-graph/lib/graph/src/store/pool.rs

We need to create new connections to the underlying Authorization client per request. The current design enforces this as otherwise it's not possible to (properly) get a mutable instance of the backend in the code. I took the opportunity to make the REST interface a bit more readable and unified the parameter names/types so the follow-up PR will be easier.
This PR:

H-722: Create an `AuthorizationApiPool` to create connections to the auth backend

---

.vscode/extensions.json

Adds actively used lint and test tools we use within the monorepo to the `.vscode/extensions.json` recommendations file where plugins exist for them.
We were already recommending some test tools (e.g. Playwright) and linters (e.g. markdownlint) so this just makes it consistent. Alternatively, if we don't want these, we should consider removing the `.vscode` config directory entirely. It's a bit frustrating we can't achieve this via stadardized `EditorConfig` or by nesting the `vscode` prefs within our general top-level `.config` dir, but I think these plugins represent useful helper utils.

GEN-97: Add recommended VSCode lint and test plugins

---

apps/hash-graph/bench/read_scaling/knowledge/complete/entity.rs
apps/hash-graph/bench/read_scaling/knowledge/linkless/entity.rs
apps/hash-graph/bench/representative_read/knowledge/entity.rs
apps/hash-graph/bench/representative_read/ontology/entity_type.rs
apps/hash-graph/bench/representative_read/seed.rs
apps/hash-graph/bench/util.rs
apps/hash-graph/bin/cli/src/subcommand/server.rs
apps/hash-graph/lib/graph/src/api/rest.rs
apps/hash-graph/lib/graph/src/api/rest/account.rs
apps/hash-graph/lib/graph/src/api/rest/data_type.rs
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/lib/graph/src/api/rest/entity_type.rs
apps/hash-graph/lib/graph/src/api/rest/property_type.rs
apps/hash-graph/lib/graph/src/api/rest/test_server.rs
apps/hash-graph/lib/graph/src/store/account.rs
apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/knowledge.rs
apps/hash-graph/lib/graph/src/store/ontology.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/tests/integration/postgres/lib.rs

To use the authorization API in the store it needs to be made available to it. The mutability was carefully picked so the API does not need to be mutable if only information needs to be fetched but no new permissions has to be inserted. This allows a read-only access to the permission service where the API itself does not need to be `Send`, only `Sync`. The mutable version requires both, `Send` and `Sync`.
- #3114 
This PR:

H-741: Provide the authorization API to every Graph function

---

apps/hash-ai-worker-py/turbo.json
libs/@local/hash-graph-client/python/graph_client/__init__.py
libs/@local/hash-graph-client/python/turbo.json
libs/@local/hash-graph-sdk/python/examples/query_company_entities.py
libs/@local/hash-graph-sdk/python/examples/query_company_entities_limited_axes.py
libs/@local/hash-graph-sdk/python/examples/query_company_entity_type.py
libs/@local/hash-graph-sdk/python/graph_sdk/client/blocking.py
libs/@local/hash-graph-sdk/python/graph_sdk/client/concurrent.py
libs/@local/hash-graph-sdk/python/graph_sdk/types.py
libs/@local/hash-graph-sdk/python/scripts/generate_blocking.py
libs/@local/hash-graph-sdk/python/turbo.json
libs/@local/hash-graph-types/turbo.json

This applies the recent change of #3103 to the `hash-graph-client` (and subsequently `hash-graph-sdk`) packages and _significantly_ improves the ergonomics of setting and using an actor.
As a drive-by, an issue with the `turbo.json` that was discovered in #3119 has been fixed by requiring that `lint` is a dependency of `build`.
This PR:

H-745: Apply changes to python packages

---

apps/hash-frontend/src/components/emoji-picker/emoji-picker.tsx
apps/hash-frontend/src/components/page-icon.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-entity-type-list.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-page-list/account-page-list.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-page-list/page-tree-item.tsx

This PR makes improves the styling and makes some fixes to the sidebar of the HASH app.
Additional ticket addressed in this PR: [Make font weight of types match those of pages, and make whitespace between them and "View all" equal between both.](https://linear.app/hash/issue/H-738/make-font-weight-of-types-match-those-of-pages-and-make-whitespace)
- changes the “Add subpages, delete, duplicate and more” tooltip to simply read “Options”
- always display the right chevron of pages in the tree, displaying "No sub-pages inside" when un-collapsing a page which has no children
- prevents the emoji picker from repositioning when it is used on non-top-level pages
- fixes a bug which set incorrect fractional indexes for top-level pages when they were repositioned. Previously if you rearranged a …

H-587: Sidebar styling improvements and fixes

---

apps/hash-external-services/README.md

Fixes the command used to apply the snapshots to include the `exec` subcommand, previously I must've removed it accidentally.
> Huge PR, I know.
This PR:

Fix `hash-external-apps` README backup command invocation

---

.github/workflows/rust.yml
.justfile

`cargo-hack@0.6.6` introduced groups in CI which makes reading CI much easier.
This PR:

H-766: Update `cargo-hack` to at least `0.6.6`

---

apps/hash-frontend/package.json
apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx
apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/use-entity-type-value.tsx
apps/hash-frontend/src/shared/entity-types-context/hooks.ts
libs/@hashintel/query-editor/package.json
libs/@hashintel/type-editor/package.json
libs/@hashintel/type-editor/src/entity-type-editor/shared/use-inherited-values.ts
yarn.lock

This PR fixes a couple of bugs related to moving from an existing entity type to a draft entity type without leaving the type editor page, which has only been possible since the introduction of the 'Extend type' button
1. Resets the edit bar state when moving between types (fixes click extend type, edit bar shows incorrect version)
2. Update `completedRef.current` when tracking which type we last loaded to take account of moving from a type to a draft and then back to the same type (fixes click extend type, click parent in sidebar, form state does not reset)
3. Wait for entity types to load before checking ancestors (fixes click extend type, then refresh page)
4. Add hacky timeout when resetting form state with a draft (fixes click extend type where the parent has at least one of its own …

H-767: Fix bugs in type editor form when moving between types

---

apps/hash-graph/Cargo.lock
apps/hash-graph/lib/graph/Cargo.toml
apps/hash-graph/lib/graph/src/snapshot/ontology/data_type/channel.rs
apps/hash-graph/lib/graph/src/snapshot/ontology/entity_type/channel.rs
apps/hash-graph/lib/graph/src/snapshot/ontology/property_type/channel.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/ontology_id.rs

To deterministically create ontology IDs newly inserted IDs will be UUIDv5. This implies that after dumping and restoring a snapshot all IDs will be v5.
This PR:

H-668: Use UUIDv5 for newly created ontology id

---

apps/hash-frontend/src/pages/login.page.tsx
apps/hash-frontend/src/pages/settings/organizations/new/index.page/create-org-form.tsx
apps/hash-frontend/src/pages/settings/organizations/shared/org-form.tsx
apps/hash-frontend/src/pages/signup.page.tsx
libs/@hashintel/design-system/src/theme/components.ts
libs/@hashintel/design-system/src/theme/components/inputs/mui-input-base-theme-options.ts

This PR stops the display name from autofocusing on the general page for existing orgs, and prevents 1Password from autofilling inputs by default (which is overridden in the `/login` and `/signup` pages where this behaviour is desired).
In addition it disables the Safari contact button for all inputs, which was also appearing on the display name input for organisations.
This PR:
None
1. Go to an individual org's "General" page, and observe the display name no longer being autofocused, and that 1Password/Safari is no longer attempting to autofill the input.
2. Go to the login page, and verify 1Password is still trying to complete the relevant inputs.
https://github.com/hashintel/hash/assets/42802102/58982e75-ffed-43a0-a387-8c7bbdc46775

H-585: Individual org's "General" page improvements

---

apps/hash-frontend/src/lib/entities.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/shared/use-draft-entity-subgraph.ts
libs/@local/hash-isomorphic-utils/src/simplify-properties.ts
libs/@local/hash-subgraph/src/stdlib/subgraph/element/entity-type.ts

We have a custom `labelProperty` which can be set on entity types, which indicates which property should be used when labelling an entity in the UI. 
This PR starts using it to label entities, where it is defined on the entity's type or on its type's parents (preferring closer ones).
I've also simplified how we check for fallbacks based on some property names that should make for reasonable labels.
This PR:
- H-142: Allow setting a type's label property in the UI (currently only configurable via the API/db)
- None
1. Try setting a `labelProperty` on a type or its parents (directly in the db locally is easiest), then creating an entity with that property value
https://github.com/hashintel/hash/assets/37743469/919ea905-dd9a-48e5-ae74-5293fb77f6 …

H-760: Check `labelProperty`s when generating an entity's label

---

apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs

When inserting a type or an entity the graph needs to know if the `owned_by_id` is an `AccountId` or an `AccoutGroupId`. Even though it's not used, yet, it will be in the near future.
- Upon insertion check if the id is in the `accounts` table or `account_groups` table
- Store the retrieved information in a variable
This PR:

H-743: Determine `OwnedById` type when inserting a record

---

apps/hash-frontend/src/pages/settings/organizations/[shortname]/members.page.tsx
apps/hash-frontend/src/pages/settings/organizations/[shortname]/members.page/member-row/member-context-menu.tsx
apps/hash-frontend/src/pages/settings/organizations/index.page/org-row.tsx
apps/hash-frontend/src/pages/settings/organizations/index.page/org-row/org-context-menu.tsx
apps/hash-frontend/src/pages/settings/shared/context-menu.tsx
libs/@hashintel/design-system/src/menu-item.tsx
libs/@hashintel/design-system/src/text-field.tsx

This PR adds functionality and styling to the context menu on the `/settings/orgs` page, including:
- a "View profile" button
- a "Edit profile" button
- a "View members" button
- an "Invite new members" button
- updates the styling of the "Leave Organization" button in the org and member context menu to be red
- focuses the invite member input on the members page when a `#invite` anchor tag is provided
This PR:
None
Go to the `/settings/organizations` page and test out the new context menu buttons.
https://github.com/hashintel/hash/assets/42802102/e7f3a559-c3e3-455a-8343-8dd2d3324c68

H-584: Improve context menu on `/settings/organizations` page

---

apps/hash-graph/lib/graph/src/snapshot/ontology/metadata/batch.rs

If a type was archived and then unarchived it cannot be restored using snapshots.
- #3151 
This PR:

H-769: Fix snapshots to work with archived types

---

libs/@local/hash-graph-types/turbo.json

The build step is a required step for any downstream package. This implies as soon as a package depends on hash-graph-types and that package and that package is being built, that mypy will run on hash-graph-types.
This PR:

H-775: Don't run `lint:mypy` as a build step in `hash-graph-types`

---

apps/hashdotdev/src/components/blog-post.tsx

This PR makes use of the blurred placeholder image for the image of authors of blog posts in the hash.dev site.
- H-629
This PR:
None
Go to a blog post on the hash.dev site, and click refresh. Observe the image of an author being blurred briefly before loaded.
https://github.com/hashintel/hash/assets/42802102/89ab25d0-4e50-4a48-822f-5385dad7dfd2

H-629: Ensure blurhash appears for author photos on HDEV post pages

---

apps/hashdotdev/src/components/pre-footer.tsx

This PR fixes the icon size for the "email" icon shown on successful subscription to the hash.dev blog.
- H-734
This PR:
None
Go to the `/blog` page and subscribe to the email list to see the success state.

H-734: Increase size of "email" icon shown on successful subscription to hash.dev blog

---

apps/hash-api/src/graph/knowledge/system-types/org-membership.ts
apps/hash-graph/lib/authorization/src/api.rs
apps/hash-graph/lib/authorization/src/lib.rs
apps/hash-graph/lib/graph/src/api/rest/account.rs
apps/hash-graph/openapi/openapi.json

The Graph is not aware how users are added to organizations. For this, the Graph needs to expose the functionality to add and remove members from an account group.
- #3164 
This PR:

H-778: Expose account group membership in the Graph REST API

---

libs/@hashintel/design-system/src/text-field.tsx

This PR fixes a bug that was introduced in https://github.com/hashintel/hash/pull/3155, where the usage of `inputProps` on the `TextField` component to disable 1Password on inputs by default prevented the `ref` from being passed to the component correctly for some reason.
This broke several inputs in the application which relied upon the `ref` being set, for example the link type selector in the entity type editor, the link selector in the entity editor, etc.
After some trial and error, I discovered that using the `slotProps` prop to achieve the override does not introduce this issue.
- H-786
This PR:
None.
Try adding a link to an entity type, and confirm this is working again.
Go to `/settings/organizations/example-org/members` and inspect …

H-786: fix `TextField` ref not being passed to component correctly

---

tests/hash-playwright/tests/shared/login-using-temp-form.ts

We've been noticing increasing flakiness of Playwright tests, specifically timing out while waiting for login.
This doesn't appear to happen consistently – possibly increasing the timeout will help.
This PR:
- Playwright test performance and coverage generally is tracked in H-463
- Playwright ones.
1. No retries necessary on this PR's Playwright tests would be a good signal, but otherwise hard to test.

H-801: Increase Playwright test timeout

---

apps/hash-graph/lib/authorization/src/backend.rs
apps/hash-graph/lib/authorization/src/backend/spicedb/api.rs
apps/hash-graph/lib/authorization/src/backend/spicedb/model.rs
apps/hash-graph/lib/authorization/src/zanzibar.rs
apps/hash-graph/lib/authorization/src/zanzibar/types.rs
apps/hash-graph/lib/authorization/tests/api.rs
apps/hash-graph/lib/authorization/tests/schema.rs
apps/hash-graph/lib/authorization/tests/simple.rs

The current implementation of the permission system requires `AsRef<str>`. We only use `UUID`s or `UUID`-like identifiers in the Graph, but `Uuid` does not implement the trait (It only implements `AsRef<[u8]>`).
We currently have the compatibility for untyped tuple but we don't expect this to be used as the plan for migrations is do be more fine-grained within snapshots.
To solve this, the `Tuple` trait requires associated types (which would be required to properly implement a gRPC interface as well), so we can directly serialize it into JSON (or a `Message` for gRPC).
- #3171 
This PR:
A known issue is that the interface with optional parameters might be more unintuitive to use but as we currently don't use that interface we can worry about …

H-787: Allow usage of non-string values as permission object/subject

---

apps/hash-graph/lib/authorization/src/api.rs
apps/hash-graph/lib/authorization/src/lib.rs
apps/hash-graph/lib/authorization/src/zanzibar/api.rs
apps/hash-graph/lib/graph/src/api/rest/account.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs

Account groups require some kind of administration, otherwise it would not be possible to add new members. The most straightforward way is to use the creator of the organization.
- #3171 
- #3174 
This PR:

H-788: Make the organization creator an admin of the account group

---

apps/hash-graph/bench/read_scaling/knowledge/complete/entity.rs
apps/hash-graph/bench/read_scaling/knowledge/linkless/entity.rs
apps/hash-graph/bench/representative_read/knowledge/entity.rs
apps/hash-graph/bench/representative_read/seed.rs
apps/hash-graph/bench/util.rs
apps/hash-graph/lib/graph-types/src/account.rs
apps/hash-graph/lib/graph-types/src/knowledge/entity.rs
apps/hash-graph/lib/graph-types/src/provenance.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/ontology_id.rs
apps/hash-graph/lib/graph/src/store/postgres/traversal_context.rs
apps/hash-graph/lib/graph/src/store/query/filter.rs
apps/hash-graph/tests/integration/postgres/lib.rs

The UUID wrapper only returns a copy of the inner value. This way it's not possible to use it in a generic context. Generally, `as_*` should be used to return a reference, not a copy. For that, either `to_*` (ref -> copy) or `into_*` (value -> value) are supposed to be used.
This PR renames `as_uuid` to `into_uuid` and adds a proper `as_uuid` method.
- #3171 
- #3174 
- #3176 
This PR:

H-789: Rename `as_uuid` and provide a reference getter

---

apps/hash-graph/lib/authorization/src/backend.rs
apps/hash-graph/lib/authorization/src/backend/spicedb/api.rs
apps/hash-graph/lib/authorization/src/backend/spicedb/model.rs
apps/hash-graph/lib/authorization/src/zanzibar/types.rs
apps/hash-graph/lib/authorization/tests/api.rs
apps/hash-graph/lib/authorization/tests/schema.rs
apps/hash-graph/lib/authorization/tests/simple.rs

SpiceDB allows to set preconditions or deletions by filter. We don't use them currently (and don't plan to use them in the near future) and this overcomplicates the current API by a fair bit. It's easier to just defer it  until we need it.
This allows making the Tuple trait more generic, which greatly simplifies the API to speed up development in #3179.
- Removes preconditions and filter-by deletions (both are unused)
- Stop using `Resource` trait as associated type in `Tuple`. This has the major advantage that it's now finally possible to specify typed tuples without a userset-field, which was not possible before.
- #3171 
- #3174 
- #3176 
- #3177
This PR:

H-795: Remove filter from permission queries

---

apps/hash-api/src/graph/knowledge/system-types/hash-instance.ts
apps/hash-api/src/graph/knowledge/system-types/linear-integration-entity.ts
apps/hash-api/src/graph/knowledge/system-types/linear-user-secret.ts
apps/hash-api/src/graph/knowledge/system-types/org.ts
apps/hash-api/src/graph/knowledge/system-types/page.ts
apps/hash-api/src/graph/knowledge/system-types/user.ts
apps/hash-api/src/graph/system-user.ts
apps/hash-frontend/src/pages/[shortname]/[page-slug].page.tsx
apps/hash-frontend/src/shared/use-user-or-org.ts
apps/hash-integration-worker/src/activities.ts
libs/@local/hash-isomorphic-utils/src/graph-queries.ts

Where we query for entities and match against the type of the entity or of some other entity linked to them, the queries can currently be slow, mainly because of type inheritance.
This PR introduces a `generateVersionedUrlMatchingFilter` function that can create a filter with two ways of improving query performance:
1. Skip checking type parents (major improvement)
2. Split the type id we're matching on to instead match by its components `baseUrl` and `version`, which are top-level database fields, rather than the id which is a property nested in the type's jsonb schema. This has no discernible impact currently but may be better with more data (it may not if a query using indices on `baseUrl` and `version` perform the same as one using a GIN index on `schema -> $id`, and the number of …

H-802: Skip checking type parents when looking up system entities by type

---

apps/hash-graph/lib/type-fetcher/src/fetcher_server.rs

To avoid doing [H-670](https://linear.app/hash/issue/H-670/make-the-type-fetcher-a-temporalio-worker) right now, we should try to make the type fetcher more robust to external services being unresponsive (e.g. because bp.org is currently redeploying)
This PR:

H-671: Add a timeout for the type fetcher

---

.github/renovate.json

By default, `ignorePaths` is set to
```json
[
"/node_modules/",
"/bower_components/"
]
```
however, for some reason, it's set to 
```json
[
"**/node_modules/**",
"**/bower_components/**",
"**/vendor/**",
"**/examples/**",
"**/__tests__/**",
"**/test/**",
"**/tests/**",
"**/__fixtures__/**"
]
```
resulting in `tests/` not being updated.
To reproduce the error I used `renovate` locally:
```
LOG_LEVEL=debug renovate --dry-run=true --token $MY_GH_TOKEN --ignore-paths '["**/node_modules/**", "**/target/**", "**/dist/**"]' hashintel/hash
```
- https://docs.renovatebot.com/configuration-options/#ignorepaths
This PR:

H-834: Fix `ignorePaths` setting in Renovate

---

.github/scripts/rust/setup.py

The only real reason to run Rust CI when `.github` change is when the actual workflow changes.
This PR:

H-835: Don't run Rust CI if something else than workflows changed in `.github/`

---

apps/hash-graph/lib/authorization/schemas/v1__initial_schema.zed
apps/hash-graph/lib/authorization/src/api.rs
apps/hash-graph/lib/authorization/src/backend.rs
apps/hash-graph/lib/authorization/src/backend/spicedb/api.rs
apps/hash-graph/lib/authorization/src/backend/spicedb/model.rs
apps/hash-graph/lib/authorization/src/lib.rs
apps/hash-graph/lib/authorization/src/schema.rs
apps/hash-graph/lib/authorization/src/schema/web.rs
apps/hash-graph/lib/authorization/src/zanzibar/api.rs
apps/hash-graph/lib/authorization/tests/api.rs
apps/hash-graph/lib/authorization/tests/simple.rs
apps/hash-graph/lib/graph-types/src/lib.rs
apps/hash-graph/lib/graph-types/src/provenance.rs
apps/hash-graph/lib/graph-types/src/web.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs

With #3179 an initial SpiceDB schema is created. The `AuthorizationApi` has to be adjusted to use the new permissions and the correct functions has to be called everywhere.
This does not enable the permissions in `dev` yet. BE tests don't cover the tests, yet, as snapshots has not been adjusted and I hesitate to enable permissions in `dev` until they are somewhat tested at least.
- #3171 
- #3174 
- #3176 
- #3177
- #3189 
- #3179 
This PR:

H-804: Use SpiceDB schema in the Graph to check/alter permissions

---

apps/hash-api/src/graph/knowledge/system-types/org.ts
apps/hash-api/src/graph/knowledge/system-types/user.ts
apps/hash-api/src/graph/ontology/primitive/util.ts
apps/hash-api/src/graph/system-types.ts
apps/hash-api/src/seed-data/index.ts
apps/hash-api/src/seed-data/seed-pages.ts
apps/hash-api/src/seed-data/seed-users.ts
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs

With permissions enabled, it would be required that the system user (the current owner of users and orgs) has the same access to the users and orgs as the users and orgs themself. Instead, users and orgs should own themself, which reduces the dependency on the system user as well.
Either this approach needs to be done or the authorization logic has to be expanded to allow permission granting on the users/orgs.
- #3176 
- #3177
- #3189 
- #3179 
- #3190
This PR:

H-809: Change users and orgs to own themselves

---

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/file-preview-section.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/shared/get-image-url-from-properties.ts
apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page/definition-tab.tsx
libs/@hashintel/type-editor/src/entity-type-editor/link-list-card.tsx
libs/@hashintel/type-editor/src/entity-type-editor/property-list-card/property-title-cell.tsx

A few small fixes:
1. H-580: Stop the link/property titles wrapping in the type editor, i.e. stop this
2. Fix a crash when viewing the entity editor for non-file entities (introduced in #3216)
3. Adjust tooltip placement on file preview to stop tooltips covering the adjacent button
4. Reset entity type editor state when switching types (fixes a crash I noticed while testing the above)
This PR:
- I noticed another crash in the type editor tracked in H-846
- None
1. For wrapping, you need to create a type which has a non-latest property or link type
2. Visit entity editor for non-file entity to confirm no crash
3. Check tooltip placement on file preview

H-580: Fix styling in link/property table, fix crash in entity editor

---

apps/hash-graph/Cargo.lock
apps/hash-graph/Cargo.toml
apps/hash-graph/bin/cli/Cargo.toml
apps/hash-graph/bin/cli/src/subcommand/snapshot.rs
apps/hash-graph/lib/codec/Cargo.toml
apps/hash-graph/lib/codec/src/bytes.rs
apps/hash-graph/lib/codec/src/lib.rs
apps/hash-graph/lib/graph/Cargo.toml
apps/hash-graph/lib/graph/src/api/rest/test_server.rs
apps/hash-graph/lib/graph/src/snapshot.rs

The `JsonLineDecoderis` is required in multiple locations in the repository. It should be moved to a separate crate.
In the future, I expect more codecs to be implemented here, such as how (de-)serialization is implemented (e.g. the current temporal_versioning::serde module).
This PR:

H-849: Make `codec` module a crate

---

libs/error-stack/Cargo.toml
libs/error-stack/src/lib.rs

Fix #3209
As a ever-re-returning user that wants to start a new project
using error-stack, I open http://docs.rs/error-stack and get
lots of words explaining some details, and not a single basic
example that would get me going.
This PR adds the simple example code that I'm looking always
looking for.
`cargo test --doc` :)

GEN-108: Add a simple example for new error-stack users starting new project

---

.github/workflows/package.yml
turbo.json

GEN-99 added a new CI approach. That CI changed `turbo.json` which implies that all CI jobs are running anyway so wrongly used `[HEAD^]` filters were not noticed. This PR (hopefully) fixes the issues.
This PR:

GEN-109, GEN-110: Fix CI jobs not determined correctly

---

.github/workflows/package.yml

Jobs are not filtered, this hotfixes that.

GEN-110: Fix CI running too many jobs

---

apps/hash-api/src/graph/knowledge/system-types/hash-instance.ts
apps/hash-api/src/graph/knowledge/system-types/org.ts
apps/hash-api/src/graph/knowledge/system-types/user.ts
apps/hash-api/src/seed-data/seed-users.ts
tests/hash-backend-integration/src/tests/graph/knowledge/primitive/entity.test.ts
tests/hash-backend-integration/src/tests/graph/knowledge/system-types/hash-instance.test.ts
tests/hash-backend-integration/src/tests/graph/knowledge/system-types/org-membership.test.ts
tests/hash-backend-integration/src/tests/graph/knowledge/system-types/org.test.ts
tests/hash-backend-integration/src/tests/graph/knowledge/system-types/user.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/data-type.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/entity-type.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/property-type.test.ts
tests/hash-backend-integration/src/tests/util.ts

With basic entity authorization implemented it's time to adjust a few Node API functions to properly fill the permissions. This includes making users, orgs, and the HASH-instance public and tweak various locations to use more correct actor ids.
This does not enable permissions in `dev` or `prod` by default but with permissions enabled most BE integration tests are passing. The missing parts are the subgraph tests (the snapshots do not know yet about permissions, will be done in H-669) and the instance admin tests (will be done as part of H-817).
- #3179 
- #3190
- #3200
- #3204 
- #3210 
This PR:

H-827: Adjust Node API to use authentication for several cases

---

apps/hash-graph/lib/graph/src/api/rest.rs
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/openapi/openapi.json
libs/@local/hash-graph-client/python/graph_client/models.py

To check if a user will be able to update an entity, a function is required to be exposed for that. The first thing where this is used is to determine if the user can edit the instance settings.
- #3200
- #3204 
- #3210 
- #3211 
This PR:

H-838: Expose function to check if a user can update an entity

---

apps/hash-graph/lib/authorization/src/backend.rs
apps/hash-graph/lib/authorization/src/backend/spicedb/api.rs
apps/hash-graph/lib/authorization/src/backend/spicedb/model.rs
apps/hash-graph/lib/authorization/tests/api.rs

Snapshots do not now previous entries, thus, it's not possible to check if a relation already existed in the database. This adds a method to create relations without erroring on duplicates.
- #3210 
- #3211 
- #3223
- ~#3224~
- ~#3243~
This PR:

H-653: Support creation and deletion of relations without erroring on conflicts

---

apps/hash-ai-worker-py/app/infer/entities/__init__.py

`gpt-4-0612` has an 8k (not 4k) context window.
This changes `max_tokens` in the `hash-ai-worker-py`'s entity inference workflow.
Ideally we'd define the `max_tokens` accepted for each model statically elsewhere (likely alongside pricing information in the internal API) so we don't have to update this in multiple places.
It would still be useful to maintain `max_tokens` inline here separately here, allowing for capping of overall input sizes.

H-886: Bump `max_tokens` for `gpt-4-0613` model

---

apps/hash-ai-worker-py/app/infer/entities/__init__.py

Reverts hashintel/hash#3291
I'll figure out another way to solve this, but for now it's more important that entity inference is working.
The PR actually broke entity inference with the following status as an example returned:
```json
[
{
"code": "UNKNOWN",
"contents": [],
"message": "Unable to infer entities: This model's maximum context length is 8192 tokens. However, you requested 8777 tokens (478 in the messages, 107 in the functions, and 8192 in the completion). Please reduce the length of the messages, functions, or completion."
}
]
```

H-886: Revert "H-886: Bump `max_tokens` for `gpt-4-0613` model"

---

apps/hash-ai-worker-py/app/encoding.py
apps/hash-ai-worker-py/app/infer/entities/__init__.py

We currently pass a maximum completion token number of 4096 by default. This changes the default behavior that does not pass any explicit limit to the AI. The model will use it's internal limit and an sensible error will be returned if this is reached. An example status when the maximum token count is reached:
```json
[
{
"code": "INVALID_ARGUMENT",
"contents": [],
"message": "The maximum amount of tokens was reached."
}
]
```
This PR:

H-886: Don't restrict token count by default

---

.github/workflows/package.yml
apps/hash-graph/bench/representative_read/seed.rs
apps/hash-graph/bench/util.rs
apps/hash-graph/lib/authorization/tests/api.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/rust-toolchain.toml
libs/@local/status/rust/rust-toolchain.toml
libs/antsi/rust-toolchain.toml
libs/deer/rust-toolchain.toml
libs/deer/src/error/type.rs
libs/error-stack/README.md
libs/error-stack/macros/README.md
libs/error-stack/rust-toolchain.toml
libs/error-stack/src/hook.rs
libs/error-stack/src/lib.rs
libs/sarif/rust-toolchain.toml

The CI does not run all clippy lints. This is bad.
For some reason, `[target.cfg(all())]` is not used in CI so as a workaround, the content is exported to `RUSTFLAGS`. To make sure everything is still well tested, the toolchain for all crates were bumped and errors are solved.
This PR:

GEN-72: Fix clippy not working in CI

---

apps/hashdotdev/src/pages/roadmap/technology-tree-data.tsx

Adds the HASH Browser Extension to tech tree.
Check the absolute bottom row of the hash.dev/roadmap tech tree.

H-900: Add HASH Browser Extension to tech tree

---

libs/antsi/README.md
libs/deer/README.md
libs/deer/json/README.md
libs/deer/macros/README.md
libs/error-stack/src/report.rs
libs/sarif/README.md

Many README files contain a link to file an issue. The link is hard-coded and outdated as the template may change over time. This changes the link to the [`/choose` page](https://github.com/hashintel/hash/issues/new/choose). This is not as precise as before but always up-to-date and it's better to show all options in any case.
This PR:

H-893: Update issue creation links to the `/choose` page

---

apps/hash-ai-worker-py/app/infer/entities/__init__.py
apps/hash-ai-worker-py/app/infer/entities/workflow.py
apps/hash-api/src/graphql/resolvers/knowledge/entity/entity.ts
libs/@local/hash-graphql-shared/src/graphql/type-defs/knowledge/entity.typedef.ts

The GraphQL endpoints currently do not return the entity id and has a wrong `LinkData` associated (it's not possible to infer the correct entity ID from AI).
With this PR the GraphQL endpoint has all capabilities to infer entities as required for H-57.
Synchronize the parameters/results of GraphQL and the Python worker
This PR:

H-57, H-894: Adjust GraphQL endpoints to support links and more configuration parameters

---

apps/hash-ai-worker-py/app/infer/entities/activity.py

When no entities were inferred but multiple entity type ids are provided the ids may be assigned wrongly
This PR:

H-917: Fix wrongly inferred entity type id if another type was not inferred

---

apps/hash-ai-worker-py/app/_status.py
apps/hash-ai-worker-py/app/infer/entities/activity.py

The Python worker calls the TS worker which has more status codes defined. If the TS worker is emitting a statuscode unknown to Python it will crash the workflow.
The descriptions are copied from the TS definition and brought in to Python shape.
This PR:

H-922: Allow more status codes to be returned in Python

---

infra/terraform/hash/main.tf

Adds an environment variable to the Terraform config to specify the S3 bucket for file uploads.
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1696430133479179) (internal)
This PR:

Add S3 upload bucket environment variable

---

.github/actions/terraform-exec/action.yml
infra/terraform/hash/prod-usea1.tfvars

Another variable required following #3327 to enable s3 object storage.
This PR:

H-941: Set FILE_UPLOAD_PROVIDER in prod hash config

---

infra/terraform/hash/hash_application/api.tf
infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/main.tf

Adds Terraform configuration for creating an S3 bucket for user file uploads, and assign read/write access to the task role.
Supersedes #3327.
This PR:
1. Check file uploads work in the remote deployment
1. For now, we can only check Terraform plan

H-936: Add file upload S3 bucket to Terraform config

---

.github/workflows/hash-backend-cd.yml
.github/workflows/release.yml
.github/workflows/tf-apply-hash.yml

Notifies Slack when a GitHub action which is triggered by a merge to `main` fails.
This PR:
1. Can only be done after merging... I intend to retrigger [Terraform apply](https://github.com/hashintel/hash/actions/workflows/tf-apply-hash.yml) which is currently failing.

H-944: Send Slack notifications when GitHub actions fail

---

.github/workflows/hash-backend-cd.yml
.github/workflows/tf-apply-hash.yml

The Slack notification job introduced in #3339 is [failing](https://github.com/hashintel/hash/actions/runs/6423979071/job/17443644852) because the [action](https://github.com/rtCamp/action-slack-notify) we are using supports storing the webhook URL in Vault, by setting `VAULT_ADDR` and `VAULT_TOKEN` environment variables. Because we use these environment variables for other things in some jobs it assumes the webhook URL can be found there, when it can't.
This PR overwrites those variables for the Slack job. I'm not sure how secret inheritance/overwriting works in GitHub actions so this might not work. If it doesn't we can always add the webhook URL to vault, but that would also mean adding the Vault environment variables to jobs that don't currently need them, just for the webhook URL.

H-945: Set vault variables to blank for Slack notification job

---

infra/terraform/hash/hash_application/api.tf

Terraform is [failing](https://github.com/hashintel/hash/actions/runs/6420331103/job/17432187349#step:14:910) to create the S3 bucket introduced in #3336. It's possible that it's because it's missing the settings added in this PR.
If not, it may be the permissions of the user GitHub is acting as, which I will investigate if this doesn't work.
This PR:

H-941: Add more S3 bucket config

---

libs/error-stack/src/hook.rs
libs/error-stack/tests/snapshots/doc/hook__location_hook.snap

The feature to disable the location is available since `0.2.4` but it was not properly documented.
- #3353
- #1215
This PR:

GEN-114: Add example to disable location printing

---

.github/workflows/hash-backend-cd.yml
.github/workflows/release.yml
.github/workflows/tf-apply-hash.yml

Adds `@mention`ing of people in Slack when a GitHub action failures to make it more likely the warning is picked up.
This PR:
1. On merge to `main` the Terraform apply should fail (unrelated issue I am working on), and we will see if this works.

H-946: `@mention` people in Slack on github action failure

---

apps/hash-api/src/graph/knowledge/primitive/entity.ts
apps/hash-api/src/graph/knowledge/system-types/user.ts
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/openapi/openapi.json

The node API should have an easy way to tell if an entity can be viewed/is public.
- #3337
- Expose `canViewEntity` from Rust to Node
- Add `isEntityPublic` to Node API by checking if the public user can read an entity
This PR:

H-985: Allow checking if an entity is public

---

apps/hash-api/src/graph/knowledge/system-types/file.ts
apps/hash-api/src/graphql/resolvers/knowledge/file/request-file-upload.ts
apps/hash-api/src/lib/aws-config.ts
apps/hash-api/src/storage/aws-s3-storage-provider.ts
apps/hash-api/src/storage/local-file-storage.ts
apps/hash-api/src/storage/storage-provider.ts
apps/hash-frontend/src/components/hooks/block-protocol-functions/knowledge/use-block-protocol-file-upload.ts
apps/hash-frontend/src/graphql/queries/knowledge/file.queries.ts
apps/hash-frontend/src/shared/file-upload-context.tsx
apps/hash-frontend/src/shared/upload-to-storage-provider.ts
infra/terraform/hash/hash_application/api.tf
infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/main.tf
libs/@local/hash-graphql-shared/src/graphql/type-defs/knowledge/file.typedef.ts
tests/hash-backend-integration/src/tests/graph/knowledge/system-types/file.test.ts

Changes where we store files from S3 to R2.
- Adds environment variables for connecting to R2 (we were previously relying on the AWS IAM role for the API task having authorization)
- Update the file upload request from a presigned POST (not supported in R2) to a PUT
- Validate that the content type and length are as originally requested (this currently simply ensures that the type/length requested by the user for upload, which could be anything, are the same as what they actually upload, but at some point we could reject requests for upload with certain types/sizes, if we wanted)
- Remove Terraform config for S3 bucket
This PR:
We probably want to change how we proxy file downloads to address the following: 
1. Currently, if the storage …

H-697: Migrate from S3 to Cloudflare R2 for file object storage

---

.env
apps/hash-api/src/index.ts
apps/hash-api/src/integrations/sync-back-watcher.ts
apps/hash-realtime/src/index.ts
libs/@local/hash-backend-utils/src/environment.ts

The `realtime` service reads database changes from a replica slot and adds them to a Redis queue, which can be subscribed to by other services which need to react to changes in the database. Previously, this included the collaborative editing ("collab") service, but currently it is only the service which syncs data changes in HASH back to external integrations.
With the introduction of authorization we need to figure out the permissions for this service. Until we do so, and until we return to developing external integrations, this PR disables `realtime` and the integration syncing function by default (it can be enabled by environment variable).
This PR:

H-1028: Disable realtime service by default

---

.github/actions/load-docker-images/action.yml
.github/workflows/package.yml
apps/hash-api/src/graph/knowledge/primitive/entity.ts
apps/hash-graph/Cargo.lock
apps/hash-graph/docker/Dockerfile
apps/hash-graph/lib/graph/Cargo.toml
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/lib/graph/src/snapshot.rs
apps/hash-graph/lib/graph/src/snapshot/entity/channel.rs
apps/hash-graph/lib/graph/src/snapshot/entity/record.rs
apps/hash-graph/lib/graph/src/store/account.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/friendship.http
libs/@local/hash-authorization/Cargo.toml
libs/@local/hash-authorization/src/api.rs
libs/@local/hash-authorization/src/lib.rs
libs/@local/hash-authorization/src/schema/entity.rs
libs/@local/hash-authorization/src/zanzibar/api.rs
libs/@local/hash-authorization/tests/simple.rs
libs/@local/hash-graph-client/python/graph_client/models.py
libs/@local/hash-subgraph/src/types/shared/branded.ts

Provides an interface to read all users and relations for the requested entity.
This PR:
This is not how I want to implement reading relationships in the first place. This approach is very inflexible and lengthy. In addition, this will not work when introducing more features such as attribute-based permissions (caveats) which are required for more fine-grained permissions. Also, this approach does not scale well and is rather slow. However, the functionality is required for the share menu, so I decided to provide a function that is working.
The approach I wanted to use did not work out fully but can be extended. It's available in [this branch](https://github.com/hashintel/hash/tree/t/h-980-return-all-users-relations-for-a-given-entity-experim …

H-980: Return all users and relations for a given entity

---

libs/README.md

To easier see what libraries exist this starts a section on unpublished libraries in the `libs/` folder. I purposefully did that in `libs/` not in `libs/@local` so every library going to be listed in a single file which makes searching for a specific library easier.

H-913: Add non-exhaustive outline of unpublished libraries

---

apps/hash-api/src/graph/knowledge/primitive/entity.ts
apps/hash-api/src/graph/knowledge/primitive/link-entity.ts
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/lib/graph/src/snapshot.rs
apps/hash-graph/lib/graph/src/snapshot/web/channel.rs
apps/hash-graph/lib/graph/src/store.rs
apps/hash-graph/lib/graph/src/store/account.rs
apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/knowledge.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/circular-links.http
apps/hash-graph/tests/friendship.http
apps/hash-integration-worker/src/activities.ts
libs/@local/hash-authorization/src/api.rs
libs/@local/hash-authorization/src/schema/web.rs
libs/@local/hash-authorization/src/zanzibar/api.rs
libs/@local/hash-graph-client/python/graph_client/models.py
tests/hash-graph-integration/postgres/lib.rs

For thinks like comments it's desired that the `ownedById` is not the same as the owner (we're going to rename `ownedById` at some later point).
- H-1064
This PR:

H-1064: Allow specifying the owner of an entity on creation

---

apps/hash-graph/lib/graph/src/api/rest/account.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/friendship.http

we need it to determine whether a user can add/remove org members
- H-1068
- #3394 
This PR:

H-1068: Expose checking 'can user edit account group members' via Graph API

---

infra/terraform/hash/main.tf
libs/@local/hash-authorization/src/backend/spicedb/api.rs

While testing if authorization works in prod I noticed a minor issue with an environment variable. To have a better error output I attached the URL on error.
- H-1072
This PR:

H-1072: Fix environment variable for authorization

---

apps/hash-graph/Cargo.lock
libs/@local/hash-authorization/Cargo.toml
libs/@local/hash-authorization/src/backend/spicedb/api.rs
libs/@local/hash-authorization/src/backend/spicedb/model.rs

With too many write operations at the same time a data race may happen. To avoid this, this adds a very primitive retry solution which attempts to retry the request three times.
This PR:

H-1070: Fix Graph API crash when attempting to remove entity owner

---

apps/hash-frontend/src/components/grid/grid.tsx
apps/hash-frontend/src/pages/shared/entities-table.tsx
apps/hash-frontend/src/pages/shared/entities-table/use-entities-table.tsx
apps/hash-frontend/src/pages/types/[[...type-kind]].page.tsx
apps/hash-frontend/src/pages/types/[[...type-kind]].page/types-table.tsx
apps/hash-frontend/src/shared/table-header.tsx

This PR adds a loading state to the `Grid` component, when the provided `rows` are set to `undefined`. This loading state is now displayed for the entities and types tables whilst the rows are loading (so on the `/entities`, `/pages` and `/types` pages).
- H-888
This PR:
None
Go to the `/entities` page in the deployment, and observe the loading state.
https://github.com/hashintel/hash/assets/42802102/d317e0ab-adf4-4d7d-9a41-045ab8d434c0

H-888: Implement loading skeleton when Glide table is loading

---

infra/terraform/hash/hash_application/main.tf

Using the same task definition name for two definitions causes conflicts
This PR:

H-1128: Rename task definition name for AI worker

---

apps/hash-graph/lib/graph/src/snapshot/entity/batch.rs
apps/hash-graph/lib/graph/src/snapshot/owner/batch.rs
apps/hash-graph/lib/graph/src/snapshot/web/batch.rs
libs/@local/hash-authorization/src/backend.rs
libs/@local/hash-authorization/src/backend/spicedb/api.rs
libs/@local/hash-authorization/src/backend/spicedb/model.rs
libs/@local/hash-authorization/src/zanzibar/api.rs
libs/@local/hash-authorization/tests/simple.rs

We currently define three convenient methods to modify a relationship. To avoid updating multiple places, this should be implemented on a trait level
- H-1121
- #3403 
This PR:

H-1121: Define modify-relationship-API on trait level

---

.github/workflows/test.yml
turbo.json

The CI is allowed to pass if a build step is failing as next steps will be skipped and skipped tests count as passed.

H-1136: Fix Test CI passing when a build-step fails

---

apps/hash-external-services/docker-compose.yml

The volume set for postgres data is erroneous, pointing to a directory that isn't used at all. This is a remnant of the old `docker-compose.yml`. The correct setting was previously set in `docker-compose.prod.yml`. 
This corrects the issue.
This PR:
Because we change where the volume points to (and the directory), your current database will most likely get wiped! To circumvent this you must first `pg_dump` in the container itself, before any rebuild happens.

H-1089: Fix Postgres data not have a dedicated volume

---

apps/hash-ai-worker-py/package.json
apps/hash-ai-worker-ts/package.json
apps/hash-graph/package.json
apps/hash-integration-worker/package.json

This adds `--load` to the `buildx` command to explicitly force `buildx` to load the image into docker. This is needed as there are multiple different "drivers" for building images: `docker`, `docker-container`, `kubernetes` and `remote`. Only `docker` supports automatically loading the image, but some setups use `docker-container` (like mine) instead, and need an explicit `--load` argument.
This fixes it by adding the argument.
Fun fact: you can see what your default driver is via: `docker buildx ls` (the `*` indicates the default)
- https://docs.docker.com/build/drivers/
This PR:

H-1147: Explicitly load images into Docker

---

apps/hash-graph/Cargo.lock
apps/hash-graph/bin/cli/src/error.rs
apps/hash-graph/bin/cli/src/main.rs

It seems that in a recent version the sentry-rust `Transport` has been changed, in a way where it is no longer possible to know if a connection was successful (or maybe I this never worked, who knows 🤷). After some more investigation, there doesn't seem to be an official way of verifying that the DSN is correct, so I have removed it for now.
- https://github.com/getsentry/sentry-python/issues/1033
This PR:
We no longer can verify if a DSN is correct, only that it is of a valid format.

H-1148: `hash-graph`: remove check if DSN is valid

---

apps/hash-frontend/src/lib/user-and-org.ts
apps/hash-frontend/src/shared/table-header.tsx
apps/hash-frontend/src/shared/use-user-or-org.ts

1. Fixes a check for 'is this an user or org'
2. Driveby: have a fallback for table headers to avoid 'undefined in your webs' table header
This PR:
1. Not entirely sure what brings the crash about as I haven't experienced it, so I can't confirm that the fix works – maybe @TimDiekmann can once it's deployed

H-1159: Fix check for isUserOrOrg

---

apps/hash-graph/lib/graph/src/api/rest/test_server.rs
libs/@local/hash-authorization/src/backend.rs
libs/@local/hash-authorization/src/backend/spicedb/api.rs
libs/@local/hash-authorization/src/schema.rs

For entities it didn't hurt if more relationships were stored than required (it was annoying though), for ontology types this will break the BE test suite.
- #3442
- #3443
- #3458
This PR:

H-1150: Allow bulk deletion of relationships

---

apps/hash-graph/lib/graph/src/api/rest/data_type.rs
apps/hash-graph/lib/graph/src/api/rest/entity_type.rs
apps/hash-graph/lib/graph/src/api/rest/property_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/tests/friendship.http
tests/hash-backend-integration/src/tests/graph/knowledge/primitive/entity.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/data-type.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/entity-type.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/property-type.test.ts

The relationships for ontology types were added in [H-1074](https://linear.app/hash/issue/H-1074/add-very-basic-data-type-permissions), [H-1075](https://linear.app/hash/issue/H-1075/add-very-basic-property-type-permissions), and [H-1076](https://linear.app/hash/issue/H-1076/add-very-basic-entity-type-permissions). The permission needs to be checked when updating the types.
- #3442
- #3443
- #3458
- #3463
- #3464 
- #3465
This PR:

H-1154: Check `update` permission for ontology types

---

apps/hash-graph/lib/graph/src/api/rest/account.rs
apps/hash-graph/openapi/openapi.json

The pass in the `utoipa` attribute was wrong so the Node API hard-coded the `add_owner` permission, which does not even exist.
This PR:

H-1185: Fix wrong permission passed to the Graph API

---

apps/hash-graph/Cargo.lock
apps/hash-graph/Cargo.toml
apps/hash-graph/bin/cli/Cargo.toml
apps/hash-graph/bin/cli/src/main.rs
apps/hash-graph/lib/graph/Cargo.toml
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/lib/graph/src/api/rest/status.rs
apps/hash-graph/lib/graph/src/store.rs
apps/hash-graph/lib/graph/src/store/pool.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/lib/graph/src/store/validation.rs
apps/hash-graph/package.json
libs/@local/hash-authorization/src/api.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/status/rust/src/lib.rs

#3505 added the `validation` crate. This PR is responsible to use that functionality in the Graph.
- #3505 
- Validate entities on create/update
- Drive-by: Improve errors returned from `create_entity` and `update-entity` endpoints.
This PR:

H-968, H-970: Adjust `hash-graph` to use entity validation

---

.github/workflows/test.yml

PW tests pass after we touch them but fail after a while. This typically is a caching issue so we disable caching and see if this will fix the issues.
This PR:

H-1200: Disable caching for Playwright tests

---

apps/hash-api/src/graph/knowledge/primitive/entity.ts
apps/hash-api/src/graph/ontology/primitive/data-type.ts
apps/hash-api/src/graph/ontology/primitive/entity-type.ts
apps/hash-api/src/graph/ontology/primitive/property-type.ts
apps/hash-graph/lib/graph/src/api/rest/data_type.rs
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/lib/graph/src/api/rest/entity_type.rs
apps/hash-graph/lib/graph/src/api/rest/property_type.rs
apps/hash-graph/openapi/openapi.json
libs/@local/hash-graph-client/python/graph_client/models.py
libs/@local/hash-subgraph/src/types/shared/branded.ts

To fully control ontology types this adds three endpoints for all ontology types:
- read relationships
- write relationships
- read permissions
This PR:

H-1179: Allow reading/writing ontology type relationships/permissions

---

apps/hash-graph/lib/graph/src/store/validation.rs
libs/@local/hash-graph-types/rust/src/knowledge/entity.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/lib.rs

To validate links it's required that entity types and entities can be seen from the validation. This adds the functionality to access these. Also, a function is added to detect if an entity type is inheriting from another type.
This PR:

H-1211: Support reading Entity and `EntityType` from validation

---

.env
.env.test
apps/hash-graph/bin/cli/src/subcommand/server.rs

Without the backslashes `\` escaped in the environment file the Graph fails to load all variables. This also drives-by a fix for the default value to exclude the old `link-type`
This PR:

H-1220: Fix environment variable for allowed domain pattern

---

apps/hash-api/src/graph/util.ts
apps/hash-api/src/index.ts
apps/hash-api/src/integrations/enabled-integrations.ts

We were creating the Linear system types conditional on a Linear client ID being present, but creating the Linear org unconditionally. We should only create it if the Linear integration is enabled.
A better approach would be either 
(a) to have one check for Linear being enabled, and create the types and org if so, or
(b) check which system types exist, and only create the orgs for the webs they belong to
but this will do for now – we can make it better when we introduce another integration.
- H-1226
This PR:

H-1126: Don't create Linear integration org if integration not enabled

---

infra/terraform/hash/main.tf

We removed the client ID and client secret variable to prevent seeding linear types until they are updated. To avoid breaking TF, this removes them from the environment as well.
This PR:

H-1227: Comment out unused vault variables

---

apps/hash-api/src/graph/account-permission-management.ts
apps/hash-api/src/graph/knowledge/system-types/hash-instance.ts
apps/hash-api/src/graph/knowledge/system-types/org.ts
apps/hash-api/src/graph/knowledge/system-types/user.ts
apps/hash-api/src/graph/ontology/primitive/util.ts
apps/hash-api/src/graph/util.ts
apps/hash-api/src/graphql/resolvers/knowledge/entity/entity.ts
apps/hash-external-services/docker-compose.test.yml
apps/hash-graph/bench/read_scaling/knowledge/complete/entity.rs
apps/hash-graph/bench/read_scaling/knowledge/linkless/entity.rs
apps/hash-graph/bench/representative_read/seed.rs
apps/hash-graph/lib/graph/src/api/rest/web.rs
apps/hash-graph/lib/graph/src/store/account.rs
apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/postgres.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/circular-links.http
apps/hash-graph/tests/friendship.http
libs/@local/hash-authorization/schemas/v1__initial_schema.zed
libs/@local/hash-authorization/src/api.rs
libs/@local/hash-authorization/src/lib.rs
libs/@local/hash-authorization/src/schema/web.rs
libs/@local/hash-authorization/src/zanzibar/api.rs
libs/@local/hash-graph-client/python/graph_client/models.py
libs/@local/hash-subgraph/src/types/shared/branded.ts
tests/hash-graph-integration/postgres/lib.rs

This changes the way a user is created. As a web is required to create the user entity, a web is created first, but the owner is set to the system account. After the registration is completed, the ownership is transferred to the user.
This PR:

H-1225: Fix user being created without web

---

apps/hash-frontend/src/components/block-loader/block-loader.tsx
blocks/code/package.json
blocks/code/src/app.tsx
blocks/code/src/types/generated/block-entity.ts
blocks/heading/variants.json
libs/@local/hash-isomorphic-utils/src/blocks.ts
libs/@local/hash-isomorphic-utils/src/prosemirror-manager.ts

Fixes a couple of bugs related to blocks:
1. Restore the ability to swap between blocks that accept a text property, and retain the text (H-60)
2. Handle blocks created mid-session properly (fetch their permissions and subgraph, don't rely on it being in the page subgraph)
3. Upgrade the code block's schema to use the new text property type
4. Fix variant properties in header level 4
This PR:
There are still several bugs to do with text editing:
1. Header levels do not set consistently (H-1276)
2. Swapping between header levels via the context menu does not work (H-1276)
3. The code block needs a blur to save, it should save periodically (H-1281)
4. Loading jank for blocks (H-1282)
1. Try swapping between blocks that have a `textual-content` …

H-60, H-1262: Retain text when swapping between blocks. Fix block permissions

---

apps/hash-frontend/src/components/hooks/use-entity-by-id.ts
apps/hash-frontend/src/pages/shared/block-collection/mention-view/mention-display.tsx

This PR fixes the property mention chip to not re-use cached results when navigating to the page without a hard refresh, and polling for the latest version of the entity every 5 seconds.
- H-1245
- adds an optional `pollInterval` parameter to the `useEntityById` hook
- sets `fetchPolicy: "cache-and-network"` for the `useQuery` method in `useEntityById`
This PR:
None
1. Run HASH locally or view the deployment
2. Create a property mention on a page
3. Update the value of the property in the underlying entity
4. Ensure the property mention is automatically updated after no longer than 5 seconds, or immediately when navigating away and back to the page via the sidebar
https://github.com/hashintel/hash/assets/42802102/366bbd64-d3e6-45f6-94f0-f0a98 …

H-1245: Ensure mention attribute chips automatically update when underlying data changes

---

apps/hash-frontend/src/pages/_app.page.tsx
apps/hash-frontend/src/pages/notes.page/create-quick-note.tsx
apps/hash-frontend/src/shared/command-bar.tsx
apps/hash-frontend/src/shared/command-bar/cheat-sheet.tsx
apps/hash-frontend/src/shared/command-bar/command-bar-options.ts
apps/hash-frontend/src/shared/keyboard-shortcuts-context.tsx
apps/hash-frontend/src/shared/layout/layout-with-header/search-bar/search-input.tsx

To handle keyboard actions involving multiple key presses we were using either `useKeys` from [rooks](https://github.com/imbhargav5/rooks) or an approach adapted from it, both of which rely on manually maintaining which keys have been held by the user. This approach is unreliable because it relies on the `keyup` handler being fired in order to wipe the key map.
A previous attempt to fix this in #2983 involving also wiping the key map on `blur` does not work for some OS-level actions, for example screen capture shortcuts on MacOS (`cmd` + `shift` + `5`).
This PR introduces an approach which relies solely on the `KeyboardEvent`, removing the need for maintaining a manual map. This does mean we cannot support some key combinations, as described in a comment in the diff, but in the absence of …

H-1034: Fix keyboard shortcuts firing when they shouldn't

---

apps/hash-graph/lib/graph/src/snapshot/owner/channel.rs

The relations are stored in the database but not the account group.
This PR:

H-1349: Fix snapshots not storing account groups when restoring

---

apps/hash-graph/bin/cli/src/args.rs
apps/hash-graph/bin/cli/src/main.rs
infra/terraform/hash/main.tf

Adds Sentry to the production instance.
This PR:
Set the `HASH_GRAPH_SENTRY_DSN` to the Graph DSN and `HASH_GRAPH_SENTRY_ENVIRONMENT` to `development` and run the Graph with an error (e.g. by not starting the Database service)

H-1338: Add Sentry to/enable in prod for the Graph

---

apps/hash-api/README.md
apps/hash-api/package.json
apps/hash-api/src/graphql/create-apollo-server.ts
apps/hash-api/src/index.ts
apps/hash-api/src/sentry.ts
apps/hash-frontend/sentry.client.config.ts
apps/hash-frontend/sentry.edge.config.ts
apps/hash-frontend/sentry.server.config.ts
apps/hash-frontend/src/components/hooks/use-snackbar.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor-page.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/select-entity-type-page.tsx
apps/hash-frontend/src/pages/_app.page/error-fallback.tsx
apps/hash-frontend/src/pages/shared/block-collection/block-collection.tsx
apps/hash-frontend/src/pages/shared/block-collection/create-editor-view.ts
infra/terraform/hash/main.tf
libs/@local/hash-isomorphic-utils/src/create-apollo-client.ts
yarn.lock

A few things to help in error capturing and in giving more information about errors to users:
- H-1131: Stop errors being sent to Sentry from the frontend where they relate to a user not being logged in – this is juust spam
- H-1333: Show a snackbar when page contents are not being saved for whatever reason (see demo) – this uses an existing snackbar implementation which we can add custom styling to in a later task (designs [here](https://www.figma.com/file/gydVGka9FjNEg9E2STwhi2/HASH?type=design&node-id=552%3A30695&mode=design&t=v3gy5C2e2Z17yCCu-1))
- H-1335: Add Sentry to the Node API
- H-1348: Include the stack trace information in the ErrorFallback component
This PR:
Get the appropriate DSNs for the projects from Sentry.
1. H-1131: Add a …

H-1131, H-1333, H-1335, H-1348: Add Sentry to Node API, improve error handling in frontend

---

apps/hash-graph/bin/cli/src/args.rs
apps/hash-graph/bin/cli/src/main.rs

To avoid passing no sentry environment a default environment is provided.
This PR:

H-1350: Set a default variable for the sentry environment in `graph`

---

apps/hash-api/src/graph/knowledge/primitive/entity.ts
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/lib/graph/src/store.rs
apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/knowledge.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/friendship.http
libs/@local/hash-graph-client/python/graph_client/models.py
libs/@local/hash-validation/src/property_type.rs

To allow the frontend and entity inference to validate entities using the Graph, the functionality has to be exposed.
- Adds a new `EntityStore` method `validate_entity` which is used by the `create_entity` and `update_entity` methods. The function will read the closed schema from the Graph if required (but does not invoke the type fetcher)
- Expose the above function to the REST API
- Add a small wrapper function in the Node API
This PR:
- Three example invocations are added to the HTTP tests

H-994: Expose entity validation to the Node API

---

apps/hash-frontend/src/blocks/use-fetch-block-subgraph.ts
apps/hash-frontend/src/components/block-loader/block-loader.tsx
apps/hash-frontend/src/pages/shared/block-collection/block-context-menu/block-context-menu-item.tsx
apps/hash-frontend/src/pages/shared/block-collection/block-context-menu/block-context-menu.tsx
apps/hash-frontend/src/pages/shared/block-collection/block-context-menu/block-list-menu-content.tsx
apps/hash-frontend/src/pages/shared/block-collection/component-view.tsx
libs/@local/hash-isomorphic-utils/src/entity-store-plugin.ts
libs/@local/hash-isomorphic-utils/src/entity-store.ts

Fixes a few bugs related to setting variants of blocks. The visible effect of this is that when inserting a header of a specific level, or swapping between headers of specific levels, they will appear at the correct size (rather than defaulting to H1).
The key underlying issue is that when creating a new block with specific properties, or updating the properties on an existing entity via the context menu, what is actually happening is that the ProseMirror code is updating a local entity store which only it uses, which is periodically persisted to the API. The changes in this PR are to ensure that properties set in this way are used in the block loading code, which was previously relying on data from the API. We'd be better off having a single entity store which manages interaction with …

H-1276: Fix swapping between block variants, header levels

---

apps/hash-frontend/src/pages/shared/entity-type-page.tsx

In the remote deployment, types are given a `https//hash.ai` origin for their ids, but are hosted on `https://app.hash.ai`, in anticipation of the frontend being moved to `https://hash.ai`. This involves a number of temporary workarounds when users click on links with `https://hash.ai` URLs to actually treat them as internal – introduced in #3485.
One place where a workaround is required was missed – where users are sent to after submitting the type form. This means after submission users were sent to `https://hash.ai`, and redirected back to the same page, resulting in a full refresh (and the time taken to process the redirect). This PR fixes that.
This PR:
1. Only possible in production, since the workaround depends on the frontend running …

H-1384: Stop full-page refresh after submitting the entity type form

---

apps/hash-api/src/graph/knowledge/primitive/entity.ts
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/openapi/openapi.json

Then OpenAPI client generator uses the wrong type (The serialization of `Set` does not result in an array, so `Set` is wrong in this situation).
This PR:

H-1441: Fix Graph API client types for `validateEntity`

---

apps/hash-graph/lib/graph/src/snapshot/entity/batch.rs
apps/hash-graph/lib/graph/src/store.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/lib/graph/src/store/validation.rs

While trying to insert a snapshot from <insert place here>, I found that the restore times were not tolerable. One of the problems encountered seems to be the repeated fetching of the same types thousands of times, leading to massive slowdowns (we're talking about down to multiple hours).
This tries to remedy it by only querying SpiceDB and Postgres once and saving the result in an intermediate cache.
@TimDiekmann, any guidance on how to best write a test case for this?
- Naive caching strategy for types (not entities).
This PR:

H-1443: Implement caching when validating entities in snapshots

---

apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/knowledge.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs

The error message on `validate_entity` is confusing
This PR:

H-1459: Use different error for `validate_entity`

---

apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
libs/@local/hash-authorization/src/backend/spicedb/api.rs

SpiceDB is configured to fail if more than 1000 relationships are being updated. This is a sensible default and we should chunk the requests instead.
This PR:

H-1457: Fix SpiceDB failing when inserting more than 1000 relationships

---

infra/terraform/hash/hash_application/main.tf

With the removal of the AI Python worker (#3644), there are no secrets among the `worker_task_defs`. 
This PR removes a redundant rule allowing the ECS Task Execution role to get secrets from SSM that don't exist.

Remove unused policy rule from hash terraform

---

apps/hash-ai-worker-ts/src/activities/infer-entities/create-entities.ts
apps/hash-api/src/graph/knowledge/primitive/entity.ts
apps/hash-api/src/graph/knowledge/primitive/link-entity.ts
apps/hash-frontend/src/blocks/use-fetch-block-subgraph.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/cells/linked-with-cell/linked-entity-list-editor.tsx
apps/hash-frontend/src/pages/shared/block-collection/component-view.tsx
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/lib/graph/src/store/knowledge.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/circular-links.http
apps/hash-graph/tests/friendship.http
apps/hash-integration-worker/src/activities.ts
apps/hash-integration-worker/src/activities/graph-requests.ts
libs/@local/hash-graph-types/rust/src/knowledge/entity.rs
libs/@local/hash-graph-types/rust/src/knowledge/link.rs
libs/@local/hash-isomorphic-utils/src/entity-store-plugin.ts
libs/@local/hash-isomorphic-utils/src/entity-store.ts
libs/@local/hash-subgraph/src/types/element/knowledge.ts
libs/@local/hash-subgraph/tests/compatibility.test/map-vertices.ts

Even though drafts are not fully implemented, yet, this exposes the functionality to the node API. Exposing it implies it's that it's available as OpenAPI so it's far easier to test functionality via plain http requests.
- #3640 
- Expose the `draft` field on `EntityMetadata` and on create/update requests
- Return an error if a draft is about to be created via the Node API
This PR:
- The functionality which is exposed does not work yet and will always error with a permission-denied error.
- In the Node API there is already a struct `DraftEntity`, which we probably want to rename.

H-1453: Expose draft entity interface to the Node API

---

apps/hash-graph/lib/graph/src/snapshot.rs
apps/hash-graph/lib/graph/src/snapshot/entity/channel.rs
apps/hash-graph/lib/graph/src/snapshot/entity/record.rs

Adjusts the subgraph logic to also dump/restore drafts. If an entity is not a draft, that field will be omitted.
- #3640 
This PR:

H-1454: Adjust snapshots to support draft entities

---

apps/hash-ai-worker-ts/src/activities/infer-entities/create-entities.ts
apps/hash-api/src/graph/knowledge/primitive/entity.ts
apps/hash-graph/lib/graph/src/api/rest/entity.rs
apps/hash-graph/lib/graph/src/snapshot/entity/batch.rs
apps/hash-graph/lib/graph/src/store/fetcher.rs
apps/hash-graph/lib/graph/src/store/knowledge.rs
apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/friendship.http
libs/@local/hash-validation/src/data_type.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/lib.rs
libs/@local/hash-validation/src/property_type.rs

When creating draft entities, the validation constraints should be lifted.
- #3640 
- #3646 
- Allow to pass either `ValidationProfile::Draft` or `ValidationProfile::Full` to any validation function
- Don't check for required properties if profile is `Draft`
- Don't check for min/max items on arrays if profile is `Draft`
- Add a `draft` parameter to the `validateEntity` endpoint
This PR:

H-1449: Relax constraints on entity validation for draft entities

---

libs/@local/hash-validation/src/entity_type.rs

If a link is not a draft it must not link to any draft entity.
- #3640 
- #3646 
- #3649
This PR:

H-1450: Restrict non-draft links to non-draft entities

---

apps/hash-api/src/graph/knowledge/system-types/org.ts
apps/hash-api/src/graph/knowledge/system-types/page.ts
apps/hash-frontend/src/components/block-loader/block-loader.tsx
apps/hash-frontend/src/components/hooks/shared/get-page-refetch-queries.ts
apps/hash-frontend/src/components/hooks/use-archive-page.ts
apps/hash-frontend/src/components/hooks/use-page-comments.ts
apps/hash-frontend/src/pages/[shortname].page/profile-bio.tsx
apps/hash-frontend/src/pages/[shortname]/[page-slug].page.tsx
apps/hash-frontend/src/pages/[shortname]/[page-slug].page/canvas-page/block-creation-dialog.tsx
apps/hash-frontend/src/pages/[shortname]/[page-slug].page/canvas-page/block-shape.tsx
apps/hash-frontend/src/pages/_app.page.tsx
apps/hash-frontend/src/pages/notes.page.tsx
apps/hash-frontend/src/pages/notes.page/timestamp-column.tsx
apps/hash-frontend/src/pages/shared/auth-info-context.tsx
apps/hash-frontend/src/pages/shared/block-collection-contents.ts
apps/hash-frontend/src/pages/shared/ory-kratos.ts

Makes some improvements to page loading times by:
- On page creation, don't bother creating an initial empty block in the API (the frontend code will handle it) – saves two sequential creations (H-1509)
- When loading blocks in a page, set the initial data from the page's subgraph on first render, not in an effect
- Don't bother converting the page's shortname into an `ownedById` before loading a page, we can identify the page without it – this speeds up the loading of `/@[shortname]/[page-uuid]` pages
- Don't fetch the Kratos session on the server prior to each page load – this speeds up all navigation, server or client-side
- Ignore parents when retrieving quick notes (checking type inheritance slows down the query) – speeds up quick notes loading
Also fixes a bug where the quick note …

H-1421, H-1474, H-1509: Page loading and quick notes improvements

---

apps/hash-frontend/src/shared/entity-types-context/hooks.ts
apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-entity-type-list.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-page-list/account-page-list.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/acount-entities-list.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/shared/loading-skeleton.tsx

It adds loading skeletons for the entities + type section in sidebar, although since the latter is collapsed by default it will only be visible if someone quickly expands it on page load.
This PR:
-
1. Reload the page
https://github.com/hashintel/hash/assets/37743469/f4529da8-da38-4a0e-a178-0bb6b2b5b296

H-1414: Add loading skeletons for the entities + type section in sidebar

---

apps/hash-frontend/src/pages/shared/entity-type-page.tsx

An entity type may have a link where the expected type linked to is itself.
E.g . a `Company` may be a `Subsidiary of` `Company`, or `Company` may have `Invested In` `Company`.
Previously, it was impossible to have the versions of `Company` involved consistent via the UI, because there was no way of setting a link destination to be 'the next version of this thing', and creating a new version of the type would increment its version, meaning the version of the link destination was one step behind.
This PR keeps them consistent automatically by amending the schema to make the version of any 'self' link destinations the same as the type's next version.
This PR:
1. Create a type which links to itself
2. Check that the version of the type and the …

H-1491: Version consistency for types which refer to themselves

---

apps/hash-frontend/src/blocks/user-blocks.tsx
apps/hash-frontend/src/pages/[shortname]/[page-slug].page/canvas-page.tsx
libs/@local/hash-isomorphic-utils/src/blocks.ts
libs/@local/hash-isomorphic-utils/src/prosemirror-manager.ts

This PR modifies the `useUserBlocks` method to fetch the latest version of the blocks reliably once per page-load, updating the block metadata stored in local storage if there's been any changes.
Previously to get the latest versions of the blocks users would've been forced to manually clear their local storage.
- H-1199
- adds the `bustCache` parameter to the `fetchBlock` call in `useUserBlocks`
This PR:
- When an updated version of the block has breaking changes, there is currently no mechanism for migrating previous versions of the block to the newer version.
Manual testing
If you haven't cleared local storage since the last block update, run the HASH App locally with these changes and the latest versions of the blocks should be loaded.

H-1199: fetch latest version of blocks once per page load

---

apps/hash-frontend/src/pages/shared/entity-type-page.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-entity-type-list.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/acount-entities-list.tsx
patches/@blockprotocol+type-system+0.1.1.patch

Fixes a bug introduced by #3683 where attempting to add a link to an entity type without constraining its destination would cause a crash. This crept in because the TS compiler for some reason doesn't flag that something which is `T | Record<string, never>` might be `Record<string, never>` and not `T`. I've patched the type locally to use `{}` instead.
As a drive-by I also noticed that the loading state in the sidebar introduced in #3677 would show when the data was refetching, which I've stopped.
This PR:

H-1548: Fix setting unconstrained links on an entity type

---

blocks/ai-text/src/app/generate-text/model-selector.tsx

This PR removes the ability to use `Davinci`, `Curie`, `Babbage` and `Ada` in the AI Text block, which are models that [will stop working on 2024-01-04l](https://platform.openai.com/docs/deprecations/instructgpt-models).
- H-1436
This PR:
- Add support for other models (such as GPT-4) in the service methods, so that the dropdown in the AI text block displays more than one option again
Manual testing
1. Checkout the branch, and run the AI text block locally
2. Ensure that only GPT-3.5 Turbo can selected
https://github.com/hashintel/hash/assets/42802102/1e888936-f23e-4ee1-bbb1-902209c425da

H-1436: Remove deprecated OpenAI models from model list in AI blocks

---

libs/@local/hash-validation/src/entity_type.rs

We want to validate only the BaseURLs, however, this is a more ambitious task as we don't store the inheritance data for Base URLs, only for VersionedUrls. For the time being, we disable the validation.

H-1551: Comment out link source/target type validation

---

apps/hash-frontend/src/pages/shared/top-context-bar.tsx

The 'share' button on a page (a document or canvas) only shares the page entity itself with other users (or the public), not the entities it contains. This PR hides the button on a page until this is fixed (involves figuring out how to cascade permissions from the page to entities it might need to display, and warn the user about what's happening).
The button remains on an individual entity's page.
This PR:
1. Check that the 'Share' button does not appear on a document page, but does on the entity editor for an individual entity

H-1461: Hide share button on page

---

apps/hash-graph/bins/cli/src/subcommand/snapshot.rs
apps/hash-graph/libs/graph/src/api/rest/test_server.rs
apps/hash-graph/libs/graph/src/snapshot/entity/batch.rs
apps/hash-graph/libs/graph/src/snapshot/mod.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/batch.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/entity_type/batch.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/metadata/batch.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/property_type/batch.rs
apps/hash-graph/libs/graph/src/snapshot/owner/batch.rs
apps/hash-graph/libs/graph/src/snapshot/restore/batch.rs
apps/hash-graph/libs/graph/src/snapshot/web/batch.rs

Snapshot restoration can be a very time consuming task currently if every entity is validated. This is especially the case if the database is on a remote server. As the validation could happen on a separate step, this provides the functionality to bypass validation

H-1591: Provide a `--skip-validation` flag to snapshot restoration

---

apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/validation.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/lib.rs

When a link is updated, the source and target entities should be validated at the current timestamp for the base URL
We also want to change validation on link creation to only check the base URL also
- Change link validation to search for matching BaseURL instead of Versioned URLs (including parents)
- Enable link validation on create/update

H-1413: Validate link source and target by BaseURL on creation/update

---

apps/hash-graph/tests/friendship.http
libs/@local/hash-validation/src/entity_type.rs

For some entities it's desired to link to draft entities, e.g. for `notification`s or `comment`s. We don't want to generally forbid creating links for drafts.
- [Slack discussion](https://hashintel.slack.com/archives/C022217GAHF/p1702385753659749) _(internal)_

H-1599: Remove restriction on links not being able link to drafts

---

apps/hash-frontend/src/pages/drafts.page/draft-entities.tsx
apps/hash-frontend/src/pages/drafts.page/draft-entities/draft-entities-filters.tsx
apps/hash-frontend/src/pages/drafts.page/draft-entity/draft-entity-provenance.tsx
apps/hash-frontend/src/pages/inbox.page.tsx
apps/hash-frontend/src/shared/notifications-context.tsx
apps/hash-frontend/src/shared/use-actors.ts
apps/plugin-browser/src/pages/popup/popup-contents/action-center/log/inference-request.tsx
apps/plugin-browser/src/pages/popup/popup-contents/action-center/one-off/infer-entities-action.tsx
apps/plugin-browser/webpack.config.js

Fixes a few bugs related to the notifications / draft page following the introduction of machine actors (H-1625):
- Account for potential mismatches between the contents of the `draftEntities` and `draftEntityHistoriesSubgraph`s (fixes crash when a draft is created with the page open)
- Look for machine actors as draft creators in the `DraftEntityChip`
- Better copy for machine-inferred entity notifications
- Fix link to entities in machine-inferred entity notifications
- Filter out notifications linked to archived entities
- Correct the query for machine actors
Separately:
- Stop uploading plugin source maps to Sentry in development
- H-1561: Have a link to the inference source in the plugin `Log` tab
This PR:
Rather than filtering out …

H-1625, H-1561: Fix bugs related to machine notifications, link to original page from plugin request

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/001-create-hash-system-types.migration.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/004-create-machines-update-users.migration.ts
apps/hash-api/src/graph/knowledge/system-types/hash-instance.ts

#3714 limited the `instantiator` permission on some system entity types, which is intended to restrict who can create entities of a certain type. But at the moment `instantiator` also restricts who can _update_ entities of those types, which was not the intention of the restrictions and isn't currently workable (e.g. users need to be able to edit their own record, at least parts of it, and to archive/mark notifications as read).
This PR therefore makes those system types have an 'anyone' instantiator again, until we change the restriction to apply only to entity creation and not update.
This PR:
1. You would have to rebuild the app and check that a user can mark a notification as read

H-1630: Make instantiators public for some system types

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util.ts
apps/hash-frontend/src/pages/drafts.page/draft-entities.tsx
apps/hash-frontend/src/pages/drafts.page/draft-entity.tsx
apps/hash-frontend/src/pages/drafts.page/draft-entity/draft-entity-action-buttons.tsx
apps/hash-frontend/src/shared/draft-entities-context.tsx
apps/hash-frontend/src/shared/notifications-context.tsx
apps/hash-frontend/src/shared/use-actors.ts
libs/@local/hash-isomorphic-utils/src/ontology-types.ts

This PR archives notifications related to draft entities when they are discarded on the `/drafts` page.
In addition it:
- fixes a bug in a migration utility function which meant the migration state was not updated with the up-to-date version of a type
- fixes the empty state on the `/drafts` page (currently it just hangs on the loading state)
- fixes an issue where we weren't accounting for `oneOf: {}`, not relevant to the diff in this PR but was uncovered in some other changes I originally made
- H-1631
See description.
This PR:
1. Create a draft entity via the browser plugin
2. Check a notification and a draft entity was created
3. Discard the draft entity, and ensure the notification has been archived …

H-1631: Archive notification when discarding a draft entity

---

apps/hash-ai-worker-ts/src/activities/infer-entities.ts
apps/hash-ai-worker-ts/src/workflows.ts
apps/plugin-browser/src/scripts/background/infer-entities.ts
libs/@local/hash-isomorphic-utils/src/temporal-types.ts

This updates the prompt and context in the AI Inference feature to address two common failures:
1. Failing to infer the most obvious entity of a requested type in a webpage – providing the page title and URL and a hint about focus seems to help here
2. Being 'lazy' in filling out properties for which there is information in the context – encouraging it to be comprehensive seems to help here
In local testing the 'comprehensive-bias' encouragement was so successful that I started getting `length` finish reasons. I want to see if it's possible to stitch together function call responses to make a bigger function argument than the completion token limit allows, but since each iteration of this takes 10 minutes+ to test and there are higher priorities right now I will come back to it in the …

H-1655: Update AI inference prompt to provide more context, encourage comprehensiveness

---

apps/hash-api/src/graphql/resolvers/integrations/linear/sync-workspaces-with-teams.ts
apps/hash-api/src/integrations/linear/oauth.ts
apps/hash-api/src/integrations/sync-back-watcher.ts

This PR makes several fixes to the linear integration following the recent introduction of the linear bot machine user:
- Refactors the `oAuthLinearCallback` to ignore the `ownedById` it receives in the OAuth state, and just create the linear integration in the user's web. It also no longer gives the linear bot access to the web, as in this point in the flow we don't yet know which web the user is trying to sync linear with.
- Refactors the `syncLinearIntegrationWithWorkspacesMutation` resolver to ensure the linear bot has access to the webs the user is trying to sync linear data with. This now works for both org and user webs.
- Refactors the sync back watcher to use the linear bot to try and fetch any entity that has changed. We probably want to change this so that the sync back watcher …

H-1663: Fix linear integration

---

Cargo.lock
apps/hash-graph/bins/cli/Cargo.toml
apps/hash-graph/bins/cli/src/main.rs

We encountered a memory leak in our application. After endless debugging and false positives one solution which seems to work is switching out the global allocator. I'm not going into the details why this could solve this, but the TL;DR is that different allocators handle certain scenarios differently.
- Make `mimalloc` the global allocator

H-1668: Change global allocator to `mimalloc`

---

apps/hash-ai-worker-ts/src/activities/infer-entities.ts
apps/hash-ai-worker-ts/src/activities/infer-entities/create-entities.ts

In the AI inference logic we don't bother to create entities or ask the AI to update them if the model suggests an entity that is _identical_ to one that already exists (same type, properties).
There was a bug whereby if the AI had suggested a link involving one such entity in a _subsequent_ iteration, the link could not be created because we didn't preserve information on those entities across iterations (there was no record of them in future iterations).
This PR fixes that by tracking entities which were not created because they are identical to existing entities, so that they are available in subsequent iterations.
This PR:

H-1669: Fix creating some link entities in AI inference

---

infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/hash_application/spicedb.tf

Last time when we updated SpiceDB the migration failed due to the wrong connection URI. This was because the migration connection URI was overwritten by the default URI.

H-1708: Fix SpiceDB migration not working in prod

---

apps/hash-api/src/graph/knowledge/system-types/user.ts

Fix setting permissions on user webs where they haven't yet completed signup – we need to use the system account to grant a machine actor permissions to their web, not the user (as they haven't been given permission to do so yet)
This PR:

H-1709: Update permission set during registration

---

.github/workflows/hash-backend-cd.yml
infra/terraform/hash/hash_application/api.tf
infra/terraform/hash/hash_application/graph.tf
infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/hash_application/spicedb.tf
infra/terraform/hash/hash_application/temporal_worker_ai_ts.tf
infra/terraform/hash/hash_application/temporal_worker_integration.tf
infra/terraform/hash/hash_application/type_fetcher.tf
infra/terraform/hash/hash_application/variables.tf
infra/terraform/hash/main.tf
infra/terraform/hash/prod-usea1.tfvars

Addresses H-1714 and H-1717 (children of H-96). To have finer control over resources and a better traffic health check this moves SpiceDB and the Graph into separate services. Also fixes H-1621 in drive-by. 
- Create a task definition, a service, and a security group for SpiceDB, the Graph and the type fetcher
- Use AWS Service Connect to connect the Graph with SpiceDB
- Update CD to restart the graph service as well
This PR:
- `egress` rules can probably be reduced
- Currently, it's using 2 CPUs and 4 GB memory, this probably can be reduced

H-1621, H-1714, H-1717: Split SpiceDB tasks into another service

---

Cargo.lock
Cargo.toml
libs/@local/hash-validation/Cargo.toml
libs/@local/hash-validation/src/data_type.rs
libs/@local/hash-validation/src/lib.rs

Add support for some more data type validations:
- `minimum`
- `maximum`
- `exclusiveMinimum`
- `exclusiveMaximum`
- `multipleOf`
- `format = "uri"`
- `format = "email"`

H-1735: Validate more custom data types

---

.github/workflows/lint.yml
.github/workflows/test.yml

If a global file changed, the CI does not run. As `turbo` does not recognize changes in `globalDependencies`, this only filters CI runs if the root package did not change.
If the CI of this PR runs we're good.
This PR:

H-1736: Run CI if the root package changed

---

apps/hash-graph/tests/friendship.http
libs/@local/hash-authorization/schemas/v1__initial_schema.zed
tests/hash-backend-integration/src/tests/graph/ontology/primitive/data-type.test.ts

We don't expose the functionality in the frontend but we need to allow web admins to insert new data types.
- Allow `administrator` relations to insert/update data types
- Adjust HTTP and BE tests
This PR:

H-1711: Allow inserting custom data types as web admin

---

apps/hash-frontend/src/pages/inbox.page.tsx
apps/hash-frontend/src/shared/notifications-context.tsx

This PR adds the time of day to the nearest minute when a notification was created to the notification timestamp, when the notification was created more than a day ago.
- H-1656
- fixes the empty state of the notifications page (previously was loading indefinitely when there are 0 notifications)
This PR:
Easiest way to test this is to uncomment the various conditions that determine how the timestamp is formatted for an existing notification.
When the notification has been created less than a minute ago, displays:
More than a minute ago (will include hours if more than an hour ago):
More than a day ago:
More than 7 days ago:
More than a year ago:

H-1656: Show more precise timestamps than the day in the `Inbox > Notifications` table

---

apps/hash-frontend/src/components/hooks/block-protocol-functions/knowledge/knowledge-shim.ts
apps/hash-frontend/src/components/hooks/block-protocol-functions/knowledge/use-block-protocol-query-entities.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/query-editor-page.tsx
apps/hash-frontend/src/pages/settings/integrations/use-linear-integrations.ts
blocks/chart/package.json
blocks/chart/src/app.tsx
blocks/chart/src/types/generated/block-entity.ts
blocks/table/package.json
blocks/table/src/app.tsx
blocks/table/src/components/settings-bar/settings-bar.tsx
blocks/table/src/components/table/table-with-query.tsx
blocks/table/src/components/table/table.tsx
blocks/table/src/dev.tsx
blocks/table/src/types/generated/block-entity.ts

This PR allows for loading entities into the table block via the "Select data" modal.
- H-1472
- updates the block to use `https://blockprotocol.org/@hash/types/entity-type/table/v/1` and related production types (previously it was using types created in a staging environment)
- adds the "Has Query" link to the block's type, so that the select data modal is displayed in the block's dropdown
- uses the property type's title to name columns, rather than using the slug from its base UrL
- cleaned up some misleading variable names
This PR:
1. Checkout the branch, and load the table block into a locally running instance of HASH
2. Try using the table block in its default mode, where data/columns are manually added
3. Try using the …

H-1472: Support loading entities into table block

---

apps/hash-graph/libs/api/src/rest/mod.rs
apps/hash-graph/libs/graph/src/knowledge/query.rs
apps/hash-graph/libs/graph/src/store/postgres/query/compile.rs
apps/hash-graph/libs/graph/src/store/postgres/query/condition.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/where_clause.rs
apps/hash-graph/libs/graph/src/store/postgres/query/statement/select.rs
apps/hash-graph/libs/graph/src/store/postgres/query/table.rs
apps/hash-graph/libs/graph/src/store/query/filter.rs
apps/hash-graph/libs/graph/src/store/query/mod.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/friendship.http
libs/@local/hash-graph-types/rust/src/embedding.rs
libs/@local/hash-graph-types/rust/src/lib.rs

To allow querying by embeddings it's required that a Vector type is available in structural queries
- Rename `Parameter::Number` to `Parameter::I32`
- Add `Parameter::F64` and `Parameter::Vector`
- Add an `Embedding` type and allow converting it to/from Postgres
- Add filter for L2 distance, cosine distance, and inner product
This PR:

H-1649: Support `Vector` type in Structural Queries

---

libs/@local/hash-validation/src/data_type.rs

The `label` property on data type does not have to be validated

H-1764: Allow `label` property on data types

---

infra/terraform/hash/hash_application/graph.tf
infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/hash_application/variables.tf
infra/terraform/hash/main.tf

Migration script require admin permissions, e.g. when creating extensions. This will change the AWS instance to use the `superuser` for migration instead of the default user.
- Use a new set of environment variables for the migration container
This PR:

H-1783: Use superuser permissions to migrate graph database

---

apps/hash-graph/libs/api/src/rest/utoipa_typedef/subgraph/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/libs/graph/src/subgraph/mod.rs

Even if we sort the returned values in Postgres the roots in the subgraph are unordered. This means that any sorting is pointless and results in unexpected values when using pagination.
- retain the order
This PR:

H-1762: Retain order returned from Postgres in `roots`

---

apps/hash-frontend/src/pages/signup.page.tsx

#3767 added an 'allow list' which limits which emails can signup to HASH, but disallowed users were still shown the next step of the signup form, which couldn't be completed as they didn't have permission to.
This PR fixes that by redirecting them out of the signup flow if they can't complete it.

H-1789: Send user out of signup flow if they are not on access whitelist

---

apps/hash-api/src/index.ts
apps/hash-frontend/src/blocks/use-fetch-block-subgraph.ts
apps/plugin-browser/package.json
apps/plugin-browser/src/pages/options/options-contents.tsx
apps/plugin-browser/src/pages/popup/popup-contents.tsx
apps/plugin-browser/src/pages/popup/popup-contents/action-center.tsx
apps/plugin-browser/src/pages/popup/popup-contents/action-center/shared/select-web-target/web-selector.tsx
apps/plugin-browser/src/pages/shared/sentry.ts
apps/plugin-browser/src/shared/get-user.ts
apps/plugin-browser/src/shared/storage.ts

H-1759: 
- Account for users who haven't completed signup in the plugin, and the AI inference websocket, by treating them as non-users
H-1793:
- Fix bug when labelling entities with a placeholder entity id by correcting the delimiter in the placeholder id. This bug was exposed by the additional of `generateEntityLabel` to the entity editor modal in #3759. The modal component (at least the wrapper) is mounted as long as an entity subgraph is present, but the subgraph might contain a placeholder entity, for new paragraph blocks. This was crashing because the `extractEntityUuidFromEntityId` function expects the entity id to have a `~` delimiter, and the placeholder id for new block entiites still used the old `%` delimiter (between the ownedById and uuid).
This PR: …

H-1759, H-1793: Handle incomplete users in plugin, fix entity labelling bug

---

apps/hash-frontend/src/pages/shared/entities-table.tsx
libs/@hashintel/block-design-system/src/entities-graph-chart.tsx
libs/@hashintel/design-system/src/e-chart.tsx

This PR makes some small improvements to the entities graph:
- prevents initial animation from playing by disabling `layoutAnimation` on the initial echarts configuration, and subsequently setting `layoutAnimation` back to `true`
- on the `/entities` page render all nodes as primary nodes (no reduced opacity)
- H-1797
This PR:
- republish `Graph` block to account for changes in the entities graph component
- hide node/edge labels when zooming out of the entities graph (H-1803)
Manual testing
Go to the `/entities` page, and look at the graph visualisation.
<details>
<summary>Previously</summary>
https://github.com/hashintel/hash/assets/42802102/81c40ed7-b095-478d-8c4e-b8cb13fea7f6
</details>
<details>
<summary>Now</summary> …

H-1797: Improve entity graph

---

apps/hash-api/src/graph/ontology/primitive/util.ts
apps/hash-frontend/next.config.js
apps/hash-frontend/src/shared/generate-link-parameters.ts
apps/hash-frontend/src/shared/is-href-external.ts

Fixes a couple of bugs related to links to external types, i.e. types which originate from instances of HASH other than the one running:
1. Respect `SELF_HOSTED_HASH` environment variable in the frontend, if it is set (rather than always treating a `localhost:3000` origin as being HASH prime). This allows testing of self-hosted instance frontends locally
2. Only use the special external type page for entity types (since there is no dedicated page for property or data types, whether external or not)
This PR:
1. Set `SELF_HOSTED_HASH=true` in `.env.local` and run the app (don't need to reseed)
2. Visit `/types`
3. Click on a HASH entity type, check it loads in the external route
4. Click on a HASH property type, check that the JSON is loaded …

H-1598: Fix handling of links to externally-hosted types

---

apps/hash-frontend/src/blocks/use-fetch-block-subgraph.ts
apps/hash-frontend/src/pages/[shortname]/[page-slug].page.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/use-rows/generate-property-rows-from-entity.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/use-rows/generate-property-rows-from-entity/generate-property-row-recursively.ts
apps/hash-frontend/src/pages/shared/block-collection/mention-view/mention-display.tsx
apps/hash-frontend/src/pages/shared/block-collection/shared/mention-suggester.tsx
apps/hash-frontend/src/pages/shared/block-collection/shared/mention-suggester/mention-suggester-entity.tsx
apps/hash-frontend/src/pages/shared/hidden-types.ts
apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-entities-list.tsx
libs/@local/hash-isomorphic-utils/src/text.ts

The PR started off to fix the `@mention` suggester crashing, and fixed a few other things along the way:
1. Handle missing target entities of links in the mention suggester. 
- the cause of the original crash – the mention suggester doesn't look for draft entities, and so it picks up 'live' notification entities which point to draft entities, which aren't available
2. Save the `linkEntityTypeBaseUrl` when inserting a mention of the target of a link (this information was not being saved before, meaning the link type wasn't available when returning to the page)
3. Handle type inheritance in the mention display
4. Hide some system types from the mention suggester
Things I fixed in passing because I noticed them when trying to test this:
1. The entity editor was crashing when viewing entities …

H-1808: Fix mention bugs, editor crash on property object arrays, and page content reloading

---

Cargo.lock
libs/@local/hash-validation/Cargo.toml
libs/@local/hash-validation/src/data_type.rs

This adds CDT validation (and support) for:
- `ipv4`
- `ipv6`
- `hostname` (Either an IP or domain)
- `uuid`
- `regex`
- `time`
Also, I removed the `chrono` dependency and added a simple regex for date parsing. In contrast to `chrono` or `time` this does only validate dates which conforms to both, ISO-8601 and RFC 3336.
This PR:
Various tests and test cases were added/adjusted

H-1788, H-1791: Add more common custom data type validations

---

.github/actions/build-docker-images/action.yml
.github/actions/load-docker-images/action.yml
.github/renovate.json

Version 4 of `actions/download-artifacts` frequently fails to download an artifact. Until this issue is fixed we're pinning the version to v3.
- https://github.com/orgs/community/discussions/81413
This PR:

H-1837: Downgrade `actions/download-artifact` to `v3`

---

apps/hash-api/src/generate-ontology-type-ids.ts
libs/@local/hash-isomorphic-utils/src/ontology-type-ids.ts

This PR adds the system data types (the data types in the HASH org) to the generated `ontology-type-ids.ts` file.
- H-1792
This PR:
Check the `ontology-type-ids.ts` file in this PR contains the expected data types.

H-1792: Generate `systemDataTypes` type ids

---

apps/hash-external-services/docker-compose.yml
apps/hash-external-services/postgres/Dockerfile

We currently encounter a lot of CI failures when starting the Postgres external service. It seems to be fixed when removing the `echo` from `postgres/Dockerfile` and use the desired `PGDATA` directory for the volume. I don’t see why we have that `echo` in the first place as it’s outputting to a directory which is supposed to be unused as `PGDATA` is manually set.
This PR:

H-1846: Use the default `/var/lib/postgresql/data` for PGDATA

---

apps/hash-external-services/docker-compose.dev.yml

The volume for `vault` is wrong and uses the same volume as for `postgres`. As the result `postgres` will fail to start if `vault` was started earlier.

H-1846: Use correct volume for `vault`

---

Cargo.lock
apps/hash-ai-worker-ts/src/activities/embeddings.ts
apps/hash-graph/libs/api/src/rest/entity.rs
apps/hash-graph/libs/graph/Cargo.toml
apps/hash-graph/libs/graph/src/store/fetcher.rs
apps/hash-graph/libs/graph/src/store/knowledge.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
libs/@local/temporal-client/src/ai.rs
libs/@local/temporal-client/src/error.rs
libs/@local/temporal-client/src/lib.rs
tests/hash-graph-integration/postgres/lib.rs

After an entity was created/updated, the workflow to update the entity embeddings should be triggered. This PR implements that.
- #3855
- #3861 
This PR:

H-1841: Trigger embedding creation workflow when entity was created/updated

---

apps/hash-ai-worker-ts/src/activities/graph.ts
apps/hash-ai-worker-ts/src/workflows.ts
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/query/statement/select.rs
apps/hash-graph/libs/graph/src/store/postgres/query/table.rs
libs/@local/temporal-client/src/ai.rs

For initial seeding and if an embedding creation failed we need a way to manually trigger entity embedding creation. Ideally, this is done via a structural query.
- #3855
- #3861 
- #3862
This PR:
When using a filter to return all entities, this is still filtered by the actor's permission to see the entities so it's not possible to update all embeddings in one go.
With a few simple arguments it's possible to update all entities without embeddings:
```json
[{"authentication":{"actorId":"40bbc079-0d81-4def-bd5d-5fae94edca47"},"filter":{"equal":[{"path":["embedding"]},null]}}]
```
A full call would look like this:
```bash
temporal workflow execute --no-pager --task-queue ai --type updateEntityEmbeddings --namespace HASH -i "$(jq -n '{filter: { …
```

H-1871: Extend workflow to support multiple entities or a filter

---

apps/hash-ai-worker-ts/src/workflows.ts

Embeddings are also generated for drafts and when using a filter the behavior should be the same.

H-1888: Don't filter out draft entities when create embeddings via a filter

---

apps/hash-frontend/src/pages/shared/entity-type-page/type-slide-over-stack/type-slide-over-slide.tsx
apps/hash-frontend/src/shared/icons/arrow-up-right-from-square-regular-icon.tsx
apps/hash-frontend/src/shared/layout/layout-with-header/notifications-dropdown.tsx
libs/@hashintel/type-editor/src/entity-type-editor/link-list-card/anything-chip.tsx

This PR makes some minor styling/functionality improvements, including:
- copying the URL of an entity type in the entity type slideover when the URL chip is clicked (H-1678), and allowing the type to be opened in a new tab via an icon (H-1679)
- fixes the font size of the notification counter in the header (H-1753)
- fixes height inconsistencies between the "Anything" chip and other entity type chips (as part of H-590)
- H-590, H-1753, H-1678, H-1679
This PR:
View the relevant pages in the deployment to view the styling changes.
Updated font size for notification counter:
Consistent height for "Anything" and other type chips:
Allow for copying type URL via the chip in the slideover: …

H-590, H-1753, H-1678, H-1679: Style cleanup around the expected link types table on the entity types page + other minor tweaks

---

.env
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/read.rs
apps/hash-graph/libs/graph/src/store/postgres/query/compile.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/group_by_clause.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/with_clause.rs
apps/hash-graph/libs/graph/src/store/postgres/query/statement/select.rs

There might be the different embeddings for the same entity and as the entities are sorted by the distance it's not guaranteed, that an entity is only returned once.
- Add a `GROUP BY` statement to the distance filter
- Tweak logging to (a) not print `rustle` debug/trace infos and (b) print tracing info about the calculated embedding distance of an entity
This PR:

H-1904: Avoid duplicated entries when querying by distance

---

infra/terraform/hash/main.tf

The `HASH_TEMPORAL_SERVER_HOST` and `HASH_TEMPORAL_SERVER_PORT` variables are set twice. This removes one of the definitions.

H-1905: Remove duplicated environment variables for Graph

---

apps/hash-api/package.json
apps/hash-api/src/graphql/resolvers/ontology/data-type.ts
apps/hash-api/src/graphql/resolvers/ontology/entity-type.ts
apps/hash-api/src/graphql/resolvers/ontology/property-type.ts
apps/hash-frontend/src/graphql/queries/ontology/data-type.queries.ts
apps/hash-frontend/src/graphql/queries/ontology/entity-type.queries.ts
apps/hash-frontend/src/graphql/queries/ontology/property-type.queries.ts
apps/hash-frontend/src/middleware/return-types-as-json/generate-query-args.ts
libs/@local/hash-isomorphic-utils/src/graph-queries.ts
libs/@local/hash-isomorphic-utils/src/graphql/type-defs/ontology/data-type.typedef.ts
libs/@local/hash-isomorphic-utils/src/graphql/type-defs/ontology/entity-type.typedef.ts
libs/@local/hash-isomorphic-utils/src/graphql/type-defs/ontology/property-type.typedef.ts

When a type's URL is requested outside a browser contet (when there's no `text/html` in the `accept` header), we return JSON instead.
The logic for doing so was excluding archived types. Type archival is meant to remove types from being discovered, but not from being used if they are already being relied on. 
This PR fixes the 'return types as JSON' logic to return an archived type if its URL is requested.
This PR:
- Manual
1. Create a property type and archive it
2. `curl [its-id]` and check the JSON is returned
3. in `main` this will not work

H-1908: Return archived types when JSON is requested

---

apps/plugin-browser/src/pages/popup/popup-contents/action-center/automated/select-scope/rows-by-location.tsx
apps/plugin-browser/src/pages/popup/popup-contents/action-center/automated/select-scope/rows-by-type.tsx
apps/plugin-browser/src/pages/popup/popup-contents/action-center/one-off/infer-entities-action.tsx
apps/plugin-browser/src/pages/popup/popup-contents/action-center/shared/entity-type-selector.tsx

This PR introduces a convenience when configuring entity type inference in the browser plugin: when an entity type is added, it automatically adds any links from that type, plus their destination types (but no further).
This does not yet indicate which types are automatically added / inherited, or remove any linked types if a source type is removed. We will do more of this in follow-up.
This PR:
1. `yarn dev` in the plugin's folder with the API running, try adding types which link to stuff
https://github.com/hashintel/hash/assets/37743469/3e9b39bb-20a2-4c99-b9f6-5f1339c1c7e7

H-1721: When adding a type for inference, add its linked types

---

apps/hash-frontend/src/pages/[shortname].page/pinned-entity-type-tab-contents.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-page-wrapper/entity-page-header.tsx
apps/hash-frontend/src/pages/new/entity.page.tsx
apps/hash-frontend/src/pages/shared/entity-type-page/entity-type-tabs.tsx
apps/hash-frontend/src/pages/shared/link-label-with-source-and-destination.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-entity-type-list/entity-menu.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-entity-type-list/entity-type-menu.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/account-page-list/account-page-list.tsx

This PR prevents a crash in the entity editor when trying to create an entity with a link entity type, by displaying an error message instead. It also hides links to the "Create new entity" page when the entity type is a link entity.
- H-1845
- H-1814
- H-1815
- H-1818
- lower-case "Page" in sidebar on hover (H-1818)
- make 'Entities' breadcrumb clickable (H-1815)
- display attributes (properties/outgoing links)of source/destination in tooltip link chips (H-1814)
This PR:
1. Try creating a link on the "Create new entity" page, for example via `http://localhost:3000/new/entity?entity-type-id=https%3A%2F%2Fhash.ai%2F%40hash%2Ftypes%2Fentity-type%2Fauthored-by%2Fv%2F1`
2. View an existing link entity in the entity editor or a …

H-1845, H-1814, H-1815, H-1818: Fix entity editor crashes + other small improvements

---

apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/property_type.rs
libs/@local/hash-authorization/src/schema/account.rs
libs/@local/hash-authorization/src/schema/data_type.rs
libs/@local/hash-authorization/src/schema/entity_type.rs
libs/@local/hash-authorization/src/schema/property_type.rs

When fetching an external type with circular dependencies the relationships to be inserted may have duplicates, which is not allowed.

H-1920: Fix authorization relationship updates on circular types

---

.env
apps/hash-graph/libs/api/src/rest/status.rs
infra/terraform/hash/main.tf
libs/@local/tracing/src/lib.rs
libs/@local/tracing/src/sentry.rs

Sentry is currently the place where we trace our errors. Because of this, we want to capture as many spans as possible.
- #3897 
- Dynamically configure sentry via environment variables
- Tweak log configuration
This PR:

H-1928: Make sure all Rust spans are captured in Sentry

---

apps/hashdotdev/src/_pages/blog/0004_announcing-error-stack.mdx
apps/hashdotdev/src/_pages/blog/0010_error-stack-update-0-2.mdx
package.json

Following concern expressed in #3740, this PR adds callouts to the top of our original `error-stack` announcement posts notifying users that the code snippets within may be out-of-date, and directing them to the up-to-date docs and examples for current best practice.
Fixes #3740.

GEN-132: Update `error-stack` blog posts with link to docs

---

apps/hash-api/src/graph/knowledge/system-types/org-membership.ts
apps/hash-api/src/graphql/resolvers/knowledge/entity/entity.ts
apps/hash-frontend/src/graphql/queries/knowledge/entity.queries.ts
apps/hash-frontend/src/pages/settings/organizations/[shortname]/members.page/add-member-form.tsx
libs/@local/hash-isomorphic-utils/src/graph-queries.ts
libs/@local/hash-isomorphic-utils/src/graphql/scalar-mapping.ts
libs/@local/hash-isomorphic-utils/src/graphql/type-defs/knowledge/entity.typedef.ts

This PR corrects a bug whereby adding an org member via the frontend would set the default permissions on the link between the member and the org, which is incorrect because:
1. The default permissions allow any member of the web (the org in this case) to edit the link, whereas it should be limited to org admins and the member the link refers to
2. The default permissions only permit web members to view the link, whereas org membership should be viewable by people outside the link (until we allow restricting that)
This PR fixes that by exposing the ability to specify custom permission relationships when creating an entity, and shares the org link permissions between the existing `createOrg` function in the backend, and the frontend.
An alternative solution would be to expose a …

H-1608: Set correct permissions on org membership link

---

apps/hash-api/src/graphql/create-apollo-server.ts
apps/hash-api/src/index.ts
apps/hash-api/src/storage/aws-s3-storage-provider.ts
apps/hash-api/src/storage/index.ts
infra/terraform/hash/prod-usea1.tfvars

This improves logging and error handling in the API by:
1. Moving the request logging middleware to before the routes it is supposed to apply to, so that it works
2. Similarly moving the Sentry tracing middleware up above the request routes
3. Setting the request context consistently between GraphQL and non-GraphQL requests
4. Clear the scope and breadcrumbs in each request, since otherwise Sentry has breadcrumbs / scope from other requests (this should not be required so there is still something wrong somehow)
5. Add a fallback error handler for non-GraphQL requests
6. Change the Node API's log level in production from `debug` to `info`
It also **adds some temporary debug logs** to try and figure out why file retrieval is not working in production, which I will remove after looking at …

H-1397: Better logging, error handling in the Node API

---

apps/hash-graph/libs/graph/src/store/postgres/query/compile.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/order_clause.rs

The roots are not sorted by distance anymore.

H-2008: Fix root sorting by embedding distance

---

apps/hash-graph/libs/graph/src/store/crud.rs
apps/hash-graph/libs/graph/src/store/postgres/crud.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/query.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/libs/graph/src/store/postgres/query/compile.rs
apps/hash-graph/libs/graph/src/store/postgres/query/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/query/statement/select.rs
apps/hash-graph/libs/graph/src/store/query/filter.rs

Generically passing custom paths to the query compiler came with various issues. The `CustomSorting` struct is supposed to do exactly this, so this was an issue. This PR solves various lifetime errors to allow passing `QueryPath<'static>` to the `SelectCompiler`. 
This PR:
- It's currently not possible to pass a generic `CustomSorting<'s, R: Record>` to the `ReadPaginated` trait. Using `'s` instead of `'static` implies some errors about the struct not being generic enough and using `R` instead of `Entity` came with various other lifetime issues. For the initial use case, `CustomSorting<'static, Entity>` is enough, but this suggest various other issues in the query logic itself, mainly because it grew over time and all different …

H-1937: Fix various lifetime issues and start implementing `CustomSorting`

---

apps/hash-ai-worker-ts/package.json
apps/hash-ai-worker-ts/src/activities.ts
apps/hash-ai-worker-ts/src/activities/infer-entities.ts
apps/hash-ai-worker-ts/src/activities/infer-entities/get-results-from-inference-state.ts
apps/hash-ai-worker-ts/src/activities/infer-entities/persist-entities.ts
apps/hash-ai-worker-ts/src/activities/infer-entities/shared/get-open-ai-response.ts
apps/hash-ai-worker-ts/src/workflows.ts
apps/hash-api/src/ai/infer-entities-websocket.ts
apps/hash-api/src/ai/infer-entities-websocket/handle-cancel-infer-entities-request.ts
apps/hash-api/src/ai/infer-entities-websocket/handle-infer-entities-request.ts
apps/hash-api/src/storage/aws-s3-storage-provider.ts
apps/plugin-browser/src/pages/popup/popup-contents/action-center/log/inference-request.tsx
apps/plugin-browser/src/pages/popup/popup-contents/action-center/log/inference-request/copyable-request-id.tsx
apps/plugin-browser/src/pages/popup/popup-contents/action-center/log/inference-requests.tsx
apps/plugin-browser/src/scripts/background.ts
apps/plugin-browser/src/scripts/background/infer-entities.ts
apps/plugin-browser/src/shared/messages.ts
apps/plugin-browser/src/shared/storage.ts
libs/@local/hash-isomorphic-utils/package.json
libs/@local/hash-isomorphic-utils/src/ai-inference-types.ts

Adds a button to inference jobs on the browser plugin allowing the user to cancel them early, receiving whatever entity creations/updates (if any) had been processed up to that point.
- Adds a button to pending inference requests allowing them to be cancelled (see demo)
- jobs which are cancelled are marked by red 'Cancelled' text in the inference details
- they otherwise appear as completed jobs, i.e. a gray dash if they resulted in no changes, and a green tick if they resulted in some changes. We could alternatively use a different icon for 'Cancelled', but it would mean the user would not know if it resulted in any graph changes or not.
- Handle cancellations in the AI inference websocket, and the Temporal activity/workflow
- a lot of the diff is moving the existing 'handle AI …

H-1626: Enable cancelling inference jobs from the browser plugin

---

.github/actions/install-turbo/action.yml
.github/actions/prune-repository/action.yml
.github/workflows/lint.yml
.github/workflows/test.yml
apps/hash-ai-worker-ts/docker/Dockerfile
apps/hash-frontend/vercel-install.sh
apps/hash-graph/docker/Dockerfile
apps/hash-integration-worker/docker/Dockerfile
infra/docker/api/prod/Dockerfile
infra/docker/frontend/prod/Dockerfile

The current CI fails because `turbo@1.12` behaves differently from `turbo@1.11`. This changes the CI to use the same version as specified in `package.json` so we can pin the version.

H-2074: Use turbo version from `package.json` in CI

---

.justfile
apps/hash-graph/libs/graph/src/knowledge/query.rs

`-Dwarnings` is not specified in CI.

H-2133: Fix CI not erroring if Rust docs contains invalid links

---

apps/hash-graph/libs/graph/src/knowledge/query.rs
apps/hash-graph/libs/graph/src/ontology/mod.rs
apps/hash-graph/libs/graph/src/snapshot/entity/batch.rs
apps/hash-graph/libs/graph/src/snapshot/entity/channel.rs
apps/hash-graph/libs/graph/src/snapshot/entity/mod.rs
apps/hash-graph/libs/graph/src/snapshot/entity/record.rs
apps/hash-graph/libs/graph/src/snapshot/entity/table.rs
apps/hash-graph/libs/graph/src/snapshot/mod.rs
apps/hash-graph/libs/graph/src/snapshot/restore/channel.rs
apps/hash-graph/libs/graph/src/store/crud.rs
apps/hash-graph/libs/graph/src/store/fetcher.rs
apps/hash-graph/libs/graph/src/store/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/libs/graph/src/store/postgres/query/compile.rs
apps/hash-graph/libs/graph/src/store/postgres/query/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/query/table.rs
apps/hash-graph/libs/graph/src/store/postgres/traversal_context.rs
apps/hash-graph/libs/graph/src/store/query/filter.rs
apps/hash-graph/libs/graph/src/store/record.rs
apps/hash-graph/libs/graph/src/subgraph/mod.rs
apps/hash-graph/libs/graph/src/subgraph/query.rs

To avoid regenerating embeddings, this adds the embeddings to the Snapshots as well.
- #3973 
This PR:
As snapshots are stored as JSON and embeddings contains many numbers the snapshot can grow pretty big. To mitigate this it's possible to pipe the snapshot from/to `gzip`. Later, we probably want to allow splitting the snapshots, either by number of records or by type. Ideally, it's possible to specify the format as well so a more efficient format can be used instead.

H-1886: Store embeddings in snapshot

---

apps/hash-ai-worker-ts/src/activities/graph.ts
apps/hash-ai-worker-ts/src/workflows.ts

From time to time it's required that all entity embeddings are updated.
- Add an activity to read all account ids based on the `user` BaseURL. If no user can see an entity, the embedding is not needed anyway
- Adjust the `updateEntityEmbeddings` workflow to use pagination. Only 100 entities are queried from the graph at once now
- Add a workflow to combine the two things
This PR:

H-2162: Write workflow to update all embeddings

---

infra/docker/api/prod/Dockerfile
infra/terraform/hash/hash_application/api.tf
infra/terraform/hash/hash_application/graph.tf

ECS does not use the health-check defined in the Dockerfile. This sets the check manually.

H-2171: Use Node API healthcheck in AWS

---

apps/hash-graph/libs/graph/src/snapshot/mod.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/batch.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/channel.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/entity_type/batch.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/entity_type/channel.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/mod.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/property_type/batch.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/property_type/channel.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/record.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/table.rs
apps/hash-graph/libs/graph/src/snapshot/restore/channel.rs

To make snapshot migrations possible, the embeddings should be stored in the snapshots as well.

H-2168: Add type embeddings to Snapshots

---

apps/hash-api/src/lib/config.ts

It adds `https://hash.ai` to the Node API CORS list, so that we can call the API from https://hash.ai (to check if a user is logged in to the app).
This PR:

H-2189: Add hash.ai to Node API CORS list

---

infra/terraform/hash/postgres/postgres.tf

AWS updated Postgres from 15.3 to 15.5 which breaks our `terraform apply` step.

H-2190: Pin Postgres to the major version only

---

apps/hash-frontend/src/pages/signin.page.tsx
apps/hash-frontend/src/pages/signup.page/signup-registration-form.tsx

This PR allows the email value on `/signup` to be set from a query parameter, so that we can send people here to complete registration having entered their email elsewhere.
It also adds autofocus to inputs on login and signup routes.
This PR:
1. Visit `https://localhost:3000/signup?email=something@example.com`

H-2187: Allow setting email on signup page from query params

---

apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/postgres_migrations/V16__manual_temporal_updates.sql

The current implementation uses a trigger to properly handle a bi-temporal update. This comes with a few downsides:
- It's not possible to re-use the trigger for setting an end-time (this is the main issue currently)
- It's not easily possible to get the previous edition id
- Maintainability is bad as migration files must not change
- Remove the triggers from Postgres and implement it manually in the Graph logic. 
This PR:

H-2159: Implement temporal versioning without a Postgres update trigger

---

.env
apps/hash-external-services/docker-compose.type-fetcher.yml
apps/hash-graph/bins/cli/src/subcommand/type_fetcher.rs
infra/terraform/hash/hash_application/graph.tf
infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/hash_application/type_fetcher.tf

The port `4444` is currently used by the type fetcher and conflicts with Ory Hydra. As we are in full control over the default port of the type fetcher and it would be annoying to change the default port to another port for Ory Hydra, we change the port for the type fetcher.
This PR:

H-2195: Change port for type fetcher to `4455`

---

apps/hash-graph/libs/graph/src/knowledge/query.rs
apps/hash-graph/libs/graph/src/snapshot/entity/channel.rs
apps/hash-graph/libs/graph/src/snapshot/entity/table.rs
apps/hash-graph/libs/graph/src/snapshot/restore/channel.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/query.rs
apps/hash-graph/libs/graph/src/store/postgres/query/entity.rs
apps/hash-graph/libs/graph/src/store/postgres/query/table.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/postgres_migrations/V18__undrafted_at.sql
libs/@local/hash-graph-types/rust/src/knowledge/entity.rs
tests/hash-graph-integration/postgres/drafts.rs

It's interesting to know if for a given draft a non-draft entity exists and if so at which time that one was created. This adds two new provenance fields (decision time + transaction time) for the time when an entity of a given ID was first created in a non-draft state.
- Add provenance fields and do required changes to the Graph API
- Drive-by: Fix `created-at-*` not calculated correctly in database
- Drive-by: Fix snapshots not being able to be restored when embeddings are part of the snapshot
This PR:
- A bunch of assertions were added to the `draft` tests

H-2210: Store provenance data for first non-draft entity date

---

apps/hash-ai-worker-ts/src/workflows.ts
apps/hash-api/src/graph/knowledge/primitive/entity.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/use-rows/generate-property-rows-from-entity/get-expected-types-of-property-type.ts
apps/hash-frontend/src/shared/layout/layout-with-header/page-header.tsx
apps/hash-frontend/src/shared/layout/layout-with-header/search-bar.tsx
apps/hash-frontend/src/shared/layout/layout-with-header/search-bar/search-input.tsx
libs/@local/hash-backend-utils/src/create-graph-client.ts

This PR restores the search bar in HASH. It searches for entities based on their semantic distance, and links results to the entity editor.
This PR:
- Because search involves calling a Temporal workflow to create the embedding of the search text, there might be unacceptable delay introduced that could be mitigated by calling OpenAI's embedding model directly from the API. To see how this works in practice and potentially change.
- Results are not paginated, which means they might be slow to load with lots of results. H-2258
- Ideally for entities which are contained in a page (e.g. paragraphs), we would link to the containing Page rather than the entity editor. H-2258. 
- The entity editor crashes if you try and load a paragraph block into …

H-2034: Restore basic search bar to frontend

---

apps/hash-graph/bench/read_scaling/knowledge/complete/entity.rs
apps/hash-graph/postgres_migrations/V19__temporal_indices.sql

We noticed a significant performance regression when traversing entities. The query, which is responsible to find edges from one entities to other entities, is the reason for this (e.g. finding the left entities of a link). To find these edges, these steps are done in the query:
- Get the temporal data of the source entities (“source entities”) for:
- the source’s pinned axis lies inside the queried pinned axis
- the source’s variable axis starts with the entity version being queried
- the source’s entity id (web id + uuid) matches the requested entity’s id
- read all edges from the “source entities” (identified by the entity ID), this results in a set of potential target entity IDs
- Get the temporal data of target entities, where:
- the target’s pinned axis lies inside the queried …

H-2264: Add index for temporal metadata

---

Cargo.lock
apps/hash-graph/libs/api/Cargo.toml
apps/hash-graph/libs/api/src/rest/data_type.rs
apps/hash-graph/libs/api/src/rest/entity.rs
apps/hash-graph/libs/api/src/rest/entity_type.rs
apps/hash-graph/libs/api/src/rest/mod.rs
apps/hash-graph/libs/api/src/rest/property_type.rs
apps/hash-graph/libs/graph/src/store/knowledge.rs
apps/hash-graph/libs/graph/src/store/ontology.rs
apps/hash-graph/libs/graph/src/subgraph/identifier/vertex.rs
apps/hash-graph/openapi/openapi.json
libs/@blockprotocol/type-system/rust/Cargo.toml
libs/@blockprotocol/type-system/rust/src/ontology/url/mod.rs
libs/@local/hash-graph-types/rust/src/knowledge/entity.rs

`ToSchema` is not implemented for `BaseUrl` and `VersionedUrl`. For simple types this can be avoided by explicitly specifying the value type, however, when nested this is an issue (as required for multi type entities).
- Implement `ToSchema` for URL types
- Use that definition everywhere (removing workaround code)
This PR:

H-2290: Implement `utoipa` schema for type system URLs

---

package.json
yarn.lock

Turbo just released `1.12.5` which breaks CI for us.

H-2345: Pin turbo version to patch version

---

apps/hash-graph/libs/graph/src/lib.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
libs/@blockprotocol/type-system/rust/src/lib.rs
libs/@blockprotocol/type-system/rust/src/ontology/entity_type/error.rs
libs/@blockprotocol/type-system/rust/src/ontology/entity_type/links/mod.rs
libs/@blockprotocol/type-system/rust/src/ontology/entity_type/links/raw.rs
libs/@blockprotocol/type-system/rust/src/ontology/entity_type/mod.rs
libs/@blockprotocol/type-system/rust/src/ontology/entity_type/raw.rs
libs/@blockprotocol/type-system/rust/src/ontology/shared/array/mod.rs
libs/@blockprotocol/type-system/rust/src/ontology/shared/array/raw.rs
libs/@blockprotocol/type-system/rust/src/ontology/shared/object/mod.rs
libs/@blockprotocol/type-system/rust/src/ontology/shared/object/raw.rs
libs/@blockprotocol/type-system/rust/src/ontology/shared/one_of/mod.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/property_type.rs

Quite a few issues were detected in the type system package. This fixes a few of them.
- Properly implement merging entity types (`properties`, `required`, `links`)
- Fix a deserializing issue for `links`
- Don't allow `0` in `maxItems`
- Make `ordered` in `links` optional (it's deprecated)
- Tests for merging links were added
This PR:

H-2303: Overhaul merge logic for entity types

---

.github/workflows/test.yml

The Playwright tests currently fail a lot due to unknown reasons. To still allow PRs to be merged, this temporarily disables the requirement of these tests.

H-2347: Temporarily disable Playwright test requirement

---

package.json
turbo.json
yarn.lock

The glob for global dependencies in `turbo.json` were incorrect. The newest Turbo version errors in such a case (which typically would be a minor release, not a patch release, as this is a feature). This PR fixes the glob and bumps the version to the latest version.
- #4131

H-2345: Fix global dependency globs for Turbo

---

apps/hash-graph/libs/graph/src/snapshot/ontology/entity_type/channel.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/table.rs
apps/hash-graph/libs/graph/src/store/knowledge.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/read.rs
apps/hash-graph/libs/graph/src/store/validation.rs
libs/@blockprotocol/type-system/rust/src/ontology/entity_type/closed.rs
libs/@blockprotocol/type-system/rust/src/ontology/entity_type/links/mod.rs
libs/@blockprotocol/type-system/rust/src/ontology/entity_type/mod.rs
libs/@blockprotocol/type-system/rust/src/ontology/entity_type/raw.rs
libs/@blockprotocol/type-system/rust/src/ontology/mod.rs
libs/@blockprotocol/type-system/rust/src/ontology/property_type/mod.rs
libs/@blockprotocol/type-system/rust/src/ontology/shared/array/mod.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/error.rs
libs/@local/hash-validation/src/lib.rs

The `EntityType` struct does not keep track over the IDs of the types when merging them together to create a closed schema. That tracking, however, is very useful when validating entities and more. This introduces a type which keeps track over the IDs when merging but don't expose it to the Node API, yet. This will be especially useful when multi-type entities will be introduced.
- #4113 
This PR:

H-2331: Introduce a `ClosedEntityType` struct

---

apps/hash-frontend/vercel-install.sh
apps/hashdotdesign/vercel-install.sh
apps/hashdotdev/vercel-install.sh

We encounter frequent failures in the Vercel build step when installing Rust. This moves the toolchain installation to the install step and adds a retry logic.
This PR:

H-2355: Install Rust in Vercel install step

---

apps/hashdotai/guide/02_webs/02_orgs.mdx

Corrects a misspecified icon URL.

H-2376: Fix `Organizations` user guide page icon

---

Cargo.toml

We currently cannot use the backtraces generated in production as symbols are stripped. See the [official documentation](https://doc.rust-lang.org/cargo/reference/profiles.html#strip).

H-2381: Enable backtraces in production

---

Cargo.lock
apps/hash-graph/libs/graph/src/knowledge/query.rs
apps/hash-graph/libs/graph/src/ontology/data_type.rs
apps/hash-graph/libs/graph/src/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/ontology/property_type.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/query.rs
apps/hash-graph/libs/graph/src/store/postgres/query/compile.rs
apps/hash-graph/libs/graph/src/store/postgres/query/entity.rs
apps/hash-graph/libs/graph/src/store/postgres/query/table.rs
apps/hash-graph/libs/graph/src/store/query/filter.rs
apps/hash-graph/libs/graph/src/store/query/mod.rs
apps/hash-graph/postgres_migrations/V20__multi_type_entities.sql

The logic to read multiple entity types for a single entity is different. This creates a view to aggregate the types and make them available.
- #4148 
This PR:
Write tests for multi type pentities
None, yet

H-2351: Allow querying multiple entity types for a single entity

---

infra/terraform/hash/postgres_roles/postgres_roles.tf

The `entity_drafts` table wasn't accessible from the graph user in production. A `GRANT` call was able to solve this issue:
```sql
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA public TO graph;
```
We currently don't manage permissions for the graph database in terraform and this could be the issue as no default privileges are set.

H-2298: Encode `graph` database permissions in Terraform

---

Cargo.lock
apps/hash-ai-worker-ts/src/workflows.ts
libs/@local/hash-subgraph/src/stdlib/subgraph/roots.ts

The `updateEntityEmbeddings` workflow may take a filter or a list of entities. Entities passed from the Graph may contain more than a single type id, so the entities has to be mapped, first.

H-2385: Convert Graph API entity type to Node API type in AI worker

---

apps/hash-frontend/src/components/grid/utils/sorting.ts
apps/hash-frontend/src/pages/_app.page.tsx
apps/hash-frontend/src/pages/shared/entities-table.tsx
apps/hash-frontend/src/pages/shared/entities-table/use-entities-table.tsx
apps/hash-graph/package.json
package.json

A few small bug fixes:
1. The entities table didn't switch back to non-file view when switching to a non-file type from a file type (via the sidebar)
2. The table wasn't sorting on properties, because the sort function tries to do `row[value]` but the properties were under `row.properties[value]`
3. The `return_to` if a user visited a page they needed to log in for wasn't taking account of dynamic paths (e.g. `/@[shortname]`
This PR:

H-2224, H-2239, H-2373: Bug fixes in entities table, redirect after signin

---

infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/hash_application/temporal_worker_integration.tf
infra/terraform/hash/hash_application/variables.tf
infra/terraform/hash/main.tf

Adds variables needed to connect to Vault to Terraform. Stops the integration worker crashing in AWS, because it expects them.
Worth flagging that the 'provide a token' approach is unlikely to be the desired authentication solution, instead relying on an IAM policy as outlined in #2837.
This PR:

H-2406: Add environment variables for connecting to vault to Terraform

---

Cargo.lock

Renovate does not update indirect dependencies.
This should be done automatically, either as a cron job or from renovate.

H-2414: Bump indirect Rust dependencies

---

apps/hashdotdesign/package.json
blocks/kanban-board/package.json
libs/@blockprotocol/graph/package.json
libs/@blockprotocol/type-system/typescript/package.json

We haven't merged the Version Packages PR for a while, and [we just did and it](https://github.com/hashintel/hash/actions/runs/8300661559/job/22719071158) (a) attempted to publish some apps that aren't on the registry, and (b) successfully published the copy of `@blockprotocol/graph` package we have in this repo as `latest`, that it shouldn't have.
This PR marks those packages as private to stop them being published again, and I am merging the [release PR](https://github.com/blockprotocol/blockprotocol/pull/1376#pullrequestreview-1939993506) in the `blockprotocol` PR so that we get another `latest` version of `@blockprotocol/graph` to override the one just published from here.

H-2417: Mark packages that shouldn't be published as private

---

blocks/chart/package.json
libs/@hashintel/design-system/package.json
yarn.lock

Fixes #4196 which is an [issue in ECharts](https://github.com/apache/echarts/issues/19233) caused by transitive dependency `zrender`, and has been fixed in the latest release.
This PR:
1. Install and use Node 21 (`nvm install 21` if you have nvm) 
2. run `yarn dev`
3. Visit http://localhost:3000
The app should crash without this upgrade and not crash with it.

H-2439: Upgrade ECharts to fix running app with Node 21

---

libs/@hashintel/block-design-system/package.json

`@hashintel/block-design-system` has a private local dependency which means publishing it to `npm` fails. We don't need it there for now.

H-2455: Make `@hashintel/block-design-system` private

---

package.json

This pins the package manager to `yarn@1` (done through `corepack use yarn@1`). This enables the use of `yarn 1` even on systems where an alternative yarn is installed, as long as `corepack` is active. `corepack` is a new package manager for package managers (the JS ecosystem sure is wild), and each package manager and node nowadays recommends managing the package manager of a repo.
> This is mostly done because I was frustrated w/ `yarn 4` (which I use in every other repo) and `yarn 1` (which is used in `hashintel/hash`) The `packageManager` field is ignored if `corepack` isn't used, although you really should!
- https://github.com/nodejs/corepack
This PR:

Pin `packageManager` to `yarn@1`

---

apps/hash-graph/bench/read_scaling/knowledge/complete/entity.rs
apps/hash-graph/bench/representative_read/seed.rs
apps/hash-graph/libs/api/src/rest/entity.rs
apps/hash-graph/libs/api/src/rest/utoipa_typedef/subgraph/vertices/vertex.rs
apps/hash-graph/libs/graph/src/knowledge/query.rs
apps/hash-graph/libs/graph/src/snapshot/entity/batch.rs
apps/hash-graph/libs/graph/src/snapshot/entity/channel.rs
apps/hash-graph/libs/graph/src/snapshot/entity/record.rs
apps/hash-graph/libs/graph/src/snapshot/entity/table.rs
apps/hash-graph/libs/graph/src/snapshot/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/query.rs
apps/hash-graph/libs/graph/src/store/postgres/query/entity.rs
apps/hash-graph/libs/graph/src/store/postgres/query/table.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/postgres_migrations/V22__entity_properties.sql
libs/@local/hash-graph-types/rust/src/knowledge/confidence.rs
libs/@local/hash-graph-types/rust/src/knowledge/entity.rs
libs/@local/hash-graph-types/rust/src/knowledge/link.rs
libs/@local/hash-graph-types/rust/src/knowledge/mod.rs
tests/hash-graph-integration/postgres/lib.rs

We want to support storing a confidence value for:
- the whole entity
- the every entity's properties
- the entity's link source and target (if the entity is a link)
This implements the datastore implementation to store all three kinds in the database and exposes the values to the REST API. This does not add support to specify the values (which will be addressed in a follow-up PR).
- #4202 
This PR:
- Allow specifying the confidence values when creating/updating an entity

H-2460: Support storing confidence values in Graph database

---

apps/hashdotai/guide/10_flows/00_index.mdx
apps/hashdotdev/next.config.js

Points to new open license home. Merge after [this PR](https://github.com/hashintel/internal-gitstart/pull/84).

H-2497: Update `HASH-O` license page redirect from HDEV

---

Cargo.lock
apps/hash-ai-worker-ts/src/activities/infer-entities/persist-entities/create-entities.ts
apps/hash-ai-worker-ts/src/activities/infer-entities/persist-entities/update-entities.ts
apps/hash-ai-worker-ts/src/activities/infer-entities/propose-entities.ts
apps/hash-graph/libs/api/src/rest/entity.rs
apps/hash-graph/libs/graph/src/snapshot/entity/batch.rs
apps/hash-graph/libs/graph/src/store/knowledge.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/friendship.http
libs/@local/hash-validation/src/data_type.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/lib.rs
libs/@local/hash-validation/src/property_type.rs

In some circumstances it's desired to only check the entity part, not the link part. This adds the support for this.
- Remove the `ValidationProfile`
- Adds a `ValidateEntityComponents` object which determines what components of an entity has to be validated. Currently, three components can be tweaked:
- `required_properties`: Check if all required properties are present
- `num_items`: Check if the number in arrays are correct
- `link_data`: Check links
By default (or when omitting the parameter) everything will be checked.
The previous `ValidateProfile::Draft` corresponds to `{ required_properties: false, num_items: false }`.
This PR:

H-2513: Allow validating an entity without checking linkData

---

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell/single-value-editor.tsx

This fixes some issues with editing entity properties when clicking from a cell being edited into another cell.
We're currently relying on native HTML input validation attributes (e.g. `type: "url"`, `minLength: 4`), triggering validation of the form when clicked outside of it, and preventing closing the form if it's invalid.
However, the click handler is not triggered when another grid cell is clicked. The form is unmounted immediately without validation being run. In order to force validation we need to somehow change `glide-data-grid`'s behavior to stop an open editor being closed when another cell is clicked based on some conditions. H-1834 tracks that.
In the meantime, this is an interim fix for existing issues (see demos):
1. Persists the value if the form has been unmounted. …

H-2451: Partially fix entity editor behavior when clicking between cells

---

Cargo.lock
apps/hash-ai-worker-ts/src/activities/flow-activities/get-file-from-url-action.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/persist-entity-action.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/persist-flow-activity.ts
apps/hash-ai-worker-ts/src/activities/infer-entities/persist-entities/update-entities.ts
apps/hash-ai-worker-ts/src/activities/parse-text-from-file.ts
apps/hash-api/src/graph/knowledge/primitive/entity.ts
apps/hash-api/src/graph/knowledge/primitive/link-entity.ts
apps/hash-graph/libs/api/src/rest/entity.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/friendship.http
apps/hash-integration-worker/src/linear-activities.ts
libs/@local/hash-graph-types/rust/src/knowledge/property/metadata.rs
libs/@local/hash-graph-types/rust/src/knowledge/property/path.rs

In structural queries, we use an array syntax of path elements into an object. To make it consistent and to avoid encoding/decoding JSON pointers, this syntax should be used for all property paths (e.g. property confidences, or PATCH operations)
- #4306 
This PR:

H-2503: Use arrays instead of JSON pointer for property paths

---

infra/terraform/hash/hash_application/kratos.tf

We're building the Kratos image from the `external-services` directory in CI and upload that to AWS, so we don't need to set a tag.

Revert "H-2534: Manually specify kratos version in Terraform"

---

.changeset/config.json
apps/hash-graph/libs/query-builder-derive/package.json

Mark rogue `@rust/` package as `private` and ignore `@rust/` packages in Changeset config.
This PR:
We'll know if it doesn't work because changeset will try and publish the package again. Not really worth testing locally.

H-2556: Don't try publishing Rust packages to `npm`

---

tests/hash-playwright/tests/types-page.spec.ts

There was a bug where entity types (including link types) weren't loading on the `/types` page. This has somehow disappeared since the ticket was filed, and I don't know what the underlying cause was.
This PR adds a test to confirm that at least some types load on the types page, which would have caught that bug. 
This PR:
- This one.
1. Check that the test passes. In order to check that it is testing the correct thing, you would have to run the app locally, hardcode 0 as a tab or types count (or empty array for types loaded into the page), and check that the test fails.

H-2502: Add test to check that types load on `/types` page

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types.ts
infra/terraform/hash/hash_application/api.tf
infra/terraform/hash/hash_application/temporal_worker_ai_ts.tf
infra/terraform/hash/prod-usea1.tfvars

Some changes to help debug what's going on in the Node API in AWS:
1. Add debug logs on the successful processing of each migration file
2. Set `LOG_LEVEL` to `debug`
3. Increase health check grace period
What we know so far is that the Node API is being killed without having completed all migration files. Theories as to what might be going on:
- Migrations are taking longer, and are causing the Node API to be considered unhealthy because it can't get through its startup work in time
- logs will help reveal this
- appropriate grace period will fix it 
- There's an issue in some migration file
- logs will help debug this 
This doesn't explain why the AI worker is also failing health checks.
This PR:
See what logs reveal

H-2586: Add debug logs to Node API, increase health check grace period

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util/upgrade-entities.ts
infra/terraform/hash/hash_application/api.tf
infra/terraform/hash/hash_application/main.tf

Further to #4371, it seems the issue with the Node API in production is that migrations are not completing before health checks are killing the service, because migrations that involve looking through entities in each web can take ~1 min to complete.
This PR attempts to fix that by:
1. Running checks/updates to entities in parallel in the migration so that migrations complete quicker 
2. Adding a grace period to the load balancer's health checks as well as the health checks in ECS
This PR:

H-2587: Parallelize entity migrations, add grace period for load balancer checks

---

.github/scripts/rust/sync-turborepo.rs
Cargo.lock
libs/@local/harpc/wire-protocol/package.json

This calls `cargo update --aggressive`, I first thought about just running `cargo update h2` and `cargo update rustls`, but thought it might make sense to update to the latest point releases either way.
An interesting observation is that `cargo update --workspace --aggressive` does something differently than `cargo update --aggressive`, which was unexpected.
As a drive-by (as that was discovered in #4283, `devDependencies` now never include `dependencies`.
- https://rustsec.org/advisories/RUSTSEC-2024-0336
- https://rustsec.org/advisories/RUSTSEC-2024-0332
This PR:

Bump Rust dependencies

---

apps/hashdotdev/src/pages/shared/mdx-utils.ts
apps/hashdotdev/src/util/mdx-util.ts

Allows the addition of `WIP_` blog posts to the `blogs` content folder in `hashdotdev` without these appearing on the site.

H-2597: Support `WIP_` blog posts on hash.dev

---

apps/hashdotai/guide/08_sharing/01_peers.mdx

Updates our public documentation around crosswalking in response to a question on Discord.
[Original question](https://discord.com/channels/840573247803097118/862336114597036042/1231691006160928788) in Discord [and the response](https://discord.com/channels/840573247803097118/862336114597036042/1235105069599555647).
The `/guide/sharing/peers` page ([current version](https://hash.ai/guide/sharing/peers)).

H-2609: Expand crosswalking section in docs

---

turbo.json

It's easy to miss the codegen step. For Node development this is unlikely to be an issue, but it is when the Rust code changed and `yarn dev` is required for testing.

H-2612: Make `dev` depend on `hash-graph-client#codegen`

---

apps/hash-graph/libs/api/src/rest/mod.rs

In the unlikely case that a non-existing endpoint is called we should at least show an error in the graph.

H-2614: Add a fallback handler for the Graph

---

libs/@local/harpc/wire-protocol/package.json
libs/@local/harpc/wire-protocol/src/codec/mod.rs
libs/@local/harpc/wire-protocol/src/codec/types.rs
libs/@local/harpc/wire-protocol/src/payload.rs
libs/@local/harpc/wire-protocol/src/protocol.rs
libs/@local/harpc/wire-protocol/src/request/begin.rs
libs/@local/harpc/wire-protocol/src/request/body.rs
libs/@local/harpc/wire-protocol/src/request/flags.rs
libs/@local/harpc/wire-protocol/src/request/frame.rs
libs/@local/harpc/wire-protocol/src/request/header.rs
libs/@local/harpc/wire-protocol/src/request/id.rs
libs/@local/harpc/wire-protocol/src/request/mod.rs
libs/@local/harpc/wire-protocol/src/request/procedure.rs
libs/@local/harpc/wire-protocol/src/request/service.rs
libs/@local/harpc/wire-protocol/src/response/begin.rs
libs/@local/harpc/wire-protocol/src/response/body.rs
libs/@local/harpc/wire-protocol/src/response/flags.rs
libs/@local/harpc/wire-protocol/src/response/frame.rs
libs/@local/harpc/wire-protocol/src/response/header.rs
libs/@local/harpc/wire-protocol/src/response/kind.rs
libs/@local/harpc/wire-protocol/src/response/mod.rs
rust-toolchain.toml

Memory layout is tricky and `miri` is able to detect errors here.
- Proptests are not working with `miri`

H-2613: Enable miri for HaRPC wireprotocol

---

apps/hash-graph/libs/graph/src/store/postgres/query/compile.rs
apps/hash-graph/libs/graph/src/store/postgres/query/condition.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/conditional.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/group_by_clause.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/join_clause.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/order_clause.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/select_clause.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/where_clause.rs
apps/hash-graph/libs/graph/src/store/postgres/query/expression/with_clause.rs
apps/hash-graph/libs/graph/src/store/postgres/query/rows.rs
apps/hash-graph/libs/graph/src/store/postgres/query/statement/insert.rs
apps/hash-graph/libs/graph/src/store/postgres/query/statement/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/query/statement/select.rs
apps/hash-graph/libs/graph/src/store/postgres/query/table.rs

In some functions we have "almost the same query" as many as 4x times. With a builder we can just generate the bits, rather than write it multiple times (and don't need to update it in multiple locations when changing, as well). 
In addition, this simplifies writing insert statements and makes them more safe.
- #4384 
- Implement `InsertStatement`
- Generalize parts of `SelectStatement` which are shared
This PR:

H-2219: Extend existing query builder to also support basic `INSERT` statements

---

Cargo.lock
libs/error-stack/Cargo.toml
libs/sarif/Cargo.toml

Renovate added the minor version and patch version to some public dependencies which is not expected. This reverts the dependencies.
- https://github.com/renovatebot/renovate/discussions/28782

GEN-156: Revert renovate PRs using wrong update behavior

---

.github/renovate.json

The behavior of `bump` changed. For most package managers, `bump` is the default but for `Rust` it is not, so this just removes the configuration to (hopefully) achieve the desired behavior.

H-2649: Fix renovate update behavior

---

apps/hash-graph/docker/Dockerfile

The `Cargo.lock` file is pruned by turborepo because it does not know that `Rust` is a thing. This bypasses `turborepo` and copies the file manually.

H-2651: Copy `Cargo.lock` before building Graph Docker image

---

apps/hash-graph/libs/graph/src/store/fetcher.rs
apps/hash-graph/libs/graph/src/store/knowledge.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/validation.rs
tests/hash-graph-integration/postgres/lib.rs

This allows validating a bunch of entities at the same time which results in reusing the store-cache.
- #4398 
- Adds a `validate_entities` function
- Default to `validate_entities` when calling `validate_entity`
This PR:

H-1451: Implement bulk validation for entities

---

apps/hash-frontend/package.json
apps/hashdotdev/package.json
libs/@local/hash-isomorphic-utils/package.json
yarn.lock

Major version bump shouldn't automerge, and this one has messed up WASM bundling somehow.
Note that vulnerability does not affect Vercel deployments.
```
⨯ Error: Cannot find module '@blockprotocol/type-system/type-system.wasm'
Require stack:
- /var/task/apps/hash-frontend/.next/server/chunks/2406.js
- /var/task/apps/hash-frontend/.next/server/webpack-runtime.js
- /var/task/apps/hash-frontend/.next/server/pages/_document.js
- /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js
- /var/task/apps/hash-frontend/___next_launcher.cjs
- /opt/rust/nodejs.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
at /var/task/node_modules/next/dist/compiled/next-server/server.runtime.prod.js:11:25300
```
Reverts hashintel/hash#4443

Revert "Update npm package `next` to v14 [SECURITY]"

---

apps/hash-ai-worker-ts/src/activities/shared/graph-api-client.ts
apps/hash-api/package.json
apps/hash-api/src/auth/ory-kratos.ts
apps/hash-api/src/ensure-system-graph-is-initialized.ts
apps/hash-api/src/generate-ontology-type-ids.ts
apps/hash-api/src/index.ts
apps/hash-api/src/integrations/sync-back-watcher.ts
apps/hash-api/src/telemetry/snowplow-setup.ts
libs/@local/hash-backend-utils/src/aws-config.ts
libs/@local/hash-backend-utils/src/temporal.ts
libs/@local/hash-isomorphic-utils/src/environment.ts
tests/hash-backend-integration/src/tests/util.ts

The migrations for the Node API are supposed to run in a dedicated service. This provides a script to run the migrations.
- Remove `getRequiredEnv` from isomorphic utils and use backend utils instead 
- Create script to run embeddings
This PR:
This is only one half of the work to build the API image and upload it to AWS. In the second PR, the changes to the infrastructure will be made.

H-2589: Provide separate script to migrate API

---

.github/workflows/bench.yml
turbo.json

A few issues in CI were found.
- Fix `if` statement in CI
- Fetch head branch before pull it
- Don't cache benchmarks (The results shown below don't have a diff because on main the results are cached)
This PR:

H-2684: Fix Bench CI on push to `main`

---

apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/infer-entities-from-web-page-worker-agent/tool-definitions.ts
apps/hash-ai-worker-ts/src/activities/infer-entities/propose-entities.ts
apps/hash-ai-worker-ts/src/activities/shared/get-llm-response.ts
apps/hash-ai-worker-ts/src/activities/shared/get-llm-response/types.ts
apps/hash-frontend/package.json
yarn.lock

This PR improves the `getLlmResponse` method to improve the handling of an edge case, where an LLM may make a correct and an incorrect tool call in the same request. Previously when using the OpenAI API, this would've lead to a single retry message in a tool call response for the incorrect tool use, and leave the correct tool call unanswered. This results in a `400` error, as some tool calls that the LLM agent made were not responded to.
This PR addresses this, by only including the incorrect tool calls when asking the LLM to retry them. This also reduces the input token consumption of the retry requests.
- H-2686
- H-2548 (resolves outstanding concern regarding "missed" tool calls, because we are now keeping track of all successful tool calls in consecutive retry requests)
- upgrades the …

H-2686, H-2548: Handle incorrect and correct tool calls made by an LLM in the same request in the getLlmResponse method

---

Cargo.lock
apps/hash-graph/bench/util.rs
libs/@local/repo-chores/rust/Cargo.toml
libs/@local/repo-chores/rust/bin/cli/subcommand/benches/analyze.rs
libs/@local/repo-chores/rust/bin/cli/subcommand/benches/mod.rs
libs/@local/repo-chores/rust/bin/cli/subcommand/benches/upload.rs
libs/@local/repo-chores/rust/src/benches/analyze/criterion.rs
libs/@local/repo-chores/rust/src/benches/analyze/mod.rs
libs/@local/repo-chores/rust/src/benches/analyze/tracing.rs
libs/@local/repo-chores/rust/src/benches/report.rs
libs/@local/repo-chores/rust/src/benches/storage.rs

The benchmark analyzer needs to be able to associate the generated artifacts from benchmarks with the benchmark results.
- #4464 
- #4469 
- Re-use algorithm from criterion to create artifact locations so we directly can use the `directory_name` of a measurement to read artifacts
- Read the `tracing.folded` content
This PR:

H-2702: Find corresponding tracing data when analyzing benchmarks

---

Cargo.lock
libs/@local/repo-chores/rust/Cargo.toml
libs/@local/repo-chores/rust/src/benches/analyze/tracing.rs

Duplication of #4471 
The output of the benchmarks is supposed to be used to create flame graphs. This PR allows converting a `FoldedStacks` to `FlameGraph`.
- #4464 
- #4469 
- #4470 
This PR:

H-2704: Allow creating flamegraphs from benchmark results

---

apps/hash-ai-worker-ts/src/activities/graph.ts
apps/hash-api/src/graph/ontology/primitive/data-type.ts
apps/hash-api/src/graph/ontology/primitive/entity-type.ts
apps/hash-api/src/graph/ontology/primitive/property-type.ts
apps/hash-graph/libs/api/src/rest/data_type.rs
apps/hash-graph/libs/api/src/rest/entity_type.rs
apps/hash-graph/libs/api/src/rest/mod.rs
apps/hash-graph/libs/api/src/rest/property_type.rs
apps/hash-graph/libs/graph/src/store/ontology.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/openapi/openapi.json
tests/hash-backend-integration/src/tests/subgraph/friendship.test.ts

Previously, we used a header as pagination parameters/response, this aligns the interface of ontology types to the entity interface.
This PR:

H-2164: Use same pagination/sorting approach for ontology types as for entities

---

.github/workflows/test.yml

We encounter a disk-storage error in PW tests as the docker images are too big. This temporarily disables the requirement to pass CI.

H-2731: Temporarily make Playwright tests not required

---

.github/workflows/lint.yml
.github/workflows/test.yml
.justfile

While attempting to fix tests for the latest Rust toolchain bump I noticed that the cargo tools are quite outdated (installing them locally doesn't work with the specified versions)

H-2733: Update cargo tools

---

Cargo.lock
Cargo.toml

Since a recent nightly toolchain version compiling crc32c fails to compile on ARM.
- https://github.com/zowens/crc32c/issues/62
- https://github.com/zowens/crc32c/issues/63
- Patch the dependency to the latest revision (two commits after the latest release) which fixed the issue
This PR:
- Revert this PR when a new version of `crc32c` was released

H-2742: Specify revision for crc32c crate

---

apps/hash-ai-worker-ts/src/activities/flow-activities/persist-entity-action.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/infer-entities-from-web-page-worker-agent.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/infer-entities-from-web-page-worker-agent/tool-definitions.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/infer-entities-from-web-page-worker-agent/types.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/get-file-entity-from-url.ts

When an entity creation or update has been generated as part of an AI process, we should use the appropriate machine actor to perform the operation. This PR does that.
This PR:

H-2618: Use the AI bot when persisting entities as appropriate

---

apps/hash-graph/bench/representative_read/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/store/fetcher.rs
apps/hash-graph/libs/graph/src/store/ontology.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/openapi/openapi.json
tests/hash-graph-integration/postgres/data_type.rs
tests/hash-graph-integration/postgres/entity_type.rs
tests/hash-graph-integration/postgres/lib.rs
tests/hash-graph-integration/postgres/property_type.rs

When returning paginated results for ontology types it should be possible to see the total number of ontologies.
- #4484
This PR:

H-2606: Support for `Counts` for ontology types

---

tests/hash-graph-integration/postgres/interconnected_graph.rs
tests/hash-graph-integration/postgres/lib.rs

Adds a test that an two linked entities can be created in one transaction.
This PR:

H-2538: Create test for creating a graph of interlinked entities in one transaction

---

apps/hash-graph/libs/api/src/rest/data_type.rs
apps/hash-graph/libs/api/src/rest/entity_type.rs
apps/hash-graph/libs/api/src/rest/property_type.rs
apps/hash-graph/libs/graph/src/snapshot/mod.rs
apps/hash-graph/libs/graph/src/snapshot/restore/channel.rs
apps/hash-graph/openapi/openapi.json
libs/@local/hash-graph-types/rust/src/ontology/provenance.rs

Relatively high-priority given its utility in the context of type inference.
- Add provenance fields for `actorType`, `sources`, and `origin` to ontology types
This PR:

H-2539: Add support in graph for Provenance Metadata for types

---

.github/renovate.json

We want to ensure we're always using the latest version of the LLM provider SDKs we rely on, without:
- waiting the normal 3 day period `npm` unpublishing safeguards would normally have us delay updating for
- having to manually trigger these to be updated via the repository's [dependency update dashboard](https://github.com/hashintel/hash/issues/3037).
Further rationale in this [chat thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1716322500100909) (_internal link_). To this end, we want PRs to be opened, _but not set to automerge_, so that their changelogs can be reviewed by a member of our team (and any relevant features taken advantage of) before merging in.
As well as supporting `@openai/` and `@anthropic/` npm namespaces, this PR pre-emptively adds handling for the …

H-2753: Update Renovate schedule for LLM provider SDKs

---

apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/infer-facts-from-text/infer-entity-facts-from-text.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/infer-facts-from-text/types.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/propose-entities-from-facts.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/propose-entities-from-facts/propose-entities-from-facts.ai.test.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/propose-entities-from-facts/propose-entity-from-facts.ai.test.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/propose-entities-from-facts/propose-entity-from-facts.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/011-deprecate-preferred-name.migration.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-page-wrapper/draft-entity-banner.tsx
apps/hash-frontend/src/shared/draft-entities-context.tsx

This PR updates the `proposeEntitiesFromFacts` method to require the LLM to specify which facts it used to determine the value of a top-level property, so that the relevant provenance information stored on the fact can be stored on a per-property basis.
- H-2743
- Changes the model used in `proposeEntitiesFromFacts` to `gpt-4o-2024-05-13`, because it is cheaper and faster than the prior `gpt-4-0125-preview`. This didn't introduce any noticeable regressions.
- Adds a `factId` to facts inferred from text.
This PR:
- currently the provenance data is only attached to the top-level properties for proposed entities/links. This could also be attached to nested properties (H-2755)
The easiest way of testing this is by inspecting the …

H-2743: Attach provenance information to properties on proposed entities

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util.ts

Fixes the migrations not accounting for self-hosted instances when entity types and property types are updated.
This PR:
- None yet (H-2716)
1. Update `.env.local`:
`SELF_HOSTED_HASH=true`
`HASH_GRAPH_ALLOWED_URL_DOMAIN_PATTERN` to not include hash.ai
2. Reset db
3. `yarn dev:graph` `yarn dev:backend:api`
4. Check migrations run through without error

H-2714: Fix upgrading types in migrations for self-hosted instances

---

libs/@local/hash-subgraph/src/types/element/knowledge.ts
libs/@local/hash-subgraph/src/types/shared.ts
libs/@local/hash-subgraph/tests/compatibility.test/map-vertices.ts

The fields are missing in the subgraph library, this makes them accessible.

H-2763: Add provenance data to subgraph library

---

apps/hash-graph/libs/api/src/rest/data_type.rs
apps/hash-graph/libs/api/src/rest/entity_type.rs
apps/hash-graph/libs/api/src/rest/property_type.rs

If unknown parameters are passed and are silently ignored the API behaves differently than expected.

H-2768: Prevent passing wrong parameters when loading external types

---

apps/hash-graph/libs/api/src/rest/entity_type.rs
apps/hash-graph/openapi/openapi.json

We use `camelCase` in the Node API

H-2766: Make `label_property` camelCase instead of snake_case

---

apps/hash-graph/openapi/openapi.json
libs/@local/hash-graph-types/rust/src/knowledge/entity/provenance.rs

We want to allow tracking the user agent for an origin

H-2764: Add optional `userAgent` string field to origin provenance

---

Cargo.lock
Cargo.toml

`crc32c` released a new version
- #4498 
- https://github.com/zowens/crc32c/pull/66

H-2745: Revert specifying revision for crc32c crate

---

apps/hash-ai-worker-ts/src/main.ts
infra/terraform/hash/hash_application/temporal_worker_ai_ts.tf

Add some debug logs to the AI Temporal worker to attempt to debug why it isn't connecting to the Temporal server.
I've also made the `startPeriod` on its health check consistent with the integration worker (which does connect). I've no idea why a _longer_ grace period would make a difference but it's one of the only differences I can find between the two workers.
I've also removed the custom logger in case this was causing an issue somehow.
This is more changes than are ideal at once, but it takes a while to deploy. If this fixes it I will start removing changes until it breaks (the `startPeriod` can be reverted in AWS directly at first, to test it).

H-2833: Add debug logs to Temporal worker

---

apps/hash-ai-worker-ts/scripts/bundle-workflow-code.ts
apps/hash-integration-worker/scripts/bundle-workflow-code.ts

When bundling workflow code for a Temporal worker, we need to specify any interceptors we are using when bundling the code.
I noticed this issue when looking at logs to debug a Temporal worker not connecting to the server in production, though I do not think it is related (it is just preventing Sentry from capturing errors which are thrown from workflows – it is definitely capturing errors thrown from activities).
```
[WARN] Ignoring WorkerOptions.interceptors.workflowModules because WorkerOptions.workflowBundle is set.
To use workflow interceptors with a workflowBundle, pass them in the call to bundleWorkflowCode.
```
This PR:

H-2834: Fix Sentry capturing errors from Temporal workflows

---

libs/@local/hash-backend-utils/src/hash-instance.ts

A continuation of PRs attempting to debug AWS deployment failures.
The API migration fails at the same function in different files – this PR adds some debug logs around the point it fails to further narrow down the issue (which is possibly due to concurrent request volume).

H-2842: Add debug logs around isUserHashInstanceAdmin

---

apps/hash-api/src/graph/knowledge/primitive/link-entity.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section/get-history-events.ts
libs/@local/hash-graph-sdk/typescript/package.json
libs/@local/hash-graph-sdk/typescript/src/entity.ts
libs/@local/hash-graph-types/typescript/src/entity.ts
libs/@local/hash-subgraph/tests/compatibility.test/map-vertices.ts

The internals of property metadata are not specified and should only be accessed via a method.
- Forbid direct access to `metadata.properties` and use `propertyMetadata()` instead
- Make some more `EntityMetadata` and `LinkData` fields internal 
- #4526 
This PR:

H-2793: Use method to access property metadata in TS

---

apps/hash-ai-worker-ts/src/activities/flow-activities.ts

The AI worker works with the removal of `writeGoogleSheetAction`, but it was still broken when built off #4561 when it was absent. So there must be other activities which also cause it to break.
This PR adds a couple back so we can find out the multiple activities that cause it to break, and look for the code they share to identify the issue.

Restore code to AI worker

---

apps/hash-ai-worker-ts/src/activities/flow-activities.ts

Further debugging – the reintroduction of `persistEntity` and `persistEntities` in #4572 broke the AI worker again so this PR restores `persistEntities`. If it starts working again the problem is in some code shared between `persistEntity` and `writeGoogleSheet`. 
I have a suspicion it is `getFlowContext` as it has side effects inside it (caching and creation of a Temporal client). `persistEntities` does not use it, so my next step if the AI worker builds off this PR is to change `getFlowContext` and restore `persistEntity` to see if removing the side effect fixes it.

Remove flow activity

---

Cargo.toml
apps/hash-graph/bins/cli/src/args.rs
libs/@local/tracing/src/logging.rs
libs/@local/tracing/src/opentelemetry.rs
libs/@local/tracing/src/sentry.rs

I was searching for a configuration in the `--help` command and especially the logging commands were pretty mixed. This put them into sections and also prints a more readable `--help` output.

H-2859: Improve `--help` output for CLI

---

apps/hash-ai-worker-ts/src/activities/flow-activities.ts

The theory in #4576 has been disproven. This PR removes `persistEntitiesAction` (the presence of which causes the AI worker not to start) and adds `getFileFromUrlAction` back in to see if it causes a crash.

restore a different flow activity

---

Cargo.lock
Cargo.toml
apps/hash-graph/libs/graph/Cargo.toml
apps/hash-graph/libs/graph/src/store/config.rs
apps/hash-graph/libs/graph/src/store/query/filter.rs
apps/hash-graph/libs/graph/src/subgraph/temporal_axes.rs
libs/@local/hash-authorization/Cargo.toml
libs/@local/temporal-versioning/Cargo.toml
libs/@local/temporal-versioning/src/temporal_bound.rs
libs/@local/temporal-versioning/src/timestamp.rs

`derive_where` generates more idiomatic code, is easier to write, and supports more features.

H-2880: Use `derive_where` instead of `derivative`

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util/upgrade-entities.ts

A lot migrations are running in parallel. To track down further the issue about the timeout we encounter, this avoids running the migrations in parallel.

H-2829: Don't run the migrations in parallel

---

apps/hash-api/src/graphql/resolvers/knowledge/user/submit-early-access-form.ts
apps/hash-frontend/src/pages/index.page/logged-out.tsx
infra/terraform/hash/main.tf

Notify Slack when the early access form is submitted (hosted HASH only).
Also fixes a couple of bugs:
1. In order that a returning user can see the form entity (and thus know they have already submitted it), the permission needs to be explicitly granted to the user to view, since they don't yet own the web
2. Fix copy
This PR:
1. Get the appropriate webhook URL from the "Notify HASH" app in our Slack workspace, set the environment variable, and submit the form.

H-2831: Add Slack notification on early access form submission

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util.ts
infra/terraform/hash/hash_application/api.tf
infra/terraform/hash/hash_application/hydra.tf
infra/terraform/hash/hash_application/kratos.tf
infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/prod-usea1.tfvars
libs/@local/hash-backend-utils/src/hash-instance.ts

When migrating, about 1000 requests are made at the same time. Until we figure out how to handle this gracefully, we don't migrate in parallel.
- For easier debugging, I moved the `kratos` and `hydra` tasks to a separate service
- Disable parallel migration
- Comment out logging for getting the HASH instance. It's a helpful output but very spammy.

H-2829: Fix deployment of backend in AWS

---

apps/hash-frontend/src/pages/shared/entity-type-page.tsx

When converting an entity to a link type, the `icon` and `labelProperty` are passed in the schema as well, this will let the graph return an error.
Drive-bys:
- Also pass `labelProperty` (it was not persisted before)
- Retain previous parent types (`allOf` was overwritten previously)

H-2878, H-2879: Fix entity type conversion to link type not working

---

apps/hash-api/src/graphql/resolvers/index.ts
apps/hash-api/src/graphql/resolvers/knowledge/hash-instance/hash-instance.ts
apps/hash-frontend/src/components/hooks/use-hash-instance.ts
apps/hash-frontend/src/graphql/queries/knowledge/hash-instance.queries.ts
apps/hash-frontend/src/pages/_app.page.tsx
apps/hash-frontend/src/pages/shared/auth-info-context.tsx
apps/hash-frontend/src/shared/layout/layout-with-sidebar/sidebar.tsx
libs/@local/hash-isomorphic-utils/src/graphql/type-defs/knowledge/hash-instance.typedef.ts

Fixes a few things related to viewing feature flagged pages:
1. The 'Goals' page should not be visible if the AI feature flag is not enabled, but the other Flows pages should. The 'Workers' link in the sidebar needing fixing to go to 'Flows' if the user didn't have AI enabled, rather than goals
2. Admins should bypass all feature flags, but admin status wasn't being checked server-side
3. In service of fixing (2), make it easier / quicker to check admin status
This PR:
1. Log in as `admin@example.com` and check that you can click on the 'Workers' link in the sidebar and it loads a page

H-2912: Fix loading Workers page, improve check for instance admin

---

apps/hash-ai-worker-ts/src/activities/shared/get-llm-response.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/014-add-instance-admin-permission.migration.ts
apps/hash-api/src/graph/knowledge/system-types/hash-instance.ts
apps/hash-api/src/graph/knowledge/system-types/user.ts
apps/hash-api/src/graphql/resolvers/knowledge/entity/entity.ts
apps/hash-api/src/graphql/resolvers/knowledge/user/submit-early-access-form.ts
apps/hash-graph/libs/api/src/rest/entity.rs
apps/hash-graph/openapi/openapi.json
libs/@local/hash-authorization/schemas/v1__initial_schema.zed
libs/@local/hash-authorization/src/schema/entity.rs
libs/@local/hash-backend-utils/src/service-usage.ts

Currently, we only allow account group members to have permissions on entities. This extends to the account group admins and makes specifying the subject set required.

H-2916: Allow org admins to have dedicated permissions

---

infra/terraform/hash/hash_application/api.tf
infra/terraform/hash/hash_application/hydra.tf
infra/terraform/hash/hash_application/kratos.tf
infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/prod-usea1.tfvars

This reverts commit 4106b12f988da86b23c9ef7128a8e6f079be8915 from #4590 as it is causing some issues in production – the API is timing out, seemingly related to issues with signin/signup.

H-2918: Revert "Move `kratos` and `hydra` tasks to separate service"

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/018-fix-incomplete-user-accounts.migration.ts
infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/main.tf

Fixes incomplete user accounts which were created during the period when registration could not be completed (fixed by #4613).
This PR:
The commit will be reverted once the migration is run.
1. Add a variable to your `.env.local`
`INCOMPLETE_USER_ACCOUNTS=[["some-uuid", "email@example.com"]]`
2. When running `yarn dev:backend:api` the user account should be created. It will not be able to login unless you have created a Kratos identity for it with `some-uuid` as the identity uuid

H-2920: Temporary migration to fix incomplete user accounts

---

.github/actions/prune-repository/action.yml

Since the latest runner image, the CI is failing because turbo is pruning Rust crates even though a workaround should re-add them. If Turborepo knew that Rust is a thing, this wouldn't even be needed.

H-2929: Fix CI failing due to Turborepo pruning Rust crates

---

.github/renovate.json

Reduces the frequency with which Renovate attempts to open PRs for GitHub Actions with available updates (following work previously done to limit `taiki-e/install-action` update frequencies.

H-2935: Reduce GHA update frequency

---

.github/workflows/deploy.yml
.github/workflows/test.yml
apps/hash-ai-worker-ts/docker/Dockerfile
apps/hash-frontend/vercel-build.sh
apps/hash-integration-worker/docker/Dockerfile
apps/hashdotdesign/vercel-build.sh
apps/hashdotdev/vercel-build.sh
infra/docker/api/prod/Dockerfile
package.json

The upgrade to Turbo 2 (#4584) broke https://app.hash.ai because it [enables environment variable strict mode](https://turbo.build/repo/docs/crafting-your-repository/using-environment-variables#strict-mode) by default, meaning that environment variables not defined in workspaces' `turbo.json` will not be provided to its `turbo` commands (rationale: cache can be invalidated when a value changes if turbo is aware of it).
This PR sets loose mode back, which is what we were implicitly using before, to get it working again.
This PR:
See what API the preview deployment attempts to contact.
- We should take advantage of strict mode – H-2936.

H-2761: Fix frontend environment variables

---

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section/history-table.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section/history-table/shared/chip.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section/history-table/shared/event-detail.tsx
apps/hash-frontend/src/shared/use-entity-type-entities.tsx

1. Fix a bug where a value used as an effect dependency wasn't memoized, causing a render loop in the entities table
2. Style tweaks to the entity history table:
a. allow chips to take up as much space as there is (rather than cutting all to `200`)
b. when history detail at the bottom of the table is opened, scroll it into view
This PR:
- The `entities-page.spec.ts` should've caught the console errors but Playwright tests are currently disabled pending another fix
1. View entities page, check no console errors
2. View history tab for an entity
https://github.com/hashintel/hash/assets/37743469/12f2293f-5027-4d38-bd6d-9211bf29f7c3

H-2940, H-2941: Fix entities table render loop, event history style tweaks

---

.github/workflows/bench.yml

The benchmarks are currently failing because environment variables are not passed to the commands in strict mode in turbo.
- Set the env-mode to `loose` for uploading results
This PR:

H-2946: Fix benchmark uploading from CI

---

apps/hash-graph/libs/api/src/lib.rs
apps/hash-graph/libs/api/src/rest/entity.rs
apps/hash-graph/libs/graph/src/store/knowledge.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/openapi/openapi.json
libs/@local/hash-graph-types/rust/src/knowledge/entity/mod.rs
libs/@local/hash-graph-types/rust/src/knowledge/mod.rs
libs/@local/hash-graph-types/rust/src/knowledge/property/mod.rs
libs/@local/hash-validation/src/data_type.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/error.rs
libs/@local/hash-validation/src/lib.rs
libs/@local/hash-validation/src/property_type.rs
tests/hash-graph-benches/read_scaling/knowledge/complete/entity.rs
tests/hash-graph-benches/read_scaling/knowledge/linkless/entity.rs
tests/hash-graph-benches/representative_read/seed.rs
tests/hash-graph-integration/postgres/drafts.rs
tests/hash-graph-integration/postgres/entity.rs
tests/hash-graph-integration/postgres/interconnected_graph.rs
tests/hash-graph-integration/postgres/links.rs
tests/hash-graph-integration/postgres/multi_type.rs
tests/hash-graph-integration/postgres/partial_updates.rs
tests/hash-graph-integration/postgres/property_metadata.rs
tests/hash-graph-integration/postgres/sorting.rs

The layout of the property metadata needs to correspond to the properties in the entity. This adds a function to visit all nodes in metadata and executes a callback. In the validation code the callback is used to validate the path of a metadata.
This PR:

H-2799: Validate existence of properties for metadata

---

apps/hash-graph/libs/api/src/rest/entity.rs
apps/hash-graph/libs/graph/src/store/fetcher.rs
apps/hash-graph/libs/graph/src/store/knowledge.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/circular-links.http
apps/hash-graph/tests/friendship.http
libs/@local/hash-graph-sdk/typescript/package.json
libs/@local/hash-graph-sdk/typescript/src/entity.ts
libs/@local/hash-graph-types/rust/src/knowledge/property/mod.rs
tests/hash-graph-benches/read_scaling/knowledge/complete/entity.rs
tests/hash-graph-benches/read_scaling/knowledge/linkless/entity.rs
tests/hash-graph-benches/representative_read/seed.rs
tests/hash-graph-integration/postgres/drafts.rs
tests/hash-graph-integration/postgres/entity.rs
tests/hash-graph-integration/postgres/interconnected_graph.rs
tests/hash-graph-integration/postgres/lib.rs
tests/hash-graph-integration/postgres/links.rs
tests/hash-graph-integration/postgres/multi_type.rs
tests/hash-graph-integration/postgres/partial_updates.rs
tests/hash-graph-integration/postgres/property_metadata.rs

We expect to pass the metadata alongside the properties, but for now we will use them in the SDK as two separate objects. The Graph already constructs an entity, so a traversal in the Node API can be avoided.
Further, it is expected that the Graph will be capable of using hooks, which might change some properties. As the SDK does not necessarily know what properties have been changed, it's good to inform it.
- #4589 
- Change the return type of `createEntity` and `createEntities` to return the full entities instead of only the metadata
This PR:

H-2947: Return full entity from Graph on creation

---

apps/hash/README.md
libs/antsi/rust-toolchain.toml
libs/deer/rust-toolchain.toml
libs/error-stack/README.md
libs/error-stack/macros/README.md
libs/error-stack/rust-toolchain.toml
libs/error-stack/src/lib.rs
libs/sarif/rust-toolchain.toml
rust-toolchain.toml

There was a regression in the latest nightly toolchain, which is fixed.
- https://github.com/rust-lang/rust/issues/126887

H-2969: Bump Rust toolchain to `nightly-2024-06-25`

---

apps/hash-graph/tests/friendship.http
libs/@local/hash-graph-types/rust/src/knowledge/property/mod.rs
libs/@local/hash-validation/src/data_type.rs
libs/@local/hash-validation/src/property_type.rs

The specified data type needs to:
- match the actual data
- be allowed on the entity

H-2801: Validate data type in entity property metadata

---

tests/hash-backend-integration/src/tests/graph/knowledge/primitive/entity.test.ts
tests/hash-backend-integration/src/tests/graph/knowledge/system-types/comment-notification.test.ts
tests/hash-backend-integration/src/tests/graph/knowledge/system-types/org-membership.test.ts
tests/hash-backend-integration/src/tests/graph/knowledge/system-types/org.test.ts
tests/hash-backend-integration/src/tests/graph/knowledge/system-types/user.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/data-type.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/entity-type.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/property-type.test.ts
tests/hash-backend-integration/src/tests/util.ts

The BE integration tests run the migration scripts 3-4 times on average. Migrations takes up the majority of time in testing, so reducing the amount of migrations to 1 per test will speed up testing by 3x-4x
- Remove calling migration script when inserting test orgs/users On average
This PR:

Speed up backend integration tests

---

apps/hash-ai-worker-ts/src/activities/flow-activities/shared/graph-requests.ts
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/friendship.http
libs/@local/hash-graph-sdk/typescript/src/entity.ts
libs/@local/hash-graph-types/rust/src/knowledge/entity/mod.rs
libs/@local/hash-graph-types/rust/src/knowledge/property/patch.rs
libs/@local/hash-graph-types/typescript/src/entity.ts
tests/hash-graph-integration/postgres/drafts.rs
tests/hash-graph-integration/postgres/entity.rs
tests/hash-graph-integration/postgres/partial_updates.rs
tests/hash-graph-integration/postgres/property_metadata.rs

Initially, this was planned after H-2927 but as some operations do a create-or-update operation it makes sense to allow passing the metadata in a compound object when patching entities.
- #4630 
- Change API to require `property: PropertyWithMetadata` instead of `value` and `metadata`
- Abstract this away in the Graph SDK
This PR:

H-2953: Pass metadata alongside properties to Graph in patches

---

apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer.tsx
apps/hash-frontend/src/pages/goals/new.page.tsx
apps/hash-frontend/src/pages/shared/flow-definitions-context.tsx
libs/@local/hash-isomorphic-utils/src/flows/goal-flow-definitions.ts
libs/@local/hash-isomorphic-utils/src/flows/goal-flow-definitions/google-sheets.ts
libs/@local/hash-isomorphic-utils/src/flows/goal-flow-definitions/markdown-report.ts

Handles the case where a Goal-driven flow is set up where the user selects both (a) to write to Google Sheets and (b) produce a Markdown-formatted report.
This PR:
This 'manually define a fixed flow per deliverable combination' will not scale with more deliverables. The longer-term solution is to start persisting Flow definitions in the database, and generate them dynamically as needed.
- None yet.
1. Start a Flow with both spreadsheet and report selected

H-2939: Handle both spreadsheet and report being chosen as deliverables 

---

tests/hash-graph-integration/postgres/partial_updates.rs

To ensure that an `add` operation on an existing property behaves like a `replace` function a test case is added

H-3043: Add test case to check add operation for existing property

---

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section/get-history-events.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section/history-table.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section/history-table/shared/event-detail.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section/shared/types.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/shared/update-entity-subgraph-state-by-entity.ts
libs/@local/hash-subgraph/src/types/shared/branded.ts

In the history section of the entity editor, show rows for when:
1. A type is added, removed or upgraded on the entity
2. Draft status is changed from false to true or from true to false
Also fixes a couple of bugs related to ApolloClient state now being immutable (as it should be, but has caused errors to be thrown where we do mutate it).
This PR:
The history do not filter out drafts which may be irrelevant to the history being viewed, either because they are new drafts of a live entity being viewed which shouldn't be in its own history, or because multiple drafts in the past were created and only one was selected to be turned into the live entity – to be addressed in H-3030, H-3031.
1. Make relevant changes, look at the history …

H-2774: Show type and draft status change in entity history tab

---

libs/@local/hash-graph-types/rust/src/knowledge/entity/provenance.rs

When the origin type is set to `flow` it fails to deserialize, this is not intended.
This PR:
Sadly, we have to remove `deny_unknown_fields` for this as this is not working with `flatten`.

H-3057: Fix `originType == "flow"` failing to deserialize

---

apps/hash-frontend/turbo.json

The output of the build command of the frontend is probably a big part of the cache. We disable the caching of that command and see how slow the CI might become.

H-3061: Disable caching for building frontend

---

Cargo.lock
libs/error-stack/CHANGELOG.md
libs/error-stack/src/context.rs
libs/error-stack/src/report.rs
libs/error-stack/src/result.rs
libs/error-stack/tests/test_conversion.rs

It's desired that source errors of `Error` are printed as part of a `Report` as well.
- Closes #2127
- Adds a hidden `__source` method to `Context` to close the gap between `Context` and `Error`. This allows using `Error::source` without specialization.
- Add contexts for sources returned from `Error::source` to the `Report` when creating it
This PR:

GEN-68: Capture source errors when converting `Error` to `Report`

---

Cargo.lock
libs/@blockprotocol/type-system/rust/src/ontology/shared/array/raw.rs

We removed the attribute to remove the `ordered` field. The production DB was adjusted, so we can re-add the attribute.

H-3058: Add `deny_unknown_field` to `ArraySchema`

---

libs/error-stack/.justfile
libs/error-stack/CHANGELOG.md
libs/error-stack/Cargo.toml
libs/error-stack/build.rs
libs/error-stack/src/fmt/hook.rs
libs/error-stack/src/lib.rs
libs/error-stack/src/report.rs
libs/error-stack/tests/common.rs
libs/error-stack/tests/snapshots/test_debug__full__complex.snap
libs/error-stack/tests/snapshots/test_debug__full__hook_provider.snap
libs/error-stack/tests/snapshots/test_debug__full__linear.snap
libs/error-stack/tests/snapshots/test_debug__full__linear_ext.snap
libs/error-stack/tests/snapshots/test_debug__full__multiline_context.snap
libs/error-stack/tests/snapshots/test_debug__full__sources.snap
libs/error-stack/tests/snapshots/test_debug__full__sources_transparent.snap
libs/error-stack/tests/snapshots/test_debug__sources_nested@spantrace.snap
libs/error-stack/tests/snapshots/test_debug__sources_nested_alternate@spantrace.snap
libs/error-stack/tests/test_backtrace.rs
libs/error-stack/tests/test_compatibility.rs
libs/error-stack/tests/test_debug.rs

In some contexts, such as with `panic_immediate_abort` set, backtraces should not be compiled into the binary. Currently, the `std` feature determines if backtraces are enabled or not. Making this a dedicated feature flag helps reduce the binary size.
- Closes https://github.com/hashintel/hash/issues/3353
- Guard `Backtrace` behind the `backtrace` feature

GEN-115: Don't compile backtrace support if feature is disabled

---

.github/renovate.json

We currently encounter a lot of timeouts in Renovate. This should help mitigating the issue.
- #3037 
- https://docs.renovatebot.com/configuration-options/#maxretryafter

H-3068: Set rate max retry duration for Renovate

---

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell/inputs/number-or-text-input.tsx

Currently, only `1` is added/substracted from the minimum/maximum. This does not take into account `type === "number"` so this will fix this by using the `step` here.
- #4688 
- #4689

H-3073: Use `multipleOf` to determine exclusive min/max in data type validation

---

.github/renovate.json

In the renovate logs there are several “Reached branch limit - skipping branch creation” messages. This sets the maximum amount of branches to unlimited  as we have a few branches lying around all the time. Also, it explicitly sets the PR limit.

H-3078: Set concurrent limits for branches and PRs for renovate

---

Cargo.lock
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util/upgrade-entities.ts
apps/hash-graph/libs/api/src/rest/test_server.rs
apps/hash-graph/libs/graph/Cargo.toml
apps/hash-graph/libs/graph/src/snapshot/mod.rs
apps/hash-graph/libs/graph/src/store/config.rs
apps/hash-graph/libs/graph/src/store/postgres/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/pool.rs
tests/hash-graph-benches/util.rs
tests/hash-graph-integration/postgres/lib.rs

We encountered quite a few timeouts with `bb8` and `deadpool` seems to run more stable. This changes the pool implementation, so we can try out `deadpool`.
- change postgres pool from `bb8` to `deadpool`
- Minor fix in migration script to avoid error in Graph API
This PR:

H-2886: Change postgres pool from `bb8` to `deadpool`

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util/upgrade-entities.ts

Migrating the Graph in parallel currently crashes AWS. Until we found out the exact reason we change it to run it sequentially again.
Reviewing should happen without whitespace, then this only changes 6 lines.

H-3099: Run migrations sequentially instead of in parallel

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util/upgrade-entities.ts

For some reason, in AWS the migration script doesn't find `{ isEqual }` in `lodash`

H-3105: Fix `lodash/isEqual` issue

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util.ts
libs/@blockprotocol/graph/src/codegen/initialize/metadata/generate-metadata-schema.ts
libs/@blockprotocol/graph/src/codegen/initialize/traverse-and-collate-schemas.ts
libs/@local/hash-isomorphic-utils/src/system-types/canvas.ts
libs/@local/hash-isomorphic-utils/src/system-types/commentnotification.ts
libs/@local/hash-isomorphic-utils/src/system-types/document.ts
libs/@local/hash-isomorphic-utils/src/system-types/docxdocument.ts
libs/@local/hash-isomorphic-utils/src/system-types/facebookaccount.ts
libs/@local/hash-isomorphic-utils/src/system-types/githubaccount.ts
libs/@local/hash-isomorphic-utils/src/system-types/google/googlesheetsfile.ts
libs/@local/hash-isomorphic-utils/src/system-types/google/shared.ts
libs/@local/hash-isomorphic-utils/src/system-types/graphchangenotification.ts
libs/@local/hash-isomorphic-utils/src/system-types/instagramaccount.ts
libs/@local/hash-isomorphic-utils/src/system-types/linear/attachment.ts
libs/@local/hash-isomorphic-utils/src/system-types/linear/shared.ts
libs/@local/hash-isomorphic-utils/src/system-types/linearintegration.ts
libs/@local/hash-isomorphic-utils/src/system-types/linkedinaccount.ts
libs/@local/hash-isomorphic-utils/src/system-types/machine.ts
libs/@local/hash-isomorphic-utils/src/system-types/mentionnotification.ts
libs/@local/hash-isomorphic-utils/src/system-types/pdfdocument.ts
libs/@local/hash-isomorphic-utils/src/system-types/pptxpresentation.ts
libs/@local/hash-isomorphic-utils/src/system-types/quicknote.ts
libs/@local/hash-isomorphic-utils/src/system-types/shared.ts
libs/@local/hash-isomorphic-utils/src/system-types/spreadsheetfile.ts
libs/@local/hash-isomorphic-utils/src/system-types/tiktokaccount.ts
libs/@local/hash-isomorphic-utils/src/system-types/twitteraccount.ts
libs/@local/hash-isomorphic-utils/src/system-types/usagerecord.ts

#4650 introduced new `PropertiesWithMetadata` types to support passing metadata along with properties, but didn't take account of inheritance for entities.
This PR fixes that.
This PR:
- `tsc`
1. Look at the changes in the generated types

H-3106: Account for inheritance when generating `properties-with-metadata`

---

apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/channel.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/postgres_migrations/V27__closed_data_types_2.sql
libs/@blockprotocol/type-system/rust/src/schema/data_type/closed.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/raw.rs
libs/@local/harpc/tower/package.json

The new closed schema has the same shape as DataType but with the references being replaced by the full schema - recursively.
- Add an `allOf` value to `DataType`
- Change the `ClosedDataType` to align with `DataType`
- drive-by: Fix `package.json` for `@rust/harpc-tower`
This PR:

H-3120: Add a `ClosedDataType` schema based on the normal `DataType` schema

---

apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/handle-web-search-tool-call.ts
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/activity-log.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/flow-run-sidebar.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/flow-run-sidebar/manager.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/flow-run-sidebar/manager/resolved-questions-modal.tsx
apps/hash-frontend/src/pages/shared/virtualized-table.tsx
libs/@local/harpc/tower/package.json
libs/@local/hash-isomorphic-utils/src/flows/types.ts

A few improvements to flow run visualization:
1. Show the original research prompt in a toggle
2. Show resolved Q&A
3. Hide the date on activity log entries from today, show date in tooltip
This PR:
**Goal prompt toggle**
https://github.com/user-attachments/assets/0d7cf983-8a97-4393-96ab-50f55ab7089f
**Resolved questions, activity log date**
https://github.com/user-attachments/assets/1b33a045-70f4-432c-af4f-32731dbc018c

H-3084, H-3115, H-3116: Show prompt, resolved questions for flow run

---

apps/hashdotdev/vercel-install.sh
libs/@blockprotocol/type-system/rust/package.json
yarn.lock

For some reason, hashdotdev doesn't find `wasm-pack` anymore.
- Install `wasm-pack` from `yarn` and not from `cargo`
- Drive-by: Bump version to `0.13.0`
This PR:

H-3133: Fix `hashdotdev` deployment

---

apps/hash-api/src/index.ts

There's a loop in the Node API which checks for Redis messages related to changes to Linear-related entities, to write them back out to Linear.
If the Linear integration is not enabled this loop should not start.
- ...
This PR:

H-2773: Don't start sync back watcher if Linear integration disabled

---

.github/licenses/LICENSE-HASH.md
apps/hash-ai-worker-ts/LICENSE.md
libs/@local/internal-api-client/typescript/LICENSE.md

Updates the version of the HASH license found in the repository.

H-3155: Update HASH license from `1.1` to `1.2`

---

infra/terraform/hash/hash_application/api.tf

The TF file was forgotten to be updated. With this the migration should run again on AWS.

H-3168: Fix API migration on AWS

---

tests/hash-backend-performance/scenarios/login.yml

Most queries require a logged in user
- #4756 
- #4752 
Add a simple scenario to
- login
- query `me`
This PR:

H-3164: Add artillery scenario to login and query `me`

---

tests/hash-backend-performance/artillery.yml
tests/hash-backend-performance/package.json
tests/hash-backend-performance/rollup.config.ts
tests/hash-backend-performance/scenarios/login.yml
tests/hash-backend-performance/src/graph.ts
tests/hash-backend-performance/src/session.ts

Reading the owned-by-id from a subgraph is not trivial (and probably not possible using JsonPath).
- Allows hooks to connect to the graph directly
- Reads the user entity after login
- stores the user properties and the owned-by-id in the session
- asserts, that the `me` query returns the correct entity
- changes rollup to emit an ESM module instead of CJS
This PR:

H-3180: Read user entity after logging in

---

tests/hash-backend-performance/package.json
tests/hash-backend-performance/scenarios/ontology-read.yml
tests/hash-backend-performance/scenarios/read-data-types.yml
tests/hash-backend-performance/scenarios/read-entity-types-entity-refs.yml
tests/hash-backend-performance/scenarios/read-entity-types-parents.yml
tests/hash-backend-performance/scenarios/read-entity-types-property-entity-refs.yml
tests/hash-backend-performance/scenarios/read-entity-types-value-property-entity-refs.yml
tests/hash-backend-performance/scenarios/read-entity-types.yml
tests/hash-backend-performance/scenarios/read-property-types-property-refs.yml
tests/hash-backend-performance/scenarios/read-property-types-value-property-refs.yml
tests/hash-backend-performance/scenarios/read-property-types.yml

We want load tests for ontology type loading
- Create load tests for ontology types with different resolve depths
- Output reports as JSON when running load tests and avoid terminal output
- **Drive-by**: Add expect-test for existing tests
This PR:

H-3175: Implement load tests for type-loading

---

apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/coordinating-agent.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/handle-web-search-tool-call.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/link-follower-agent.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/link-follower-agent/link-follower-agent.ai.test.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/sub-task-agent.ai.test.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/sub-task-agent.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/propose-entities-from-claims.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/propose-entities-from-claims/propose-entities-from-claims.ai.test.ts
apps/hash-ai-worker-ts/src/activities/infer-entities/propose-entities.ts
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/activity-log.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/flow-run-sidebar/group-status.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/shared/format-time-taken.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/shared/types.ts
apps/hash-frontend/src/pages/shared/virtualized-table.tsx
libs/@local/hash-isomorphic-utils/src/flows/types.ts

This PR improves flow logging by:
- Adding an identifier for a worker (and its parent) to activity logs
- Adding new logs for the starting and closing of worker tasks (e.g. sub-task, link explorer)
- Adds the ability to display logs grouped by worker in the flow run UI
Actions taken by the research coordinator appear at the top level, with any activity by workers it spawns grouped in a toggleable list (see demo).
This PR:
- None yet
1. Run a flow, see logs
https://github.com/user-attachments/assets/938c5e2a-3fa3-4910-82db-b413fa9ff66a

H-3181: Add identifiers for workers in flows, group activity log by worker

---

libs/@local/hql/cst/package.json

So `changesets` doesn't attempt to publish it.

H-3199: Set @rust/hql-cst package private

---

patches/@artilleryio+int-commons+2.9.0.patch
tests/hash-backend-performance/package.json
tests/hash-backend-performance/rollup.config.ts
tests/hash-backend-performance/scenarios/flow.yml
tests/hash-backend-performance/src/session.ts
tests/hash-backend-performance/src/types.ts
yarn.lock

Flows run asynchronously, so to observe specific behavior and load-test the API we need to kimic some flows.
- Patch artillery library to correctly use JSON: https://github.com/artilleryio/artillery/issues/879#issuecomment-2260331103
- Add a `flow` scenario which simply creates two entities 10 times (one at the graph, one at GraphQL) - this is not a real flow behavior, but at least it's creating entities
- Adjust session code to properly detect expiration dates
- Remove unneeded/outdated type-dependency
This PR:

H-3166: Mimic Flow behavior in artillery

---

.changeset/config.json

`error-stack` and `deer` are now prepended with `@rust`

H-3211: Fix ignore in changeset configuration

---

.github/workflows/bench.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.justfile

One of our CI steps failed as it wasn't able to install `clippy-sarif`, which was a quite outdated version. Typically, they are prebuilt but if that download fails they are built instead. The newest version should pass building.

H-3214: Update Rust pipeline tools

---

apps/hash-graph/libs/api/src/rest/data_type.rs
apps/hash-graph/libs/graph/src/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/property_type.rs
apps/hash-graph/libs/graph/src/store/postgres/query/compile.rs
apps/hash-graph/libs/graph/src/store/postgres/query/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/traversal_context.rs
apps/hash-graph/libs/graph/src/store/query/filter.rs
apps/hash-graph/openapi/openapi.json
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/validation.rs
tests/hash-graph-integration/postgres/data_type.rs
tests/hash-graph-integration/postgres/lib.rs
tests/hash-graph-test-data/rust/src/data_type/centimeter.json
tests/hash-graph-test-data/rust/src/data_type/length.json
tests/hash-graph-test-data/rust/src/data_type/meter.json
tests/hash-graph-test-data/rust/src/data_type/mod.rs

We need to query for
- parent types if we resolve data types on creation
- children when we validate the types
- In most areas replace `OntologyId` with `DataTypeId`/`PropertyTypeId`/`EntityTypeId`. The latter are newtype wrapper, but they provide more safety.
- Add a data type query path for inheritance
- Add a predefined filter to
- read parents of data types (depending on the depth, multi in/multi out)
- read children of a data type (depending on the depth, single in, multi out) 
This PR:
A few test cases were added

H-2962: Allow querying inheritance for data types

---

apps/hash-graph/bins/cli/package.json
apps/hash-graph/libs/api/package.json
apps/hash-graph/libs/graph/package.json
apps/hash-graph/libs/query-builder-derive/package.json
apps/hash-graph/libs/test-server/package.json
apps/hash-graph/libs/type-fetcher/package.json
libs/@local/codec/package.json
libs/@local/harpc/net/package.json
libs/@local/harpc/tower/package.json
libs/@local/harpc/types/package.json
libs/@local/harpc/wire-protocol/package.json
libs/@local/hash-authorization/package.json
libs/@local/hash-graph-types/rust/package.json
libs/@local/hash-validation/package.json
libs/@local/hql/cst/package.json
libs/@local/hql/diagnostics/package.json
libs/@local/hql/span/package.json
libs/@local/repo-chores/rust/package.json
libs/@local/temporal-client/package.json
libs/@local/temporal-versioning/package.json
libs/@local/tracing/package.json
libs/error-stack/Cargo.toml
libs/error-stack/package.json
tests/hash-graph-benches/package.json
tests/hash-graph-integration/package.json
tests/hash-graph-test-data/rust/package.json

We only publish it through `cargo`. Also, this ran the scnc-script again and added somemissing licenes to `package.json`.

H-3230: Ignore error-stack for turborepo-sync script

---

.github/scripts/rust/sync-turborepo.rs
.github/workflows/lint.yml
libs/error-stack/Cargo.toml

To avoid inconsistencies between `package.json` and `Cargo.toml` we enfore this in CI now.

H-3234: Enfore synced Turborepo in CI

---

.github/renovate.json

Improves our Renovate update process.

H-3235: Group various Renovate updates, exclude `tldraw`

---

apps/hash-graph/libs/graph/src/store/postgres/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
tests/hash-graph-integration/postgres/data_type.rs

When creating a new data type the order should not matter if they depend on each other.
- Split `inserst_data_type_with_id` into `inserst_data_type_with_id` and `insert_data_type_references`
- Collect references instead of inserting them directly
- insert references after everything else is inserted
- Drive-by: Use `DataTypeId` instead of `OntologyId`
This PR:

H-3222: Make sure data types inheriting from each other can be passed in arbitrary order when creating at the same time

---

apps/hash-graph/libs/graph/src/store/validation.rs
libs/@local/hash-validation/src/data_type.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/lib.rs
libs/@local/hash-validation/src/property_type.rs
tests/hash-graph-integration/postgres/data_type.rs
tests/hash-graph-test-data/rust/src/entity_type/line.json
tests/hash-graph-test-data/rust/src/entity_type/mod.rs
tests/hash-graph-test-data/rust/src/property_type/length.json
tests/hash-graph-test-data/rust/src/property_type/mod.rs

Depending on the data type the validation needs to behave differently.
We require these checks:
- If the data type ID is provided:
- Validate the value against that data type ID
- Check if the data type ID is an exact match:
- validation passed ✅ 
- Check if it’s a child (is the expected base URL one of the parent's base URL of the provided type?):
- Validate the value against the expected type
- If the data type ID is not provided
- Fail, if expected type has children 🛑 
- In `oneOf` this counts as a potential candidate, so if only one other data type passes the validation this will still be ambiguous
- Validate the value against the expected type
This PR:
The test case for inheritance has been adjusted by attempting to create entities.

H-3229: Validate data type IDs over inheritance

---

apps/hash-graph/bins/cli/src/subcommand/snapshot.rs
apps/hash-graph/libs/graph/src/snapshot/mod.rs

Snapshot dumping is very slow when relationships has to be read. Sometimes, the relationships are not needed, so we should provide a way to skip them.
- To the `snapshot dump` command it adds:
- `--no-webs`
- `--no-accounts`
- `--no-accout-grous`
- `--no-entities`
- `--no-entity-types`
- `--no-property-types`
- `--no-data-types`
- `--no-embeddings`
- `--no-relations`
- To the `snapshot restore` command it adds:
- `--skip-authorization`
This PR:

H-3238: Provide a way to dump a snapshot without authorization relationships

---

Cargo.lock
libs/@local/hql/diagnostics/examples/jexpr.rs
libs/@local/hql/diagnostics/src/diagnostic.rs
libs/@local/hql/diagnostics/src/label.rs
libs/@local/hql/span/Cargo.toml
libs/@local/hql/span/src/storage.rs

Using `orx-concurrent-vec` `SpanStorage` is now able to have `insert(&self)`, this simplifies carrying around the storage to various parts.
To increase the benefits, the internal vector has been wrapped in `Arc`, allowing for the cloning of the storage. This is especially useful to reduce lifetimes around parsing code.
Additional as a drive-by diagnostics now only add color if requested.
The full history of the branch can be seen in `bm/hql/cst-preserve`, which will be deleted once this stack of PRs is resolved.
This PR:

H-3239: HQL: Make span storage insertion non mutable

---

apps/hash-graph/libs/api/src/rest/data_type.rs

The API package currently panics as soon as a data type schema contains a non-empty allOf field.
- https://github.com/hashintel/hash/pull/4804
- https://github.com/hashintel/hash/pull/4814
- https://github.com/hashintel/hash/pull/4818
Nice-to-have but not needed
- H-3159: Resolve closed data types when loading snapshots
- H-3082: Allow querying of closed data schema (resolving works without it)
Allows usage of `allOf` outside of the graph
This PR:

H-3221: Enable data type inheritance in Graph API

---

apps/hash-frontend/src/components/grid/grid.tsx
apps/hash-frontend/src/components/grid/utils/sorting.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section/history-table/shared/event-detail.tsx
apps/hash-frontend/src/pages/shared/entities-table.tsx
apps/hash-frontend/src/pages/shared/entities-table/text-icon-cell.tsx
apps/hash-frontend/src/pages/shared/entities-table/use-entities-table.tsx
apps/hash-frontend/src/pages/types/[[...type-kind]].page/types-table.tsx

The following UX improvements on the entities and type tables:
- Hide the `archived` column when viewing **pages** and 'include archived' is not selected
- Hide the `archived` column when viewing **types** and 'include archived' is not selected
- Add `createdBy`/`created` columns to the entities table
- Add `lastEditedBy`/`lastEdited` columns to the types table
- On the entities table, show the entity in a slideover when the entity's name is clicked
- On the entities table, show the type of entity in a slideover when the type is clicked
- On the types table, show entity types in a slideover when clicked
- Rename 'namespace' to 'web' on the entities table
- On the entities and types tables, allow clicking the web to go to its profile
Bug fixes:
- Fix sorting by `lastEditedBy` on the …

H-3252: Entity and types table UI improvements, bug fixes

---

apps/hash-ai-worker-ts/docker/Dockerfile
apps/hash-graph/docker/Dockerfile
apps/hash-integration-worker/docker/Dockerfile
infra/docker/api/prod/Dockerfile

On [`f6d1a69` (#4892)](https://github.com/hashintel/hash/pull/4892/commits/f6d1a69fa00ddfc4211e12d393c7a6c71029d2fa#diff-abe64b7e17a62a627bc3288e2f6663b0401d814fdc940c2569e13860dff728ca) I noticed a few warnings, this adresses the concerns.

H-3274: Prevent Dockerfile warnings emitted from GitHub

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/006-create-first-custom-data-types.migration.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/012-create-google-sheets-system-types.migration.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/016-add-initial-currency-data-types.dev.migration.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util.ts
apps/hash-api/src/graph/ontology/primitive/data-type.ts
apps/hash-graph/libs/api/src/rest/data_type.rs
apps/hash-graph/libs/graph/src/snapshot/mod.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/batch.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/channel.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/mod.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/record.rs
apps/hash-graph/libs/graph/src/snapshot/restore/channel.rs
apps/hash-graph/libs/graph/src/store/fetcher.rs
apps/hash-graph/libs/graph/src/store/ontology.rs
apps/hash-graph/libs/graph/src/store/postgres/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/query/rows.rs
apps/hash-graph/libs/graph/src/store/postgres/query/table.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/postgres_migrations/V28__data_type_conversions.sql
apps/hash-graph/tests/ambiguous.http
apps/hash-graph/tests/friendship.http
libs/@blockprotocol/type-system/rust/src/schema/data_type/conversion.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/mod.rs
tests/hash-backend-integration/src/tests/graph/ontology/primitive/data-type.test.ts
tests/hash-graph-benches/util.rs
tests/hash-graph-integration/postgres/data_type.rs
tests/hash-graph-integration/postgres/lib.rs

Conversions are supposed to be stored in the database. A conversion currently is always required to be a canonical version. The format is similar to the syntax introduced in #4828:
```typescript
type ConversionValue = Variable | { const: number; type: "number" } | ConversionExpression;
type Operator = "+" | "-" | "*" | "/";
type ConversionExpression = [Operator, ConversionValue, ConversionValue];
interface ConversionDefinition {
expression: ConversionExpression;
}
interface Conversions {
from: ConversionDefinition;
to: ConversionDefinition;
}
```
e.g.
```typescript
{
from: { 
expression: ["/", "self", { const: 1000, type: "number" }]
},
to: { 
expression: ["*", "self", { const: 1000, type: "number" }]
},
}
```
- Define conversion format
- Add conversions to database when …

H-2963, H-3292: Allow storing of data type conversion definitions

---

apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/checkpoints.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/research-entities-action/coordinating-agent.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/infer-summaries-then-claims-from-text/infer-entity-claims-from-text-agent.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/history-section/history-table.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/activity-log.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/dag-slide.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/outputs.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/outputs/claims-table.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/outputs/entity-result-table.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/outputs/entity-result-table/cells.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/outputs/shared/output-container.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/outputs/shared/table-skeleton.tsx
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/topbar.tsx
apps/hash-frontend/src/pages/flows.page.tsx
apps/hash-frontend/src/pages/shared/virtualized-table.tsx
apps/hash-frontend/src/pages/shared/virtualized-table/header.tsx
apps/hash-frontend/src/pages/shared/virtualized-table/header/filter.tsx
apps/hash-frontend/src/pages/shared/virtualized-table/header/sort.tsx
apps/hash-frontend/src/pages/shared/virtualized-table/use-filter-state.tsx
apps/hash-frontend/src/pages/workers.page.tsx
apps/hash-frontend/src/shared/icons/filter-light-icon.tsx
libs/@local/hash-isomorphic-utils/src/flows/action-definitions.ts
libs/@local/hash-subgraph/src/stdlib.ts
libs/@local/hash-subgraph/src/stdlib/subgraph/element/link-type.ts
libs/@local/hash-subgraph/src/stdlib/subgraph/element/property-type.ts

Introduce the following UX improvements to the tables in the flow run output tables:
1. Adds filters to the columns for the entities and claims tables
2. Adds loading state to the entities and claims tables
3. Show links as chips in the source entity's row, not individual rows
4. Adds a 'Relevance' column to the entities table, column allowing filtering discovered entities by which the AI has reported as most relevant to the research job
5. Move the 'graph / table' display switcher next to the 'Entities' table button
6. Fix breadcrumbs on Goals pages
7. Only show one output table at a time
This PR:
Further testing of inference, improvements to agent behavior.
- None yet.
1. Run a flow locally.

H-3276: Flow run output tables UX improvements

---

.github/renovate.json

Ensures `@ory`-published npm packages will be treated as an update group by Renovate.

H-3299: Group Ory npm packages in Renovate

---

Cargo.lock
Cargo.toml
apps/hash-graph/bins/cli/Cargo.toml
apps/hash-graph/bins/cli/package.json
apps/hash-graph/libs/api/Cargo.toml
apps/hash-graph/libs/api/package.json
apps/hash-graph/libs/graph/Cargo.toml
apps/hash-graph/libs/graph/package.json
apps/hash-graph/libs/query-builder-derive/Cargo.toml
apps/hash-graph/libs/type-fetcher/Cargo.toml
libs/@local/hash-authorization/Cargo.toml
libs/@local/hash-authorization/package.json
libs/@local/hash-graph-types/rust/Cargo.toml
libs/@local/hash-validation/Cargo.toml
libs/@local/hql/span/Cargo.toml
libs/@local/hql/syntax-jexpr/Cargo.toml
libs/@local/status/rust/Cargo.toml
libs/error-stack/Cargo.toml
libs/error-stack/macros/Cargo.toml
tests/hash-graph-benches/Cargo.toml
tests/hash-graph-integration/Cargo.toml

I have not found a way to properly check this automatically, but cargo-machete does a decent jobs after some manual tweaks (it does not support Rust 2024 and has a lot of false positives, however, it detected quite a few unused dependencies)

H-3301: Remove unused Rust dependencies

---

.config/husky/post-checkout
.config/husky/post-merge
.config/husky/post-rewrite
.github/CONTRIBUTING.md
apps/hash/README.md
package.json

This PR adds a git hook (via [husky](https://github.com/typicode/husky)) to install `yarn` dependencies after changing branches, merging branches, or rebasing. 
The motivation for this is to avoid occasional small amounts of time lost to issues which are caused by not installing dependencies when moving between branches.
Because this is a polyglot monorepo, and running `yarn` on checkout etc is more intrusive than existing `pre-commit` git hooks, this PR also moves the git hooks to _opt in_ via `yarn install:hooks`, and documents this in the HASH `README.md`.
This PR:
1. Checkout the branch, check that `yarn` runs automatically

H-3271: Add `yarn install` hook post-checkout/merge, make hooks opt-in

---

apps/hash-ai-worker-ts/src/activities/flow-activities/infer-entities-from-content-action.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/shared/propose-entities-from-claims/propose-entity-from-claims-agent.ts
apps/hash-frontend/src/pages/[shortname]/shared/flow-visualizer/outputs/entity-result-table.tsx
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/ambiguous.http
libs/@local/hash-graph-sdk/typescript/src/entity.ts
libs/@local/hash-graph-types/rust/src/knowledge/property/metadata/value.rs
libs/@local/hash-graph-types/typescript/src/entity.ts

Instead of omitting the data type ID if unknown should pass `null` so the graph can distinguish between values which are shaped as properties and values.

H-3308: Pass `null` for `dataTypeId` if not known

---

.github/actions/install-rust-toolchain/action.yml
.github/renovate.json
.github/workflows/auto-approve.yml
.github/workflows/renovate.yml

With renovate being self-hosted it's possible to use a nightly version of Cargo which is required to properly generate artifacts. The hosted instance of renovate does not (and probably never will!) support nightly toolchains.
Further, we are in full control of the invocations and have access to self-hosted configurations.
- Add a workflow to run renovate every 30 min and on manual dispatch
- The flow will authenticate with Vault and use the stored credentials for the [HASH worker bot](https://github.com/apps/hash-worker)
- It installs Rust (the toolchain specified in `rust-toolchain.toml` and node)
- Runs renovate
- Stores the renovate cache (quite small) as GH artifact. In the future we might want to use S3 for that
- Add an auto-approval bot for dependencies. It will run if (and only …

GEN-51: Run Renovate through GitHub Actions

---

apps/hash-graph/libs/api/src/rest/entity.rs
apps/hash-graph/libs/api/src/rest/entity_type.rs
apps/hash-graph/libs/graph/src/store/fetcher.rs
apps/hash-graph/libs/graph/src/store/knowledge.rs
apps/hash-graph/libs/graph/src/store/ontology.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/openapi/openapi.json
tests/hash-graph-benches/read_scaling/knowledge/complete/entity.rs
tests/hash-graph-benches/read_scaling/knowledge/linkless/entity.rs
tests/hash-graph-benches/representative_read/knowledge/entity.rs
tests/hash-graph-benches/representative_read/ontology/entity_type.rs
tests/hash-graph-integration/postgres/entity.rs
tests/hash-graph-integration/postgres/entity_type.rs
tests/hash-graph-integration/postgres/links.rs
tests/hash-graph-integration/postgres/multi_type.rs
tests/hash-graph-integration/postgres/partial_updates.rs
tests/hash-graph-integration/postgres/sorting.rs

When requested, a set (+ count) of all possible values should be returned independent of pagination.
Allow specifying a set of distinct values (+ count) for:
- `web` (only entities and owned types)
- `createdById` (only entities, we currently don't store the initial creator of a type)
- `editionCreatedById` (corresponds to `updatedById`)
- `types` (only entities)
This PR:

H-3285, H-3286: Optionally return set of distinct values for entity (type) queries

---

apps/hash-graph/libs/api/src/rest/entity.rs
apps/hash-graph/libs/graph/src/knowledge/query.rs
apps/hash-graph/libs/graph/src/store/postgres/query/compile.rs
apps/hash-graph/libs/graph/src/store/postgres/query/entity.rs
apps/hash-graph/libs/graph/src/store/postgres/query/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/query/table.rs
apps/hash-graph/openapi/openapi.json
apps/hash-graph/tests/friendship.http

We want to allow sorting entities by e.g. it's type's title, so we can sort by
- label
- type title
- entity ID
- Add sorting paths for the above
- Add logic to dynamically use `label` property (returns `null` if not present)
This PR:

H-3284, H-3287: Allow sorting Entities by entity type's properties

---

.github/renovate.json
Cargo.lock
Cargo.toml
libs/sarif/src/schema/log.rs

The `Cargo.lock` does not fully match the `Cargo.toml` because it may use later versions. This also helps with the issue renovate has to open Rust PRs

H-3317: Change dependencies to be precise in Rust

---

Cargo.lock
Cargo.toml
libs/error-stack/Cargo.toml
libs/error-stack/experimental/Cargo.toml
libs/error-stack/experimental/LICENSE.md
libs/error-stack/experimental/README.md
libs/error-stack/experimental/package.json
libs/error-stack/experimental/src/lib.rs

This crates the `error-stack-experimental` crate, which is to be used to test out new features or traits that aren't ready yet for the main `error-stack` crate.
The first set of traits that are going to be exposed in `error-stack-experimental` are going to be utility traits to make working with collections of related errors easier.
This PR:

GEN-194: Create `error-stack-experimental` crate

---

apps/hash-graph/libs/api/openapi/openapi.json
apps/hash-graph/libs/graph/postgres_migrations/V30__data_type_conversion_aggrecation.sql
apps/hash-graph/libs/graph/src/ontology/data_type.rs
apps/hash-graph/libs/graph/src/snapshot/mod.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/channel.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/mod.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/record.rs
apps/hash-graph/libs/graph/src/snapshot/restore/channel.rs
apps/hash-graph/libs/graph/src/store/postgres/crud.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/query/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/query/table.rs
libs/@local/hash-graph-types/rust/src/ontology/data_type.rs

To display conversions defined on data types they should be queryable (i.e. returned as part of a data type query). Also, it's required to know the possible conversions when storing canonical values.
- Add a view to aggregate conversions
- Add internal query paths to query into the table
- Adjust snapshot logic to use new queries
- Add conversions to data type metadata
This PR:

H-3290: Return conversions as part of data type queries

---

apps/hash-graph/libs/api/openapi/openapi.json
apps/hash-graph/libs/graph/src/knowledge/query.rs
libs/@local/hash-graph-types/rust/src/knowledge/property/metadata/value.rs
libs/@local/hash-validation/src/entity_type.rs
tests/hash-graph-integration/postgres/property_metadata.rs

To sort by "real" units we need to sort by a canonical value stored in the database.
We only store canonical values for values which are not already in canonical form. When sorting by canonical form we also want to take the values into account which don’t need a conversions. This means we either
- need a special filter for canonical values. This requires to:
- add a query path which is aware of the expected canonical type (e.g. `meters`) and the path to the value (needs to be distinguished)
- Create a postgres statement `CASE X THEN A ELSE B` with:
- `X`: check existence of `value path -> data_type_id == expected type` with `value_path` being calulated as the path for `properties` and `property_metadata` differs (we have these `value`s in between)
- `A`: `properties->value path`
- `B`: …

H-3279: Allow sorting by property metadata

---

apps/hash-graph/libs/api/openapi/models/data_type.json
apps/hash-graph/libs/api/openapi/models/update_data_type.json
apps/hash-graph/libs/api/src/rest/json_schemas/data_type.json
apps/hash-graph/libs/api/src/rest/json_schemas/update_data_type.json
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/array.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/boolean.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/error.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/null.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/number.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/object.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/string.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs
libs/@hashintel/type-editor/src/shared/data-types-options-context.tsx
libs/@local/hash-validation/src/entity_type.rs

To enable a `Value` data type it's required that a data type may have multiple possible types.
- Make `type` a `HashSet` but (de-)serialize from/to a string if only a single element is provided
- Require, that in the case of an array at least one item is specified
This PR:
Add the `Value` data type

H-3325: Support array in data type's type field

---

libs/@local/hash-graph-types/rust/src/knowledge/property/visitor.rs
libs/@local/hash-validation/src/entity_type.rs
tests/hash-graph-http/tests/ambiguous.http

Currently, we only validate the constraints on the same data type but not the parents.
- Add the validation for the `allOf` field in data types
This PR:

H-3331: Validate all data type constraints

---

Cargo.lock
libs/error-stack/experimental/Cargo.toml
libs/error-stack/experimental/build.rs
libs/error-stack/experimental/package.json
libs/error-stack/experimental/src/iter.rs
libs/error-stack/experimental/src/lib.rs
libs/error-stack/experimental/src/result.rs
libs/error-stack/experimental/src/stream.rs
libs/error-stack/experimental/src/tuple.rs
libs/error-stack/src/report.rs

This implements an experimental set of traits to be used to collecting reports in a fail slow manner these include:
* `TryReportIteratorExt`
* `ResultMultiExt` (I don't like that name at all)
* `TryReportTupleExt`
* `TryReportStreamExt` (gated behind the `stream` flag)
This PR:

Introduce experimental/unstable extension traits

---

apps/hash-graph/libs/api/openapi/openapi.json
apps/hash-graph/libs/api/src/rest/data_type.rs
apps/hash-graph/libs/api/src/rest/entity_type.rs
apps/hash-graph/libs/api/src/rest/property_type.rs
apps/hash-graph/libs/graph/src/store/crud.rs
apps/hash-graph/libs/graph/src/store/ontology.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/query.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/property_type.rs

The Subgraph code restricts the VertexIdSorting logic to be locked to the vertices in the graph. To sort ontologies this is not required, we can sort by versioned URL in general. For entities, we don't use that sorting anyway.
- Removes `VertexIdSorting` for Entities
- Change `VertexIdSorting` to `VersionedUrlSorting` for ontologies
This PR:

H-3334: Stop depending on subgraph when sorting by ontology IDs

---

apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/array.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/string.rs
libs/@local/hash-graph-types/rust/src/knowledge/property/visitor.rs
libs/@local/hash-validation/src/entity_type.rs
libs/deer/json/src/array.rs
libs/deer/json/src/deserializer.rs
libs/deer/json/src/object.rs
libs/deer/src/impls/core/array.rs
libs/deer/src/impls/core/ops.rs
libs/deer/tests/test_bound.rs
libs/deer/tests/test_enum_visitor.rs
libs/deer/tests/test_struct_visitor.rs
libs/error-stack/src/lib.rs
libs/error-stack/src/macros.rs
libs/error-stack/src/report.rs
libs/error-stack/src/sink.rs

Implements suggestions from #5181, this needed to be done in another PR, as I didn't want to redo the work done in #5200, which moves the workspace to the new `error-stack` version.
This is mostly just renames, moving around of methods and documentation improvements.
Open Question:
* Do we want to default to `Panic` for `ReportSink`?
This PR:

GEN-196: Apply suggestions from #5181

---

.github/dependabot.yml

We still use Dependabot for certain kinds of security-related package updates. We want to stop Dependabot adding labels we don't use (e.g. `javascript` and `dependencies`) when it opens these PRs.
Our existing labeler configuration (`labeler.yml`) will correctly pick up the labels we use that should be added to PRs opened by Dependabot (e.g. `area/deps`)
See [`labels` in the Dependabot docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels).

GEN-198: Add Dependabot config file

---

package.json

The command was moved but the root package.json was not updated.
The new location is `@rust/graph-http-tests` instead of `@apps/hash-graph`

H-3361: Fix `yarn graph:reset-database` command

---

apps/hash-graph/libs/graph/src/store/validation.rs
apps/hash-graph/libs/store/src/filter/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs
libs/@local/hash-graph-types/rust/src/knowledge/property/visitor.rs
libs/@local/hash-graph-types/rust/src/lib.rs
libs/@local/hash-graph-types/rust/src/ontology/mod.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/lib.rs
tests/hash-graph-http/tests/ambiguous.http
tests/hash-graph-test-data/rust/src/data_type/boolean.json
tests/hash-graph-test-data/rust/src/data_type/centimeter_v1.json
tests/hash-graph-test-data/rust/src/data_type/centimeter_v2.json
tests/hash-graph-test-data/rust/src/data_type/empty_list.json
tests/hash-graph-test-data/rust/src/data_type/length.json
tests/hash-graph-test-data/rust/src/data_type/meter.json
tests/hash-graph-test-data/rust/src/data_type/null.json
tests/hash-graph-test-data/rust/src/data_type/number.json
tests/hash-graph-test-data/rust/src/data_type/object_v1.json
tests/hash-graph-test-data/rust/src/data_type/object_v2.json
tests/hash-graph-test-data/rust/src/data_type/text.json

Some data types (such as `length`) should not be instantiated directly. For these, the `abstract` flag is useful.

H-3356: Add abstract flag for data types

---

.github/dependabot.yml

We use Renovate for non-security updates, so don't need Dependabot trying to do it's own thang here, too.
See the docs around `open-pull-requests-limit: 0` [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit).

GEN-199: Stop Dependabot opening non-security updates

---

apps/hash-graph/libs/api/Cargo.toml
libs/error-stack/Cargo.toml
libs/error-stack/build.rs
libs/error-stack/src/sink.rs

The warnings on the terminal are annoying and cannot easily be silenced. This adds a `tracing` feature to `error-stack` to use `tracing` instead of `eprintln!`. Also, the message alone was kind-of pointless without a location, so on a `Warn`-level it will capture the caller location as well.
Example output:
```
`ReportSink` was dropped without being consumed at /<...>/hash/libs/@local/hash-graph-types/rust/src/knowledge/property/visitor.rs:452:22
```

H-3372: Use logger to print error-stack warnings

---

apps/hash-ai-worker-ts/src/activities/flow-activities/persist-entities-action.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util.ts
apps/hash-frontend/src/pages/shared/entities-table.tsx
apps/hash-frontend/src/pages/shared/graph-visualizer/graph-container/graph-data-loader.tsx
apps/hash-frontend/src/pages/shared/type-graph-visualizer.tsx
apps/hash-frontend/src/pages/types/[[...type-kind]].page/types-table.tsx
apps/hash-frontend/src/shared/table-header.tsx

This PR introduces support for visualizing type graphs where links link to other links. 
It also makes a couple of other improvements to the types page:
1. Respect the applied filters when loading the graph visualization (previously they were only applied to the table)
2. Add code to allow for filtering to types in a specific web (not yet exposed in the UI)
This PR:

H-3362: Support links which link to other links in the types graph visualization

---

libs/error-stack/src/sink.rs

The caller is currently not tracked, this defeats the purpose of capturing the location.

H-3377: Track caller when using ReportSink

---

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell/array-editor/sortable-row.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell/single-value-editor.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell/utils.ts
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/use-create-get-cell-content.ts
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/any_of.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/array.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/boolean.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/null.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/number.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/object.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/string.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/mod.rs
libs/@hashintel/type-editor/src/shared/data-types-options-context.tsx
libs/@local/hash-isomorphic-utils/src/data-types.ts
libs/@local/hash-subgraph/src/stdlib/subgraph/element/property-type.ts
tests/hash-graph-test-data/rust/src/data_type/value.json

To allow a `Value` type we need the type system to support `anyOf` instead of specifying a `type` for data types.
- Support `anyOf` in the type system
- Add a test for `Value`
- Add proper validation logic for `anyOf` (future-proof so in theory any type could use `anyOf`)
- Add missing documentation for validations
This PR:

H-2958: Support `anyOf` in type system

---

apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/batch.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/closed.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs

After running the migration script to introduce Value and re-inserting the data using snapshots, ~50% of the data types don’t have the correct parents set in the database even though the schema is correct.
- Instead of attempting to resolve all types at once (and fail on that due to incomplete schemas), the new approach only resolves one at a time. This also requires to add the schema to be resolved in advance.
This PR:

H-3375: Overhaul logic to detect inheritance depths for data types

---

apps/hash-graph/libs/graph/src/store/validation.rs
apps/hash-graph/libs/store/src/filter/mod.rs
libs/@local/hash-graph-types/rust/src/ontology/mod.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/lib.rs

With inheritance being used for data types, it's likely that data types are ambiguous. As long as we don't always pass the data type ID we should take abstract into account when inferring the ID to get the best possible behavior.
- When checking for parents when inferring data type IDs take into account `abstract` parents
This PR:

H-3376: Infer data type IDs if only abstract parents exists

---

Cargo.lock
apps/hash-graph/bins/cli/Cargo.toml
apps/hash-graph/bins/cli/package.json
apps/hash-graph/bins/cli/src/main.rs
apps/hash-graph/libs/graph/src/store/validation.rs
apps/hash-graph/libs/store/src/filter/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/any_of.rs
libs/@local/hash-graph-types/rust/src/knowledge/property/error.rs
libs/@local/hash-graph-types/rust/src/knowledge/property/mod.rs
libs/@local/hash-graph-types/rust/src/knowledge/property/visitor.rs
libs/@local/hash-graph-types/rust/src/ontology/mod.rs
libs/@local/hash-validation/src/entity_type.rs
libs/@local/hash-validation/src/lib.rs

We want to infer the data type if the schema is requesting exactly one possible data type and it's not abstract. Also, the errors reported from validation should include more information on what property/data type has failed to validate.
- Lift constraints on data type inference:
- All potential data type IDs must be non-abstract
- Exactly one data type ID needs to be allowed for a property
This should cover almost every scenario we currently encounter
- Improve error layout and attachments on validation errors
- A few more locations make sure that the `ReportSink`-bomb is defused.
This PR:

H-3380, H-3381: Improve error handling and data type ID inference

---

apps/hash-graph/bins/cli/src/subcommand/mod.rs
apps/hash-graph/bins/cli/src/subcommand/reindex_cache.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/batch.rs
apps/hash-graph/libs/graph/src/store/fetcher.rs
apps/hash-graph/libs/graph/src/store/ontology.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs
tests/hash-graph-integration/postgres/lib.rs

We change data type inheritence in quite a few PRs currently and to avoid running snapshot migrations for everything it's easier to run a command from the CLI. The functionality was borrowed from snapshots, which has to do the same functionality, but this PR also exposes the functionality to the CLI:
```
cargo run --bin hash-graph -- reindex-cache --data-types
```

H-3385: Allow updating the data type cache in the database

---

apps/hash-graph/libs/api/src/rest/data_type.rs
apps/hash-graph/libs/api/src/rest/entity_type.rs
apps/hash-graph/libs/api/src/rest/property_type.rs
apps/hash-graph/libs/api/src/rest/status.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/data_type.rs

This uses the `report_to_response` function in more places. The function tries to infer the status code and prints the error to the terminal.

H-3389: Return better status codes for data type and property type API

---

libs/@blockprotocol/type-system/rust/src/schema/data_type/validation.rs
tests/hash-graph-http/tests/friendship.http

Every type should currently inherit from a primitive type, not from `Value` directly. This adds a validation step for this.

H-3382: Ensure only primitive types can inherit from `Value`

---

tests/hash-graph-integration/turbo.json

The integration tests do not pick up changes properly, Turbo will use the cache instead. For more details see the linked [thread slack](https://hashintel.slack.com/archives/C02TWBTT3ED/p1727945579768759).
- Add `codegen` to the dependencies to the integration tests to create a virtual pipeline
This PR:

H-2981: Fix `turbo` config to account for changes in type system

---

Cargo.lock
apps/hash-graph/libs/api/src/rest/mod.rs
apps/hash-graph/libs/graph/Cargo.toml
apps/hash-graph/libs/graph/src/snapshot/entity/batch.rs
apps/hash-graph/libs/graph/src/snapshot/mod.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/data_type/batch.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/entity_type/batch.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/metadata/batch.rs
apps/hash-graph/libs/graph/src/snapshot/ontology/property_type/batch.rs
apps/hash-graph/libs/graph/src/snapshot/owner/batch.rs
apps/hash-graph/libs/graph/src/snapshot/restore/batch.rs
apps/hash-graph/libs/graph/src/snapshot/web/batch.rs
apps/hash-graph/libs/graph/src/store/crud.rs
apps/hash-graph/libs/graph/src/store/fetcher.rs
apps/hash-graph/libs/graph/src/store/migration.rs
apps/hash-graph/libs/graph/src/store/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/crud.rs
apps/hash-graph/libs/graph/src/store/postgres/knowledge/entity/mod.rs
apps/hash-graph/libs/graph/src/store/postgres/migration.rs

It's not needed anymore (except to implement third-party crates for `axum`)
- Remove `#[async_trait]` for all define traits

H-721: Remove `async-trait` dependency

---

.cargo/config.toml
.github/actions/install-rust-toolchain/action.yml
.justfile
Cargo.toml
apps/hash-ai-worker-ts/docker/Dockerfile
apps/hash-graph/docker/Dockerfile
apps/hash-integration-worker/docker/Dockerfile
infra/docker/api/prod/Dockerfile
infra/docker/frontend/prod/Dockerfile
libs/antsi/rust-toolchain.toml
libs/deer/rust-toolchain.toml
libs/error-stack/.justfile
libs/error-stack/rust-toolchain.toml
libs/sarif/rust-toolchain.toml
rust-toolchain.toml

Using `cranelift` as backend potentially speeds up compilation for dev builds. This is good.
- https://github.com/rust-lang/rustc_codegen_cranelift

H-3412: Enable `cranelift` codegen backend

---

Cargo.lock
libs/@local/harpc/net/Cargo.toml
libs/@local/harpc/net/src/session/server/mod.rs
libs/@local/harpc/server/Cargo.toml
libs/@local/harpc/server/examples/account.rs
libs/@local/harpc/server/src/router.rs
libs/@local/harpc/server/src/session.rs

This adds an ergonomic way to spawn and create the background task that's required to operate without leaking memory.
Primarily it makes the use of `tokio::sync::broadcast` an implementation detail, thought that might make sense, as the user shouldn't care what we use under the hood. It's just a stream of events.
This PR:

H-3432: `harpc`: Expose background task

---

Cargo.lock
libs/@local/harpc/codec/Cargo.toml
libs/@local/harpc/codec/src/json.rs
libs/@local/harpc/net/Cargo.toml
libs/@local/harpc/net/src/session/server/mod.rs
libs/@local/harpc/server/Cargo.toml
libs/@local/harpc/server/examples/account.rs
libs/@local/harpc/server/src/router.rs
libs/@local/harpc/server/src/session.rs
libs/@local/harpc/tower/Cargo.toml
libs/@local/harpc/tower/src/body/encode_error.rs
libs/@local/harpc/tower/src/body/encode_report.rs
libs/@local/harpc/tower/src/body/mod.rs
libs/@local/harpc/tower/src/body/size_hint.rs
libs/@local/harpc/tower/src/either.rs
libs/@local/harpc/tower/src/layer/body_error.rs
libs/@local/harpc/tower/src/layer/body_report.rs
libs/@local/harpc/tower/src/layer/error.rs
libs/@local/harpc/tower/src/layer/mod.rs
libs/@local/harpc/tower/src/lib.rs
libs/@local/harpc/tower/src/test.rs

This enables the handling of `Body` errors through two new layers (and combinators) `HandleBodyError` and `HandleReportError`, they work pretty much the same by turning any error on the `Body` layer into `!` if required.
That allows us to remove the `ResponseBodyError` and have it be guaranteed to be `!`, this then enables a further PR that allows for boxed routers (if necessary).
This has been made possible through our change in the `Codec`.
> an open question is how to handle underlying stream errors when encoding. I'd like to layer them, but that requires a trait bound I am unsure about working out. I have other idea though that might work instead! (in another PR as to not make these too large)
> `JsonErrorRepr` is going to be hoisted up in the other PR as well, I think it's generally …

H-3433: `harpc`: Encode `Body` errors

---

libs/@blockprotocol/type-system/rust/src/schema/data_type/closed.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/any_of.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/array.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/boolean.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/null.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/number.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/object.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/string.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/mod.rs
libs/@local/hash-validation/src/entity_type.rs

When data types are resolved the constraints should be folded and minimized. This is the groundwork and logic to be used when combining different constraints.
- It's not a good idea to implement `combine` on `Constraint` as `Constraint` is generic and `combine` would not use the generic parameter. Instead, I renamed `Constraint` to `ConstraintValidator` and added a new `Constraint` trait. This adds a `combine` method which takes a mutable reference to a constraint and consumes another constraint. If they can be fully combined, `None` is returned, otherwise `Some` with the remaining constraints. If the constraints cannot be combined at all because it would be unsatisfiable it will error.
- Add `fold_intersections` function to construct a vector of all intersections using the `combine` …

H-3426: Implement folding for data type constraints

---

libs/@blockprotocol/type-system/rust/src/schema/data_type/closed.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/number.rs

This adds the `combine` functionality for numbers. 
- Implement behavior to combine number constraints
This PR:
Due to the mutable nature of `combine` there is quite some duplication as the `lhs` and `rhs` typically cannot be swapped simply. This probably requires some changes to H-3426
Various test cases were added. Also, previous tests were adjusted to take the new changes into account.

H-3427: Implement folding for number constraints

---

libs/@blockprotocol/type-system/rust/src/schema/data_type/closed.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/any_of.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/mod.rs

This adds the `combine` functionality for `anyOf`s. 
This PR:
Due to the mutable nature of `combine` there is quite some duplication as the `lhs` and `rhs` typically cannot be swapped simply. This probably requires some changes to H-3426
Various test cases were added. Also, previous tests were adjusted to take the new changes into account.

H-3430: Implement folding for `anyOf` constraints

---

libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/string.rs

Similar to previous PRs, this adds folding for `string` constraints
This PR:
- Various tests were added

H-3428: Implement folding for string constraints

---

apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs

In order to reconstruct closed and resolved entity types, the existing data from Postgres needs to be used to fill EntityTypeResolveData for a given entity type.
This PR:

H-3516: Allow querying entity type resolve data from Postgres

---

Cargo.lock
libs/@local/harpc/client/Cargo.toml
libs/@local/harpc/client/package.json
libs/@local/harpc/client/src/connection/default.rs
libs/@local/harpc/client/src/connection/mod.rs
libs/@local/harpc/client/src/connection/service.rs
libs/@local/harpc/client/src/lib.rs
libs/@local/harpc/server/examples/account.rs
libs/@local/harpc/tower/src/request.rs

Reworks the connection client to be more general, it is not instead a `Connection<S, C>`, where `S` is the inner service and `C` is the codec used.
This is a usability improvement, because previously you needed to layer the connection service. This wasn't very ergonomic.
Now a default service exists that creates that layer (created with `connection`), but one can also create their own connection with a tower layer via `connection_with`.
(this also allows for easier type erasure - in the future - we can create a `BoxedConnection` (`C` would need a proxy trait like `erased_serde`, because we're making use of GATs)
This PR:

H-3519: `harpc`: rework the `Connection` type

---

.github/actions/terraform-exec/action.yml

`type` and `options` are not allowed as input.

H-3524: Remove wrong input parameters from terraform execute action

---

libs/@local/eslint-config/generate-ignore-patterns.cjs
libs/@local/eslint-config/package.json
libs/@local/eslint-config/temporarily-disable-rules.cjs
libs/@local/hash-graph-client/typescript/.eslintrc.cjs
libs/@local/hash-graph-client/typescript/tsconfig.json
libs/@local/tsconfig/legacy-base-tsconfig-to-refactor.json
yarn.lock

The ESLint config was not checked for tsc. This mainly caused issues in IDEs.

H-3531: Properly run `lint:tsc` for eslint-config

---

apps/hash-api/src/graph/ontology/primitive/data-type.ts
apps/hash-api/src/graph/ontology/primitive/entity-type.ts
apps/hash-api/src/graph/ontology/primitive/property-type.ts
apps/hash-graph/libs/api/openapi/models/closed_multi_entity_type.json
apps/hash-graph/libs/api/openapi/openapi.json
apps/hash-graph/libs/api/src/rest/entity_type.rs
apps/hash-graph/libs/api/src/rest/json_schemas/closed_multi_entity_type.json
apps/hash-graph/libs/graph/src/store/fetcher.rs
apps/hash-graph/libs/graph/src/store/ontology.rs
apps/hash-graph/libs/graph/src/store/postgres/ontology/entity_type.rs
libs/@local/hash-graph-client/typescript/turbo.json
libs/@local/hash-isomorphic-utils/src/subgraph-mapping.ts
tests/hash-graph-integration/postgres/lib.rs

For entities we need to combine entity types.
This is a small endpoint to allow merging entity types at all. It's not supposed to be a long-time solution (the types ideally should be returned alongside the entities), however, this allows viewing the entity types in the first place.
This PR:

H-3532: Expose querying multi-entity types

---

apps/hash-api/src/graph/ontology/primitive/entity-type.ts
apps/hash-graph/libs/api/openapi/openapi.json
apps/hash-graph/libs/api/src/rest/entity_type.rs
libs/@local/hash-graph-types/typescript/src/ontology.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/entity-type.test.ts
tests/hash-graph-http/tests/friendship.http

The path for querying multi-entity types in the OpenAPI specs is wrong so the Node API picks up he wrong endpoint.
- FIx path
- Rename the endpoint to be singular
- Add tests for closed entity type querying and closed multi-entity type querying

H-3546: Fix OpenAPI path for multi closed-entity type querying

---

Cargo.lock
libs/error-stack/Cargo.toml

We removed the usage of `once-cell` before, but didn't remove the dev-dependency on it.

GEN-201: Remove `once-cell` dev-dependency

---

apps/hash-graph/libs/api/src/rpc/account.rs
apps/hash-graph/libs/api/src/rpc/auth.rs
apps/hash-graph/libs/api/src/rpc/echo.rs
libs/@local/harpc/server/examples/account.rs
libs/@local/harpc/service/src/lib.rs
libs/@local/harpc/service/src/metadata.rs
libs/@local/harpc/service/src/procedure.rs

Splits `Metadata` into `SubsystemInformation` and `ProcedureInformation`, additionally they are altered slightly as well as how they're constructed, to make overwriting them in the future easier and more consistent.
This PR:

H-3558: `harpc`: rename `Metadata` to `SubsystemInformation` and `ProcedureInformation`

---

.github/workflows/lint.yml
.taplo.toml
Cargo.toml
apps/hash-graph/Cargo.toml
libs/@local/codec/Cargo.toml
libs/@local/graph/api/Cargo.toml
libs/@local/graph/authorization/Cargo.toml
libs/@local/graph/postgres-store/Cargo.toml
libs/@local/graph/store/Cargo.toml
libs/@local/graph/temporal-versioning/Cargo.toml
libs/@local/graph/test-server/Cargo.toml
libs/@local/graph/type-fetcher/Cargo.toml
libs/@local/graph/types/rust/Cargo.toml
libs/@local/graph/validation/Cargo.toml
libs/@local/harpc/client/Cargo.toml
libs/@local/harpc/codec/Cargo.toml
libs/@local/harpc/net/Cargo.toml
libs/@local/harpc/server/Cargo.toml
libs/@local/harpc/tower/Cargo.toml
libs/@local/hql/cst/Cargo.toml
libs/@local/hql/diagnostics/Cargo.toml
libs/@local/tracing/Cargo.toml
libs/deer/Cargo.toml
libs/deer/json/Cargo.toml
libs/error-stack/Cargo.toml
package.json
yarn.lock

While doing [H-1000](https://linear.app/hash/issue/H-1000/split-the-graph-into-multiple-lib-modules) it happened quite some times that manually reformatting *.toml files would have been needed. I used tuple to format the files, it's easy to add that configuration to the repository.
- Add `taplo` to dev-dependencies
- Add `fix:taplo` and `lint:taplo` scripts
- Add `lint:taplo` in CI
- Add small config for taplo
- Run `fix:taplo` to apply changes
This PR:

H-3570: Provide formatter for `*.toml` files

---

libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs
libs/@local/graph/type-fetcher/src/store.rs

We have an issue that tracing spans from previous queries occurring in new queries.
When `Span::enter()` is called and the returned `Drop`-guard is kept over an `.await` point it's possible that this results in wrong traces. For more information see the [`Span::enter()` documentation](https://docs.rs/tracing/latest/tracing/struct.Span.html#method.enter). This PR avoids calling `.enter()` in `async` context and uses the `Instrument` trait instead.
This PR:

H-3544: Fix spans occurring in unrelated queries

---

.github/actions/build-docker-images/action.yml
.github/workflows/bench.yml
.github/workflows/deploy.yml
.github/workflows/release.yml
.github/workflows/tf-plan-hash.yml

When opening PRs from a fork some CI cannot pass because they require authentication. To avoid this issue, this PR disables these steps (they will still be checked when running the merge-queue)
- Avoid uploading the cache for Build steps
- drive-by: Don't upload the Build results as artifact anymore, it's not used
- Use `checkout` action for Benchmark CI instead of manual commands
- Don't post the Benchmark-result as comment (the action runs from a fork so we cannot use `GH_TOKEN` here) - this can possibly be avoided by adding a `pull_request_target` run but that requires another CI workflow as we must not run the benchmarks using `pull_request_target`.
- Don't upload source maps to Sentry
- Don't attempt to plan a Terraform run
This PR:

H-3590: Allow all CI to pass when opening PRs from a fork

---

libs/@local/graph/migrations-macros/src/lib.rs
libs/@local/graph/migrations/src/bin/cli/subcommand/run.rs
libs/@local/graph/migrations/src/info.rs
libs/@local/graph/migrations/src/lib.rs
libs/@local/graph/migrations/src/list.rs
libs/@local/graph/migrations/src/plan.rs
libs/@local/graph/migrations/src/postgres.rs
libs/@local/graph/migrations/src/state.rs

When migration files changed and the database was already migrated this should error on migration attempt. Also, if a file was removed form the file system but is stored in the database.
- Implement failing on divergent or missing 
- Add four new parameters (CLI) parameters to the plan builder:
- `--allow-divergent`: Ignores if a file changed on the file system
- `--update-divergent`: Update migration info in the database if a file diverged (requires `--allow-divergent`)
- `--allow-missing`: Ignores if a file is missing in the file system
- `--remove-missing`: Removes migration info from the database if a file is missing (requires `--allow-missing`)
This PR:
TBD

H-3599, H-3600: Implement failing on divergent or missing files

---

libs/@local/graph/api/openapi/models/closed_data_type.json
libs/@local/graph/api/src/rest/json_schemas/closed_data_type.json

The OpenAPI specs are missing `allOf` and `abstract` from the `ClosedDataType` type and typescript is complaining when converting them to the type-system variants. This adds the definitions.

H-3650: Add `allOf` and `abstract` to `ClosedDataType`

---

apps/hash-graph/src/subcommand/migrate.rs
apps/hash-graph/src/subcommand/reindex_cache.rs
apps/hash-graph/src/subcommand/server.rs
apps/hash-graph/src/subcommand/snapshot.rs
apps/hash-graph/src/subcommand/test_server.rs
libs/@local/graph/api/openapi/openapi.json
libs/@local/graph/postgres-store/src/snapshot/entity/batch.rs
libs/@local/graph/postgres-store/src/snapshot/mod.rs
libs/@local/graph/postgres-store/src/snapshot/ontology/data_type/batch.rs
libs/@local/graph/postgres-store/src/snapshot/ontology/entity_type/batch.rs
libs/@local/graph/postgres-store/src/snapshot/ontology/metadata/batch.rs
libs/@local/graph/postgres-store/src/snapshot/ontology/property_type/batch.rs
libs/@local/graph/postgres-store/src/snapshot/owner/batch.rs
libs/@local/graph/postgres-store/src/snapshot/restore/batch.rs
libs/@local/graph/postgres-store/src/snapshot/web/batch.rs
libs/@local/graph/postgres-store/src/store/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/pool.rs
libs/@local/graph/store/src/entity/store.rs
libs/@local/graph/test-server/src/lib.rs
libs/@local/graph/validation/src/entity_type.rs
tests/graph/benches/util.rs
tests/graph/integration/postgres/lib.rs

The link validation is known to be slow currently (see [H-3522](https://linear.app/hash/issue/H-3522/speed-up-link-validation)). Until we sped up link validation we need a way to quickly seed a lot of data. For this, a CLI parameter is desired to skip validation of links.
- Adds a CLI parameter `--skip-link-validation`
- Propagates the settings down do the validation logic by adding a `settings` field to the Postgres store.
This PR:
Run the `hash-graph` binary directly using
```
cargo run --all-features --bin hash-graph --release -- server --skip-link-validation
```
and insert your data.

H-3674: Allow skipping link validation

---

libs/@local/harpc/client/typescript/src/codec/Decoder.ts
libs/@local/harpc/client/typescript/src/codec/Encoder.ts
libs/@local/harpc/client/typescript/src/codec/JsonDecoder.ts
libs/@local/harpc/client/typescript/src/codec/JsonEncoder.ts
libs/@local/harpc/client/typescript/src/codec/index.ts
libs/@local/harpc/client/typescript/tests/codec/JsonDecoder.test.ts
libs/@local/harpc/client/typescript/tests/codec/JsonEncoder.test.ts
libs/@local/harpc/client/typescript/tests/wire-protocol/decode.test.ts
libs/@local/harpc/client/typescript/tests/wire-protocol/encode.test.ts
libs/@local/harpc/client/typescript/tests/wire-protocol/utils.ts
libs/@local/harpc/client/typescript/tsconfig.json

Introduce the TypeScript equivalent to the `harpc_codec` crate. 
To be able to use type information (and transformations) these make use [effect schemas](https://effect.website/docs/schema/introduction/), which can also be ignored (each implementation provides a `layer` and `layerUnchecked` implementation.
Two new services are introduced:
* `Encoder`
* `Decoder`
As well as two implementations that mirror the existing Rust implementation:
* `JsonEncoder`
* `JsonDecoder`
This PR:

H-3682: Introduce TypeScript `harpc` codec

---

libs/@blockprotocol/type-system/rust/src/schema/entity_type/closed.rs
libs/@blockprotocol/type-system/rust/src/schema/entity_type/mod.rs
tests/hash-backend-integration/src/tests/graph/ontology/primitive/entity-type.test.ts

The open entity type should be contained in the `allOf` of the closed entity type provide a unified interface to all `icon`s and `labelProperty`s. In addition, the depth should be included.
- Add all parents to the `allOf`
- Add the schema itself as well

H-3677: Include entity type in closed entity type's `allOf`

---

libs/@local/graph/postgres-store/src/store/postgres/ontology/data_type.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs

When running `hash-graph reindex-cache` with `--data-types` or `--entity-types` there is now way to see the progress.
- Add a simple output to show the progress

H-3694: Add output when resolving a type

---

.github/workflows/renovate.yml
.yarnrc.yml
apps/hash/README.md

#5742 has set up Yarn 4, but while doing so several opportunities to enhance the documentation were found.
These are:
* setup corepack
* author and remove patches
This PR adds these to the general developer documentation, as well as enables corepack for renovate as a drive-by.
This PR:

H-3696: Create follow-up Yarn 4 documentation

---

libs/@blockprotocol/type-system/rust/src/schema/data_type/closed.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/array.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/boolean.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/null.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/object.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/string.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs

The current type constraints are defined for example like `{ type: "null" } & null`. We need to omit the unneeded part, so only `{ type: "null" }` remains. Also applies for `boolean` and `object`. Also, at the moment in theory it's possible to create conflicting format constraints. Until we actually find a use for this feature we avoid it.
- Change `SingleValueConstraint` to:
```ts
export type SingleValueConstraints =
| { type: "null" }
| { type: "boolean" }
| ({ type: "number" } & NumberSchema)
| ({ type: "string" } & StringSchema)
| ({ type: "array" } & ArraySchema)
| { type: "object" };
```
- Return an error if two different formats are used in value constraints
This PR:

H-3705, H-3706: Fix codegen for data type constraints and prohibit multiple formats in constraints

---

libs/@local/graph/postgres-store/src/store/postgres/query/compile.rs

If the same table was joined with different parameters it failed because the `alias` was not changed even though it should have.
If no equal tables are detected, the reference tables are checked if the variant is matching. If so, the `alias` is increased instead which leads to the desired behavior.
Technically, the `inheritanceDepth` should probably be stored as a parameter on the `Relation` instead but not all relations has an `inheritanceDepth`. Changing this would be a bigger change.

H-3612: Properly detect tables with different inheritance depths

---

libs/@local/graph/migrations/graph-migrations/v006__data_types/down.sql
libs/@local/graph/migrations/graph-migrations/v006__data_types/up.sql
libs/@local/graph/postgres-store/postgres_migrations/V35__remove_data_type_constrains_values_on_table.sql
libs/@local/graph/postgres-store/src/store/postgres/ontology/data_type.rs
libs/@local/graph/postgres-store/src/store/postgres/query/table.rs

When I added support for Custom Data Types in the graph I added two reference tables:
- `data_type_inherits_from`
- `data_type_constrains_values_on`
The former is used for the `allOf`. The second one I added in advance because I assumed this is what we’re going to use for `anyOf`. However, we chose another route here. If we need it we can easily re-add it.

H-3703: Remove unused `data_type_constrains_values_on` table

---

libs/@local/graph/migrations/graph-migrations/v009__entities/up.sql
libs/@local/graph/postgres-store/postgres_migrations/V36__link_table_indices.sql

I further tested out on adding more indices. A direct improvement gave the `link-entity` indices (uni-directional). All other indices did not show a noticeable change or even decreased performance. I don’t think there is any point in poking around in indices even more if we don’t have more benchmark coverage in place or a query in mind in particular which is slow.
Add the two link-indices

H-3723: Add link table indices

---

.config/husky/pre-commit
.github/actions/warm-up-repo/action.yml
.lefthook.yml
apps/hash-frontend/vercel-install.sh
apps/hashdotdesign/vercel-install.sh
apps/hashdotdev/vercel-install.sh
package.json
yarn.lock

husky and lint-staged are both dependency heavy and there have been challenges in trying to make external tools work (tools that cannot be installed with yarn).
The goal of this is to try to see if lefthook can be a minimally invasive alternative that allows for sqlfluff (and other packages) to be used.
> Personally I've also seen instances where husky/lint-staged just doesn't work because because e.g. it picked up the wrong node version from my system (I use mise to configure those) which has been very annoying in the past.
**husky doesn't clean up correctly**, while it works fine without doing it, keeping your hook location to the one of husky will mean you have a permanent stage file that shouldn't be committed, unset the git change that husky applied via: `git config --unset …

H-3733: Experiment with lefthook as a husky/lint-staged replacement

---

Cargo.lock
Cargo.toml
libs/@blockprotocol/type-system/rust/Cargo.toml
libs/@local/hql/diagnostics/Cargo.toml
libs/@local/temporal-client/Cargo.toml
libs/@local/temporal-client/src/ai.rs
libs/@local/temporal-client/src/lib.rs

We did not upgrade the Temporal dependency in a while. This also required some recursive dependencies to be upgraded (most importantly `chromo`) which is a feature which is sadly missing from Renovate. 
- Upgrade to latest Temporal version
- Adjust and test new Temporal client code (minimal changes required)
- Avoid the renaming of the temporal packages
- Run `cargo upgrade`

H-3745: Upgrade recursive dependencies and TemporalIO dependency

---

libs/@blockprotocol/type-system/rust/src/schema/array/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/array/validation.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/closed.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/validation.rs
libs/@blockprotocol/type-system/rust/src/schema/entity_type/validation.rs
libs/@blockprotocol/type-system/rust/src/schema/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/property_type/validation.rs

Some ontology types don't make sense, e.g. having a minimum higher than the maximum or an `allOf: [number, string]`. An error should be emitted in this case.
Entity/property types should be validated: e.g. required only specifies actual properties.
The references don't need to be validated up-front as they will be checked when inserted into the graph anyway.
By now, most of the schemas are either validated when created or when creating the closed variant of it.
This PR adds a validation for array property types to ensure that `minItems` must be less than or equal to `maxItems`.
Further, it allows `required` to point to a property which is specified in a parent entity type (by removing this constraint on the `EntityType` but keep it in `ClosedEntityType`).
This PR: …

H-2976: Improve validation for ontology types

---

.github/renovate.json

Groups `libp2p` updates in Renovate, for synchronous updating. Also improves the name formatting of other grouped `npm` package collections updated by Renovate.

H-3770: Group `libp2p` Renovate updates

---

libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
tests/graph/integration/postgres/sorting.rs

The parameter was wrongly set to `false` (as previously `count` was gotten from somewhere else).

H-3771: Fix `includeCount` not working in entity subgraph queries

---

libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs

Currently, if `resolveDataTypeWithChildren` is set, no data types will be returned if no children exist for the data types.
Instead of joining the inheritance it additionally selects from it as otherwise it requires that some inheritance exists.

H-3774: Fix including data type children will not emit anything if no children exist

---

infra/terraform/hash/hash_application/graph.tf
infra/terraform/hash/main.tf

Turn the switch, enable HaRPC 🚀 
- Pass the `HASH_RPC_ENABLED` and `HASH_GRAPH_RPC_ENABLED` environment variables
- Change the app protocol to TCP

H-3776: Enable HaRPC in AWS

---

apps/hash-api/src/index.ts
libs/@local/harpc/client/typescript/package.json
libs/@local/harpc/client/typescript/src/net/Transport.ts
libs/@local/harpc/client/typescript/src/net/internal/multiaddr.ts
libs/@local/harpc/client/typescript/src/net/internal/transport.ts
libs/@local/harpc/client/typescript/src/utils.ts
libs/@local/harpc/client/typescript/src/wire-protocol/models/Payload.ts
yarn.lock

When connecting via `libp2p` over DNS the addresses that are saved on the peer are the `ipv4` ones, not the `dns` entry, this lead to `harpc` forcing and maintaining a new connection.
This is (of course) not ideal, as DNS isn't "built-in" (it simply exploits the fact that `node:net` can resolve dns entries) we need to resolve the DNS entries ourselves and match them with the ones libp2p uses.
This PR:

H-3778: Resolve DNS entries on connection re-use

---

apps/hash-api/src/index.ts

To track down an error in production we need to enable logging. Also, we only use IPv4, so we can restrict the DNS lookup to `dns4` for now.

Enable verbose logging for HaRPC

---

Cargo.lock
libs/@local/harpc/client/typescript/package.json
libs/@local/harpc/client/typescript/src/net/internal/transport.ts
yarn.lock

The current harpc TypeScript DNS resolution has a bug, where multiple DNS entries lead to a relay address, instead of multiple possible addresses.
For example, `localhost` might resolve to both: `127.0.0.1` *and* `192.168.178.24`, this means that `/dns/localhost/tcp/4002` should resolve to: `/ip4/127.0.0.1/tcp/4002` **and** `/ip4/192.168.178.24/tcp/4002`, instead it will resolve to `/ip4/127.0.0.1/ip4/192.168.178.24/tcp/4002` which is a valid multiaddr but means: connect to `127.0.0.1` **over** `192.168.178.24` as a relay (which is obviously incorrect).
The fix is very straightforward and "just" a logic bug in the use of `flatMap` instead of `reduce`.
As a drive-by it also switches from `dns.resolve` to `dns.lookup`, to see if this changes the DNS resolution enough to work on AWS.
This …

H-3784: Correctly resolve multiple DNS entries

---

libs/@local/graph/api/openapi/openapi.json
libs/@local/graph/types/rust/src/knowledge/property/visitor.rs
libs/@local/graph/types/typescript/src/validation.ts
libs/@local/graph/validation/src/entity_type.rs

`properties` is confusing in this context

H-3786: Rename `properties` to `items` in `ArrayValidationReport`

---

infra/terraform/hash/prod-usea1.tfvars

The current logging level is quite verbose, we set this to warn instead.

H-3787: Reduce logging level for Node API in AWS

---

apps/hash-api/src/index.ts
libs/@local/harpc/client/typescript/src/net/internal/transport.ts

We're experiencing an issue in the harpc client implementation, where the resolved DNS entry seems to be out of sync with the one libp2p is using.
This PR:

H-3791: Log discovered `PeerId`s in HaRPC

---

Cargo.lock
Cargo.toml
apps/hash-graph/src/subcommand/server.rs
libs/@local/graph/api/Cargo.toml
libs/@local/graph/api/src/rest/account.rs
libs/@local/graph/api/src/rest/data_type.rs
libs/@local/graph/api/src/rest/entity.rs
libs/@local/graph/api/src/rest/entity_type.rs
libs/@local/graph/api/src/rest/mod.rs
libs/@local/graph/api/src/rest/property_type.rs
libs/@local/graph/store/src/entity/store.rs

In order to find slow queries the simplest way is to log the query times in question and capture the time spent on them.
This might be extended to other queries in the future, but for now we only need the actual read queries.
Adds a `--log-queries <PATH>` argument to the `server` subcommand to log queries at the specified path in JSON-lines format.
This PR:
The code is quite repetitive as I really wanted full control what exactly goes to the logger. It might be possible to encapsulate this in a new service, but this probably would have token more time than just implementing it as it is.

H-3789: Detect queries to the graph and record times

---

libs/@local/harpc/client/typescript/src/net/internal/dns.ts
libs/@local/harpc/client/typescript/src/net/internal/transport.ts

It seems like that `dns.resolve` wasn't the issue, instead it seems that the issue was that we were forcing FQDNs. This is currently unproven and needs to be deployed on AWS for verification. 
This also moves the dns code into it's own module to make it easier to understand (and `transport.ts` was getting quite cramped)
This PR:

H-3792: Switch to `dns.resolve` in HaRPC

---

.github/workflows/lint.yml
apps/hash/README.md
package.json
yarn.config.cjs
yarn.lock

lockfile-lint is quite simple in it's use-case (for us it's simply checking the source and parsing the file). Instead of needing to use a new tool to do so we can make use of yarn constraints to ensure that we don't use any of the sources we currently do not allow.
This also allows us to make changes that are a lot more stringent than lockfile-lint allowed previously. See the change to see what we're enforcing and how.
> we also support the `patch:` protocol, unlike lockfile-lint
This PR:

H-3691: Replace lockfile-lint with yarn constraints

---

libs/@local/graph/api/src/rest/account.rs
libs/@local/graph/api/src/rest/data_type.rs
libs/@local/graph/api/src/rest/entity.rs
libs/@local/graph/api/src/rest/entity_type.rs
libs/@local/graph/api/src/rest/mod.rs
libs/@local/graph/api/src/rest/property_type.rs

To properly reproduce performance bottleneck based on query logs it's required to include the `AccountId` of the actor.
- Add `actor_id` to the query logger
- drive-by: Emit a warning if `limit` is set to `0` in entity queries. If only the number of entities is required, `countEntities` can be used.

H-3804: Improve performance observability tooling in the graph

---

apps/hash-graph/src/subcommand/snapshot.rs
libs/@local/graph/postgres-store/src/snapshot/entity/batch.rs
libs/@local/graph/postgres-store/src/snapshot/mod.rs
libs/@local/graph/postgres-store/src/snapshot/ontology/data_type/batch.rs
libs/@local/graph/postgres-store/src/snapshot/ontology/entity_type/batch.rs
libs/@local/graph/postgres-store/src/snapshot/ontology/metadata/batch.rs
libs/@local/graph/postgres-store/src/snapshot/ontology/property_type/batch.rs
libs/@local/graph/postgres-store/src/snapshot/owner/batch.rs
libs/@local/graph/postgres-store/src/snapshot/restore/batch.rs
libs/@local/graph/postgres-store/src/snapshot/web/batch.rs
libs/@local/graph/test-server/src/lib.rs

It's useful to have a flag for debugging that validation errors may happen when restoring a snapshot.

H-3795: Allow snapshot restoring with validation errors

---

.github/renovate.json

At the moment, `@effect/vitest` matches the `vitest` pattern we use in Renovate, and thus is excluded from the `effect` group (with which it should belong).
This PR adds a negative match for the `@effect/vitest` package in the `vitest` group, in the hopes that it is then correctly picked up as part of the `effect` group.
- [Negative matching syntax](https://docs.renovatebot.com/string-pattern-matching/#negative-matching) in the Renovate docs

H-3811: Exclude `@effect/vitest` from Vitest upgrade group

---

apps/hash-api/src/index.ts
libs/@local/harpc/client/typescript/src/net/internal/dns.ts

During startup of the API, whenever RPC is enabled, print out useful DNS diagnostics.
This is primarily intended for AWS debugging purposes.
* removal of debugging information: [H-3813](https://linear.app/hash/issue/H-3813/remove-dns-logging-durring-hash-api-start)
This PR:

H-3812: enable DNS logging during `hash-api` start

---

libs/@local/graph/migrations/graph-migrations/v009__entities/up.sql
libs/@local/graph/postgres-store/postgres_migrations/V37__more_link_table_indices.sql

We currently only have indices on one side of the link reference tables. This adds the other side as well.

H-3814: Create remaining indices for link reference tables

---

libs/@local/graph/postgres-store/src/store/postgres/crud.rs

Postgres is not able to properly reorder `JOIN` statements. Currently, the entities are selected and later the filtering tables are joined. If the selecting joins are joined on already filtered joins this can speed up querying by a large amount (I noticed an improvement of up to x4)

H-3815: Reorder Postgres statements to join filter statements first

---

Cargo.lock
libs/@local/graph/api/src/rest/entity.rs
libs/@local/graph/api/src/rest/mod.rs
libs/@local/graph/store/src/entity/store.rs
tests/graph/benches/Cargo.toml
tests/graph/benches/manual_queries/entity_queries/all-public.json
tests/graph/benches/manual_queries/entity_queries/mod.rs
tests/graph/benches/manual_queries/lib.rs
tests/graph/benches/package.json
yarn.lock

Dynamically measure the performance for a specific query currently is quite hard. This adds a new benchmark to `tests/graph/benches` which can be run by `yarn bench:integration:manual`.
The queries will be read from the `manual_queries` directory and are in this shape:
- `type: "getEntities" | "getEntitySubgraph"`
- `actorId: Uuid`
- `request`  depending on type the exact same input as you’d pass to the graphApi functions
This PR:
- It would be good to add more dynamic behavior by allowing certain parameters to be dynamic such as the ActorID or the graph resolve depths. This will be done later.

H-1628: Write a benchmark which runs queries as specified in a JSON file

---

apps/hash-api/src/util.ts
apps/hash-frontend/src/components/grid/grid.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/edit-entity-slide-over.tsx
apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-page-wrapper/entity-page-header.tsx
apps/hash-frontend/src/pages/shared/entities-visualizer.tsx
apps/hash-frontend/src/pages/shared/entity-type-page/type-slide-over-stack.tsx
apps/hash-frontend/src/shared/is-of-type.ts
apps/hash-frontend/src/shared/table-header/bulk-actions-dropdown.tsx

A few small fixes in the frontend:
1. Fix selecting via checkbox in the entities table
2. Support archiving selected entities in the entities table
3. Add an 'archived' banner to the entity slideover, indicating an entity is archived
4. Add validation to the slideover if not in readonly mode
5. Fix locking body scroll when the type slideover is open
This PR:
1. Try the functionality described above

H-3553, H-3695, H-3805: Entities table and slideover fixes

---

apps/hashdotai/glossary/actor-model.mdx
apps/hashdotai/glossary/agent-based-modeling.mdx
apps/hashdotai/glossary/attributes.mdx
apps/hashdotai/glossary/block-protocol.mdx
apps/hashdotai/glossary/blocks.mdx
apps/hashdotai/glossary/digital-twin.mdx
apps/hashdotai/glossary/graphs.mdx
apps/hashdotai/glossary/properties.mdx

Various updates to glossary pages.

H-3809: Update glossary pages

---

apps/hashdotai/guide/05_workers/00_index.mdx

Fixes an incorrect on-page title.

H-3833: Fix `Workers` page heading

---

.github/renovate.json

Switches us from `yarnDedupeFewer` to `yarnDedupeHighest`.
Let's see if this makes a difference, and saves us from the never-ending need to run `yarn fix:yarn-deduplicate` on Renovate `npm` PRs.

H-3843: Change Renovate `postUpdateOptions` strategy

---

apps/hash-frontend/src/components/hooks/use-get-owner-for-entity.ts

The entities table currently crashes if it loads an entity where the User or Org owner can't be found. It shouldn't be the case that the User/Org can't be found, but if it does (as has happened due to a past issue when creating a user), we shouldn't crash the page, but instead have some fallback.
This PR does that.
This PR:
H-3851: We should make the user (and org) creation process better in rolling back things it has done if some subsequent step changes.
1. View `/entities` in the preview deployment, switch to viewing all global entities. It should not crash (check against prod) – https://hash-bhur9o6re.stage.hash.ai/entities

H-3852: Don't crash entities table if an entity's owner is missing

---

Cargo.lock
Cargo.toml

Renovate misses dependencies. In particular it's missing recursive dependencies. Also, it failed updating `Cargo.lock` properly (which is the reason why I looked into this in the first place)

H-3884: Upgrade Rust dependencies

---

libs/@local/graph/migrations/graph-migrations/v009__entities/up.sql
libs/@local/graph/postgres-store/postgres_migrations/V38__entity_temporal_metadata_edition_id_idx.sql

In normal entity queries the index often helps performance. See the relevant [slack thread](https://hashintel.slack.com/archives/C03F7V6DU9M/p1736267057261149) _(internal_).
This PR:

H-3702: Add edition ID index on entity table

---

apps/hash-frontend/src/pages/index.page/waitlisted/early-access-modal.tsx
apps/hash-frontend/src/pages/shared/url-input.tsx
libs/@hashintel/design-system/src/theme/components/inputs/mui-select-theme-options.tsx
libs/@hashintel/design-system/src/theme/components/navigation/mui-menu-item-theme-options.ts

We want to move property types which have URLs as their values to using the `URL` data type. This means values for them must pass URL validation, e.g. include a scheme at the start (`https://`) rather than just be e.g. `example.com`
But we also want users to be able to just type `example.com` into some inputs, e.g. in the early access form.
This PR adds a protocol dropdown to the early access form's website URL input so that we can pass a full URL to the database but users don't have to type it out properly themselves.
It also allows for having a path in the URL (e.g. `example.com/my-page`) which the early access form website URL input was previously not allowing.
This PR:
https://github.com/user-attachments/assets/12c790d7-dfff-4606-b046-fe1 …

H-3879: Add protocol dropdown to early access form URL input

---

Cargo.lock
apps/hash-graph/src/subcommand/server.rs
libs/@local/graph/api/src/rest/entity.rs
libs/@local/graph/postgres-store/Cargo.toml
libs/@local/graph/postgres-store/src/store/postgres/crud.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/read.rs
libs/@local/graph/postgres-store/src/store/postgres/query/compile.rs
libs/@local/graph/postgres-store/src/store/postgres/query/condition.rs
libs/@local/graph/postgres-store/src/store/postgres/query/expression/where_clause.rs
libs/@local/graph/postgres-store/src/store/postgres/query/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/query/statement/select.rs

In some very special cases the `SelectCompiler` panics. To avoid crashing the graph if this happens, this is changed to errors instead.
- Expose a `SelectComilerError` instead of panics
- Drive-by: Allow `limit` in more locations
- Drive-by: Make sure the compiler correctly errors when a cursor is passed
This PR:

H-3919: Return error instead of `panic` in `SelectCompiler`

---

package.json
yarn.lock

We're doing a migration that involves renaming types and updating some of them to refer to more appropriate data types.
This means block codegen currently fails, because some types in Block Protocol refer to types in HASH that don't yet exist.
This PR excludes blocks from workspaces and therefore CI until the migration is complete.

H-3926: Filter out blocks from repo workspaces

---

apps/hash-api/src/graph/ontology/primitive/data-type.ts
libs/@blockprotocol/type-system/rust/src/url/mod.rs
libs/@local/graph/api/openapi/openapi.json
libs/@local/graph/api/src/rest/data_type.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/data_type.rs
libs/@local/graph/store/src/data_type/mod.rs
libs/@local/graph/store/src/data_type/store.rs
libs/@local/hash-isomorphic-utils/src/data-types.ts
libs/@local/hash-isomorphic-utils/src/subgraph-mapping.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/data-type.test.ts

We can query for conversion targets, but another roundtrip to the graph is required to read the title. This can be done at the same time instead.
- Change the return type for `POST /data-types/query/conversions` to include the title

H-3929: Include data type conversion target title

---

infra/terraform/modules/variables/main.tf

For some reason, the `group-name` filter suddenly stopped working. The correct name is `region-name`, this PR changes the filter. This should not change any infrastructure.

H-3948: Fix Terraform filter to find AZ regions

---

.github/workflows/hash-backend-cd.yml
Cargo.toml
apps/hash-graph/docker/Dockerfile
infra/terraform/hash/hash_application/graph.tf

Manually deploying Graph images currently is quite painful if not on a machine with x86. This changes the architecture for the Graph in AWS to `ARM64` instead. At the same time, the Docker Image building process was adjusted in GitHub Actions to use the ARM images so CD can build them smoothly.
- Change architecture for graph on AWS to ARM64
- Change GH CD to use ARM image for building the graph
- Tweak Dockerfile to use LLVM builds when using the `dev` profile
- Add a `dev-llvm` profile
This PR:

H-3942: Run Graph on ARM in AWS

---

.nvmrc
apps/hashdotdev/.nvmrc

We have 3 .`nvmrc` files in this repo.
- @indietyp flagged we specify Node 22+ in the root `package.json` and only Node 20 in the corresponding `.nvmrc` file (used to provide `fnm` auto-switching support amongst others) should be updated to avoid conflicts (also for `nvm`, `mise`, `volta`, etc.)
- This was also true for the HDEV site.
- Meanwhile the HDESIGN nvm file is accurate, as our Storybook still runs on Node 20.

H-3931: Update `.nvmrc` files

---

libs/@local/graph/api/openapi/openapi.json
libs/@local/graph/store/package.json
libs/@local/graph/store/src/entity_type/query.rs

Currently, it's not possible to explore link destinations for entity types. This completes the picture of outgoing edges for ontology types.
This PR:

H-3975: Add `linkDestinations` as possible entity type query path token

---

apps/hash-frontend/src/components/grid/utils/conversion-menu.tsx
apps/hash-frontend/src/pages/shared/entities-visualizer.tsx
apps/hash-frontend/src/pages/shared/entities-visualizer/entities-table.tsx

Following the introduction of data type conversions to the frontend in #6237, this PR sorts table columns by the converted value rather than the stored number where available. 
e.g. Length as shown here is sorted by the value in the world, not the numbers.
This PR:
1. Possible to test in preview deployment if you have appropriate types.
See description.

H-3966: Sort entities table column by normalized value where possible

---

libs/@local/graph/api/openapi/openapi.json
libs/@local/graph/api/src/rest/mod.rs

It does not add any type safety as we have string in the list of possible tokens, however, having "convert" in the list of tokens will make DX easier.

H-3979: Expose a `convert` token in query paths

---

apps/hash-ai-worker-ts/src/activities/flow-activities/infer-metadata-from-document-action.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/infer-metadata-from-document-action/generate-proposed-entities-and-claims.ts
apps/hash-ai-worker-ts/src/activities/flow-activities/infer-metadata-from-document-action/get-llm-analysis-of-doc.ts
apps/hash-frontend/src/components/grid/grid.tsx
apps/hash-frontend/src/components/grid/utils.ts
apps/hash-frontend/src/components/grid/utils/interactable-manager.ts
apps/hash-frontend/src/components/grid/utils/interactable-manager/types.ts
apps/hash-frontend/src/components/grid/utils/use-draw-header.ts
apps/hash-frontend/src/components/grid/utils/use-grid-tooltip.tsx
apps/hash-frontend/src/components/grid/utils/use-grid-tooltip/draw-interactable-tooltip-icons.ts
apps/hash-frontend/src/components/grid/utils/use-grid-tooltip/types.ts
apps/hash-frontend/src/pages/@/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/outgoing-links-section/cells/linked-with-cell.ts
apps/hash-frontend/src/pages/@/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table.tsx
apps/hash-frontend/src/pages/@/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell.tsx
apps/hash-frontend/src/pages/@/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx
apps/hash-frontend/src/pages/shared/chip-cell.tsx
apps/hash-frontend/src/pages/shared/sources-popover.tsx

This PR:
- Shows the sources for a given property value (if any) on hovering over the value in the entity editor
- Fixes some behavior issues with grid table tooltips in general (make them disappear when leaving the tooltip, not when leaving the cell)
- Fixes a couple of bugs in the document inference action
- Fixes a bug when navigating client-side to a type's page
This PR:
1. If you have sources for properties, testable in preview deployment
https://github.com/user-attachments/assets/f5b2ab26-fd38-46f2-a8a6-11fc350e2aeb

H-3145: Show sources on property hover in entity editor; bug fixes

---

turbo.json

The current global dependencies are quite outdated and many files are not included so we manually do it by parsing the // package (the root package) in CI.
To avoid that, the global dependencies should be overhauled.
See the changed files
This PR:

H-3998: Adjust global `turbo` dependencies

---

.vscode/settings.json
.zed/settings.json

Turborepo does not support the `turbo.json` file being renamed to `.jsonc`, but it does correctly parse comments in the `.json` file (as introduced in https://github.com/hashintel/hash/pull/6314). This update to the repo `.vscode/settings.json` file tells VSCode/Cursor to treat the `turbo.json` file as if it were JSONC.
- Thread on [potential future support for the JSONC file extension in Turborepo](https://github.com/vercel/turborepo/issues/3793)

H-4001: Improve VSCode/Zed file type handling

---

apps/hash-ai-worker-ts/src/activities/infer-entities/propose-entities.ts
libs/@local/codec/package.json
libs/@local/codec/src/serde/string_hash_map.rs
libs/@local/graph/api/openapi/openapi.json
libs/@local/graph/types/rust/src/knowledge/property/array.rs
libs/@local/graph/types/rust/src/knowledge/property/metadata/mod.rs
libs/@local/graph/types/rust/src/knowledge/property/object.rs
libs/@local/graph/types/typescript/src/entity.ts

To distinguish between the array and the object variant of properties, the `value` needs to be defined. Then, it's possible to check, if `value` is an array or an object.
There is one drive-by change to enable more tests in CI

H-3995: Make `value` required for properties with metadata

---

.github/workflows/lint.yml
.github/workflows/test.yml

Currently, we use `turbo run ... dry-run. Instead, we can use `turbo query`.
This PR:

H-3999: Use `turbo query` to determine changed packages in CI

---

libs/@local/hash-backend-utils/package.json
libs/@local/hash-backend-utils/src/public-user-account-id.ts
yarn.lock

Semgrep complains about hardcoding an account ID. As this is a well-known constant, we can just use that instead.

H-4003: Use `uuid.NIL` for public account ID

---

apps/hash-ai-worker-ts/src/activities/graph.ts
apps/hash-ai-worker-ts/src/workflows.ts
libs/@local/graph/validation/src/test_data_type.rs

When possible we should use the constant `uuid.NIL` or the corresponding public account ID constant instead.

H-4003: Permission to hard coded nil-UUID string denied, use constants instead

---

.config/nextest.toml
.github/workflows/test.yml
libs/@local/harpc/net/src/session/test.rs
turbo.json

The `session::test::echo_tcp_concurrent` sometimes fail in CI, this adds it to fail once per run.
- Adds a new `NexTest` profile `ci`
- Add override for the mentioned test

H-4005: Allow flaky test to fail (once)

---

.github/workflows/bench.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml

`turbo` is not able to properly find the commit SHA. Instead, we use `HEAD^`.

H-4008: Fix base branch detection for CI

---

apps/hash-frontend/src/pages/@/[shortname]/entities/[entity-uuid].page/entity-page-wrapper/draft-entity-banner.tsx
apps/hash-frontend/src/pages/@/[shortname]/entities/[entity-uuid].page/entity-page-wrapper/entity-page-header.tsx
apps/hash-frontend/src/pages/actions.page.tsx
apps/hash-frontend/src/pages/actions.page/draft-entities.tsx
apps/hash-frontend/src/pages/actions.page/draft-entities/draft-entities-filters.tsx
apps/hash-frontend/src/pages/actions.page/draft-entities/types.ts
apps/hash-frontend/src/pages/actions.page/draft-entity.tsx
apps/hash-frontend/src/pages/actions.page/draft-entity/draft-entity-action-buttons.tsx
apps/hash-frontend/src/pages/actions.page/draft-entity/draft-entity-type.tsx
apps/hash-frontend/src/pages/shared/accept-draft-entity-button.tsx
apps/hash-frontend/src/pages/shared/discard-draft-entity-button.tsx

This PR switches to using the 'closed' (fully resolved) entity types in the drafts action queue. This makes it easier to take account of inherited icons, labels etc.
This PR:

H-3928: Use closed types in drafts queue

---

apps/hash-frontend/src/pages/@/[shortname].page/pinned-entity-type-tab-contents.tsx
apps/hash-frontend/src/pages/entities.page.tsx
apps/hash-frontend/src/pages/shared/entity-type-page.tsx
apps/hash-frontend/src/pages/shared/entity-type-page/edit-bar-type-editor.tsx
apps/hash-frontend/src/pages/shared/entity-type-page/type-slide-over-stack/type-slide-over-slide.tsx
apps/hash-frontend/src/shared/entity-types-context/shared/is-special-entity-type.ts

The intended user flow for creating links from entities to other entities is that links are created from the source entity's page.
This PR catches a couple of places where it was possible to click 'create entity' on a link directly, which just goes to a page telling you that you can't.
It also fixes an issue with discarding changes in the type editor.
This PR:
1. See if you can find anywhere to create a link entity directly.

H-1844: Prevent creating link entities directly

---

libs/@local/graph/postgres-store/src/ontology/mod.rs

The `$id` field is not required when updating a type, however, we should not error in this case as for updating in batches this is additional work which is not needed.

H-4022: Don't error if $id is passed when updating a schema

---

apps/hash-frontend/src/components/grid/utils/override-custom-renderers.tsx
apps/hash-frontend/src/pages/@/[shortname].page/pinned-entity-type-tab-contents.tsx
apps/hash-frontend/src/pages/@/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell.tsx
apps/hash-frontend/src/pages/@/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell/array-editor.tsx
apps/hash-frontend/src/pages/@/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell/array-editor/draft-row.tsx
apps/hash-frontend/src/pages/@/[shortname]/entities/[entity-uuid].page/entity-editor/properties-section/property-table/cells/value-cell/array-editor/sortable-row.tsx
apps/hash-frontend/src/pages/actions.page.tsx
apps/hash-frontend/src/pages/shared/inline-select.tsx
apps/hash-frontend/src/shared/use-scroll-lock.ts

1. Updates the full display of readonly array values in the entity editor to be the same as in editing mode 
2. Fixes an issue when clicking on a cell in the entity editor in a slide, where you'd end up with two scroll bars (body and slide)
3. Fixes styling issue with a sort dropdown in the actions queue
See demo.
This PR:
There's still an issue when clicking into a cell in the entity editor whereby the slide remains scrollable. Fixing this requires reworking a bit of how we lock scrolling, if it becomes annoying.
1. Not possible in preview deployment because entities in prod lack metadata which the editor relies on.
Shows both scroll issue and previous readonly array display
https://github.com/user-attachments/assets/3653e963-18f1-4790-8008- …

H-3545, H-4032: Update readonly array display in editor, fix scroll behavior in editor slide

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util.ts
libs/@local/graph/api/openapi/openapi.json
libs/@local/graph/api/src/rest/data_type.rs
libs/@local/graph/authorization/schemas/v1__initial_schema.zed
libs/@local/graph/authorization/src/schema/data_type.rs
libs/@local/graph/authorization/src/schema/mod.rs
package.json
tests/graph/http/tests/friendship.http
tests/hash-backend-integration/src/tests/graph/ontology/primitive/data-type.test.ts

Data types needs to be updated eventually.
Aligns the permissions for data types with the other ontology types
This PR:

H-2767: Create and allow assigning editor permissions on data types

---

apps/hash-api/src/graph/ontology/primitive/entity-type.ts
apps/hash-api/src/graphql/resolvers/ontology/entity-type.ts
apps/hash-frontend/src/pages/@/[shortname]/shared/use-route-namespace.tsx
apps/hash-frontend/src/pages/@/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx
apps/hash-frontend/src/pages/shared/entity-type-page.tsx

This PR un-hides the modal introduced in #6366 which allows users to update types which are dependent on the type being updated.
This PR:
- Currently not all dependent types will be correctly found. This is because of an issue with `any` filters in the Graph API whereby if you use a query path which depends on a table join (e.g. `inheritsFrom`), only those types which have _some_ value for that path will be possible returns, even if types which _don't_ have anything they e.g. inherit from match _another_ of the `any` filter. In this context, this means that it will only find dependents which have _something_ they inherit from, and _some_ link. Types without either a parent or any links will not be found. Tracked in H-4015.
- The same 'offer …

H-4026: Enable showing the modal to update dependent entity types

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/001-create-hash-system-types.migration.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/005-create-hash-system-entities-and-web-bots.migration.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/017-add-use-case-form-and-example-org.migration.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util/upgrade-entities.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/system-webs-and-entities.ts
apps/hash-api/src/graph/knowledge/system-types/hash-instance.ts
apps/hash-api/src/graph/knowledge/system-types/org.ts
apps/hash-api/src/graph/knowledge/system-types/user.ts
libs/@local/hash-backend-utils/src/machine-actors.ts

This PR does a few pieces of cleanup around permissions:
1. Restricts anyone from creating `User` and `Organization` entities outside of the dedicated routes (creating the entities elsewhere doesn't grant any permissions, but if someone does it we will have broken User/Orgs lying around)
2. Don't bother to maintain instantiator permission on `Machine` for anyone (just grant and remove it as needed)
3. Fix migration scripts to account for arbitrary needs to grant/remove permissions to add new types to entities
This PR:
- Migration scripts and some BE integration tests involve creating orgs
1. Check that migrations still run as expected
2. Check that user can create an org via UI (workspace switcher -> create org)
3. Check that user cannot …

H-4064: Restrict `User` and `Organization` instantiators

---

apps/hashdotdesign/vercel-build.sh
apps/hashdotdev/vercel-build.sh

The vercel-builds did not source the correct file, so they couldn't find `cargo metadata`.

H-3071: Fix hash.design vercel builds

---

libs/@blockprotocol/type-system/rust/Cargo.toml
libs/@blockprotocol/type-system/rust/package.json
libs/@blockprotocol/type-system/rust/src/lib.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/number.rs
libs/@blockprotocol/type-system/rust/src/utils.rs
libs/@blockprotocol/type-system/rust/tsconfig.json
libs/@blockprotocol/type-system/rust/turbo.json
libs/@local/effect-dns/hickory/Cargo.toml
yarn.lock

When we added higher precision conversions, the type system did not generate valid TS. This fixes the generations for number constraints to use `number` instead of `Real` and also fix the `Value` type.
This PR:

H-4068: Fix codegen in `typesystem` to generate `number` instead of `Real`

---

Cargo.toml

The `workspace.lints.cargo` section is currently not used and also not part of the Cargo manifest schema. This results in linting errors in the IDE if the IDE supports schema validation.

H-4071: Comment out unused/unsupported lint section in Cargo manifest

---

package.json

Minimal change to help track clones back to their original source, for basic software supply chain provenance per https://github.com/microsoft/Secure-Supply-Chain

H-4075: Explicitly declare repo in root `package.json`

---

libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/number.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/constraint/string.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/mod.rs
libs/@blockprotocol/type-system/rust/src/schema/data_type/validation.rs
libs/@local/codec/src/serde/mod.rs
libs/@local/codec/src/serde/unique_vec.rs
libs/@local/hash-isomorphic-utils/src/data-types.ts

We want to preserve the ordering when creating data types. For simplicity, we also remove the `const` constraint as it's effectively the same as a single-element `enum` constraint.
This PR:

Preserve order for `enum` data type constraints

---

package.json

We have a `start:graph` and a `start:test` command, but no `start:test:graph` (but we have `start:test:worker`). The `start:graph` command uses a release build, the newly added `start:test:graph` is a debug build.

H-4091: Add a `start:test:graph` command in top level package

---

.config/_examples/vscode/extensions-backend.json
.config/_examples/vscode/extensions-rust.json
Cargo.lock
Cargo.toml
libs/@local/graph/authorization/Cargo.toml
libs/@local/graph/authorization/schemas/policies.cedarschema
libs/@local/graph/authorization/src/policies/action/mod.rs
libs/@local/graph/authorization/src/policies/mod.rs
libs/@local/graph/authorization/src/policies/principal/mod.rs
libs/@local/graph/authorization/src/policies/principal/team.rs
libs/@local/graph/authorization/src/policies/principal/user.rs
libs/@local/graph/authorization/src/policies/principal/web.rs
libs/@local/graph/authorization/src/policies/resource/entity.rs
libs/@local/graph/authorization/src/policies/resource/entity_type.rs
libs/@local/graph/authorization/src/policies/resource/mod.rs

To support an MVP of permissions using policies, we require a few more things in the policies itself.
- Replace the `Organization` principal with the `Web` principal. Technically, we don't even need the `User` principal anymore but could use a role per web instead.
- Add the `Team` principal
- Add the `EntityType` resource
- Add a Schema for policies
- Collect information about principals and resources before evaluation (this means, that the policy engine is aware of a user's web, the type of an entity, or the base URL and version for an entity type
- Support filtering entities by type
This PR:
- We use a Versioned URL to safe ontology types. In comparison to Entity UUIDs, this does not implement `Copy` as it internally uses a `String`. …

H-4086: Add remaining types for Permission MVP

---

.github/renovate.json

The lockfile maintenance for Rust downgrades some crates, which then will be upgraded again by renovate. Renovate just does a bad job in determining changes in Rust, so we remove lockfile maintenance for Rust. As we had issues with the Node-lockfile PR as well, so we simply remove the feature completely, again.
- https://github.com/hashintel/hash/pull/6478

H-4097: Revert 'Lock File Maintenance' in Renovate

---

libs/@local/graph/test-server/turbo.json
libs/@local/graph/type-fetcher/turbo.json

`yarn start:test:graph` did not wait for the compilation to be finished.
Let the `compile` task a dependency of the healthcheck tasks
This PR:

H-4119: Fix `yarn start:test:graph` not properly compiling Rust crates

---

libs/@local/graph/postgres-store/src/store/postgres/ontology/data_type.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/property_type.rs
tests/hash-backend-integration/src/tests/graph/ontology/primitive/data-type.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/entity-type.test.ts
tests/hash-backend-integration/src/tests/graph/ontology/primitive/property-type.test.ts

When archiving and then unarchiving a type, the returned types may be the archived one (with the upper timestamp set to `type: "exclusive"`). Instead, the latest should be returned, which will be the unarchived one if existing.
- Order the returned ontology type by transaction time
- Write tests for all ontology types to archive/unarchive
This PR:
- A test has been added for each ontology type which archives and the unarchives the type. Then it's checked if the correct version is returned.

H-4109: Fix ontology queries returning archived types instead of latest

---

libs/@local/graph/authorization/schemas/policies.cedarschema
libs/@local/graph/authorization/src/policies/context.rs
libs/@local/graph/authorization/src/policies/mod.rs
libs/@local/graph/authorization/src/policies/principal/actor.rs
libs/@local/graph/authorization/src/policies/principal/machine.rs
libs/@local/graph/authorization/src/policies/principal/mod.rs
libs/@local/graph/authorization/src/policies/principal/role.rs
libs/@local/graph/authorization/src/policies/principal/user.rs
libs/@local/graph/authorization/src/policies/principal/web.rs
libs/@local/graph/authorization/src/policies/resource/entity.rs
libs/@local/graph/authorization/src/policies/resource/entity_type.rs
libs/@local/graph/authorization/src/policies/resource/mod.rs
libs/@local/graph/authorization/src/policies/set/mod.rs
libs/@local/graph/authorization/src/policies/validation.rs
libs/@local/graph/authorization/tests/policies/definitions/forbid-update-web-machine.cedar
libs/@local/graph/authorization/tests/policies/definitions/mod.rs
libs/@local/graph/authorization/tests/policies/definitions/permit-admin-web.cedar
libs/@local/graph/authorization/tests/policies/definitions/permit-hash-instance-admins.cedar
libs/@local/graph/authorization/tests/policies/definitions/permit-instantiate.cedar
libs/@local/graph/authorization/tests/policies/definitions/permit-member-crud-web.cedar
libs/@local/graph/authorization/tests/policies/definitions/permit-view-ontology.cedar
libs/@local/graph/authorization/tests/policies/definitions/permit-view-system-entities.cedar
libs/@local/graph/authorization/tests/policies/main.rs

We require a set of policies to drive the Graph in general. This PR adds common policies and missing features associated with them.
- https://github.com/hashintel/hash/pull/6518
- Add `IsAllTypes` and `IsAnyType` to restrict policies to multiple (at least one or all) types in an entity
- Allow filtering entity types (A combination of `All`, `Any`, `Not`, `IsBaseUrl` and `IsVersion`
- Add a range of policies for testing
- Run different sets of request against the policies
This PR:

H-4103: Write test for common Policies

---

apps/hash-frontend/vercel-build.sh

Mise is picking up the `.env` files which we currently don't want when building the Frontend. This removes the `.env` files before it get's built.
- H-3213: Use consistent naming schema for environment variables
- H-4202: Sort out which environment variables are defined where

H-4200: Fix Vercel frontend pointing to localhost

---

.github/workflows/ai-pr-review.yml
.github/workflows/bench.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml
libs/@local/repo-chores/node/scripts/ai-pr-review.ts
libs/@local/repo-chores/node/scripts/ai-pr-review/generate-comment-replies.ts

This PR addresses two issues:
1. Prevents multiple AI reviews from running simultaneously on the same pull
request by adding concurrency configuration to the GitHub workflow
2. Fixes tag resolution bugs in AI comment replies that caused invalid tag errors
- [H-4232: Avoid running multiple AI reviews at the same time](https://linear.app/hash/issue/H-4232/avoid-running-multiple-ai-reviews-at-the-same-time)
- Adds concurrency configuration to the GitHub workflow file
`.github/workflows/ai-pr-review.yml`
- Configures concurrency group to use PR number or inputs for workflow_dispatch 
events
- Sets `cancel-in-progress: false` to ensure reviews complete before new ones 
start
- Adds explanatory comments documenting the concurrency behavior
- Improves tag handling in …

H-4232: Avoid running multiple AI reviews at the same time

---

.taplo.toml

The world doesn't need to know that `/.venv/lib/python3.12/site-packages/pandas/pyproject.toml` doesn't match our lint rules. And we don't care!

H-4242: Exclude `.venv` from TOML linting

---

libs/error-stack/CHANGELOG.md
libs/error-stack/src/fmt/charset.rs
libs/error-stack/src/fmt/color.rs
libs/error-stack/src/hook/mod.rs
libs/error-stack/src/lib.rs
libs/error-stack/src/macros.rs
libs/error-stack/src/report.rs
libs/error-stack/src/result.rs
libs/error-stack/tests/snapshots/doc/fmt__charset_ascii.snap
libs/error-stack/tests/snapshots/doc/fmt__charset_utf8.snap
libs/error-stack/tests/snapshots/doc/fmt__preference_color.snap
libs/error-stack/tests/snapshots/doc/fmt__preference_emphasis.snap
libs/error-stack/tests/snapshots/doc/fmt__preference_none.snap
libs/error-stack/tests/snapshots/doc/hook__debug_hook.snap
libs/error-stack/tests/snapshots/doc/hook__debug_hook_provide.snap
libs/error-stack/tests/test_conversion.rs
libs/error-stack/tests/test_extend.rs
libs/error-stack/tests/test_iter.rs
libs/error-stack/tests/test_macros.rs
libs/error-stack/tests/ui/macro_invalid_args.rs
libs/error-stack/tests/ui/macro_invalid_args.stderr
undefined/settings.toml

Currently, when using errors in traits, it's annoying that you cannot properly specify errors in associated types.
```rust
// Requires `Result<_, Report<Self::Error>>` as return to allow `.change_context()` 
type Error: Error + Send + Sync + 'static;
```
Also, `Result<_, Report<!>>` is not working as well as it could work.
This PR (re-)adds `IntoReport` to allow it in associated types, such as:
```rust
// Allows `impl Error`, `Report<impl Error>`, and `!` as type
type Error: IntoReport;
```
This PR:
A trait is added to the interface but the trait is very simple and outweighs the drawbacks of a new trait.
The `ResultExt` trait was changed, so pretty much every test is using the new trait indirectly

H-4250: Use a `IntoReport` trait to determine conversion to a `Report`

---

.config/mise/config.toml
.justfile
libs/@local/codec/package.json
libs/@local/graph/types/rust/package.json
libs/@local/harpc/types/package.json
libs/@local/hql/cst/package.json
libs/@local/hql/span/package.json
libs/antsi/package.json
libs/sarif/package.json

Renovate currently does not cover all dependency updates
- `mise upgrade --bump`
- Revert bumping `node`

H-4262: Bump tool versions

---

README.md
package.json

We renamed the `type-fetcher` package a while back but did not update it in `package.json`'s `start` script

H-4283: Update package name in `package.json`

---

apps/hashdotai/guide/04_types/04_data-types.mdx

Removes references to `Empty List` as a primitive data type from the docs.

H-4296: Remove docs reference to `Empty List` data type as a primitive

---

libs/@local/hashql/syntax-jexpr/src/lexer/mod.rs
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__adjacent_comment.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__adjacent_comment_no_space.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__comment_json_inside.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__comment_no_space_between.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__empty_comment.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__empty_multiline_comment.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__multiline_comment_json_inside.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__multiline_comment_too_smol.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__multiline_linebreak.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__multiline_with_asterisks.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__preceded_comment.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__preceded_multiline_comment.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__separated_comment.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__separated_multiline_comment.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__trailing_comment.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__trailing_multiline_comment.snap
libs/@local/hashql/syntax-jexpr/src/lexer/snapshots/hashql_syntax_jexpr__lexer__test__unclosed_multiline_comment.snap
libs/@local/hashql/syntax-jexpr/src/lexer/token_kind.rs

Allow for comments inside JSON. This is super straightforward to implement (a two line change in the lexer).
This PR:

H-4324: HashQL J-Expr support use of JSONC

---

.config/mise/config.toml
Cargo.lock

Renovate currently does not cover all dependency updates. To update them manually, the easiest way is to use `mise ugrade --bump`.
This PR:

H-4270: Bump tool dependencies

---

libs/@local/hashql/ast/src/heap.rs
libs/@local/hashql/ast/src/node/expr/call.rs
libs/@local/hashql/ast/src/node/expr/closure.rs
libs/@local/hashql/ast/src/node/expr/dict.rs
libs/@local/hashql/ast/src/node/expr/list.rs
libs/@local/hashql/ast/src/node/expr/struct.rs
libs/@local/hashql/ast/src/node/expr/tuple.rs
libs/@local/hashql/ast/src/node/expr/use.rs
libs/@local/hashql/ast/src/node/generic.rs
libs/@local/hashql/ast/src/node/path.rs
libs/@local/hashql/ast/src/node/type.rs
libs/@local/hashql/syntax-jexpr/src/parser/array/mod.rs
libs/@local/hashql/syntax-jexpr/src/parser/object/dict.rs
libs/@local/hashql/syntax-jexpr/src/parser/object/list.rs
libs/@local/hashql/syntax-jexpr/src/parser/object/struct.rs
libs/@local/hashql/syntax-jexpr/src/parser/object/tuple.rs
libs/@local/hashql/syntax-jexpr/src/parser/string/combinator.rs
libs/@local/hashql/syntax-jexpr/src/parser/string/generic.rs
libs/@local/hashql/syntax-jexpr/src/parser/string/path.rs
libs/@local/hashql/syntax-jexpr/src/parser/string/type.rs

Switch from `Box<[T]>` to `Vec<T>`. This is required as during lowering we need to do some changes to the underlying structure, like expanding etc.
This has the caveat that we're potentially have "wasted" space whenever the vector is re-allocating, but that amount should be negligible. There's precedence for this, `swc_allocator` and `oxc_allocator` both make use of this exact same technique.
The other possibility would be to use a split-vec (like [https://docs.rs/orx-split-vec/latest/orx_split_vec/](https://docs.rs/orx-split-vec/latest/orx_split_vec/)), but there is sadly no crate out there that supports split-vec *and* the allocator API.
> `biome` forgoes a custom allocator completely, but only because they never leave the syntax tree (`rowan` behind).
This PR: …

H-4339: HashQL: Switch from `Box<[T]>` to `Vec<T>`

---

apps/hash-frontend/src/pages/shared/graph-visualizer/graph-container/shared/control-components.tsx
apps/hash-frontend/src/pages/shared/graph-visualizer/graph-container/shared/graph-viz-tooltip.tsx
apps/hash-frontend/src/pages/shared/graph-visualizer/graph-container/shared/simple-autocomplete.tsx
apps/hash-frontend/src/pages/shared/graph-visualizer/graph-container/shared/use-event-handlers.ts
apps/hash-frontend/src/pages/shared/slide-stack.tsx
apps/hash-frontend/src/pages/shared/type-graph-visualizer.tsx

When the graph visualization is fullscreened, fix the following things:
1. Tooltips weren't showing up (we need to tell MUI the non-`body` container to attach them to)
2. Opening a slide exited fullscreen (need to stop opening slides re-rendering components using information from the slide context, and `Portal` the slide stack)
This PR:
1. Open 'Types' page, open graph viz, fullscreen, check tooltips (e.g. on filter component), and click on type to open slide in fullscreen

H-4321: Fix slides and tooltips appearing in graph viz fullscreen mode

---

Cargo.lock
Cargo.toml
apps/hash-graph/src/subcommand/server.rs
libs/@local/graph/api/src/rest/mod.rs
libs/@local/graph/api/src/rest/web.rs
libs/@local/graph/authorization/Cargo.toml
libs/@local/graph/authorization/schemas/policies.cedarschema
libs/@local/graph/authorization/src/policies/action/mod.rs
libs/@local/graph/authorization/src/policies/context.rs
libs/@local/graph/authorization/src/policies/mod.rs
libs/@local/graph/authorization/src/policies/principal/mod.rs
libs/@local/graph/authorization/src/policies/principal/role/mod.rs
libs/@local/graph/authorization/src/policies/principal/team/mod.rs
libs/@local/graph/authorization/src/policies/principal/team/subteam.rs
libs/@local/graph/authorization/src/policies/principal/team/web.rs
libs/@local/graph/authorization/src/policies/store/error.rs
libs/@local/graph/authorization/src/policies/store/mod.rs
libs/@local/graph/postgres-store/src/permissions/error.rs
libs/@local/graph/postgres-store/src/permissions/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/tests/principals/actions.rs
libs/@local/graph/postgres-store/tests/principals/ai.rs
libs/@local/graph/postgres-store/tests/principals/machine.rs
libs/@local/graph/postgres-store/tests/principals/main.rs
libs/@local/graph/postgres-store/tests/principals/policies.rs
libs/@local/graph/postgres-store/tests/principals/role.rs
libs/@local/graph/postgres-store/tests/principals/team.rs
libs/@local/graph/postgres-store/tests/principals/user.rs
libs/@local/graph/postgres-store/tests/principals/web.rs
libs/@local/graph/type-fetcher/src/store.rs

To allow the usage of the new policies we need to bubble up the interface to the Graph API layer. Also, it has to be possible to create a principal context which can be used in Cedar.
- Implement a `PrincipalStore`
- Expose `PrincipalStore` up to the `rest` module (but with commented out functionality to not interfere with the current permission system)
- Implement creation of principal context creation
- Greatly simplify handling of actions by creating a list of parents in Rust.
This PR:
- Previous tests were adjusted to use the new `create_web` function signature
- A seeding logic was added to tests
- A new test was added to verify consistency of the Cedar schema and the Rust implementation

H-4345: Prepare evaluation of policies when calling from API

---

apps/hash-frontend/src/pages/actions.page/draft-entities-context.tsx
apps/hash-frontend/src/pages/notifications.page/notifications-with-links-context.tsx
apps/hash-frontend/src/pages/shared/entities-visualizer.tsx
apps/hash-frontend/src/shared/draft-entities-count-context.tsx
apps/hash-frontend/src/shared/notification-count-context.tsx
apps/hash-frontend/src/shared/poll-interval.ts
apps/hash-frontend/src/shared/use-poll-interval.ts

Waitlisted users are still shown the header navbar, which includes some logic related to notifications.
This PR disables polling for notifications (and actions) if a user hasn't completed signup, to avoid pointless API requests.
This PR:

H-4399: Disable notification polling for waitlisted users

---

libs/@local/graph/authorization/tests/policies/definitions/permit-instantiate.cedar
tests/hash-backend-integration/src/tests/graph/knowledge/primitive/entity.test.ts

Before we migrate to the new permission engine we need to add tests if certain types cannot be instantiated directly. This includes
- `Actor`
- `User`
- `Machine`
- `Organization`
- `HashInstance`
- Add tests for the above entity types
- Add it to the example Cedar file to instantiate
This PR:

H-4397: Add integration tests to make sure instantiation of special system types is not possible

---

apps/hash-frontend/src/pages/process.page/process-editor.tsx
apps/hash-frontend/src/pages/process.page/process-editor/token-type-editor.tsx
apps/hash-frontend/src/pages/process.page/process-editor/types.ts
apps/hash-frontend/src/pages/process.page/process-editor/use-convert-to-pnml.ts
apps/hash-frontend/src/pages/process.page/process-editor/use-load-from-pnml.ts

Adds buttons to export to or import from a PNML file.
Some of the information is non-standard and the exact field names / representation to be used are TBC, but this works to at least save the HASH representation to a file and then load it again later.
This PR:
- Confirm proper representation for things like probabilistic branching, delays.
1. Draw a process then export / import
https://github.com/user-attachments/assets/6f2c2d2b-f10b-432d-9456-cb2a6726edad

H-4436: Add import/export Petri net from/to PNML

---

apps/hash-frontend/src/pages/process.page/process-editor.tsx
apps/hash-frontend/src/pages/process.page/process-editor/editor-context.tsx
apps/hash-frontend/src/pages/process.page/process-editor/place-node.tsx
apps/hash-frontend/src/pages/process.page/process-editor/sidebar.tsx
apps/hash-frontend/src/pages/process.page/process-editor/styling.ts
apps/hash-frontend/src/pages/process.page/process-editor/token-types.tsx
apps/hash-frontend/src/pages/process.page/process-editor/token-types/token-type-editor.tsx
apps/hash-frontend/src/pages/process.page/process-editor/transition-node.tsx
apps/hash-frontend/src/pages/process.page/process-editor/use-layout-graph.ts
apps/hash-frontend/src/pages/process.page/process-editor/use-load-from-pnml.ts

To make it easier to layout and work with the Petri net editor:
1. Add a button to automatically lay out the net nicely (using [elkjs](https://github.com/kieler/elkjs))
2. When loading a net from a file or the example, automatically fit the net to the container
Note that it does NOT:
1. Add a switch to automatically re-layout the net any time a node is added. I tried this and found it extremely annoying, because the algorithm will pack nodes together as soon as they're added, making it a pain to then connect them (since they're tightly packed until connected). There is possibly some tweaking we could do to get a good algorithm in 'auto-layout' mode, maybe only doing autolayout only on connected nodes or similar
2. Automatically layout a net loaded from a file. The user might have manually …

H-4422: Petri net editor auto-layout and fit to viewport

---

libs/@local/hashql/core/src/type/inference/solver/mod.rs
libs/@local/hashql/core/src/type/inference/solver/test.rs

Fixes that we no longer double emit on unconstrained variables, previously, if there was a "floating" variable (as in we constrain `_1 <: _2`) we would create two diagnostics:
1. compiler bug - detected unconstrained variable
2. error - unconstrained variable
This is because the order for both was flipped. We checked if all variables are constrained *after* checking if a variable actually exists. Therefore any error would remove a variable from the final substitution, leading to the compiler bug. The compiler bug is only there in cases where - like the name - suggests - a compiler bug exists, where we *somehow* know of a variable, but don't know where it came wrong. This is highly unusual, and is therefore only a sanity check (but better to have that instead of just silently swallowing …

H-4449: HashQL: Minor type inference solver fixes

---

libs/@local/hashql/core/src/type/environment/simplify.rs
libs/@local/hashql/core/src/type/kind/closure.rs
libs/@local/hashql/core/src/type/kind/intersection.rs
libs/@local/hashql/core/src/type/kind/intrinsic.rs
libs/@local/hashql/core/src/type/kind/opaque.rs
libs/@local/hashql/core/src/type/kind/struct.rs
libs/@local/hashql/core/src/type/kind/tuple.rs
libs/@local/hashql/core/src/type/kind/union.rs

Currently, when we try to simplify and we encounter a recursive type, we simply abort and return the original type. This has the fundamental problem that simplifications naturally "cascade" down on further simplifications, branching of at every recursion point. This is not ideal. Instead we should make use of the proposed API changes in [H-4409](https://linear.app/hash/issue/H-4409/hashql-intern-types). When we first start simplification, we get a provisional id. We then register said id with the simplify functions. Once simplification has hit a recursion point, we return the provisional id. Because that id hasn't been seen yet, the interner will always create a new type, instead of interning and will cascade up to the recursive type, leading to the provisional id to be used.
This PR:
The …

H-4448: HashQL: Recursive types should be simplified more intelligently

---

libs/@local/codegen/src/definitions/fields.rs
libs/@local/codegen/src/typescript.rs
libs/@local/codegen/tests/codegen/snapshots/codegen__EnumAdjacent::Typescript.snap
libs/@local/codegen/tests/codegen/snapshots/codegen__EnumExternal::Typescript.snap
libs/@local/codegen/tests/codegen/snapshots/codegen__EnumUntagged::Typescript.snap
libs/@local/codegen/tests/codegen/snapshots/codegen__StructEmpty::Typescript.snap

We don't have situation where `{}` is appropriate. Instead, we use `Record<string, never>`
This PR:

H-4487: Special-case {} type to `Record<string, never>`

---

libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/fn-params-tuple.jsonc
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/fn-params-type.jsonc
libs/@local/hashql/compiletest/src/executor/mod.rs
libs/@local/hashql/compiletest/src/executor/trial.rs

Before we just ignored the `RunMode`, even though we were parsing it. This change remedies this, by actually enforcing that `RunMode` is as expected.
This PR:

H-4504: HashQL: Compiletest should respect run mode

---

libs/@local/hashql/ast/src/format/dump.rs
libs/@local/hashql/ast/src/lowering/name_mangler.rs
libs/@local/hashql/ast/src/lowering/special_form_expander/mod.rs
libs/@local/hashql/ast/src/node/expr/newtype.rs
libs/@local/hashql/ast/src/visit.rs
libs/@local/hashql/ast/tests/ui/lowering/name-mangler/newtype-generics.jsonc
libs/@local/hashql/ast/tests/ui/lowering/name-mangler/newtype-generics.stdout
libs/@local/hashql/ast/tests/ui/lowering/name-mangler/type-generics-constraints.stdout
libs/@local/hashql/ast/tests/ui/lowering/name-mangler/type-generics-interdependent-generics.stdout
libs/@local/hashql/ast/tests/ui/lowering/name-mangler/type-generics-nested.stdout
libs/@local/hashql/ast/tests/ui/lowering/name-mangler/type-generics.stdout
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/newtype-collect-all-errors.jsonc
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/newtype-collect-all-errors.stderr
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/newtype-constraints.jsonc
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/newtype-constraints.stdout
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/type-generic-constraint.stdout
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/type-generic.stdout

Allow for generics (with constraints) in newtypes, for example:
```
newtype User<T: String> = (name: T, birthday: ZonedDateTime) in
...
```
now works as intended. This is largely a follow-up to https://linear.app/hash/issue/H-4362/hashql-allow-for-generics-on-types as both require the same logic.
This PR:

H-4363: HashQL: Allow for generics on newtypes

---

Cargo.lock
libs/@blockprotocol/type-system/rust/src/knowledge/value/mod.rs
libs/@local/codec/Cargo.toml
libs/@local/codec/src/numeric/real.rs
libs/@local/codegen/src/definitions/mod.rs
libs/@local/codegen/src/definitions/type.rs
libs/@local/codegen/src/lib.rs
libs/@local/codegen/src/typescript.rs
libs/@local/codegen/tests/codegen/main.rs
libs/@local/codegen/tests/codegen/snapshots/codegen__PropertyValue::Typescript.snap
libs/@local/codegen/tests/codegen/snapshots/codegen__Real::Typescript.snap

When two types have the same name the codegen behaves wrongly. In particular with transitive types this is likely to happen.

H-4486: Implement a TypeId to distinguish between different references with the same name

---

libs/@local/codegen/src/definitions/type.rs
libs/@local/codegen/src/lib.rs
libs/@local/codegen/tests/full-exports/snapshots/full_exports__type_system::Typescript.snap

We currently use BTreeMap with TypeId as key while TypeId is an opaque SpectaId. The ID is not stable so the generated files change quite badly eventually.
Instead, we should use a more robust approach, such as putting the module path and name of the type in there as well.
This adds a new internal type 
```rust
struct OrderedTypeId {
module_path: Cow<'static, str>,
name: Cow<'static, str>,
id: SpectaID,
}
```
which is ordered by the module path and the type name before the actual internal ID. The internal ID is only used as a fail-safe if `module_name` and `name` is the same for two types for whatever reason.
This is used as a key in the type collection to determine iteration order. While this might not be the fastest implementation as the key needs to be constructed, it's faster than …

H-4522: Make codegen ordering consistent

---

turbo.json

Ensures ESLint configuration is properly built before running the `fix:eslint` task in Turborepo pipeline.

H-4523: Fix turbos @local/eslint dependency

---

libs/@blockprotocol/type-system/rust/src/bin/export-types.rs
libs/@blockprotocol/type-system/rust/src/knowledge/value/mod.rs
libs/@blockprotocol/type-system/rust/src/utils.rs
libs/@local/codegen/src/typescript.rs
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__MapEnumKey::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__MapNested::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__MapNumericKey::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__MapOptional::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__MapStringKey::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__MapStructValue::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__PropertyValue::Typescript.snap

Record<K, V>might be more readable, however, it cannot be used recursively. E.g. 
```ts
type Property = Property[] | Record<BaseUrl, Property> | PropertyValue;
```
would fail. This, however, works just fine:
```ts
type Property = Property[] | { [key: BaseUrl]: Property } | PropertyValue;
```
- Use index signature notation over `Record`
- Use `PropertyValue` through the new codegen instead of `tsify`
This PR:

H-4516: Use index signatures instead of Record

---

libs/@local/codegen/src/definitions/fields.rs
libs/@local/codegen/src/typescript.rs
libs/@local/codegen/tests/full-exports/snapshots/full_exports__type_system::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__MapOptional::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__StructOptional::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__TupleOptional::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__Web::Typescript.snap

Optional fields (`field?: type`) are different from unions with `undefined` (i.e. `field: type | undefined`). This handles them correctly.

H-4457: Properly handle optional fields

---

libs/@local/hashql/ast/src/format/dump.rs
libs/@local/hashql/ast/src/lowering/import_resolver/mod.rs
libs/@local/hashql/ast/src/lowering/type_extractor/translate.rs
libs/@local/hashql/ast/src/node/type.rs
libs/@local/hashql/ast/src/visit.rs
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/.spec.toml
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-nested.jsonc
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-nested.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-nested.stdout
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-type.jsonc
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-type.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-type.stdout
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-value.jsonc
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-value.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-value.stdout
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/use-not-found.jsonc
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/use-not-found.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/use-not-found.stdout
libs/@local/hashql/compiletest/src/suite/ast_lowering_import_resolver_continue.rs
libs/@local/hashql/compiletest/src/suite/mod.rs

The `ImportResolver` is one of the compilation passes that does not replace many or any nodes with dummy nodes to support continued compilation.
The reason for that is that is simple - any unbound or unknown variable leads to the problem that we're unable to confidently report over any error that's happening and will likely lead to a cascade of issues. Considering that `Dummy` nodes (the replacement) are effectively ignored this shouldn't be *too much* of a problem.
The other problem is just that implementation itself is a bit more obtuse considering the control flow, we operate on a path level, which is present for both types and expressions, to be able to able to mark out specific parts of as dummy nodes we'd need to: (A) introduce a type dummy node and (B) have a way of tracking the if …

H-4531: HashQL: Make `ImportResolver` able to continue compilation

---

libs/@local/hashql/ast/src/lowering/generic_constraint_sanitizer.rs
libs/@local/hashql/ast/src/lowering/mod.rs
libs/@local/hashql/ast/tests/ui/lowering/generic-constraint-sanitizer/.spec.toml
libs/@local/hashql/ast/tests/ui/lowering/generic-constraint-sanitizer/constraint.jsonc
libs/@local/hashql/ast/tests/ui/lowering/generic-constraint-sanitizer/constraint.stderr
libs/@local/hashql/compiletest/src/suite/ast_lowering_generic_constraint_sanitizer.rs
libs/@local/hashql/compiletest/src/suite/mod.rs

These should only be used for `Type` and `Newtype` constructors, so we should error out otherwise.
This PR:

H-4511: HashQL: Implement AST stage to disallow any GenericConstraint's on paths

---

apps/hash-api/src/graph/account-permission-management.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/005-create-hash-system-entities-and-web-bots.migration.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/system-webs-and-entities.ts
apps/hash-api/src/graph/knowledge/system-types/org.ts
libs/@local/graph/api/openapi/openapi.json
libs/@local/graph/api/src/rest/actor_group.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/sdk/typescript/src/principal/team.ts
libs/@local/graph/sdk/typescript/src/principal/web.ts
libs/@local/graph/store/src/account/mod.rs
libs/@local/graph/type-fetcher/src/store.rs
libs/@local/hash-backend-utils/src/hash-instance.ts
libs/@local/hash-backend-utils/src/machine-actors.ts

We want our API surface to be clear and consistent so that developers can intuitively predict function names, expected parameters, and return types. By systematically naming functions as getXById for simple, direct lookups (always returning Value | null), and queryX for filter-based array results, we remove ambiguity and set concrete expectations both for new and experienced SDK users.
- H-4538 -- the parent task of this
This changes the signatures for principal types (we don't have many exposed to the Node API, yet).
This PR:

H-4540: Standardize SDK function naming and return conventions for principal types

---

libs/@local/hashql/ast/src/visit.rs
libs/@local/hashql/core/src/intern/mod.rs
libs/@local/hashql/core/src/intern/set.rs
libs/@local/hashql/hir/src/fold.rs
libs/@local/hashql/hir/src/fold/beef.rs
libs/@local/hashql/hir/src/fold/mod.rs
libs/@local/hashql/hir/src/fold/nested.rs
libs/@local/hashql/hir/src/intern.rs
libs/@local/hashql/hir/src/lib.rs
libs/@local/hashql/hir/src/node/access/field.rs
libs/@local/hashql/hir/src/node/access/index.rs
libs/@local/hashql/hir/src/node/branch/mod.rs
libs/@local/hashql/hir/src/node/call.rs
libs/@local/hashql/hir/src/node/closure.rs
libs/@local/hashql/hir/src/node/data/dict.rs
libs/@local/hashql/hir/src/node/data/struct.rs
libs/@local/hashql/hir/src/node/graph/mod.rs
libs/@local/hashql/hir/src/node/input.rs
libs/@local/hashql/hir/src/node/let.rs
libs/@local/hashql/hir/src/node/mod.rs
libs/@local/hashql/hir/src/node/operation/binary.rs
libs/@local/hashql/hir/src/node/operation/type.rs
libs/@local/hashql/hir/src/node/operation/unary.rs
libs/@local/hashql/hir/src/node/variable.rs
libs/@local/hashql/hir/src/path.rs
libs/@local/hashql/hir/src/visit.rs

Implements two complementary traits for working with the HIR:
* `Visitor` - For immutable traversal of the HIR tree, useful for analysis, linting, and type-checking
* `Fold` - For transforming the HIR tree while preserving node identity where possible
The `Visitor` trait enables immutable traversal of the HIR tree, similar to rustc's [`intravisit`](https://github.com/rust-lang/rust/blob/dbab4e152bd9eed57ccfc096ef6060dd9af45a99/compiler/rustc_hir/src/intravisit.rs#L177) module. It's designed for:
* Linting and static analysis
* Type checking
* Collecting information from the HIR without modifying it
The `Fold` trait supports tree transformations by creating new nodes as needed, inspired by [swc_visit](https://docs.rs/swc_visit/latest/swc_visit/). Key features:
* Uses copy-on-write …

H-4536: HashQL: Implement HIR Visitor traits and infrastructor

---

libs/@blockprotocol/type-system/rust/package.json
libs/@local/codec/package.json
libs/@local/graph/api/openapi/openapi.json
libs/@local/graph/api/src/rest/permissions.rs
libs/@local/graph/authorization/package.json
libs/@local/graph/authorization/src/policies/mod.rs
libs/@local/graph/authorization/src/policies/principal/mod.rs
libs/@local/graph/authorization/src/policies/resource/entity.rs
libs/@local/graph/authorization/src/policies/resource/entity_type.rs
libs/@local/graph/authorization/src/policies/resource/mod.rs
libs/@local/graph/authorization/src/policies/store/error.rs
libs/@local/graph/authorization/src/policies/store/mod.rs
libs/@local/graph/authorization/types/index.snap.d.ts
libs/@local/graph/postgres-store/src/permissions/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/tests/principals/main.rs
libs/@local/graph/postgres-store/tests/principals/policies.rs
libs/@local/graph/sdk/typescript/src/policy.ts
libs/@local/graph/type-fetcher/src/store.rs
tests/hash-backend-integration/src/tests/graph/authorization/policy.test.ts

Policies needs to be queried/created/updated and potentially removed.
The goal is to manage policies from the Node API in the migration files. This means, that we need to query for existing policies to avoid creating duplicate policies. This in particular is important as long as we continue running the same migrations. But it's also required if we only run a migration once because we later need to find these policies.
- to create policies from the Node API
- to remove policies from the Node API
- to update policies from the Node API, i.e. adding another action 
- Move policy creation and deletion to `PolicyStore`
- Implement policy updating
- Expose endpoints
- Implement tests
This PR:
- New tests have been added

H-4334: Expose CRUD operations for Policies

---

libs/@blockprotocol/type-system/rust/types/index.snap.d.ts
libs/@local/codegen/src/definitions/fields.rs
libs/@local/codegen/src/definitions/type.rs
libs/@local/codegen/src/typescript.rs
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__ListOptionals::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__MapOptional::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__StructOptional::Typescript.snap
libs/@local/codegen/tests/standalone-types/snapshots/standalone_types__TupleOptional::Typescript.snap
libs/@local/codegen/tests/standalone-types/structs.rs
libs/@local/codegen/tests/standalone-types/tuples.rs
libs/@local/graph/authorization/src/policies/store/mod.rs
libs/@local/graph/authorization/types/index.snap.d.ts

Passing `null` or passing nothing is different. Even though, `serde_json` does ignore the difference (which, to be honest, is quite annoying), but this does not mean that our generated types should not reflect these changes.

H-4562: Properly distinguish between optionals and nullables in codegen

---

libs/@local/hashql/ast/src/lowering/special_form_expander/mod.rs
libs/@local/hashql/core/src/collection.rs
libs/@local/hashql/core/src/type/environment/analysis.rs
libs/@local/hashql/core/src/type/environment/context/diagnostics.rs
libs/@local/hashql/core/src/type/inference/solver/graph.rs
libs/@local/hashql/core/src/type/inference/solver/mod.rs
libs/@local/hashql/core/src/type/inference/solver/tarjan.rs
libs/@local/hashql/core/src/type/inference/solver/test.rs
libs/@local/hashql/core/src/type/inference/solver/topo.rs

This is required for projections and indices (so field access and indexing into collections), currently these are unsupported. Primarily what we need to do to implement them is fix-point evaluation.
As this means that the hot code will be run more than once, the code now takes more care about it's allocation behaviour, trying to re-use as much space as possible (while still remaining ergonomic). This is done through a multiple systems:
The graph condense algorithm has been implemented in-place, meaning the graph is now persistent (this is required for iteration either way, as we need to keep track of any relationships)
Other operations use a temporary heap, this means the space required we only allocate once in the initial loop, each subsequent loop will re-use the same scratch space, as …

H-4543: HashQL: Implement deferred type checking

---

libs/@local/graph/authorization/src/policies/store/mod.rs
libs/@local/graph/authorization/types/index.snap.d.ts
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
tests/hash-backend-integration/src/tests/graph/authorization/policy.test.ts

Instead of creating an instantiation permission for every single entity type, it's useful to have one more broad permission. In order to create that policy, it's useful to allow updating an existing policy in place instead of removing the old one and creating a new one.

H-4561: Allow updating resource constraints on policies

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/022-add-petri-nets.dev.migration.ts
apps/hash-frontend/src/pages/process.page/process-editor.tsx
apps/hash-frontend/src/pages/process.page/process-editor/editor-context.tsx
apps/hash-frontend/src/pages/process.page/process-editor/editor-context/sub-process-nodes.ts
apps/hash-frontend/src/pages/process.page/process-editor/editor-context/use-persisted-nets.ts
apps/hash-frontend/src/pages/process.page/process-editor/persisted-net-selector.tsx
apps/hash-frontend/src/pages/process.page/process-editor/place-node.tsx
apps/hash-frontend/src/pages/process.page/process-editor/process-edit-bar.tsx
apps/hash-frontend/src/pages/process.page/process-editor/title-and-net-select.tsx
apps/hash-frontend/src/pages/process.page/process-editor/transition-editor.tsx
apps/hash-frontend/src/pages/process.page/process-editor/transition-node.tsx
apps/hash-frontend/src/pages/process.page/process-editor/types.ts
apps/hash-frontend/src/pages/shared/shared/edit-bar-contents.tsx
libs/@local/hash-isomorphic-utils/src/ontology-type-ids.ts
libs/@local/hash-isomorphic-utils/src/system-types/petrinet.ts

Makes the following improvements to the process (Petri net) editor:
1. Show a bar similar to the entity/type editors which indicates when a net has unsaved changes
2. When a sub-process is linked a transition, i.e. the sub-process represents the details of what is going on inside the transition, we want to represent at least one of the input and output places to the transition in the sub-process. The PR makes it so that the user can select the relevant input/output places to represent in the sub-process, and updates the sub-process when these are changed to make sure that corresponding places appear in it.
This PR:
- Styling remains basic / functional, I have not spent much time on it on the assumption that it will be significantly …

H-4496, H-4501: Process editor: add save bar; link input & output places in sub-processes

---

libs/@local/graph/api/openapi/openapi.json
libs/@local/graph/api/src/rest/entity_type.rs
libs/@local/graph/authorization/src/policies/resource/entity_type.rs
libs/@local/graph/postgres-store/src/permissions/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs
libs/@local/graph/sdk/typescript/src/entity-type.ts
libs/@local/graph/store/src/entity_type/store.rs
libs/@local/graph/type-fetcher/src/store.rs
tests/graph/integration/postgres/lib.rs

In some locations, we need to check for a specific permission outside of the graph. For this, we need a function exposed in the Node API.
Implement the logic to query for the instantiation permission. Other permissions can easily be added in the future and this function can be parameterized.
This PR:

H-4565: Expose querying for specific permissions

---

.config/mise/tasks/test/unit.sh
.justfile
libs/@local/codec/package.json
libs/@local/graph/api/package.json
libs/@local/graph/authorization/package.json
libs/@local/graph/postgres-store/package.json
libs/@local/graph/store/package.json
libs/@local/graph/temporal-versioning/package.json
libs/@local/graph/types/package.json
libs/@local/graph/validation/package.json
libs/@local/harpc/codec/package.json
libs/@local/harpc/net/package.json
libs/@local/harpc/tower/package.json
libs/@local/harpc/types/package.json
libs/@local/harpc/wire-protocol/package.json
libs/@local/hashql/ast/package.json
libs/@local/hashql/compiletest/package.json
libs/@local/hashql/core/package.json
libs/@local/hashql/diagnostics/package.json
libs/@local/hashql/hir/package.json
libs/@local/hashql/syntax-jexpr/package.json
libs/antsi/package.json
libs/deer/package.json
libs/error-stack/package.json
libs/sarif/package.json

Currently, most of the crates don't actually upload coverage information to codecov, this PR changes it by creating a mise task that can be used by any crate to do proper coverage, as well as centralizing configuration.
> There are several crates I've chosen not to convert yet, notably I needed to rollback converting both: `hash-graph-authorization` and `hash-graph-postgres-store`. This is left for a follow-up PR as it requires some more plumbing. Tracked in https://linear.app/hash/issue/H-4579/instrument-hash-graph-authorization-and-hash-graph-postgres-store
This PR:

H-4578: Rework Rust crate coverage

---

.github/actions/install-corepack/action.yml
.github/actions/install-tools/action.yml
.github/workflows/ai-pr-review.yml
.github/workflows/bench.yml
.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml

Yarn has a 429 error in CI nowadays, so we need to be a more cautious in downloading yarn, a bit convoluted of a fix, but oh well.
This PR:

H-4584: Cache yarn download in CI

---

apps/hash-frontend/src/pages/shared/entity-type-selector.tsx
apps/hash-frontend/src/pages/shared/entity-type.tsx

A couple of small frontend fixes:
1. Remove a non-functional 'create entity type' button when using the type selector on the 'New Goal' page
2. Correctly skip permission checks for local draft entity types (blocks #7159)
This PR:
At some point we might want to reintroduce the 'create entity type' button to the new goal page, but it isn't a priority.
- Create entity type test covers draft entity type

H-3148, H-4586: Remove non-functional 'create entity type' button, fix draft entity type permission check

---

libs/@local/graph/authorization/src/policies/store/error.rs
libs/@local/graph/postgres-store/src/permissions/error.rs
libs/@local/graph/postgres-store/src/permissions/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs

We need to distinguish between an authenticated actor (= an actor which has an actor type assigned in the database), an unauthenticated actor (= a well-defined actor without a corresponding entry in the database), and an invalid actor (none of the above).
After a lot of attempts to properly handle this, this PR simply handles the public actor when determining the actor type. This results in a `401` (unauthenticated) error for most operations. In the future, we might want to more idiomatically handle the public user case, however, this is a larger undertaking, so we stick with the most simple solution for now (the actual authentication happens in the Node API).

H-4567: Handle public actor explicitly in Graph

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/002-create-system-policies.migration.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/util/upgrade-policies.ts
libs/@blockprotocol/type-system/rust/src/principal/actor/mod.rs
libs/@local/graph/api/src/rest/permissions.rs
libs/@local/graph/authorization/schemas/policies.cedarschema
libs/@local/graph/authorization/src/policies/mod.rs
libs/@local/graph/authorization/src/policies/principal/actor/mod.rs
libs/@local/graph/authorization/src/policies/store/mod.rs
libs/@local/graph/authorization/tests/policies/main.rs
libs/@local/graph/postgres-store/src/permissions/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs
libs/@local/graph/postgres-store/tests/principals/policies.rs
libs/@local/graph/type-fetcher/src/store.rs

[H-4567](https://linear.app/hash/issue/H-4567/properly-handle-public-actors) adds support public actors in general, but we did not have policies with public actor support, yet
- Add a `PublicActor` type which is used in requests by the public actor
- Simplify policy migration in Node and make sure, instantiation permission is only granted to authenticated users.

H-4596: Support the public actor in Cedar

---

libs/@local/graph/postgres-store/src/snapshot/entity/batch.rs
libs/@local/graph/postgres-store/src/snapshot/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/crud.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/data_type.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/property_type.rs
libs/@local/graph/postgres-store/src/store/postgres/query/statement/select.rs
libs/@local/graph/postgres-store/src/store/postgres/traversal_context.rs
libs/@local/graph/postgres-store/src/store/validation.rs
libs/@local/graph/store/src/query/mod.rs
libs/@local/graph/type-fetcher/src/store.rs

When policies are partially evaluated, we want to add that as a dedicated filters.
- Changes the signatures of the `read`-functions to take a slice instead of a simple reference (an iterator would also work, but that makes the signature even more complex, so I chose to use a simple slice here for now)
- Put every call in a slice instead and remove the filter if it's an `all([])`-filter
This PR:

H-4598: Allow multiple filters in a single request in the Postgres query builder

---

apps/hash-api/src/graphql/resolvers/ontology/entity-type.ts
apps/hash-api/src/graphql/resolvers/ontology/property-type.ts
apps/hash-frontend/next.config.js
apps/hash-frontend/src/graphql/queries/ontology/property-type.queries.ts
apps/hash-frontend/src/pages/@/[shortname].page.tsx
apps/hash-frontend/src/pages/@/[shortname].page/pinned-entity-type-tab-contents.tsx
apps/hash-frontend/src/pages/@/[shortname].page/profile-page-content.tsx
apps/hash-frontend/src/pages/@/[shortname].page/profile-page-header.tsx
apps/hash-frontend/src/pages/@/[shortname].page/profile-page-info.tsx
apps/hash-frontend/src/pages/@/[shortname].page/profile-page-tabs.tsx
apps/hash-frontend/src/pages/@/[shortname].page/types-tab.tsx
apps/hash-frontend/src/pages/@/[shortname].page/util.ts
apps/hash-frontend/src/pages/@/[shortname]/[page-slug].page.tsx
apps/hash-frontend/src/pages/shared/types-table.tsx
apps/hash-frontend/src/pages/types/[[...type-kind]].page.tsx
apps/hash-frontend/src/shared/table-header.tsx
libs/@local/hash-isomorphic-utils/src/graphql/type-defs/ontology/property-type.typedef.ts

Adds a 'Types' tab to user / org profile pages, available at `/@[shortname]/types`.
It will show a table of types belonging to that web.
This PR:
1. Visit a profile page
https://github.com/user-attachments/assets/358e2673-152e-4922-b6cb-956109dafcbb

H-1757: Add types tab/table to user/org profile pages

---

tests/hash-backend-integration/src/tests/graph/knowledge/system-types/ai.test.ts

Previously, we had users and machines, now we have users, machines, and AIs. The AI assistant is called hash-ai, however, we read them from the graph using `getMachineByIdentifier`.
- H-4621: Fix AI assistant retrieval from the graph
This adds a (currently failing) test which attempts to read the AI assistant from the graph.

H-4620: Investigate if reading the hash-ai machine is buggy

---

Cargo.lock
Cargo.toml
libs/@local/hashql/ast/Cargo.toml
libs/@local/hashql/ast/src/lowering/import_resolver/error.rs
libs/@local/hashql/ast/src/lowering/import_resolver/mod.rs
libs/@local/hashql/ast/src/lowering/special_form_expander/error.rs
libs/@local/hashql/ast/src/lowering/type_extractor/error.rs
libs/@local/hashql/ast/src/lowering/type_extractor/translate.rs
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-nested.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-type.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/unresolved-value.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/continue/use-not-found.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/glob-not-found.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/item-not-found.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/module-not-found.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/rollback.stderr
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/unresolver-variable.stderr
libs/@local/hashql/core/Cargo.toml
libs/@local/hashql/core/src/lib.rs
libs/@local/hashql/core/src/module/error.rs
libs/@local/hashql/core/src/module/locals.rs
libs/@local/hashql/core/src/module/mod.rs
libs/@local/hashql/core/src/module/namespace.rs
libs/@local/hashql/core/src/module/resolver.rs
libs/@local/hashql/core/src/similarity.rs
libs/@local/hashql/core/src/symbol/mod.rs

Currently we're using `jaro_winkler` in conjunction with a threshold directly, instead `hashql_core` should have a function dedicated to this, so that we don't have `> 0.7` floating around everywhere and we're free to change the internal implementation.
This adds a new function modeled similar to [what rustc does](https://github.com/rust-lang/rust/blob/master/compiler/rustc_span/src/edit_distance.rs). We basically have a 3 step process, rewarding prefix and postfix similarities.
Overall this results in fewer but _more meaningful_ suggestions.
This PR:

H-4532: HashQL: Unify string similarity infrastructure

---

libs/@local/hashql/core/src/type/environment/infer.rs
libs/@local/hashql/core/src/type/inference/mod.rs
libs/@local/hashql/core/src/type/inference/solver/mod.rs
libs/@local/hashql/core/src/type/inference/solver/test.rs
libs/@local/hashql/core/src/type/kind/opaque.rs

Replace this in favour with a new constraint (`Constraint::Unify`) this is required, as [H-4545](https://linear.app/hash/issue/H-4545/hashql-implement-subscript-type-inferencechecking) may discharge additional constraints.
This PR:

H-4635: Remove `Unification` from `InferenceEnvironment`

---

.github/workflows/hash-backend-cd.yml

We have a few images (node API, workers) which will immediatly deploy as soon as they are all finished. We can block this at least on the graph image, so they will at least not deploy before the graph. There is no guarantee, that it will start deploying before the graph has finished, but it’s better than almost always start deploying before the graph starts.

H-4642: Don't deploy node images before Rust image has been finished

---

libs/@local/hashql/core/src/type/kind/union.rs

This pull request implements the `subscript` method for `UnionType` in the `Lattice` trait.
This PR:

H-4644: HashQL: Implement `Subscript` for Unions

---

libs/@local/hashql/core/src/lib.rs
libs/@local/hashql/core/src/type/environment/infer.rs
libs/@local/hashql/core/src/type/inference/mod.rs
libs/@local/hashql/core/src/type/inference/solver/mod.rs
libs/@local/hashql/core/src/type/inference/solver/test.rs
libs/@local/hashql/core/src/type/kind/intersection.rs
libs/@local/hashql/core/src/type/test.rs

Implements `Subscript` for intersections. Which is largely the same as unions, additionally allows for solving selection constraints across complex unions and intersections. Which was required for the `multi_subscript` test case.
---
Selection constraints may require the need for simplification. In cases like:
```
(List<T> | Null) & List<T>
```
This shouldn't fail, because `List<T>` is the only one that actually survives this "encounter".
To be able to do that we need to simplify the type. The problem is that during simplification any resolved types are made "concrete". Which means that any constraint issued won't register for the variable.
To combat this we do fix-point evaluation, where we first try to index using an unsimplified version, and if that fails we fallback to the next …

H-4645, H-4659: HashQL: Implement `Subscript` for Intersections

---

.config/mise/config.toml
Cargo.lock

Recurring task to bump dependencies
- `mise upgrade --bump`
- Revert `node` version to v22
- `cargo update --ignore-rust-version --recursive`

H-4589, H-4590: Bump tool and transitive cargo dependencies

---

infra/terraform/hash/hash_application/outputs.tf
infra/terraform/hash/outputs.tf

We want to be able to refer to the task role running HASH ECS task roles elsewhere, which involves exposing it as an `output` from the Terraform config.
This PR:

H-4696: Expose ECS task role ARN from Terraform state

---

apps/hash-frontend/src/pages/shared/entity/shared/entity-editor-tabs.tsx

When viewing a page for a draft entity, the URLs generated for the tabs (e.g. Overview, History) incorrectly duplicated the `draftId` param from the URL, causing a malformed request to the API (and the URL to be wrong).
This PR fixes that.
This PR:
1. View a draft entity, check that switching to the History tab doesn't end up with multiple `draftId` in URL

H-4745: Fix URL generation for entity tabs when draftId present

---

infra/terraform/hash/hash_application/outputs.tf
infra/terraform/hash/outputs.tf

I need the role name to use in Vault config hosted elsewhere, so adding it to the Terraform state, from which it can be accessed elsewhere.

H-4759: Expose ECS task role name from Terraform state

---

.github/workflows/lint.yml
apps/hash-ai-worker-ts/src/activities/shared/get-llm-response.ts
apps/hash-api/src/graphql/resolvers/knowledge/entity/entity.ts
apps/hash-integration-worker/src/linear-activities.ts
libs/@local/graph/postgres-store/src/store/postgres/seed_policies.rs
libs/@local/hash-backend-utils/src/service-usage.ts

A few inconsistencies are remaining between the old SpiceDB based policy engine and the new engine:
- `incurred-in` entities should have the same policies as `usage-record` and `records-usage-of`
- Web-admins should have access to these as well
- When manually creating relationships, policies are not updated (i.e. `viewer` permissions`
- synchronized linear link-entities get a permission, but the source entity does not
- view permissions for the system actor on
- triggered-by-user
- occurred-in-block
- occurred-in-entity
- occurred-in-comment
- occurred-in-text
This PR:

H-4726: Fix inconsistencies between `viewer` relationship and `viewEntity` policy action

---

infra/terraform/modules/bastion/main.tf

Terraform `plan` and `apply` have started failing with this message:
```
Error: Your query returned no results. Please change your search criteria and try again.
with module.bastion.data.aws_ami.amazon_linux,
on ../modules/bastion/main.tf line 16, in data "aws_ami" "amazon_linux":
16: data "aws_ami" "amazon_linux" {
```
The block the error references contains this filter:
```
filter {
name = "name"
values = [
"amzn2-ami-hvm-2.0.20230612.0-x86_64-gp2",
]
}
```
so my theory is that this 2023 AMI image has been removed, or similar. This PR updates to a newer one that appears in the list returned by the command in that code block.
1. See that `terraform plan` works in CI, whereas all other recent invocations are failing

H-4786: Update bastion host ami image

---

libs/@local/hashql/compiletest/src/executor/mod.rs
libs/@local/hashql/compiletest/src/executor/trial_group.rs
libs/@local/hashql/compiletest/src/lib.rs
libs/@local/hashql/compiletest/src/reporter.rs
libs/@local/hashql/compiletest/src/suite/mod.rs

Panics in compiletest are currently quite opaque, as they do not have any backtraces and sometimes the output of tracing just removes them from the output.
Using `catch_unwind` and a custom hook we're able to make the error clearer.
> Sadly no output, because well... you need to have an error for that to happen.
This PR:

H-4783: HashQL: Improve compiletest panics

---

apps/hash-frontend/src/pages/settings/integrations/linear/use-linear-integrations.ts

The query path is different for `getEntitySubgraph` versus the old BP filter queries, this PR fixes a place when fetching Linear integrations where the old version wasn't translated to the new.

H-4810: Fix Linear integrations query

---

Cargo.lock
libs/@local/graph/api/src/rest/entity_type.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/read.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/data_type.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/property_type.rs
libs/@local/graph/type-fetcher/src/store.rs
libs/@local/repo-chores/rust/bin/cli/subcommand/dependency_diagram/mod.rs
libs/@local/repo-chores/rust/src/dependency_diagram/mod.rs
libs/error-stack/tests/test_span_trace.rs

Renovate currently does not cover all transitive cargo dependency. To update them manually, the easiest way is to use
- `cargo update --ignore-rust-version --recursive`

H-4702: Bump transitive Cargo dependencies

---

infra/terraform/hash/bastion.md
infra/terraform/hash/networking/main.tf
infra/terraform/hash/outputs.tf
infra/terraform/modules/bastion/output.tf

This PR modernizes AWS infrastructure access by implementing SSM Session Manager connectivity and eliminating SSH tunneling dependencies. VPC interface endpoints have been deployed to enable secure, keyless access to bastion hosts and database tunneling without requiring SSH key management or NAT Gateway dependencies.
- **Deployed VPC interface endpoints**: Added SSM endpoints for private subnet connectivity
- **Eliminated SSH dependency**: Replaced complex SSH tunneling scripts with simple AWS SSM commands
- **Added Terraform outputs**: Exported bastion instance ID for seamless automation
This PR:
None. This is a pure infrastructure modernization with enhanced security and simplified access patterns.
- ✅ SSM Session Manager direct shell …

H-4813: Allow connecting to Bastion using AWS SSM

---

apps/hash-ai-worker-ts/src/activities/shared/get-llm-response.ts
apps/hash-api/src/graph/knowledge/system-types/user-secret.ts
libs/@local/graph/authorization/schemas/policies.cedarschema
libs/@local/graph/authorization/src/policies/cedar/actor.rs
libs/@local/graph/authorization/src/policies/cedar/expression_tree.rs
libs/@local/graph/authorization/src/policies/cedar/mod.rs
libs/@local/graph/authorization/src/policies/components.rs
libs/@local/graph/authorization/src/policies/context.rs
libs/@local/graph/authorization/src/policies/evaluation/mod.rs
libs/@local/graph/authorization/src/policies/mod.rs
libs/@local/graph/authorization/src/policies/principal/actor/ai.rs
libs/@local/graph/authorization/src/policies/principal/actor/machine.rs
libs/@local/graph/authorization/src/policies/principal/actor/mod.rs
libs/@local/graph/authorization/src/policies/principal/actor/user.rs
libs/@local/graph/authorization/src/policies/resource/entity.rs
libs/@local/graph/authorization/src/policies/resource/entity_type.rs
libs/@local/graph/authorization/tests/policies/main.rs
libs/@local/graph/authorization/types/index.snap.d.ts
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/seed_policies.rs
libs/@local/graph/store/src/filter/mod.rs
libs/@local/hash-backend-utils/src/service-usage.ts

For some entity types we require that only the entity creator can see the entity, for example for the `usage-record`s, not every member of the web should see them but only the admins and the creators.
- Implement a resource filter `createdByPrincipal`
- Remove per-entity policy for `incurred-in` entities
- Remove per-entity policy for entity creator for `usage-record`, `user-secret`, and `records-usage-of` entities
This PR:

H-4699: Support policy resource filter on the creator

---

apps/hash-ai-worker-ts/package.json
apps/hash-api/package.json
apps/hash-integration-worker/package.json

CI integration tests were failing because workers weren't becoming alive within the timeout period. Workers need to wait for `hash-api` to become alive first before they can pass their own healthchecks.
- `hash-integration-worker` (`apps/hash-integration-worker/package.json:18,20`): Increased healthcheck timeout from 300000ms (5 min) to 600000ms (10 min)
- `hash-ai-worker-ts` (`apps/hash-ai-worker-ts/package.json:38,40`): Increased healthcheck timeout from 300000ms (5 min) to 600000ms (10 min)
- Align `hash-api` timeout to also use 10 min.

H-4865: Increase timeout for healthchecks for Workers

---

libs/@local/graph/authorization/src/policies/components.rs
libs/@local/graph/authorization/src/policies/store/error.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs
libs/@local/graph/store/src/filter/mod.rs

This PR refactors the policy evaluation system to enable direct conversion from Cedar policies to database filters, setting the foundation for future policy filter optimizations. The main goal is to solve lifetime issues that were blocking OR-to-IN clause optimizations in policy-based database queries.
- **Refactor PolicyComponents structure**: Separate raw policy storage from PolicySet creation
- `PolicyComponents` now stores `Vec<Policy>` directly instead of pre-built `PolicySet`
- Add lazy `create_policy_set()` method that builds PolicySet only when needed for Cedar evaluation
- Update all `PolicySet` usage sites to use the new lazy creation pattern
- **Add direct policy-to-filter conversion**: New `Filter::for_policies()` method
- Converts policy constraints directly to database …

H-4827: Allow direct conversion from policies to filters

---

libs/@local/graph/postgres-store/src/store/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/query/compile.rs
libs/@local/graph/postgres-store/src/store/postgres/query/expression/join_clause.rs
libs/@local/graph/postgres-store/src/store/postgres/query/expression/order_clause.rs
libs/@local/graph/postgres-store/src/store/postgres/query/expression/where_clause.rs
libs/@local/graph/postgres-store/src/store/postgres/query/expression/with_clause.rs
libs/@local/graph/postgres-store/src/store/postgres/query/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/query/statement/insert.rs
libs/@local/graph/postgres-store/src/store/postgres/query/statement/window.rs
libs/@local/graph/postgres-store/src/store/postgres/query/table.rs
libs/@local/graph/postgres-store/src/store/postgres/traversal_context.rs

Improves the documentation of several types in `hash-graph-postgres-store`, by adding error documentation and `must_use` where required.
This PR:

H-4879: Improve documentation of `hash-graph-postgres-store`

---

libs/@local/graph/authorization/src/policies/components.rs
libs/@local/graph/postgres-store/src/store/postgres/crud.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/read.rs
libs/@local/graph/postgres-store/src/store/postgres/query/compile.rs
libs/@local/graph/postgres-store/src/store/validation.rs

I prepared everything in order to use the new `viewEntity` policy action and stop relying on SpiceDB for entity queries. This changes the implementation in the Graph.
- #7350 
- #7496 
All usages of `EntityPermission::View` has been replaced with the appropriated call to the new policy engine.
This PR:
- https://github.com/hashintel/hash/pull/7351
Pretty much every test around entities implicitly tests this
Start the application and make sure everything is still working as expected

H-847, H-4433: Use `viewEntity` policy over `viewer` relationships in the Graph

---

libs/@local/graph/authorization/schemas/policies.cedarschema
libs/@local/graph/authorization/src/policies/action/mod.rs
libs/@local/graph/authorization/src/policies/components.rs
libs/@local/graph/authorization/types/index.snap.d.ts
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/read.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/ontology/entity_type.rs
libs/@local/graph/postgres-store/src/store/postgres/seed_policies.rs
libs/@local/graph/postgres-store/src/store/validation.rs

This PR implements Cedar-based authorization for entity creation by introducing the `CreateEntity` action. Previously, entity creation authorization was handled through Zanzibar permissions, but as part of the migration to Cedar-based authorization, we now have a dedicated Cedar action that provides more granular and consistent authorization control for entity creation operations.
- **Adds `CreateEntity` Cedar action**: New action in the Cedar schema that inherits from `Create` and applies to Web resources
- **Implements per-action optimization**: Refactors `PolicyComponents` to support per-action optimization instead of global optimization, allowing selective optimization of different actions
- **Updates entity creation authorization**: Replaces Zanzibar-based entity creation checks with …

H-4891: Introduce `CreateEntity` permission and fix policy optimization logic

---

libs/@local/graph/store/src/subgraph/temporal_axes.rs

Currently the `QueryTemporalAxesUnresolved` can only be resolved to the current time (`now`) as it means that we're unable to reliably use it during tests that make use of snapshots, as the time is **(usually)** monotonically increasing.
This changes it to introduce a new method that takes a `Timestamp` as `now`, and uses that instead.
This PR:

H-4884: Allow resolving the query temporal axes relative to a specific now

---

libs/@local/graph/store/src/filter/path.rs

Currently a `JsonPath` is constructed in an all or nothing fashion from a vector of path tokens. This changes it so that the `JsonPath` can be built up incrementally by pushing tokens.
This PR:

H-4885: Allow for incremental building of `JsonPath`

---

README.md

This may happen if `turbo` tries to run multiple `cargo` commands at the same time.

H-4937: Mention `rustup toolchain install` in README

---

apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/007-create-api-usage-tracking.migration.ts
apps/hash-api/src/graph/ensure-system-graph-is-initialized/migrate-ontology-types/migrations/017-add-use-case-form-and-example-org.migration.ts
apps/hash-api/src/graph/knowledge/system-types/org.ts
apps/hash-api/src/graph/knowledge/system-types/user.ts
apps/hash-frontend/src/lib/user-and-org.ts
apps/hash-frontend/src/pages/_app.page.tsx

In a few places in the Node API and frontend we check if an entity is a user or org by matching against the latest user/org `entityTypeId` in the codebase… but in cases where we deploy a change to user or org types, until the backend successfully deploys and upgrades users/orgs, these checks will throw errors because the user/org is on an older version.
This means if the new frontend deploys before the backend has migrated (likely), the app will crash until the migrations have caught up.
Ideally everything would deploy in the same moment, but as this is very hard the better thing is to relax the check so we're checking against type base URL, not including the version. This PR does that.
This PR:

H-4949: Relax user and org entity type matching

---

libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/read.rs

Fix panic caused by empty PostgreSQL temporal ranges in entity edge queries. This addresses a non-reproducible panic where the temporal versioning library would fail to parse empty ranges returned from PostgreSQL range intersection operations.
- H-4210
- [Slack thread](https://hashintel.slack.com/archives/CJ1GD3Q84/p1741694092213449)
- [Sentry issue](https://hashintel.sentry.io/issues/6385183858)
- Adds a `NOT isempty()` check to the SQL query in `read_knowledge_edges` to prevent empty temporal range intersections from being returned
- Preserves the existing pairwise overlap checks (`&&` operators) for query performance optimization
- Prevents the panic that occurs when the Rust temporal versioning library tries to parse an empty PostgreSQL range
The root cause was that even with pairwise …

H-4210: Fix panic from empty PostgreSQL temporal ranges in entity queries

---

libs/@local/graph/authorization/schemas/policies.cedarschema
libs/@local/graph/authorization/src/policies/components.rs
libs/@local/graph/postgres-store/src/lib.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/seed_policies.rs
libs/@local/graph/store/src/entity/store.rs
libs/@local/graph/type-fetcher/src/store.rs
tests/graph/integration/postgres/lib.rs

This PR implements the changes described in H-4929 to transition from using `Web` resources to `Entity` resources for the `CreateEntity` permission. This change provides more granular control over entity creation by allowing filtering by entity type, actor type restrictions, and even specific entity creation permissions.
- **Authorization Schema**: Changed `createEntity` action in Cedar schema to use `Entity` resource instead of `Web` resource
- **Policy Components**: Added entity type tracking and entity resource context building capabilities
- **Entity Creation Logic**: Replaced web-based authorization with entity-based authorization, including early permission checks for both `Instantiate` and `CreateEntity` actions
- **Seed Policies**: Updated policy generation to use …

H-4929: Change `CreateEntity` permission to use an `Entity`-resource

---

libs/@local/graph/authorization/schemas/policies.cedarschema
libs/@local/graph/authorization/src/policies/action/mod.rs
libs/@local/graph/authorization/src/policies/cedar/expression_tree.rs
libs/@local/graph/authorization/src/policies/components.rs
libs/@local/graph/authorization/src/policies/context.rs
libs/@local/graph/authorization/src/policies/mod.rs
libs/@local/graph/authorization/src/policies/principal/actor/mod.rs
libs/@local/graph/authorization/src/policies/resource/data_type.rs
libs/@local/graph/authorization/src/policies/resource/entity.rs
libs/@local/graph/authorization/src/policies/resource/entity_type.rs
libs/@local/graph/authorization/src/policies/resource/meta.rs
libs/@local/graph/authorization/src/policies/resource/mod.rs
libs/@local/graph/authorization/src/policies/resource/property_type.rs
libs/@local/graph/authorization/src/policies/store/error.rs
libs/@local/graph/authorization/src/policies/store/mod.rs
libs/@local/graph/authorization/types/index.snap.d.ts
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/seed_policies.rs
libs/@local/graph/postgres-store/tests/principals/main.rs
libs/@local/graph/postgres-store/tests/principals/policies.rs
libs/@local/graph/store/src/filter/mod.rs
tests/hash-backend-integration/src/tests/graph/authorization/policy.test.ts

This PR implements meta-permissions for policy management in HASH's authorization system. It establishes who can create, update, and delete policies by introducing a new `Policy` entity type in Cedar schema and implementing resource constraints that scope policy management permissions to appropriate actor roles.
The implementation follows the principle that policy management should be restricted by resource constraints - web administrators can manage policies within their web scope, while preventing unauthorized global policy creation that could lead to privilege escalation.
- [H-4825: Explore meta-permissions — Who can manage policies?](https://linear.app/hash/issue/H-4825/explore-meta-permissions-who-can-manage-policies)
- N/A
- Add `Policy` entity type with `actions: Set<String>` …

H-4825: Implement initial meta-policy handling

---

libs/@local/graph/authorization/src/policies/cedar/mod.rs
libs/@local/graph/authorization/src/policies/principal/actor/ai.rs
libs/@local/graph/authorization/src/policies/principal/actor/machine.rs
libs/@local/graph/authorization/src/policies/principal/actor/mod.rs
libs/@local/graph/authorization/src/policies/principal/actor/user.rs
libs/@local/graph/authorization/src/policies/principal/group/team.rs
libs/@local/graph/authorization/src/policies/principal/group/web.rs
libs/@local/graph/authorization/src/policies/principal/role/team.rs
libs/@local/graph/authorization/src/policies/principal/role/web.rs
libs/@local/graph/authorization/src/policies/resource/data_type.rs
libs/@local/graph/authorization/src/policies/resource/entity.rs
libs/@local/graph/authorization/src/policies/resource/entity_type.rs
libs/@local/graph/authorization/src/policies/resource/meta.rs
libs/@local/graph/authorization/src/policies/resource/property_type.rs
libs/@local/graph/postgres-store/src/snapshot/mod.rs
libs/@local/graph/postgres-store/src/snapshot/policy/batch.rs
libs/@local/graph/postgres-store/src/store/postgres/seed_policies.rs

We encountered a panic in production when using `ast::Entity::new()`:
```
thread 'main' panicked at libs/@local/graph/authorization/src/policies/resource/meta.rs:62:10:
Policy should be a valid Cedar entity: EntityAttrEvaluationError { uid: EntityUID(EntityUIDImpl { ty: EntityType(Name(InternalName { id: Id("Policy"), path: [Id("HASH")], loc: None })), eid: Eid("521b8df8-662f-4730-b7c6-049ef7e4f0e6"), loc: None }), attr_or_tag: "actions", was_attr: true, err: RecursionLimit(RecursionLimitError { source_loc: None }) }
stack backtrace:
0: __rustc::rust_begin_unwind
at ./rustc/9982d6462bedf1e793f7b2dbd655a4e57cdf67d4/library/std/src/panicking.rs:697:5
1: core::panicking::panic_fmt
at ./rustc/9982d6462bedf1e793f7b2dbd655a4e57cdf67d4/library/core/src/panicking.rs:75:14
2: …
```

H-5025: Use an `ast::Value` instead of an `ast::Expr` for Cedar entity creation

---

libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/seed_policies.rs

We don't need to check permissions when seeding the default policies

H-5033: Avoid checking permissions when database seeding happens

---

.env.development
infra/terraform/hash/hash_application/api.tf
infra/terraform/hash/hash_application/graph.tf
infra/terraform/hash/hash_application/hydra.tf
infra/terraform/hash/hash_application/kratos.tf
infra/terraform/hash/hash_application/main.tf
infra/terraform/hash/hash_application/otel_collector.tf
infra/terraform/hash/hash_application/temporal_worker_ai_ts.tf
infra/terraform/hash/hash_application/temporal_worker_integration.tf
infra/terraform/hash/hash_application/type_fetcher.tf

Implements a local OpenTelemetry Collector in the app cluster to provide telemetry collection for all services. This follows an Agent-to-Gateway pattern where the local collector acts as an agent receiving telemetry from all app services and can later be configured to forward to the observability cluster gateway.
- **`otel_collector.tf`**: Complete ECS service implementation with:
- S3-based configuration using config-downloader pattern
- Service Connect integration for HTTP (4318) and gRPC (4317) endpoints
- Debug exporter for initial telemetry validation
- Proper security groups and IAM permissions
- **All services** now include `HASH_OTLP_ENDPOINT` environment variable pointing to local collector
- **Kratos/Hydra**: Added OTLP-specific environment variables for OpenTelemetry …

H-4988: Add OpenTelemetry collector to `app` cluster

---

.github/workflows/test.yml
libs/@local/telemetry/src/logging/mod.rs

When a graph error in CI happens it's very hard to find it. This is because it's spammed with INFO level logs. Sometimes these logs are helpful, but often they're not. We should set the terminal logging level in CI to WARN and emit a more verbose output to a file, which we should upload as artifact.

H-4991: Write background log files in CI and upload them on completion; Set terminal logging to WARN

---

CLAUDE.md
infra/terraform/hash/observability/grafana/config.tf
infra/terraform/hash/observability/grafana/security_groups.tf
infra/terraform/hash/observability/grafana/templates/grafana.ini.tpl
infra/terraform/hash/observability/grafana/templates/provisioning/datasources/loki.yaml.tpl
infra/terraform/hash/observability/grafana/templates/provisioning/datasources/tempo.yaml.tpl
infra/terraform/hash/observability/grafana/variables.tf
infra/terraform/hash/observability/loki/config.tf
infra/terraform/hash/observability/loki/iam.tf
infra/terraform/hash/observability/loki/main.tf
infra/terraform/hash/observability/loki/outputs.tf
infra/terraform/hash/observability/loki/security_groups.tf
infra/terraform/hash/observability/loki/service.tf
infra/terraform/hash/observability/loki/storage.tf
infra/terraform/hash/observability/loki/templates/loki.yaml.tpl
infra/terraform/hash/observability/loki/variables.tf
infra/terraform/hash/observability/main.tf
infra/terraform/hash/observability/otel_collector/config.tf
infra/terraform/hash/observability/otel_collector/security_groups.tf
infra/terraform/hash/observability/otel_collector/templates/otel-collector.yaml.tpl
infra/terraform/hash/observability/otel_collector/variables.tf

This PR implements Loki log aggregation service in the AWS observability infrastructure to complete the telemetry stack alongside existing Tempo (tracing) and OpenTelemetry Collector components. Loki provides centralized log storage and querying capabilities with S3 backend storage and integrates seamlessly with Grafana for log visualization and correlation with traces.
- https://github.com/hashintel/hash/pull/7690
- **Creates complete Loki service infrastructure** in `infra/terraform/hash/observability/loki/`:
- ECS task definition and service configuration with Fargate deployment
- S3 bucket for log storage with 7-day lifecycle policy (consistent with Tempo)
- IAM roles with least-privilege permissions for S3 config and log storage access
- Security groups allowing HTTP API access from …

H-5059: Set up Loki in AWS

---

libs/@local/graph/authorization/src/policies/store/error.rs
libs/@local/graph/authorization/src/policies/store/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/knowledge/entity/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/mod.rs
libs/@local/graph/postgres-store/src/store/postgres/seed_policies.rs
libs/@local/graph/postgres-store/tests/principals/main.rs

While we don't necessarily need batch-creation of policies in production, seeding tests and benchmarks are quite slow without it.
Change the internal `insert_policy_into_database` to take a batch of policies.
This PR:

H-4628: Allow batch-creation of policies

---

tests/graph/benches/Cargo.toml
tests/graph/benches/manual_queries/lib.rs
tests/graph/benches/package.json
tests/graph/benches/policy/benchmark_matrix.rs
tests/graph/benches/policy/lib.rs
tests/graph/benches/policy/seed.rs
tests/graph/benches/util.rs

Add comprehensive benchmarking infrastructure for policy resolution performance testing in HASH's authorization system. This implementation creates scalable benchmark datasets and measures policy resolution query performance across different user types, data volumes, and action selectivity patterns.
**Comprehensive data generation with realistic authorization patterns:**
- **SeedConfig system** with 4 preset scales (Small→ExtraLarge):
- Small: ~200 policies (3 users, 2 webs)
- Medium: ~1,100 policies (10 users, 5 webs)
- Large: ~32,000 policies (50 users, 10 webs)
- ExtraLarge: ~767,000 policies (100 users, 25 webs)
- **Hierarchical team structure creation** that triggers recursive CTE performance patterns:
```rust
create_team_hierarchy(web_id, teams_per_web, nesting_depth, …
```

H-5149: Add comprehensive policy resolution benchmarking infrastructure

---

infra/terraform/hash/main.tf

The TS workers currently hsare 1 GB RAM. This works, but they're constantly using 80% of the memory and only spiking a bit would OOM them.

H-5158: Increase memory limit for TS workers

---

libs/@local/graph/postgres-store/src/store/postgres/query/compile.rs

We have _a lot_ of spans on `compile_special_filter` in the Graph. Most of these calls are no-ops. I changed the instrumentation to observe the inner function instead to greatly reduce the noise and make this actually useful.

H-5157: Properly instrument special filter compilation

---

libs/@blockprotocol/type-system/rust/src/ontology/entity_type/schema/mod.rs
libs/@local/graph/store/src/entity_type/store.rs
tests/graph/benches/config/producers/entity_types/basic.json
tests/graph/benches/config/producers/entity_types/with_properties.json
tests/graph/benches/config/scenarios/full_ontology_seeding.json
tests/graph/benches/graph/config/mod.rs
tests/graph/benches/graph/scenario/runner.rs
tests/graph/benches/graph/scenario/stages/data_type.rs
tests/graph/benches/graph/scenario/stages/entity_type.rs
tests/graph/benches/graph/scenario/stages/mod.rs
tests/graph/benches/graph/scenario/stages/property_type.rs
tests/graph/test-data/rust/src/seeding/context.rs
tests/graph/test-data/rust/src/seeding/distributions/ontology/entity_type/mod.rs
tests/graph/test-data/rust/src/seeding/distributions/ontology/entity_type/properties.rs
tests/graph/test-data/rust/src/seeding/distributions/ontology/mod.rs
tests/graph/test-data/rust/src/seeding/distributions/ontology/property_type/values.rs
tests/graph/test-data/rust/src/seeding/producer/data_type.rs
tests/graph/test-data/rust/src/seeding/producer/entity_type.rs
tests/graph/test-data/rust/src/seeding/producer/mod.rs
tests/graph/test-data/rust/src/seeding/producer/ontology/domain.rs
tests/graph/test-data/rust/src/seeding/producer/ontology/mod.rs
tests/graph/test-data/rust/src/seeding/producer/property_type.rs

This PR completes the ontology seeding pipeline by implementing EntityType automatic generation for the HASH graph benchmarking infrastructure. Building on the existing DataType and PropertyType producers, this adds the final piece to enable comprehensive ontology performance testing with deterministic test data generation.
The implementation follows the established patterns from PropertyType seeding, providing EntityType producers with configurable property distributions, domain policies, and catalog-based dependency management.
**Core EntityType Producer Implementation:**
- `tests/graph/test-data/rust/src/seeding/producer/entity_type.rs` - New `EntityType` producer with `PropertyType` catalog dependencies
- `tests/graph/test-data/rust/src/seeding/distributions/ontology/entity_type/` - …

H-5213: Add EntityType generation with PropertyType dependencies

---

tests/graph/benches/graph/scenario/runner.rs
tests/graph/test-data/rust/src/seeding/context.rs
tests/graph/test-data/rust/src/seeding/distributions/mod.rs
tests/graph/test-data/rust/src/seeding/distributions/value/mod.rs
tests/graph/test-data/rust/src/seeding/distributions/value/number.rs
tests/graph/test-data/rust/src/seeding/distributions/value/string.rs
tests/graph/test-data/rust/src/seeding/producer/data_type.rs
tests/graph/test-data/rust/src/seeding/producer/entity_type.rs
tests/graph/test-data/rust/src/seeding/producer/mod.rs
tests/graph/test-data/rust/src/seeding/producer/property_type.rs
tests/graph/test-data/rust/src/seeding/producer/user.rs
tests/graph/test-data/rust/src/seeding/producer/value.rs

This PR implements value generation capabilities for the test data seeding framework, enabling the creation of valid `PropertyValue` instances from `ValueConstraints` definitions. This is a critical component for generating realistic test data that respects JSON schema constraints defined in data types.
The implementation provides distribution-based sampling for primitive value types (null, boolean, number, string), laying the groundwork for comprehensive property type testing with deterministic, reproducible test data.
- Linear Issue: [H-5214](https://linear.app/hash/issue/H-5214)
- Related PRs:
- [H-5198: PropertyType generation MVP](https://github.com/hashintel/hash/pull/7736)
- [H-5174: Initial deterministic seeding functionality](https://github.com/hashintel/hash/pull/7727)
- …

H-5214: Implement distribution-based value sampling for string and number schemas

---

apps/hash-frontend/vercel-install.sh

For some reason, `wasm-opt` cannot be downloaded in Vercel anymore. Typically, this means that `mise` will fallback to build it. However, `rust` is installed _after_ the attempt to install `wasm-opt`

BE-1: Fix Vercel not building wasm-opt

---

apps/hash-frontend/vercel-install.sh

This caused Vercel builds to fail

SRE-24: Prevent Vercel build step from downloading Rust multiple times

---

libs/@local/hashql/syntax-jexpr/src/parser/array/error.rs
libs/@local/hashql/syntax-jexpr/src/parser/array/mod.rs
libs/@local/hashql/syntax-jexpr/src/parser/array/snapshots/hashql_syntax_jexpr__parser__array__tests__parse_function_call_with_empty_object.snap
libs/@local/hashql/syntax-jexpr/src/parser/array/snapshots/hashql_syntax_jexpr__parser__array__tests__parse_function_call_with_labeled_arguments_shorthand.snap
libs/@local/hashql/syntax-jexpr/src/parser/array/snapshots/hashql_syntax_jexpr__parser__array__tests__parse_function_call_with_multiple_labeled_arguments.snap
libs/@local/hashql/syntax-jexpr/src/parser/array/snapshots/hashql_syntax_jexpr__parser__array__tests__parse_malformed_labeled_argument.snap
libs/@local/hashql/syntax-jexpr/src/parser/object/literal.rs
libs/@local/hashql/syntax-jexpr/src/parser/string/expr.rs
libs/@local/hashql/syntax-jexpr/src/parser/string/snapshots/hashql_syntax_jexpr__parser__string__expr__tests__empty_brackets.snap
libs/@local/hashql/syntax-jexpr/src/parser/string/snapshots/hashql_syntax_jexpr__parser__string__expr__tests__index_access_field_access.snap
libs/@local/hashql/syntax-jexpr/src/parser/string/snapshots/hashql_syntax_jexpr__parser__string__expr__tests__index_access_mixed.snap
libs/@local/hashql/syntax-jexpr/src/parser/string/snapshots/hashql_syntax_jexpr__parser__string__expr__tests__index_access_with_ident.snap
libs/@local/hashql/syntax-jexpr/src/parser/string/snapshots/hashql_syntax_jexpr__parser__string__expr__tests__index_access_with_ident_chained.snap
libs/@local/hashql/syntax-jexpr/src/parser/string/snapshots/hashql_syntax_jexpr__parser__string__expr__tests__multi_digit_index.snap
libs/@local/hashql/syntax-jexpr/src/parser/string/snapshots/hashql_syntax_jexpr__parser__string__expr__tests__non_numeric_index.snap
libs/@local/hashql/syntax-jexpr/src/parser/string/snapshots/hashql_syntax_jexpr__parser__string__expr__tests__simple_index.snap
libs/@local/hashql/syntax-jexpr/src/parser/string/snapshots/hashql_syntax_jexpr__parser__string__expr__tests__whitespace_in_brackets.snap

Ensures consistency with the features described in the dissertation, fixing the following points:
* allow for nested index expressions inside string shorthand
* only allow for a single labelled argument
* labelled argument shorthand
Additionally, it disables exponent support for literals on the parsing level (to be fixed in https://linear.app/hash/issue/H-5290/hashql-allow-for-integer-literals-with-exponents), as it was never supported in the backend in the first place.
This PR:

H-4984: HashQL: Ensure J-Expr consistency with dissertation

---

.github/actions/prune-repository/action.yml

`turbo` does not support cyclic dependencies. We missed a few dependencies in our prune-logic. This was the reason why previously we achieved a test-failure on main, which otherwise would have been caught.

SRE-25: Fix turbo-hack to bypass cyclic dependency issue

---

libs/error-stack/CHANGELOG.md
libs/error-stack/src/macros.rs
libs/error-stack/tests/ui/missing_args.stderr

Trailing commas are natural in macro calls.
This PR:

ES-19, ES-20: Allow trailing commas in bail macro to return `Report<C>`, not `Report<[C]>`

---

libs/@local/hashql/ast/src/lowering/special_form_expander/error.rs
libs/@local/hashql/ast/src/lowering/special_form_expander/mod.rs
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/access-field-index-out-of-bounds.jsonc
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/access-field-index-out-of-bounds.stderr
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/access-field-literal-boolean.jsonc
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/access-field-literal-boolean.stderr
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/access-field-literal-string.jsonc
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/access-field-literal-string.stderr
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/access-field-literal-type-annotation.jsonc
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/access-field-literal-type-annotation.stderr
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/access-field-literal-valid.jsonc
libs/@local/hashql/ast/tests/ui/lowering/special-form-expander/access-field-literal-valid.stdout
libs/@local/hashql/syntax-jexpr/src/parser/string/expr.rs
libs/@local/hashql/syntax-jexpr/src/parser/string/snapshots/hashql_syntax_jexpr__parser__string__expr__tests__index_too_large.snap

Element access (tuple indexing) was currently only possible using the string notation in j-expr, e.g. using `"value.field"`, this is insufficient in cases where the target is of a dynamic nature. This remedies it by allowing for `[".", "foo", {"#literal": 1}]`, e.g. access via a single integer literal that fits into usize.
This PR:

H-5115: HashQL: allow for integer literals during field access

---

libs/@local/graph/type-fetcher/src/store.rs
tests/graph/benches/config/scenarios/linked_queries.json
tests/graph/benches/graph/lib.rs
tests/graph/benches/graph/scenario/runner.rs
tests/graph/benches/graph/scenario/stages/data_type.rs
tests/graph/benches/graph/scenario/stages/entity.rs
tests/graph/benches/graph/scenario/stages/entity_type.rs
tests/graph/benches/graph/scenario/stages/mod.rs
tests/graph/benches/graph/scenario/stages/property_type.rs
tests/graph/test-data/rust/src/seeding/producer/entity.rs
tests/graph/test-data/rust/src/seeding/producer/entity_type.rs

Link entities are a core part of the system. They are a bit more complex to create as they need to precisely match the entity type, so it has to pick the correct other entities. 
- #7778 
- Extend current functionality by link entity creation
This PR:
- We currently don't track which user can access which entity (basically only their own entities at this stage). So the linked-entity scenario only creates a single user web currently.

BE-35: Support link entity generation in benchmarks

---

libs/@local/hashql/ast/src/lowering/import_resolver/error.rs
libs/@local/hashql/ast/src/lowering/import_resolver/mod.rs
libs/@local/hashql/ast/src/lowering/pre_expansion_name_resolver.rs
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/use-shadowing-let.jsonc
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/use-shadowing-let.stdout
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/use-shadowing-use.jsonc
libs/@local/hashql/ast/tests/ui/lowering/import-resolver/use-shadowing-use.stdout
libs/@local/hashql/core/src/module/error.rs
libs/@local/hashql/core/src/module/import.rs
libs/@local/hashql/core/src/module/locals.rs
libs/@local/hashql/core/src/module/mod.rs
libs/@local/hashql/core/src/module/namespace.rs
libs/@local/hashql/core/src/module/resolver.rs

Currently declared identifiers always take precedence. This is not correct, instead we should correctly resolve types and values, given:
```rust
use path::to::item in // defines item = 24
let item = 42 in
item == 42
// where as:
let item = 42 in
use path::to::item in
item == 24
```
The current evaluation rules effectively ignore imports for identifiers already declared, which is incorrect.
Current behaviour:
```rust
use path::to::item in // defines item = 24
let item = 42 in
item == 42
let item = 42 in
use path::to::item in
item == 42
```
This PR:

BE-40: HashQL: Fix `use` expression resolving

---

apps/hash-external-services/docker-compose.dev.yml
apps/hash-external-services/grafana/provisioning/datasources/pyroscope.yml
apps/hash-external-services/pyroscope/pyroscope.yaml

We have set up Pyroscope in production. To profile locally, it's good to have an instance running locally as well.
I did not revert the autoformatting changes in the compose file. It's a bit more noise this time, but less noise in the future.

H-5330: Add a local Pyroscope container

---

infra/terraform/hash/observability/alloy/config.tf
infra/terraform/hash/observability/alloy/main.tf
infra/terraform/hash/observability/alloy/outputs.tf
infra/terraform/hash/observability/alloy/security_groups.tf
infra/terraform/hash/observability/alloy/target_groups.tf
infra/terraform/hash/observability/alloy/templates/alloy-config.alloy.tpl
infra/terraform/hash/observability/grafana/config.tf
infra/terraform/hash/observability/grafana/security_groups.tf
infra/terraform/hash/observability/grafana/templates/provisioning/datasources/pyroscope.yaml.tpl
infra/terraform/hash/observability/grafana/variables.tf
infra/terraform/hash/observability/load_balancer.tf
infra/terraform/hash/observability/main.tf
infra/terraform/hash/observability/otel_collector/config.tf
infra/terraform/hash/observability/otel_collector/security_groups.tf
infra/terraform/hash/observability/otel_collector/templates/otel-collector.yaml.tpl
infra/terraform/hash/observability/otel_collector/variables.tf
infra/terraform/hash/observability/pyroscope/config.tf
infra/terraform/hash/observability/pyroscope/iam.tf
infra/terraform/hash/observability/pyroscope/main.tf
infra/terraform/hash/observability/pyroscope/outputs.tf
infra/terraform/hash/observability/pyroscope/security_groups.tf
infra/terraform/hash/observability/pyroscope/service.tf
infra/terraform/hash/observability/pyroscope/storage.tf
infra/terraform/hash/observability/pyroscope/templates/pyroscope.yaml.tpl
infra/terraform/hash/observability/pyroscope/variables.tf
infra/terraform/hash/observability/tls.tf

This PR implements a complete Pyroscope continuous profiling service within our AWS observability infrastructure. Pyroscope enables continuous profiling of applications in production, allowing developers to identify performance bottlenecks, memory leaks, and CPU hotspots with minimal overhead.
The implementation provides a production-ready Pyroscope deployment with S3-based storage, proper security configurations, and seamless integration with our existing observability stack (Grafana, Alloy, OpenTelemetry Collector).
Note on Rust profiling:
- We will have CPU profiling by looking at the stack trace with a certain frequency to get CPU time spent over time
- We will have Wall time profiling through tracing
- Memory profiling could be achieved by using a global allocator which supports …

H-5328: Add Pyroscope continuous profiling infrastructure to AWS observability stack
