packages/engine/stdlib/src/py/dev_requirements.txt, packages/engine/stdlib/src/py/hstd/agent.py, packages/engine/stdlib/src/py/hstd/context.py, packages/engine/stdlib/src/py/hstd/init.py, packages/engine/stdlib/src/py/hstd/neighbor.py, packages/engine/stdlib/src/py/hstd/rand.py, packages/engine/stdlib/src/py/hstd/spatial.py, packages/engine/stdlib/src/py/hstd/test_init.py, packages/engine/stdlib/src/py/hstd/test_neighbor.py, packages/engine/stdlib/src/py/hstd/test_rand.py, packages/engine/stdlib/src/py/hstd/test_spatial.py, packages/engine/stdlib/src/ts/neighbor.spec.ts, packages/engine/stdlib/src/ts/neighbor.ts, packages/engine/stdlib/src/ts/spatial.ts
- Bringing the Python standard library to parity with the TypeScript library.
- Adding tests for all new Python functions
- Small improvements in code clarity for TypeScript library.
- Larger rework of the TypeScript neighbors/neighborsInRadius function to use distance functions from spatial/
=> Python Stdlib Parity

resources/docs/simulation/creating-simulations/agent-messages/built-in-message-handlers.md
Adds documentation for the "stop" message to the "Built-in message handlers" page.
=> Add docs for 'stop' message

resources/docs/simulation/README.md, resources/docs/simulation/extra/performance.md
We have a few legacy Discord links scattered around the docs that will soon hit invite caps. This PR replaces them with a link to https://hash.ai/discord which allows users to sign up without limitation.
=> Update Discord links

CONTRIBUTING.md, packages/engine/README.md, packages/engine/stdlib/CONTRIBUTING.md, packages/engine/stdlib/README.md, resources/docs/simulation/README.md, resources/docs/simulation/extra/performance.md, resources/docs/simulation/tutorials/building-process-models/README.md
Changes community.hash.ai to hash.community in the HASH public monorepo content. Other CMS updates will be pushed separately.
=> Update forum links

resources/docs/simulation/creating-simulations/libraries/hash/neighbors.md
This PR updates the `neighbors.md` docs file to display inside code marks `, to maintain each function name's case.
~Although it's possible to use MD inside headings in markdown, it jumbles up the underlying HTML, which means we can't read the current heading which is being passed from the markdown. So, I've converted it to bold code blocks, like I've done earlier elsewhere.~
The above is now fixed, we can use headings with code, bold or italics in HASH docs.
=> Fix headings for code

resources/docs/simulation/concepts/designing-with-system-dynamics-models.md, resources/docs/simulation/tutorials/phase-1-building-a-simple-hotelling-model-in-2d/business-collect-and-update.md, resources/docs/simulation/tutorials/phase-1-building-a-simple-hotelling-model-in-2d/customer-reply.md, resources/docs/simulation/tutorials/phase-1-building-a-simple-hotelling-model-in-2d/initialization.md, resources/docs/simulation/tutorials/phase-1-building-a-simple-hotelling-model-in-2d/query-customers.md
This PR removes bold modifiers from code, which were used to style filenames before. [This PR](https://github.com/hashintel/internal/pull/3172) makes it redundant, allowing filenames in code to be displayed as filenames directly.
=> Remove unneeded bold from code

resources/docs/simulation/extra/specs-requirements.md
This PR updates the specs-requirement file to support the new Partial Support design for Safari.
Related Asana Task: https://app.asana.com/0/1199550852792212/1201333602499687/f
Related PR which adds the icon: https://github.com/hashintel/internal/pull/3174
=> Update specs-requirements.md to display partial support icon

resources/glossary/url_map.json
Presently, while building the Glossary pages in NextJS, each of the Glossary pages has to be fetched in each page to build the sidebar. This PR, in conjunction with [this change](https://github.com/hashintel/internal/pull/3177) on hash.ai, reduces that to just one API call to the `url_map.json`, so that the frontend gets all of the data at once.
This reduces the reliance on GitHub's API, and keeps us farther from reaching the rate limit.
I realize these could also be auto-generated via GitHub Actions eventually, so I'm creating an Asana task for this: https://app.asana.com/0/1199550852792212/1201430261338781/f
=> Add url_map for Glossary

resources/docs/simulation/concepts/designing-with-process-models/process-blocks.md
Add missing code blocks delimiters to fix the docs formatting which is currently very hard to read
=> Fix: formatting for process blocks docs

.github/workflows/attach-pr-to-asana-task.yml
Adds a GitHub action [[source](https://github.com/Asana/create-app-attachment-github-action)] which will scan PR descriptions for Asana tasks, and attach the PR info to the Asana task.
- [This Asana task should have this PR automatically attached](https://app.asana.com/0/1199550852792314/1201473331768997/f)
1. Visit the Asana task URL above
2. Check it has this PR attached
3. Trust me that I didn't attach it manually
=> [TOOL] Add GitHub action to attach PR to Asana task

.github/workflows/algolia/src/syncAlgoliaIndex.ts
#51 added `url_map.json` to the glossary folder. However, it's being incorrectly indexed by the Algolia GitHub Action, and displaying a garbage search result. This PR only allows `.md` and `.mdx` files to be picked up by the Algolia indexing code, hence stopping wrong files from being indexed.
---
- [Asana task](https://app.asana.com/0/0/1201449675033652)
=> [Priority] Only index md and mdx files into Algolia

packages/engine/Cargo.toml, packages/engine/bin/cli/Cargo.toml, packages/engine/bin/cli/src/experiment.rs, packages/engine/bin/server/Cargo.toml, packages/engine/src/config/package.rs, packages/engine/src/datastore/arrow/field_conversion.rs, packages/engine/src/datastore/arrow/meta_conversion.rs, packages/engine/src/datastore/mod.rs, packages/engine/src/datastore/schema/field_spec/mod.rs, packages/engine/src/hash_types/vec.rs, packages/engine/src/output/buffer/mod.rs, packages/engine/src/simulation/package/context/packages/agent_messages/fields.rs, packages/engine/src/simulation/package/context/packages/agent_messages/mod.rs, packages/engine/src/simulation/package/context/packages/agent_messages/writer.rs, packages/engine/src/simulation/package/context/packages/mod.rs, packages/engine/src/simulation/package/creator.rs, packages/engine/src/simulation/package/init/packages/mod.rs, packages/engine/src/simulation/package/name.rs, packages/engine/src/simulation/package/output/packages/analysis/config.rs, packages/engine/src/simulation/package/output/packages/mod.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/config.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/fields/mod.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/mod.rs, packages/engine/src/simulation/package/state/packages/mod.rs, packages/engine/src/worker/runner/javascript/mini_v8/value.rs, packages/engine/src/worker/runner/mod.rs
[Rust 2021](https://doc.rust-lang.org/edition-guide/rust-2021/index.html) comes with a new Cargo-Resolver for workspaces and some more Items in the prelude. The new cargo-resolver may or may not speed up our compilation time.
=> Migrate to Rust 2021 and apply rustfmt

packages/engine/Cargo.lock, packages/engine/Cargo.toml, packages/engine/README.md, packages/engine/build.rs
The `nng` dependency has an optional feature to compile nng. This does not work on ARM Macs.
To get around this it's necessary to acquire a compiled version of NNG.
To avoid making this a dependency for the majority of users, we want to conditionally require the external NNG dependency.
This adds the relevant conditional logic, and expands the README to explain the reasoning.
https://gitlab.com/neachdainn/nng-rs/-/issues/55
* Cargo.toml checks to see if the target_os is macos and then either:
* _Isn't_ macos
* Adds nng as a dependency _with_ default-features (i.e. the nng build feature)
* _Is_ macos
* adds nng as a dependency _without_ default-features
* We attempted to implement this entirely with a _default_ feature-flag but it seems that currently nightly is broken where …
=> Fixing NNG-building on everything that isn't an ARM-based Mac

packages/engine/bin/cli/src/process/local.rs, packages/engine/src/datastore/batch/context.rs, packages/engine/src/datastore/table/context/mod.rs, packages/engine/src/simulation/comms/mod.rs, packages/engine/src/simulation/engine.rs, packages/engine/src/simulation/package/context/mod.rs, packages/engine/src/simulation/package/context/packages/agent_messages/collected.rs, packages/engine/src/simulation/package/context/packages/agent_messages/fields.rs, packages/engine/src/simulation/package/context/packages/agent_messages/mod.rs, packages/engine/src/simulation/package/context/packages/api_requests/fields.rs, packages/engine/src/simulation/package/context/packages/api_requests/mod.rs, packages/engine/src/simulation/package/context/packages/neighbors/fields.rs, packages/engine/src/simulation/package/context/packages/neighbors/mod.rs, packages/engine/src/simulation/package/run.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/fields/mod.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/mod.rs
This allows context packages to return / maintain multiple columns. Although this isn't currently useful.
It also does a somewhat messy re-ordering of the return values relating to columns of context packages to fix a pretty nasty bug.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201481007343173/f)
* Changes the signatures of the traits for Context Packages to return Vecs instead of single elements
* Adds an ordering and look-up step with those return values, that reads through the columns present in the schema and selects the relevant column from the package's column writers. This ensures that the ordering is the same, and we additionally get some better error handling if it's missing or unexpected things happen. Nevertheless, this is still pretty sloppy and I …
=> Allowing context packages to have multiple columns, fixing bug where column ordering didn't match schema

packages/engine/README.md
Adds a section for describing the outputs of the engine in the README, with some initial contents.
Also adds a few more disclaimer-y / warning headings just to clarify that features are highly volatile at the moment. 
- [Asana task description](https://app.asana.com/0/1199550852792314/1201486809262034/f)
The README
None needed, it is a README
=> Adding some description of engine outputs in the README

packages/engine/src/datastore/schema/field_spec/mod.rs, packages/engine/src/datastore/schema/mod.rs, packages/engine/src/simulation/package/output/packages/json_state/config.rs, packages/engine/src/simulation/package/output/packages/json_state/mod.rs
Filters hidden and private fields from JSON output.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201481006654696/f)
- It's using the `FieldSpec` constants to filter for hidden and private fields.
✅ Manual Tests
1. Run a simulation
2. Check, that _./parts_ output neither contain `"_HIDDEN_"`, nor `"_PRIVATE_"` fields
=> Sanitize output for JsonState

packages/engine/README.md
Adds a readme section on how to run a simulation from hCore and add `--release` flags to `cargo` commands.
[Asana task](https://app.asana.com/0/1199550852792314/1201497703621221/f)
=> Add a README how-to section on how to run a project from hCore

packages/engine/README.md
Expands the README to explain the Engine is currently pre-release and is unstable. Also aims to provide greater clarity on Python and Rust runners not being enabled currently
---
- https://app.asana.com/0/0/1201494000207966
=> Expanding README with a section describing the state of development of the repository

packages/engine/bin/cli/src/main.rs
---
- https://app.asana.com/0/0/1201499937429459
=> Make the project path required when calling the CLI

packages/engine/bin/cli/src/experiment.rs
I don't think we want the 3600 time to be based on debug builds (i.e. without optimisations). I think we only want that ridiculous timeout when using a debugger, in which case it's fine to set the envvar in the IDE run config.
PING_INTERVAL also seems to not exist anywhere in the codebase so I removed.
=> Changing timeout default values and removing unused one.

packages/engine/.gitignore, packages/engine/src/output/buffer/part.rs, packages/engine/src/output/local/sim.rs
We called `.extend` with a path starting with `"/"` which replaces the path rather than appending it. This is why we were getting permission denied errors, because we were trying to write into the root.
Fixing this correctly produces an `/output` directory now.
=> Fixing output-persistence logic where extend was replacing the path

packages/engine/src/datastore/schema/field_spec/mod.rs, packages/engine/src/datastore/schema/field_spec/short_json.rs, packages/engine/src/simulation/package/creator.rs
When generating `FieldSpec` from short_json, "PREVIOUS_INDEX" was not added
- [Asana task description](https://app.asana.com/0/1199550852792314/1201481006654684/f)
- ✅ Unit Tests
=> Add PREVIOUS_INDEX to `short_json`

packages/engine/src/datastore/storage/memory.rs, packages/engine/src/experiment/controller/controller.rs, packages/engine/src/output/local/sim.rs, packages/engine/src/simulation/controller/runs.rs
* Fixes the experiment controller ending too early and therefore dropping simulations before their output persistence is finished.
* Fixes a bug with the output persistence paths introduced in a previous PR.
* Two small drive-by fixes for warnings
=> Fixing Simulation termination logic and output bug

packages/engine/README.md, packages/engine/src/experiment/controller/controller.rs, packages/engine/src/output/local/sim.rs
We were only exposing the JSON state output in parts, this was mostly done for S3 persistence reasons on cloud as uploading it in one large blob could fail. There are currently no persistence methods implemented in this repo aside from to file, so we can combine them into one.
Outputs are now persisted in `./output/<EXPERIMENT ID>/<SIMULATION ID>`
Also contains a drive-by fix where a warn statement uses the incorrect value.
=> Combining parts into a single json_state file in the output

packages/engine/src/output/local/sim.rs
We log where the outputs are being written to. This was a trace log, it's useful info for almost any run so it makes sense to change the level to info.
Before:
```TRACE hash_engine::output::local::sim > Making new output directory directory: "./output/3551d8c1-1e55-4c7a-bb8f-192fe6c54037/1"```
After:
```INFO hash_engine::output::local::sim > Making new output directory directory: "./output/3551d8c1-1e55-4c7a-bb8f-192fe6c54037/1"```
Asana: https://app.asana.com/0/1199550852792314/1201499989227961/f
=> Changing output log to info instead of trace

packages/engine/README.md, packages/engine/bin/cli/src/experiment.rs, packages/engine/bin/cli/src/main.rs
Improves usability and readability of the output folder. (Both for human and machine consumption)
- [Asana task description](https://app.asana.com/0/1199550852792314/1201514365398449/f)
- Adds a CLI argument to set the Project name
* Defaults to the name of the final directory in the project path 
- Changes the output folder structure to group experiments by given project name
=> Adding a project name arg and using it to build the output folder

packages/engine/format/sync_context_batch.fbs, packages/engine/src/datastore/table/sync.rs, packages/engine/src/simulation/comms/mod.rs, packages/engine/src/simulation/controller/run.rs, packages/engine/src/simulation/engine.rs, packages/engine/src/worker/runner/javascript/context.js, packages/engine/src/worker/runner/javascript/mod.rs, packages/engine/src/worker/runner/javascript/runner.js
We support a `context.step()` method in the legacy hEngine used within hCore/hCloud today, which provides the current step of the simulation. This PR implements the same in our new open hEngine.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201525968072827/f)
1. Download the step simulation from https://core.hash.ai/@alfie/steps/stable
2. Run a single_run with a few steps and check that the current_step field is correctly incremented in the outputted json_state.json
=> Adding `step()` method for contexts in JS

packages/engine/bin/cli/src/experiment.rs
Change the log severity for experiment messages do debug, so the Javascript `console.log` can be filtered better.
In order to see the logging output from Javascript, set the environment variable `RUST_LOG=cli::experiment=info`.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201524950327107/f)
=> Change log severity for experiment message

packages/engine/src/simulation/package/output/packages/json_state/mod.rs
The JSON output of Agent state includes messages within hCore/hCloud. Until this PR we were only serializing the AgentBatch rather than also the more dynamic messages batch.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201521491107069/f)
* Uses the message batch as well as the agent batch for serializing AgentState
✅ Manual Tests
1. Run any experiment that utilises messages (e.g. sugarscape)
2. Check the json_state.json output file and verify that the agents have a messages field.
=> Include messages within json_state output

packages/engine/src/hash_types/state.rs
`search_radius` and `position_was_corrected` don't need to be builtin.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201514365398447/f)
=> Remove `search_radius` and `position_was_corrected` from builtin fields

.github/workflows/rust-lints.yml
We currently require the Rust-Lint CI to pass, but it's not executed when non-Rust changes are made.
=> Temporarily disable paths on rust-lints.yml to enable PRs on non-Rust changes

packages/engine/src/simulation/package/state/packages/behavior_execution/package.js
Only behaviors for the first agents are executed. This is a fix to this.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201524950327102/f)
For optimization, the `agent_state` was reused in the javascript runner. This PR removes the optimization, as behavior indices were borked after reusing.
=> Fix behavior execution for Javascript runners

packages/engine/src/datastore/batch/context.rs, packages/engine/src/datastore/storage/mod.rs, packages/engine/src/simulation/controller/run.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/package.js
Messages were missing from the context, despite being written to the batch. This was due to the runners not reloading the memory as the batch metaversion wasn't incremented, thus the runners didn't think data had changed
- [Asana task description](https://app.asana.com/0/0/1201532662164415/f)
- Increments the context batch metaversion when we finish writing
- Removes a potentially problematic context optimisation to be revisited alongside an existing TODO for the same optimisation for state
- ✅ Manual Tests (Ran a basic sim with 3 agents that send messages to another agent and confirmed that the context.messages() length is now 3)
=> Fixing missing messages from context 

packages/engine/src/simulation/package/context/packages/agent_messages/collected.rs
Sending a message to an agent with a capitalised letter was broken as we had half implemented case-*in*sensitivity. This PR removes it and makes agent_name case _sensitive_ for message passing
- [Asana task description](https://app.asana.com/0/0/1201532662164416/f)
- Removes a `to_lowercase()` call where we were turning the message target to lowercase, but only in one side of the logic rather than the other
- ✅ Manual Tests (Confirmed a message to "Fred" now correctly goes to the "Fred" agent whereas before it didn't)
=> Making message-sending case sensitive for the target of the message

packages/engine/bin/cli/src/experiment.rs, packages/engine/src/experiment/controller/controller.rs, packages/engine/src/proto.rs, packages/engine/src/worker/mod.rs, packages/engine/src/workerpool/comms/mod.rs, packages/engine/src/workerpool/comms/top.rs, packages/engine/src/workerpool/mod.rs
Messages from workers (such as those containing logs and warnings from user behaviors) weren't associated with a simulationID. This fixes that
- [Asana task description](https://app.asana.com/0/1199550852792314/1201533886101099/f)
- The message sender from Worker has been expanded to also send the simulationId
- Worker handle methods pass the SimId
- The WorkerPool receiver correctly propagates that SimId
=> Associating messages from workers with simulation IDs

packages/engine/bin/cli/src/experiment.rs, packages/engine/bin/cli/src/main.rs, packages/engine/bin/cli/src/process/local.rs, packages/engine/src/args.rs, packages/engine/src/datastore/schema/field_spec/mod.rs, packages/engine/src/env.rs, packages/engine/src/experiment/controller/controller.rs, packages/engine/src/experiment/package/single.rs, packages/engine/src/proto.rs, packages/engine/src/worker/runner/javascript/mod.rs
Changes some log levels and clears up info-level logging to improve readability of running experiments in normal use. Also clears up unused parts of the code-base and some other drive-bys
- [Asana task description](https://app.asana.com/0/1199550852792314/1201526606175188/f)
- Removes unused (and legacy) persist argument for the CLI
- Replaces a warning message when adding FieldSpecs that already exist with a comment explaining why it's okay to ignore
- Increases the initial wait time for the Experiment Controller exit logic to avoid logs that aren't useful
- Removes empty print (e.g. console.log in behaviors) from task messages at an earlier point
Example output for an experiment, logging at info-level, is as follows (now cleaner and only showing useful information):
``` …
```
=> Improving info-level logging, cleaning up TODOs, and unused code, 

README.md
We're in the process of restructuring this repo, ahead of the open-source release of HASH's workspace product, and following the publication of the code behind our next-gen [hEngine](https://hash.ai/platform/engine).
=> README improvements ahead of HASH open-sourcing

packages/engine/src/output/buffer/mod.rs, packages/engine/src/output/local/sim.rs, packages/engine/src/output/mod.rs, packages/engine/src/output/none.rs, packages/engine/src/simulation/controller/run.rs
Simulation outputs were tied to their project, experiment run, and simulation run, but there was no easy way of knowing which parameters were used for which run. In the case of experiments, this poses a large problem as the user provided `globals.json` can have properties overridden by the experiment. 
This PR outputs each simulation's respective globals.json alongside the json_state.json and analysis_outputs.json.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201533886101107/f)
- Writes the simulation globals to a globals.json in the output folder for the simulation
1. Run any simulation (preferably an experiment with multiple simulations)
2. Check the output folder and verify that there is a globals.json, and the respective globals.json for the …
=> Writing globals.json to the output folder alongside simulation results

packages/engine/bin/cli/src/experiment.rs
https://github.com/hashintel/hash/pull/93 implemented logging from JS behaviors. However when the logs appear they only have a `SimulationID` attached, and do not contain information about what file, location, behavior, task, function, etc. that it came from:
```
INFO  cli::experiment > [1]: 0,50
```
This also adds the current experiment id and changes the log targets to `behaviors`:
```
INFO  behaviors > [single_run-e073f2][1]: 0,50
```
- [Asana task description](https://app.asana.com/0/1199550852792314/1201533886101103/f)
=> Add experiment Id to logging output

README.md
This PR will serve as a catch-all for various updates to documentation ahead of our open-sourcing of **HASH** in January 2022, our eponymous, open-source, data-centred workspace.
=> In-repo documentation updates for open-sourcing

packages/engine/Cargo.lock, packages/engine/lib/provider/Cargo.toml, packages/engine/lib/provider/src/internal.rs, packages/engine/lib/provider/src/lib.rs, packages/engine/lib/provider/src/requisition.rs, packages/engine/lib/provider/src/tags.rs
Contains the `Provider` trait and accompanying API, which enable trait objects to provide data based on typed requests, an alternate form of runtime reflection.
Currently, we use `thiserror` in hEngine, which just wraps every error in another error. Errors may (or may not) contain additional information on the cause or the context. It's very hard to track down the exact cause with all it's information (without huge, nested `match error` statements). It's even harder to add more general information like the [`Location`](https://doc.rust-lang.org/stable/std/panic/struct.Location.html), where the error/cause/context happened. We want to replace our error handling with a more generic approach like shown in #134. 
The provider API was proposed by the official error handling project of Rust …
=> Add `Provider` API for context information on errors (and possibly other things)

packages/engine/src/worker/runner/python/message.py, packages/engine/src/worker/runner/python/package.py, packages/engine/src/worker/runner/python/runner.py, packages/engine/src/worker/runner/python/sim.py
Python init PR `#2`
Previous PR: #112 
- [Asana task description](https://app.asana.com/0/0/1201539039235282/f)
* Ignores packages' owned fields temporarily
* Fixes sending runner errors to Rust (using nng)
* Fixes paths where packages are expected to be
* Fixes `hash_util` import in packages
1. Run any experiment.
2. Check that Python reaches behavior execution or messages package init
=> Fix package loading in Python runner

packages/engine/src/simulation/package/state/packages/behavior_execution/package.py, packages/engine/src/worker/runner/python/package.py, packages/engine/src/worker/runner/python/runner.py
Python init PR `#3`
Previously line numbers were incorrect if an exception occurred inside a package, due to the runner automatically prepending imports. The PR fixes this by propagating imports in a better way.
- [Asana task description](https://app.asana.com/0/0/1201539039235283/f)
* Changes how imports are propagated to Python components of packages
1. Run any experiment with a package that has a Python component
2. Raise an exception during package init
3. The resulting traceback should have correct line numbers
=> Fix line numbers in Python tracebacks

packages/engine/src/simulation/package/state/packages/behavior_execution/package.py
Python init PR #4
- [Asana task description](https://app.asana.com/0/0/1201539039235285/f)
* Fixes {behavior id --> behavior} mapping in Python
* Changes `dict.field` to `dict['field']`, as is correct in Python
1. Run any experiment.
2. Python should get through behavior execution package init and reach messages package init.
=> Fix behavior execution package Python component init

resources/docs/simulation/creating-simulations/libraries/hash/random.md, resources/docs/simulation/creating-simulations/libraries/hash/spatial.md
There are a couple of MDX tags missing closing quotes on their `title` property. This PR fixes that.
=> [DOCS] Add missing closing quotes

packages/engine/Cargo.lock, packages/engine/Cargo.toml, packages/engine/bin/cli/Cargo.toml, packages/engine/bin/cli/src/experiment.rs, packages/engine/bin/cli/src/main.rs, packages/engine/bin/server/Cargo.toml, packages/engine/bin/server/src/main.rs, packages/engine/src/utils.rs
Replace `log` with a structured logging library `tracing`
- [Asana task description](https://app.asana.com/0/1199550852792314/1201612388082320/f)
Replaces the `log` crate with `tracing` crate. The macros are backwards compatible (even though `tracing`s are more powerful). They inspect the current span and add it to the log entry: https://github.com/hashintel/hash/blob/fc161e9fb6bf64ba31aa91b9d5f792c460136834/packages/engine/bin/cli/src/experiment.rs#L55-L61
Spans also enables us to print `SpanTraces`.
```
0.013644156s  INFO hash_engine::utils: Setting `ENGINE_START_TIMEOUT=2`
at src/utils.rs:35
in cli::experiment::run_experiment_with_manifest with , project_name: "sugarscape", experiment_id: "single_run-85adf6"
0.056424725s  INFO hash_engine: HASH Engine process started …
```
=> Use `tracing` instead of `log`

packages/engine/bin/cli/src/manifest.rs, packages/engine/src/experiment/package/simple.rs, packages/engine/src/proto.rs
Sometimes it may be beneficial to limit how many simulations can run in parallel in an experiment. For example, it may have simulations that use a lot of resources and running them sequentially allows it to fit within RAM, or for benchmarking reasons.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201614340097579/f)
- Creates a new optional field in `experiments.json` called `max_sims_in_parallel` 
- Reworks the SimpleExperiment package execution logic to work around a queue of simulations, with a sized-batch of active ones according to the `max_sims_in_parallel` parameter (defaulting to an 'infinite (in reality := number_of_sims) number in parallel)
Run a simple experiment with and without the parameter and check for correct differing behavior …
=> Implementing limiting on number of parallel sims

packages/engine/src/worker/runner/python/mod.rs, packages/engine/src/worker/runner/python/runner.py, packages/engine/src/worker/runner/python/sender.rs
Python init PR #6
- [Asana task description](https://app.asana.com/0/0/1201539039235273/f)
* Temporarily ignores (aside from termination) inbound messages to the Python runner -- they are not forwarded as nng messages
* (Did merge with main)
1. Run any experiment with packages that have Python components
2. The experiment should work as long as no tasks are actually sent to the Python runner to be executed
=> Fix Python runner init

.github/workflows/rust.yml
Dynamically collects all GitHub Actions for Rust in one job.
- [Asana task description](https://app.asana.com/0/1199550852792314/1201600029668233/f)
- Changes the find-job to create a list of packages to test
- If any file of a rust package is changed, all tests and checks are run (they could depend on each other)
- rustfmt is only run for the package changed
- Adds a job `enable merging` which can be required be be merged
- It fails if any ran job failed
- Otherwise it succeeds
=> Collect Rust Actions to only require one job to pass to enable merging

.github/workflows/rust.yml
Let changed files in Rust crates only affect the corresponding module
When a Rust file of a submodule (e.g. `packages/engine/lib/error`) is changed, this is also matched by `packages/engine`. This small fix sorts the available crates, so the longest name will be matched first. As soon as it's matching the changed file, the next file is searched.
=> Only match first crate when determining crates to test in Rust Action

packages/engine/CONTRIBUTING.md
Adds the start of a contribution guide for hEngine.
Currently heavily inspired (mostly copied) from Atom as [theirs](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) is pretty great
- [Asana task description](https://app.asana.com/0/1199550852792314/1201533886101109/f)
- Adds CONTRIBUTING.md
1. [Open the README on Github](https://github.com/hashintel/hash/blob/engine/contributions/packages/engine/CONTRIBUTING.md) (link is valid until PR is merged and branch is deleted, after merging open the README in main)
=> Adding an initial CONTRIBUTING.md in packages/engine

packages/engine/bin/cli/src/experiment.rs, packages/engine/bin/cli/src/main.rs, packages/engine/bin/cli/src/process/local.rs, packages/engine/bin/server/src/main.rs, packages/engine/src/args.rs, packages/engine/src/utils.rs
For easier parsing in integration tests, this adds an optional argument `--emit` to chose from different formats (`pretty` (default), `full`, `compact`, and `json` (disabled) )
- [Asana task description](https://app.asana.com/0/1199550852792314/1201643790165293/f)
- Run simulation with different `--emit` arguments
`cargo run -p cli -- -p sugarscape --emit compact single-run -n2`
`cargo run -p cli -- -p sugarscape --emit full single-run -n2` (We currently don't have nested spans)
`cargo run -p cli -- -p sugarscape --emit pretty single-run -n2`
=> Add option to chose output format

packages/engine/bin/cli/src/main.rs, packages/engine/src/args.rs, packages/engine/src/utils.rs
- Change the log output to `stderr` instead of `stdout`
- Change default log format to `full` instead of `pretty` (see #145 for demos)
=> Change the log output to `stderr` instead of `stdout`

CONTRIBUTING.md, README.md, packages/engine/CONTRIBUTING.md
We're recruiting for a handful of key roles and would like to encourage our open-source contributors to apply. To date some of our best applicants (and hires) have been active users of our platform.
=> Add links to our open roles

LICENSE.md, packages/engine/LICENSE.md
This PR improves clarity around our licensing:
- it outlines that hEngine is in fact dual-licensed (available under Elastic License 2.0 as well as v1 of the Server Side Public License)
- it outlines the license under which the HASH workspace will be made available (GNU Affero General Public License 3.0)
- it outlines that source code outside of the above projects is by default now available under the **MIT** license (but exceptions may apply)
- appends a copy of the Elastic License 2.0 to our hEngine package `LICENSE.md` file, accompanying the SSPL text already there
=> Update root LICENSE.md to reflect new products

.github/pull_request_template.md
In some cases, a Pull request is blocked by another PR or other things like missing information. It's useful to point those information out.
- For PR without blockers, this section has to be removed manually
#181
=> Add a blocked-by section to the PR template

packages/engine/src/config/topology.rs, packages/engine/tests/units/neighbors/search_radius/mod.rs
Changes the default distance function from `conway` to `euclidean`
- No, as this is to behave as hCloud
- [Asana task](https://app.asana.com/0/1201481007343159/1201674703280810/f) (_internal_)
- ✅ Integration tests for search radius turned green
=> Make euclidean the default distance function

packages/engine/src/simulation/package/state/packages/behavior_execution/package.js, packages/engine/tests/units/state/mod.rs
Fix `state.behaviorIndex()` return the right behavior index instead of `undefined`
`AgentState.behaviorIndex()` is using the internal field `__i_behavior` instead of `behavior_index`. `__i_behavior` is never set, so this PR fixes this.
- [Asana task](https://app.asana.com/0/1201481007343159/1201671951990162/f) (_internal_)
- ✅ The integration test for testing `state.behaviorIndex()` turns green. The integration test is designed so that the expected behavior is the same as in hCloud.
=> Fix `state.behaviorIndex()` return the right behavior index

packages/hash/frontend/styles/globals.scss, packages/hash/frontend/twind.config.js
Overriding twind's preflight styles did not work as documented. this PR works around that.
Overriding twind's preflight styles does not work as documented
none.
no follow-up.
Moves overrides from `twind.config.json` to `globals.scss`.
no.
- [twind docs on preflight](https://twind.dev/handbook/configuration.html#preflight)
- [Asana task](https://app.asana.com/0/1201095311341924/1201454402248656/f) (_internal_)
none.
1.  Confirm that styles from the twind-override-section in `packages/hash/frontend/src/styles/globals.scss` overrule those provided by twind's preflight (contained by one of the first inline stylesheets)
see tests.
=> [FE] effectively override twind preflight styles

.github/workflows/rust.yml
Deduplicates crate executions in Rust CI
I expected that `git diff` already sorts the outputs. Without sorted outputs, `uniq` does not work for full deduplications, this PR sorts the output of `git diff`.
- PR with duplicated actions: #195
=> Deduplicate Rust Actions

.github/workflows/rust.yml
Adds the `--no-deps` flag for clippy in GH Actions to only run clippy on the corresponding crate
=> Use `--no-deps` on clippy in CI

packages/hash/api/src/collab/Instance.ts, packages/hash/frontend/src/blocks/page/collab/EditorConnection.ts, packages/hash/shared/src/ProsemirrorSchemaManager.ts, packages/hash/shared/src/entityStorePlugin.ts
This PR rewrites the entity store plugin to generate changes via a set of discrete actions that describe the change being made, instead of those just overwriting the full draft entity store whenever anything changes. This will allow a future PR to sync those actions between clients, to allow clients to push updates to the entity store that are not connected to changes in the Prosemirror tree, which are the only changes clients can make right now.
This will be necessary for variant switching.
N/A
- [**\[ASANA\]** Rewrite entityStorePlugin to be based on discrete actions which can be synced with collab](https://app.asana.com/0/1201095311341924/1201662619366268/f) (_internal_)
- [**\[ASANA\]** Fix switching variant ](https://app.asana.com/0/1200211978612931/1200972693311572/f) (_internal_)
- …
=> [FE] [BE] [COLLAB] Rewrite entity store plugin to be based on discrete actions

packages/hash/README.md, packages/hash/playwright/package.json, packages/hash/playwright/playwright.config.ts, yarn.lock
This PR improves local DX of running Playwright tests. It also bumps Playwright to 1.18.0 in hope to fix cookies in webkit. Having a working webkit in CI will useful in #201
Webkit still fails so I reverted the comment:
```js
// TODO: investigate issue with cookie persistence in CI (Ubuntu).
// GraphQL queries remain unauthenticated after login.
// { name: "webkit", use: { ...devices["Desktop Safari"] } },
```
- Continue #201
- Check if we can quickly fix Webkit cookies in Ubuntu (can help #201)
This PR saves developers from confusion. Playwright runs multiple workers locally by default, which breaks login flows in tests. Adding `--workers=1` is  not an obvious move.
- I removed `--workers=1`  from README
- [Slack discussion](https://hashintel.slack.com/archives/C022217GAHF/p16427711890880 …
=> Bump Playwright to 1.18.0, improve config

packages/hash/api/src/collab/Instance.ts, packages/hash/api/src/collab/collabApp.ts, packages/hash/frontend/src/blocks/page/collab/EditorConnection.ts, packages/hash/frontend/src/blocks/page/collab/http.ts, packages/hash/shared/src/entityStorePlugin.ts
This builds on previous work of making the entity store plugin work based on discrete actions, by syncing those actions with the collab instance, and then with other clients. This will allow clients to make and sync changes to the entity store that are not linked to a change in the prosemirror document, which was previously their only way to describe changes to the server. This will come in a future PR and is necessary for variant switching. 
Collab already has issues where high frequency updates cause 409 Conflict issues which is to be expected. This will be fixed by moving to a websocket transport.
- [**\[ASANA\]** Fix switching variant ](https://app.asana.com/0/1200211978612931/1200972693311572/f) (_internal_)
- New type of update in collab update list for entity store actions
- New …
=> [BE] [FE] [COLLAB] Sync entity store actions through collab

packages/hash/frontend/src/blocks/page/PageBlock.tsx
Hides the "restart collab instance" button which is useful for testing but possibly confusing, unless local storage value is present.
N/A
N/A
N/A
- Hides the "restart collab" button, unless there's a localStorage value for `hash.internal.debugging` set to either `true` or an object containing a key of `restartCollabButton` with a value of true (with the view that we can expand our debugging tools, and you might want a way to show them all or just some)
It might be worth following up in the README that this is available, but no immediate need.
- [**\[ASANA\]** Hide restart collab instance button by default](https://app.asana.com/0/1201095311341924/1201701347014981/f) (_internal_)
- [Slack discussion](https://hashintel.slack.com/archives/C022217GAHF/p1642178037020100) (_internal_)
None …
=> [FE] Hide restart collab instance button

packages/hash/playwright/tests/page-creation.spec.ts
This PR partially reverts #201 due to increased CI failures. Examples:
- https://github.com/hashintel/hash/runs/4956796162?check_suite_focus=true
- https://github.com/hashintel/hash/runs/4956462823?check_suite_focus=true
- https://github.com/hashintel/hash/runs/4956434139?check_suite_focus=true
The most common problem is having:
instead of:
[Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1643227188874519?thread_ts=1643114381.025900&cid=C02TWBTT3ED) _(internal link)_
- Revert this PR as part of [the follow-up Asana Task](https://app.asana.com/0/1201707629991380/1201720874843710/f) _(internal link)_
- Devs are unblocked for now
=> Remove a few steps from Playwright tests to reduce CI flakiness

packages/engine/Cargo.toml, packages/engine/tests/units/experiment.rs
The integration tests didn't work on ARM macOS because you couldn't disable default features.
We also shouldn't need to require the `OUT_DIR` env-var to be set so this adds a default.
=> [ENGINE] Hotfixing the integration tests

packages/engine/src/simulation/package/state/packages/behavior_execution/package.js, packages/engine/src/worker/runner/javascript/runner.js
JavaScript behaviors are off by 2. This PR changes the stack trace generation for JS Code to return the right line numbers.
- When improving error handling, the stack trace can be used to display a pretty trace to the user.
- Use `prepare_user_trace` as `Error.prepareStackTrace`
- This produces not a string as trace but a dictionary, which can be parsed
- [Asana task](https://app.asana.com/0/1201481007343159/1201674006952090/f) (_internal_)
Use any JS simulation, add an error (e.g. `throw new Error("JavaScript error handling is stupid");`) and watch the output.
Before:
```
0.144500954s ERROR orchestrator::experiment: Got error: "Worker error: JavaScript runner error: Error in package: Error: \"Error: JavaScript error handling is stupid\\n    at Object.behavior [as fn] (eval at …
```
=> Fix line numbers for JavaScript runner

packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/src/simulation/agent_control.rs, packages/engine/src/simulation/command.rs, packages/engine/src/simulation/comms/mod.rs, packages/engine/src/simulation/controller/run.rs, packages/engine/src/simulation/engine.rs, packages/engine/src/simulation/status.rs, packages/engine/src/simulation/step_result.rs, packages/engine/tests/units/message/mod.rs
Adds support for stop-messages
- Renames `CreateRemoveCommands` to `Commands` and include `StopMessage`
- Handle `"stop"` messages from agents and forwards it to the orchestrator
- Logs the stop message and fail if the status is `"error"`
- [Messages documentation](https://hash.ai/docs/simulation/creating-simulations/agent-messages/built-in-message-handlers#Stopping-a-simulation)
- [Asana task](https://app.asana.com/0/1199550852792314/1201630005867419/f) (_internal_)
- This PR enables the integration test covering this exact case
- Run `cargo test`
or
- Run a simulation sending the `"stop"` message to `"hash"`
Sending a message with `"data": { "status": "success", "reason": "<stop message provided by a behavior>" }`
```
0.276331810s INFO orchestrator::experiment: Simulation stopped …
```
=> [ENGINE] Handle stop messages from agents

packages/engine/tests/integration.rs, packages/engine/tests/units/experiment.rs
#218 made passing the `Language` to `run_test!` required, this PR reverts the change because we also want to test multiple language runners at once and run more complex simulations. When specifying a language here could be confusing.
- Add integration tests with multiple languages
- Add more complex integration tests
Reverts the macro change from #218
#218 forgot to update the documentation, the docs are now correct again
- #218
=> [ENGINE] Make language in integration test macro optional (again)

packages/blocks/header/package.json, packages/blocks/header/src/App.tsx, packages/blocks/paragraph/package.json, packages/blocks/paragraph/src/App.tsx, packages/blocks/paragraph/src/webpack-dev-server.js, packages/hash/playwright/tests/page-creation.spec.ts
As a part of the blockprotocol website, this PR fixes rendering for the header and para blocks in the hub. Users can optionally pass the `text` property instead of `editableRef` to have some text render inside the block.
It also adds examples for both blocks as an extension to PR #227
Check commits.
- [Fix header and paragraph block rendering in hub](https://app.asana.com/0/1201668052739245/1201624051032817/f)
=> [FE] Fix Paragraph and Header rendering in hub

packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/src/simulation/agent_control.rs, packages/engine/src/simulation/command.rs, packages/engine/src/simulation/engine.rs, packages/engine/src/simulation/status.rs
Adds the agent's UUID to the stop message
- #235 
```
0.303205213s  INFO orchestrator::experiment: Simulation stopped by agent `366f9a12-a629-400b-ba7d-c0feb527a606` successfully: test
at lib/orchestrator/src/experiment.rs:170
in orchestrator::experiment::run with project_name="stop_simulation" experiment_id=57bd184c-c3aa-4076-b5dc-22f4f8d3f2d6
```
=> Add Agent UUID to stop message

packages/engine/tests/units/experiment.rs
In integration tests we have a config file with the expected test outputs. We specify a specific step and compare the results to the actual outputs. The steps are stored as `HashMap` with the step as key. If a test fails with the output at step Y, we don't know, if the test would already fail on step X (with step X < step Y) as `HashMaps` are unsorted. This PR sorts the map before comparing to the outputs to compare expected outputs to actual outputs chronologically. If now step Y fails, we now, that step X was successful.
=> Sort test outputs

packages/engine/bin/cli/src/main.rs, packages/engine/bin/server/src/main.rs, packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/lib/orchestrator/src/process/local.rs, packages/engine/src/args.rs, packages/engine/src/utils.rs, packages/engine/tests/integration.rs, packages/engine/tests/units/experiment.rs, packages/engine/tests/units/message/stop_simulation/src/behaviors/test.js
We are going to measure performance in integration tests. In order to do this, the output should be stored for each test separately. This PR makes logging output configurable ~~(not from the CLI but when using the orchestrator)~~ and changes the testing output strategy.
This also speed ups our testing suite as we are not outputting every simulation to the terminal.
- Add command line arguments for server-binary (logic mainly in _packages/engine/src/utils.rs_)
- `--output`: Output location, either `stderr`, `stdout` or a file name. File is relative to `--log-folder`
- `--log-folder`: Logs are stored in this directory
- ~~Default to `RUST_LOG=trace` in tests (will not overwrite user-defined environment)~~
- Make `RUST_LOG` be over-writable by environment variables
- Use "pretty" for output …
=> Make Logging output configurable for tests

packages/engine/src/experiment/controller/controller.rs, packages/engine/src/simulation/comms/package.rs, packages/engine/src/simulation/engine.rs, packages/engine/src/simulation/package/context/mod.rs, packages/engine/src/simulation/package/context/packages/agent_messages/mod.rs, packages/engine/src/simulation/package/context/packages/api_requests/mod.rs, packages/engine/src/simulation/package/context/packages/neighbors/mod.rs, packages/engine/src/simulation/package/init/packages/js_py/mod.rs, packages/engine/src/simulation/package/output/mod.rs, packages/engine/src/simulation/package/output/packages/analysis/mod.rs, packages/engine/src/simulation/package/output/packages/json_state/mod.rs, packages/engine/src/simulation/package/run.rs, packages/engine/src/simulation/package/state/mod.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/mod.rs, packages/engine/src/simulation/package/state/packages/topology/mod.rs, packages/engine/src/worker/runner/javascript/mod.rs
Expands upon the work done in #228 by adding more spans around key parts of code execution. 
This greatly improves the timings produced by TeXRay, and adds additional information to general logging.
It also cleans up some of the logging in general, where we have messages that are far too large to be printed.
- Overrides the Debug impl for the `SuccessMessage` in the JsPy init package, as we shouldn't be printing the full Agent JSON, that can be far too large
- Removes a trace log in the Javascript runner where we log every message (including init messages like above) which can be far too large and pollutes the logs.
- Adds Spans for the following
- Running Init Packages 
- Preparing for Context Packages
- Running Context Packages
- A span for each package
- A span for the run method
- A …
=> [ENGINE] Adding more Spans

packages/blocks/image/src/Image.tsx, packages/blocks/video/src/Video.tsx
In the present demo for media blocks in the [blocks hub](https://blockprotocol.org/hub), the media blocks appear to be working fine on first render. However, on clicking the editing pencil, one quickly realizes the blocks update don't work, which I have traced back to the UI rendering condition I've updated in this PR.
As a part of this PR, users will be able to update the media blocks as easily as they do so in the HASH app.
- [Add `userIsEditing` key to handle edit state](https://github.com/hashintel/hash/pull/244/files#diff-6885e28abf53ee8f6e0799552660e0d4e4e9a00bdb59ad43b19c7d091bca4f0cR112)
- [Decide which state to render based on the previous state](https://github.com/hashintel/hash/pull/244/files#diff-e0b0728aab1c50ff39ee7d7178fc58c8369c8585841d34962443bfc463cb72a7R296)
- [Fix …
=> [FE] Fix media blocks updates in hub

packages/engine/src/datastore/table/pool/agent.rs
This PR fixes the function `get_batch_at_index` to return `Some(batch)` if there is a batch at that index and `None` otherwise. Previously when there wasn't a batch at the index, it returned a misleading error about acquiring a write lock.
* `get_batch_at_index` returns `None` when there is no batch at the index.
* `get_batch_at_index` acquires a read lock, not a write lock, because a write lock isn't necessary.
No
- [Asana task](https://app.asana.com/0/1201481007343159/1201545519802517/f) (_internal_)
Integration tests
1.  Run JavaScript integration tests.
2. No errors like "failed to acquire batch lock" should occur.
=> Fix getting batch at maybe existing index

packages/engine/lib/orchestrator/src/experiment.rs
The CLI panicked when providing an invalid number to `--num-workers` as `validator = ` replaces the default validator.
Make CLI arguments global so one can pass things like `--num-workers` after the subcommand
- Forwards the error returned from `parse`
- Add conditional compilation for the otherwise unused function `at_least_one`
Run the CLI with different arguments to `--num-workers`
=> Fix `--num-workers` panicking when passing an invalid digit

packages/engine/bin/cli/src/main.rs, packages/engine/lib/orchestrator/src/experiment.rs
Mark a lot of the CLI arguments as global if they are not required (limited behavior by clap). We do this so it doesn't matter if the parameters are passed before or after the subcommand (`single-run` or `simple`). Without doing this, the error message was very unclear when a user put, for example, `--num-workers` after `single-run`.
- Remove unused CLI arguments, left over from previous changes
- Add `global = true` to clap arguments
=> [ENGINE] Make CLI arguments global

packages/engine/src/simulation/package/init/packages/js_py/package.py, packages/engine/src/simulation/package/run.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/fields/mod.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/mod.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/package.js, packages/engine/src/simulation/package/state/packages/behavior_execution/package.py, packages/engine/src/worker/mod.rs, packages/engine/src/worker/runner/javascript/state.js, packages/engine/src/worker/runner/python/message.py, packages/engine/src/worker/runner/python/runner.py, packages/engine/src/worker/runner/python/state.py, packages/engine/tests/units/data/csv/access/src/behaviors/test.py, packages/engine/tests/units/data/json/access/src/behaviors/test.py, packages/engine/tests/units/data/json/immutable/src/behaviors/test.py, packages/engine/tests/units/data/json/mod.rs, packages/engine/tests/units/globals/mod.rs, packages/engine/tests/units/neighbors/fields/mod.rs
The `dev/python-fixes` branch is failing integration tests for a variety of reasons. This PR fixes some of them.
1. **The Python implementation of Init Packages**
2. **Missing Experiment Context**
3. **behavior_index() was broken**
4. **Python errors being received in Rust** - Previously, if an error occurred in the Python runner (whether a runner, package or user error), a second error would then occur when trying to receive the first error, because the first error was serialized incorrectly to flatbuffers. This PR fixes the flatbuffers serialization.
* Temporarily ignore integration tests about immutability.
* (1) Fix structure/format of message (containing agent JSON) returned from init package
* (2) Fix experiment context propagation during init.
* (3) Make the `behavior_index` field …
=> [ENGINE] Fix a variety of Errors around the Python runner

.github/workflows/rust.yml
Always run test suite for engine when the engine has changed. This avoids thinks like #257.
- [Asana task](https://app.asana.com/0/1201707629991362/1201643790165301/f) (_internal_)
=> [ENGINE] Run test suite for packages/engine everytime the engine changed

packages/hash/api/src/collab/Instance.ts, packages/hash/api/src/collab/util.ts, packages/hash/shared/src/entityStore.ts, packages/hash/shared/src/util.ts
In order to create an entity store from a given entity or set of entities, we walk the value looking for values that look like block entities, and then insert the block entity and any important "subentities" (i.e, `block.properties.entity` and also any text entities if this is a text block). 
This process currently returns multiple copies of the block entity when working on text variants. This is a bug, but probably harmless. This PR fixes that bug. 
N/A
N/A
This bug/simplification was discovered when updating collab's change detection/processing mechanism – a PR depending on this PR will follow. 
- https://github.com/hashintel/hash/pull/260
- `findEntities` won't now return duplicates when building an entity store from a text block with a variant entity. 
- `findEntities` doesn't need to …
=> Don't process entities twice when creating entity store

.github/workflows/rust.yml, packages/engine/tests/integration.rs, packages/engine/tests/units/experiment.rs
Runs the integration test suite as release build and captures timings to be uploaded
Log the timings and compare them between PR and `main`
- Adds a new job  `bench` to the Rust CI
- Adjust `setup` job to run `bench` when "packages/engine" tests has to run
- Print timing information from tests
- [Asana task](https://app.asana.com/0/1201707629991362/1201762844341058/f) (_internal_)
=> Add bench Action to CI

packages/engine/src/datastore/table/task_shared_store.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/tasks.rs, packages/engine/src/worker/runner/javascript/mod.rs, packages/engine/src/worker/runner/python/sender.rs
Large simple simulations were breaking (500,000+ agents) due to some odd errors about group indices.
This PR fixes that error, and a following error to do with task distribution across groups of agents.
We know about shared write-access issues, that occasionally appear within CI runs, etc.
> failed to acquire write locks on batches in pool
This is now happening every time on a simple simulation with 500,000 agents.
We've also identified that Tasks that are split by group are ended prematurely, we need to wait for all individual messages _within_ a task. 
- Follow Up PR to handle write access with distributed tasks
- Renames some fields to be more self-explanatory
- Adds a function to take a TaskSharedStore and safely partition it into many TaskSharedStores for each group within it.
- …
=> Fixing dynamic groups

.github/workflows/rust.yml
Changes the Rust CI to not wait for `bench` to be able to merge
=> Don't wait for `bench` to complete before merging is enabled

.github/workflows/rust.yml
Fix the Rust CI when pushing to main
- `github.head_ref` is only defined for pull requests
- Fallback to `github.run_id` to ensure the CI will run on push
=> Fallback to `run_id` when running Rust CI on push

.github/workflows/rust.yml
Running multiple benchmarks at once isn't very smart
- Limits the number of parallel tests
=> Only use one test threads when benchmarking

package.json, packages/hash/api/src/collab/Instance.ts, packages/hash/api/src/collab/util.ts, packages/hash/api/src/graphql/resolvers/block/blocks.ts, packages/hash/api/src/graphql/resolvers/block/index.ts, packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/graphql/resolvers/pages/contents.ts, packages/hash/api/src/graphql/typeDefs/block.typedef.ts, packages/hash/shared/package.json, packages/hash/shared/src/entity.test.ts, packages/hash/shared/src/entity.ts, packages/hash/shared/src/queries/page.queries.ts, packages/hash/shared/src/util.ts
This PR updates collab so that it refreshes updated entities by refreshing the block(s) these entities belongs to, instead of the entities themselves. This ensures new links are refreshed properly when updates are made to them in postgres.
Helped by @thehabbos007 on changes to tree iteration. 
N/A
- https://github.com/hashintel/hash/pull/188
- New `blocks` query in GraphQL to fetch a specified set of blocks, by `accountId` and `entityId`. 
- Abstracted the implementation of the `Page` `properties.contents` field resolver to use in the new `blocks` query
- New `LatestEntityRef` type which is similar to the existing `EntityRef` type, but not linked to a specific version of the entity. This is used to reference blocks in the new `blocks` query
- Abstracted `blockFieldsFragment` out of …
=> Refresh entire block when an entity within it changes in postgres

packages/engine/README.md, packages/engine/lib/orchestrator/src/manifest.rs, packages/engine/src/experiment/controller/run.rs, packages/engine/src/output/local/mod.rs, packages/engine/src/output/local/sim.rs, packages/engine/src/proto.rs, packages/engine/src/simulation/package/deps.rs
We previously allowed users to set a project_name and this was used in output structure.
This was accidentally removed in a previous PR.
This PR re-adds the project name and structure albeit in a different implementation to before. It's also no longer overrideable from the CLI
- Modifies `ProjectBase` to include a `name` field
- Modifies the output directory to once again have the project name as a top-level folder
- A few tiny driveby clean-ups
- A small clarification to the README was included
- [Asana task](https://app.asana.com/0/1201707629991362/1201778502679423/f) (_internal_)
- None
1.  Run any simulation or experiment, check the output folder
=> Propagating the project name and using in output

.github/workflows/rust.yml, packages/engine/src/output/local/mod.rs
The Rust CI has a "merging-enabled" job. This was changed to run only on PRs, but now it's skipped if the previous steps are failing. Running it always isn't a big deal for pushes as it's almost a no-op, but for Pull Requests it's much clearer when it's failing instead of being skipped.
=> Fix Rust CI to always run "merging-enabled"

packages/engine/src/datastore/store.rs, packages/engine/src/datastore/table/proxy.rs, packages/engine/src/datastore/table/state/create_remove/planner.rs, packages/engine/src/datastore/table/state/mod.rs, packages/engine/src/datastore/table/task_shared_store.rs, packages/engine/src/output/local/mod.rs, packages/engine/src/simulation/comms/mod.rs, packages/engine/src/simulation/engine.rs, packages/engine/src/simulation/package/context/packages/agent_messages/mod.rs, packages/engine/src/simulation/package/context/packages/api_requests/mod.rs, packages/engine/src/simulation/package/context/packages/neighbors/mod.rs, packages/engine/src/simulation/package/mod.rs, packages/engine/src/simulation/package/output/packages/analysis/mod.rs, packages/engine/src/simulation/package/output/packages/json_state/mod.rs, packages/engine/src/simulation/package/run.rs, packages/engine/src/simulation/package/state/mod.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/chain.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/mod.rs, packages/engine/src/simulation/package/state/packages/topology/mod.rs
`State` and `StateMut` can be merged into a single struct, instead `&mut` and `mut` should be used properly. 
- Use the Proxy API for states
- Move `state::Inner` into `state::State`
- Move `state::StateMut` into `state::State`
- Removes `ReadState` and `WriteState` as they are not needed anymore
- [Asana task](https://app.asana.com/0/1201707629991362/1201778198730315/f) (_internal_)
=> Refactor `State`, `StateMut` and `Inner` into `State`

.github/workflows/rust.yml, packages/engine/Cargo.lock, packages/engine/Cargo.toml, packages/engine/README.md, packages/engine/bin/cli/Cargo.toml, packages/engine/bin/cli/src/main.rs, packages/engine/bin/hash_engine/Cargo.toml, packages/engine/bin/hash_engine/src/main.rs, packages/engine/lib/orchestrator/Cargo.toml, packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/lib/orchestrator/src/experiment_server.rs, packages/engine/lib/orchestrator/src/manifest.rs, packages/engine/lib/orchestrator/src/process/local.rs, packages/engine/lib/orchestrator/src/process/mod.rs, packages/engine/src/datastore/schema/field_spec/creator.rs, packages/engine/src/worker/runner/python/main.py, packages/engine/src/worker/runner/python/setup.py, packages/engine/tests/experiment/mod.rs, packages/engine/tests/integration.rs
The engine itself is composed of a lib crate and a binary crate. We had them both called `hash_engine` which was causing problems with things like generating docs.
- [Asana task](https://app.asana.com/0/1201707629991362/1201660430639978/f) (_internal_)
- Integration and unit tests
=> Renaming the lib component of hash_engine to hash_engine_lib

packages/engine/src/datastore/arrow/batch_conversion.rs, packages/engine/src/datastore/arrow/field_conversion.rs, packages/engine/src/datastore/batch/migration/mod.rs, packages/engine/src/worker/runner/javascript/mini_v8/ffi.rs, packages/engine/src/worker/runner/javascript/mini_v8/mini_v8.rs, packages/engine/src/worker/runner/javascript/mini_v8/tests/function.rs, packages/engine/src/worker/runner/javascript/mini_v8/tests/mini_v8.rs
Fixes and re-enables unit-tests that were ignored.
There are some more ignored unit-tests within the datastore. 
We'll fix and re-enable the unit tests within Datastore after some imminent work is completed on restructuring read/write access to state and context objects. 
- Fixes remnants of a rename of `serialized` to `any_type_fields` in schema metadata and re-enables field_conversion tests that were mistakenly ignored because of it.
- Re-enables unit-tests in batch migration that were broken for the same reason
- Removes an additional unnecessary test module within the test module in batch migration (**the git diff is big because of this, no code changes were made outside of removing the nesting and commented imports**) 
- Removes the `timeout` field from the mv8 `Script` object as it …
=> Fix unit tests

packages/blocks/code/package.json, packages/blocks/divider/package.json, packages/blocks/embed/package.json, packages/blocks/header/package.json, packages/blocks/html-para/block-metadata.json, packages/blocks/html-para/package.json, packages/blocks/image/package.json, packages/blocks/paragraph/package.json, packages/blocks/person/package.json, packages/blocks/table/package.json, packages/blocks/video/package.json
This PR is a follow-up to https://github.com/blockprotocol/blockprotocol/pull/198, updating the `repository` fields in `package.json` to include the `main` branch, as described in the npm [`package.json` spec](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository).
Without this update, the above-mentioned PR would link to `master` as the default branch, which is not the link we desire.
- [Add #main to package.json:repository for blocks in hashintel/hash/packages/blocks](https://app.asana.com/0/1201707629991380/1201785439041126/f)
=> Update branch for block repository fields to main

packages/engine/rust-toolchain.toml
We currently encounter an error in CI, this PR attempts to fix this by bumping the toolchain.
- rust-lang/rust#93633
=> Bump Rust toolchain to 2202-02-10

.github/workflows/rust.yml, packages/engine/tests/experiment/mod.rs
As our CI is now (more or less) stable with #281 merged, we can remove the attempting strategy
As the benchmark now runs in a reasonable time, we can require it to merge a PR
- Removes the attempting strategy from tests and CI
- Replace test output file instead of appending to it
=> Remove attempting strategy in integration tests

.github/workflows/rust.yml
As our CI is now (more or less) stable with #281 merged, we can require the bench CI to pass before merging is enabled.
- Require `bench` Action to pass
=> Require bench CI to pass before merging is enabled

.github/workflows/rust.yml
Currently, the Rust CI only runs, if a crate was changed. As we require the CI to pass, it should run when changing it.
- Checks for _.github/_ folder to run tests
- Remove the `break` statement from loop, otherwise, only the first crate will be tested. This has no implications for the tests as duplications will be removed later.
=> Always run Rust CI when a workflow file has changed

packages/engine/tests/experiment/mod.rs
If two tests start at the same time, they may use the same NNG URL. To avoid this, we should use a UUID instead.
=> Use UUID for generating the NNG url in tests

packages/engine/tests/examples/mod.rs
As our CI is now (more or less) stable with #281 merged, we can now run our example simulations in debug builds
- Enable module `integration::examples` for debug builds
=> Enable examples in debug builds

.github/workflows/rust.yml, packages/engine/bin/cli/src/main.rs, packages/engine/bin/hash_engine/src/main.rs, packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/lib/orchestrator/src/process/local.rs, packages/engine/src/args.rs, packages/engine/src/utils.rs, packages/engine/tests/experiment/mod.rs
If our tests are failing, we want to know why. As always running them with `RUST_LOG=trace` affects performance, they should run with a lower severity unless it fails.
- Adds a command-line argument to specify the `LogLevel`
- Runs tests with `LogLevel::Warning` and rerun it with `LogLevel::Trace` if it failed
- If `RUST_LOG` is set manually, only one attempt is running
=> Rerun integration test with `LogLevel::Trace` if `RUST_LOG` is not set manually

packages/engine/src/datastore/table/context/mod.rs, packages/engine/src/datastore/table/sync.rs, packages/engine/src/simulation/comms/mod.rs
In order to access the `Context`, it's not required to use a Proxy
Do this for the rest of `Batch`es
Removes the `RwLock` inside of `Context`
- [Asana task](https://app.asana.com/0/1201707629991362/1201822309177039/f) (_internal_)
=> Remove `Proxy` for `ContextBatch` access

packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/lib/orchestrator/src/process/local.rs
If the orchestrator timed out while waiting for an Engine response, we still gave an Ok(()) return. This PR fixes that and clarifies the messages.
=> Clarifying orchestrator experiment error logic

packages/engine/bin/cli/src/main.rs, packages/engine/bin/hash_engine/src/main.rs, packages/engine/src/utils.rs, packages/engine/tests/experiment/mod.rs
We use RUST_LOG in the integration tests to encapsulate information about how to run the engine subprocesses (this also makes it difficult to use crates like [tracing_test](https://docs.rs/tracing-test/latest/tracing_test/)). 
Because of this we actually had broken logging coming from the testing suite itself. This PR fixes that
- Initialises the Logger from the testing suite
- Changes some variable names to be clearer
- [Asana task](https://app.asana.com/0/1201707629991362/1201823931582526/f) (_internal_)
- CI integration tests
=> Fixing logging in integration tests

packages/engine/tests/units/state/edit/dot/bool_array/src/behaviors/test.js, packages/engine/tests/units/state/edit/dot/number_array/src/behaviors/test.js, packages/engine/tests/units/state/edit/dot/object_array/src/behaviors/test.js
JavaScript does not have a built-in type for lists like Python's `list`, so `typeof ["a"]` will return "object". To improve testing stability, we want to check for lists with `Array.isArray` instead.
Replaces `typeof <list>` checks with `Array.isArray` checks.
=> Improve checking for array type in JS state tests

packages/engine/tests/units/state/edit/dot/object/src/behaviors/test.js, packages/engine/tests/units/state/edit/dot/object_array/src/behaviors/test.js, packages/engine/tests/units/state/edit/index/bool_array/src/behaviors/test.js, packages/engine/tests/units/state/edit/index/number_array/src/behaviors/test.js, packages/engine/tests/units/state/edit/index/object/src/behaviors/test.js, packages/engine/tests/units/state/edit/index/object_array/src/behaviors/test.js, packages/engine/tests/units/state/edit/set_get/bool_array/src/behaviors/test.js, packages/engine/tests/units/state/edit/set_get/number_array/src/behaviors/test.js, packages/engine/tests/units/state/edit/set_get/object/src/behaviors/test.js, packages/engine/tests/units/state/edit/set_get/object_array/src/behaviors/test.js, packages/engine/tests/units/state/empty/object/src/behaviors/test.js
JavaScript does not have a built-in type for lists like Python's `list`, so `typeof ["a"]` will return "object". To improve testing stability, we want to check for lists with `Array.isArray` instead. For actual structs, this also adds checks, if the type is **not** an array.
- Replaces more `typeof <list>` checks with `Array.isArray` checks.
- Adds `!Array.isArray` for struct fields
Also, apply it to #301
- [Asana task](https://app.asana.com/0/1201793759102797/1201816386539221/f) (_internal_)
This is to improve the stability of the touched tests
=> Improve checking for struct and arrays in JS tests

packages/engine/src/datastore/table/context/mod.rs, packages/engine/src/datastore/table/pool/message.rs, packages/engine/src/datastore/table/pool/mod.rs, packages/engine/src/datastore/table/state/create_remove/plan.rs
When removing batches from a Pool, we previously returned a proxy. This was misleading as it didn't clearly explain we were dropping the Batch in the method (a proxy sort of implied we were viewing the batch and dropping the view).
Those methods were only used when tracking IDs of Batches we removed, so the methods have been changed to return Batch IDs instead of proxies/batches.
- Changes `remove` and `swap_remove` on the Pool traits to return a `String`
- Updates the areas of the code that called them, cleaning up the iters
No
- [Asana task](https://app.asana.com/0/1201793759102797/1201819939567711/f) (_internal_)
- Standard integration tests, maybe
=> Changing the remove methods on BatchPools to return the ID

.github/workflows/rust.yml
Currently, we only run Rust CI on pull requests (and the `bench` job when pushing to main). In order to rely on CI when pushing to a branch like `td/my-wip-branch`, CI can simply be run on every push.
None:
- Secrets are not exposed
- [CI for Open Source repositories is free](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration):
> GitHub Actions usage is free for both public repositories and self-hosted runners
- Removes the limitation on `push`-branches
- Removes check to only run tests on `pull_request`s
- As `bench` runs pretty long on push (10 samples), it's limited to pull requests and `main`
- **This does not change the behavior when the CI is running in regards to changed files, so it will still only run if `A-Engine` changes** (And when …
=> Run Rust CI on push

package.json, yarn.lock
Author of `check-dependency-version-consistency` [implemented](https://github.com/bmish/check-dependency-version-consistency/pull/343) my [feature request](https://github.com/bmish/check-dependency-version-consistency/issues/332) 🎉 This PR hardens our checks by upgrading the dependency.
We are now protected against wrong version numbers for our own packages, a mistake I have made before.
No
Same change in the Block Protocol repo: https://github.com/blockprotocol/blockprotocol/pull/221
CI
1. Change package version of any app inside `packages/hash/*`.
1. Run `yarn lint:dependency-version-consistency`
1. Observe the error
1. Revert and run the same command again, observe no error.
Here is what happens if I change `@hashintel/hash-shared` version to `0.4.2` in …
=> Upgrade `check-dependency-version-consistency` to v2

packages/hash/api/datastore/postgres/schema/0000_base.sql, packages/hash/api/datastore/postgres/schema/0002_citus_setup.sql, packages/hash/api/datastore/postgres/schema/0003_foreign_keys.sql, packages/hash/api/src/db/postgres/client.ts, packages/hash/api/src/db/postgres/entity.ts, packages/hash/api/src/db/postgres/link/createLink.ts, packages/hash/api/src/db/postgres/link/getEntityOutgoingLinks.ts, packages/hash/api/src/db/postgres/link/util.ts
This PR deprecates a legacy `outgoing_links` lookup table, whose functionality has been replaced by the dedicated `links` table (introduced as part of https://github.com/hashintel/dev/pull/293).
- removes all references to the `outgoing_links` table
- refractors postgres query for getting outgoing links of an entity to uniquely use `links` table
- [Asana task](https://app.asana.com/0/1201095311341924/1201610239258382/f) (_internal_)
- various integration tests make use of the the `getOutgoingLinks` db adapter method, which (to my knowledge) is the only place the `outgoing_links` table was used prior to this PR
=> Deprecate legacy `outgoing_links` lookup table

.github/workflows/algolia-upload-index.yml
This PR fixes https://github.com/hashintel/hash/actions/workflows/algolia-upload-index.yml. This is done by removing a [broken optimization](https://github.com/hashintel/hash/pull/324/files#r809292163) added in #324.
[Error example](https://github.com/hashintel/hash/runs/5301110474?check_suite_focus=true):
```txt
[4/4] Building fresh packages...
error /home/runner/work/hash/hash/node_modules/postinstall-postinstall: Command failed.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Exit code: 1
Command: node ./run.js
Arguments: 
Directory: /home/runner/work/hash/hash/node_modules/postinstall-postinstall
Output:
Error: Patch file found for package prosemirror-model which is not present at node_modules/@types/prosemirror-model
Error: Patch file found …
```
=> Fix `yarn install` in Algolia CI

packages/engine/format/package_error.fbs, packages/engine/format/user_error.fbs, packages/engine/lib/flatbuffers_gen/src/package_error_generated.rs, packages/engine/lib/flatbuffers_gen/src/user_error_generated.rs, packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/src/experiment/controller/controller.rs, packages/engine/src/proto.rs, packages/engine/src/worker/mod.rs, packages/engine/src/worker/runner/comms/outbound.rs, packages/engine/src/worker/runner/javascript/error.rs, packages/engine/src/worker/runner/javascript/mod.rs, packages/engine/src/workerpool/comms/mod.rs, packages/engine/src/workerpool/comms/top.rs, packages/engine/src/workerpool/mod.rs
We distinguish between errors/warnings that come from the Runner and those that come from user-code. There was a TODO about implementing these variants and properly propagating them. This PR does that.
It also fixes a mistake where certain classifications of errors were marked as fatal for the runners (thus killing an experiment rather than just a simulation), when they shouldn't have been. (User errors and Package errors are non-fatal).
- Makes the msg strings on `PackageError` and `UserError` required in the FlatBuffers schemas. It doesn't make sense to propagate these without any associated error information
- Creates the `UserError`, `UserWarning`, and `PackageError` variants on all the relevant enums within the Rust code, propagating it up to the orchestrator for display.
- …
=> Propagating the UserErrors, UserWarnings, and PackageError variants

packages/engine/src/worker/runner/javascript/hash_util.js
Since arrow-rs version 3.0.0, the inner types of `List`s and `FixedSizeList`s are named. This change adjusts the JS side.
- The check for a primitive/list relies on duck-typing. This is very bad considering we should have known the actual type. This will be fixed, when we switch to TS.
- Change the checks for primitive/list in JS find the field `"item"`, which is now the default name for `List`'s and `FixedSizeList`'s inner type
No
=> Fix checking for primitive and lists arrow types in JS

packages/engine/src/worker/runner/javascript/mod.rs
For loading the arrow data from JavaScript, we previously did some real low level stuff, which is not needed anymore.
Use more builders in the rest of the code
- Changes `array_data_from_js` to use an `ArrayDataBuilder` instead of building int by hand
- Use builders for data where possible
It's not possible (or not a good idea) to use non-buffer builders, as the data already exists (behind pointers). Otherwise the data would need to be parsed and recreated from scratch, which would hit the performance badly.
No
- [Asana task](https://app.asana.com/0/1201793759102797/1201877648275953/f) (_internal_)
None directly, this function is indirectly tested by integration tests.
=> Use Builders for `array_data_from_js`

packages/engine/Cargo.lock, packages/engine/Cargo.toml
We want to use the latest version of arrow-rs
None
Fix the last issue to merge the dev-branch into main
- Bumps the arrow version from 9.0.2 to 9.1.0
No
=> Bump arrow version to 9.1.0

packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/lib/orchestrator/src/process/local.rs, packages/engine/lib/orchestrator/src/process/mod.rs
We currently don't check if the `hash_engine` process has actually finished, instead, we wait for responses and also wait on a timeout.
- Change the `orchestrator` to use `tokio::process` rather than `std::process
- Add `async fn wait()` to the `Process` trait
- Add a `select!` arm to `wait()` on the engine process
No.
- [Asana task](https://app.asana.com/0/1201893074552404/1201837823804295/f) (_internal_)
We don't have tests for abnormally exiting the engine process.
1. Set the `ENGINE_WAIT_TIMEOUT` to a high value
3. Run a simulation, which is 
4. Kill the engine subprocess
5. Verify that the orchestrator is exiting
```
3.529230193s ERROR run: orchestrator::experiment: Engine process errored with exit code signal: 15
```
=> Exit orchestrator if engine process exits abnormally

packages/hash/api/src/db/adapter.ts, packages/hash/api/src/db/postgres/client.ts, packages/hash/api/src/db/postgres/index.ts, packages/hash/api/src/db/postgres/link/getEntityOutgoingLinks.ts, packages/hash/api/src/graphql/resolvers/pages/accountPages.ts, packages/hash/api/src/graphql/resolvers/pages/linkedEntities.ts, packages/hash/api/src/graphql/resolvers/pages/setParentPage.ts, packages/hash/api/src/graphql/typeDefs/page.typedef.ts, packages/hash/api/src/model/page.model.ts, packages/hash/integration/src/graphql/queries/page.queries.ts, packages/hash/integration/src/tests/integration.test.ts
This PR is a follow up to #230, which is also useful for implementing the sidebar design that @teenoh is implementing.
Instead of deleting links manually to remove a parent page, this change allows API users to set the `parentPageId` to `null` in order to specify that a page should have no parent - deleting any existing parent page link.
- Use the APIs in the new sidebar
- GQL documentation of the mutaiton (done)
- [Asana task](https://app.asana.com/0/1201837296904616/1201906825107761/f) (_internal_)
- Integration tests
Follow test procedure of #230 and use `null`  as a `parentPageId`
=> Allow removing parent page links from the setParentPage mutation

packages/blocks/table/src/Table.tsx, packages/blocks/table/src/devRenderer.tsx, packages/hash/frontend/src/blocks/page/ComponentView.tsx, packages/hash/frontend/src/components/EntityEditor/types.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/useBlockProtocolCreateLinks.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/useBlockProtocolUpdateLinks.ts, patches/blockprotocol+0.0.1.patch
Fixes the table block so that users can select a type when a type is not yet selected.
In conjunction with https://github.com/blockprotocol/blockprotocol/pull/249, this fixes the [table block in the Block Hub](https://blockprotocol.org/@hash/blocks/table).
In the order they appear in the diff:
- remove some redundant code passing `data` to the table block
- remove some code that was just removing `__typename` in arguments passed out of the Table block - this is a GraphQL-specific thing that should be handled by the embedding application instead
- change `updatedOperation` argument on `BlockProtocolUpdateLinksFunction` to `data`, to match the spec (we can sort this out properly when we split out CRUD operations for links and linkedAggregations)
- create a link if none already exist, i.e. …
=> Fix selecting the type on table block when none is selected

packages/hash/api/src/db/errors.ts, packages/hash/api/src/db/index.ts, packages/hash/api/src/db/postgres/aggregation/updateAggregationOperation.ts, packages/hash/api/src/db/postgres/aggregation/util.ts
This task removes the `getAggregation` postgres utility method, as it implements the same functionality of the existing `getEntityAggregation` db adapter method (which can be used instead).
Note: This indirectly addresses [this task](https://app.asana.com/0/1201825402400452/1201820398013202/f)
- removes `getAggregation` pg utility method
- adds `DbAggregationNotFoundError` error class, to be thrown when `getEntityAggregation` unexpectedly returns null
No
- [Asana task](https://app.asana.com/0/1201825402400452/1201820398013202/f) (_internal_)
- existing aggregation tests
=> Remove redundant `getAggregation` pg utility method

packages/hash/api/datastore/postgres/schema/0000_base.sql, packages/hash/api/src/db/adapter.ts, packages/hash/api/src/db/postgres/client.ts, packages/hash/api/src/db/postgres/entity.ts, packages/hash/api/src/db/postgres/history.ts, packages/hash/api/src/db/postgres/index.ts, packages/hash/api/src/db/postgres/link/createLink.ts, packages/hash/api/src/db/postgres/link/deleteLink.ts, packages/hash/api/src/db/postgres/link/getEntityOutgoingLinks.ts, packages/hash/api/src/db/postgres/link/getLink.ts, packages/hash/api/src/db/postgres/link/util.ts, packages/hash/api/src/model/entity.model.ts, packages/hash/api/src/model/link.model.ts, packages/hash/api/src/model/page.model.ts, packages/hash/integration/src/graphql/queries/page.queries.ts, packages/hash/integration/src/tests/integration.test.ts, packages/hash/integration/src/tests/model/link.model.test.ts, packages/hash/integration/src/tests/model/page.model.test.ts
This PR refactors how outgoing links of versioned entities are stored in the datastore. Previously all `entityVersionId`s of a source entity that a link was valid for was stored in an `sourceEntityVersionIds` array. This had the drawbacks that:
- a new version of the source entity had to be created when its outgoing links changed
- the `sourceEntityVersionIds` array would scale significantly for links that exist for a long time
This PR replaces the `sourceEntityVersionIds` array with `appliedToSourceAt` and `removedFromSourceAt` timestamps, that indicate for which period a link was "active" in the history of its source entity.
- [Improve how versions of links are stored in the db](https://app.asana.com/0/1201095311341924/1201817757879406/f)
- [Implement way of updating a link's index …
=> Use timestamps instead of an array of `entityVersionId`s to store the source versions of links

packages/hash/frontend/jest.config.js, packages/hash/frontend/src/pages/login.test.tsx, packages/hash/frontend/src/pages/signup.test.tsx
This PR fixes the FE unit tests.
- the frontend `jest.config` now contains the required module mapper to support imports from the `@hashintel/hash-shared` package
=> Fix frontend unit tests

packages/engine/src/datastore/batch/agent.rs, packages/engine/src/datastore/batch/migration/mod.rs, packages/engine/src/datastore/table/state/create_remove/action.rs, packages/engine/src/datastore/table/state/create_remove/batch.rs, packages/engine/src/datastore/table/state/create_remove/plan.rs, packages/engine/src/datastore/table/state/create_remove/planner.rs
We had a variable called affinity in a lot of places which was confusing and not self descriptive. This renames it to a clearer `worker_index`
- CI should pass, this is just a refactor/rename
=> Renaming affinity to worker_index

packages/blocks/code/src/App.tsx
State management in the block is still based on `useEffect`. We should switch to `setState` in the render phase in most blocks.
- Update commit has in https://github.com/blockprotocol/blockprotocol/pull/258 and merge.
- If initial value of `caption ` is not empty, the caption is rendered
- Clicking on the caption button selects caption text for convenience
- Removing focus from an empty caption hides the input.
No
- [Asana task](https://app.asana.com/0/1200211978612931/1201858561350502/f) _(internal)_
- Manual
- https://github.com/blockprotocol/blockprotocol/pull/258 (see Preview Release on Vercel)
1.  Run `yarn workspace @hashintel/block-code dev`
1. Open `localhost:9000` and click around.
1. Try changing `initialData` → `caption` in …
=> Fix caption visibility in the code block

packages/blocks/code/src/App.tsx, packages/blocks/code/src/webpack-dev-server.js
Fixes the code block when the caption is undefined (currently broken, see [here](https://blockprotocol.org/@hash/blocks/code)). We shouldn't rely on users passing an empty string when there is no caption.
- [Asana task](https://app.asana.com/0/1201927504137297/1201966863964862/f) _(internal)_
1. Try passing undefined, an empty string, and a non-empty string to the code block in the dev renderer to check all work correctly
=> Fix code block when caption is undefined

packages/hash/LICENSE.md
License information was previously provided, outlining the package's licensing terms, but in the root directory. This additionally adds a dedicated AGPL license file within the `hash` folder.
=> Adds LICENSE.md file to `hash` package

packages/hash/README.md
Currently the `@opensearch-project/opensearch` package does not support node version 17. This PR updates the hash `README.md` to specify that the local developer environment cannot run using node 17.
- the readme at `packages/hash/README.md`
This is an update to the docs :)
=> Update hash README.md supported node version

packages/engine/src/simulation/task/active.rs, packages/engine/src/worker/mod.rs, packages/engine/src/worker/runner/javascript/mod.rs, packages/engine/src/worker/runner/python/mod.rs, packages/engine/src/worker/runner/python/sender.rs, packages/engine/src/workerpool/comms/mod.rs, packages/engine/src/workerpool/mod.rs, packages/engine/src/workerpool/pending.rs
Cancel-events are currently not handled. Instead of silently ignoring them, we should not even send them to the runners and `panic!` if they appear instead.
- [Handle cancel messages](https://app.asana.com/0/1199548034582004/1202011714603653/f) (_internal_, low priority)
- Panic, as soon as a cancel-method is called or a cancel message occurred at a runner
- Annotate every change with the link to the corresponding task above for easier picking it up
No
- [Asana task](https://app.asana.com/0/1201893074552404/1202011714603665/f) _(internal)_
The integration test suite would `panic!`, if there are still cancel-messages around
=> Disable cancel messages

packages/engine/tests/units/state/empty/mod.rs
This test was missed in #229, so we enable it *now*. The error for `empty::object` is the same as in JS.
=> Enable `empty::array` Python test

packages/engine/lib/clippy.toml, packages/engine/lib/error/src/ext.rs, packages/engine/lib/error/src/macros.rs, packages/engine/lib/provider/src/lib.rs, packages/engine/lib/provider/src/requisition.rs
#426 added a `clippy.toml`. This also applies that config to other library files to let newly moved-out crates directly pick it up.
`res` is used in `format!()`, thus it can't be blacklisted.
- Move `clippy.toml` from `lib/nano/` to `lib/`
- Apply lints to other crates in that directory
=> Apply clippy.toml to other library crates

packages/engine/Cargo.lock, packages/engine/Cargo.toml
Instead of relying on a random commit, this sticks the commit of `rusty_v8`, which has a well defined submodule commit for `v8`. This will hopefully be more reliable than the random commit-poking we did before.
- Stick `v8` version in https://github.com/hashdeps/rusty_v8/commit/0bf4d26961697591baf54bc4ceb0d15d3f195f86
- Stick `rusty_v8` version in 552f2602052368c2357e04ca10d859b5d7c2409f
=> Stick rusty_v8 version

packages/hash/frontend/src/blocks/page/createSuggester/BlockSuggester.tsx
The code to load block icons was not properly handling relative URLs: it was trying to construct an absolute URL by prepending `blockprotocol.org`, which won't be where all blocks come from. For some reason it also handled relative URLs with `public/` differently
The immediate benefit of this is when loading blocks locally.
- [Asana task](https://app.asana.com/0/1201959586244685/1202085228123347/f) _(internal)_
1.  Serve a block locally with a relative URL
2. Check its icon loads
=> Fix handling of relative icon urls

packages/engine/src/simulation/package/id.rs, packages/engine/src/simulation/package/state/packages/behavior_execution/package.js, packages/engine/src/simulation/package/state/packages/behavior_execution/package.py, packages/engine/src/worker/runner/javascript/state.js, packages/engine/src/worker/runner/python/state.py
We wrongly generate the `PackageId`, instead of `pow(2, package_number)` we are doing `2 ^ package_number` (= `2 XOR package_number`). This implies, that the third package for each package type (package number `2`) would become `PackageId(0)` as `2 XOR 2 == 0`, which is reserved for the engine.
Also, the `PackageId` generation was supposed to generate unique ids based on prime numbers. This was "simply" a bug.
- Change the `PackageId` generation to use `pow`
- Adjust hardcoded field keys to use the corrected value
=> Fix `PackageId` generation

.github/workflows/rust.yml
Resolving deltas on large git repositories takes a lot of time, which is a flat overhead for all CI runs.
- Cache the git checkouts cargo does
This does not affect any code, only CI
Let the CI run
=> Cache cargo checkouts in CI

packages/hash/frontend/src/pages/_app.page.tsx
This fixes a warning that has come up as a result of a mismatch between the server and client on initial render.
- Adds an extra react state `ssr` to `_app.page.tsx` to ensure the first client render is the same as the server render
- No
- [Fix Nextjs SSR Mismatch warning](https://app.asana.com/0/1202032708093162/1202115687136784) _(internal)_
- None
1.  Reload any page on the app
1.  Confirm there is no error log in console with text `"Warning: Expected server HTML to contain..."`
---
- https://app.asana.com/0/0/1202115687136784
=> Fix Nextjs SSR mismatch warning

.eslintrc.json, packages/blocks/callout/webpack-block-meta-plugin.js, packages/blocks/code/webpack-block-meta-plugin.js, packages/blocks/divider/webpack-block-meta-plugin.js, packages/blocks/embed/webpack-block-meta-plugin.js, packages/blocks/header/webpack-block-meta-plugin.js, packages/blocks/image/webpack-block-meta-plugin.js, packages/blocks/paragraph/webpack-block-meta-plugin.js, packages/blocks/person/webpack-block-meta-plugin.js, packages/blocks/table/webpack-block-meta-plugin.js, packages/blocks/video/webpack-block-meta-plugin.js, packages/hash/frontend/src/blocks/page/ComponentView.tsx, packages/hash/frontend/src/blocks/page/createSuggester/BlockSuggester.tsx, packages/hash/frontend/src/blocks/page/createSuggester/useFilteredBlocks.tsx, packages/hash/frontend/src/blocks/userBlocks.tsx, packages/hash/frontend/src/components/BlockContextMenu/SearchView.tsx, packages/hash/frontend/src/components/entityTypes/SchemaEditor/SchemaEditor.tsx, packages/hash/frontend/src/components/entityTypes/SchemaEditor/SchemaPropertiesTable.tsx, packages/hash/frontend/src/components/entityTypes/SchemaEditor/SchemaPropertyRow.tsx, packages/hash/frontend/src/components/entityTypes/SchemaEditor/SchemaPropertyTypeList.tsx, packages/hash/frontend/src/components/entityTypes/SchemaEditor/SubSchemaItem.tsx, packages/hash/frontend/src/components/entityTypes/SchemaEditor/schemaEditorReducer.ts, packages/hash/frontend/src/lib/entities.ts, packages/hash/shared/src/blockMeta.ts, packages/hash/shared/src/json-utils.ts
The primary purpose of this PR is to introduce the ability to read a `default` object from a block schema to set as its starting properties (e.g. as we do for `variants`, but on the assumption that a block has no variants).
Figuring this out took longer than it should have because we were doing things to the block's metadata in several places, so I've also taken the opportunity to consolidate all the fallbacks and string manipulation we were doing to one place.
There are a lot of deprecation warnings in the `blockMeta` file and a hint that how we're handling metadata through context is not the intended final solution, which we could usefully expand with more detail.
- We should have some way of users setting the `default` on the block schema for the autogenerated type, in …
=> Consolidate block metadata manipulation. Handle 'default' properties

packages/hash/api/src/collab/Waiting.ts, packages/hash/frontend/src/blocks/page/collab/EditorConnection.ts
This is a fix for the collab polling requests timing out different load balancers in the hosted instance.
Simply reducing the waiting timeout will put in natural ending points for the collab polling connections, allowing the frontend to restart polling.
- This is not moving to socket.io, as it introduced a whole range of issues which were quite out-of-scope to fix
This is a middle-ground PR to get collab working in the hosted instance. Next steps:
- Move to websocket based transport
- Perhaps use Yjs for its wire protocol and CRDT which would allow automatic conflict resolution
- The collab polling timeout on the server side
- [Asana task](https://app.asana.com/0/1200211978612931/1202047422882134/f) _(internal)_
Doesn't change functionality
1. Spin up the front- and backend
1. Open any …
=> Fix collab polling timeout

packages/engine/Cargo.lock
Merge a `Cargo.lock` forgotten in https://github.com/hashintel/hash/pull/487.
- Add the missing `Cargo.lock`.
No
=> Add missing Cargo.lock

.github/workflows/rust.yml, packages/engine/Cargo.toml
Making sure no generated file were forgotten when opening a PR.
This can happen with `Cargo.lock` for example.
- Add a check to make sure that the `git diff` is empty after tests.
No
In theory push a commit with an outdated `Cargo.lock`.
You can see it on this commit https://github.com/hashintel/hash/runs/6120802375?check_suite_focus=true.
As opposed to the same code but with the `Cargo.lock` https://github.com/hashintel/hash/pull/498/checks?sha=3516ca3216780945ad2c8140b4b18ff2af4f8a4d.
=> Fail CI if diff not empty during tests

.github/workflows/rust.yml, packages/engine/tests/integration.rs
Enable backtrace for tests to better understand the error.
- Set the "RUST_BACKTRACE" environment variable to 1 when running tests.
No
- [Asana task](https://app.asana.com/0/1199548034582004/1202022593956537/f) _(internal)_
In theory push a commit that makes a test panic and check the backtrace is displayed in the github action's log.
You can see it here https://github.com/hashintel/hash/runs/6130654178?check_suite_focus=true.
=> Enable Rust backtrace on CI

packages/hash/api/src/collab/EntityWatcher.ts, packages/hash/api/src/collab/Instance.ts, packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/graphql/resolvers/link/getLink.ts, packages/hash/api/src/graphql/resolvers/linkedAggregation/getLinkedAggregation.ts, packages/hash/api/src/graphql/typeDefs/aggregation.typedef.ts, packages/hash/api/src/graphql/typeDefs/link.typedef.ts, packages/hash/backend-utils/src/pgTables.ts, packages/hash/backend-utils/src/realtime.ts, packages/hash/realtime/src/config.ts, packages/hash/shared/src/queries/link.queries.ts
Our collab service, which the frontend relies on for the document state, is subscribed to realtime updates from the db for records which are updated via some other means than collab. When receiving these updates, it checks if they affect the document, and refreshes it if so.
Previously, it was only receiving updates on the `entity_versions` table. Since #364 meant that new `entity_versions` are **not** created when a link from an entity is created/updated, and #484 took the same approach for linked aggregations, there are updates which should lead to a change in the document which (a) collab is not set up to check for, and (b) realtime is not notifying subscribers about anyway.
This PR fixes that by (a) making the realtime service send out notifications of changes to links/aggregations, …
=> Watch links & aggregations via realtime, and respond in collab

packages/hash/frontend/twind.config.js
Disables the Tailwind [preflight](https://tailwindcss.com/docs/preflight) CSS. We already had `preflight: false` in `tailwind.config.js` but we also need it in `twind.config.js` to properly turn it off, which this does.
Tailwind is not sticking around in the app long term, because we're using MUI for component styling instead. We'll remove it incrementally as we redesign existing components which are currently using Tailwind.
Some elements now appear differently, e.g. link colour in sidebar, button text background.
- Check and fix styles which are now broken in the sidebar.
=> Disable twind preflight

packages/hash/frontend/src/blocks/page/BlockContextMenu/BlockContextMenu.tsx, packages/hash/frontend/src/blocks/page/BlockView.tsx, packages/hash/shared/src/ProsemirrorSchemaManager.ts
Makes the 'delete' button in the context menu delete a block. This makes it nicer to add a bunch of testing blocks and clean them up without abandoning the page.
I've also hidden the context menu items which do nothing, so that people aren't wondering if they're broken or unimplemented.
Also ordered some props to be alphabetical which were almost-but-not-quite.
- [Asana task](https://app.asana.com/0/1202055186269233/1202189029159327/f) _(internal)_
1.  Click 'delete' in the block context menu
2. Refresh to check persistence
=> Make delete block button functional. Hide non-functional buttons

packages/hash/api/src/graphql/resolvers/pages/updatePageContents.ts, packages/hash/api/src/model/page.model.ts
Fixes a bug whereby it was impossible to change the type of the first block in a page.
This was caused by a check preventing the removal of the only block in a page. We need to remove the block in order to insert a new one. 
This PR fixes it by allowing the removal of the final block if another one will be inserted in the same set of actions. 
1.  Load a new page
2. Change the type of the first block in the page
=> Permit swapping the first block in a page to another type

packages/blocks/callout/package.json, packages/blocks/code/package.json, packages/blocks/divider/package.json, packages/blocks/embed/package.json, packages/blocks/header/package.json, packages/blocks/image/package.json, packages/blocks/paragraph/package.json, packages/blocks/person/package.json, packages/blocks/table/package.json, packages/blocks/video/package.json, yarn.lock
Updates block-scripts for the whole repo, or new PRs with new versions of block scripts will fail CI due to mismatched versions.
=> Update `block-scripts` to 0.0.5

packages/hash/frontend/src/blocks/page/BlockConfigMenu/BlockConfigMenu.tsx
Currently the Block Config Menu doesn't
1. properly handle changes to properties of type "number". changes to properties get saved as a string even though the property type is a number
1. handle displaying input for properties that can either be a number or string. i.e properties with type ["number", "string"]
I noticed this when working on #515 . This PR fixes both issues 
- Update `updateProperty` to properly handle changes when the property type is "number" or ["number", "string"]
- Render an input when the property type is an array that contains "number"
- No
=> Block Configuration Menu Updates

packages/blocks/image/src/components/media.tsx, packages/blocks/table/src/table.tsx, packages/blocks/video/src/components/media.tsx, packages/hash/api/src/graphql/resolvers/link/deleteLink.ts, packages/hash/api/src/graphql/resolvers/linkedAggregation/deleteLinkedAggregation.ts, packages/hash/api/src/graphql/resolvers/linkedAggregation/linkedAggregationResults.ts, packages/hash/api/src/graphql/resolvers/linkedAggregation/updateLinkedAggregationOperation.ts, packages/hash/api/src/graphql/typeDefs/aggregation.typedef.ts, packages/hash/api/src/graphql/typeDefs/link.typedef.ts, packages/hash/api/src/model/aggregation.model.ts, packages/hash/api/src/model/entity.model.ts, packages/hash/frontend/src/components/BlockLoader/BlockLoader.tsx, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/useBlockProtocolCreateLinkedAggregations.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/useBlockProtocolCreateLinks.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/useBlockProtocolDeleteLinkedAggregations.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/useBlockProtocolDeleteLinks.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/useBlockProtocolUpdateLinkedAggregations.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/useBlockProtocolUpdateLinks.ts, packages/hash/frontend/src/components/util/typeUtils.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/shared/simple-entity-editor.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/shared/simple-entity-editor/entity-field-link-editor.tsx, packages/hash/integration/src/graphql/queries/aggregation.queries.ts, packages/hash/integration/src/tests/integration.test.ts, packages/hash/shared/src/queries/entity.queries.ts, packages/hash/shared/src/queries/link.queries.ts, patches/blockprotocol+0.0.7.patch
This PR implements three new BP methods for creating/updating/deleting the linked aggregations of an entity.
- There is a bug presumed to be related to the entity store where updates to linked aggregations are no longer reflected in the entity store. This means updating an aggregation (when toggling the entity type displayed in the table block for example) does not get reflected in the block, although the update was saved in the datastore.
- [update the `blockprotocol` package to include the updated BP method types](https://app.asana.com/0/1201095311341924/1202216335609392/f)
- [update the BP spec to include the introduced BP aggregation methods](https://app.asana.com/0/1201095311341924/1202216335609402/f)
- [implement the `useBlockProtocolUpdateLinks` hook to update links using their …
=> Implement BP hooks for creating/updating/deleting linked aggregations

packages/blocks/table/src/table.tsx
Fix the table block for two bugs:
1. It was checking for the presence of a `linkedAggregation` on the table before allowing creating one, meaning that it was impossible to create one if one didn't already exist
2. There was no provision to delete a `linkedAggregation` if the entity type selector was set to None/`undefined`
- remove check for existing `linkedAggregation` before allowing one to be created
- add `deleteLinkedAggregation` when switching back to none
I will be releasing a PR on `blockprotocol` which updates the version number there, once this is merged (it seems to be a recent breakage as the version on the hub is working).
Try a table block in HASH.
=> Fix table block updating / deleting linked aggregation

.github/actions/warm-up-repo/action.yml, .github/workflows/algolia-upload-index.yml, .github/workflows/ci.yml, package.json, packages/hash/README.md, packages/hash/backend-utils/package.json, packages/hash/backend-utils/src/search/opensearch.ts, packages/hash/search-loader/package.json, yarn.lock
The goal of this PR is to unlock the usage of Node 18. This used to be blocked by `@opensearch-project/opensearch` in which we had this problem with imports:
```
[seed-data:*opensearch] Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/errors' is not defined by "exports" in /Users/alfie/Documents/code/hash_2/node_modules/@opensearch-project/opensearch/package.json
[seed-data:*opensearch]     at new NodeError (node:internal/errors:377:5)
[seed-data:*opensearch]     at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
[seed-data:*opensearch]     at packageExportsResolve (node:internal/modules/esm/resolve:719:3)
[seed-data:*opensearch]     at resolveExports (node:internal/modules/cjs/loader:483:36)
[seed-data:*opensearch]     at Function.Module._findPath …
```
=> Fix `@opensearch-project/opensearch` compatibility with Node 18

.github/actions/docker-ecr-login/action.yml, .github/workflows/hash-backend-cd.yml, packages/hash/api/src/index.ts
This PR adds a pipeline to publish the HASH backend every time the `main` branch is merged into.
Because of prior work in #438, we are able to continuously apply changes without needing to consider a lot of edge cases in regards to the DB.
- [Asana task](https://app.asana.com/0/1200211978612931/1202142633000396/f) _(internal)_
- Add new GitHub Action for building, pushing and deploying HASH images
- Adds composite action that allows connecting to AWS and exposes the AWS CLI for our pipelines when needed
- Makes health checks more quickly available for the `api` service, as we would previously be blocked by a redis connection that would never succeed without terminating existing instances of the `api`.
- It takes around 2 minutes from the final step of the pipeline to the new services …
=> GitHub action to build services, push to ECR and (re)deploy ECS Fargate instances

packages/blocks/table/src/table.tsx, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/useBlockProtocolUpdateLinkedAggregations.ts, patches/blockprotocol+0.0.7.patch
Updates the key under which the updated `LinkedAggregation` should be passed to be called "operation" instead of "data" - suggested [here](https://github.com/blockprotocol/blockprotocol/pull/302#discussion_r865776607).
Updating here so that the counterpart PR can be merged without breaking the table block in the Block Hub. 
To follow: update `blockprotocol` version in this repo once https://github.com/blockprotocol/blockprotocol/pull/302 is merged, and reduce patch here.
=> Update BlockProtocolUpdateLinkedAggregationAction data -> operation

packages/engine/lib/stateful/src/agent/arrow/mod.rs, packages/engine/lib/stateful/src/agent/arrow/pool.rs, packages/engine/lib/stateful/src/agent/mod.rs, packages/engine/lib/stateful/src/context/batch.rs, packages/engine/lib/stateful/src/context/mod.rs, packages/engine/lib/stateful/src/message/mod.rs, packages/engine/lib/stateful/src/message/pool.rs, packages/engine/lib/stateful/src/state/column.rs, packages/engine/lib/stateful/src/state/mod.rs, packages/engine/lib/stateful/src/state/proxy.rs, packages/engine/lib/stateful/src/state/references.rs, packages/engine/lib/stateful/src/state/view.rs, packages/engine/src/datastore/table/create_remove/plan.rs, packages/engine/src/simulation/engine.rs
The term `AgentPool`, `MessagePool`, and `StatePools` are confusing. This PR renames the structs to `AgentBatchPool`, `MessageBatchPool`, and `StateBatchPool`.
- [Asana task](https://app.asana.com/0/1201893074552404/1201800853370429/f) _(internal)_
=> Rename `Pool` to `BatchPool`

packages/engine/Cargo.lock, packages/engine/Cargo.toml, packages/engine/bin/cli/Cargo.toml, packages/engine/bin/hash_engine/Cargo.toml, packages/engine/lib/execution/Cargo.toml, packages/engine/lib/nano/Cargo.toml, packages/engine/lib/orchestrator/Cargo.toml
Our current tokio version (`1.5.0`) does not implement `Error` on it's error types like `SendError`, in later versions this is fixed.
This also fixes [Data race when sending and receiving after closing a oneshot channel](https://rustsec.org/advisories/RUSTSEC-2021-0124).
=> Bump tokio to `1.18.2`

packages/engine/lib/error/src/report.rs
=> Rename `Report::generalise` to `generalize`

.github/workflows/rust.yml
As seen in https://github.com/hashintel/hash/pull/550 only a few crates are run when changing the toolchain. To avoid surprises, let the CI run **all** Rust jobs when the toolchain changes.
=> Always run all Rust jobs if toolchain changed

packages/engine/lib/execution/src/runner/javascript/mod.rs
In order to replace a few Rust behaviors with Javascript ones we need to get rid of an Arrow validation error when converting Javascript arrays to Rust.
An actual fix for this error would be to switch to Arrow2 but this would take quite some time.
As this validation error is likely a false-positive, we are going to ignore it for now.
- [Asana task](https://app.asana.com/0/1199548034582004/1201927209654757/f) _(internal)_
- [Move to Arrow2 Asana task](https://app.asana.com/0/1199548034582004/1201999214936733/f) _(internal)_
- Switch [`ArrayDataBuilder::build`](https://docs.rs/arrow/latest/arrow/array/struct.ArrayDataBuilder.html#method.build) with [`ArrayDataBuilder::build_unchecked`](https://docs.rs/arrow/latest/arrow/array/struct.ArrayDataBuilder.html#method.build_unchecked)
No
- [Move …
=> Skip Arrow validation for ArrayData

.github/workflows/rust.yml, packages/engine/lib/memory/src/shared_memory/segment.rs, packages/engine/lib/stateful/src/vec.rs
As introduced in #557, miri is running for `provider` and `error`. With only small adjustments to the tests, it could run almost everywhere and actually found a soundness hole.
- #557
=> Run miri for all lib-crates

packages/engine/lib/error/src/iter.rs, packages/engine/lib/error/src/lib.rs, packages/engine/lib/error/src/macros.rs, packages/engine/lib/error/src/report.rs
Re-add `Report::request_value`, which was removed while vendoring in the upstream provider RFC.
- [Asana task](https://app.asana.com/0/1201893074552404/1201481007343178/f) _(internal)_
- Rename `Requests` to `RequestRef` and add `RequestValue`
- Add `Report::request_value`
- Fix documentation
- Check documentation in CI to ensure doc-links are generated properly
=> Add support to request from `Report` by value

packages/hash/realtime/package.json, packages/hash/realtime/src/index.ts, yarn.lock
To make the frontend feel more responsive when updates are propagating.
Previously the worst-case delay between updated entity and frontend seeing the change was 5 seconds, we're reducing it to 150 ms.
The decision to land on `150ms` stems from the DB idling at around 16 transactions/second at ~5k block I/O hits compared to around 22 tps and ~7k block I/O hits at `100ms` along with the diminishing returns on lowering the polling interval further (that Nate pointed out in the internal document). The stress on the DB is still a lot higher than the ~650 block I/O and around 1 tps that a 5 second interval showed, we might need to increase this if the rest of the application feels sluggish when multiple users are interacting with the DB.
The realtime service now uses a custom version of …
=> Reduce realtime poll interval

packages/hash/frontend/src/blocks/page/BlockContextMenu/BlockLoaderInput.tsx, packages/hash/shared/src/ProsemirrorSchemaManager.ts, packages/hash/shared/src/blockMeta.ts
We have an input field to paste a URL to load a block from, for development purposes.
Re-loading a block is supposed to refresh its source from the URL, but an in-memory cache wasn't being busted when doing so.
This PR fixes that.
1.  Serve a block locally, load it in the app
2. Change something, re-load it via the URL input
3. Check the change has taken effect
=> Bust in-memory block cache when loading block from url

.prettierignore, packages/blocks/drawing-canvas/src/base.css, packages/blocks/github-pr-overview/src/index.css, packages/blocks/toggle-item/src/index.css, packages/hash/frontend/styles/globals.scss, sites/hashdev/styles/globals.css
When working on https://github.com/hashintel/hash/pull/576, I noticed that my new `app.scss` files was not fixed by Prettier. I added `!*.css` and `!*.scss` to `.prettierignore`, but it broke CI. This PR applies formatting to all pre-existing style files to reduce the diff in #576.
- CI
=> Apply Prettier to style files

CONTRIBUTING.md
This improves the `CONTRIBUTOR.md` guide at the root of our public monorepo in line with a set of suggestions collected internally.
* Expand common contribution processes
* Add instructions on how to find interesting PRs
* Add possible reasons for PR rejections
=> Expand contributor guide

packages/engine/Cargo.lock, packages/engine/lib/error/Cargo.toml, packages/engine/lib/error/src/future_ext.rs, packages/engine/lib/error/src/hook.rs, packages/engine/lib/error/src/lib.rs, packages/engine/lib/error/src/result_ext.rs
It's useful to add contextual information on futures without calling `map` but call `wrap_err` directly (without polling the future). This PR adds `FutureExt` to wrap a `Future` with contextual information.
- [Asana task](https://app.asana.com/0/0/1201908585432589) _(internal)_
- Adds the `FutureExt` Adaptor
- Slightly adjust documentation for `ResultExt`
The documentation were adjusted and is tested on CI
=> Add `FutureExt` adaptor trait

packages/engine/lib/error/src/hook.rs, packages/engine/lib/error/src/lib.rs
Instead of calling `debug_hook` or `display_hook`, it's better to call `Debug` or `Display` instead.
Makes `debug_hook` and `display_hook` internal
Docs are changed in #587
=> Make retrieving hooks internal

packages/engine/lib/error/src/frame.rs, packages/engine/lib/error/src/lib.rs, packages/engine/lib/error/src/macros.rs, packages/engine/lib/error/src/report.rs, packages/engine/lib/nano/src/client.rs, packages/engine/lib/nano/src/spmc.rs
Error macros are too complicated, passing `context: ` is not required. This PR adjusts this
- ~#590~
**Before**:
```rust
report!(context: std::io::Error { .. }, "Some error message");
```
**After** (Will be forbidden in a follow up PR as string literals will be removed from macros):
```rust
report!("Some error message").provide_context(std::io::Error { .. });
```
---
**Before**:
```rust
let report = report!(context: std::io::Error { .. });
assert!(report.contains::<std::io::Error>);
let report = report!(std::io::Error { .. });
assert!(report.contains::<std::io::Error>); // Fails
```
**After**:
```rust
let report = report!(std::io::Error { .. });
assert!(report.contains::<std::io::Error>); // Succeeds
```
=> Simplify error macros

packages/engine/bin/cli/src/main.rs, packages/engine/bin/hash_engine/src/main.rs, packages/engine/lib/error/src/error.rs, packages/engine/lib/error/src/hook.rs, packages/engine/lib/error/src/lib.rs, packages/engine/lib/error/src/macros.rs, packages/engine/lib/error/src/report.rs, packages/engine/lib/error/src/result_ext.rs, packages/engine/lib/nano/src/client.rs, packages/engine/lib/nano/src/server.rs, packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/lib/orchestrator/src/experiment_server.rs, packages/engine/lib/orchestrator/src/manifest.rs, packages/engine/lib/orchestrator/src/process/local.rs, packages/engine/tests/experiment/mod.rs
When creating `Report` from `Error`, the resulting type should be `Report<Error>` instead of `Report<()>`.
- #591 
- Change the return type when creating `Report` from `Error`: 148265979eeae52c6eab9c4f318bbfb4a9eb05b6
- Apply changes to `nano` crate: a58854cb552e2db1e00769ba3439d52292a4333c
- ~Add an extension trait for `Error` to convert it to `Report` by adding context~
The binary crates, the orchestrator, and the test suite is using `Report<()>`. It's out of scope to change this in this PR, thus this PR adds a workaround `ResultExt::generalize`, which needs to be removed before release. The method is marked as `#[doc(hidden)]`.
- Change the context type for the crates mentioned above and remove `ResultExt::generalize`
**Before:**
```rust
let report: Report<()> = report!(std::io::Error …
```
=> Change context type for errors to `Report<Error>`

packages/engine/bin/cli/src/main.rs, packages/engine/bin/hash_engine/src/main.rs, packages/engine/lib/error/src/lib.rs, packages/engine/lib/error/src/report.rs, packages/engine/lib/error/src/result.rs, packages/engine/lib/nano/src/client.rs, packages/engine/lib/nano/src/server.rs, packages/engine/lib/nano/src/spmc.rs, packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/lib/orchestrator/src/experiment_server.rs, packages/engine/lib/orchestrator/src/manifest.rs, packages/engine/lib/orchestrator/src/process/local.rs, packages/engine/tests/experiment/mod.rs
Currently, we can convert any `Result<T, E: Error>` to `Result<T, Report<E>>` by calling `wrap_err(_lazy)` or `provide_context(_lazy)` on it. This might be bad because this silently converts `E` to `Report<E>`, which may have performance implications for allocating heap memory to store `E` and may capture a backtrace or a span trace.
- [Asana task](https://app.asana.com/0/1199550852792314/1201586921294315) _(internal)_
- Remove `impl ResultExt for Result<T, E: Error>`
- Add an `IntoReport` trait and implement it for `Result<T, E: Into<Report<E>>>`
- Adjust tests
- Apply changes to hEngine
The docs were updated to reflect these changes. A major documentation overhaul is coming soon
- This adds a bit of boilerplate.
- Forbid creating `Report<()>`
The unit test suite from the error crate is …
=> Make conversion to `Report` explicit

packages/engine/Cargo.lock, packages/engine/Cargo.toml, packages/engine/lib/error/Cargo.toml, packages/engine/lib/error/src/frame.rs, packages/engine/lib/error/src/future.rs, packages/engine/lib/error/src/lib.rs, packages/engine/lib/error/src/macros.rs, packages/engine/lib/error/src/provider.rs, packages/engine/lib/error/src/report.rs, packages/engine/lib/error/src/result.rs, packages/engine/lib/nano/Cargo.toml, packages/engine/lib/nano/src/error.rs, packages/engine/lib/orchestrator/Cargo.toml, packages/engine/lib/orchestrator/src/error.rs, packages/engine/lib/provider/Cargo.toml, packages/engine/tests/experiment/error.rs
In order to publish the error crate, we want to avoid publishing the `provider` crate as it's soon to be expected to land on `core` soon.
- [Asana task](https://app.asana.com/0/1199548034582004/1202128277084777/f) _(internal)_
- #598
- Move provider API to `error` crate
- Apply fixes to usages
- Move `Demand` creation to it's own function (as in a review upstream)
- Apply clippy lints
Doc tests were updated
=> Move `provider` API to `error` crate

packages/engine/bin/cli/src/main.rs, packages/engine/bin/hash_engine/src/main.rs, packages/engine/lib/error/Cargo.toml, packages/engine/lib/error/examples/contextual_messages.rs, packages/engine/lib/error/examples/json_output.rs, packages/engine/lib/error/src/error.rs, packages/engine/lib/error/src/frame.rs, packages/engine/lib/error/src/future.rs, packages/engine/lib/error/src/iter.rs, packages/engine/lib/error/src/lib.rs, packages/engine/lib/error/src/macros.rs, packages/engine/lib/error/src/report.rs, packages/engine/lib/error/src/result.rs, packages/engine/lib/nano/src/client.rs, packages/engine/lib/nano/src/error.rs, packages/engine/lib/nano/src/server.rs, packages/engine/lib/nano/src/spmc.rs, packages/engine/lib/orchestrator/src/error.rs, packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/lib/orchestrator/src/experiment_server.rs, packages/engine/lib/orchestrator/src/manifest.rs, packages/engine/lib/orchestrator/src/process/local.rs, packages/engine/src/env.rs, packages/engine/tests/experiment/error.rs, packages/engine/tests/experiment/mod.rs
This makes the naming on methods more consistent and adds a method to attach a provider without changing the current context.
- [Asana task](https://app.asana.com/0/1201893074552404/1201481007343178/f) _(internal)_
- #599 
- Rename `wrap_err` to `attach_message`
- Rename `provide_context` to `change_context`
- This implies a new trait `Context: Display + Debug` and changes to the internal `Frame` representation
- Add `attach_provider`:
```rust
fn attach_provider<P: Provider + Display + Debug>(self, provider: P) -> Self;
```
- Make the provider API a nightly-only feature to make this crate to be used on stable as well. (We will switch to the upstream implementation of `Provider` as soon as it lands on `core`)
- Adjust `Report` so that `Report` will always have a `Context` associated …
=> Rename methods on error library and add `attach_provider`

packages/engine/lib/error/src/lib.rs, packages/engine/lib/error/src/macros.rs, packages/engine/lib/error/src/report.rs
It's reasonable to get the current context without the need of explicit downcasting.
- [Asana task](https://app.asana.com/0/1199548034582004/1201481007343178/f) _(internal)_
- Adds a function to return the current context
=> Add a function to return the latest context

packages/engine/bin/cli/src/main.rs, packages/engine/bin/hash_engine/src/main.rs, packages/engine/lib/error/src/report.rs, packages/engine/lib/error/src/result.rs
We used an anonymous Report as workaround, this needs to be removed
- [Asana task](https://app.asana.com/0/1201893074552404/1201481007343178/f) _(internal)_
- Removes calls to `generalize`
- Removes the `generalize` method
The documentation for this methods were already hidden
=> Remove usage of generalize

packages/libs/error-stack/Cargo.toml, packages/libs/error-stack/examples/contextual_messages.rs, packages/libs/error-stack/examples/parse_config.rs, packages/libs/error-stack/src/frame.rs, packages/libs/error-stack/src/lib.rs, packages/libs/error-stack/src/report.rs
Since we support getting the type of a `Frame`, this can be used for better printing
- [Asana task](https://app.asana.com/0/1201893074552404/1201481007343178/f) _(internal)_
- Improve `Debug` output for `Frame` and `Report`
- Add a new example to the crate-level docs, which shows the new output better
- An example was added, that shows these changes
Output of the following code:
```rust
let content = fs::read_to_string(path)
.report()
.change_context(ParseConfigError::new())
.attach(Suggestion("Use a file you can read next time!"))
.attach_lazy(|| format!("Could not read file {path:?}"))?;
```
**Before:**
```
Could not read file "config.json"
at examples/parse_config.rs:45:10
Caused by:
0: Use a file you can read next time!
at examples/parse_config.rs:44:10
1: Could not parse …
```
=> Improve `Debug` implementation for `Frame` and `Report`

packages/blocks/countdown/package.json, packages/blocks/countdown/src/app.tsx, packages/blocks/countdown/src/styles.scss
This fixes a styling error that comes up when the countdown block is rendered on block hub
Previous
Current
=> Countdown Block styling improvements

.github/labeler.yml
Adds the `A-libs` tag for libraries in _packages/libs_
=> Add `A-libs` tag to GitHub labeler

sites/hashdev/src/_pages/blog/4_announcing-error-stack.mdx
It seems that a link which is not contained by a paragraph does not get proper styling, which means the current 'View the crate on GitHub' link is not very visible.
As a temporary solution I've put it in a list item.
**Before**
**After**
=> Improve 'view the crate on GitHub' visibility

sites/hashdev/src/components/MdxPre.tsx
The base color for `<pre>` currently is `purple[600]`. To make this more readable, this is changed to `grey[40]`.
- [Slack](https://hashintel.slack.com/archives/C02NW18QGUR/p1654945808477039?thread_ts=1654853213.971799&cid=C02NW18QGUR) _(internal)_
**Before:**
**Now:**
=> Change `<pre>` base color in blog posts to `gray[40]`

packages/engine/Cargo.lock, packages/engine/Cargo.toml, packages/engine/bin/cli/Cargo.toml, packages/engine/bin/hash_engine/Cargo.toml, packages/engine/lib/nano/Cargo.toml, packages/engine/lib/orchestrator/Cargo.toml
`error-stack` is now published. Instead of using the local version, we switch to the upstream version.
=> Change to upstream error-stack

.github/workflows/semgrep.yml
This PR fixes Semgrep CI which started failing because of breaking changes upstream
```
=========== DEPRECATION WARNING ===========
Semgrep's audit mode setting will be removed by 2022 May.
Please update your CI configuration. Your CI script should run this command to ignore findings:
$ semgrep ci || true
We recommend setting up separate CI jobs for pull request and push events, so that you can ignore findings only on push events.
For questions or support, please reach out at https://r2c.dev/slack
=== Running: SEMGREP_AUDIT_ON="push" semgrep ci
run `semgrep login` before using `semgrep ci` or set `--config`
```
- [Asana task](https://app.asana.com/0/1202250835094702/1202435394337592/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1655136605181019) …
=> Update Semgrep yaml file to fix CI

sites/hashdev/src/_pages/blog/4_announcing-error-stack.mdx
Some readers of our announcement highlighted that our phrasing might have been a little confusing in that it didn't make clear that other libraries could capture arbitrary data. This PR attempts to rectify that through a correction.
I've tried to adjust the formatting of the note next to the comment just to help differentiate between the note and the footnote-like thing.
=> Clarifying arbitrary data attachment in error-stack Announcement

sites/hashdev/src/pages/blog/index.page.tsx
Fixes an alignment issue in the blog's homepage
- [Asana task](https://app.asana.com/0/1202250835094702/1202440221235951) _(internal)_
1.  Go to blog homepage
1.  Confirm the posts below the subscribe section look like the last attached image
Before
After
=> Fix alignment issue in blog homepage

packages/blocks/callout/package.json, packages/blocks/chart/package.json, packages/blocks/code/package.json, packages/blocks/countdown/package.json, packages/blocks/divider/package.json, packages/blocks/drawing/package.json, packages/blocks/embed/package.json, packages/blocks/github-pr-overview/package.json, packages/blocks/header/package.json, packages/blocks/image/package.json, packages/blocks/paragraph/package.json, packages/blocks/person/package.json, packages/blocks/stopwatch/package.json, packages/blocks/table/package.json, packages/blocks/timer/package.json, packages/blocks/toggle-item/package.json, packages/blocks/video/package.json, yarn.lock
Bumping all block-scripts to 0.0.11 to get smaller bundle sizes!
=> Bump block-scripts to 0.0.11

packages/libs/error-stack/src/report.rs
https://github.com/hashintel/hash/pull/697 introduced a compilation failure if `feature = "spantrace"` is set but *not* `feature = "std"`.
- Bug discovered by #694
=> Fix usage statement for `feature = "spantrace"`

packages/graph/rust-toolchain.toml
Sticks the Rust version to `nightly-2022-06-26`
=> Stick Rust version for the Graph crate

.github/scripts/rust/Makefile.toml, .github/scripts/rust/setup.py, .github/workflows/rust.yml, packages/engine/Makefile.toml, packages/engine/tests/integration.rs, packages/libs/error-stack/Makefile.toml
[cargo-make](https://sagiegurari.github.io/cargo-make/) is a task runner with Rust as it's primary target.
We chose to give `cargo-make` a try in order to simplify development.
Side effect: this hugely improves the number of jobs in CI, see the `checks` section below.
- [Asana task](https://app.asana.com/0/0/1202518779738147) _(internal)_
- Adds a base configuration to `.github/scripts/rust/Makefile.toml`
- Adds extending configurations to `packages/engine` and `packages/libs/error-stack`
- Change the CI to use `cargo make`
A summary of available commands can be printed by running `cargo make --list-all-steps`
The CI uses `cargo make` as well, so the setup is tested automatically
Please checkout the branch and run a variety of `cargo make` commands on these crates:
- …
=> Use `cargo make` in CI

sites/hashdev/src/_pages/blog/1_block-design.mdx, sites/hashdev/src/_pages/blog/5_build-blocks-in-any-language.mdx, sites/hashdev/src/_pages/blog/6_block-protocol-v02.mdx
This PR updates a few links to blockprotocol.org which changed as we migrated to Þ 0.2.
- [Asana task](https://app.asana.com/0/1202250835094702/1202440221033864/f) _(internal)_
- https://github.com/blockprotocol/blockprotocol/pull/411 (similar PR)
=> Update URLs to Þ docs and specs

.github/scripts/rust/Makefile.toml
Sometimes we want to pass additional parameters to `cargo make`, for example `cargo make test -- --ignored`.
=> Support additional parameters for `cargo make test/miri` (`main`)

packages/graph/hash_graph/Cargo.lock, packages/graph/hash_graph/Makefile.toml, packages/graph/hash_graph/bin/hash_graph/Cargo.toml, packages/graph/hash_graph/bin/hash_graph/src/args.rs, packages/graph/hash_graph/bin/hash_graph/src/main.rs, packages/graph/hash_graph/lib/graph/Cargo.toml, packages/graph/hash_graph/lib/graph/src/datastore/mod.rs, packages/graph/hash_graph/lib/graph/src/datastore/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/lib.rs
Currently, we have the database information hardcoded. This adds a `DatabaseConnectionInfo` struct, which is used for (a) provide information how to connect to a database and (b) can be used from the command line.
- [Asana task](https://app.asana.com/0/1201095311341924/1202510174412962) _(internal)_
- Add the `DatabaseConnectionInfo` struct and use it for connecting
- Change the tests to use `DatabaseConnectionInfo`
- Add `clap` to use `DatabaseConnectionInfo` in the command line
The struct is used in the tests
Run `cargo run -- --help` in `packages/graph/hash_graph`
It's possible to generate completions by running `cargo run -- --generate-completion zsh`:
=> Add `DatabaseConnectionInfo`

packages/engine/lib/execution/src/runner/python/setup.py
During some of the separation of crates work we improved the `setup.py` script which tries to dynamically find the most recent build target folder. It was searching for an artifact that only appears on Linux so this updates it to also find it on macOS.
1.  If you have a mac, checkout this branch and follow the README to setup Python.
=> Fix Python setup on macOS

packages/graph/LICENSE.md
The graph backend will initially be released under the AGPL. This PR adds the corresponding license file to the containing directory.
=> Specify `graph` license

.github/scripts/rust/Makefile.toml, .github/workflows/rust.yml, packages/engine/Makefile.toml, packages/libs/error-stack/Makefile.toml
Improves the Rust CI cache sizes and improves test behavior.
- [Asana task](https://app.asana.com/0/0/1202543415238115/f) _(internal)_
- #733
- Adjust Makefile.toml to make them more readable by re-using the same pattern
- Greatly enhance CI speed by shrinking the uploaded cache and caching on `dev/graph`
Caching cleanup report for hEngine:
```
Total:                                    1.14 GB => 494.93 MB
22 installed binaries:                             287.81 MB
Registry:                             846.93 MB => 206.78 MB
Registry index:                     247.78 MB => 111.88 MB
428 crate archives:                               94.91 MB
428 => 0 crate source checkouts:         504.24 MB => 0  B
Git db:                               864.99 KB => 338.44 KB
1 bare git repos: …
```
=> Optimize CI cache and runs for Rust

.github/labeler.yml
We currently only have `error-stack` in `libs` and `error-stack` is used often in issues/discussions/PRs.
=> Change `libs` label to `error-stack`

sites/hashdev/src/pages/blog/[...blogSlug].page.tsx, sites/hashdev/src/pages/blog/index.page.tsx, sites/hashdev/src/pages/blog/shared/get-photo.ts
Upgrading Next to 12.2 in #757 broke `yarn workspace @hashintel/hashdev build`. This PR fixes the build (see [logs on Vercel](https://vercel.com/hashintel/hashdev/QSFzEEV4KxMpHAdyy2ddHF4Fr8Yw)).
- [Asana task](https://app.asana.com/0/1202482456346915/1202552815181167/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1657210605084789) _(internal)_
Next 12.2 must have changed some tree-shaking nuances compared to 12.1. I believe that `const imageSize = promisify(legacyImageSize)` is now preventing tree-shaking, thus making `image-size` a part of the client bundle. Build crashes because it cannot resolve `fs` which `image-size` relies on. Moving `getImage` to a separate file re-enables tree-shaking because the function is only used in `getStaticProps`. This …
=> Move `getPhoto` to a separate file to fix hashdev build

packages/libs/error-stack/src/frame/erasable.rs, packages/libs/error-stack/src/frame/mod.rs, packages/libs/error-stack/src/frame/vtable.rs, packages/libs/error-stack/src/iter.rs
`miri` recently became smarter on detecting stacked borrows (basically references, which must not exist). This means, that no reference to `ErasableFrame<()>` must exist.
- Use `NonNull<...>` instead of `ManuallyDrop<Box<...>>`
=> Fix stacked borrows for new miri version

packages/hash/frontend/src/blocks/page/style.module.css
Words in text blocks were breaking at the end of each line. This was because we had set `word-break: break-all` on blocks.
- [Asana task](https://app.asana.com/0/1201095311341924/1202567646653901/f) _(internal)_
Changed `word-break` to `break-word` so that words don't break when they reach the end of the line. 
Also changed `white-space` to `pre-wrap` so that new lines can't be inserted by adding empty spaces, only by entering text or pressing Shift + Enter.
Type some text into various text blocks and check if words are breaking across lines.
=> prevent words from breaking across lines

packages/libs/error-stack/README.md
Even though we can specify the required rust version, it's not displayed on crates.io or libs.rs. This PR adds a badge to the readme to avoid confusion.
- https://github.com/hashintel/hash/issues/775
=> Add badge to `error-stack` readme for required version

packages/graph/hash_graph/lib/graph/src/types/schema/combinator.rs, packages/graph/hash_graph/lib/graph/src/types/schema/entity_type.rs, packages/graph/hash_graph/lib/graph/src/types/schema/mod.rs, packages/graph/hash_graph/lib/graph/src/types/schema/property_type.rs
Implements `EntityType` and it's schema validation
- [Asana task](https://app.asana.com/0/0/1202590061714999/f) _(internal)_
- Implement `EntityType`
- Fix an issue for `Optional`: If `json!({ ... })` is passed, it's parsed as `Empty`. With `deny_unknown_fields`, it will correctly be picked up. Denying unknown fields is good anyway.
Tests were added to check the schema. Test data were taken from the [Graph Type System RFC](https://github.com/blockprotocol/blockprotocol/blob/main/rfcs/text/0352-graph-type-system.md).
=> Implement `EntityType` and it's schema validation

packages/graph/hash_graph/lib/graph/src/types/schema/data_type.rs, packages/graph/hash_graph/lib/graph/src/types/schema/property_type.rs
`DataTypeReference` and `PropertyTypeReference` has a `reference` fields (`"$ref"`). We already renamed the function to return it to `uri()` in e3f794526f80cf6d7b96468ef09f29baa15d3c9a, this PR also renames the field
- #790
=> Rename `reference` field to `uri`

packages/graph/hash_graph/lib/graph/src/types/schema/combinator.rs, packages/graph/hash_graph/lib/graph/src/types/schema/data_type.rs, packages/graph/hash_graph/lib/graph/src/types/schema/entity_type.rs, packages/graph/hash_graph/lib/graph/src/types/schema/mod.rs, packages/graph/hash_graph/lib/graph/src/types/schema/object.rs, packages/graph/hash_graph/lib/graph/src/types/schema/property_type.rs
URIs in `"$ref"` must match the base URI by which it is referenced. This PR validates the URIs.
- [Asana task](https://app.asana.com/0/1201095311341924/1202598517577618/f) _(internal)_
- It isn't straight forward to implement this validation, because the versioned URI lives in `*TypeReference`s, but the key could be anywhere else. To work around this, this PR adds a module-scoped trait `ValidateUri` trait. This trait is implemented on the `*TypeReference`s are called when validating the wrapping structs.
- Implement `Object: Deserialize` by hand (using `ObjectRepr`) because the required trait bound
- Adjust tests to pass the validation
- Add a test to check the validation
=> Validate `BaseUri` keys to match the `VersionedUri`

packages/hash/frontend/src/blocks/page/ComponentView.tsx, packages/hash/frontend/src/components/BlockLoader/BlockLoader.tsx, packages/hash/shared/src/entityStore.ts
In #752 we started sending the `entityTypes` message (and prop) to blocks. This is [defined](https://blockprotocol.org/docs/spec/graph-service-specification#message-definitions) in the spec as:
> the entity type definitions for any entities provided to the block in other messages
One thing I left out of that PR is sending the entity type for the `blockEntity` to the block – it was only sending entity types for entities in the wider block graph (e.g. for any entities in `linkedEntities`).
This PR fixes that by also including the block entity's entity type in the `entityTypes` array.
- [Asana task](https://app.asana.com/0/1202482456346915/1202566631614518/f) _(internal)_
1.  Log out `graphProperties.entityTypes` in `RemoteBlock`
2. Check that the correct entity types are sent to any chosen …
=> Send entity type for root entity to blocks

packages/hash/api/src/lib/config.ts
In order to use our Vercel preview deployments with our deployed HASH API, we need them to use a cookie with a `*.hash.ai` domain. We've therefore updated Vercel deployments to be under `*.stage.hash.ai` rather than `-hashintel.vercel.app`
This PR adds `*.stage.hash.ai` to the list of permitted CORS origins.
- [Asana task](https://app.asana.com/0/1200211978612931/1202590106842629/f) _(internal)_
Because we are using a single API at the moment, there is no 'staging' environment for preview deployments to target, so every single preview deployment _and_ the "production" deployment (i.e. the thing built off `main`) are using the same API, and therefore operating on the same data, and the same session cookie will be used across all of them.
This is fine until we introduce preview builds for …
=> Add `*.stage.hash.ai` as valid CORS origin

packages/graph/hash_graph/.config/nextest.toml, packages/graph/hash_graph/Makefile.toml
Ensure, that `nextest` will always run with only one test thread for the Graph until we can run multiple tests at once
=> Run `nextest` with only one test thread

.github/actions/warm-up-repo/action.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/hash-backend-cd.yml, .github/workflows/labeler.yml, .github/workflows/sync-algolia-index.yml
While working on https://github.com/blockprotocol/blockprotocol/pull/434, I noticed ≈ 10-30 seconds of CI savings after caching `.next/cache` folder. This PR does the same for HASH frontend, which should speed up Playwright tests.
I’ve also bumped action versions given the opportunity, similar to what I’ve done in https://github.com/blockprotocol/blockprotocol/pull/431. New versions run on Node 16 instead of Node 12.
- https://github.com/actions/checkout/releases
- https://github.com/actions/labeler/releases
- https://github.com/actions/setup-node/releases
- [Asana task](https://app.asana.com/0/1202482456346918/1202605360401408/f) _(internal)_
Check CI output
`next build`
- without cache: [53.93s](https://github.com/hashintel/hash/runs/7343569230?check_suite_focus=true#step:9:56)
- with …
=> Cache frontend `.next` folder in CI

.github/actions/warm-up-repo/action.yml, .github/workflows/ci.yml
The goal of this PR is to leverage [`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD`](https://playwright.dev/docs/browsers#skip-browser-downloads), which can speed up most jobs in GitHub workflow.
- [Asana task](https://app.asana.com/0/1202482456346918/1202605360401430/f) _(internal)_
`yarn install` runs with `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=true`, unless `playwright-deps` input is provided. This skips unused browser downloads and thus speeds up the install process. 
- CI
=> Skip Playwright downloads by default to speed up CI

packages/graph/hash_graph/.config/nextest.toml, packages/graph/hash_graph/Makefile.toml, packages/graph/hash_graph/lib/graph/src/datastore/postgres/mod.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
We want to move all database related tests out of the unit tests, so it's possible to run the unit tests without having a database set up.
- [Asana task](https://app.asana.com/0/1200211978612931/1202597697815312) _(internal)_
- #814
- #815
- #816
- Move the `can_connect` test to the integration test suite
- Remove the test thread limit (it's not needed anymore)
=> Clean up Graph unit tests

packages/libs/error-stack/README.md
Basically, I added a workaround to the readme so that `error_stack` errors can be properly parsed by emacs.
More details can be found here: https://github.com/rust-lang/rust-mode/issues/452
Also here: #811 
This is a docs change, so I just need to know any other places this information should show up.
I think this fix is a bit hacky due to the fact it matches on two specific things to determine the start of the filename `at` and `',`.
It also overwrites a variable in `rust-mode` defined in [rust-compile.el](https://github.com/rust-lang/rust-mode/blob/master/rust-compile.el#L39-L41).
I don't think you want emacs in you CI pipeline.
Copy paste the code I provided in the readme into your `init.el` or wherever you place your user config.
Try seeing what an error_stack message looks like.
Do …
=> Add rust-mode workaround for `error-stack` errors

packages/hash/frontend/src/blocks/page/usePortals.tsx
While working on another ticket, I discovered our portals implementation can be simplified, relying on React 18's state batching behaviour. 
N/A
N/A
Currently, whenever part of the app calls `renderPortal`, we defer a task to the end of the tick in order to collect any further calls to `renderPortal` within this tick, before calling `setPortals` and triggering a re-render. This is to ensure sequential calls to render portal don't trigger sequential renders. Now, React batches calls to `setState` within a tick for us, so we don't need to do any schedule management. In fact, our current implementation takes *longer* than necessary, because we queue a task to call set state, which queues a state to re-render. We could have done this all in one task. But now React 18 batches, we don't need to …
=> Simplify portal implementation, improving performance

packages/graph/hash_graph/lib/graph/src/types/schema/array.rs, packages/graph/hash_graph/lib/graph/src/types/schema/combinator.rs, packages/graph/hash_graph/lib/graph/src/types/schema/entity_type.rs, packages/graph/hash_graph/lib/graph/src/types/schema/link.rs, packages/graph/hash_graph/lib/graph/src/types/schema/mod.rs, packages/graph/hash_graph/lib/graph/src/types/schema/property_type.rs, packages/graph/hash_graph/tests/test_data/entity_type/book_v1.json, packages/graph/hash_graph/tests/test_data/entity_type/book_v2.json, packages/graph/hash_graph/tests/test_data/entity_type/building.json, packages/graph/hash_graph/tests/test_data/entity_type/page.json, packages/graph/hash_graph/tests/test_data/entity_type/person.json, packages/graph/hash_graph/tests/test_data/entity_type/playlist.json
While we await completion of the the [Link Constraints RFC](https://github.com/blockprotocol/blockprotocol/pull/354) we're going to go ahead with a temporary design to unblock ourselves. Entity Types will constraint the destinations of their links by specifying a reference to an Entity Type, either inline, or inside the `"items"` when the links are an array.
**This is a temporary solution, we shall be updating it in the future**
I also unfortunately came across some issues with our combinator design so I've had to modify those files and polluted the PR with some drivebys.
- [Asana task](https://app.asana.com/0/1200211978612931/1202510175233302/f) _(internal)_
- Moves `ValueOrArray` to the property type module as it was only used there
- Creates a `ValueOrMaybeOrderedArray` enum to use …
=> Basic Constraints on Links in Entity Types

packages/graph/hash_graph/Cargo.lock, packages/graph/hash_graph/lib/graph/Cargo.toml, packages/graph/hash_graph/lib/graph/src/datastore/mod.rs, packages/graph/hash_graph/lib/graph/src/datastore/postgres/mod.rs, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
Previously, we only checked if a reference is valid, this PR also inserts it into the database
- [Asana task](https://app.asana.com/0/1200211978612931/1202597697815314/f) _(internal)_
- #821 
- Because `sqlx::Executor` is only implemented for references, change the implementation to use `Transaction` instead
- Use transactions to read the references
- Store the references in the database
We have quite a few code duplication here as we need the logic for different types.
- Add tests to the test suite, which passes invalid date: [Asana task](https://app.asana.com/0/1200211978612931/1202598311667201/f) (_internal_)
The integration test suite covers this
=> Insert type references into the database

packages/graph/hash_graph/lib/graph/src/datastore/postgres/mod.rs, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
We have some tables to track "references" inside the types (i.e. other types that are mentioned inside the type). We were being inconsistent with the naming scheme for these tables, this PR fixes it.
- The integration tests
1.  Follow the README and to start/recreate the DB and run the integration tests
=> Rename table for consistency

packages/blocks/callout/package.json, packages/blocks/code/package.json, packages/blocks/countdown/package.json, packages/blocks/drawing/package.json, packages/blocks/github-pr-overview/package.json, packages/blocks/header/package.json, packages/blocks/image/package.json, packages/blocks/person/package.json, packages/blocks/table/package.json, packages/blocks/timer/package.json, packages/blocks/video/package.json, packages/hash/frontend/package.json, yarn.lock
Update the version of `@blockprotocol/graph` used in the repo.
This new version removes some code that was importing a JSON file, because the deployment on Vercel is built in such a way that it (a) doesn't preserve the JSON file but (b) _does_ preserve an import statement referencing it, causing a crash on any page using blocks. 
We should fix this properly (tracked in [this internal task](https://app.asana.com/0/1202542409311090/1202614421149286/f)), but in the meantime this version gets pages on alpha.hash.ai working again.
- [Asana task](https://app.asana.com/0/1202482456346918/1202600431594490/f) _(internal)_
- Fix the problem properly so that we can restore the code removed from `@blockprotocol/graph` (which was checking if a callback attempted to be registered corresponded to an …
=> Use new @blockprotocol/graph version

packages/graph/hash_graph/lib/graph/src/datastore/mod.rs, packages/graph/hash_graph/lib/graph/src/datastore/postgres/mod.rs
By default, all statements are logged with the `Info` log level. This is very verbose, so this PR changes the logging level.
The `PgConnectOptions` is very poorly designed, so first, the options have to be created, then the logging can be set, then it can be passed to the pool creations. It's also not possible to pass a URI.
=> Change logging of queries to `Trace`

packages/hash/frontend/src/blocks/page/BlockContext.tsx, packages/hash/frontend/src/blocks/page/BlockContextMenu/BlockContextMenu.tsx, packages/hash/frontend/src/blocks/page/BlockContextMenu/BlockListMenuContent.tsx, packages/hash/frontend/src/blocks/page/BlockHandle.tsx, packages/hash/frontend/src/blocks/page/BlockPortals.tsx, packages/hash/frontend/src/blocks/page/BlockView.tsx, packages/hash/frontend/src/blocks/page/ComponentView.tsx, packages/hash/frontend/src/blocks/page/createSuggester/createSuggester.tsx, packages/hash/frontend/src/blocks/page/createSuggester/useFilteredBlocks.tsx, packages/hash/frontend/src/blocks/page/usePortals.tsx, packages/hash/frontend/src/components/ErrorBlock/ErrorBlock.tsx
When switching the type of a block from a basic text-type (paragraph, header, callout) to a non text-type block (table for example), the text is gone. This PR removes the unsupported block types from the swap list, until there is a proper data-mapping implementation.
- [Asana task](https://app.asana.com/0/1200211978612931/1202500568584727/f) _(internal)_
- Swap type menu is only shown if block is of type Paragraph, Header or Callout or if the fallback error block is displayed.
- Swap type menu only includes the Paragraph, Header or Callout types.
- 
Retaining the text property in the code block would need to be hardcoded, as it doesn't have a `text` property. So we're skipping this for now.
1.  Create a text block and insert text
1.  Test …
=> Remove unsupported block types from swap list

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/types/mod.rs
Provide a REST endpoint for CRU operations on link types
- [Asana task](https://app.asana.com/0/1202542409311090/1202622269244648/f) _(internal)_
- Adds the REST Endpoint to the REST API
- Add the endpoint for entity types (since #827 link types are required for inserting entity types, thus this was done first) (direct follow-up)
- Add very basic tests (like an HTTP request file) to test the REST API (direct follow-up)
Currently none, tested locally.
Run the binary and make the following requests:
Insertions:
```http
POST localhost:3000/link-type
Accept: application/json
{
"account_id": "00000000-0000-0000-0000-000000000000",
"schema": {
"kind": "linkType",
"$id": "https://blockprotocol.org/@alice/types/link-type/friend-of/v/1",
"title": "Friend Of", …
```
=> Add REST endpoint for link types

packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/types/mod.rs
Provide a REST endpoint for CRU operations on entity types
- [Asana task](https://app.asana.com/0/1202542409311090/1202622269244647/f) _(internal)_
- Adds the Endpoint to the REST API
- Add very basic tests (like an HTTP request file) to test the REST API (direct follow-up)
Currently none, tested locally.
Run the binary and make the following requests (requires some data types, property types, and link types to be inserted into the database before):
Insertions:
```http
POST localhost:3000/entity-type
Accept: application/json
{
"account_id": "00000000-0000-0000-0000-000000000000",
"schema": {
"kind": "entityType",
"$id": "https://blockprotocol.org/@alice/types/entity-type/person/v/1",
"type": "object",
"title": "Person",
"properties": { …
```
=> Add REST endpoint for entity types

packages/graph/hash_graph/Makefile.toml, packages/graph/hash_graph/README.md
Currently, the tests for the REST endpoints are manual tests, this enables them in the CI
- [Asana task](https://app.asana.com/0/1201095311341924/1202643529167462/f) _(internal)_
Modify the `Makefile.toml` to run the binary, then run the tests
This is using a bash script to run the tests, which is working but not a nice solution. This will be revisited once we have e2e tests in place
=> Run REST endpoint tests in CI

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/tests/rest-test.http
The `VersionId` is supposed to be an implementation detail. Also, it's not possible to read the id for a type when it was already created.
- [Asana task](https://app.asana.com/0/1201095311341924/1202642946839413) _(internal)_
- Add a public conversion method to get a version id by URI
- Use URIs in REST GET endpoints
- drive-by: Add error-logging output when REST methods are failing
- Due to the way SQLx implements their `Executor` trait, the functionality for getting a URI by id needs two entrypoints, but can rely on the same internal methods. This will be solved by a follow-up task
The test-requests were adjusted to use URL-encoded URIs instead
- Install dependencies:
```sh
cargo make yarn
```
- Deploy the database and populate it:
```sh
cargo make deployment-up
cargo make recreate-db …
```
=> Use URIs in REST endpoints rather the the database id

packages/engine/lib/execution/src/runner/python/requirements.txt
We have scipy in the Python venv in cloud but were missing it in hEngine due to removing Pyodide. I've added quite an old version to match the one we had, as we haven't been updating the Python dependencies yet (but should soon)
=> Adding missing Python dependency

packages/graph/hash_graph/bin/hash_graph/src/main.rs, packages/graph/hash_graph/lib/graph/src/api/rest/api_resource.rs, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs
We are going to split the pooling and the connection logic of the `Store`, this implies, that the `Store` itself is not necessarily `Clone` anymore. `Send` + `Sync` + `'static` are not necessarily required for a store.
- [Asana task](https://app.asana.com/0/1202538466812818/1202660056731614/f) _(internal)_
- Remove the `Clone` bound by using `Arc` instead
- Remove `Send` + `Sync` + `'static` bounds by moving them to the REST API. `Send` + `'static` are required to use the `Store` inside of a router, the `Sync` bound is required because `Arc<T>` implements `Send` when `T: Send + Sync`
- Drive-by: Reduce boilerplate in REST API methods
Split the pooling logic from the connection logic
- REST API tests
=> Remove `Store` bounds

.github/workflows/rust.yml
Currently, we always use the latest version for tools in CI. To avoid breaking changes and speed up CI runs in the case the binary is not prebuilt yet, we want to pin the version of the used tools.
=> Pin `cargo quickinstall` versions

.github/workflows/rust.yml
Currently, we always use the latest version for tools in CI. To avoid breaking changes and speed up CI runs in the case the binary is not prebuilt yet, we want to pin the version of the used tools.
=> Pin `cargo quickinstall` versions (dev/graph)

sites/hashai/resources/glossary/entities.mdx
The `<>` in the copy for the Entities glossary entry was being interpreted as an opening tag for an MDX component, causing a crash when there was no corresponding closing tag.
This PR escapes the `<`s.
=> Escape less-thans in entities glossary mdx

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs
Changes the `Store` signature to only take a shared reference, as a mutable reference is not needed anymore using `tokio-postgres`
- [Asana task](https://app.asana.com/0/1201095311341924/1202652453922927/f) _(internal)_
- #851 
- #855
=> Change `get` methods to take a shared reference

.github/scripts/rust/Makefile.toml
in #853 the versions were pinned for `cargo-quickinstall`, so the CI will run properly. Running the tests locally does not work if `cargo-nextest` is not installed, so this PR also pins the versions in the makefile.
=> Pin cargo tool versions for `cargo make`

.github/scripts/rust/Makefile.toml, packages/graph/hash_graph/Makefile.toml
Same PR as #866, but for the `dev/graph` branch
in #854 the versions were pinned for `cargo-quickinstall`, so the CI will run properly. Running the tests locally does not work if `cargo-nextest` is not installed, so this PR also pins the versions in the makefile.
=> Pin cargo tool versions for `cargo make` (dev/graph)

packages/libs/error-stack/src/report.rs
[#98912 ](https://github.com/rust-lang/rust/pull/98912) in the newest nightly changed how the generics for `core::any::request_ref` are. Instead of specifying the value requested via the generic, we explicitly annotate the filter method. Circumventing the issue.
* [#98912 ](https://github.com/rust-lang/rust/pull/98912)
* https://github.com/rust-lang/rust/issues/96024
* #873
changes `core::any::request_ref<T, _>().filter(|x| ...)` to `core::any::request_ref().filter(|x: &&T| ...)`
Nope.
Does it compile on the old nightly and the new nightly?
=> Fix generic arguments when requesting from a `Provider`

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/read.rs, packages/graph/hash_graph/tests/integration/postgres/data_type.rs, packages/graph/hash_graph/tests/integration/postgres/entity_type.rs, packages/graph/hash_graph/tests/integration/postgres/link_type.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/integration/postgres/property_type.rs
The public-facing interface is not using `VersionId` but `VersionedUri`. This adds the read-method for the store to support reading by URI directly
- [Asana task](https://app.asana.com/0/1202538466812818/1202675758696580/f) _(internal)_
- #864
- Add `Read<VersionedUri, T> for PostgresStore`
- Use `VersionedUri` in tests and the REST API
=> Implement a store-reader to read types from URIs directly

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/ontology/types/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/types/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/types/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/types/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/types/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/version_id.rs, packages/graph/hash_graph/tests/integration/postgres/data_type.rs, packages/graph/hash_graph/tests/integration/postgres/entity_type.rs, packages/graph/hash_graph/tests/integration/postgres/link_type.rs, packages/graph/hash_graph/tests/integration/postgres/links.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/integration/postgres/property_type.rs, packages/graph/hash_graph/tests/rest-test.http
The `VersionId` was never designed to be exposed, this removes all references to the `VersionId` outside of the `postgres` module
- [Asana task](https://app.asana.com/0/0/1202675758696584/f) _(internal)_
- Don't return `Persisted` from the REST API
- Don't return `Persisted` from the `Store` anymore (but create/update it by reference)
- Move `VersionId` to `store::postgres`
- Integration tests
- REST endpoint tests
=> Make `VersionId` an implementation detail

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/tests/rest-test.http
Currently, all endpoints are singular. Normally, REST endpoints are plural, to play well with getting multiple things as well, e.g.
- `/api/data-types/` to get all data-types
- `/api/data-types/{data-type-uri}` to get a specific data-type
- [Asana task](https://app.asana.com/0/1202538466812818/1202682556665557/f) _(internal)_
- Make the endpoints plural
- Adjust the tests
The OpenAPI attributes also has been adjusted
- Implement read-many endpoints
The REST endpoint tests were adjusted
=> Rename REST endpoints to plural names

packages/blocks/shuffle/package.json
The Shuffle block workspace name does not follow the normal pattern and the examples in the block's `package.json` are incorrect.
- Changed workspace name from `@hashintel/shuffle` to `@hashintel/block-shuffle`
- Changed examples from: 
```   
"examples": [
[
"Alice",
"Bob",
"Charlie"
]
]
```
to:
```
"examples": [
{
"items": [
"Alice",
"Bob",
"Charlie"
]
}
],
```
=> Shuffle block improvements

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/link/read.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
With the recent changes, it's now possible to generalize the GET methods for the REST endpoints to avoid code duplication
- [Asana task](https://app.asana.com/0/1201095311341924/1202668708596541/f) _(internal)_
- Generalize the GET method bodides
- Drive-by: Make `T` for links in `Read` trait singular (for consistency)
=> Generalize GET method bodies

packages/graph/hash_graph/Cargo.lock, packages/graph/hash_graph/lib/graph/Cargo.toml, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/store/crud.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/tests/rest-test.http
Enhances the API to support getting all available data/property/link/entity-types
- #878 
- [Asana task](https://app.asana.com/0/1202538466812818/1202682556665567/f) _(internal)_
- Implement the logic in the backend: dac951c6d032628e80260048ad56182d97f9bcad
- Make the logic usable in the REST endpoint: 75761a64575025db1a3531ddc2e8f93ad3852891
- Add methods to the REST endpoints: a027b3bdc0d4deff16022ebb90b9c0bebadb0fe6
- Add tests for the newly added functionality: 419312004eb61220188ef512999e2b2f0690bb29
The OpenAPI is generated from the REST endpoints
- Make the types filterable by `AccountId`
The newly added functions has been added to the REST endpoint test
=> Implement GET for all stored ontology types

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/entity/read.rs, packages/graph/hash_graph/tests/rest-test.http
Extends the API to support getting all available entities
- [Asana task](https://app.asana.com/0/1202621375435411/1202682556665582/f) _(internal)_
- Adds a REST endpoint for getting all entities, and the required backend code
- Driveby on some incorrect status codes on other endpoints
The OpenAPI is generated from the REST endpoints
- Make the entities filterable by `AccountId`
- Make the entities filterable by a given Entity Type's Base URI
The newly added functions has been added to the REST endpoint test
=> Implement GET all entities

packages/hash/api/src/collab/save.ts, packages/hash/frontend/src/blocks/page/BlockContextMenu/BlockContextMenu.tsx, packages/hash/frontend/src/blocks/page/BlockContextMenu/BlockListMenuContent.tsx, packages/hash/frontend/src/blocks/page/BlockContextMenu/LoadEntityMenuContent.tsx, packages/hash/frontend/src/blocks/page/BlockHandle.tsx, packages/hash/frontend/src/blocks/page/BlockView.tsx, packages/hash/frontend/src/components/hooks/useAccountEntities.ts, packages/hash/integration/src/mockData/index.ts, packages/hash/shared/src/ProsemirrorManager.ts, packages/hash/shared/src/entityStorePlugin.ts
We have a feature whereby users can choose an entity to load into a block, rather than relying on the block itself being able to generate a new entity, and swap existing entities for new ones. This previously:
- only allowed users to swap to another _block_ entity of an identical type (i.e. a block that referenced the same `componentId`, e.g. `blockprotocol.org/.../table` – a "block entity" in this context is the entity that wraps a block, and references the child / data entity and the component that loads it)
- was behind a feature flag
This PR is part of the groundwork for being able to choose any entity to load into a block, even if isn't compatible, by:
a. allowing users to pick from any data entity to load into a block, i.e. not the _block_entity, but any child / data entity
b. …
=> Load any child entity into a block + remove feature flag

.github/workflows/rust.yml
When determining the toolchain to use, outputting fails. This was only a bug in displaying the toolchain, the toolchain was picked up correctly.
Thanks for @indietyp for reporting!
- https://github.com/hashintel/hash/issues/897#issuecomment-1207476945
=> Fix output of toolchain in CI

packages/engine/Cargo.lock, packages/engine/Cargo.toml, packages/engine/bin/cli/Cargo.toml, packages/engine/bin/cli/src/main.rs, packages/engine/bin/hash_engine/Cargo.toml, packages/engine/bin/hash_engine/src/main.rs, packages/engine/lib/experiment-control/Cargo.toml, packages/engine/lib/experiment-structure/Cargo.toml, packages/engine/lib/experiment-structure/src/config/experiment.rs, packages/engine/lib/experiment-structure/src/config/package.rs, packages/engine/lib/experiment-structure/src/experiment/plan.rs, packages/engine/lib/experiment-structure/src/manifest.rs, packages/engine/lib/nano/Cargo.toml, packages/engine/lib/nano/src/client.rs, packages/engine/lib/nano/src/server.rs, packages/engine/lib/orchestrator/Cargo.toml, packages/engine/lib/orchestrator/src/experiment.rs, packages/engine/lib/orchestrator/src/experiment_server.rs, packages/engine/lib/orchestrator/src/process/local.rs, packages/engine/tests/experiment/mod.rs, packages/libs/error-stack/Cargo.toml, packages/libs/error-stack/examples/exit_code.rs, packages/libs/error-stack/tests/test_conversion.rs
In order to bump the toolchain for `hEngine`, it's required to use the latest `error-stack` version available, as `std::error::Error::backtrace` were removed.
Our CI is currently limited to only the same nightly toolchains for different projects, this results in problems with a breaking changes on a nightly feature in `std`. It's not possible to simply bump the toolchain as hEngine would then use an old version of `error-stack` but on a compiler which is not working for `error-stack`. It's also not possible to specify the link to `error-stack` by a git path because it does not yet exist upstream. So this is a temporary fix to use the correct error-stack version until the toolchain was bumped. Afterward, it will be replaced by a git-link instead of a path to avoid breaking hEngine without …
=> Use `error-stack` by path

.github/scripts/rust/Makefile.toml, .github/workflows/rust.yml, packages/libs/error-stack/Cargo.toml, packages/libs/error-stack/Makefile.toml
error-stack recently gained new capabilities (#794, #793, #747), combined with the newly introduced extensive test suite, which has been implemented in #777, results in multiple new `feature` flags, which we need to test against. These circumstances have led to testing times up to ~5h, which - with new features - will only get exponentially longer.
This PR tries to find a compromise by introducing feature groups of features that are unlikely to influence each other. Discussion #877 outlines the worst-case math and potential improvements this change adds.
> **Note:** This change adds a new environmental flag, `CARGO_TEST_HACK_GROUPS`, which we append to the actual `cargo-hack` command. For the complete pre-release test, needs to set `CARGO_TEST_HACK_GROUPS = ""`, the env_script will pick …
=> Use test groups for testing `error-stack`

packages/hash/frontend/src/blocks/page/BlockHandle.tsx, packages/hash/frontend/src/blocks/page/BlockView.tsx, packages/hash/frontend/src/blocks/page/style.module.css
- Hides the `BlockHandle` by default, and display it only when the mouse cursor hovers over a block.
- Changes a spelling to American English within a comment
[Asana task](https://app.asana.com/0/1200211978612931/1202700524579036/f) (internal)
1.  Try hovering on a Block inside a page
1.  Confirm that `BlockHandle` is visible on hover.
https://user-images.githubusercontent.com/39553853/183638037-1045618b-1127-412b-ab4b-c0ea40881a13.mov
=> Show block handles only on mouse hover

packages/graph/hash_graph/bin/hash_graph/src/main.rs, packages/graph/hash_graph/tests/rest-test.http
The primitive data types are effectively constants that should be available in any Block Protocol compliant system. Later on we expect these to be accessible through blockprotocol.org and resolvable through their URIs. In the absence of that infrastructure, this is a temporary solution which seeds the DB with them when the graph service starts.
- [Asana task](https://app.asana.com/0/1201095311341924/1202775849963303/f) _(internal)_
- Collects our temporary solutions in one function so we can track how many we have and delete them over time
- Adds a seeding step that inserts the primitive data types
- Updates the REST API tests to account for these changes
- No
- The REST API tests
1.  Follow the README instructions to run tests as normal, or check the CI
=> Seed primitive data types at the start of execution

packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/hash/api/src/model/index.ts, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/api/src/model/ontology/data-type.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/link-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts, packages/hash/api/src/model/util.ts, packages/hash/integration/src/tests/model/knowledge/entity.model.test.ts, packages/hash/integration/src/tests/model/ontology/data-type.model.test.ts, packages/hash/integration/src/tests/model/ontology/entity-type.model.test.ts, packages/hash/integration/src/tests/model/ontology/link-type.model.test.ts, packages/hash/integration/src/tests/model/ontology/property-type.model.test.ts
This PR adds the `EntityModel` class for creating, getting and updating `Entities`. 
- [Asana task](https://app.asana.com/0/1200211978612931/1202731581883433/f) _(internal)_
- Changes PersistedEntity in the rust API to not flatten the `identifier` as Utoipa doesn't support this
- Adds a new `EntityModel` class under `/api/src/models/knowledge/` directory
- We've added explicit NIL UUID references instead of relying on passed-in `accountId`s for the existing model classes. This needs to change and will allow us to refer to `created_by` workspace accounts in the future.
- Implementing user entities [Asana task](https://app.asana.com/0/1200211978612931/1202693393444197/f) (_internal_)
- `packages/hash/integration/src/tests/model/knowledge/entity.model.test.ts`
1.  Checkout the branch / view …
=> Add `EntityModel` class with Graph API CRU operations

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/tests/integration/postgres/data_type.rs, packages/graph/hash_graph/tests/integration/postgres/entity_type.rs, packages/graph/hash_graph/tests/integration/postgres/link_type.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/integration/postgres/property_type.rs, packages/graph/hash_graph/tests/rest-test.http, packages/hash/api/src/model/ontology/data-type.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/link-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts
Similar to #905, this returns metadata from ontology types
- [Asana task](https://app.asana.com/0/1201095311341924/1202770062090893/f) _(internal)_
- #909 
- Add `PersistedOntologyIdentifier` containing a `created_by` field
- Add `PersistedOntologyType<T>` containing the identifier from above and `T`
- Add aliases for `PersistedOntologType<DataType>`, `PersistedOntologType<PropertyType>`, etc.
- Change return type for creating/updating to `PersistedOntologyIdentifier`
- Change return type for reading to `PersistedOntologyType`
=> Return metadata with ontology types

packages/hash/frontend/sentry.properties
Renames the Sentry project for the HASH frontend from `hashdev-frontend` to `hash-frontend`. 
`hashdev` was an early/inaccurate name for the project which is now confusing since we also have a hash.dev website.
The one reference to the project name is in `sentry.properties`, which sets the options for the Sentry CLI, which is used to upload source maps to Sentry. The destination for errors logged at runtime is set by the DSN variable, which does not change.
**I have renamed the project in Sentry, because otherwise this branch will not build. We need to merge this to make other branches build again, since they will now contain a project name that doesn't exist.**
- [Asana task](https://app.asana.com/0/1200211978612931/1202579651285689/f) _(internal)_
=> Rename sentry project

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/hash/api/src/model/ontology/data-type.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/link-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts, packages/hash/frontend/sentry.properties
As a follow up to #912 we missed updating the GET operations' OpenAPI annotations to return `Persisted*Type` instead of the raw schemas
- Follow up to #912 
- Changed from `VAR_*_TYPE` to `Persisted*Type` in GET operations on the rust side
- Update model classes to make use of the new structures
- Ontology integration tests
1.  Recreate and migrate DB and run backend
- From the `packages/graph/hash_graph/bin/hash_graph` path run:
- `cargo make recreate-db && cargo make migrate-up`
- `cargo run`
1.  In another terminal, from the `packages/hash/integration` path run `yarn jest "ontology/*"`
1.  Confirm all tests pass
=> Fix OpenAPI spec type mismatch

packages/graph/.gitattributes
The `api.ts` file is autogenerated. This hides the file from diffs and excluded it from stats.
=> Add hint for autogenerated files

.github/scripts/rust/setup.py, packages/libs/error-stack/CHANGELOG.md, packages/libs/error-stack/README.md
We have agreed on bumping the Minimum Supported Rust Version to 1.63 as this will reduce the maintenance of multiple branches in the upcoming hook logic
- Closes #930 
- #794 
- #943
=> Bump the Minimal Supported Rust Version to 1.63

.github/scripts/rust/Makefile.toml, .github/workflows/rust.yml, packages/libs/error-stack/Cargo.toml, packages/libs/error-stack/Makefile.toml
This implements the same optimizations outlined in #877, which have been applied in #892 for tests. We forgot Clippy in the initial PR, which has been applied in this PR after being pointed out by https://github.com/hashintel/hash/pull/794#discussion_r949698353.
* Discussion about time complexity and motivation: #877 
* Initial PR: #892 
`cargo make clippy` will only run for a fraction of feature sets on PRs, but with all permutations on release.
Not user-facing, just CI.
=> Add feature groups for linting

packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/graphql/resolvers/ontology/data-type.ts, packages/hash/api/src/graphql/resolvers/ontology/link-type.ts, packages/hash/api/src/graphql/resolvers/ontology/property-type.ts, packages/hash/api/src/graphql/typeDefs/ontology/link-type.typedef.ts, packages/hash/api/src/graphql/typeDefs/ontology/property-type.typedef.ts
This PR adds authentication middleware to the recently added type resolvers in the GQL API.
Additionally it makes the `accountId` parameter for the `createLinkType`/`createPropertyType` methods optional, defaulting to the `accountId` of the currently authenticated user.
- [Asana task](https://app.asana.com/0/1202621375435417/1202829711398832/f) _(internal)_
No.
None.
1. Checkout the branch / view the deployment
2. Run the hash workspace using `yarn external-services up` and `yarn dev`
3. Go to the GraphQL playground at `http://localhost:5001/graphql` and try to call a type query/mutation such as `getAllLatestDataTypes` (you can use the query attached below). You should get an authentication error.
4. Login to the hash workspace at `http://localhost:3000/login`
5. Re-run the mutation in …
=> Authenticate type GQL resolvers

packages/libs/error-stack/README.md, packages/libs/error-stack/rust-toolchain.toml, packages/libs/error-stack/src/lib.rs
With `error-stack` v0.1 our MSRV is `1.61`, but with v0.2 it will be bumped to `1.63`. When looking at the [documentation](https://docs.rs/error-stack/latest/error_stack) it's not possible to determine the MSRV for the current version. Looking at the repository is misleading because it only captures the most recent MSRV.
[Asana Task](https://app.asana.com/0/1200211978612931/1202829737531477/f) (_internal_)
- Extend MSRV badge by the current nightly version we use for testing
- Add badges to crate-level documentation
=> Add badges to crate documentation

packages/libs/error-stack/src/context.rs, packages/libs/error-stack/src/ext/mod.rs, packages/libs/error-stack/src/fmt/hook.rs, packages/libs/error-stack/src/fmt/mod.rs, packages/libs/error-stack/src/lib.rs, packages/libs/error-stack/src/macros.rs
This is a continuation of https://github.com/hashintel/hash/pull/794#discussion_r950169256, which enables the `unreachable_pub` lint and disables the [`redundant_pub_crate`](https://rust-lang.github.io/rust-clippy/master/index.html#redundant_pub_crate) clippy lint.
* Initial discussion: https://github.com/hashintel/hash/pull/794#discussion_r950169256
This changes which lints we make use of for visibility modifiers in `error-stack`.
No
This is a bit weird. As we export those, this could very well be a false positive.
`cargo make lint`
=> Change `error-stack` `pub(crate)` lints

packages/blocks/callout/README.md, packages/blocks/embed/README.md, packages/blocks/header/README.md, packages/blocks/paragraph/README.md, packages/hash/frontend/src/blocks/page/createEditorView.ts
There's one place in the HASH code where we find the paragraph block by the `name` property in its metadata returned by the API, which at the moment is its `name` in its original source location, i.e. its yarn workspace name (`@hashintel/block-code`).
[This PR](https://github.com/blockprotocol/blockprotocol/pull/509) in `blockprotocol` is setting `name` to be a block's `name` in the Block Protocol hub, not whatever was its `name` in its original package.json, which might be completely unrelated.
We were previously matching the paragraph block based on its name in the original package.json, we will no longer be what is exposed via the BP API. This PR updates it to something that will remain consistent (the `componentId`).
- https://github.com/blockprotocol/blockprotocol/pull/509
=> Identify paragraph block by its componentId, not name

packages/graph/Makefile.toml, packages/graph/hash_graph/Cargo.lock, packages/graph/hash_graph/lib/graph/Cargo.toml, packages/graph/hash_graph/lib/graph/src/store/error.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs
#909 only covered ontology types with a specific URI + version or all latest types, but no other combinations. This PR adds a more general approach on filtering.
- [Asana task](https://app.asana.com/0/1200211978612931/1202510174412974/f) _(internal)_
- Change the read interface to the database to return all types or only the latest version
- Apply filters in Rust (optimizations can be added later)  
This is an internal-only change
=> Support filtering for URIs and versions on ontology types

.github/workflows/rust.yml, packages/libs/error-stack/Cargo.toml, packages/libs/error-stack/macros/Cargo.toml
With #982 we attempted to publish `error-stack-crates` but it failed because instead of `refs/head/main` we specified `ref/head/main`. Also, this fixes an issue in `Cargo.toml`
- #982
- Fix publish job CI
- Only run tests on pull requests, not on push. There is no point in testing it after the tests have passed again. First, it will take quite a while (about 30 minutes), and secondly, it might fail spuriously (we didn't have that issue yet but who knows...)
- Fix Cargo.toml
- Temporarily (will be reverted in follow-up):
- Bump version to test it on CI (needs to be merged)
- Do a dry-run on push to ensure it's working without publishing the version
- Revert the mentioned changes and publish the crate
=> Fix refs in publish job and prepare `error-stack-macros` release

packages/hash/README.md, packages/hash/design-system/src/fontawesome-icon.tsx, packages/hash/frontend/package.json, packages/hash/frontend/src/blocks/page/PageBlock.tsx, packages/hash/frontend/src/components/EmojiPicker/EmojiPicker.tsx, packages/hash/frontend/src/components/PageIcon.tsx, packages/hash/frontend/src/components/PageIconButton.tsx, packages/hash/frontend/src/pages/[account-slug]/[page-slug].page.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page.tsx, packages/hash/frontend/src/pages/shared/top-context-bar.tsx, packages/hash/frontend/src/shared/layout/layout-with-sidebar/account-page-list.tsx, packages/hash/frontend/src/shared/layout/layout-with-sidebar/account-page-list/page-tree-item.tsx
This addresses a few things that needed tidying up. Read below for more information. 
**Asana Links**: (_internal_)
- [Add instructions on enabling debug mode to HASH project README](https://app.asana.com/0/1200211978612931/1202796290628210/f)
- [Comment out non-functional context bar buttons](https://app.asana.com/0/1200211978612931/1202819146709794/f)
- [Sidebar Pages should have text-overflow](https://app.asana.com/0/1201095311341924/1202847510363966)
- [Error crashing blocks – Failed to execute 'removeChild' on 'Node'](https://app.asana.com/0/1201095311341924/1202838927575313/f)
- [TreeView changing between controlled/not controlled warning](https://app.asana.com/0/1201095311341924/1202849277774018/f)
- [validateDOMNesting(...): <button> cannot appear as a descendant of …
=> Assorted tidy up 

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/query/ontology.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
This is the initial PR to support basic structural queries. "basic" in this context means, that the queries do not have a syntax, but only an AST. Also, only a small set of query parameters are supported.
- [Asana task for data types](https://app.asana.com/0/0/1202884883200952/f) _(internal)_
- [Asana task for property types](https://app.asana.com/0/0/1202884883200953/f) _(internal)_
- Add a `Literal` enumeration, which is similar to `serde_json::Value`. `Value` is not used as we require some special handling for e.g. versioning and subsets. 
- Add a `Resolve` trait, which resolves a struct into a `Literal`
- Add a `PostgresContext` trait used as the resolver context. Currently, this is implemented by the `PostgresStore` itself, but in the future it will be used to store query …
=> Introduce structural queries

packages/libs/error-stack/tests/test_compatibility.rs
`anyhow` was released today in a new version that allows `Backtrace` to be provided using `Error::provide`. The test assumed that `anyhow` does not currently support retrieving backtraces, but this has been fixed upstream.
- https://github.com/dtolnay/anyhow/pull/266
=> Fix `anyhow` test to support backtraces

packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/resolve.rs
A few small improvements when dealing with streams
- Change `PostgresContext` to return `impl Stream<Item = Result<Record<T>, QueryObject>>` instead of `RowStream`. For this, `account_id` was added to `Record`.
- Use stream combinators for building `Literal::List` instead of constructing the `Vec` by hand
- #1016
=> Improve usages of streams by using `StreamExt`

packages/graph/hash_graph/Cargo.lock, packages/graph/hash_graph/bin/hash_graph/Cargo.toml, packages/graph/hash_graph/lib/graph/Cargo.toml, packages/hash/api/package.json, packages/hash/frontend/package.json, packages/hash/integration/package.json, yarn.lock
The latest changes are required in order to use `error-stack`.
- https://github.com/blockprotocol/blockprotocol/pull/563
=> Bump type-system dependency to latest revision

packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/query/ontology.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
Similar to #1021 this adds structural queries for `EntityType`s
- [Asana task](https://app.asana.com/0/0/1202884883200955/f) _(internal)_
- #1021 
- #1023
- Add `EntityType` to `PostgresContext`
- Implement resolving for `EntityType`
- Implement `Read` for `EntityType` with `Expression` as `Read::Query`
- Use the new implementation in the REST endpoints
- Adjust tests
- This is the last ontology type where structural queries had to be adjusted. All four ontology types share a similar `Read` implementation, this will be unified: [Asana Task](https://app.asana.com/0/0/1202884883200959/f) (_internal_)
Currently, only basic expressions are tested. Currently, these are manually tested, a [follow-up task](https://app.asana.com/0/0/1202884883200974/f) (_internal_) will cover more extensive …
=> Add structural queries for `EntityType`

packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/resolve/context.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/resolve/links.rs
#1027 added support for basic `Entity` queries, but did not implement queries across entities as `Links` were added in #1028. This combines these functionalities and adds a query for `Entity` to filter by `"outgoingLinks"` and `"incomingLinks"`.
- [Asana task](https://app.asana.com/0/0/1202912966917505/f) _(internal)_
- #1027 
- #1028
- Add functions to read links by source/target entity ids from the context
- Resolve the source/target entity queries 
- Add tests for Structural Querying: [Asana Task](https://app.asana.com/0/0/1202884883200974/f) (_internal_)
Currently, only basic expressions are tested. Currently, these are manually tested, a [follow-up task](https://app.asana.com/0/0/1202884883200974/f) (_internal_) will cover more extensive testing of the API.
Pass arbitrary expressions …
=> Support links in `Entity` queries

packages/libs/error-stack/README.md, packages/libs/error-stack/macros/rust-toolchain.toml, packages/libs/error-stack/rust-toolchain.toml, packages/libs/error-stack/src/lib.rs
Wtith the`2022-08-27` toolchain, `Error` was moved into `core.
`2022-08-27` is currently the latest toolchain with miri support
- #1038
=> Bump toolchain to `2022-08-27`

packages/libs/error-stack/src/context.rs, packages/libs/error-stack/src/lib.rs, packages/libs/error-stack/src/macros.rs
`Error` was moved to `core`, we should support it
- https://github.com/rust-lang/rust/pull/99917
- https://github.com/rust-lang/project-error-handling/issues/3
- #1037
- Support `core::error::Error` on nightly builds
=> Support `core::error::Error`

packages/libs/error-stack/CHANGELOG.md
#1038 added support for `core::error::Error` which is worth pointing out in the changelog
=> Mention support for `core::error:Error` in CHANGELOG.md

packages/libs/error-stack/src/fmt/mod.rs, packages/libs/error-stack/tests/snapshots/doc/fmt__doc.snap, packages/libs/error-stack/tests/snapshots/doc/fmt_doc_alt.snap
In the future, once `specialization` is stabilized, we will remove the `attach_printable()` function and replace it with a specialization.
Hooks currently treat printable attachments differently, as they do not invoke any hooks, if we would merge `attach()` and `attach_printable()`, that behavior would change and cause confusion.
Thanks to @TimDiekmann for spotting this!
Hooks are also invoked for printable attachments, but they will have an additional fallback: their `String` representation.
They will change from:
* `printable.to_string()`
To:
* invoke hooks
* no hook invoked? invoke fallback
* no fallback found? use `printable.to_string()`
No, no documentation currently explicitly mentions that `attach_printable` does not invoke hooks. We might add an explicit note that hooks are called …
=> `attach_printable()` attachments now invoke hooks in `error-stack`

packages/hash/README.md, packages/hash/api/src/graphql/resolvers/blockprotocol/getBlock.ts, packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/graphql/typeDefs/blockprotocol.typedef.ts, packages/hash/api/src/graphql/typeDefs/index.ts, packages/hash/frontend/src/blocks/userBlocks.tsx, packages/hash/frontend/src/components/hooks/useGetBlockProtocolBlocks.ts, packages/hash/frontend/src/graphql/queries/block.queries.ts
This PR requests the `Available Block List` from `BP API` over `Workspace API` , instead of directly making a call to `BP API` from frontend. So this PR will prevent avoid leaking the API key in the frontend client, which is a security flaw.
- [Asana task](https://app.asana.com/0/1200211978612931/1202720005996068/f) _(internal)_
- Create a new graphql query to make a call to `BP API` from `Workspace API`. And use the new query instead of calling `BP API` from client
=> Proxy get Block Protocol blocks request via Workspace API

packages/libs/error-stack/src/lib.rs, packages/libs/error-stack/src/report.rs
Boxing the collection of Frames implies a memory footprint equal to a single pointer size instead of three pointer sizes. `Report` is unlikely to be used in the happy path, but it's almost always used in `Result::Err`, so for small `Result::Ok` variants, this would increase the size of the `Result` to 24 bytes (on 64 bit) instead of 8 bytes.
- #1054 
- Box the vector of Frames in `Report`
No
A test was added, which ensures, that a `Report` always has the same memory footprint as a pointer
=> Decrease the memory footprint of `Report` to a third

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/crud.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
This moves out the Rust implementation from #1051. It cleans up the linked implementation and also adds implementations for `DataType`, `EntityType` and `LinkType`.
This PR enhances the query REST endpoints to require additional depth parameters. When passing a depth > 0, all referenced types up to a certain depth will also be returned. The depth specifies how deep the recursive lookup will be. E.g. having a property type `A`, which references a property type `B`, which references a property type `C`, which references a data type `D`:
- a `propertyTypeQueryDepth=0` will not return any references
- a `propertyTypeQueryDepth=1` will include `B` in the referenced property types
- a `propertyTypeQueryDepth=2` will return `B` and `C` in the referenced property types
- a …
=> Implement recursive lookup for ontology types

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/tests/integration/postgres/entity.rs, packages/graph/hash_graph/tests/integration/postgres/links.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/hash/api/src/graph/workspace-types.ts, packages/hash/api/src/graphql/resolvers/ontology/data-type.ts, packages/hash/api/src/graphql/resolvers/ontology/entity-type.ts, packages/hash/api/src/graphql/resolvers/ontology/link-type.ts, packages/hash/api/src/graphql/resolvers/ontology/property-type.ts, packages/hash/api/src/graphql/resolvers/user/util.ts, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/api/src/model/knowledge/org.model.ts, packages/hash/api/src/model/knowledge/user.model.ts, packages/hash/integration/src/tests/model/knowledge/org.model.test.ts, packages/hash/integration/src/tests/model/knowledge/user.model.test.ts, packages/hash/integration/src/tests/util.ts
Users and Orgs had the following IDs:
- Kratos Identifier ID
- Entity ID
- Account ID (stored inside the properties blob)
The last two were deemed duplicative (and confusing) and as such the Account ID inside the properties blob (and its associated property types and accessors) has been removed.
Doing so required us to extend the create_entity endpoint to allow the caller to pass in an `entityId`. This seems a little strange but it could allow the workspace to implement custom ID generation in the future.
- [Asana task](https://app.asana.com/0/1200211978612931/1202937382769276/f) _(internal)_
- Adds an optional `EntityId` parameter on the create entity methods.
- Removes the `accountId` property type and accessors from the User and Org types and Model classes
- Replaces usages of …
=> Consolidate entityId and accountId for Users/Orgs

packages/libs/error-stack/Makefile.toml, packages/libs/error-stack/src/lib.rs
With the `hooks` feature and the `futures` feature deprecated (thus, ignored), the feature powerset will now only run 13 Jobs (12 without powerset). 
- #1048 
- #1049
=> Enable `--feature-powerset` for tests

packages/graph/hash_graph/Makefile.toml, packages/graph/hash_graph/bin/hash_graph/src/main.rs, packages/graph/hash_graph/lib/graph/src/lib.rs
We don't use any unsafe code in the [HASH](https://hash.ai/platform/hash) graph datastore, and we should avoid it if not strictly necessary. Forbidding `unsafe` also implies, that we don't require to run `miri` on CI, which (a) speeds up CI and (b) allows us to use toolchains, where `miri` is not available.
- Forbid unsafe code (`#![deny(...)]` allows further `#![allow]` statements, `#![forbid(...)` does not)
- Disable `miri`
Next to the statement, I put a comment on how we want to proceed, if we require `unsafe`: We should prefer `#![deny(...)]` over removing the statement, unless this gets too verbose.
```
error: declaration of an `unsafe` function
--> lib/graph/src/lib.rs:78:1
|
78 | unsafe fn test() {}
| ^^^^^^^^^^^^^^^^^^^
|
= note: At the current state, unsafe code should be avoided …
```
=> Forbid unsafe code in the HASH graph

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/link.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/links.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/ontology.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/tests/rest-test.http, packages/graph/migrations/postgres/migration/1656417312397_initial.ts, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/api/src/model/knowledge/link.model.ts, packages/hash/api/src/model/ontology/data-type.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/link-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts
There were a few confusing / non-ideal column names in the database. This PR simply updates them and the relevant usages in the Graph. It does not propagate those renames through the workspace code, as that is a larger task ([tracked in this](https://app.asana.com/0/0/1202986802899184/f))
- [Asana task](https://app.asana.com/0/1202882583267702/1202986802899183/f) _(internal)_
- Completes a TODO to rename `ids` to `type_ids`
- Renames `created_by` to `owned_by_id`
- Renames `removed_by` to `removed_by_id`
- Not to my knowledge
This introduces some inconsistency whereby the workspace now has `accountId`, and `ownedByAccountId` and other things throughout its code. We will want to unify the naming.
Refactor the Workspace backend (and possibly frontend) code to be consistent with the naming. …
=> Rename database columns

packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/logging/init.rs, packages/graph/hash_graph/lib/graph/src/store/pool.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/links.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/ontology.rs, packages/graph/hash_graph/rust-toolchain.toml
Generic associated types got stabilized, so we should use the stabilized feature.
This also applies suggestions from clippy introduced since our last toolchain bump.
- Because of https://github.com/hashintel/hash/pull/1064, we don't require the `miri` component.
=> Bump toolchain to `nightly-2022-09-15`

packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/query.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts
Currently, structured queries only support `"uri"`, which is misleading as it is not clear, if a base URI or a versioned URI is expected. This removes `"uri"` and adds `"baseUri"` and `"versionedUri"` instead.
- [Slack discussion](https://hashintel.slack.com/archives/C03F7V6DU9M/p1663254240476059) (_internal_)
=> Replace `"uri"` with `"baseUri"` and `"versionedUri"` in queries

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/rest-test.http
Adds a depth field to read linked entities when querying enttities.
- [Asana task](https://app.asana.com/0/1200211978612931/1202682556665585/f) _(internal)_
- This is a follow-up of #1066
- Look up linked entity ids and it's corresponding link type by a given entity id
- Recursively resolve the linked entities up to the specified 
- The OpenAPI client was updated
- Support returning Links
- Add a similar functionality for `Link`s: [Asana Task](https://app.asana.com/0/1202882583267702/1202986163519979/f) (_internal_)
The query itself is used in a REST endpoint test, but the result is not read yet
Run the query as shown in `rest-test.http` and validate the results
```http
POST http://127.0.0.1:4000/entities/query
{
"query": {
"eq": [
{
"path": [
"version"
]
}, …
```
=> Implement recursive lookups for entities

packages/blocks/callout/package.json, packages/blocks/header/package.json, packages/blocks/paragraph/package.json, packages/hash/api/package.json, packages/hash/backend-utils/package.json, packages/hash/frontend/package.json, packages/hash/shared/package.json, yarn.lock
We currently require a single version of `@blockprotocol/core` to be relied on by the other `@blockprotocol/*` packages, because they are designed to share a map of element:core handlers.
`@blockprotocol/hook` had fallen behind, and was using a different version to `@blockprotocol/graph`, meaning that blocks did not work.
This PR fixes that by upgrading `@blockprotocol/hook`.
=> Upgrade @blockprotocol dependencies

packages/hash/api/src/graph/workspace-types.ts, packages/hash/api/src/model/index.ts, packages/hash/api/src/model/knowledge/block.model.ts, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/integration/src/tests/model/knowledge/block.model.test.ts
This PR adds the `BlockModel` class, and its corresponding workspace types:
- the `componentId` property type
- the `blockData` link type
- the `block` entity type
- [Asana task](https://app.asana.com/0/1202882583267702/1202606867065365/f) _(internal)_
- adds workspace types blocks depend on
- adds `BlockModel` class
No.
- currently the destination entity type of a link type has to be specified when adding an outgoing link to an entity type. For the outgoing block data link of a block model class, any entity type could be a possible destination for the link. As a temporary solution, a "dummy" entity type has been added to the workspace types so that the block entity type satisfies the current constraints of the Graph API.
- [Stop requiring outgoing links to specifying a destination entity …
=> Implement `BlockModel` class

packages/hash/frontend/src/blocks/page/createSuggester/Suggester.tsx
#896 inserted a bug where the suggester won't automatically scroll when navigating the list with the up and down arrow keys. This PR adds back the code that scrolls the selected item into the view.
Before: 
After:
=> Fix suggester scrolling with arrow keys

packages/libs/error-stack/Makefile.toml, packages/libs/error-stack/tests/common.rs, packages/libs/error-stack/tests/snapshots/test_debug__full__complex.snap, packages/libs/error-stack/tests/snapshots/test_debug__full__hook_provider.snap, packages/libs/error-stack/tests/snapshots/test_debug__full__linear.snap, packages/libs/error-stack/tests/snapshots/test_debug__full__linear_ext.snap, packages/libs/error-stack/tests/snapshots/test_debug__full__multiline_ctx.snap, packages/libs/error-stack/tests/snapshots/test_debug__full__sources.snap, packages/libs/error-stack/tests/snapshots/test_debug__full__sources_transparent.snap, packages/libs/error-stack/tests/test_compatibility.rs, packages/libs/error-stack/tests/test_debug.rs
In CI, we currently do not test `test_compatibility`. This is because optional dependencies (`eyre`/`anyhow`) are not included by `cargo hack` by default.
- #1098 
- Enable optional dependencies in `cargo make`
- Fix `test_compatibility` (was outdated as it was not tested)
=> Test optional dependencies from `cargo make`

packages/libs/error-stack/src/fmt/hook.rs, packages/libs/error-stack/tests/snapshots/test_debug__full__hook_for_context.snap, packages/libs/error-stack/tests/test_debug.rs
The hooks are supposed to be invoked on:
- Attachments
- values provided by `Context::provide`
On non-nightly channels, the latter is not available, but the hooks are invoked for `Context` as well. This PR changes the behavior on non-nightly channels to match the behavior on nightly channels (as far as possible).
- Fixes https://github.com/hashintel/hash/issues/1092
- #1099 
- Hook behavior on stable channels
A new test was added to test this behavior
=> Fix hook behavior on non-nightly channels

packages/graph/hash_graph/lib/graph/src/store/query.rs
Comparing with `null` should never bail with an error, at most it should return `false`
=> Support comparing with `null`

packages/hash/frontend/src/blocks/page/InsertBlock.tsx, packages/hash/frontend/src/blocks/page/PageTitle/PageTitle.tsx, packages/hash/frontend/src/pages/[account-slug]/[page-slug].page.tsx
Disable following elements on pages on `readonly` mode, to prevent the users from seeing editable elements on readonly pages. 
- Page title
- Page icon
- Insert block element (full-width horizontal element between blocks)
- [Asana task](https://app.asana.com/0/1200211978612931/1202855617846688/f) _(internal)_
1.  Open a page and add `&readonly` as url param
1.  Confirm that elements mentioned above are not available.
=> Disable `PageIcon`, `InsertBlock` & `PageTitle` on readonly mode

packages/hash/frontend/src/shared/layout/layout-with-sidebar/account-page-list/page-tree-item.tsx
This PR shows a tooltip when page titles on the left sidebar are hovered, to improve the UX.
- [Asana task](https://app.asana.com/0/1200211978612931/1202861224066305/f) _(internal)_
=> Show tooltip with full page title on hover in sidebar

packages/graph/hash_graph/lib/graph/src/store/postgres/context/ontology.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/link/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/resolve.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/resolve.rs
For some use cases we want to filter queries by their owner id.
- [Asana task](https://app.asana.com/0/1200211978612931/1203015527055374/f) _(internal)_
- add `ownedById` filter to queries
Currently, this is not tested, but this will be used soon in the backend, which then will be tested as part of the backend integration tests
```http
POST http://127.0.0.1:4000/entities/query
{
"query": {
"eq": [
{
"path": [
"ownedById"
]
},
{
"literal": "f13ef0fb-fcfd-44c8-b652-a47824b95596"
}
]
},
"dataTypeQueryDepth": 0,
"propertyTypeQueryDepth": 0,
"linkTypeQueryDepth": 0,
"entityTypeQueryDepth": 0,
"linkTargetEntityQueryDepth": 0,
"linkQueryDepth": 0
}
```
=> Support `ownedById` in queries

packages/libs/error-stack/Cargo.toml, packages/libs/error-stack/src/compat/eyre.rs, packages/libs/error-stack/tests/compiletest.rs, packages/libs/error-stack/tests/test_compatibility.rs
`eyre` currently does not support `no-std` compilation. Implying avoids surprises and also reduces the amount of tests
`trybuild` currently has a bug with `dep:`-features, so UI builds are currently disabled
=> Imply `std` feature when enabling `eyre`

packages/hash/api/src/model/knowledge/link.model.ts, packages/hash/api/src/model/knowledge/user.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/util.ts, packages/hash/integration/src/tests/model/knowledge/entity.model.test.ts, packages/hash/integration/src/tests/model/knowledge/link.model.test.ts, packages/hash/integration/src/tests/model/ontology/entity-type.model.test.ts
This PR improves how the `LinkModel` class determines whether a link is ordered. Previously it inspected the sibling links for the presence of an `index`. Now it inspects the source entity type schema to see if `ordered` is set to `true` for the outgoing link.
- [Asana task](https://app.asana.com/0/1202805690238892/1203045927094838/f) _(internal)_
See commits.
- The docs for x need updating to explain that y
The existing integration tests, and an additional `EntityTypeModel` test for the `isOutgoingLinkOrdered` method.
Check backend integration tests in CI
=> Determine whether link is `ordered` using its source entity type schema

packages/libs/error-stack/src/compat/anyhow.rs, packages/libs/error-stack/src/compat/eyre.rs, packages/libs/error-stack/src/compat/mod.rs, packages/libs/error-stack/src/frame/frame_impl.rs, packages/libs/error-stack/src/lib.rs, packages/libs/error-stack/src/report.rs, packages/libs/error-stack/tests/test_compatibility.rs
Currently, the compatibility layer has an intermediate context (`AnyhowContext`/`EyreContext`). This PR removes the required additional context, so `anyhow::Error`/`eyre::Report` are directly captured in a `Report`
- #1113 
- Make `AnyhowContext`/`EyreContext` an implementation detail by making it private to frame implementation
- Implement `FrameImpl` for those contexts and support constructing a frame from the underlying error directly
- Properly test backtrace capturing of `anyhow` and `eyre`
Before:
```rust
let anyhow_error: anyhow::Error = anyhow!(...);
let anyhow_report: Report<AnyhowContext> = Err(anyhow_error).into_report().unwrap_err();
let anyhow_context: &AnyhowContext = anyhow_report.current_context();
let anyhow_error_ref: &anyhow::Error = anyhow_context.as_anyhow();
```
now: …
=> Remove intermediate context for compatibility module

packages/libs/error-stack/src/iter.rs, packages/libs/error-stack/tests/test_iter.rs
The tests for `Frames` is not really readable.
- Change test to use contexts instead of attachments for prettier prints
- use the printed report in the docs
- remove implementation detail on the docs
=> Make test and docs for `Frames` more readable

packages/hash/api/src/graphql/resolvers/knowledge/model-mapping.ts, packages/hash/api/src/graphql/typeDefs/knowledge/block.typedef.ts, packages/hash/api/src/graphql/typeDefs/knowledge/entity.typedef.ts, packages/hash/api/src/graphql/typeDefs/knowledge/page.typedef.ts
A follow-up PR to address an alias we wanted in https://github.com/hashintel/hash/pull/1090
This PR simply adds `accountId` to the knowledge GQL types that should alias the `ownedById`
=> Aliased accountId

.github/scripts/rust/Makefile.toml, packages/graph/Makefile.toml, packages/graph/hash_graph/Makefile.toml, packages/libs/error-stack/Makefile.toml
Simply cleans up the make files a bit.
- [Asana task](https://app.asana.com/0/1200211978612931/1202840100810875/f) _(internal)_
- Renames `task` to `cargo`
- Introduces more of the tooling at the top level such as `docker` and `yarn`
- Refactors tasks to extend from the respective tooling
- Reworks the top level makefile formatting a little
- Re-orders attributes to be somewhat consistent, putting the command close to the args, the description at the top, etc.
No, it should be functionally the same
- CI should be fairly comprehensive
1.  Run whatever `cargo make` commands you feel like
=> Cleanup Makefile

packages/libs/error-stack/CHANGELOG.md
`Report::source(_mut)` wasn't a public method, so it does not need to be shown in the changelog. Additionally, it's easier to read changelogs if they are ordered by the importance of the different items. I attempted to re-order the changelog to improve this
[Rendered](https://github.com/hashintel/hash/blob/td/error-stack/changelog-reorder/packages/libs/error-stack/CHANGELOG.md)
=> Reorder changelog by importance

packages/hash/api/src/graphql/resolvers/ontology/entity-type.ts, packages/hash/api/src/graphql/resolvers/ontology/link-type.ts, packages/hash/api/src/graphql/resolvers/ontology/property-type.ts, packages/hash/api/src/graphql/typeDefs/ontology/entity-type.typedef.ts, packages/hash/api/src/graphql/typeDefs/ontology/link-type.typedef.ts, packages/hash/api/src/graphql/typeDefs/ontology/property-type.typedef.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolCreateEntityType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolCreateLinkType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolCreatePropertyType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolUpdateEntityType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolUpdateLinkType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolUpdatePropertyType.ts, packages/hash/frontend/src/graphql/queries/ontology/data-type.queries.ts, packages/hash/frontend/src/graphql/queries/ontology/entity-type.queries.ts, packages/hash/frontend/src/graphql/queries/ontology/link-type.queries.ts, packages/hash/frontend/src/graphql/queries/ontology/property-type.queries.ts, packages/hash/frontend/src/pages/type-editor/blockprotocol-ontology-functions-hook.ts
This PR modifies the GQL ontology mutations to use `ownedById` instead of the `accountId` alias. This propagated changes in the frontend, where these mutations are currently being used in the BP hooks.
- [Asana task](https://app.asana.com/0/1202805690238892/1203072290779156/f) _(internal)_
No.
=> Use `ownedById` in GQL ontology mutations

packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/graphql/resolvers/knowledge/page/page.ts, packages/hash/api/src/graphql/typeDefs/knowledge/page.typedef.ts, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/api/src/model/knowledge/page.model.ts
This PR introduces a `knowledgePage` GQL query.
- [Asana task](https://app.asana.com/0/1202953520344818/1203064073566616/f) _(internal)_
- introduces the `knowledgePage` GQL query
- adds an unimplemented `EntityModel.getVersion` method
No.
- the current implementation of the `KnowledgePage` GQL type cannot directly replace the existing `Page` GQL type, as it's properties don't resolve linked entities using legacy fields.
We are currently conducting manual tests for GQL queries/mutations
2. Run `yarn external-services up` locally
3. Run `yarn test:backend-integration page.model` in a separate terminal window to seed the database with some pages
4. Run `yarn dev`
5. Open `localhost:3000` and login
6. Open `localhost:5001/graphql` to access the GQL playground
7. …
=> `knowledgePage` GQL query

packages/hash/api/src/graphql/resolvers/ontology/data-type.ts, packages/hash/api/src/graphql/resolvers/ontology/entity-type.ts, packages/hash/api/src/graphql/resolvers/ontology/link-type.ts, packages/hash/api/src/graphql/resolvers/ontology/model-mapping.ts, packages/hash/api/src/graphql/resolvers/ontology/property-type.ts, packages/hash/api/src/graphql/typeDefs/ontology/data-type.typedef.ts, packages/hash/api/src/graphql/typeDefs/ontology/entity-type.typedef.ts, packages/hash/api/src/graphql/typeDefs/ontology/link-type.typedef.ts, packages/hash/api/src/graphql/typeDefs/ontology/property-type.typedef.ts, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/ontology-types-shim.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolCreateEntityType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolCreateLinkType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolCreatePropertyType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolUpdateEntityType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolUpdateLinkType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolUpdatePropertyType.ts, packages/hash/frontend/src/graphql/queries/ontology/data-type.queries.ts, packages/hash/frontend/src/graphql/queries/ontology/entity-type.queries.ts, packages/hash/frontend/src/graphql/queries/ontology/link-type.queries.ts, packages/hash/frontend/src/graphql/queries/ontology/property-type.queries.ts
Replaces instances of `VersionedUri` with `Id` for any ontology type in the HASH API and frontend.
=> Replace `*VersionedUri` with `*Id` for ontology types

packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/graphql/resolvers/knowledge/block/block.ts, packages/hash/api/src/graphql/typeDefs/knowledge/block.typedef.ts
This PR introduces a `knowledgeBlocks` GQL query.
- [Asana task](https://app.asana.com/0/1202953520344818/1203064073566618/f) _(internal)_
- introduces the `knowledgeBlocks` GQL query
No.
- the current implementation of the `KnowledgeBlock` GQL type cannot directly replace the existing `Block` GQL type, as it's properties don't resolve linked entities using legacy fields.
We are currently conducting manual tests for GQL queries/mutations
2. Run `yarn external-services up` locally
3. Run `yarn test:backend-integration page.model` in a separate terminal window to seed the database with some pages and blocks
4. Run `yarn dev`
5. Open `localhost:3000` and login
6. Open `localhost:5001/graphql` to access the GQL playground
7. Execute the below query to fetch a page by …
=> `knowledgeBlocks` GQL query

packages/graph/hash_graph/bench/benches/representative_read/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/mod.rs, packages/graph/hash_graph/bench/benches/representative_read/ontology/entity_type.rs, packages/graph/hash_graph/bench/benches/representative_read/ontology/mod.rs, packages/graph/hash_graph/bench/benches/representative_read/seed.rs
This follows from #1132. It simply adds a query across the "representative" graph to get an entity type by its ID.
- Introduces a benchmark for getting an entity type by its ID.
- No
- Query rooted subgraphs
- Check performance of querying across various scales of the graph
- The current (single) benchmark group
1. Checkout the branch
2. Run `cargo make deployment-up`
3. Run `make recreate-db`
4. Run `make migrate-up`
5. Run `cargo bench`
=> Benchmark query entity type

packages/graph/hash_graph/bench/Cargo.toml, packages/graph/hash_graph/bench/benches/read_scaling/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/read_scaling/knowledge/mod.rs, packages/graph/hash_graph/bench/benches/read_scaling/mod.rs, packages/graph/hash_graph/bench/benches/representative_read/mod.rs, packages/graph/hash_graph/bench/benches/util.rs
This follows from #1137. It adds a benchmark to query an entity by its ID, comparing the performance at various sizes of database (numbers of that specific entity type).
- [Asana task](https://app.asana.com/0/0/1203072189010770/f) _(internal)_
- Introduces a scaling benchmark for get_entity_by_id
- Adds a parameter to the `StoreWrapper` to optionally delete the database on drop
- Adds the `Drop` implementation
- Adds the `html_reports` feature to criterion to generate HTML reports
- No, although if we start to use the reports we should update the README to say where to find them (they are currently made inside `./target/criterion/reports`
- Write scaling benchmarks for other queries
- The current (single) benchmark group
1. Checkout the branch
2. Run `cargo make deployment-up`
3. Run …
=> Benchmark asymptotic performance of `get_entity_by_id` 

packages/libs/error-stack/CHANGELOG.md
`error-stack` was released in #1113, this will adjust the changelog to link to that commit.
- [Asana task](https://app.asana.com/0/1200211978612931/1202958255787895/f) _(internal)_
- Tag the release when this PR is merged
=> Update CHANGELOG.md for latest release

packages/libs/error-stack/README.md
The link for the output image is broken on external pages, this makes the link absolute
- Fixes #1151
=> Make image link in README.md absolute

.github/ISSUE_TEMPLATE/bug-report-error-stack.yml, packages/libs/error-stack/Cargo.toml
error-stack v0.2.0 had a relative link in the readme, so it was not rendered correctly on crates.io
- https://github.com/hashintel/hash/issues/1151
=> Bump error-stack to version 0.2.1

packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/graphql/resolvers/knowledge/link/link.ts, packages/hash/api/src/graphql/resolvers/knowledge/model-mapping.ts, packages/hash/api/src/graphql/typeDefs/index.ts, packages/hash/api/src/graphql/typeDefs/knowledge/link.typedef.ts, packages/hash/api/src/model/knowledge/link.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts
This PR adds resolvers for interacting with Links in the API.
- [Asana task](https://app.asana.com/0/1202953520344818/1203055428965602/f) _(internal)_
- Adds new `typedefs` for `link`s
- Add get, create and delete links
- GQL docs have been added
- There is some uncertainty with how we want the GQL types to be exposed, so the structure of this addition is subject to change.
- The Get query here specifically will allow implementing more of collab ([Asana task](https://app.asana.com/0/0/1203055428965600/f)).
- None yet
1.  Set up external services
1.  Run `yarn dev` and login
1.  run queries on http://localhost:5001/graphql
These demos assume the http tests at `packages/graph/hash_graph/tests/rest-test.http` have been run to seed some data. …
=> Add `link` resolvers

sites/hashdev/src/_pages/blog/10_error-stack-update-0-2.mdx
The method is called [`request_ref`](https://docs.rs/error-stack/latest/error_stack/struct.Report.html#method.request_ref), not `requested_ref`
=> Fix typo in blog post

packages/hash/api/src/graphql/resolvers/index.ts, packages/hash/api/src/graphql/resolvers/knowledge/entity/entity.ts, packages/hash/api/src/graphql/resolvers/knowledge/page/update-page-actions.ts, packages/hash/api/src/graphql/typeDefs/knowledge/entity.typedef.ts, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/integration/src/tests/model/knowledge/entity.model.test.ts
This PR introduces the `createKnowledgeEntity` mutation, and slightly modifies the arguments of a related a model class method
- [Asana task](https://app.asana.com/0/1202953520344818/1203086812814267/f) _(internal)_
See commits.
No.
We are currently conducting manual tests for GQL queries/mutations
2. Run `yarn external-services up` locally
3. Run `yarn test:backend-integration page.model` in a separate terminal window to seed the database with some pages and blocks
4. Run `yarn dev`
5. Open `localhost:3000` and login
6. Open `localhost:5001/graphql` to access the GQL playground
7. Execute a `createKnowledgeEntity` mutation (like the example below) to test that fetching entities works, and returns the appropriate GQL type.
<details>
<summary>createKnowledgeEntity …
=> Add `createKnowledgeEntity` mutation

packages/graph/hash_graph/bench/Cargo.toml, packages/graph/hash_graph/bench/benches/read_scaling/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/seed.rs, packages/graph/hash_graph/lib/graph/Cargo.toml, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
In benchmarks, seeding the database takes a long time as we insert entities one by one. 
- Add a default to `entities.version` to be the time of creation, this is required in order to use the COPY query
- Add functions to batch-insert entity ids and entities
- Use batch-insertion in benchmarking
For testing this PR locally or after this PR is merged, the database needs to be migrated. This functionality was added to speed up seeding in benchmarks, so it's hidden behind a feature flag.
before:
> Finished seeding database representative_read with 16500 entities after 134.974929s
after:
> Finished seeding database representative_read with 16500 entities after 1.514568s
=> Support batch insertion of entities

packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/knowledge-shim.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolGetEntity.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/ontology-types-shim.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetDataType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetEntityType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetLinkType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetPropertyType.ts, packages/hash/frontend/src/graphql/queries/knowledge/entity.queries.ts, packages/hash/frontend/src/graphql/queries/ontology/entity-type.queries.ts, packages/hash/frontend/src/pages/entity-editor.page.tsx, packages/hash/frontend/src/pages/type-editor/blockprotocol-ontology-functions-hook.ts
This PR adds the `useBlockProtocolGetEntity` hook to be used for the upcoming entity editor.
It also provides an example entity editor page to the frontend, demonstrating its usage.
- [Asana task](https://app.asana.com/0/1202805690238892/1203084714149805/f) _(internal)_
See commits.
No.
None.
2. Run `yarn external-services up` locally
3. Run `yarn dev`
4. Open `localhost:3000` and login
5. Go to `localhost:3000/entity-editor` to view the example entity editor making use of the `useBlockProtocolGetEntity` method
https://user-images.githubusercontent.com/42802102/194020333-bd8f0368-aa57-43f9-953b-6e9494978e30.mov
=> Add `useBlockProtocolGetEntity` hook + example entity-editor page

.github/workflows/ci.yml, packages/hash/playwright/tests/entity-creation.spec.ts, packages/hash/playwright/tests/guest-user.spec.ts, packages/hash/playwright/tests/page-creation.spec.ts, packages/hash/playwright/tests/page-readonly-mode.spec.ts
This PR re-enables the playwright CI workflow, and individually "skips" each of the playwright tests that are broken (currently that's all of them).
- [Asana task](https://app.asana.com/0/1202805690238892/1203106234191591/f) _(internal)_
- The seed-data scripts that the playwright tests depend on have not been re-implemented yet. Follow-up task has been linked in a todo.
=> Re-enable playwright workflow in CI on the `dev/graph` branch

packages/libs/error-stack/CHANGELOG.md, packages/libs/error-stack/Cargo.toml
With #1174 being immediately helpful for VSCode users, this is a small improvement on the usability on `error-stack`
=> Bump error-stack to 0.2.2

.github/ISSUE_TEMPLATE/bug-report-error-stack.yml
Include myself (@indietyp) in the assignees of error-stack issues. 
This was previously not possible (due to me not being a collaborator).
This would make noticing and reacting to issues a lot easier!
=> include `indietyp` in error-stack issue template

packages/libs/error-stack/src/lib.rs
Some minor changes to the documentation
- Mention compatibility to `eyre` and `anyhow` in crate-level docs
- Remove mentioning of `Display` hooks (deprecated)
- Some formatting
=> Minor tweaking to crate-level documentation

packages/libs/error-stack/CHANGELOG.md, packages/libs/error-stack/Cargo.toml
We added a new license option and tweaked some bits. The license change is the only notable change, but worth doing a release.
- #1187
- #1188
- #1189
- Bump `error-stack` version to `0.2.3`
- Update heading in changelog
=> Bump `error-stack` to version `0.2.3`

packages/hash/frontend/src/lib/use-init-type-system.ts, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/[entity-type-id].page.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/edit-bar.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/form-types.ts, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/property-expected-values.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/property-list-card.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/property-menu.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/property-selector.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/use-entity-type.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/use-property-types.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/util.ts
Persist updates to list of properties in the entity type editor, and related changes. See below
- [Asana task](https://app.asana.com/0/1203007126736604/1203144688196124/f) _(internal)_
N/A
Functionality changes:
- Always display the latest entity type version, not just version 1
- Make publish changes and discard changes buttons on entity type edit bar work
- New loading state for the edit bar while publishing, which disabled buttons. @nonparibus I'll need to consult on what these buttons should look like while disabled, not sure we have that design anywhere
- Display already persisted property types for an entity type when loading the editor
Code changes:
- Integrate the type system loading process into `useEntityType` so that `onComplete` isn't called until the type system has loaded …
=> Entity type editor – persist changes, and related updates

packages/graph/hash_graph/Cargo.lock, packages/graph/hash_graph/bench/Cargo.toml, packages/graph/hash_graph/bin/hash_graph/Cargo.toml, packages/graph/hash_graph/bin/hash_graph/src/args.rs, packages/graph/hash_graph/lib/graph/Cargo.toml, packages/graph/hash_graph/lib/graph/src/api/rest/account.rs, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/logging/args.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/version_id.rs
We were starting to fall behind on dependency versions, there were a few major (or at least breaking) updates made to our dependencies. This PR upgrades all dependencies (or at least all the ones that were automatically selected by `cargo upgrade --workspace`).
This also means we are using a proper release of `error-stack` again rather than a direct git hash.
- [Asana task](https://app.asana.com/0/1200211978612931/1203157172269841/f) _(internal)_
- Runs `cargo upgrade` and updates the versions for packages (look to diff for comprehensive list)
- Stop depending on a git hash for utoipa and use their newest release
- Changes our uses of `Component` to `ToSchema`
- Changes our usages of `handlers` to `paths` in utoipa (they changed the attribute)
- Changes some of our own modifying code to …
=> Upgrade HASH Graph dependencies

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/tests/integration/postgres/entity.rs, packages/graph/hash_graph/tests/integration/postgres/links.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/rest-test.http, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/api/src/model/knowledge/link.model.ts, packages/hash/api/src/model/ontology/data-type.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/link-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts
This PR introduces the `PersistedOntologyMetadata`, `PersistedEntityMetadata` and `PersistedLinkMetadata` structs.
- [Asana task](https://app.asana.com/0/1203007126736604/1203157427866931/f) _(internal)_
- adds a `metadata` field to the existing persisted ontology/knowledge types
- updates the return types of the Graph API to return the metadata field instead of an identifier
The existing rust tests/workspace integration tests
Check CI to see the rust tests/workspace integration tests are passing, or run them locally
=> Introduce ontology/knowledge `metadata` structs

sites/hashai/resources/docs/simulation/creating-simulations/libraries/hash/README.md
`hstd` is currently not available in Python but some docs use `import hstd`
- [Slack thread](https://hashintel.slack.com/archives/C02HR1B2NP7/p1665615743646959) _(internal)_
=> Add hint that `hstd` is unavailable in Python

packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/tests/integration/postgres/data_type.rs, packages/graph/hash_graph/tests/integration/postgres/entity_type.rs, packages/graph/hash_graph/tests/integration/postgres/link_type.rs, packages/graph/hash_graph/tests/integration/postgres/property_type.rs
We had inconsistent visibilities on our `Persisted*` structs. Ideally we don't want these to be constructed unless the record actually exists, and at that point we don't want them to be mutable.
This makes the fields within them private, and updates accessors.
- [Asana task](https://app.asana.com/0/1200211978612931/1203179088220798/f) _(internal)_
- Rust tests (and compilation)
1.  Follow instructions for setting up the Graph dev env
2. Run `cargo make test`
=> Fix visibility on `Persisted*` structs

packages/graph/hash_graph/lib/graph/src/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/database.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs
Adds structures for `DataType`s required for compiling data type queries.
This commit is not adding compilation code logic, but the required structures to feed the compiler.
- [Asana task](https://app.asana.com/0/0/1203157447338103/f) _(internal)_
- #1202
- #1208
- Adds `DataTypeQuery`, `DataTypeQueryField`, and `DataTypeQueryPath`
- Implement the query traits on these
Documentation was added for the newly added structs
The structs and traits are currently unused. They will be used in a follow-up.
Please see the list of subtasks of the [main Asana task](https://app.asana.com/0/1200211978612931/1203073992606533/f) _(internal)_
Tests were added for functions and rendering
=> Add structures for `DataType` for query compilation

packages/graph/hash_graph/lib/graph/src/ontology/data_type.rs
To use compiled queries, the path passed in the Rest endpoints needs to be converted to the specific ontology/knowledge query path. With #1203, `DataTypeQueryPath` is available, so this PR adds the conversion from a list of strings.
- [Asana task](https://app.asana.com/0/0/1203167266370353/f) _(internal)_
- #1202
- #1203
- Add `DataTypeQueryToken`, which is used as an implementation detail to parse a single token of a full `DataTypeQueryPath`
- **Implement `Deserialize` on `DataTypeQueryPath`**
- To make migration as smooth as possible, this also adds a conversion from `Path` to `DataTypeQueryPath`
This is mostly an implementation detail. A short description on the types were added
Please see the list of subtasks of the [main Asana …
=> Add conversion from structural query path to `DataTypeQueryPath`

packages/graph/hash_graph/lib/graph/src/store/query/filter.rs, packages/graph/hash_graph/lib/graph/src/store/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/query/old.rs
`Filter`s are going to replace `Expression`s. The functionality is almost identical, but the internal representation is different:
- No special casing of `Parameter` (`Literal` in `Expression`)
- `Literal::Null` is now represented as `Option`, as it's only possible to compare `NULL` for equality, not for comparison operator (not added yet). Also, in Postgres, the `NULL` value has to be special cased, so `NULL` is not a parameter but part of the query.
- `Filter` does not allow malformed expression, e.g. using `All` inside of `Eq`
- `Equals` and `NotEquals` are now a binary operator
- [Asana task](https://app.asana.com/0/0/1203157447338099/f) _(internal)_
- #1204 
- Adds the bespoke `Filter` and conversion from `Expression` to `Filter`
Please see the list of subtasks of the [main Asana …
=> Add `Filter` and conversion from `Expression`

packages/graph/hash_graph/lib/graph/src/store/postgres/query/condition.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/query/mod.rs
This adds the compilation of `Filter` into `Condition` (added in this PR). a `Condition` will be used in `WHERE` statements and differs in a few key points from `Filter` (which is uer-facing):
- Parameters are prepared, so each `Filter::Parameter` will be replaced with `$x` (e.g. `$1`, `$2`)
- `Filter::Path` is resolved to a `Column`
- [Asana task](https://app.asana.com/0/0/1203132766663456/f) _(internal)_
- #1209
- Adds `Condition` and `ConditionValue` (similar to `Filter`/`FilterValue` but adjusted to be transpiled to SQL)
- Provide a conversion from `Filter` to `Condition`. The parameter list, which is generated in this step, can directly be passed to `tokio_postgres`.
- Extend `QueryRecord` trait with `base_table` and `Field` via `PostgresQueryRecord` (replaces `Query`)
Please see the …
=> Add `Condition` and conversion from `Filter`

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/subgraph.rs
#1198 introduced the `Subgraph` type. The combines all of the elements of the graph into a vertex set. The "edge set" represents how those elements depend on one another. This PR populates the `edges` field.
- [Asana task](https://app.asana.com/0/0/1203176491232123/f) _(internal)_
- Creates the `Edges` struct
- Modifies the `as_dependency` methods to capture edges while resolving dependencies in structural queries.\
- *It is a conscious design decision* to capture edges even if the dependencies won't be resolved (due to the max depth being encountered). This potentially will help with 'cursor'-based pagination, and will help calling code to know there are more things to be resolved. **It does mean that at the moment, having an identifier in the `Subgraph` object does _not_ mean it will …
=> Subgraph edge tracking

packages/graph/Makefile.toml, packages/graph/hash_graph/Makefile.toml
If the DB changes, at the moment devs have to manually call `docker compose` with the build arg`, or temporarily add `--build` to the `deployment-up` task in the graph's Makefile. 
It's not possible (or at least not easy) to pass in parameters to the task (e.g. with `${@}` because they get passed to all tasks, and this breaks CI as we have a `cargo make test` task which requires parameters such as `--no-fail-fast`).
Adding `--build` barely adds overhead as it benefits heavily from docker's caching, so this has minimal impact on local dev, and CI was already building fresh so this should be fine.
1. Run `cargo make test` in the graph
2. Watch CI
=> Rebuild on `deployment-up` in Graph Makefile

packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-page-wrapper/entity-page-header.tsx, packages/hash/frontend/src/shared/layout/layout-with-header/actions-dropdown.tsx
This PR removes two keyboard shortcuts that interfere with other user interactions. For example, pressing 't' in the editor was causing the type editor to appear.
- [Asana task](https://app.asana.com/0/1203007126736604/1203150072758523/f) _(internal)_
We'll want to re-introduce shorcuts in a coherent way throughout the app later. That's not on a critical path to market.
- Manual
1.  Open a page
1.  Press Alt + t / Alt + p
=> Remove keyboard shortcuts starting with Alt / Opt

packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/condition.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/where_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs
It was possible to inject user defined strings into the database query, this provides a fix
- [Asana task](https://app.asana.com/0/1203007126736607/1203205825668112/f) _(internal)_
- https://github.com/hashintel/hash/pull/1217#discussion_r1000583326
- #1218 
- Adds a `Parameter` column access
- Prepare user defined paths
A test is picking this change up
=> Fix user-provided fields not being prepared

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/identifier.rs, packages/graph/hash_graph/lib/graph/src/shared/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/version_id.rs, packages/graph/hash_graph/lib/graph/src/subgraph.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/rest-test.http, packages/graph/migrations/postgres/migration/1656417312397_initial.ts, packages/hash/api/src/model/knowledge/entity.model.ts
This is similar to a number of previous PRs [#1198, #1205, #1220, #1227] however it is _not_ a full-stack change. This returns `Subgraph` from entity endpoints in the Graph API only, and applies a temporary hotfix in the entity model class to allow TypeScript to compile (without breaking functionality).
Migrating the workspace to use the new subgraph will require substantial changes as the concept of `Entity` is ingrained into the BP, and we use the types, hooks, etc. all over the place.
A bug was discovered in development regarding the identifiers, as such some driveby's have been added around this.
- [Asana task](https://app.asana.com/0/1203007126736607/1203214689883085/f) _(internal)_
- Changes `get_entities_by_query` to return a `Subgraph`
- Regenerates the OpenAPI spec
- Driveby's on …
=> Return `Subgraph` from Entity endpoints in the Graph API

packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/condition.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/conditional.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/select_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/where_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/with_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs
Similar to `DataType`s, this adds the representation for `PropertyType`
- [Asana task](https://app.asana.com/0/1203007126736607/1203157447338104/f) _(internal)_
- #1218 
- #1230
- Add `PropertyTypeQueryPath` and implement traits
- Add `PropertyTypeQueryField` and implement traits
A set of tests were added to test property-type queries
=> Add query representation for `PropertyType`

.github/workflows/ci.yml
This PR helps avoid false-positive CI failures like:
- https://github.com/hashintel/hash/actions/runs/3314781921/jobs/5474512064
- https://github.com/hashintel/hash/actions/runs/3319635516/jobs/5485036060
Backend starts successfully, but may take just above 30 seconds to warm up. If `wait-on` timeout is exhausted, the whole workflow shows ❌ instead of ✅ although all tests pass.
Increasing the timeout to 60 seconds helps avoid false-positive failures. We may revisit it again later if we manage to significantly improve backend warm-up performance.
- Check CI examples shared above
- Check CI results in this PR
=> Increase `wait-on` timeout for backend in CI

packages/graph/hash_graph/lib/graph/src/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/link_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/link_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs
With #1197 the provenance fields were introduced. In order to use the structural queries in the REST API, it's required, that the fields can be selected.
- [Asana task](https://app.asana.com/0/1203007126736607/1203157447338099/f) _(internal)_
- #1223 
Adds `CreatedById`, `UpdatedById`, and `RemovedById` to query parameters
=> Add provenance fields for ontology query types

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/crud.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/link/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
- [Asana task](https://app.asana.com/0/1203007126736610/1203205825668099/f) _(internal)_
- #1255 
- #1256 
- #1257
- Slightly adjusts the `Read` trait to allow capturing lifetimes
- Use `Filter` instead of `Expression` for reading ontology types
- Convert `Path` to `Filter` for get-by-query endpoints
This is an implementation detail
All ontology-related tests, which are using the database, will pick this up
Test out different queries for the `/query` endpoints of ontology types
=> Use ontology queries in REST endpoints

packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/link_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/property_type.rs
For `Links` (and also other edge types later on), we allow resolving in both directions, from source to target and from target to source.
- preparation for [this Asana task](https://app.asana.com/0/0/1203157447338108/f) _(internal)_
- #1255 
- #1259
- Adds an enumeration for determining the join direction
- Allow joining in both direction specified by the `Path`
=> Allow specifying resolve direction on edges in compiled queries

packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/link/query.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/link.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs
Similar to the `Entity` representation, this adds the representation for `Link`s
- [Asana task](https://app.asana.com/0/1203007126736607/1203157447338099/f) (_internal_)
- [Asana task for links](https://app.asana.com/0/1203007126736610/1203157447338108/f) _(internal)_
- [Asana task for linked entities](https://app.asana.com/0/1203007126736610/1203157447338109/f) _(internal)_
- #1255
- #1259 
- #1267
- #1268
- Add representation for `Link`s without deserialization (follow-up)
- Implement common query traits on `Link` and `LinkQueryPath`
- Special case `Link <-> LinkType` joins
- Add test cases to cover the above
- Add tests for linked entities
- A bunch of tests were added to cover the cases of entities
=> Add representation for `Link` and linked entities

packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/link_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/property_type.rs, packages/graph/hash_graph/lib/graph/src/shared/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/query.rs
Similar to other deserialization functions, this adds deserialize functionality for entity queries
- [Asana task](https://app.asana.com/0/1203007126736607/1203167266370358/f) _(internal)_
- #1255 
- #1267
- #1268
- #1269
Pretty much the same changes as before: implement `Deserialize` for `EntityQueryPath`
=> Add deserialization support for entity queries

packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/link/query.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs
Supporting deserializing links, similar to entities in #1273
- [Asana task](https://app.asana.com/0/1203007126736610/1203167266370359/f) _(internal)_
- #1255 
- #1267
- #1268
- #1269
- #1273
Similar changes as in #1273, but for links
=> Add deserialization support for Link queries

packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/order_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/with_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs
For some endpoints we currently guarantee a specific ordering (e.g. for links). 
- [Asana task](https://app.asana.com/0/1203007126736610/1203157447338109/f) _(internal)_
- #1255
- #1267
- #1268
- #1269
- Adds an ordering clause 
- Allow specifying the ordering when adding a selection
A few tests were added to test transpiling
=> Allow ordering by path of query results

packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/with_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs
Having an implicit `DISTINCT` statement does not cover all cases (e.g. when joining multiple links). Also, without an `ON` clause on `DISTINCT` this is error-prone.
- [Asana task](https://app.asana.com/0/1203007126736610/1203157447338109/f) _(internal)_
- #1255
- #1267
- #1268
- #1269
- #1271
- Changes the `distinct` field to be an array of columns
- Allow specifying the `distinct` field upon adding a selection
=> Make distinct selections explicit

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/bench/benches/read_scaling/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link.rs, packages/graph/hash_graph/lib/graph/src/api/rest/link_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/link/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/link_type/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type/mod.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
The optimization implementation in Rust is finished, so the next step is to expose the new queries to the backend. To make this reviewable, this task is split up into three parts:
- #1277 (this PR)
- #1278
- #1279
- [Asana task](https://app.asana.com/0/1203007126736610/1203157447721367/f) _(internal)_
- #1267
- #1268
- #1269
- #1271
- #1272 
- #1273 
- #1228 
- #1274
- #1275
- #1276
- Temporarily rename `StructuralQuery` struct to `NewStructuralQuery` struct and make it aware of `Filter<T>`
- Copy "old" `StructuralQuery` struct to be available in the REST API to avoid adjusting the backend in this PR
- #1278
- #1279
The REST API tests will pick this change up
=> Adjust `StructuralQuery` struct to contain a `Filter<T>`

packages/libs/error-stack/CHANGELOG.md, packages/libs/error-stack/src/frame/mod.rs, packages/libs/error-stack/tests/test_frame.rs
While developing `deer` (which heavily uses `error-stack` and `Frame`s for errors), I often tried to get the current type contained in a `Frame`, before #1288 `error-stack` had a `pub(crate)` function with the same name (`type_id`). Even though `error-stack` no longer directly uses `TypeId`, I think it is still valuable to add the method for lower-level use cases outside of `error-stack`, to inspect the contained type easily.
This is entirely optional, one can also repeatedly call `Frame::is<T>()` for every expected type, but this isn't ideal, as it isn't very straightforward, nor ergonomic, or as performant as a simple lookup in a `HashSet` (or similar).
* exposes `Frame::type_id`
Yes, the newly exposed method is documented.
An additional test has been added to verify the behavior.
=> `error-stack` expose `Frame::type_id`

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/hash/api/src/graphql/resolvers/knowledge/entity/entity.ts, packages/hash/api/src/graphql/resolvers/knowledge/link/link.ts, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/api/src/model/knowledge/link.model.ts
The optimization implementation in Rust is finished, so the next step is to expose the new queries to the backend. To make this reviewable, this task is split up into three parts:
- #1277
- #1278
- #1279 (this PR)
- [Asana task](https://app.asana.com/0/1203007126736610/1203157447721367/f) _(internal)_
- #1267
- #1268
- #1269
- #1271
- #1272 
- #1273 
- #1228 
- #1274
- #1275
- #1276
- #1277
- #1278
- Manually add `Filter` as schema to the OpenAPI specs resulting in a much more robust interface in TS
- The schema and `Filter` have to be kept in sync, however, if one falls out-of-sync either the tests will fail or the methods are not available in TS
- `Path` cannot be encoded (easily) in TS as the deserialization differs from it's representation. For this, a path builder could be provided. …
=> Generate OpenAPI specs to make the usage of queries more type-safe

packages/graph/migrations/postgres/migration/1656417312397_initial.ts
This PR removes the `links` and `link_histories` tables and adds `entity_histories` to take its place.
- [Asana task](https://app.asana.com/0/1200211978612931/1203250001255253/f) _(internal)_
- https://github.com/hashintel/hash/pull/1295
- Removes `links` table
- Removes `link_histories` table
- Adds `entity_histories` table
- Adds constraints for link entity refences to have both set or none set.
=> Add entity histories table with references

.github/labeler.yml
Top level configuration files are infra-configurations. This adds these files to the `A-infra` label
- Add `*.yml` and `*.json` files
- Include other `*ignore` files
=> Tweak `A-infra` labeling to include top level configurations

packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/tests/rest-test.http
We want Entities to be able to also be links, this PR adds the foundation of that.
- [Asana task](https://app.asana.com/0/1203007126736613/1203273190678871/f) _(internal)_
- Adds the `LinkEntityMetadata` struct
- Adds the link metadata struct to the `Entity` definition, and to the `CreateEntityRequest` definition
- Updates insertion logic to pass in the link metadata
- Updates the HTTP tests to test creating a link, **and disables broken ones**
- Read operations are broken 
- References aren't correctly being persisted for entity types
- We don't validate an entity is allowed to be a link before creating it
- Fix entity type reference storing
- Fix structural querying
- Fix entity update logic
- Fix integration tests
- Fix HTTP tests
Partially covered by HTTP tests
1.  Follow the README …
=> Rework Entity to support Link Entities

codecov.yml
Currently, we have to unconditionally run coverage. With this change, the flags can be carried forward from previous commits.
- [CodeCov documentation](https://docs.codecov.com/docs/flags#recommended-automatic-flag-management)
- Sets all flags to `carryforward = true` by default
There are many options for flags (see the documentation), we probably want to further tweak the configuration but this is not required right now. [**Asana Task**](https://app.asana.com/0/1201095311341924/1203264930671957/f) (_internal_)
=> Set coverage flags to carry forward

packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
When we create the objects in the DB we store index tables about their references (e.g. this entity type references this property type). The logic to store those references when creating an entity type was broken, this PR fixes it.
- [Asana task](https://app.asana.com/0/1203007126736613/1203273212930210/f) _(internal)_
- Reintroduces the `entity_type_entity_type_references` table as it went missing
- Reimplements the entity type references logic to use the new API from the Type System crate
- We don't currently check that a referenced entity type _is_ a link entity type when used as one
- The HTTP tests should check this doesn't error
1. Checkout the branch
2. Follow instructions on how to run the HTTP tests
=> Fix references in create entity type

.github/actions/warm-up-repo/action.yml, .github/workflows/hash-backend-cd.yml, .github/workflows/sync-algolia-index.yml
Before re-enabling Playwright tests, I’ve decided to downgrade Node from v18 to v16. This slightly improves our confidence in Vercel deployments based on local tests.
When Vercel enables Node 18, we will upgrade our actions too. This will probably happen in Spring 2023, according to [Node 16 announcement](https://vercel.com/changelog/node-js-16-lts-is-now-available) (May 2022). Vercel lambdas run on top of AWS so they depend on the platform timeline.
- [Asana task](https://app.asana.com/0/1201095311341924/1203272958744356/f) _(internal)_
Check CI output
=> Use Node 16 in CI to align runtime with Vercel lambdas

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/json_schemas/entity_type.json, packages/graph/hash_graph/lib/graph/src/api/rest/json_schemas/update_entity_type.json, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/provenance.rs, packages/graph/hash_graph/lib/graph/src/store/error.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/tests/rest-test.http, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
This PR adds an endpoint for archiving an entity.
This also allowed entity updates to be re-enabled
- [Asana task](https://app.asana.com/0/1200211978612931/1203250001255275/f) _(internal)_
- Fixes entity updating (and makes use of historic table)
- Adds new DB methods for moving an entity from `entities` to `entity_histories`
- Optionally marks the entity as archived
- Adds HTTP POST endpoint for archiving
- Adds HTTP manual test for archiving
- Re-enables HTTP manual test for updates
-
1.  Run manual HTTP tests
1.  Confirm that the database has 2 entities in the latest table, `entities`, and 3 entity versions in the `entity_histories` table (1 for the update, 2 for the archival.)
=> Add entity archival endpoint

packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/lib.rs, packages/graph/hash_graph/lib/graph/src/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs
With links being entities, the logic for links in queries changes quite a lot.
This is the second part of #1314 
- [Asana task](https://app.asana.com/0/1201095311341924/1203250001255262/f) _(internal)_
- Completely rewrites the `JOIN` logic by adding a `Relation` struct, which keeps track of the joining columns and the joining table. Previously, these were a separate method, which implied a lot of edge cases. This PR could also have been done by edge cases, but the new approach is cleaner. **All edge cases for join logic are now removed!!**
- The new join logic made the implementation for incoming and outgoing links trivial: Add it back to the enumeration and implement the traits (guided by compiler)
- Fixes the unit test suite and most of the lining errors
- The unit test suite has been …
=> Support outgoing and incoming links in structural queries

packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/provenance.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/ontology.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/with_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs
with #1254 we added the provenance module, but we don't want to implement `ToSql` and `FromSql` for these types. This PR removes the implementation and makes the code explicit about that.
- [Asana task](https://app.asana.com/0/1202805690238892/1203264930671943/f) _(internal)_
=> Don't implement `ToSql` and `FromSql` for provenance records

packages/graph/hash_graph/lib/graph/src/store/postgres/context/ontology.rs
https://github.com/hashintel/hash/pull/1330 introduced a typo, which is fixed by this PR (we will have tests again, soon)
=> Fix wrong index in ontology reading

packages/libs/error-stack/README.md, packages/libs/error-stack/macros/rust-toolchain.toml, packages/libs/error-stack/rust-toolchain.toml, packages/libs/error-stack/src/lib.rs
Today's nightly Rust release is 1.67. As we plan to release a new version of `error-stack` we should test the release with the latest nightly.
=> Bump nightly version of `error-stack` to Rust 1.67

.github/scripts/rust/setup.py
Rust 1.65 released today with backtrace being stabilized. Instead of testing `error-stack` with the beta branch, we should test it with a stable release
=> Test `error-stack` with Rust 1.65

packages/libs/error-stack/src/fmt/hook.rs, packages/libs/error-stack/src/lib.rs
A previous PR introduced a debug statement, which should not exist
- Remove the `println`
- Add lints to avoid this kind of mistakes in the future
=> Remove debug statement of previous PR

packages/libs/error-stack/CHANGELOG.md, packages/libs/error-stack/Cargo.toml
`error-stack` 0.2.4 is ready to be released
- #1334 
- #1336
- Bump `error-stack` version to `0.2.4`
- Update heading in changelog
=> Bump `error-stack` to version `0.2.4`

packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/links-section.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/properties-section.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-id].page/entity-editor/types-section.tsx
- This PR adds an empty state for "properties" section on the entity page. So if an entity has no properties defined, we inform the users about this to prevent confusion.
- [Asana task](https://app.asana.com/0/1201095311341924/1203199644802780/f) _(internal)_
- [Design] (https://www.figma.com/file/gydVGka9FjNEg9E2STwhi2/HASH-App?node-id=5438%3A244733) _(internal)_
1.  Open entity editor for an entity with no properties defined (this could be achieved by DB manipulation right now)
1.  Confirm that properties section renders an empty state
=> Add empty "Properties" state on entity page

packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
This PR adds a view combining latest and historic entity entries
- [Asana task](https://app.asana.com/0/0/1203325827190276/f) _(internal)_
- Renames `entities` to `latest_entities`
- Adds a view called `entities` which is a `UNION ALL` of the two existing entities tables
- the `UNION ALL` is important to use rather than `UNION` as we do not wish to deduplicate anything.
- Querying for latest version through a structural query returns archived entries.
=> Add united view of latest and historic entities

packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/condition.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs
The lifetimes of the query compilers are suboptimal as they require the compiler to outlive the parameters.
- [Asana task](https://app.asana.com/0/0/1203324626226283/f) _(internal)_
- Make `Relation<'q>` static
- Return `'static` from default selection fields
- Remove lifetime from `PostgresQueryRecord`
- Reverse lifetime requirements for `SelectCompiler`
=> Fix lifetimes for compiler

package.json, sites/hashdev/package.json, yarn.lock
[`prism`](https://www.npmjs.com/package/prism) was added in https://github.com/hashintel/hash/pull/628 and was possibly mistaken for [`prismjs`](https://www.npmjs.com/package/prismjs). Removing this unused dependency allows us to remove resolution for `node-fetch` too. This is possible because all remaining packages depend on v2 and not v1, like `prism`.
- [Asana task](https://app.asana.com/0/1201095311341924/1203216920361646/f) _(internal)_
1.  Check CI
=> Remove prism dependency

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/conditional.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/tests/integration/postgres/links.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/rest-test.http, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
We previously split up the entities table into `entity_histories` and `latest_entities`. An `entities` view exists combining these two. The `entities` view almost behave like the table before, but it is also returning archived entities, so this PR treats getting entity versions differently.
- [Asana task](https://app.asana.com/0/1201095311341924/1203190454879638/f) _(internal)_
- Change the view to return `latest_version` depending on the table: `TRUE` for `latest_entities` and `FALSE` for `entity_histories`.
- Remove the CTE when asking for `version = "latest"` and use the new column instead
- In order to implement the above, a `Constant` expression was added to the compiler (not exposed to the API) which skips statement preparation
- Allow `entity.archived` to be set in filters, so one …
=> Support returning archived and versions of entities

packages/graph/hash_graph/Cargo.lock, packages/graph/hash_graph/lib/graph/Cargo.toml, packages/graph/hash_graph/lib/graph/src/api/rest/middleware.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs
We currently get very little log information for requests. This is especially infuriating in development when searching for bugs identified by the HTTP tests or workspace and we're unable to see which request failed, or why.
This PR adds middleware, so that when in TRACE logging we log much more information.
- [Asana task](https://app.asana.com/0/1201095311341924/1203331904553379/f) _(internal)_
- Adds the `TraceLayer` to the OpenAPI services setup, this will ensure that logs happen within tracing spans that can associate things like the route and headers of the request
- Adds custom middleware when in trace logging to log the bodies of HTTP requests/responses
- Not currently
- The `remove_link` integration test is currently broken
- The final HTTP test is currently broken
No tests …
=> Add Log middleware to Graph Rest API

packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/condition.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/select_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/where_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs, packages/graph/hash_graph/tests/rest-test.http
When joining with different columns on the same table, the table alias will be used twice.
- [Slack discussion](https://hashintel.slack.com/archives/C03F7V6DU9M/p1667569077479789) _(internal)_
- #1347
- Add a new field to `TableAlias`
- Only reuse the join statement if all fields are matching, if only the joined table is matching, not the column, a new join statement with a unique name is added
A test was added to cover the specific scenario mentioned in the slack discussion.
=> Fix deduplication to take columns into account

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/json_schemas/entity_type.json, packages/graph/hash_graph/lib/graph/src/api/rest/json_schemas/property_type.json, packages/graph/hash_graph/lib/graph/src/api/rest/json_schemas/update_entity_type.json, packages/graph/hash_graph/lib/graph/src/api/rest/json_schemas/update_property_type.json
Forgot to update the meta-schemas, so the OpenAPI client types mismatch the Type System ones
=> Hotfix meta-schemas

blocks/calculation/.eslintrc.cjs, blocks/chart/.eslintrc.cjs, blocks/drawing/.eslintrc.cjs, blocks/embed/.eslintrc.cjs, blocks/github-pr-overview/.eslintrc.cjs, blocks/header/.eslintrc.cjs, blocks/stopwatch/.eslintrc.cjs, blocks/table/.eslintrc.cjs, libs/javascript/@local/eslint-config/disable-until-fixed.cjs, libs/javascript/@local/eslint-config/legacy-base-eslintrc-to-refactor.cjs, libs/javascript/@local/eslint-config/temporarily-disable-rules.cjs, packages/graph/migrations/.eslintrc.cjs, packages/hash/api/.eslintrc.cjs, packages/hash/backend-utils/.eslintrc.cjs, packages/hash/design-system/.eslintrc.cjs, packages/hash/frontend/.eslintrc.cjs, packages/hash/integration/.eslintrc.cjs, packages/hash/playwright/.eslintrc.cjs, packages/hash/realtime/.eslintrc.cjs, packages/hash/search-loader/.eslintrc.cjs, packages/hash/shared/.eslintrc.cjs, packages/hash/task-executor/.eslintrc.cjs, sites/hashai/.eslintrc.cjs, sites/hashdev/.eslintrc.cjs, turbo.json
We enabled a set of [`@typescript-eslint/recommended-requiring-type-checking`](https://typescript-eslint.io/docs/linting/typed-linting/) rules in https://github.com/hashintel/hash/commit/6ebf9bf5c4db28b2cc7a92fe35e73429dd3a8229. Because this revealed hundreds of linting errors, some rules [were disabled in the whole repository](https://github.com/hashintel/hash/commit/6ebf9bf5c4db28b2cc7a92fe35e73429dd3a8229#diff-cfa10afa41baa07528e8f8b7dd0c9e3efc83dfadd7a2a9eecb020326225411bcR176-R183).
We want to re-enable all `@typescript-eslint/*` rules to avoid some types of bugs in the future. This PR makes the first step in this direction. Instead of disabling the selected rules everywhere, we now do this only in workspaces where they actually occur. This saves from introducing new instances of …
=> Prepare to re-enable `@typescript-eslint/*` rules

packages/libs/error-stack/src/fmt/hook.rs, packages/libs/error-stack/src/hook.rs, packages/libs/error-stack/src/lib.rs
Enable the following new lints;
* [`clippy::alloc_instead_of_core`](https://rust-lang.github.io/rust-clippy/master/#alloc_instead_of_core)
* [`clippy::std_instead_of_alloc`](https://rust-lang.github.io/rust-clippy/master/#std_instead_of_alloc)
* [`clippy::std_instead_of_core`](https://rust-lang.github.io/rust-clippy/master/#std_instead_of_core)
* [`clippy::if_then_some_else_none`](https://rust-lang.github.io/rust-clippy/master/#if_then_some_else_none)
The `*_instead_of_*` help us identify `std` and `alloc` imports which can also be imported using `core` or `alloc`. This helps during development, as Clippy will now complain in CLion (if enabled) if something has been accidentally imported over `std` in `no-std` code.
The benefit for `std` is not immediate, but using `alloc` and `core` …
=> `error-stack` warn about new lints

packages/hash/api/package.json, packages/hash/api/src/graph/system-types.ts, packages/hash/api/src/index.ts, packages/hash/api/src/model/knowledge/block.model.ts, packages/hash/api/src/model/knowledge/comment.model.ts, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/api/src/model/knowledge/org.model.ts, packages/hash/api/src/model/knowledge/orgMembership.model.ts, packages/hash/api/src/model/knowledge/page.model.ts, packages/hash/api/src/model/knowledge/user.model.ts, packages/hash/api/src/model/ontology/data-type.model.ts, packages/hash/api/src/model/ontology/entity-type.model.ts, packages/hash/api/src/model/ontology/property-type.model.ts, packages/hash/api/src/model/util.ts, packages/hash/api/src/seed-data/dev-users.ts, packages/hash/api/src/seed-data/index.ts, packages/hash/frontend/package.json, packages/hash/integration/package.json, packages/hash/shared/package.json, yarn.lock
This PR makes the GraphQL API runnable again, by removing references to the deprecated link type model, and refactoring the `Entity`/`EntityType`/`PropertyType`/`DataType` model classes.
- [Asana task](https://app.asana.com/0/1203150072758509/1203329839349722/f) _(internal)_
- [Update to the new Type System package in the Workspace](https://app.asana.com/0/1201095311341924/1203259817761581/f)
See commits.
- [Replace link types with entity types in the HASH App on the `dev/links` branch](https://app.asana.com/0/0/1203361844133477/f)
- [Fix links in the HASH App on the `dev/links` branch](https://app.asana.com/0/0/1203361844133479/f)
- [Replace uses of `entityId` in the codebase with `entityUuid` and `baseId`
](https://app.asana.com/0/0/1203361740074435/f)
- [Rework the TS/GraphQL types to …
=> Make GraphQL API runnable, basic fixes in `Entity`/`EntityType`/`PropertyType`/`DataType` model classes

packages/graph/hash_graph/rust-toolchain.toml
The same as https://github.com/hashintel/hash/pull/1395, but targeting the main branch
=> Bump toolchain to 2022-11-14 (`main`)

libs/javascript/@local/eslint-config/legacy-base-eslintrc-to-refactor.cjs, packages/hash/frontend/src/blocks/page/BlockView.tsx, packages/hash/frontend/src/blocks/page/ComponentView.tsx, packages/hash/frontend/src/blocks/page/LoadingView.tsx, packages/hash/frontend/src/blocks/page/MentionView/MentionNodeView.ts, packages/hash/frontend/src/blocks/page/MentionView/MentionView.tsx, packages/hash/frontend/src/blocks/page/clipboardTextSerializer.ts, packages/hash/frontend/src/blocks/page/collab/EditorConnection.ts, packages/hash/frontend/src/blocks/page/createFormatPlugins/util.ts, packages/hash/shared/src/ProsemirrorManager.ts, packages/hash/shared/src/createProseMirrorState.ts, packages/hash/shared/src/entityStorePlugin.ts, packages/hash/shared/src/prosemirror.ts, packages/hash/shared/src/save.ts, packages/hash/shared/src/text.ts, packages/hash/shared/src/wrapEntitiesPlugin.ts, patches/prosemirror-model+1.18.2.patch
We’ve been using
```js
import { ProsemirrorNode } from "prosemirror-model";
```
instead of
```js
import { Node } from "prosemirror-model";
```
since https://github.com/hashintel/hash/pull/202. This has allowed us to introduce an ESLint rule that requires a generic argument:
```js
❌ ProsemirrorNode // Please provide a generic to avoid implicit `any`
✅ ProsemirrorNode<Schema>
```
Keeping the original type name would trigger false-positive errors for DOM `Node` type.
With ProseMirror typings updated in #1359, `ProsemirrorNode` is no longer generic. We’ve removed custom linting rules and no longer benefit from a customised type name. Replacing `ProsemirrorNode` back to `Node` reduces the patch for `prosemirror-model` and also makes our codebase more aligned with ProseMirror standards.
- …
=> Replace custom `ProsemirrorNode` type with standard `Node`

.github/workflows/rust.yml
Dev-branches require a review so they are special-cased. In order to profit from caching and upload proper coverage support, the CI should run on pushes to  `dev/**` branches as well.
=> Run Rust CI on dev-branches

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/tests/integration/postgres/entity.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
We currently don't have a way to update link ordering of entities. This exposes `leftOrder` and `rightOrder` in the `updateEntity` endpoint.
- [Asana task](https://app.asana.com/0/1202805690238892/1203384069111429/f) _(internal)_
- Split `left_order` and `right_order` from `LinkEntityMetadata`
- Add logic for updating the orders:
- Update if, and only if, the order previously existed and a new order was passed
- error otherwise
- Expose functionality to the OpenAPI specs
=> Support link ordering in updateEntity endpoint

packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs
Inner joins with the column being joined is `NULL`, the result is empty. This is fine for the majority of cases as the result of the query is expected to be empty, but this is not the case for more compilcated queries like "Give me entities which either has the left entity being bar **or** the name property being baz".
- [Asana task](https://app.asana.com/0/1202805690238892/1203324626226299/f) _(internal)_
- https://github.com/hashintel/hash/pull/1387#discussion_r1020401037
- #1407
- Add a `nullable()` method to `Column`
- Decide on join type depending on `nullable()` return value
=> Use outer joins when joining on nullable columns

packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/condition.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/conditional.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/order_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/select_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/where_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/with_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs
For further features, `AliasedColumns` without an alias (which is already a contradiction) needs to be treated specially when generating join expressions. Always requiring an alias makes this easier and less error-prone.
- [Asana task](https://app.asana.com/0/1203271043333970/1203363980182352/f) _(internal)_
- Make `alias` non-optional in `AliasedTable` and `AliasedColumn`
- #1407 
Using an alias in the tests is annoying but a fair trade-off for more robust code. This is the majority of the diff of this PR.
=> Make `alias` non-optional in `AliasedTable` and `AliasedColumn`

packages/graph/hash_graph/lib/graph/src/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/conditional.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs, packages/graph/hash_graph/tests/rest-test.http
Supports the "links" query in entity types
- [Asana task](https://app.asana.com/0/1202805690238892/1203348428860462/f) _(internal)_
- #1407
- #1411
- Re-add `Links` variant to `EntityTypeQueryPath`
- Support parsing `"links"`
- Add special case for `"links"` and `"inheritsFrom"` to distinguish between different entity type references
- Add test cases for the above
The `EntityTypeQueyrPath` documentation were adjusted
We always never use the reference table to get all referenced entity types. If we'd add distinct reference tables, both, this code and the subgraph query would be easier.
Test cases were added
=> Add support for "links" queries in entity types

packages/graph/hash_graph/bench/benches/read_scaling/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/seed.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs
To allow comparing benchmarks between `main` and `dev/links`, we want more data to be queried.
This adds the same functionality as #1431, but targeting the `dev/links` branch
- [Asana task](https://app.asana.com/0/0/1203384240596317/f) _(internal)_
- Update entity batch insertion method to support links
- Seed links based on existing entities
[Add new benchmarks to `main`](https://app.asana.com/0/0/1203384240596318/f) (_internal_)
=> Seed links in benchmarks (`dev/links`)

packages/graph/hash_graph/lib/graph/src/shared/subgraph/edges/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/vertices/mod.rs
When combining intermediary HashMaps, we were using the extend trait, but this doesn't use `extend` in a nested fashion, which means we were dropping vertices and edges that have the same BaseId. This fixes it
=> Fix nested hashmap extension

packages/graph/hash_graph/lib/graph/src/shared/subgraph/depths.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/edges/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/vertices/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs
We implement `Extend` for `Subgraph` and we were collecting into a `Vec<Subgraph>` before combining them. We should just be able to directly collect into one `Subgraph`, this PR makes it possible.
=> Don't collect into intermediary collection of subgraphs

packages/graph/hash_graph/bench/benches/read_scaling/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/mod.rs, packages/graph/hash_graph/bench/benches/representative_read/seed.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs
Adds two new benchmarks testing two different structural queries with various resolve depths. This is the same implementation as in #1436, but targeting the `dev/links` branch
- [Asana task](https://app.asana.com/0/0/1203384240596319/f) _(internal)_
- #1432
- Adds two new benchmarks:
- Get entity specified by a property
- Get link to an entity, where the entity has a specified property
- Varies over the resolve depth of these filters
=> Add more benchmarks for structural queries (`dev/links`)

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/bench/benches/representative_read/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/edges/edge.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/edges/kind.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs, packages/hash/subgraph/src/types/edge.ts, packages/hash/subgraph/tests/compatibility.test/map-edges.ts
We were intermittently referring to things as LeftEntity and LeftEndpoint, RightEntity and RightEndpoint. This tries to clarify between them
=> Rename "endpoint" in edges

packages/graph/hash_graph/lib/graph/src/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/query/mod.rs, packages/graph/hash_graph/tests/rest-test.http
When joining tables, the same row may be selected multiple times, but some methods require exactly one row to be returned.
This PR changes the database query to select distinctly on the primary keys.
- [Asana task](https://app.asana.com/0/1202805690238892/1203358665695497/f) _(internal)_
- Add required methods to the `OntologyPath` trait
- Replace `Compiler::with_default_selection` to pick the columns manually
=> Select types returned from Graph distinctly

packages/hash/subgraph/src/shared/type-system-patch.ts, packages/hash/subgraph/src/stdlib/element/data-type.ts, packages/hash/subgraph/src/stdlib/element/entity-type.ts, packages/hash/subgraph/src/stdlib/element/property-type.ts, packages/hash/subgraph/tests/compatibility.test/map-edges.ts, packages/hash/subgraph/tests/compatibility.test/map-vertices.ts
We haven't unified the type system packages yet, and the subgraph lib is likely to be used in the frontend and backend. To avoid messing around with conflicting WASM definitions and such, we are just patched the handful of functions we need to use at the moment.
- Unify the packages [Asana task](https://app.asana.com/0/1201095311341924/1202923896339225/f
) _(internal)_
=> Disable type system package in subgraph lib

packages/hash/api/codegen.yml, packages/hash/frontend/codegen.yml, packages/hash/integration/codegen.yml, packages/hash/shared/codegen.yml, packages/hash/subgraph/src/stdlib/edge/link.ts, packages/hash/subgraph/src/stdlib/element/entity.ts, packages/hash/subgraph/src/stdlib/roots.ts, packages/hash/subgraph/src/types/element.ts, packages/hash/subgraph/src/types/vertex.ts
We have an old `Entity` typedef lying around in GraphQL. Removing it would be quite difficult to do now (although we intend to very soon). We were using `EntityWithMetadata` as a temporary alias for the actual up-to-date `Entity` type in GraphQL. Unfortunately, importing `Entity` from the subgraph package caused the generated ts types file to be invalid due to name conflicts on the import.
This PR temporary renames `Entity` in the subgraph package to `EntityWithMetadata` for consistency
=> Codegen Hotfix

packages/libs/deer/src/error/mod.rs, packages/libs/deer/src/error/value.rs, packages/libs/deer/src/lib.rs, packages/libs/deer/src/number.rs
The previous PR (#1375) created the types for all built-in errors inspired by `serde::ser::Error`. This PR adds them to the default implementation of functions in `Visitor` and `Deserializer`. Additionally, this PR adds a new error `MissingError`, which is a "child" of the `ValueError` and is only emitted during `visit_none` (unexpected missing value)
- [Asana task](https://app.asana.com/0/0/1203363157432059) _(internal)_
* #1375
=> `deer` use new built-in errors in visitor and deserializer defaults

packages/hash/shared/src/blocks.ts
The goal of this PR is to fix Playwright CI. This is done by supporting `null` in Block Schemas.
- [Asana task](https://app.asana.com/0/1203301853897838/1203409678848738/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1669044565345679) _(internal)_
- https://blockprotocol.hashai.workers.dev/blocks/jtewright/latest/block-schema.json
- Schema remains not fully validated (see pre-existing comment next to diff).
=> Handle `null` in Block Schema

packages/hash/api/src/graphql/resolvers/file/fileUrlResolver.ts, packages/hash/api/src/graphql/resolvers/taskExecutor/index.ts, packages/hash/api/src/task-execution/index.ts
The task-executor was still using the old DbAdaptor API, this converts the code as necessary to satisfy TSC. Unfortunately it is still broken, as the code relies on taking JSON schema from REST APIs, and that JSON schema is no longer a valid Entity Type (and hasn't been for a long time). This has been captured in the code.
This also means that TSC is now passing:
=> Fix TSC for Task-executor

packages/hash/subgraph/src/stdlib/roots.ts, packages/hash/subgraph/src/types/subgraph.ts, packages/hash/subgraph/tests/compatibility.test.ts, packages/hash/subgraph/tests/compatibility.test/map-roots.ts
We can improve the accessor of `subgraph.roots` by some more massaging of the generic type
- TSC
1.  `yarn workspace @hashintel/hash-subgraph lint:tsc`
=> Improve generic typing of subgraph roots

.github/renovate.json
This PR enables Dependency Dashboard with pre-approval which would be interesting to try. It also unsets `stabilityDays": 3` as discussed. `automerge` has already been enabled, I've just moved it up.  
 
- [Asana task](https://app.asana.com/0/1203301853897838/1203414492513792/f) (internal)
- [Slack link](https://hashintel.slack.com/archives/C02TWBTT3ED/p1669137989160599) (internal)
- [Dependency dashboard docs](https://docs.renovatebot.com/key-concepts/dashboard/)
- https://github.com/blockprotocol/blockprotocol/pull/782
=> Enable Renovate Dependency Dashboard

packages/libs/error-stack/Cargo.toml, packages/libs/error-stack/src/fmt/hook.rs, packages/libs/error-stack/src/frame/frame_impl.rs, packages/libs/error-stack/src/report.rs, packages/libs/error-stack/src/serde.rs
It's not required to rely on a recent version of `serde`, however, we require `anyhow@1.0.65`.
- set minimum dependency on `serde` to `1.0.0`
- set minimum dependency on `anyhow` to `1.0.65`
- Avoid relying on `String: Serialize`
- Drive-by: Remove unneeded `#[repr(transparent)]` or hide it
=> Avoid being too conservative with dependencies

packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/query/filter.rs
We require incoming link edges to be present in the subgraph.
- [Asana task](https://app.asana.com/0/0/1203426166281269/f) _(internal)_
- [Slack discussion](https://hashintel.slack.com/archives/C03F7V6DU9M/p1669200140528029) _(internal)_
- #1474
- Add a predefined filter to return incoming links by the right entity edition id
- Add edges and linked entities based on that filter
None
Run the REST endpoint tests and check for the correct edges to be present when querying a person-entity
=> Return incoming links by default

packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs
With b4abb8c88b70c4b8242abb730bdb7e354abc6acc the seeding logic of benchmark was broken, this is a fix for that
=> Fix benchmark seeding logic

packages/hash/frontend/src/blocks/page/MentionView/MentionDisplay.tsx, packages/hash/frontend/src/blocks/page/createSuggester/MentionSuggester.tsx, packages/hash/frontend/src/blocks/page/createSuggester/createSuggester.tsx
#1495 partly fixed mentions, but it turns out there were more breakages (or previous oversights). This PR fixes the mentions menu and improves typings on a number of props.
Now when clicking on a user mention, it links to the associated entity editor page, and when clicking on a page mention it correctly redirects.
See commits, small PR 
No
We currently query for all entities quite a lot in the process of rendering a page. It takes many seconds for the users to populate the mentions drop-down (possibly because resolving a user always also resolves its orgs)
None
1.  Run the app
1.  Type "@" on a page
Demo'd live, but:
=> Fix mentions properly

packages/graph/hash_graph/lib/graph/src/shared/subgraph/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs
As a follow-up of #1491 this also avoids unnecessary lookups across multiple roots.
With these changes, the performance was increased by up to 50% (as many queries can be avoided).
- [Asana task](https://app.asana.com/0/1202805690238892/1203358665695493/f) _(internal)_
- ~~#1491~~ 
- Reuse the same subgraph for multiple roots
- Remove `Extend` and `Default` implementation of `Subgraph`
=> Reuse subgraph from previous iterations to avoid unnecessary lookups

packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs
When the resolve depth is high enough, the entities may get resolved multiple times, this solves this issue.
This change speeds up the performance by about 50%.
- [Asana task](https://app.asana.com/0/1202805690238892/1203358665695493/f) _(internal)_
- #1488 
- ~~Insert edges before resolving the edge~~ (applied in #1488)
- Only resolve entities if the edge is unresolve
=> Avoid multiple queries for the same row

packages/hash/docker/api/prod/Dockerfile, packages/hash/docker/frontend/prod/Dockerfile
After the `dev/links` merge we have a new `subgraph` monorepo dependency which we forgot to add to the dockerfiles. The production docker-compose is currently broken without this change. I drive-by fixed caching issues with nextjs because of lack of permisisons.
- [Asana task](https://app.asana.com/0/1203312852763953/1203449369348564/f) _(internal)_
=> Make dockerfiles build

packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs
The edges based on the root vertices are not added to the subgraph, this fixes that bug.
- Don't insert the vertices before the resolving logic (results in an `DependencyStatus::DependenciesUnresolved` status instead of `DependencyStatus::Unknown`)
- Rename functions to better reflect this
- Make `GraphResolveDepths` required for dependency maps
=> Fix edges not generated for root vertices

packages/hash/api/src/graphql/resolvers/knowledge/entity/entity.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/knowledge-shim.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolAggregateEntities.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolGetEntity.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/ontology-types-shim.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolAggregateEntityTypes.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolAggregatePropertyTypes.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetEntityType.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/ontology/useBlockProtocolGetPropertyType.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-uuid].page.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-uuid].page/shared/use-create-new-entity-and-redirect.ts, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/property-type-form.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/use-entity-type-entities.tsx, packages/hash/frontend/src/pages/[account-slug]/types/new/entity-type.page.tsx, packages/hash/frontend/src/pages/entity-editor.page.tsx, packages/hash/shared/src/util.ts
Previously we selected "sensible" defaults for the hooks. It makes sense to expose the GraphResolveDepths to them so consumers can be opinionated if they want. This leads to substantial performance improvements for the frontend.
This work also discovered the bug fixed in #1530.
It also fixes bugs in the application where `Org`s weren't appearing in the workspace switcher.
- [Asana task](https://app.asana.com/0/1203312852763953/1203458586282756/f) _(internal)_
See commit list please
No
The Subgraph has started returning multiple versions of linked entities. We will fix this as part of the on-going versioning changes, but because the queries aren't actually temporal based at the moment (you can't ask for the graph at a given timestamp), it is easier to manually patch in a single place in …
=> Allow setting depths in BP hooks

.github/renovate.json
This PR extends the scope of Renovate, which now covers all dependencies in the repo. As before, new PRs are not created automatically and we need to approve them via Dependency dashboard (#1481) first.
- [Asana task](https://app.asana.com/0/1203312852763953/1203464390652052/f) _(internal)_
- https://github.com/blockprotocol/blockprotocol/pull/799
I’ve removed some package rules as they are no longer needed. We extend from a preset named [`config:base`](https://docs.renovatebot.com/presets-config/#configbase) which in turn includes [monorepo presets](https://docs.renovatebot.com/presets-monorepo/). This means that dependencies within well-known monorepos are grouped together without us having to configure anything. For example, `next` is upgraded with `@next/bundle-analyzer` in a single …
=> Reconfigure Renovate (cover all dependencies)

packages/libs/error-stack/CHANGELOG.md, packages/libs/error-stack/Cargo.toml, packages/libs/error-stack/Makefile.toml, packages/libs/error-stack/src/fmt/hook.rs, packages/libs/error-stack/src/fmt/mod.rs, packages/libs/error-stack/src/hook.rs, packages/libs/error-stack/src/lib.rs, packages/libs/error-stack/tests/test_debug.rs
While exploring #1399 we found the [spin crate](https://crates.io/crates/spin), which implements a `no-std` equivalent for `std::sync` types, like `RwLock` based on spin locks. This PR adds a new feature, `hooks`, which - if enabled - will replace the `RwLock` with the spin variant.
Note: while we expect a majority of calls to be read-only, there's still a chance of priority inversion, this is why if both `std` and `hooks` features are enabled, we will instead use the `std` `RwLock`.
> Must read for spin locks and their application: https://matklad.github.io/2020/01/02/spinlocks-considered-harmful.html
I consider using a spinlock okay for `error-stack` hooks, as we expect hooks to only be initialized very, very infrequently, and most operations are reads. A read is simply a `fetch_add` + …
=> `error-stack` support `Debug` hooks in `no-std` contexts

packages/hash/frontend/src/pages/[account-slug]/shared/white-card.tsx
This PR ensures that the Next JS link component is used when redirecting from an entity to it's entity type in the entity editor. This prevents a white screen from flashing between the pages, as the page isn't fully refreshed.
- [Asana task](https://app.asana.com/0/1203312852763953/1203468350364504/f) _(internal)_
See commits.
Not that I'm aware of.
- sometimes when clicking on the entity's type, the user is redirected to the create new entity type page
None, tested manually.
1. Log in to the frontend
2. Go to the entity editor
3. Click on it's type
4. Ensure the page is not refreshed during the page transition
Before:
https://user-images.githubusercontent.com/42802102/205073739-75d044a0-fa8a-4dd7-ba28-070d4a5975f8.mov
After:
https://user-images.githubusercontent.com/42802102/205073245-48d …
=> Use `next/link` to redirect to the entity's type in the entity editor

packages/hash/frontend/src/components/hooks/useAuthenticatedUser.ts, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-uuid].page/new-entity-page.tsx, packages/hash/frontend/src/pages/[account-slug]/entities/[entity-uuid].page/shared/use-create-new-entity-and-redirect.ts, packages/hash/frontend/src/pages/[account-slug]/entities/new.page.tsx, packages/hash/frontend/src/pages/[account-slug]/new/entity.page.tsx, packages/hash/frontend/src/pages/[account-slug]/new/types/entity-type.page.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/[entity-type-id].page.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/entity-type-tabs.tsx, packages/hash/frontend/src/pages/index.page.tsx, packages/hash/frontend/src/shared/layout/layout-with-header/actions-dropdown.tsx, packages/hash/frontend/src/shared/layout/layout-with-sidebar/account-entity-type-list.tsx, packages/hash/frontend/src/shared/layout/layout-with-sidebar/account-entity-type-list/entity-type-menu.tsx
Follow up to https://github.com/hashintel/hash/pull/1492 to improve some of the flow around the new entity type stuff (and updating routes) 
- N/A
- `useAuthenticatedUser`:
- Removed `onUserAuthenticated` as no way to implement it properly with current authentication state management
- Kratos fetching is updated to not refetch it for every use of the hook (this fixes a bug)
- Routes for new pages updated – see https://hashintel.slack.com/archives/C022217GAHF/p1669774923256599 (internal)
- `useCreateNewEntityAndRedirect` is substantially updated
- Instead of calling `useAuthenticatedUser` itself, the callback it returns now takes the user. This is because it's hard to reason about stale closures:
- The caller of `useCreateNewEntityAndRedirect` isn't supposed to use its callback until the …
=> New entity type flow improvements (follow up)

packages/hash/frontend/src/blocks/page/MentionView/MentionDisplay.tsx, packages/hash/frontend/src/blocks/page/createFormatPlugins/MarksTooltip.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/use-entities-table.tsx
A few fixes to things I noticed while playing with the app, in the order they appear in the diff:
**Before**
**After**
---
**Before**
**After**
---
**I'm not sure why the root of the subgraph was a `Block` entity?!**
**Before**
**After**
=> Frontend fixes: Formatting buttons. User mention caching. Entity labels

packages/hash/frontend/src/pages/[account-slug]/types/entity-type/expected-value-chip.tsx, packages/hash/frontend/src/pages/[account-slug]/types/entity-type/property-expected-values.tsx
This PR adds the "Array" chip to expected values to properties in the entity type editor (the chips will be expanded on in the future, this is just a placeholder https://hashintel.slack.com/archives/C022217GAHF/p1670006397135869)
It also fixes this [bug](https://github.com/hashintel/hash/pull/1579#discussion_r1038417680) by putting each chip on its own line.
=> Property type array expected value badges in entity type editor

packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/property_type.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/edges/kind.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/query.rs, packages/graph/hash_graph/lib/graph/src/store/crud.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/condition.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/where_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/statement/select.rs, packages/graph/hash_graph/lib/graph/src/store/query/filter.rs
Currently, we use `DataType`, `PropertyType`, `EntityType`, and `Entity` for the query filters. This is inconsistent, as `Entity` contains metadata, the ontology types does not.
To deduplicated a very big chunk of code in the dependency resolution, those should be unified, thus, this PR is using `DataTypeWithMetadata` etc. in `Filters` instead. This also simplifies the `Read` trait in general to allow less bounds to be used in callers
- [Asana task](https://app.asana.com/0/0/1203444301722130/f) _(internal)_
- #1493
- Simplify `Read` trait to always use `Filter`
- Consistently use the type containing the `MetaData` in `Filters`
=> Simplify `Read` trait and consistently use `*WithMetadata` for trait filters

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs, packages/graph/migrations/postgres/migration/1656417312397_initial.ts, packages/hash/api/src/graphql/resolvers/knowledge/entity/entity.ts, packages/hash/api/src/graphql/typeDefs/knowledge/entity.typedef.ts, packages/hash/api/src/model/knowledge/entity.model.ts, packages/hash/api/src/model/knowledge/linkEntity.model.ts, packages/hash/api/src/model/knowledge/page.model.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/knowledge-shim.ts, packages/hash/frontend/src/components/hooks/blockProtocolFunctions/knowledge/useBlockProtocolUpdateEntity.ts, packages/hash/frontend/src/graphql/queries/knowledge/entity.queries.ts, packages/hash/subgraph/src/types/element.ts
Links have been designed with the hope of supporting bi-directional links in the future. As such, a link might need an order (list index) for both directions. We had called this `left_order` and `right_order` to avoid accidental implication of order with `source` and `target`. The choice of the order names was deemed somewhat confusing, and `left_to_right_order` and `right_to_left_order` seems to be more explicit, albeit slightly wordy.
This PR renames all occurrences (I believe). It involves changing the DB so the volume will need to be wiped in between runs.
- [Asana task](https://app.asana.com/0/1201095311341924/1203401244553571/f) _(internal)_
See commits
- At the moment these fields aren't captured in standalone docs, however doc comments and such should have been successfully …
=> Rename link order fields

packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/subgraph/vertices/vertex.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
We currently look up each type (knowledge + ontology) twice, this reduces the amount of lookups by using the entry API. Also, don't traverse the ontology types (on the Rust side, not on PSQL) if not needed.
Additionally, this avoids iterating through the link mappings twice.
=> Avoid unnecessary lookups and traversals in Subgraph generation

packages/graph/migrations/postgres/migration/1656417312397_initial.ts
Initial PR to implement temporal versioning.
This adjusts the database to store entities in a bi-temporal table: decision-time and system-time.
- [Asana task](https://app.asana.com/0/1203363157432081/1203444301722131/f) _(internal)_
- Split the `entities` table into three: `entity_ids`, `entity_versions`, and `entity_editions`
- `entity_ids` holds the identifier for an entity and parameters, which must not change over the lifetime of an entity (left/right entity id for links)
- `entity_editions` holds the data of the entities, uniquely identified by `entity_edition_id`
- `entity_versions` holds the bi-temporal logic and points to the entity editions
- The `entities` view were adjusted to join the three table from above
- Two functions were created to appropriately handle the creation and …
=> Create database structure for temporal versioning

packages/hash/frontend/src/middleware/return-types-as-json.ts, packages/hash/frontend/src/middleware/return-types-as-json/generate-query-args.ts
I introduced middleware in #1612 without realising that the [NextJS Edge runtime](https://nextjs.org/docs/api-reference/edge-runtime) does not support how it uses WASM. 
While there are ways around this (e.g. using the `experimental-edge`), it seems simplest just to replace the one function requiring WASM with something local.
This also makes a driveby change [suggested](https://github.com/hashintel/hash/pull/1612#discussion_r1043182381) in that PR. 
1.  Check that the requests work as they should
=> Remove validateVersionedUri from json type middleware

packages/graph/migrations/postgres/migration/1656417312397_initial.ts
The `owned_by_id` is required for identifying an entity, so it *must* be included in the GiST.
- [Asana task](https://app.asana.com/0/0/1203505325130332/f) _(internal)_
=> Temporal versioning: Fix `owned_by_id` not included in GiST

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/error.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/tests/rest-test.http, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
Similar to #1604, this PR uses the `update_entity` method in SQL to update an entity.
- [Asana task](https://app.asana.com/0/1203363157432081/1203464975244303/f) _(internal)_
- #1604 
- Use the SQL function `update_entity` to ... update an entity 👁️ 👁️ 
- Remove unused error structs
- Fallback to get-entity + update entity for archiving. 
The fallback in the `/entities/archive` endpoint will result in data races if the same entity is updated at the same time, but I don't consider this as an issue as I'm going to remove this function as part of [this Asana task](https://app.asana.com/0/0/1203444301722133/f) _(internal)_ and the chance, that this will happen is very very unlikely. If it would happen, there would still be an error.
=> Temporal versioning: Support updating of entities

packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/shared/identifier/knowledge.rs, packages/graph/hash_graph/lib/graph/src/shared/identifier/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/condition.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/conditional.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/expression/where_clause.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs, packages/graph/hash_graph/lib/graph/src/store/query/filter.rs, packages/graph/hash_graph/lib/graph/src/store/query/mod.rs, packages/graph/hash_graph/tests/rest-test.http, packages/graph/migrations/postgres/migration/1656417312397_initial.ts
Adjusts the query logic for the `Read` methods and the corresponding `EntityQueryPath` to allow querying of entities as before.
- [Asana task](https://app.asana.com/0/0/1203505325130329/f) _(internal)_
- #1624 
- Replaces `EntityQueryPath::Version` with `EntityQueryPath::LowerTransactionTime` (to be removed as part of [Adjust structural queries for temporal versioning](https://app.asana.com/0/0/1203491211535116/f) (_internal_))
- Adds `EntityQueryPath::{EditionId, DecisionTime, TransactionTime}`
- Adds `Lower`, `Upper`, and `Now` functions
- Uses `Now` function as `"latest"` special case
- Adjust `Read` implementation
- Sets the correct filter for getting archived entities
=> Temporal versioning: Support selecting of entities

packages/graph/hash_graph/bench/benches/read_scaling/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/seed.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs
The database layout changed a lot with temporal versioning. The benchmarking code requires a special seeding to insert many entities at once, so this PR adjusts that seeding.
- [Asana task](https://app.asana.com/0/1203363157432081/1203505325130328/f) _(internal)_
- #1630 
- Rewrites the seeding logic for benchmarks by using temporary tables to create the autogenerated identifiers
=> Temporal versioning: Fix benchmark seeding logic

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/shared/identifier/knowledge.rs, packages/graph/hash_graph/lib/graph/src/store/query/filter.rs
This exposes the opaque `EntityRecordId` to be available for queries.
- [Asana task](https://app.asana.com/0/0/1203505325130368/f) _(internal)_
=> Expose `EntityRecordId` as `"recordId"`

packages/graph/hash_graph/Cargo.lock, packages/graph/hash_graph/bench/Cargo.toml, packages/graph/hash_graph/bench/benches/read_scaling/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/seed.rs, packages/graph/hash_graph/bench/benches/util.rs, packages/graph/hash_graph/bin/hash_graph/Cargo.toml, packages/graph/hash_graph/lib/graph/Cargo.toml, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/context/ontology.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/tests/integration/postgres/data_type.rs, packages/graph/hash_graph/tests/integration/postgres/entity_type.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/graph/hash_graph/tests/integration/postgres/property_type.rs
https://github.com/blockprotocol/blockprotocol/pull/831 exposed the representation for ontology types and removed the hard dependency on `serde_json`. Instead, `serde` is used to (de)serialize from/to the representation, which than can be converted to to the validated representation. This PR adjust the Graph API to use the new changes
- [Asana task](https://app.asana.com/0/1203363157432084/1203449432963809/f) _(internal)_
- Update `type_system` crate
- Add `OntologyType` trait to abstract over ontology type and representation
- Use `TryFrom<repr::*>` over `TryFrom<Value>`
=> Update to new type system revision and adjust Graph code 

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/lib/graph/src/api/rest/data_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity.rs, packages/graph/hash_graph/lib/graph/src/api/rest/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/property_type.rs
In order to notify the TS backend, that the old endpoints are going to be removed, we annotate them with a `deprecated` attribute
- [Asana task](https://app.asana.com/0/1201095311341924/1202979057056095/f) _(internal)_
=> Deprecate old endpoints

packages/graph/hash_graph/lib/graph/src/store/query/filter.rs
The version and the base URI are re-used in some places. The base URI filter is also required for a follow-up PR.
- [Asana task](https://app.asana.com/0/1203363157432084/1203449432963809/f) _(internal)_
- #1667 
- Add `Filter::for_base_uri`
- Add `Filter::for_version` (implementation detail)
- Reuse the above functions in other filters
=> Clean up predefined filters

packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/query/filter.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs
To read data from the store into the subgraph in a generic context, a filter for `Record`s has to be created. This adds a small function to allow creation for filters used in a structural query to filter by a specific edition id.
- Part of [this Asana task](https://app.asana.com/0/1203363157432084/1203444301722127/f) _(internal)_
- #1679 
- #1677
=> Allow filter creation from records

packages/graph/hash_graph/lib/graph/src/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/crud.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs
Deduplicates the logic to return a record from the subgraph or read it from the store and store it in the subgraph.
- [Asana task](https://app.asana.com/0/1203363157432084/1203444301722127/f) _(internal)_
- #1677 
- #1679 
- #1680 
Please see the (short) list of commits
The whitespace changes should be hidden as large parts of this PR are indentation changes
=> Deduplicate dependency resolution - part 1

packages/graph/hash_graph/lib/graph/src/shared/identifier/mod.rs, packages/graph/hash_graph/lib/graph/src/store/crud.rs, packages/graph/hash_graph/lib/graph/src/store/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs
The next step towards deduplicating of dependency resolution. It's required, that the insertion of records is aware of the `Record` type being inserted, so the deduplicated resolution can just call those function.
- [Asana task](https://app.asana.com/0/1203363157432084/1203444301722127/f) _(internal)_
- #1677 
- #1679 
- #1680 
- #1682 
- Add method to `Record` to allow inserting of themself to the provided subgraph
- Added a similar method, but add it as a root as well
- Use the above functions to simplify dependency resolution logic
- Drive-by: Simplify some trait bounds
=> Deduplicate dependency resolution - part 2: Generalizes the subgraph insertions

packages/hash/docker/api/prod/Dockerfile, packages/hash/docker/frontend/prod/Dockerfile, packages/hash/docker/search-loader/prod/Dockerfile
#1652 broke the dockerfiles for running HASH within a single docker-compose. This PR fixes the copying to allow building properly.
- [Asana task](https://app.asana.com/0/1201095311341924/1203393349856541/f) _(internal)_
=> Fix dockerfiles for new codegen approach

apps/hashdotai/resources/glossary/entities.mdx
Copy update and escaping of rogue characters.
=> Fix unescaped chars in `entities` glossary entry

packages/hash/frontend/src/pages/[shortname]/types/entity-type/[entity-type-id].page/definition-tab/shared/type-form.tsx
#1705 updated the name of a param for a route, but missed an occurence of the old name. This PR fixes it.
=> Fix expected query param account-slug

packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs
We added a few new `EntityQueryPath` variants recently, which had to be documented
- [Asana task](https://app.asana.com/0/1203363157432087/1203505325130325/f) _(internal)_
Adds doc-strings to newly added query path parameters
=> Add documentation to newly added query path variants

packages/libs/error-stack/CHANGELOG.md, packages/libs/error-stack/src/error.rs, packages/libs/error-stack/src/lib.rs, packages/libs/error-stack/src/report.rs, packages/libs/error-stack/tests/test_compatibility.rs, packages/libs/error-stack/tests/test_conversion.rs, packages/libs/error-stack/tests/ui/into_report.rs, packages/libs/error-stack/tests/ui/into_report.stderr
It's currently hard to deal with `Report` when an `Error` is required. This PR adds conversions from `Report` to `Error`.
- resolves https://github.com/hashintel/hash/issues/1746
- Add `Report::into_error` to convert `impl Error`
- Add `Report::as_error` to return `&impl Error`
- Add `From` implementation of `Report` for `Box<dyn Error>` (+ `Send` and/or `Sync`)
The changelog was changed to reflect these changes
Three new tests were added:
- A UI test to make sure, that `into_report` cannot be called on `Result<T, Report<C>>`
- Two tests to check the new methods/trait implementation by converting a `Report` to `Error` and ensure, that the provided values are still accessible
=> Allow conversion from `Report` to `Error`

packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/query/filter.rs
We encountered an issue when updating the same ontology type more than once. This is because accidentally, we're trying to read all ontology types of a specific type base URI instead of only the latest.
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1672854529471029)  by @nathggns _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1672673003673429) by @Alfred-Mountfield _(internal)_
- Add pre-defined filter to return the latest an ontology type by Base URI
- Use the newly added filter in the update method
While this is a straightforward fix, tracking it down was challenging as the error was not reported back from the Graph API. @thehabbos007 tracked down that issue, but we don't have a proper solution yet. This PR fixes the issue on the …
=> Fix updating the same ontology type resulting in an error

packages/graph/hash_graph/lib/graph/src/shared/identifier/time/mod.rs
We don't want to use `'infinity'` or `'-infinity'` in the database but unbounded bounds instead. In the case an infinity-value is in the database, this will fail to deserialize. This PR falls back to an unbounded bound and emits a warning instead of erroring.
- [Slack thread](https://hashintel.slack.com/archives/C03F7V6DU9M/p1672930907628839) _(internal)_
=> Emit warning when finding an `'infinity'` or `'-infinity'` value

packages/hash/subgraph/src/stdlib/edge/entity-type.ts, packages/hash/subgraph/src/types/edge/outward-edge-alias.ts
This expands the `stdlib` to provide a helper to get all `PropertyType`s referenced by a given `EntityType` by utilising the `Edges` of a `Subgraph`.
- [Asana task](https://app.asana.com/0/1203363157432094/1203662893654909/f) _(internal)_
N/A
See commits, tiny diff
Not to my knowledge
We have a slightly unclear strategy about when to return errors for missing things
Propagate this to the WIP new subgraph package in the Block Protocol
None
We don't currently have tests for the subgraph library, if you want to see it in action you'll need to modify the existing code and use it somewhere
=> Add helper function to get property types referenced in an entity type

packages/hash/frontend/src/pages/[shortname]/entities/[entity-uuid].page/create-entity-page.tsx
This PR fixes a bug caused app crashing when users try to update any value cell on new entity page (draft / not-published).
1.  Create an entity draft
1.  Change a value cell
2. Confirm that app is not crashing
=> Use version object on draft entity subgraph to prevent crash 

packages/hash/api/src/graphql/resolvers/task-executor/airbyte-read.ts, packages/hash/api/src/graphql/resolvers/task-executor/generation.ts
Type Generation could fail on ingest of some data streams (notably some of GitHub's) due to some edge-cases that weren't handled.
Furthermore, the previous code treated all occurrences of a specific key (e.g. `id`) within a stream as being the same property type. This PR changes that as that was causing more circular dependencies (which are often uncommitable due to a lack of transactions) and was misleading, as in an object like this:
```json5
{
"id": ...,
"someObject": {
"id": ...,
}
}
```
the second `id` field is probably referring to the `id` of `someObject`, which is different from the one in the root. This PR takes that into account and instead would generate a property type for the given path `someObject.id`.
It also has identified a number of other edge-cases, which have been …
=> Handle more edge cases in type generation

packages/libs/deer/README.md
It seems the [Deserializer with Parser](https://github.com/hashintel/hash/tree/main/packages/libs/deer#deserializer-with-parser) section has some repeated text.
Replaces the first repeated paragraph with the second one.
I'm also guessing that inside `<details>` there's a sample error message missing, something like `malformed input, missing "}"` perhaps?
=> Improve `deer` README phrasing

packages/graph/hash_graph/lib/interval-ops/src/bounds.rs, packages/graph/hash_graph/lib/interval-ops/src/interval.rs
Currently not required but for the sake of completeness, this adds `contains_point` similar to #1835 
- #1835
- Adds `Interval::contains_point`
- Drive-by: Remove `test_` from the name of tests, they are already residing in a `tests` module
Tests were added to test various values with different intervals
=> Add `Interval::contains_point` method

.github/scripts/rust/setup.py, packages/libs/deer/macros/rust-toolchain.toml, packages/libs/error-stack/macros/rust-toolchain.toml, packages/libs/error-stack/rust-toolchain.toml
rustup is able to search for the `rust-toolchain.toml` in the crate's or parent directory. Our CI currently requires the file to be present in the crate's directory (next to `Cargo.toml`). This is restricting, if we want to run `cargo` from another directory than the crate root.
Currently, #1827 fails because of this. Also, the toolchain files of `error-stack` and `deer` are currently duplicated because of this issue.
- #1827
- Add a function to the `setup.py` script to find the correct toolchain file (or error otherwise)
- Remove the obsolete toolchain files in `error-stack//macro` and `deer/macros`
=> Support searching for `rust-toolchain.toml` files in parent directories in CI

packages/graph/hash_graph/lib/interval-ops/src/interval.rs
Adds a function to the `Interval` trait to check if another interval is contained in this interval
- #1834 
An additional test was added to the test suite based on `lhs.merge(rhs) == lhs`, which is only true, if `lhs` contains `rhs`
=> Add `Interval::contains_interval` function

packages/graph/clients/typescript/api.ts, packages/graph/hash_graph/bench/benches/read_scaling/knowledge/complete/entity.rs, packages/graph/hash_graph/bench/benches/read_scaling/knowledge/linkless/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/knowledge/entity.rs, packages/graph/hash_graph/bench/benches/representative_read/ontology/entity_type.rs, packages/graph/hash_graph/lib/graph/src/api/rest/mod.rs, packages/graph/hash_graph/lib/graph/src/knowledge/entity/query.rs, packages/graph/hash_graph/lib/graph/src/shared/identifier/knowledge.rs, packages/graph/hash_graph/lib/graph/src/shared/identifier/time/interval.rs, packages/graph/hash_graph/lib/graph/src/shared/identifier/time/mod.rs, packages/graph/hash_graph/lib/graph/src/shared/identifier/time/projection.rs, packages/graph/hash_graph/lib/graph/src/shared/identifier/time/version.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/compile.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/condition.rs, packages/graph/hash_graph/lib/graph/src/store/query/mod.rs, packages/graph/hash_graph/tests/integration/postgres/mod.rs, packages/hash/subgraph/src/types/identifier.ts, packages/hash/subgraph/src/types/time.ts
To be consistent in the terms, we decided to rename `Span` to `Interval` and `VersionTimespan` to `VersionInterval`
- #1801 
- #1802
=> Rename `Span` to `Interval`

packages/graph/hash_graph/Makefile.toml
The doc-string tests are pretty slow in release builds because a new binary has to be compiled per test. This disables the doc-tests in release build to speed up the CI
=> Disable doc tests for release build in the Graph

turbo.json
Disables caching on `codegen` scripts – Turbo repo is not detecting that changes to `"@hashintel/hash-shared/graphql/scalar-mapping"`, a dependency of other packages used in their `codegen` scripts, is a reason to bust the cache (e.g. amend `scalar-mapping.ts` and see that cache is hit in other packages).
We need to figure out how to express it properly as a dependency.
I initially tried adding `"@hashintel/hash-shared/graphql/scalar-mapping"` as an explicit `inputs` to `codegen` commands in the repo, but this did not work (`inputs` appears to be for relative/local file paths only).
- [Related task](https://app.asana.com/0/1201095311341924/1203756634855180/f) _(internal)_
- Figure out how to express the dependency properly.
1.  Change something in the `scalar-mapping` file
2. `yarn`
3. …
=> Disable caching on codegen scripts

.github/renovate.json
This is an improvement of the previous PR, implementing suggestions from #1865. This includes:
* `separateMajorMinor: false`, we should™ now no longer get a "major" version bump every year for rust
* `fetchReleaseNotes: false`, we do not need rust-analyzer release notes if we just ~~ab~~use rust-analyzer to get the version number
* grouping into three buckets: <- this does **not** need to be updated for the move into `libs/`
* `error-stack`
* `deer`
* `graph`
* update badge in README and `lib.rs` of projects automatically
* there's no way to do this as a side-effect without a self-hosted bot, so we pretend it's a dependency we upgrade. This means that we cannot ensure that it is the same version, but assuming that the versions are always in sync and updated at the same time (through …
=> Automatically upgrade rust toolchain (2nd attempt)

package.json, packages/libs/error-stack/Cargo.toml, packages/libs/error-stack/package.json
This PR facilitates the completion of #1851. It partially repeats #1858, but does not move `packages/libs/error-stack` to `libs`. This will be done separately.
Adding `package.json` to `error-stack` improves the output of `yarn lint:license-in-workspaces`:
```
[EXTRA]   packages/libs/error-stack/LICENSE.md
[EXTRA]   packages/libs/error-stack/LICENSE-APACHE.md
[EXTRA]   packages/libs/error-stack/LICENSE-MIT.md
```
```
[FOUND]   packages/libs/error-stack/LICENSE.md
packages/libs/error-stack/LICENSE-APACHE.md
packages/libs/error-stack/LICENSE-MIT.md
```
=> Make `error-stack` a Yarn workspace

blocks/code/package.json, blocks/code/src/app.tsx, blocks/code/src/dev.tsx, blocks/code/src/types.ts
The code block has types which are automatically generated from a remote URI, which (a) the block source relies on and (b) are run as part of the repo's `codegen` command across all workspaces.
Because alpha.hash.ai's data is not yet stable, this risks the CI pipeline breaking, either because the type is not available, or because it is different from the expectations in the code block (if it has been recreated).
This PR commits the code block's types and renames its `codegen` command so that it is not run as part of CI and is available in the format the block requires to build.
=> Commit code block types. Change codegen command

.github/workflows/hash-backend-cd.yml
This PR fixes [a new error in CD](https://github.com/hashintel/hash/actions/runs/3958626453/jobs/6780421158):
```
ERROR: unable to prepare context: path "/home/runner/work/hash/hash/packages/hash/external-services/kratos" not found
Error: buildx failed with: ERROR: unable to prepare context: path "/home/runner/work/hash/hash/packages/hash/external-services/kratos" not found
```
It is a result of a clash between two PRs. https://github.com/hashintel/hash/pull/1864 was merged quite recently, after I checked paths in #1870. I did not check for the re-introduction of `packages/hash/external-services` this morning, so missed the clash. This should be fixed now.
Merge and see if `hash-backend-cd.yml` passes
=> Update path to kratos to fix CD

packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/ontology/read.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/data_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/entity_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/property_type.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/query/table.rs, packages/graph/hash_graph/postgres_migrations/V2__ontology_tables.sql
For future work and to avoid duplication we can move these types to the shared `type_ids` table
- This is required for [this Asana task](https://app.asana.com/0/0/1203774687353268/f) _(internal)_
- Change the database layout
- Adjust inserting logic
- Adjust querying logic
- Drive-by: Query base URI and the version from the `type_ids` table as well
=> Move `OwnedById` and `UpdatedById` to `type_ids` table

packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/version_id.rs, packages/graph/hash_graph/postgres_migrations/V2__ontology_tables.sql, packages/graph/hash_graph/postgres_migrations/V4__ontology_functions.sql
To more robustly create ontology types and allow changes to the database without touching the Rust code, we are going to move to function based creation and updating of ontology types (the same logic as we do for entities). This also resolved the potential data race
- [Asana task](https://app.asana.com/0/1202805690238892/1203201674100967/f) _(internal)_
- Use functions similar to the create/update functions of `entities`
- Clean up Rust code and properly handle errors
=> Use functions to create ontology types

packages/libs/error-stack/Makefile.toml
The error-stack PR is currently pretty slow, by grouping some features together, it's possible to eliminate 75% of the tests
Due to https://github.com/taiki-e/cargo-hack/issues/161 it's not possible to pass `--ignore-unknown-features` alongside with `--group-features`, so this PR works around that limitation
=> Group unrelated error-stack features

.trunk/.gitignore, .trunk/trunk.yaml
To properly test trunk.io, we need to add some basic configuration. This configuration file does not enable any checks/lints, it just adds the configuration file generated from `trunk init --lock`.
- [Init in a git repo](https://docs.trunk.io/docs/initialize-trunk-in-a-git-repo) -- official trunk.io documentation
=> Install trunk.io to the repository

.trunk/trunk.yaml
The CI is running fine for the `trunk_merge` branches, but it does not detect a passed CI. This PR attempts to solve this by removing the `required_statuses` section from the trunk configuration
=> Remove `required_statuses` from `trunk.yaml`

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/hash-backend-cd.yml, .github/workflows/rust.yml, .github/workflows/semgrep.yml
In order to allow `trunk.io` to test the CI in their branches, the CI has to run
Step 7 at [their documentation](https://docs.trunk.io/docs/getting-started) says:
> Set up the required checks by configuring your CI provider to run the required jobs whenever a branch is pushed to your GitHub repository with the special prefix `trunk-merge/`.
=> Run actions on `push` to `trunk-merge/` branches

.github/workflows/hash-backend-cd.yml
#1904 accidentally also added the branch for trunk.io to the backend CD, which was not intended.
=> Remove `push` branch from Backend CD

.github/workflows/ci.yml
To allow `trunk` to check the CI on their `trunk_merges/**` branches, it's required the CI runs on `push` events
=> Run CI on pushes to `main` and `trunk-merge/` branches

packages/graph/hash_graph/lib/graph/src/store/error.rs, packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/postgres_migrations/V2__ontology_tables.sql, packages/graph/hash_graph/postgres_migrations/V4__ontology_functions.sql
Storing the transaction time for ontology types gives us the ability to use it at some later point. This also enables validation, if we are actually updating to the version after the latest version.
- [Asana task](https://app.asana.com/0/1202805690238892/1203596982776833/f) _(internal)_
- Add `transaction_time` to `type_ids` table and adjust functions
- raise an exception, if the version does not match
=> Add transaction time to ontology types

apps/hash-frontend/src/lib/apollo-client.ts, libs/@local/hash-isomorphic-utils/src/graphql/create-apollo-client.ts
This PR disables apollo cache for any request by default on the NextJS server-side.
This reason why we do this is to prevent requests that take no params to be shared responses to users (i.e. the `me` query)
- [Asana task](https://app.asana.com/0/1202805690238892/1203788788550913/f) _(internal)_
- The Apollo client shared by client/server now conditionally disable caching
nope
1.  Start local development setup as usual
1. Follow steps by @yusufkinatas to trigger response sharing:
```
1. Open two different browsers on incognito mode, side by side
2. Register `charlie`  on left
3. Register `dean`  on right
4. Refresh `charlie`’s page
a. `charlie`  becomes `dean`
5. After step 4 , if we log out from everything, then try logging in to another …
```
=> Disable Apollo cache on SSR requests

packages/graph/hash_graph/lib/graph/src/store/postgres/mod.rs, packages/graph/hash_graph/postgres_migrations/V2__ontology_tables.sql, packages/graph/hash_graph/postgres_migrations/V4__ontology_functions.sql
With #1886, it's possible to greatly simplify the definition of the ontology tables. This is possible as inserting a new ontology type with a base URI will fail as there will be overlapping transaction times.
- #1886
- #1886
- Make `version_id` the primary key of `type_ids` (we still require `(base_uri, version)` to be unique)
- Remove `base_uris` table
- Remove `version_ids` table
- Change the insertion order on the update trigger to avoid unneeded deferring of constraints
- Adjust the Graph to also catch the overlapping-constraint on creating
=> Simplify ontology table definitions

.github/workflows/hash-backend-cd.yml
This PR adds a path check for kratos configuration in the backend CD workflow
- [Asana task](https://app.asana.com/0/1203543021352041/1203767287750379/f) _(internal)_
=> Add `external-services/kratos` path to CD push trigger

.trunk/trunk.yaml
The CI now correctly runs on the pushed branch of `trunk`, however, it still does not merge the PRs. This is another attempt to add `required_statuses` to the configuration file
=> Second attempt to enable `required_statuses` for trunk

.github/renovate.json
Renovate bot attempts to merge automatically, which is unwanted behavior.
=> Disable automerge for renovate

apps/hash-api/src/graphql/resolvers/index.ts
#1340 introduced a temporary way of having 'anonymous readonly' pages which allowed any anonymous user to see any page.
#1823 broke this by introducing a new dependency on `getEntity` for resolving a page's data (in order to fetch the subgraph rooted at a block).
This PR fixes that by removing the logged in gate on `getEntity`. As mentioned in #1340 and elsewhere, these gates are superficial and do not provide proper security for any entity – which will be solved by introducing proper authorization – and this therefore does not represent removal of an effective security control.
1.  Log in, find a page URL
2. View the page in incognito, check it loads without crashing
=> Remove get entity logged in gate

infra/docker/api/prod/Dockerfile, infra/docker/frontend/prod/Dockerfile, infra/docker/search-loader/prod/Dockerfile, infra/docker/task-executor/Dockerfile, package.json
This PR fixes [HASH backend deployment](https://github.com/hashintel/hash/actions/workflows/hash-backend-cd.yml) action which I broke in #1896. I must have forgotten to re-check paths after resolving conflicts, or there was something else. In addition to replacing `packages/hash/subgraph` with `libs/@local/hash-subgraph` I ordered paths in `COPY` directives to simplify code scanning with a human eye.
- [Asana task](https://app.asana.com/0/1203543021352032/1203324923411371/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1674572887579809) _(internal)_
- Check CI
- Check CD in `main` after merge
=> Fix path to `hash-subgraph` in `Dockerfile`s

.github/labeler.yml, .github/workflows/labeler.yml
The aim of this PR is to re-enable Slack notification for changes related to HASH app. It replaces a few globs for `packages/hash/...` with `apps/hash-*/**`, `libs/hash-*/**` and `libs/@local/hash-*/**`. To avoid repetition, I replaced the official labeler versio with the latest commit from https://github.com/actions/labeler/pull/316.
- [Asana task](https://app.asana.com/0/1203543026679373/1203800233887959/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C02THT2LG8N/p1674566469357439) _(internal)_
- Check if labeler works (we can only see this once the PR is merged because we use `pull_request_target` as a trigger) 
- Wait for `dot` option to reach GA and use the official labeler.
- We can also consider syncing the labels with BP repo and get rid of `A/B/C-`. This …
=> Update labeler config

apps/hash-frontend/src/components/block-loader/block-loader.tsx, apps/hash-frontend/src/components/remote-block/remote-block.tsx
To keep the block subgraphs provided to blocks up-to-date when they get updated, we need to refetch the block subgraph. Ideally, this should be handled by Collab service in future.
For more context, check this [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1674725747666169) _(internal)_
=> Refetch block subgraph when block entity is updated

.changeset/config.json, libs/@local/hash-subgraph/package.json
@TimDiekmann has noticed GitHub action failures, which are caused by Changesets trying to publish workspaces we don’t want: https://github.com/hashintel/hash/actions/runs/4015045206/jobs/6896304775
```
@blocks/calculation@0.2.0
@blocks/chart@0.1.0
@blocks/countdown@0.2.0
@blocks/drawing@0.2.1
@blocks/github-pr-overview@0.1.0
@blocks/html-para@0.1.0
@blocks/shuffle@0.1.0
@blocks/stopwatch@0.1.0
@blocks/timer@0.2.0
@blocks/toggle-item@0.1.0
@local/hash-subgraph@0.0.0
```
I have added `private: true` to `package.json` in `@local/hash-subgraph` and have also tweaked Changesets config for the fix.
- [Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1674742091308839) _(internal)_
- [Asana task](https://app.asana.com/0/1203543026679373/1203835586239188/f) _(internal)_
See if …
=> Fix Release action

blocks/calculation/package.json, blocks/chart/package.json, blocks/countdown/package.json, blocks/drawing/package.json, blocks/github-pr-overview/package.json, blocks/html-para/package.json, blocks/shuffle/package.json, blocks/stopwatch/package.json, blocks/timer/package.json, blocks/toggle-item/package.json
This PR complements #1950, where we prevent Changesets from publishing blocks via  its `ignore` option. In addition to that, this PR adds `private: true` to 10 out of 20 blocks we host in this repo. Other blocks have already had this property. 
Ensuring `private: true` in all blocks makes our setup more consistent and prevents accidental publish attempts from package folders directly. I have also checked the property in other workspace by searching for `"name": "@apps/`, `"name": "@local/` and `"name": "@tests/`.
- [Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1674742091308839) _(internal)_
- [Asana task](https://hashintel.slack.com/archives/C02TWBTT3ED/p1674742091308839) _(internal)_
1.  Check Release GitHub action result after merge
=> Set `"private": true` in `@blocks/*/package.json`, where missing

apps/hash-frontend/next.config.js, apps/hash-frontend/src/middleware.page.ts
#1612 introduced the ability to retrieve a JSON version of any ontology type, so that machine-readable versions of types are available at their `$id`.
This PR allows fetching of these from any origin, since they are intended to be retrievable from anywhere and not just within the HASH app.
I am going to use this in type fetching code for the WordPress plugin.
- Open a tab from some random domain, e.g. https://www.google.com
- In the console, try a fetch request:
```js
fetch(
"https://hash-fwe0goic1.stage.hash.ai/@ciaran/types/entity-type/code-snippet/v/1", 
{ headers: { accept: "application/json" } } // also accepts any value that contains "application/json"
);
```
It will `404` because the type id uses the production domain, but it won't be rejected by CORS.
You can try removing the …
=> Permit cross-origin requests for types as json

apps/hash-graph/bench/benches/representative_read/knowledge/entity.rs, apps/hash-graph/lib/graph/src/knowledge/entity/query.rs, apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/query/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs, apps/hash-graph/lib/graph/src/store/postgres/query/table.rs, apps/hash-graph/lib/graph/src/store/query/mod.rs, apps/hash-graph/lib/graph/src/store/query/path.rs
This adds the support to index by nested fields and index arrays inside of `properties` of an entity query
- [Asana task](https://app.asana.com/0/1203543021352041/1202884883200943/f) _(internal)_
- Changes the `EntityTypeQuery::Properties` variant to hold a `JsonPath`
- `JsonPath` can be constructed from a list of tokens, which consists of strings or arrays
The documentation for `EntityTypeQuery::Properties` were adjusted
I was not able to construct `Type::JSONPATH` from Rust as it's most likely has a special format. Instead, we push it as `TEXT` and convert it to `JSONPATH` in postgres.
Support the same operations on `*TypeQuery::Schema` as well
=> Support nested fields and array index in structural queries

apps/hash-graph/lib/graph/src/knowledge/entity/query.rs, apps/hash-graph/lib/graph/src/ontology/data_type.rs, apps/hash-graph/lib/graph/src/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/ontology/mod.rs, apps/hash-graph/lib/graph/src/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/query/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/table.rs
We have the functionality to query for nested fields and arrays in entity properties but not for ontology schema. The functionality can be transferred, so this PR adds the functionality to the `"schema"` field.
This, however, does not expose querying for the schema, yet.
- [Asana task](https://app.asana.com/0/1203543026679373/1203821263193159/f) _(internal)_
- #1952 
- Renames `JsonField::JsonParameter` to `JsonField::JsonPathParameter` to make the intention more clear
- Adds `JsonPath` to the `Schema` variants for ontology types
- Adds `Schema` to ontology type tokens, but hides them via adding `#[serde(skip)]` for now
=> Support nested fields and array index for ontology schemas

apps/hash-graph/bench/benches/representative_read/seed.rs, apps/hash-graph/lib/graph/src/ontology/data_type.rs, apps/hash-graph/lib/graph/src/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, apps/hash-graph/lib/graph/src/store/postgres/mod.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/mod.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/ontology_id.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/query/condition.rs, apps/hash-graph/lib/graph/src/store/postgres/query/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/conditional.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/order_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/select_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/where_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/with_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs, apps/hash-graph/lib/graph/src/store/postgres/query/table.rs, apps/hash-graph/postgres_migrations/V2__ontology_tables.sql, apps/hash-graph/postgres_migrations/V3__knowledge_tables.sql, apps/hash-graph/postgres_migrations/V4__ontology_functions.sql, apps/hash-graph/postgres_migrations/V5__owned_ontology_functions.sql, apps/hash-graph/postgres_migrations/V6__knowledge_functions.sql
We use the term `type_id` when referring to a versioned URI. Similarly, the term `version_id` is confusing. This PR renames the `type_ids` table to `ontology_ids` and the `version_id` column to `ontology_id`.
- [Asana task](https://app.asana.com/0/1202805690238892/1203214689883089/f) _(internal)_
- Rename `type_ids` to `ontology_ids`
- Rename `ontology_ids::version_id` to `ontology_ids::ontology_id`
This is an internal change only
=> Rename `type_ids` table and `version_id` column

.github/workflows/rust.yml
In various PR the Rust CI linting job is failing as `cargo make` is supposed to be installed, but it's not. This PR tries to solve this by not caching the tools (which is probably a good idea anyway). If this PR is able to be merged, this issue should be solved, otherwise, it's very likely hitting the same bug.
This error happened in
- #1800
- #1973 
- #1976
=> Attempt to fix linting job in CI

.github/workflows/ci.yml
The linting CI currently fails in CIs that do not target `main`. This hotfix does not solve the issue, but at least it does not skip the warm-up task, so other tasks can still be checked.
- https://github.com/hashintel/hash/pull/1972
- https://github.com/hashintel/hash/pull/1329
- [Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1675079929051119) _(internal)_
=> Always warm up repository in CI

apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs
@indietyp encountered an issue, where the same table was joined multiple times with the same name. The bug occurred, if from the same base table the same table was joined multiple times, where another table was joined on the joined tables, e.g. `entity_types` were joined on `entities` twice and on each `entity_types` an `type_ids` table was joined. The `entity_types` tables are intermediate and not required in the final query, so they are optimized out. However, then `type_ids` was joined with the same name. This PR fixes this issue.
- [Asana task](https://app.asana.com/0/1202805690238892/1203811012038440/f) _(internal)_
- [Slack discussion](https://hashintel.slack.com/archives/C03TWBSRT8B/p1674570505708979) _(internal)_
- Instead of modifying the last table on the stack, we pop it and …
=> Fix bug that tables may be joined multiple times

.github/scripts/rust/Makefile.toml, .github/scripts/rust/setup.py, packages/libs/error-stack/Makefile.toml
We have a logic in place to only run a subset in PRs and only run the full set of tests before merge. However, in order to test locally, this logic should be reversed and instead of testing for a `push` event, this should test for `pull_request` events.
- #1800
=> Reverse logic to detect feature powerset on `cargo make`

apps/hash-graph/postgres_migrations/V7__entity_type_closure.sql
This PR adds new tables to support resolving inheritance chains of entity types.
This new `closed_entity_types_to_constituent_types` table represents a transitive closure from every `root` entity type to all of its ancestors.
- [Asana task](https://app.asana.com/0/1201095311341924/1203294246816644/f) _(internal)_
- https://github.com/hashintel/hash/pull/1972
- Adds a `closed_entity_types` table that will contain a "materialized" version of the entity type
- Adds a `closed_entity_types_to_constituent_types` table which will contain the transitive closure of all ancestor types being inherited (for now it will house the `Link` inheritance chain.)
- ~Renames `entity_types` to `owned_entity_types` to make it explicit that  the entity types in the system are only ones we own right now (and to …
=> Transitive closure entity type table

.github/workflows/ci.yml, .github/workflows/rust.yml, packages/libs/error-stack/Cargo.toml
[`cargo-semver-checks`](https://crates.io/crates/cargo-semver-checks) is a small tool, which checks if the version to be released is SemVer conform.
- Installs `cargo-semver-checks` in the `publish` CI job
- Checks for SemVer conform version bump
- Attempt to publish a breaking release with a minor version bump: 5992696d8dc31db6835e2bdb6c9732fa348011b0 (reverted in 2f18ccc340bb99209857558d23e4d3818cf587c1)
- Drive-by: Run the `publish` job in trunk CI as well
```
Updating index
Parsing error-stack v0.2.5 (current)
Parsing error-stack v0.2.4 (baseline)
Checking error-stack v0.2.4 -> v0.2.5 (minor change)
Completed [   0.161s] 35 checks; 33 passed, 2 failed, 5 unnecessary
--- failure inherent_method_missing: pub method removed or renamed ---
Description:
A publicly-visible method or …
```
=> Add check to CI to compare Semantic Version prior releases

packages/libs/error-stack/src/fmt/hook.rs, packages/libs/error-stack/src/hook/context.rs, packages/libs/error-stack/src/lib.rs, packages/libs/error-stack/tests/snapshots/doc/fmt__hookcontext_cast.snap, packages/libs/error-stack/tests/snapshots/doc/fmt__hookcontext_decrement.snap, packages/libs/error-stack/tests/snapshots/doc/fmt__hookcontext_increment.snap
#1693 separated `fmt::HookContext` into `hook::HookContext` and `fmt::HookContext`, so that it can be used in #1558. While working, the problem is that documentation doesn't render correctly because `hook::HookContext` is private in public. Therefore unreachable rustdoc is unable to navigate to the type, and the documentation is incomplete.
This PR moves to a macro-based approach to enable better documentation. Instead of using an unreachable public type, we have a macro that implements the necessary common functions. This is by far not ideal, but I found this to be the best way without compromising #1558 or future hooks.
=> `error-stack`: clarify documentation of `HookContext`

.github/renovate.json
When moving `packages/graph` to `apps/hash-graph` we forgot to update the renovate config
=> Fix Renovate not picking up toolchain for `hash-graph`

.github/workflows/rust.yml
In order to move `error-stack` to `libs/` (#1985), which is touching the `version` line in the `Cargo.toml`, we need to disable the `publish` job, otherwise, it will try to publish the crate with an unchanged version. There is probably a better way to detect a version change, but this is currently out of scope, and moving a whole crate is unlikely to happen again in the future.
- #1985
=> Temporarily disable `Rust / publish` job

apps/hash-frontend/src/pages/[shortname]/entities/[entity-uuid].page/entity-editor/links-section/link-table/cells/linked-with-cell/linked-entity-list-editor.tsx, apps/hash-graph/lib/graph/src/shared/identifier/knowledge.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity/mod.rs, apps/hash-graph/lib/graph/src/store/postgres/mod.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs, apps/hash-graph/lib/graph/src/store/postgres/query/table.rs, apps/hash-graph/postgres_migrations/V2__ontology_tables.sql, apps/hash-graph/postgres_migrations/V3__knowledge_tables.sql, apps/hash-graph/postgres_migrations/V5__owned_ontology_functions.sql, apps/hash-graph/postgres_migrations/V6__knowledge_functions.sql, libs/@local/hash-graph-client/api.ts, libs/@local/hash-subgraph/src/types/identifier.ts
This is a subset of changes made with other PRs and some further renames with minimal effect on things outside of the database layout. We chose this route to allow merging #1978 into `main` sooner than later.
Supersedes
- https://github.com/hashintel/hash/pull/1975
- https://github.com/hashintel/hash/pull/1979
- https://github.com/hashintel/hash/pull/1988
- These are mainly the changes as in the linked three pull request, but only trying to touch database related functions.
- Also renames `updated_by_id` to `record_created_by_id` in ontology tables
- Make naming of tables more consistent
=> Rename database columns and tables

apps/hash-graph/lib/graph/src/api/rest.rs, apps/hash-graph/lib/graph/src/ontology.rs, apps/hash-graph/lib/graph/src/ontology/data_type.rs, apps/hash-graph/lib/graph/src/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs, apps/hash-graph/lib/graph/src/store/postgres/query/condition.rs, apps/hash-graph/lib/graph/src/store/postgres/query/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/conditional.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/order_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/select_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/where_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/with_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs, apps/hash-graph/lib/graph/src/store/postgres/query/table.rs, apps/hash-graph/lib/graph/src/store/query.rs, libs/@local/hash-graph-client/api.ts
With #2004 we added support for external metadata to the database. This requires new handling on the Graph API to properly query for that metadata.
For now, only the logic to query the database is implemented, external metadata is not exposed yet to the TS backend. For this, only the `skip_serialize` has to be removed from the added enumeration.
- [Asana task](https://app.asana.com/0/1203543026679380/1203843814258952/f) _(internal)_
- Split `OntologyElementMetadata` into `OwnedOntologyElementMetadata` and `ExternalOntologyElementMetadata`
- Adjust structural queries to query for the `additional_metadata` column
- Remove old references to the `owned_ontology_ids` table
=> Add new `OntologyMetadata` enum that contains variants for Owned and External

patches/react-hook-form+7.37.0.patch
A bug in react-hook-form meant that the internal state of `useFieldArray` (used for properties/links tables) wasn't updating when the entity type loaded if the entity type hadn't loaded by the time the entity type editor page loaded.
This PR uses `patch-package` to patch this bug, but it's also been reported to react-hook-form to see if they're willing to address it. 
Replaces https://github.com/hashintel/hash/pull/2013 
- [Asana task](https://app.asana.com/0/1203543021352032/1203771430939706/f) _(internal)_
- [Github issue in react-hook-form](https://github.com/react-hook-form/react-hook-form/issues/9878)
N/A
- A new effect is added to `useFieldArray` in react-hook-form to update its internal state on mount, to ensure it takes into account any changes made prior to subscribing. This …
=> Ensure properties/links tables reliably update when data loads in entity type editor

apps/hash-graph/bench/benches/util.rs, apps/hash-graph/bin/cli/src/subcommands/server.rs, apps/hash-graph/lib/graph/src/api/rest/data_type.rs, apps/hash-graph/lib/graph/src/api/rest/entity_type.rs, apps/hash-graph/lib/graph/src/api/rest/property_type.rs, apps/hash-graph/lib/graph/src/shared/identifier/ontology.rs, apps/hash-graph/lib/graph/src/store/ontology.rs, apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs, apps/hash-graph/tests/integration/lib.rs, apps/hash-graph/tests/integration/postgres.rs
This PR introduces two changes: It changes the `Store` methods to take the ontology metadata to either insert an owned or an external ontology type. Also, it introduces a batch insertion for ontology types (currently internal to the graph), which defers the insertion of references to the end of the insertion.
- [Asana task](https://app.asana.com/0/1203543026679380/1203843814258954/f) _(internal)_
- Make the `Store::create_*_type` to take `OntologyElementMetadata` instead of `UpdatedById` and `OwnedById`
- Add `Store::create_*_types`, which defers insertion of references to the end
- Default implement `Store::crate_*_type` to use the `Store::crate_*_types` method
- Correctly implement `ToSql` and `FromSql` for `OntologyTypeVersion`
- Use the batch insertion in integration tests
The Graph …
=> Allow batch insertion of (owned and external) ontology types

apps/hash-frontend/src/pages/[shortname]/types/entity-type/[entity-type-id].page/definition-tab/property-list-card/property-type-form/expected-value-selector.tsx
Removes unnecessary use of `forwardRef` which was causing React to warn in the console
- [Asana task](https://app.asana.com/0/1203543026679380/1203835239889656/f) _(internal)_
=> Fix forwardref error in console in entity type editor

libs/error-stack/src/fmt.rs, libs/error-stack/tests/snapshots/doc/fmt__emit_alt.snap, libs/error-stack/tests/snapshots/test_debug__full__multiline.snap
This was an oversight in #1980, where we removed the leading space from attachments but forgot multiline attachments.
- #2019
=> `error-stack`: remove leading space for multiline attachments

.github/scripts/rust/setup.py
When rebasing `dev/links` onto `main`, we re-added the logic to filter for sub-crates to `find_local_crates`, but this logic was moved to `filter_parent_crates`. This reverts this change
=> Fix Publish job to correctly pick up subcrates

.github/workflows/rust.yml
The `SemVer check` job does not allow publishing a crate, which did not exist in the index. To publish #2018, we have to temporarily disable this job.
- [Asana task](https://app.asana.com/0/1202805690238892/1203893818926461/f) _(internal)_
=> Temporarily disable `SemVer check` job

blocks/calculation/package.json, blocks/callout/package.json, blocks/chart/package.json, blocks/countdown/package.json, blocks/divider/package.json, blocks/drawing/package.json, blocks/embed/package.json, blocks/github-pr-overview/package.json, blocks/header/package.json, blocks/html-para/package.json, blocks/image/package.json, blocks/paragraph/package.json, blocks/person/package.json, blocks/shuffle/package.json, blocks/stopwatch/package.json, blocks/table/package.json, blocks/timer/package.json, blocks/toggle-item/package.json, blocks/video/package.json
This PR enables upcoming updates to the block publishing process. It defines block names in `package.json` → `"blockprotocol"`.
The new values of `"name"` include author and are different to the Yarn workspace names (`@blocks/*`). The only block in which I don’t update `"name"` is _Code_, in which it is equal to `"@hash/code"` already:
https://github.com/hashintel/hash/blob/4a18af145a4e20cda5b7026576256cda8c85d104/blocks/code/package.json#L45-L52
- [Asana task](https://app.asana.com/0/1203358502199087/1203388867587773/f) _(internal)_
- See tests and preview deployment in https://github.com/blockprotocol/blockprotocol/pull/947
There is a chance that HASH app may have some issues because of the new metadata. We will see this after merging …
=> Define full block names in package.json files

libs/error-stack/Cargo.toml
With `thread_local` v1.1.5 `miri` reports a memory leak. This pins the version of `thread_local` until the issue is fixed.
- https://github.com/Amanieu/thread_local-rs/issues/45
=> Pin `thread_local` crate to version `1.1.4`

libs/error-stack/CHANGELOG.md, libs/error-stack/Cargo.toml
A small bug was highlighted in #2019 and fixed in #2022, so we want to publish the fix.
- Closes #2019
- #2022
Currently, the `SemVer Check` job is disabled, so we have to run it manually. Output:
```
❯ cargo semver-checks check-release       
Updating index
Parsing error-stack v0.3.1 (current)
Parsing error-stack v0.3.0 (baseline)
Checking error-stack v0.3.0 -> v0.3.1 (minor change)
Completed [   0.127s] 35 checks; 35 passed, 5 unnecessary
cargo semver-checks check-release  11.95s user 2.40s system 87% cpu 16.334 total
❯ echo $?
0
```
=> Publish `error-stack` v0.3.1

libs/error-stack/Cargo.toml
This reverts commit 9e13ea2f
With https://github.com/hashintel/hash/pull/2033 we pinned `thread_local` to `1.1.4` as a. bug was discovered in `1.1.5`. The release was yanked, so it's safe to stop pinning the version.
- #2033 
- https://github.com/Amanieu/thread_local-rs/issues/45
=> Unpin `thread_local` crate version

.github/workflows/rust.yml
We currently encounter many errors due to `cargo quickinstall` not being able to install `cargo make`. This falls back to `cargo install`
=> Fallback to `cargo install`

apps/hash-frontend/src/pages/[shortname]/types/entity-type/[entity-type-id].page/use-entity-type-value.tsx
The entity type editor is not always getting the latest version of the entity type.
- [Asana task](https://app.asana.com/0/1203179076056209/1203945433650363/f) _(internal)_
- [Slack Thread](https://hashintel.slack.com/archives/C022217GAHF/p1676023551778349)
1.  Create an entity type;
2.  Create another entity type and create a link to the first entity type (it will link to v1);
3.  Update the first entity type to create a v2;
4.  Refresh the page;
5.  Ensure v2 is shown instead of v1.
=> Always get latest entity type in the entity type editor

.trunk/trunk.yaml
We having some issues with Vercel queuing jobs properly. If we don't consider this as a blocker for merge PRs, we don't need to require it.
- [slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1676034546212509) _(internal)_
=> Don't require `Vercel` to pass on merge

vercel.json
No idea if `vercel.json` supports glob patterns in branch name definitions here. Let's try it, and hope.
Corresponding Vercel docs: https://vercel.com/docs/concepts/projects/project-configuration/git-configuration#git.deploymentenabled
=> Disable Vercel deployment for `trunk-merge-*` branches

vercel.json
Seems that the pattern is `trunk-merge/2048/1qeq9ATg-UYT2` and not with a slash before the PR number. Maybe this would work?
=> Change vercel disabled branches to match `trunk-merge/*`

apps/hash-graph/bin/cli/src/subcommand/server.rs, apps/hash-graph/lib/type-fetcher/src/fetcher.rs, apps/hash-graph/lib/type-fetcher/src/fetcher_server.rs
Currently, the type fetcher takes in a string, but we have a more descriptive way for ontology types. This also makes the traversal operations public, so they can be used in the fetching client.
This is a required change to have a working type fetcher at HASH to unblock further work on the `FetchingStore`
- [Asana task](https://app.asana.com/0/1203623179643281/1203958456055089/f) _(internal)_
- Use `VersionedUri` in the type fetcher
- Expose traversal functions
=> Use `VersionedUri` instead of `String` in type fetcher

apps/hash-graph/bin/cli/src/subcommand/server.rs, apps/hash-graph/lib/graph/src/ontology.rs, apps/hash-graph/lib/graph/src/store/fetcher.rs, apps/hash-graph/lib/graph/src/store/ontology.rs, apps/hash-graph/tests/rest-test.http
This adds the usage of the type fetcher in the `FetchingStore` and avoids the requirement of having pre-seeded data types. 
- [Asana task](https://app.asana.com/0/1203543026679380/1203843814258959/f) _(internal)_
- #2067 
- #2068 
- [Implement `traverse_references` on `OntologyType`](https://github.com/hashintel/hash/commit/091b526eb06b1d9039cfbc503dc91fd7600b0b43)
- [Provide `provenance_metadata` from `OntologyElementMetadata`](https://github.com/hashintel/hash/commit/e987ec1455c8453dc5caa5eadc6d6224f2bf0b21)
- [Implement fetching logic on the `FetchingStore`](https://github.com/hashintel/hash/commit/256040b2de6c6a8a244220fd8fd161c1a55f17e3)
- [Don't seed datatypes in the stop-gap solution](https://github.com/hashintel/hash/commit/55e92234167d733c02b91632a69ca97282fdbc04)
=> Use type fetcher when creating or updating types

.github/actions/warm-up-repo/action.yml, .github/workflows/rust.yml
We encountered a lot of issues recently due to caching not working. This disables the caching on `warm-up repo`.
- [Slack discussion](https://hashintel.slack.com/archives/C02TWBTT3ED/p1676466201924619) _(internal)_
Caching usually speeds up the CI. In our case, however, running `yarn install` does not take very long. See the slack discussion linked above for more information.
=> Disable caching for `CI` job

.github/workflows/ci.yml, .github/workflows/rust.yml
We experience many spurious failures when uploading the coverage report. This sets the `fail_ci_if_error` flag to `false` for now.
- [Slack discussion](https://hashintel.slack.com/archives/C02TWBTT3ED/p1676629944725669) _(internal)_
- https://github.com/codecov/codecov-action/issues/918
- https://github.com/codecov/codecov-action/issues/720
=> Temporarily disable CI failure on failed coverage upload

blocks/code/package.json, blocks/code/src/dev.tsx, blocks/code/src/editor.module.css, blocks/code/src/editor.tsx
Fixes an issue with the code block whereby a horizontal scrollbar was not accounted for in the textarea and pre height (textarea is present for editing, pre for formatted display), which introduced a vertical scrollbar and made it impossible to view the lowest lines.
This also fixes an issue I just introduced in #2107 where line breaks in the example content were escaped.
1.  `cd blocks/code && yarn dev`
You can see the existing behavior in the [Hub](https://blockprotocol.org/@hash/blocks/code) or in the following video:
https://user-images.githubusercontent.com/37743469/220299060-6f7dc877-ca84-4b62-bd4b-b377930f801e.mp4
---
https://user-images.githubusercontent.com/37743469/220299187-6f134947-e9ed-479c-8b57-5c47fce55d2e.mp4
=> Account for horizontal scrollbar in code block sizing

apps/hash-graph/lib/graph/src/lib.rs, apps/hash-graph/lib/graph/src/store/postgres/query/condition.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/where_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs, apps/hash-graph/lib/graph/src/store/query/filter.rs
We currently only require integers for predefined fields (fields inside of JSON like `"properties"."..."` are treated differently):
- unsigned 32-bit value for ontology versions
- signed 32-bit value for ordering (this may change in the future)
- It's possible to truncate the value for ontology versions if the number was too big (resulting in the wrong error, annoying but not a major issue)
- It's *not* possible to specify a parameter for `"leftToRightOrder"` or `"rightToLeftOrder"` *at all* as this will fail with the following error:
```
graph::api::rest::entity: Could not read entities from the store, error: Could not query from store
│
╰─▶ error serializing parameter 2: cannot convert between the Rust type `f64` and the Postgres type `int4`
```
- [Asana …
=> Fix numbers not being passed correctly to Postgres

apps/hash-graph/lib/graph/src/api/rest.rs, apps/hash-graph/lib/graph/src/api/rest/utoipa_typedef/subgraph.rs, apps/hash-graph/lib/graph/src/api/rest/utoipa_typedef/subgraph/edges.rs, apps/hash-graph/lib/graph/src/api/rest/utoipa_typedef/subgraph/vertices/vertex.rs, apps/hash-graph/lib/graph/src/shared/subgraph/edges.rs, apps/hash-graph/lib/graph/src/shared/subgraph/edges/edge.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs, libs/@local/hash-graph-client/api.ts, libs/@local/hash-subgraph/src/temp/map-edges.ts, libs/@local/hash-subgraph/tests/compatibility.test/map-edges.ts
We currently have still a lot of `OneOf` and more unreadable things in our `api.ts` file. This makes it very unreadable. By only tweaking a few small bits on the Graph API we are able to greatly improve readability. One example is removing `OntologyOutwardEdgesOneOfKindEnum` and just using (the already defined) `OntologyEdgeKind` enumeration.
This also fixes a naming issue on the `*Edges` enumeration and removes the trailing `s`.
- #1854
=> Make `utoipa` definitions more readable

apps/hash-graph/lib/graph/src/api/rest/data_type.rs, apps/hash-graph/lib/graph/src/api/rest/entity_type.rs, apps/hash-graph/lib/graph/src/api/rest/property_type.rs, apps/hash-graph/lib/graph/src/store.rs, apps/hash-graph/lib/graph/src/store/error.rs, apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/postgres_migrations/V2__ontology_tables.sql, apps/hash-graph/postgres_migrations/V4__ontology_functions.sql, apps/hash-graph/postgres_migrations/V5__ontology_metadata_functions.sql, apps/hash-graph/tests/integration/postgres/data_type.rs, apps/hash-graph/tests/integration/postgres/lib.rs
The current database layout asserts, that we only call "create" once per Base URI.
- [Asana task](https://app.asana.com/0/1203623179643284/1203958456055099/f) _(internal)_
- Adjust database to allow multiple versions of external ontology data to be **created** (we can't _update_ them as they may be inserted in arbitrary order)
- Greatly improve the error handling code in Postgres
- A bunch of new integration tests was added to catch different possibilities of inserting various data. This also asserts the correct errors.
- Modify the Rest API tests and try out different configurations
- keep in mind that you cannot insert external types from the Rest API, so may you also want to play around with the newly added tests
=> Support inserting the same external type with different versions

.github/CODEOWNERS
Adds `@hashintel/hash-database` as CODEOWNER of `apps/hash-graph/postgres_migrations/`.
The team contains @hashdotai @TimDiekmann @thehabbos007.
---
- https://app.asana.com/0/0/1204015588280819
=> Add DB/migration owners to CODEOWNERS

.github/CODEOWNERS
Adds the _IntelliJ Plugin_ app and team to the CODEOWNERS file.
=> Add `IntelliJ Plugin` app and team to CODEOWNERS

apps/hash-graph/bench/read_scaling/knowledge/complete/entity.rs, apps/hash-graph/bench/representative_read/lib.rs, apps/hash-graph/lib/graph/src/shared/identifier/time/bound.rs, apps/hash-graph/lib/graph/src/shared/identifier/time/interval.rs, apps/hash-graph/lib/graph/src/shared/subgraph/query.rs, apps/hash-graph/lib/graph/src/store/query/filter.rs, libs/deer/desert/src/error.rs, libs/deer/tests/test_value.rs, libs/error-stack/examples/detect.rs
With the next Rust toolchain (`2023-02-27`), clippy will have a few more lints, which are enabled. This prepares the codebase to take those into account or ignore the false positives.
- #2143
=> Satisfy clippy for new Rust toolchain

apps/hash-graph/lib/graph/src/shared/interval.rs, apps/hash-graph/lib/graph/src/shared/interval/bounds.rs
Currently, we cannot sort intervals. Sorting is required to have a more or less efficient and easy way to merge overlapping intervals in a list.
- [Asana task](https://app.asana.com/0/1202805690238892/1203835712237857/f) _(internal)_
- #2110 
- Use the correct bounds for `Interval` operations: The bounds needs to be `Ord` and `Eq` over `PartialOrd` and `PartialEq`, otherwise weird panic messages will happen when for example comparing `[NaN, +∞)` and `[NaN, +∞)`. The intervals can be constructed (as `NaN` is not greater than `+∞`), but comparing `NaN` to `NaN` will panic)
- Implement `PartialOrd` and `Ord` for `Interval`
=> Implement `Interval` ordering

apps/hash-graph/lib/graph/src/shared/identifier.rs, apps/hash-graph/lib/graph/src/shared/interval.rs, apps/hash-graph/lib/graph/src/shared/subgraph/edges.rs
This implements merging overlapping intervals on edge endpoints.
- [Asana task](https://app.asana.com/0/1201095311341924/1203399924452451/f) _(internal)_
- #2110 
- #2115 
- Implements unification of intervals when iterating the `EntityIdWithIntervalSet`
- Simplify implementation of `Interval::union`
Please see the TODO comment in `EntityIdWithIntervalSet::into_iter`
=> Merge overlapping intervals when iterating through edge endpoints

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/rust.yml, .github/workflows/semgrep.yml
In the BP repository we enabled GH Merge Queue and this went pretty well. This is going to allow the GH Merge Queue in this repository as well.
- https://github.com/blockprotocol/blockprotocol/pull/1100
- [Slack thread](https://hashintel.slack.com/archives/C02TWBTT3ED/p1677788837126439) _(internal)_
=> Add the `merge_group` trigger to CI workflows

.config/lints.toml, apps/hash-graph/.cargo/config.toml, apps/hash-graph/bench/read_scaling/knowledge/complete/entity.rs, apps/hash-graph/bench/representative_read/lib.rs, apps/hash-graph/lib/graph/src/logging/init.rs, libs/deer/.cargo/config.toml, libs/error-stack/.cargo/config.toml
The lint is a great idea, but sadly it currently only has false positives. This PR disables the lint globally for now.
- [Lint description](https://rust-lang.github.io/rust-clippy/master/#significant_drop_tightening)
=> Globally allow `clippy::significant_drop_tightening`

apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
The recursive lookup is easy to implement but very hard to optimize. Instead, we want to use an unfolding loop.
I highly recommend trimming the whitespace when reviewing this PR.
- [Asana task](https://app.asana.com/0/1203623179643290/1204117845662864/f) _(internal)_
- [Slack thread](https://hashintel.slack.com/archives/C03F7V6DU9M/p1678119337542689?thread_ts=1678107081.222519&cid=C03F7V6DU9M) _(internal)_
- Use a loop instead of recursion in traversal functions
- As we don't use recursion anymore it's possible to remove the `Pin<Box>` construct
- Pass in a batch of ids to traverse and adjust the `get_` methods
- Rename `current_resolve_depths` to `graph_resolve_depths` and `intersected_temporal_axes` to `temporal_axes` to shadow previous variables to avoid using old variables by …
=> Move traversal implementation to unfold loop instead of recursive calls

blocks/how-to/src/app.tsx
The How To block intends the steps linked to it to be in a certain order, but was not specifying one – it happened to work in some environments where the order the application returned the links was deterministic in the right way, but the block cannot rely on this (applications might send the latest createst links first, for example).
This PR fixes that by specifying a position for the link when creating it.
=> Make step ordering deterministic in How To block

apps/hash-graph/lib/graph/src/api/rest.rs, apps/hash-graph/lib/graph/src/api/rest/utoipa_typedef/subgraph.rs, apps/hash-graph/lib/graph/src/api/rest/utoipa_typedef/subgraph/edges.rs, apps/hash-graph/lib/graph/src/api/rest/utoipa_typedef/subgraph/vertices.rs, apps/hash-graph/lib/graph/src/api/rest/utoipa_typedef/subgraph/vertices/vertex.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/record.rs, apps/hash-graph/lib/graph/src/subgraph.rs, apps/hash-graph/lib/graph/src/subgraph/edges.rs, apps/hash-graph/lib/graph/src/subgraph/edges/kind.rs, apps/hash-graph/lib/graph/src/subgraph/identifier.rs, apps/hash-graph/lib/graph/src/subgraph/identifier/edge.rs, apps/hash-graph/lib/graph/src/subgraph/identifier/vertex.rs, apps/hash-graph/lib/graph/src/subgraph/vertices.rs
We are going to have reference tables between entities and entities, and between entities and entity types. To simplify batched reading of the data from the database, we store a set of edges per reference table
- #2178 
- #2181 
- Use adjacency lists for each kind of edge (determined by the endpoints, not by the edge kind itself)
- If we chose to have reference tables for each edge kind, this can easily be added later on
- Merge `VertexIndex` and `VertexId` traits. They are now implemented on exactly the same types in the same context
- Move `OntologyTypeVertexId` to `utoipa_typedef`. As mentioned previously, this could be removed entirely, but to avoid touching the `utoipa_typedef` too many times moving it is sufficient for now. The subgraph typedefs …
=> Store adjacency list for each (planned) reference table

.github/scripts/rust/setup.py, libs/antsi/.cargo/config.toml
In a recent PR we changed the allowed lints in `.config`, but this did not run all expected test, thus, currently `cargo make clippy` will fail when running in the `antsi` crate
- Change `setup.py` to also cover `.config`
- fix config file for `antsi`
=> Always run Rust jobs when `.config` changed

apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs
We have a small deduplication logic in the query compiler, however, the current implementation does not generate the correct SQL Query in all circumstances. The optimization is able to remove an intermediate table, but it's currently not taking the `entities` table into account correctly.
- #1965
- [Slack discussion](https://hashintel.slack.com/archives/C03TWBSRT8B/p1678703368190799) _(internal)_
This PR removes this optimization to prefer correctness over speed (the speed gain wouldn't be very high).
In queries, where we only use an intermediate table, this table appears in the SQL query again.
Re-implement this optimization: [Asana Task](https://app.asana.com/0/1202805690238892/1204165137291093/f) _(internal)_
Two unit tests are affected by this change, they have been adjusted
=> Remove potential optimization path in Query compiler

apps/hash-graph/lib/graph/src/api/rest/utoipa_typedef/subgraph/edges.rs
Currently, there's a bug that only the entity types will be returned if entity edges and entity types are requested in the same query. This is because instead of merging the flattened adjacency lists, only the last list is collected (due to the use of `collect()`). This PR instead uses fold and properly merges duplicate entity ids.
> This is also possible if entity types and property types are requested.
=> Fix collecting of edges by merging them

apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/join_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs, apps/hash-graph/lib/graph/src/store/postgres/query/table.rs
We currently do not support joining entities by `entity_uuid` *and* `owned_by_id`. This is likely to be one cause why our experiments with Citus results in slower performance than expected.
- [Asana task](https://app.asana.com/0/1204000740778935/1204165137291102/f) _(internal)_
- Enhance the `Relation::joins` function to allow returning multiple columns
- Adjust compiler and test outputs to take these changes into account
- Drive-by: Remove obsolete `ProjectedTime`
The `Relation` enumeration is quite large. Also, the `ForeignKeyReference` does not check, if the columns belong to the same table. I have a few ideas how to improve this, but this is out of scope in this PR.
Initially, this was done as a drive-by when migrating to reference tables, but the issue was actually harder so solve …
=> Fix `owned_by_id` not used when joining entity tables

apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/table.rs
As noted in #2200, the `Relation::joins` function got very long and is expected to get even longer with more reference tables added, which is the next step.
- #2200
- #2200 
- Introduce `ReferenceTable` enumeration, which defines the layout of a reference table
- Use `ReferenceTable` inside of `Table::Reference(ReferenceTable)` to provide the same API
- Return `impl Iterator` instead of a dynamically sized list when requesting the required joins for a relation
=> Simplify reference table definitions

apps/hash-graph/bench/representative_read/seed.rs, apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/query/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs, apps/hash-graph/lib/graph/src/store/postgres/query/table.rs, apps/hash-graph/postgres_migrations/V2__ontology_tables.sql, apps/hash-graph/postgres_migrations/V3__knowledge_tables.sql, apps/hash-graph/postgres_migrations/V6__knowledge_functions.sql
We're migrating the database to use reference tables for all edge kinds.
- [Asana task](https://app.asana.com/0/1204000740778935/1204165137291098/f) _(internal)_
- #2200 
- #2201 
- Adds the reference tables to the migration files
- Adjust the table and relation definitions
- Allow a "reversed" edge relation to avoid duplication (possible due to prior work in #2200 and #2201)
- Adjust a bunch of test cases and seeding scripts
This is an internal change
Pretty much every test will directly or indirectly test this part of the code
---
- https://app.asana.com/0/0/1204117847656665
=> Use reference tables for all edge kinds

.github/scripts/rust/Makefile.lint.toml, .github/workflows/rust.yml
Currently, it's not possible to invoke `cargo make clippy` when passing additional arguments (e.g. `cargo make clippy --message-format=json`). This fixes the issue by manually invoking it
Special thanks to @indietyp for providing this snippet!
=> Manually invoke `cargo-script` instead of using `cargo-make`

libs/error-stack/src/fmt.rs
This adds additional documentation on formatting in `error-stack` through a new section: `Implementation Details`. This is part of a larger effort to reduce the accumulated tech debt in the `fmt` module by:
1) reduce allocations
1.1) use of eager evaluation and use of `core::fmt` instead of requiring `Into<String>`
2) improve (internal) documentation
3) remove redundant code
This chain of PRs should have *no* user-facing changes, except documentation. Formatting will stay the same.
=> `error-stack`: improve formatting docs

.github/workflows/rust.yml
The publish job fails if an initial version of a crate is published. This PR changes the behavior to only run the check, if the version is not `0.0.0-reserved`, which cover all current and planned cases
- #2237
=> Only run semver check if it's not an initial version

libs/antsi/Cargo.toml, libs/antsi/src/color.rs, libs/antsi/src/font.rs, libs/antsi/src/lib.rs
This PR adds several feature gates for commonly used extra extensions to the standard that are not supported by all terminals. These are:
* `rgba`
* `underline-color`
* `underline-variants`
* `overstrike`
* `script`
=> `antsi`: feature gate extensions

apps/hash-graph/bench/representative_read/knowledge/entity.rs, apps/hash-graph/lib/graph/src/knowledge/entity/query.rs, apps/hash-graph/lib/graph/src/ontology/data_type.rs, apps/hash-graph/lib/graph/src/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, apps/hash-graph/lib/graph/src/store/postgres/query/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs, apps/hash-graph/lib/graph/src/store/postgres/query/table.rs, apps/hash-graph/lib/graph/src/store/query/filter.rs, apps/hash-graph/tests/integration/postgres/lib.rs
To store reversed edges it's easier to store the edge kind in the query path than both edges. For types with the same right endpoint of an edge (currently entity types and entities), this also avoids duplication of these definitions.
- [Asana task](https://app.asana.com/0/1204000740778935/1204165139634983/f) _(internal)_
- #2202
- Use the edge definitions to identify query paths
With the current implementation, there is not much advantage to change the definitions of the query paths, however, with the two follow-up PRs, this will be more clear.
- [Support reversed edges in structural ontology queries](https://app.asana.com/0/1204000740778935/1204165139634979/f) _(internal)_
- [Migrate the current implementation of looking up ontology type references in memory to instead be from the …
=> Use edge definitions in query paths

libs/antsi/src/decorations.rs, libs/antsi/src/font.rs, libs/antsi/src/lib.rs
Remove all getter and setter (prefixed with `set_`), adhering to the builder-lite principle. Since we do not need to uphold any invariants on the struct, all fields have been marked pub, the only exception is `Font::style`, which is a bitfield and therefore needs special methods for access. These have been unified and made more readable.
=> `antsi`: rework getter

libs/sarif/Cargo.toml, libs/sarif/Makefile.toml, libs/sarif/src/lib.rs, libs/sarif/src/schema.rs, libs/sarif/src/schema/log.rs, libs/sarif/src/schema/properties.rs, libs/sarif/src/schema/run.rs, libs/sarif/src/schema/tool.rs
This exhaustively adds all fields to the `Tool` struct and the API around it
- #2243 
- Add `PropertyBag`
- Add fields to `Tools`
- Greatly extend documentation and tests
- This branch has 💯% test coverage
=> Add all fields for `Tool` struct

libs/sarif/src/schema.rs, libs/sarif/tests/example_reports/k1_minimal.sarif.json, libs/sarif/tests/example_reports/k2_recommended_with_source.sarif.json, libs/sarif/tests/example_reports/k3_recommended_without_source.sarif.json, libs/sarif/tests/example_reports/k4_comprehensive.sarif.json
The specifications have four examples SARIF files as an appendix. This PR pulls them into VCS to test the current implementation for those examples.
- [Appendix K](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541386)
- [GitHub Issue to Appendix K](https://github.com/oasis-tcs/sarif-spec/issues/476)
- For Example K4 I had to fix some line endings, e.g. a trailing comma or a missing brace
- The JSON Schema validator complains at some sections in K4
=> Add example SARIF files as test data

apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
We're going to look up the references before looking up the actual records. This implies, that ontology references also needs to be looked up through the database. This also implies, that ontology types do not need to be looked up one-by-one.
- [Asana task](https://app.asana.com/0/1204000740778935/1204117847656666/f) _(internal)_
- #2202 
- #2207
- #2208
Replace lazy lookups based on the returned ontology reference iterators with direct lookups through reference tables
The structure of looking up edges is now almost identical, which enables further work to [deduplicate the subgraph traversal logic](https://app.asana.com/0/1203363157432084/1203444301722127/f)
=> Use reference tables when looking up ontology references

libs/deer/desert/src/object.rs, libs/deer/json/src/lib.rs, libs/deer/src/error.rs, libs/deer/src/lib.rs
This introduces a new API, `FieldAccess`, which is conjunction with `ObjectAccess` and can be used to conditionally get the value depending on the underlying type. This enables `Enum` style access, e.g. for `Result`.
Because we decided to have a minimal API surface and unify the access through `Object` vs. `Array` we have a fundamental problem: conditional values based on the key, this is best shown with `Result`, `Result<T, E>` has two variants: `Ok` and `Err` and depending on the key. This is now possible, by implementing something similar to:
```rust
enum Key {
Ok,
Err
}
/* impl Deserialize for Key */
pub trait FieldAccess<'de> {
type Key: Key;
type Value: Result<T, E>;
fn value(&self, key: &Key, deserializer: D) -> Result<Self::Value, FieldAccessError> {
match key {
Key::Ok => …
```
=> `deer`: introduce `FieldAccess`

libs/sarif/Cargo.toml, libs/sarif/src/schema/log.rs, libs/sarif/src/schema/tool.rs
This further extends the `ToolComponent` struct
- #2243
- #2245
- Add `ToolComponent::version`
- Add `ToolComponent::semantic_version`
- Add builder methods and documentation
- Add to the `full` test
- This branch has 💯% test coverage
=> Support `version` and `semantic_version` in `ToolComponent`

apps/hash-graph/lib/graph/src/ontology/data_type.rs, apps/hash-graph/lib/graph/src/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/table.rs, apps/hash-graph/lib/graph/src/store/query.rs
The goal is to have proper testing of the returned subgraph. This implies, that a set of data is present in the database. To insert a set of data into the data the easiest way to achieve this is to import a previously exported set of data. As we, however, do want the data to be exactly the same after exporting, wiping, and importing the data, it implies, that the graph requires information about the time, when an ontology type was inserted into the database, which is recorded in `transactionTime`, a variable, which is not exposed yet at all.
- [Asana task](https://app.asana.com/0/1204000740778938/1204216809501000/f) _(internal)_
- Add `TransactionTime` to the ontology query paths
- Make the query compiler aware of `TransactionTime`
A doc-string has been added to the newly added query path …
=> Expose ontology transaction time to the graph

blocks/address/package.json, blocks/how-to/package.json, blocks/minesweeper/package.json, blocks/table/package.json
We set `private: true` in the `package.json` for blocks, so that Changesets does not attempt to publish updates to them when their dependencies (e.g. `@hashintel/design-system`) are updated.
Although we have an `ignore` setting in `.changeset/config.json`, this only prevents Changesets from offering the packages as an option when generating changesets. It doesn't stop it attempting to update them when a dependency is updated. We have a [patch](https://github.com/hashintel/hash/blob/main/patches/%40changesets%2Bget-dependents-graph%2B1.3.5.patch) which prevents Changesets from trying to publish dependents who are set as `private: true`, but this requires we set `private: true` in packages we don't want published.
This PR fixes a few missing ocurrences of that.
=> Consistently set private: true in blocks

apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/subgraph/edges/edge.rs
The logic for traversing entities is only different in its parameters, so it can be deduplicated
- [Asana task](https://app.asana.com/0/1203363157432084/1203444301722127/f) _(internal)_
- #2207 
- #2208 
- #2223 
- #2226 
- #2229 
- Move traversal logic for entities to function
- Fix a bug to correctly resolve the edge interval. This is not necessarily the link's interval but the intersection of both endpoints. We did never encounter issues so far as without deletion it's not possible to construct this case.
=> Deduplicate graph traversal for entities

apps/hash-frontend/src/pages/[shortname]/types/entity-type/[...slug-maybe-version].page.tsx
Decodes draft entity type state using utf8 instead of ascii to allow special characters. This replicates a change in block protocol.
- [Asana task](https://app.asana.com/0/1204000740778938/1204203279638196/f) _(internal)_
=> Allow special characters in entity type editor draft state

.github/ISSUE_TEMPLATE/config.yml
Removes a deprecated link to the old community forum, in favor of only the Discord going forward. This was found in the GitHub issues template configuration file.
=> Remove deprecated link in GitHub Issues config

libs/sarif/src/schema.rs, libs/sarif/src/schema/log.rs, libs/sarif/src/schema/properties.rs, libs/sarif/src/schema/run.rs, libs/sarif/src/schema/tool.rs
There is no real reason to propagate the lifetimes of the strings, so this exposes the lifetime `'s` for all string-fields
=> Use lifetimes for strings

blocks/address/src/app.tsx
This PR fixes an edge case introduced by #2262
- [Asana task](https://app.asana.com/0/1203801045329780/1204249591562078/f) _(internal)_
Changed the block to only reset the state in the `onClose` callback, instead of when the address card animates out. Because of the loading state introduced in #2262, the address card will always animate in when a suggestion is selected. If the block fails to retieve that suggestion's data it will display an error state and animate out. Because we were resetting the block after the card animated out, the error was being cleared as well.
Before:
After:
=> Fix `Address` block error state when retrieving a suggestion

.github/workflows/rust.yml
We're currently not able to install `cargo-make` in CI in 90% of the cases. This uses `cargo install` to have a slow but working CI
=> Install `cargo-make` manually

apps/hash-graph/package.json, libs/@local/status/package.json, libs/@local/status/scripts/codegen.ts, libs/@local/status/tsconfig.json
The `@local/status` package was an ES-Module. 
That caused us problems within the backend (`hash-api` package) as our `ts-node` package failed to handle it when importing it. I've played around with trying to fix this, and I think there are three options:
1. Move away from `ts-node` for the HASH App (it's not recommended for production anyway)
2. Upgrade the `hash-api` to ESM
3. Downgrade `status` from ESM
I've opted to go with `3.` for now, as `2.` has a higher risk profile, and `1.` involves a lot more development than I currently have capacity for.
This has highlighted a general issue with our setup though, wherein we can't create or easily use all kinds of ES Modules, this is a problem and will force us to introduce bundlers and build steps within the monorepo if we don't address this …
=> Downgrade `status` from an ES-Module

libs/deer/desert/src/deserializer.rs, libs/deer/desert/src/object.rs, libs/deer/desert/src/tape.rs, libs/deer/json/src/lib.rs, libs/deer/src/lib.rs
#2263 has shown that `FieldAccess` introduced in #2157 is enough to model structs and arbitrarily named fields.
To reduce the complexity required for implementation (no look ahead etc.) this removes the `ObjectAccess::value` method.
=> `deer`: remove `ObjectAccess::value`

.github/scripts/rust/lint.rs, .github/workflows/rust.yml, .justfile
As mentioned in #2292, `cargo-script` is unmaintained, and `rust-script` is a maintained fork, which solves the issue we currently have.
- Replace `cargo-script` with `rust-script@0.23.0`
- Drive-by: allow running `just` in all directories within a workspace
=> Use `rust-script` instead of `cargo-script`

.github/actions/install-rust-toolchain/action.yml, .github/scripts/rust/setup.py, .github/workflows/rust.yml
As noticed in #2292, the `rust-toolchain.toml` should be the location, where the components are specified. In #2292 I ran into limitations as `RUSTUP_TOOLCHAIN` would override the `rust-toolchain.toml`. This PR works around this by not setting `RUSTUP_TOOLCHAIN` if the toolchain does match with the one inside of `rust-toolchain.toml`
=> Use `rust-toolchain.toml` file to install toolchains

blocks/heading/package.json, blocks/heading/variants.json
The `variants` of the Heading Block weren't updated to reflect the type system. This means that the demo on the hub is broken:
https://user-images.githubusercontent.com/25749103/228216172-33c3fbe7-4043-4c7f-b44e-a88d2ae2f66e.mov
This PR fixes this, when used in conjunction with https://github.com/blockprotocol/blockprotocol/pull/1223
(After, with https://github.com/blockprotocol/blockprotocol/pull/1223)
https://user-images.githubusercontent.com/25749103/228216388-b4c54913-b697-4cda-a49d-accb00e3915a.mov
=> Fix `variants` for the Heading Block

apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
When traversing nested properties, they are not correctly inserted into the subgraph, this fixes that.
- [Asana task](https://app.asana.com/0/1204086167143889/1204284866390930/f) _(internal)_
=> Fix wrongly inserted vertex id for nested properties

apps/hash-graph/lib/graph/src/store/postgres/query/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/query/property_type.rs
Recently, we added the possibility to query for the transaction time of an ontology type. When querying for the transaction time for property types or entity types, this currently results in a `panic!`.
- Add `TransactionTime` to the correct match arm
We currently have a catch-all arm in the logic as we only have a single `EdgeKind` enumeration for ontology edges. This will be changed in the future, but until then we need to deal with this.
=> Fix ontology transaction-time query paths results in panic

apps/hash-graph/lib/graph/src/logging/args.rs, apps/hash-graph/lib/graph/src/store/config.rs
Currently, the parameters has to be passed at the exact location. This might sounds intuitive but it's actually pretty annoying as soon as you have nested subcommand.
Example: Let's assume we have a `hash-graph snapshot dump` command. The database parameters are shared across all `snapshot` commands. However, it's required to pass it as
```
hash-graph snapshot --database dev_graph --port 1234 dump
```
while it would be more readable to append the information, e.g.
```
hash-graph snapshot dump --database dev_graph --port 1234
```
Set `global = true` for `clap` attributes
=> Allow specifying CLI arguments globally to the Graph

apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs, apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/query/condition.rs, apps/hash-graph/lib/graph/src/store/postgres/query/expression/where_clause.rs, apps/hash-graph/lib/graph/src/store/postgres/query/statement/select.rs
To store all entities, it's required that temporal data is extracted from the database.
- Part of [this Asana task](https://app.asana.com/0/1204000740778938/1204216809501005/f) _(internal)_
- Make the temporal axes parameter to the compiler optional
Two almost identical tests has been added, one with and one without temporal axes passed to the compiler
=> Support querying for all entities without pinning a temporal axis

apps/hash-graph/lib/graph/src/store/crud.rs, apps/hash-graph/lib/graph/src/store/fetcher.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs
To make a snapshot of the data in the database, we want to re-use the `Read` trait to avoid duplicated implementation of the same concept and eventually utilize the structural query compiler. To allow reading all temporal data, we must not restrict it by temporal axes.
- Part of [this Asana task](https://app.asana.com/0/1204000740778938/1204216809501005/f) _(internal)_
- #2285 
- Make temporal axes optional in `Read` trait
=> Make temporal axes optional in `Read` trait

apps/hash-graph/Cargo.lock, apps/hash-graph/lib/graph/Cargo.toml, apps/hash-graph/lib/graph/src/shared/identifier/knowledge.rs, apps/hash-graph/lib/graph/src/store.rs, apps/hash-graph/lib/graph/src/store/test_graph.rs
For creating a snapshot, we cannot re-use the representation for the ontology types as we store more information in the database than exposed, e.g. the `transaction-time`. Also, we want to distinguish between fields specified by blockprotocol.org and custom fields we use internally in HASH.
This PR adds a module, which contains the structs required to deserialize a graph.
- Part of [this Asana task](https://app.asana.com/0/1204000740778938/1204216809501005/f) _(internal)_
- Implement `Deserialize` for `EntityEditionId` and `EntityRecordId`
- Add structs to represent ontology types and entities with an optional field for metadata. Note, that I don't have added `AccountId`s (yet) as I don't expect it to be used in the short-term future. Querying those is complicated because that does not go …
=> Add `test_graph` module containing required and optional record fields

apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs
In #2313 a set of structs were added to contain ontology types, which contains more information than exposed to HASH. Reading those types is slightly different, so this PR adds support for reading those.
- [Asana task](https://app.asana.com/0/1204000740778938/1204216809501005/f) _(internal)_
- #2313
- #2310 (Will fail at runtime until merged)
- Use `OntologyTypeRecord<T>` from `test_graph` to read from the data store
- Re-use the implementation from above to return the "old" type to the `Store` trait
- The docs for x need updating to explain that y
We have to call `expect()` in the wrapping logic. While we can expect that the Rust compiler will optimize out this branch, the data for the transaction time is still queried from the database. This can be avoided by duplicating a large portion …
=> Allow `Read`ing (almost) all data from the database

apps/hash-graph/Cargo.lock, apps/hash-graph/bin/cli/Cargo.toml, apps/hash-graph/bin/cli/src/main.rs, apps/hash-graph/bin/cli/src/subcommand.rs, apps/hash-graph/bin/cli/src/subcommand/migrate.rs, apps/hash-graph/bin/cli/src/subcommand/server.rs, apps/hash-graph/bin/cli/src/subcommand/snapshot.rs
In #2314 support to read the data was added, this PR adds an interface to dump the data to the terminal.
- [Asana task](https://app.asana.com/0/1204000740778938/1204216809501005/f) _(internal)_
- #2313 
- #2314 
- #2310 (Will fail at runtime until merged)
- #2285 
- #2304 (compilation will fail until merged)
This adds a simple subcommand to dump `test_graph::TestData` to the terminal as JSON.
```sh
cargo run -- snapshot --database dev_graph dump | jq
```
=> Add a `snapshot` subcommand to the CLI

apps/hash-graph/bin/cli/src/subcommand/snapshot.rs, apps/hash-graph/lib/graph/src/store/test_graph.rs
After reading all data from the store we want to write it back. This adds the interface to write back the data to the graph.
- Part of [this Asana task](https://app.asana.com/0/1204086167143889/1204216809501006/f) _(internal)_
- #2316
- Moves reading logic to the library
- Wrap reading logic in a function
- Add writing entry point to CLI
- Temporarily fail with error when attempting to write
This PR:
Implement the logic to insert the data
This is supposed to be used in tests
The first commit does contain a `println!` wich helps debugging. In order to extract a snapshot, run
```sh
hash-graph snapshot dump --database dev_graph > snapshot.json
```
To read it back, run
```
cat snapshot.json | hash-graph snapshot restore --database dev_graph
hash-graph snapshot dump --database dev_graph | …
```
=> Provide a `snapshot restore` command

apps/hash-graph/Cargo.lock, apps/hash-graph/bench/Cargo.toml, apps/hash-graph/bin/cli/Cargo.toml, apps/hash-graph/lib/graph/Cargo.toml, apps/hash-graph/lib/type-fetcher/Cargo.toml, apps/hash-graph/tests/integration/Cargo.toml
The current `type-system` package does rely on a feature, which was changed. I already did actions on this to fix it in the upstream package, but the version was not updated in the graph.
This is blocking any further toolchain bumps
=> Update `type-system` crate to latest version

.justfile
The `-u` flag checks if a variable is set, but `CI` is not set outside of CI and we don't check over variables.
=> Fix `-u` flag outside of CI

apps/hash-graph/lib/graph/src/store/crud.rs, apps/hash-graph/lib/graph/src/store/fetcher.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs, apps/hash-graph/lib/graph/src/store/test_graph.rs
To avoid keeping the database in memory when writing it to stdout, this changes the `Read` trait to allow streaming of the data.
- [Asana task](https://app.asana.com/0/1204086167143892/1204320436419772/f) _(internal)_
- [Asana task](https://app.asana.com/0/1202805690238892/1202923536131158/f) _(internal)_
- Add `ReadStream` associated type to `Read`
- Move the `try_collect()` to `read_vec`, which can be seen as a convenient function to deal with the streams. I'm going to remove this functionality again in a later PR but to avoid touching the traversing logic, now, I leave this behavior unchanged
- Replace almost all calls to `read` to `read_vec`
- Use the stream returned from `read` when writing the test data. This PR still stores the data in memory, but enables streaming from the …
=> Support streaming data from the datastore

blocks/countdown/src/countdown-title.tsx
This PR fixes an issue with the Countdown block where the cursor would lose its position when changing the title value.
- [Asana task](https://app.asana.com/0/1204086167143889/1204270112397116/f) _(internal)_
- Made it so the value of the title's input isn't set every time it changes, which was causing the cursor to lose its position in some browsers (firefox and safari for example);
- Added a keydown event listener to submit the changes whenever Enter is pressed.
This PR:
Are blocks libraries? They do need publishing
=> Countdown Block improvements

.github/actions/install-rust-toolchain/action.yml, .github/scripts/rust/setup.py
This changes the rust ci action to install components, not via the profile but individually from the `rust-toolchain.toml`.
We can only do this now because last week, the runner image shipped with version 1.33 of `yq`, landing read toml support, without needing to install additional tools.
The runner-image is available on 99.99% of all runners (only five are left, but those have no image version tag and are always "left behind").
=> `ci`: use `yq` to install all necessary components

apps/hash-graph/Cargo.lock
Indirectly, we depend on `rustix@0.36` which relies on `RUSTC` in build scripts. `RUSTC` for the commands emitted by CLion and invoked from the terminal are different so each time a command from the CLI is called, the crate has to be rebuilt.
`rustix` is a dependency of `terminal_size`. `terminal_size` is a dependency of `clap_builder`. `clap_builder` is a dependency of `clap`. We directly depend on `clap` for the CLI argument passing.
=> Bump `rustix`, the dependency of a dependency of `clap`

apps/hash-graph/Cargo.lock, apps/hash-graph/bin/cli/Cargo.toml, apps/hash-graph/bin/cli/src/subcommand/snapshot.rs, apps/hash-graph/lib/graph/Cargo.toml, apps/hash-graph/lib/graph/src/shared/identifier/knowledge.rs, apps/hash-graph/lib/graph/src/snapshot.rs, apps/hash-graph/lib/graph/src/snapshot/codec.rs, apps/hash-graph/lib/graph/src/snapshot/error.rs
Currently, we rely on channels, which is suboptimal. This replaces the channels by a framed read/write by providing a very basic codec for JSON Lines. This is a direct follow-up of #2355.
- #2355 
- #2355 
- Implement `codec::JsonLines`, a thin wrapper around `serde_json`
- Replace the implementation of channels with framed reads/writes
This PR:
=> Use a codec to read/write JSON Lines

apps/hash-graph/docker/Dockerfile
We encounter weird issues fetching the old revision in CI. This is an attempt to fix this issue.
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1680780643701939) _(internal)_
This PR:
=> Set cache sharing of rust docker builds to `locked`

.github/pull_request_template.md
This is very small change, but changes the emoji of the "has this modified a publishable library" from 🔍 to 🚀. I have been creating quite a few PRs today, and the fact that both sections "What does this change?" and "Has this modified a publishable library?" has somewhat annoyed me because I often orient myself on these emoji when scanning a PR^^ (This is also why I am using 📋 for todos and ❓ for open questions and ❗ for problems, etc. if the existing sections are not sufficient).
I thought a 🚀 might be more suitable for the section, as I've seen it used for releases/deployments. As an alternative, we could also use 🚢  (as in [_ship it_](https://www.youtube.com/watch?v=82ANkjVEpYk)), which might also work.
This PR:
=> change emoji in PR template

libs/error-stack/Cargo.toml
Externally, the `.config/lints.toml` cannot be used.
Please note, that this PR is from a fork of the repository to test external contributions.
=> Exclude `.config/lints.toml` from publishing

.github/CONTRIBUTING.md
We require the CI to pass but as far as I can see we never state how to apply automatic fixes. Ideally, we want a CI job, which can be run manually.
This PR:
=> Add guidance on how to apply `yarn fix` in `CONTRIBUTING.md`

libs/deer/src/impls/core.rs, libs/deer/src/impls/core/cmp.rs, libs/deer/tests/test_impls_core_cmp.rs
Implements `Deserialize` for:
* `core::cmp::Reverse` (taken from #1875)
* `core::cmp::Ordering` (new, not included in `serde`)
* #1875 
* #1700 
This PR:
=> `deer`: implement `Deserialize` for `core::cmp`

libs/deer/src/impls/core.rs, libs/deer/src/impls/core/option.rs, libs/deer/tests/test_impls_core_option.rs
Implements `Deserialize` for:
* `core::option::Option`
Taken from #1875 
The current schema is problematic; it cannot accurately represent `oneOf`, and two different proposals to solve this are available as a prototype.
* #1875 
* #1700 
This PR:
=> `deer`: implement `Deserialize` for `core::option`

libs/deer/src/impls/core.rs, libs/deer/src/impls/core/mem.rs, libs/deer/tests/test_impls_core_mem.rs
Implements `Deserialize` for:
* `core::mem::ManuallyDrop`
taken from #1875 
* #1875 
* #1700 
This PR:
=> `deer`: implement `Deserialize` for `core::mem`

.github/workflows/dispatch-fix.yml, README.md
This adds a workflow which is dispatchable and should be able to fix any auto-fixable lints (like prettier).
- [GitHub Actions documentation](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow)
- [checkout action readme](https://github.com/actions/checkout#push-a-commit-using-the-built-in-token)
This PR:
I'm currently not able to test it as
> To trigger the `workflow_dispatch` event, **your workflow must be in the default branch**
Test this workflow when this PR has been merged
=> Add a dispatchable workflow to run `yarn fix`

.github/renovate.json
For some reason renovated auto-detects semantic commits for this repository, most probably due to #2388, however, we *don't* use semantic commits.
- #1481 
- #2405
- #2406
=> Disable semantic commits for renovate

apps/hash-graph/bin/cli/src/subcommand/server.rs
Currently, we format the socket address manually. It's easier to implement `Display` and implement `TryInto` for it, so reusing it will become easier.
This PR:
=> Simplify usage of `ApiAddress`

apps/hash-external-services/docker-compose.yml, apps/hash-graph/docker/Dockerfile
https://github.com/hashintel/hash/pull/2374 moved the health check for the server to the dockerfile. Unfortunately I forgot, that this is not possible as the healthcheck specified in the Dockerfile should not be tied to a specific subcommand and we don't have a general `--healthcheck` flag in the server, which we could use.
- https://github.com/hashintel/hash/pull/2374
This PR:
=> Move back `HEALTHCHECK` to docker compose file

tests/hash-playwright/tests/entity-creation.spec.ts, tests/hash-playwright/tests/entity-type-creation.spec.ts, tests/hash-playwright/tests/guest-user.spec.ts, tests/hash-playwright/tests/page-creation.spec.ts, tests/hash-playwright/tests/shared/login-using-temp-form.ts, tests/hash-playwright/tests/shared/reset-db.ts
We have a Playwright test suite that has been mostly failing since changes to the backend. It's not a required CI check but it's distracting to see it fail.
The goal of the PR is to make the workflow pass consistently.
It does this by:
1. Skipping the 2 tests that weren't already skipped – bits of these work, but bits of them rely on pages which use currently very slow API endpoints, which are known to be slow since the graph API traversal logic was simplified pending upcoming optimization work (next ~month). Some also rely on being able to reset the db between tests, which is being implemented this week.
2. Re-enabling most of one test that was previously skipped but can pass (it just checks that creating a draft entity type works)
- [Asana …
=> Skip failing Playwright tests pending future fixes

libs/deer/desert/src/array.rs, libs/deer/desert/src/object.rs, libs/deer/json/src/lib.rs, libs/deer/src/lib.rs
This PR adds `ArrayAccess::context()` and `ObjectAccess::context()` which roughly are equivalent to `DeserializeSeed` in `serde`. This enables inner methods of `ArrayAccess` and `ObjectAccess` to modify/access the context, but also call other deserializers (like `NoneDeserializer`)
* need was discovered in #2437 
This PR:
=> `deer`: add `*Access::context()`

blocks/heading/package.json
We use the `name` field in `package.json["blockprotocol"]` to determine which API key to use when publishing blocks.
The `heading` block was missing the namespace prefix, which meant that automatic publishing was failing (see [here](https://github.com/hashintel/hash/actions/runs/4731993373/jobs/8397662623#step:5:15)).
This PR:
The `chart` block publishing is failing because it is published under a different namespace, for which we haven't entered an API key, but since it's outdated this is less important to address.
I will re-run publishing for the `heading` block.
1.  Look at a few `package.json`s for other blocks and see that this PR makes them consistent.
=> Correct Heading block name

apps/hashdotdev/src/components/blog-post.tsx
🌟 What is the purpose of this PR?
---
The aim of this pull request is to change title of hash.dev/blog/[post] pages. It should read "[post name] - HASH Developer Blog".
🔗  Related links
---
- [Github](https://github.com/hashintel/hash/issues/2439)
❓How to test this?
---
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.
=> [H-12] Change title of hash.dev/blog/[post] pages

apps/hashdotdev/src/components/mdx-talk-slide.tsx, apps/hashdotdev/src/util/mdx-util.ts
🌟 What is the purpose of this PR?
---
The aim of this pull request is to resolve the issue of the presentation slides not appearing until they have loaded in completely, by implementing a consistent approach that uses blurhashes, which is consistent with the existing approach of using blurhashes on other Images which improves the loading experience for users.
🔗  Related links
---
- [Github](https://github.com/hashintel/hash/issues/2323)
❓How to test this?
---
https://www.loom.com/share/b98bfd6e2bcb41418658c8e949ffc16e
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.
=> [H-4] Add blurhash to hash.dev slide component

apps/hash-graph/docker/Dockerfile
It's possible to better utilize the docker-layer-caching by using `turbo prune`. This command will remove unneeded clutter and write it into `out/`. Based on this the dependencies can be cached if the package.json, yarn.lock, and turbo.json did not change.
- [Turbo documentation: Deploying with Docker](https://turbo.build/repo/docs/handbook/deploying-with-docker)
- #2419 
- #2426
This PR:
=> Use `turbo` in `Dockerfile` to prune unneeded content

.github/workflows/ci.yml
Similar to the Rust CI, this cancels CI runs on previous commits in the same PR
This PR:
=> Avoid multiple CI runs for same job in same PR

.github/workflows/ci.yml, .github/workflows/rust.yml
The Rust workflow may cancel the CI workflow with the recent changes. This will fix it
Change the concurrency group:
- https://stackoverflow.com/a/72408109
The important change is to add `github.workflow`. Replacing `head_ref` with the PR number, however, makes it easier to read.
This PR:
=> Fix Rust workflow may cancel CI workflow

.github/actions/build-docker-images/action.yml, .github/actions/load-docker-images/action.yml, .github/scripts/rust/setup.py, .github/workflows/ci.yml, .github/workflows/rust.yml, apps/hash-graph/.justfile
As mentioned in #2428, this uses caching for the `hash-graph` docker image, as this is currently one of the slowest part in CI.
This PR immensely speeds up CI times.
- [Asana task](https://app.asana.com/0/1204260760205594/1204367340604860/f) _(internal)_
- #2419 
- #2426 
- #2427 
- #2428
- Add a composite action to build the `hash-graph` image
- Add a composite action to load the image back into Docker
- Add a configuration to `setup.py` to filter by `hash-graph`
- Use the composite action to build the image in the `CI` and `Rust` workflows
- Use the cached artifact to speed up external services
This PR:
=> Use caching for hash-graph docker image

apps/hash-graph/lib/graph/src/store/error.rs, apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
When running a test with a test data batch (inserted via the `snapshot` endpoint), we want to be able to remove the test data and insert a new batch afterward. This implements deletion, which is gated behind the `--cfg` flag to avoid having it available in a production environment.
- [Asana task](https://app.asana.com/0/1204260760205594/1204407146528683/f) _(internal)_
Implement deletion for
- entities
- entity-types
- property-types
- data-types
- accounts
This PR:
=> Support deletion of test-data

apps/hash-frontend/turbo.json
The `outputs` field in `turbo.json` was not set correctly, so turbo did not output the directory but a single file instead.
This PR:
=> Fix output for `@apps/hash-frontend` in `turbo.json`

.github/workflows/remove-obsolete-caches.yml
Caches for branches, which has been deleted as a PR was closed only fills the cache storage but don't have any other purpose. This GH Action removes caches after a PR has been closed.
The code was taken from the official GitHub documentation: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
This PR:
=> Remove caches when PR was closed

libs/deer/src/impls/core/integral.rs, libs/deer/src/value.rs, libs/deer/tests/test_impls_core_integral.rs, libs/deer/tests/test_value.rs
This is the first in a (probably) three-step PR chain.
This PR resolves one of the long overdue TODOs in the code and makes the deserializer of all numbers less punishing. The end goal is to remove the `usize` and `isize` types in our data scheme.
This means that everything is more in line with `serde` and that a `u32` can be deserialized using `U32Deserializer` into `u64`.
Note: We determine the size of `*size` using `target_pointer_width`, `serde` internally handles all `usize` as `u64`. We correctly determine the size of the target and set conversion functions appropriately this means that conversions would truncate w/ `serde` on 16-bit or 32-bit systems, while 🦌 correctly errors out.
This PR:
=> `deer`:  improve how integrals are handled

.changeset/config.json, .changeset/empty-trainers-think.md, libs/@hashintel/type-editor/src/entity-type-editor/shared/multiple-values-cell.tsx
This PR fixes a visual bug in the entity type editor where the "add a property" button appears on top of the "Allow multiple" menu.
- [Asana task](https://app.asana.com/0/1204274556967336/1204521839453643/f) _(internal)_
The "add a property" button table cell has `zIndex: theme.zIndex.drawer + 1` so in order for the "allow multiple" menu to appear on top its zIndex has ben set to `theme.zIndex.drawer + 2`
This PR:
Before:
After:
=> Prevent 'add a property' button from appearing over the 'allow multiple' menu

apps/hash-graph/lib/graph/src/api/rest.rs
https://github.com/hashintel/hash/pull/1844 added four lines to the `modify` method, which triggers the clippy lint. Generally, the lint is reasonable, but in this case, having it all in one function is more readable as the builders of `utoipa` are pretty verbose and boiler platy
This PR:
=> Ignore `clippy::too-many-lines` on `FilterSchemaAddon`

libs/error-stack/src/fmt.rs, libs/error-stack/src/fmt/charset.rs, libs/error-stack/src/fmt/color.rs, libs/error-stack/src/fmt/hook.rs, libs/error-stack/src/hook.rs, libs/error-stack/src/hook/context.rs, libs/error-stack/src/lib.rs, libs/error-stack/src/report.rs
The line-number in doc-test changed in a recent nightly compiler version so the lines do not align on `1.65` and the current nightly compiler. This only runs the snapshot tests on a nightly toolchain. There are still plenty of tests, which are covered on the stable toolchain.
- #2521 
- Only run doc-snapshot tests on nightly
This PR:
=> Ignore doc-snapshot outputs on non-nightly compiler

apps/hash-graph/lib/graph/src/snapshot.rs, apps/hash-graph/lib/graph/src/snapshot/error.rs, apps/hash-graph/lib/graph/src/snapshot/restore/channel.rs
Currently, we allow specifying global metadata in a snapshot but don't really use them besides checking the version. This PR enhances the restoring logic to track the snapshot metadata and fail if it's not present.
- [Asana task](https://app.asana.com/0/1204274556967336/1204549651666217/f) _(internal)_
- Adds an unbounded channel to track metadata. There is no real point in making it bounded as it's expected to have small amounts of data (usually exactly 1)
- Collect metadata values and ensures, that at least one entry exists
This PR:
- The backend integration tests are expected to fail in a follow-up PR if this data is missing
- Try to restore a snapshot with an empty snapshot
```
Could not restore snapshot, error: The snapshot does not …
```
=> Track snapshot metadata and fail restoring if missing

apps/hash-external-services/docker-compose.test.yml, apps/hash-external-services/docker-compose.yml
It's not possible to run the graph test server from `yarn external-services` as the docker image does not contain the test server. This moves the test server to the test-compose file.
- [Slack thread](https://hashintel.slack.com/archives/C03F7V6DU9M/p1683040225572009) _(internal)_
- Move the `graph-test-server` service without changing it
This PR:
=> Move `graph-test-server` to `docker-compose.test.yml`

apps/hash-graph/lib/graph/src/store/postgres/ontology.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs, apps/hash-graph/lib/graph/src/store/postgres/query.rs, apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs
We currently rely on the `associated_type_bounds` feature flag. This recently changed a little bit so it acts more intuitively (similar to `where` on traits). This addresses the issues and enables us to further update the toolchain to a more recent version.
- https://github.com/hashintel/hash/pull/2520
- Remove associated bound on `PostgresRecord`, it does not have the expected effect anymore (this was previously breaking intellisense in CLion, which is now fixed)
- Add the required links to the desired locations
This PR:
=> Fix associated trait bound for `PostgresRecord`

tests/hash-backend-integration/src/tests/test-server.ts
Currently, snapshots are read into memory before passing them to the test server. This changes the behavior to stream the snapshots.
=> Use a stream instead of reading a snapshot into memory

apps/hash-external-services/docker-compose.prototype.yml, apps/hash-external-services/package.json, apps/hash-external-services/turbo.json, apps/hash/README.md, package.json
This PR adds a `external-services:prototype` task to the monorepo that is separate from the rest of the HASH dev infrastructure. For now the prototype external services compose contains a VectorDB that is easily set up and operate locally (https://qdrant.tech/)
- Adds new root package.json script
- Adds new docker compose
This PR:
More of an open question, do we want to merge this into main?
To develop prototypes
- None required
1.  Checkout the branch
1.  Run `yarn external-services:prototype up`. This acts similarly to the other external service scripts in that they allow 
1.  Confirm that qdrant is running by going to http://localhost:6333/telemetry
=> Add Qdrant to prototype Docker compose

apps/intellij-plugin/build.gradle.kts
Previously `until-version` was specified implicitly, leading to the case where build invocations on different machines would lead to different `until-version` versions, which would lead to some being unable to use the plugin.
This fixes it by explicitly unsetting the value, through `untilBuild.convention()`
This PR:
=> `intellij-plugin`: explicitely unset `until-version`

apps/hashdotdev/src/pages/blog/[...blog-slug].page.tsx, apps/hashdotdev/src/pages/blog/index.page.tsx
🌟 What is the purpose of this PR?
---
The aim of this pull request is to enhance the presentation of author names on the `hash.dev/blog` website by introducing a more suitable formatting approach. Currently, the author names are separated by an "&" symbol. However, the desired formatting is to use commas between all author names except for the last two, which should be separated by " &".
🔗  Related links
---
- [Github](https://github.com/hashintel/hash/issues/2466)
❓How to test this?
---
**Before**
**After**
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.
=> [H-13] hash.dev: appropriately comma separate author names when articles have 3 or more

apps/hash-graph/lib/graph/src/api/rest.rs, apps/hash-graph/lib/graph/src/api/rest/api_resource.rs, apps/hash-graph/lib/graph/src/api/rest/data_type.rs, apps/hash-graph/lib/graph/src/api/rest/entity_type.rs, apps/hash-graph/lib/graph/src/api/rest/property_type.rs, apps/hash-graph/lib/graph/src/store.rs, apps/hash-graph/lib/graph/src/store/fetcher.rs
The type fetcher currently is an implementation detail on the store and is opaque to the Rest API. This PR conditionally makes the type fetcher available to the REST API.
- [Asana task](https://app.asana.com/0/1204315348455207/1204596705932067/f) _(internal)_
- Add a `TypeFetcher` trait and implement it on `FetchingStore` (empty body)
- Add a `RestApiStore` trait which conditionally includes the `TypeFetcher` trait as a requirement. This way it's possible to specify a set of conditions for the REST API.
- Use the `RestApiStore` as bound for creation methods for ontology types
This PR:
- Implement the logic on `TypeFetcher`
- Use the provided logic to allow insertion of external types
=> Make the type fetcher available to the Rest API through the `FetchingStore`

libs/deer/desert/src/deserializer.rs, libs/deer/src/error/type.rs, libs/deer/src/helpers.rs, libs/deer/src/lib.rs, libs/deer/src/schema.rs, libs/deer/tests/test_enum_visitor.rs
Mostly cleanup and implements various helpers for deserializer(s).
This includes:
* `ExpectNone` (to be used when deserializing unit enum variants)
* `EnumObjectVisitor` generalizes over the `{"Variant": "Value"}` deserialize calls by using `.into_bound(1)`, unifying even more of the API surface (which is good)
* `is_human_readable`, used for deserializers to decide which format to use, has equivalent in `serde`
Under consideration:
* `deserialize_ignored_any` (opinions welcome!) opts into efficient data discarding, also exists in serde; do we need it? This**might** be useful for `ExpectNone` as we currently use `deserialize_any`.
> There are some new TODOs scattered around, because I currently lack a good way to communicate those otherwise _virtual fingerguns_
* …
=> `deer`: implement various helpers

apps/hash-graph/lib/graph/src/store/fetcher.rs
The `FetchingStore` currently only resolves referenced types but cannot resolve a specific type on request. This adds an implementation via the `TypeFetcher` trait interface to add this functionality.
- [Asana task](https://app.asana.com/0/1204315348455207/1204596705932067/f) _(internal)_
- https://github.com/hashintel/hash/pull/2573
- Add `FetchBehavior` enumeration to reuse existing function to either resolve all types or only the references
- Make `insert_external_types_by_reference` aware of the conflict and fetching behavior
- Implement the function on `TypeFetcher`
This PR:
- Use the provided logic to allow the insertion of external types
=> Implement logic on `TypeFetcher` to load provided URL

apps/hash-graph/lib/graph/src/api/rest.rs
To avoid the same code for all ontology-type creation endpoints this adds a function to `RestApiStore` to call the `TypeFetcher`
- [Asana task](https://app.asana.com/0/1204315348455207/1204596705932067/f) _(internal)_
- https://github.com/hashintel/hash/pull/2573
- https://github.com/hashintel/hash/pull/2574
Add a function to:
- validate the domain. If the schema reference matches the domain regex it's not an external type and the function fails
- Call the underlying store and emit a `Conflict` error if the type already exists
This PR:
- Use the provided logic to allow the insertion of external types
=> Provide conversion on `RestApiStore` to simplify interfacing with the `TypeFetcher`

.github/actions/install-rust-toolchain/action.yml, apps/hash-graph/.justfile, apps/hash-graph/lib/graph/src/api/rest/data_type.rs, apps/hash-graph/lib/graph/src/api/rest/entity_type.rs, apps/hash-graph/lib/graph/src/api/rest/property_type.rs, apps/hash-graph/openapi/openapi.json, apps/hash-graph/tests/rest-test.http
This changes the endpoints to allow to either pass an ontology-type schema URI (without the owner id) or to pass the schema (with the owner id). If in the former case a type is passed which matches the current domain, it will fail, otherwise the type will be fetched and inserted as external type.
- [Asana task](https://app.asana.com/0/1204315348455207/1204596705932067/f) _(internal)_
- https://github.com/hashintel/hash/pull/2573
- https://github.com/hashintel/hash/pull/2574
- https://github.com/hashintel/hash/pull/2575
- Change the creation request parameters
- Adjust the OpenAPI spec (all changes are completely type safe)
- Adjust the `.justfile` as the `type-fetcher` feature has to be enabled
This PR:
- Use these changes in the `hash-api` …
=> Adjust ontology creation methods to load external types

apps/hash-graph/Cargo.lock, apps/hash-graph/bench/Cargo.toml, apps/hash-graph/bin/cli/Cargo.toml, apps/hash-graph/lib/graph/Cargo.toml, apps/hash-graph/lib/type-fetcher/Cargo.toml, apps/hash-graph/tests/integration/Cargo.toml
The `type-system` crate was updated and to avoid falling out of sync this bumps the version.
- https://github.com/blockprotocol/blockprotocol/pull/1291
This PR:
=> Bump `type-system` crate to `cdde49`

apps/hash-api/src/graph/ontology/primitive/data-type.ts, apps/hash-api/src/graph/ontology/primitive/entity-type.ts, apps/hash-api/src/graph/ontology/primitive/property-type.ts
In a previous PR I used the wrong way to read `$FRONTEND_URL`. This implies, that instead of failing with an error immediately the API tries to load an ontology type instead. This will fail if the ontology type is not eternal.
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1684868701217229) _(internal)_
This PR:
=> Correctly use the `FRONTEND_URL` variable in the `hash-api` package

apps/hash-api/src/graph/ontology/primitive/data-type.ts, apps/hash-api/src/graph/ontology/primitive/entity-type.ts, apps/hash-api/src/graph/ontology/primitive/property-type.ts
I accidentally changed the behavior of the GQL resolvers to error if a type does not exist.
- [Slack thread 1](https://hashintel.slack.com/archives/C022217GAHF/p1684912726686829)
- [Slack thread 2](https://hashintel.slack.com/archives/C022217GAHF/p1685010273602719)
=> Return an empty subgraph if ontology type queried by its ID does not exist

apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/traversal_context.rs
The traversal logic is currently in the process of being optimized. The first goal in order to make optimization possible the reading of vertices is going to be deferred to the end. With this, it's possible to only read the edge information while traversing instead of reading the whole record.
- [Asana task](https://app.asana.com/0/1200211978612931/1204117845662853/f) _(internal)_
- Store entity edition ids and ontology vertex ids in `TraversalContext`
- Create a new traversal context when starting a traversal
- Read vertices after traversing is finished
This PR:
- This will currently double the amount of queries being done to the graph as each record is read one by one. This will be addressed in a direct follow-up.
As mentioned above, the …
=> Move reading vertices until after traversal is finished

apps/hash-graph/lib/graph/src/shared/identifier/knowledge.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/query/condition.rs, apps/hash-graph/lib/graph/src/store/postgres/traversal_context.rs, apps/hash-graph/lib/graph/src/store/query.rs, apps/hash-graph/lib/graph/src/store/query/filter.rs, apps/hash-graph/lib/graph/src/subgraph.rs
#2612 moved the lookup of vertices to until after the traversal. To avoid reading every every vertex one-by-one this changes the implementation to read all at the same time.
- [Asana task](https://app.asana.com/0/1204315348455207/1204117845662866/f) _(internal)_
- #2612
- [Add a basic batch-filter for structural queries](https://github.com/hashintel/hash/commit/bddd63a3fb34ea067ac3c56cb65b522dd76c0c26)
- [Use batched reading for vertices](https://github.com/hashintel/hash/commit/4e99735e36f16d658d55881708c79f93ffc9001d)
This PR:
- It's not easy to filter by two distinct parameter lists at once and, in addition, `ToSql` neither implemented for `BaseUrl`, nor for `VersionedUrl`. Thus, this converts the parameters to strings and does a string …
=> Add a basic batch-filter for structural queries

apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs, apps/hash-graph/lib/graph/src/store/postgres/query.rs
This is the first PR which actively improves performance on the traversal logic. This starts by batching together edge lookups for ontology-to-ontology edges based on the edge kind.
Note, that I have not precisely measured the performance improvement. In general the number of queries is reduced which directly impacts performance. A summary will be posted in a follow-up PR.
- [Asana task](https://app.asana.com/0/1204315348455207/1204117847656663/f) _(internal)_
- #2612
- #2614
- Add function to read ontology-to-ontology edges based on a reference table
- Use that function to read as many ontology edges withing the same Query as possible
This PR:
Do the same for
- knowledge -> ontology (different due to temporal axes)
- kowledge -> knowledge …
=> Support batched reading for ontology-ontology edges

infra/terraform/hash/networking/main.tf
As a follow up to #2618 this PR removes the `moved` blocks that were necessary for the initial refactor. These are now redundant since the TF apply was successful https://github.com/hashintel/hash/actions/runs/5132276830/jobs/9233363476 
Running `terraform plan --var-file prod-usea1.tfvars  --refresh=false` from the `/infra/terraform/hash` path locally should still result in zero changes.
=> Remove `moved` statements from refactored infra

apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity/read.rs
Similar to #2625 this will add the batched traversal for knowledge-to-knowledge edges.
- [Asana task](https://app.asana.com/0/1204315348455207/1204117847656663/f) _(internal)_
- #2612
- #2614
- #2615
- #2625
- Add function to read knowledge-to-ontology edges based on a reference table
- Use that function to read as many shared edges within the same Query as possible
This PR:
- Re-enable benchmarks
- Run benchmarks
- Directly:
- The HASH Graph API Rest-tests
- The BE Integration test suite
- Indirectly:
- Every other test which depends on the Graph
Make sure the subgraph looks exactly as before
=> Support batched reading for entity-entity edges

apps/hash-graph/lib/graph/src/ontology/data_type.rs, apps/hash-graph/lib/graph/src/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity.rs, apps/hash-graph/lib/graph/src/store/postgres/knowledge/entity/read.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/ontology_id.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/read.rs, apps/hash-graph/lib/graph/src/store/postgres/query/compile.rs, apps/hash-graph/lib/graph/src/store/postgres/traversal_context.rs, apps/hash-graph/lib/graph/src/store/query.rs, apps/hash-graph/lib/graph/src/store/query/filter.rs, apps/hash-graph/lib/graph/src/subgraph/edges/kind.rs
In #2614 `ParameterList::VersionedUrl` was introduced which requires allocating a `String` per lookup. The allocation and full string comparison in Postgres can be avoided.
This generally slightly improves the performance by 5-10%.
- [Asana task](https://app.asana.com/0/1204610208832639/1204692442679557/f) _(internal)_
- #2625
- #2626
- #2627 
- #2628
- Add function to read the `OntologyId` using a `Filter`
- Change the ontology-edge-traversal to use the ontology id instead of a full string comparison
- Change the traversal entry to only run if there is a resolve depth > 0 (This slightly improves the performance by ~2% for queries with a resolve depths of 0)
This PR:
- Directly:
- The HASH Graph API Rest-tests
- The BE Integration test suite …
=> Use `OntologyId` instead of allocating a `VersionedUri` when traversing edges

apps/hash-graph/lib/graph/src/store/postgres/ontology/data_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/entity_type.rs, apps/hash-graph/lib/graph/src/store/postgres/ontology/property_type.rs
#2629 introduced a bug by not adding the ontology id roots to the traversal context. This fixes the issue
- #2629
- [Slack thread](https://hashintel.slack.com/archives/C022217GAHF/p1685715544856149) _(internal)_
- Add the roots to the traversal context
Sadly, there is no `TryStreamExt::try_flat_map` function, so I have to use `map_ok` followed by a `try_flatten`.
=> Fix roots not being added to the traversal context

apps/hash-graph/Cargo.toml, apps/hash-graph/lib/graph/src/shared/identifier/time/interval.rs
Since recently, `clippy` will warn if the resolver is not set for the workspace.
Crates with the edition set to `2021` will default to `resolver = "2"`, but virtual workspaces - as they don't specify an addition - defaults to `resolver = "1"`. To avoid this issue, this sets the `workspace.resolver` variable.
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
This PR:
=> Avoid warning on resolver not specified

apps/hash-graph/lib/graph/src/store/postgres.rs, apps/hash-graph/postgres_migrations/V8__ontology_create_functions.sql
When loading multiple external types at the same time which uses the same underlying ontology types one connection will fail to insert that datatype.
To avoid this we need to provide the on-conflict behavior to Postgres.
- [Asana task](https://app.asana.com/0/1204727813960182/1204871439592713/f) _(internal)_
- Remove old ontology creation functions (required as the parameters change and we don't want to overload the functions but replace then(
- Add three new functions:
- Create ontology id from a BaseURL and a version, taking into account if the type is external or failure is allowed
- Create metadata (owned + external), calls the above function and insert the metadata afterwards
This PR:
=> Move logic to ignore conflicting ontology type to Postgres

.github/workflows/ci.yml, apps/hash-ai-worker-py/turbo.json
We have a caching setup for `.venv`, however, it does not seems to work properly with different entries for the same output. At least [a recent Action failed due to this](https://github.com/hashintel/hash/actions/runs/5422658218/jobs/9859681702?pr=2699). To avoid spending much time on figuring out this, this PR removes caching of `.venv`.
- #2699
This PR:
=> Disable caching of `.venv`

infra/terraform/hash/main.tf, infra/terraform/modules/container_registry/main.tf, infra/terraform/modules/temporal/main.tf
🌟 What is the purpose of this PR?
https://github.com/hashintel/hash/pull/2713 introduced the Terraform module for Temporal. This will add the module to the `hash` module, which implies the creation of the required infrastructure to use it.
- https://github.com/hashintel/hash/pull/2713
- Add the `terraform` module to hash
- Set the desired tasks count in `temporal` to `0` to avoid it being hosted
- Drive-by: Fix a typo
- Drive-by: Use proper variable substitution
This PR:
This PR is required to do this as a separated step before doing further work as this will create the ECR repositories for the temporal images, which have to be uploaded separately.
Add RDS instance to be used instead of the Postgres Docker container
1.  Checkout the branch …
=> Use Temporal Terraform module in `hash`

apps/hash-ai-worker-py/app/__main__.py, apps/hash-ai-worker-py/app/encoding.py, apps/hash-ai-worker-py/app/workflows.py
Temporal suggests to use a data encoder to convert between Pydantic and JSON objects. This avoids unnecessary calls in workflows and allows Pydantic models in workflow signatures.
- Part of [this Asana task](https://app.asana.com/0/1204727813960182/1204904869169432/f) _(internal)_
- https://github.com/hashintel/hash/pull/2693
- https://github.com/hashintel/hash/pull/2695
- https://github.com/hashintel/hash/pull/2696 (CI will fail until merged)
- https://github.com/hashintel/hash/pull/2699
- https://github.com/hashintel/hash/pull/2702 (CI is likely to fail until merged)
- Add `encoding` module
- Use the added encoder in the worker
- Remove unneeded calls and make sure the workflow will fail on wrong parameters
This PR:
This is currently not …
=> Implement data encoder for Pydantic

infra/terraform/hash/main.tf, infra/terraform/hash/outputs.tf, infra/terraform/hash/postgres_roles/postgres_roles.tf, infra/terraform/hash/postgres_roles/variables.tf, infra/terraform/modules/temporal/main.tf, infra/terraform/modules/temporal/task_definitions.tf, infra/terraform/modules/temporal/variables.tf
Currently, we use a Docker container to run Postgres. This changes the Postgres instance to live in RDS instead
- Setup Postgres rules for `temporal` and `temporal_visibility`.
- Associate the Temporal service the RDS instance and remove old docker container
- For the purpose of easier and more secure testing I limited the Temporal service to the CIDR block
This PR:
Probably
- Setup authentication
- Setup visibility service
- Address TODOs in Temporal TF code
=> H-33: Use RDS for Temporal

apps/hash-graph/lib/graph/src/api/rest.rs, apps/hash-graph/lib/graph/src/api/rest/utoipa_typedef.rs, apps/hash-graph/openapi/openapi.json, libs/@local/hash-graph-client/openapitools.json
While trying to generate an OpenAPI client with a new version of openapi-generator I found that the OpenAPI spec is malformed (in 6.2.0 of the generator, some critical dependencies got upgraded). Basically we exploited some bugs in the previous versions to generate the typescript client 😅 
This included:
* `components.schemas.FilterExpression` referencing `#/components/schemas/Any` (which did not exist)
* `components.schemas.CreatePropertyTypeRequest`, referencing `#/components/schemas/property_type` (which did not exist)
* `components.schemas.CreateDataTypeRequest`, referencing `#/components/schemas/data_type` (which did not exist)
* `components.schemas.CreateEntityTypeRequest`, referencing `#/components/schemas/entity_type` (which did not exist)
Thanks to @TimDiekmann for guidance as to …
=> H-52: `graph`: Fix OpenAPI spec inconsistencies

infra/terraform/hash/temporal/main.tf
`arm64` is cheaper and often less resource intensive.
This PR:
=> H-79: Switch to `linux/arm64` ECS containers

apps/hash-ai-worker-py/app/__main__.py, apps/hash-ai-worker-ts/src/main.ts, apps/hash-ai-worker-ts/src/workflows.ts, apps/hash-external-services/docker-compose.yml, apps/hash-external-services/temporal/setup.sh
We don't want a `default` namespace around in the hosted version of Temporal so this sets the "default" namespace to `HASH`. This also adjusts the worker and the Dockerfiles to use the new namespaces. As a drive-by this adds a very simple workflow for testing purposes.
This PR:
=> H-80: Configure namespaces in hosted Temporal instance

infra/terraform/hash/temporal/main.tf
We expected that it's not needed but it is.
This PR:
=> H-81: Fix `egress` for Postgres in Temporal missing

apps/hash-api/package.json, apps/hash-external-services/kratos/Dockerfile, apps/hash-external-services/kratos/kratos.dev.yml, apps/hash-external-services/kratos/kratos.prod.yml, apps/hash-external-services/kratos/templates/README.md, yarn.lock
As part of investigating performance of the deployed app, I noticed that calls to Ory's `whoami` can be very slow (sometimes 6-7s). 
The `0.13` release of Ory Kratos [specifically mentions](https://github.com/ory/kratos/releases/tag/v0.13.0) optimising `whoami` calls, so I'm upgrading to see what benefit this brings.
This PR:
- If this does not solve the `whoami` performance issues, my next target will be looking at [the post-registration hook](https://github.com/hashintel/hash/blob/main/apps/hash-external-services/kratos/hooks/after.registration.jsonnet) in case that is the bottleneck somehow.
1.  Checkout the branch
1. Rebuild `external-services` fully (i.e. get rid of the underlying Ory Kratos image at least)
1. Check login / logout still …
=> H-87: Upgrade Ory Kratos

apps/hash-ai-worker-py/app/__main__.py, apps/hash-ai-worker-py/docker/Dockerfile, apps/hash-ai-worker-ts/docker/Dockerfile, apps/hash-graph/.gitignore, apps/hash-graph/lib/graph/src/logging/args.rs, infra/terraform/hash/hash_application/ai_worker.tf, infra/terraform/hash/hash_application/variables.tf, infra/terraform/hash/main.tf, infra/terraform/hash/temporal/main.tf, infra/terraform/hash/temporal/output.tf, infra/terraform/hash/temporal/task_definitions.tf, infra/terraform/modules/temporal_worker/main.tf, infra/terraform/modules/temporal_worker/task_definitions.tf, infra/terraform/modules/temporal_worker/variables.tf
Adds the worker configurations to the TF config.
- Drive-by: Fix `apps/hash-graph/log/*` was part of the docker context (this were > 5 GB for me locally)
- Add the Worker configuration to TF
- Fix TS Worker: `curl` was missing for healthcheck
- Fix PY Worker: healthcheck was checking for IPv4 while the server listened to IPv6
This PR:
=> H-50: Provide example worker hosted on ECS

apps/hash-api/package.json, apps/hash-api/src/telemetry/rudderstack.ts, infra/terraform/hash/main.tf, yarn.lock
Adds an API interface to send events to the RudderStack API
- Add a small helper-class to create events. The class will take care of setting up the RudderStack key and sending the actual data to the API.
- Add the `HASH_API_RUDDERSTACK_KEY` to the deployment
- It does ***not*** add locations where the API is called, this is subject to a future Pull Request (see H-97)
This PR:
=> H-38: Setup RudderStack API for `hash-api`

.github/actions/docker-build-push/action.yml, infra/terraform/hash/hash_application/main.tf
`linux/arm64` is cheaper than `linux/amd64` (~25% for both, CPU and RAM). Also, in my experience, it's less resource intensive.
As we all run ARM chips ourselves this also speeds up building the deployed images, which makes DX faster as well. (Building the images for me went down from ~15 minutes to ~1 minute.
Initially this was planned as a separated task but I did this as a drive-by for H-125 so I will just open a PR to land the changes.
=> IN-12: Change containers to linux/arm64
